const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });
const recipesToMigrate = [
  
  {
  title: "Vegetable Spring Rolls",
  image: "veg-spring-roll.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "12 spring roll wrappers",
    "2 cups cabbage, shredded",
    "1 carrot, julienned",
    "1 bell pepper, julienned",
    "100g bean sprouts",
    "2 tbsp soy sauce",
    "1 tsp ginger, grated",
    "2 cloves garlic, minced",
    "1 tbsp cornstarch",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Mix all vegetables in a bowl with soy sauce, ginger, and garlic.",
    "In a small bowl, mix cornstarch with 2 tbsp water to make paste.",
    "Place spring roll wrapper in diamond position.",
    "Add filling near bottom corner, roll halfway, fold sides, roll to top.",
    "Seal edge with cornstarch paste.",
    "Heat oil in deep pan to 350°F (175°C).",
    "Fry spring rolls in batches until golden brown (4-5 minutes).",
    "Drain on paper towels and serve hot with sweet chili sauce."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Crispy golden spring rolls filled with fresh vegetables like cabbage, carrots, and bell peppers. A perfect snack with sweet chili sauce.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "standard",
  costPerServing: 25,
  baseServings: 4,
  calories: 200,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "cabbage", "carrot", "bell pepper", "bean sprouts", "soy sauce", "ginger", "garlic", "cornstarch"],
  searchKeywords: ["spring rolls", "veg rolls", "vegetable rolls", "crispy rolls", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Spring Rolls",
image: "spring-rolls.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "12 spring roll wrappers",
    "200g chicken breast, minced",
    "1 cup cabbage, shredded",
    "1 carrot, julienned",
    "2 tbsp soy sauce",
    "1 tsp ginger, grated",
    "2 cloves garlic, minced",
    "1 tbsp oyster sauce",
    "1 tbsp cornstarch",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Marinate chicken with soy sauce, ginger, garlic for 15 minutes.",
    "Cook chicken in pan until no longer pink, let cool.",
    "Mix cooked chicken with vegetables and oyster sauce.",
    "Place wrapper, add filling, roll and seal with cornstarch paste.",
    "Heat oil to 350°F (175°C).",
    "Fry until golden brown (4-5 minutes).",
    "Drain on paper towels.",
    "Serve hot with chili sauce."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Crispy spring rolls filled with seasoned minced chicken and fresh vegetables. A great party snack everyone enjoys.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "standard",
  costPerServing: 35,
  baseServings: 4,
  calories: 240,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "chicken", "cabbage", "carrot", "soy sauce", "ginger", "garlic", "oyster sauce", "cornstarch"],
  searchKeywords: ["spring rolls", "chicken rolls", "crispy rolls", "snack", "chinese snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Shrimp Spring Rolls",
  image: "spring-rolls.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "12 spring roll wrappers",
    "200g shrimp, peeled and chopped",
    "1 cup cabbage, shredded",
    "1 carrot, julienned",
    "2 tbsp fish sauce",
    "1 tsp ginger, grated",
    "2 cloves garlic, minced",
    "1 tbsp cornstarch",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Mix shrimp with fish sauce, ginger, and garlic.",
    "Add vegetables and mix well.",
    "Place wrapper, add filling, roll and seal with cornstarch paste.",
    "Heat oil to 350°F (175°C).",
    "Fry until golden and shrimp is cooked (4-5 minutes).",
    "Drain on paper towels.",
    "Serve hot with sweet chili sauce."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Delicate crispy spring rolls filled with juicy shrimp and fresh vegetables. A seafood lover's favorite.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten", "shellfish"],
  budget: "standard",
  costPerServing: 45,
  baseServings: 4,
  calories: 220,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "shrimp", "cabbage", "carrot", "fish sauce", "ginger", "garlic", "cornstarch"],
  searchKeywords: ["spring rolls", "shrimp rolls", "prawn rolls", "crispy rolls", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Cheese Spring Rolls",
  image: "cheese-spring-roll.jpg",
  cuisine: "Continental",
  ingredientsRaw: [
    "12 spring roll wrappers",
    "200g mozzarella cheese, shredded",
    "100g cream cheese",
    "2 tbsp parsley, chopped",
    "1 tsp black pepper",
    "1 egg, beaten",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Mix mozzarella, cream cheese, parsley, and pepper.",
    "Place wrapper, add cheese mixture in center.",
    "Roll tightly, sealing edges with beaten egg.",
    "Heat oil to 350°F (175°C).",
    "Fry until golden brown (3-4 minutes).",
    "Drain on paper towels.",
    "Serve hot with marinara sauce."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Crispy spring rolls with a warm, melted cheese filling inside. Kids and adults both love these.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten", "dairy"],
  budget: "standard",
  costPerServing: 40,
  baseServings: 4,
  calories: 280,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "mozzarella", "cream cheese", "parsley", "black pepper", "egg"],
  searchKeywords: ["spring rolls", "cheese rolls", "crispy rolls", "snack", "vegetarian snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Tofu Spring Rolls",
  image: "tofu-spring-roll.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "12 spring roll wrappers",
    "200g firm tofu, crumbled",
    "1 cup cabbage, shredded",
    "1 carrot, julienned",
    "2 tbsp soy sauce",
    "1 tsp ginger, grated",
    "1 tbsp sesame oil",
    "1 tbsp cornstarch",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Press tofu to remove excess water, crumble.",
    "Mix tofu with vegetables, soy sauce, ginger, and sesame oil.",
    "Place wrapper, add filling, roll and seal with cornstarch paste.",
    "Heat oil to 350°F (175°C).",
    "Fry until golden brown (4-5 minutes).",
    "Drain on paper towels.",
    "Serve hot with sweet chili sauce."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Vegetarian spring rolls filled with crispy tofu and fresh vegetables, seasoned with soy and sesame.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten", "soy"],
  budget: "standard",
  costPerServing: 30,
  baseServings: 4,
  calories: 210,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "tofu", "cabbage", "carrot", "soy sauce", "ginger", "sesame oil", "cornstarch"],
  searchKeywords: ["spring rolls", "tofu rolls", "vegan rolls", "crispy rolls", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Vegetable Samosa",
  image: "samosa.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "12 samosa wrappers",
    "3 potatoes, boiled and mashed",
    "1/2 cup peas",
    "1 onion, finely chopped",
    "2 green chilies, chopped",
    "1 tsp cumin seeds",
    "1 tsp coriander powder",
    "1/2 tsp garam masala",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Heat oil, add cumin seeds until they crackle.",
    "Add onions and green chilies, sauté until golden.",
    "Add peas and cook for 2 minutes.",
    "Add mashed potatoes and all spices, mix well.",
    "Cook for 5 minutes, let filling cool completely.",
    "Form samosas with wrappers and filling.",
    "Seal edges with water.",
    "Deep fry until golden brown, serve with mint chutney."
  ],
  difficulty: "Medium",
  cookingTime: 45,
  isActive: true,
  isHalal: true,
  description: "Classic crispy samosa with spiced potato and pea filling. A beloved Pakistani snack for tea time.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "standard",
  costPerServing: 15,
  baseServings: 4,
  calories: 180,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "potatoes", "peas", "onion", "green chilies", "cumin seeds", "coriander", "garam masala"],
  searchKeywords: ["samosa", "veg samosa", "potato samosa", "crispy samosa", "pakistani snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Samosa",
  image: "chicken-samosa.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "12 samosa wrappers",
    "200g ground chicken",
    "1 onion, finely chopped",
    "2 green chilies, chopped",
    "1 tsp ginger-garlic paste",
    "1 tsp cumin powder",
    "1 tsp coriander powder",
    "1/2 tsp garam masala",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Heat oil, add cumin seeds, then onions until golden.",
    "Add ginger-garlic paste and green chilies, cook for 1 minute.",
    "Add ground chicken, cook until no longer pink.",
    "Add spices and cook for 5 minutes until dry.",
    "Let filling cool completely.",
    "Fill samosa wrappers with chicken mixture.",
    "Seal edges with water.",
    "Deep fry until golden, serve with chutney."
  ],
  difficulty: "Medium",
  cookingTime: 45,
  isActive: true,
  isHalal: true,
  description: "Flaky, crispy samosa filled with spiced ground chicken. A tasty non-vegetarian snack.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "standard",
  costPerServing: 25,
  baseServings: 4,
  calories: 220,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "chicken", "onion", "green chilies", "ginger garlic", "cumin", "coriander", "garam masala"],
  searchKeywords: ["samosa", "chicken samosa", "crispy samosa", "pakistani snack", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Keema Samosa",
  image: "keema-samosa.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "12 samosa wrappers",
    "250g lamb mince",
    "1 onion, finely chopped",
    "2 green chilies, chopped",
    "1 tsp ginger-garlic paste",
    "1 tsp cumin powder",
    "1 tsp coriander powder",
    "1/2 tsp garam masala",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Heat oil, sauté onions until golden.",
    "Add ginger-garlic paste and green chilies.",
    "Add lamb mince, cook until browned.",
    "Add all spices, cook until meat is dry.",
    "Let filling cool completely.",
    "Fill samosa wrappers with keema mixture.",
    "Seal edges with water.",
    "Deep fry until golden, serve with mint chutney."
  ],
  difficulty: "Medium",
  cookingTime: 45,
  isActive: true,
  isHalal: true,
  description: "Spiced minced lamb samosa - crispy pastry filled with aromatic keema. A classic favorite.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "standard",
  costPerServing: 35,
  baseServings: 4,
  calories: 250,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "lamb", "onion", "green chilies", "ginger garlic", "cumin", "coriander", "garam masala"],
  searchKeywords: ["samosa", "keema samosa", "lamb samosa", "crispy samosa", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Lentil Samosa",
  image: "samosa.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "12 samosa wrappers",
    "1 cup moong dal (split yellow lentils)",
    "1 onion, finely chopped",
    "2 green chilies, chopped",
    "1 tsp cumin seeds",
    "1/2 tsp turmeric",
    "1 tsp coriander powder",
    "Salt to taste",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Soak lentils for 2 hours, drain.",
    "Cook lentils with little water until soft but not mushy.",
    "Heat oil, add cumin seeds, then onions until golden.",
    "Add green chilies and spices, cook for 1 minute.",
    "Add cooked lentils, mix well, cook until dry.",
    "Let filling cool completely.",
    "Fill samosa wrappers with lentil mixture.",
    "Deep fry until golden, serve with chutney."
  ],
  difficulty: "Medium",
  cookingTime: 60,
  isActive: true,
  isHalal: true,
  description: "Protein-rich lentil samosa with moong dal filling - healthy, tasty, and perfectly spiced.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "standard",
  costPerServing: 18,
  baseServings: 4,
  calories: 190,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "lentils", "onion", "green chilies", "cumin seeds", "turmeric", "coriander"],
  searchKeywords: ["samosa", "lentil samosa", "veg samosa", "crispy samosa", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Cheese Samosa",
  image: "cheesy-samosa.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "12 samosa wrappers",
    "200g mozzarella cheese, grated",
    "100g cream cheese",
    "2 tbsp parsley, chopped",
    "1 tsp black pepper",
    "1/2 tsp red chili flakes",
    "1 egg, beaten",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Mix both cheeses with parsley, pepper, and chili flakes.",
    "Place cheese mixture in center of wrapper.",
    "Fold into samosa shape, seal edges with beaten egg.",
    "Refrigerate for 15 minutes to set.",
    "Heat oil to 350°F (175°C).",
    "Fry until golden brown (3-4 minutes).",
    "Drain on paper towels.",
    "Serve hot with marinara sauce."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Cheese samosa with gooey mozzarella and cream cheese filling - crispy outside, melty inside.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten", "dairy"],
  budget: "standard",
  costPerServing: 45,
  baseServings: 4,
  calories: 300,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "mozzarella", "cream cheese", "parsley", "black pepper", "red chili", "egg"],
  searchKeywords: ["samosa", "cheese samosa", "crispy samosa", "snack", "cheese snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Spinach & Feta Samosa",
  image: "samosa.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "12 samosa wrappers",
    "200g spinach, chopped",
    "150g feta cheese, crumbled",
    "1 onion, finely chopped",
    "2 cloves garlic, minced",
    "1/2 tsp nutmeg",
    "Black pepper to taste",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Sauté onion and garlic until soft.",
    "Add spinach, cook until wilted (3-4 minutes).",
    "Remove from heat, let cool, squeeze out excess water.",
    "Mix spinach with feta, nutmeg, and pepper.",
    "Fill samosa wrappers with mixture.",
    "Seal edges with water.",
    "Deep fry until golden brown.",
    "Serve hot with tzatziki sauce."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Greek-inspired samosa with spinach and tangy feta cheese - a tasty fusion appetizer.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten", "dairy"],
  budget: "standard",
  costPerServing: 38,
  baseServings: 4,
  calories: 260,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "spinach", "feta", "onion", "garlic", "nutmeg", "black pepper"],
  searchKeywords: ["samosa", "spinach samosa", "feta samosa", "veg samosa", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Mushroom Samosa",
  image: "samosa.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "12 samosa wrappers",
    "300g mushrooms, finely chopped",
    "1 onion, finely chopped",
    "2 cloves garlic, minced",
    "1 tsp thyme",
    "1/2 tsp black pepper",
    "2 tbsp cream cheese",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Sauté onion and garlic until soft.",
    "Add mushrooms, cook until moisture evaporates.",
    "Add thyme and pepper, cook for 2 minutes.",
    "Stir in cream cheese, mix well, cool.",
    "Fill samosa wrappers.",
    "Seal and deep fry until golden.",
    "Serve hot."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Earthy mushroom samosa with cream cheese - a rich, savory vegetarian snack.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten", "dairy"],
  budget: "standard",
  costPerServing: 30,
  baseServings: 4,
  calories: 230,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wrappers", "mushrooms", "onion", "garlic", "thyme", "black pepper", "cream cheese"],
  searchKeywords: ["samosa", "mushroom samosa", "veg samosa", "crispy samosa", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Vegetable Pakoras",
  image: "veg-pakora.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "1 cup gram flour (besan)",
    "1 onion, sliced",
    "1 potato, thinly sliced",
    "1 cup spinach leaves",
    "2 green chilies, chopped",
    "1 tsp cumin seeds",
    "1/2 tsp turmeric",
    "1/2 tsp red chili powder",
    "Water as needed",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Mix gram flour with all spices and enough water to make thick batter.",
    "Add all vegetables to batter, mix well to coat.",
    "Heat oil in deep pan.",
    "Drop spoonfuls of vegetable mixture into hot oil.",
    "Fry until golden brown (4-5 minutes).",
    "Remove with slotted spoon, drain on paper towels.",
    "Serve hot with mint chutney."
  ],
  difficulty: "Easy",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Classic Pakistani mixed vegetable fritters - crispy, spicy, and perfect with mint chutney.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 12,
  baseServings: 4,
  calories: 150,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["gram flour", "onion", "potato", "spinach", "green chilies", "cumin seeds", "turmeric", "red chili"],
  searchKeywords: ["pakoras", "veg pakoras", "fritters", "crispy snack", "pakistani snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Pakoras",
  image: "chicken-pakora.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "200g chicken breast, thinly sliced",
    "1 cup gram flour",
    "1 tsp ginger-garlic paste",
    "1 tsp cumin powder",
    "1/2 tsp turmeric",
    "1/2 tsp red chili powder",
    "Salt to taste",
    "Water as needed",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Marinate chicken with ginger-garlic paste and spices for 30 minutes.",
    "Mix gram flour with water to make thick batter.",
    "Dip chicken pieces in batter to coat evenly.",
    "Heat oil to 350°F (175°C).",
    "Fry chicken pieces in batches until golden and cooked (5-6 minutes).",
    "Drain on paper towels.",
    "Serve hot with mint chutney."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Crispy golden chicken fritters coated in spiced gram flour batter - a delicious snack.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 28,
  baseServings: 4,
  calories: 220,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken", "gram flour", "ginger garlic", "cumin", "turmeric", "red chili"],
  searchKeywords: ["pakoras", "chicken pakoras", "fritters", "crispy snack", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Onion Pakoras",
  image: "onion-pakora.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "2 large onions, thinly sliced",
    "1 cup gram flour",
    "2 green chilies, chopped",
    "1 tsp cumin seeds",
    "1/2 tsp turmeric",
    "1/2 tsp red chili powder",
    "Salt to taste",
    "Water as needed",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Mix gram flour with all spices and water to make thick batter.",
    "Add sliced onions and green chilies, mix well.",
    "Heat oil in deep pan.",
    "Drop spoonfuls of onion mixture into hot oil.",
    "Fry until golden and crispy (4-5 minutes).",
    "Drain on paper towels.",
    "Serve hot with ketchup or chutney."
  ],
  difficulty: "Easy",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Crispy golden onion fritters - a classic Pakistani tea-time snack, perfect with mint chutney.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 10,
  baseServings: 4,
  calories: 160,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["onions", "gram flour", "green chilies", "cumin seeds", "turmeric", "red chili"],
  searchKeywords: ["pakoras", "onion pakoras", "fritters", "crispy snack", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Spinach Pakoras",
  image: "spinach-pakora.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "2 cups spinach leaves, roughly chopped",
    "1 cup gram flour",
    "1 onion, finely chopped",
    "2 green chilies, chopped",
    "1 tsp cumin seeds",
    "1/2 tsp turmeric",
    "1/2 tsp red chili powder",
    "Water as needed",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Mix gram flour with all spices and water to make thick batter.",
    "Add spinach, onion, and green chilies, mix well.",
    "Heat oil in deep pan.",
    "Drop spoonfuls of spinach mixture into hot oil.",
    "Fry until golden and crispy (4-5 minutes).",
    "Drain on paper towels.",
    "Serve hot with mint chutney."
  ],
  difficulty: "Easy",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Healthy and crispy spinach fritters - a tasty way to enjoy greens, perfect as a snack.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 12,
  baseServings: 4,
  calories: 150,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["spinach", "gram flour", "onion", "green chilies", "cumin seeds", "turmeric", "red chili"],
  searchKeywords: ["pakoras", "spinach pakoras", "fritters", "crispy snack", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Fish Pakoras",
  image: "fish-pakora.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "200g fish fillets, cut into bite-sized pieces",
    "1 cup gram flour",
    "1 tsp ginger-garlic paste",
    "1 tsp cumin powder",
    "1/2 tsp turmeric",
    "1/2 tsp red chili powder",
    "1 tsp lemon juice",
    "Water as needed",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Marinate fish with ginger-garlic paste, spices, and lemon juice for 30 minutes.",
    "Mix gram flour with water to make thick batter.",
    "Dip fish pieces in batter to coat evenly.",
    "Heat oil to 350°F (175°C).",
    "Fry fish pieces until golden and cooked (4-5 minutes).",
    "Drain on paper towels.",
    "Serve hot with tartar sauce."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Spiced fish fritters coated in gram flour batter - crispy outside, flaky inside. A seafood treat.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["fish"],
  budget: "standard",
  costPerServing: 40,
  baseServings: 4,
  calories: 230,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["fish", "gram flour", "ginger garlic", "cumin", "turmeric", "red chili", "lemon"],
  searchKeywords: ["pakoras", "fish pakoras", "fritters", "crispy snack", "seafood snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Paneer Pakoras",
  image: "paneer-pakoras.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "200g paneer, cut into cubes",
    "1 cup gram flour",
    "1 tsp ginger-garlic paste",
    "1/2 tsp turmeric",
    "1/2 tsp red chili powder",
    "1/2 tsp garam masala",
    "Salt to taste",
    "Water as needed",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Mix gram flour with spices and water to make thick batter.",
    "Gently coat paneer cubes in batter.",
    "Heat oil to 350°F (175°C).",
    "Fry paneer cubes until golden (3-4 minutes).",
    "Drain on paper towels.",
    "Serve hot with mint chutney."
  ],
  difficulty: "Easy",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Crispy cottage cheese fritters - soft paneer inside, crunchy gram flour coating. A vegetarian favorite.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "standard",
  costPerServing: 35,
  baseServings: 4,
  calories: 240,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["paneer", "gram flour", "ginger garlic", "turmeric", "red chili", "garam masala"],
  searchKeywords: ["pakoras", "paneer pakoras", "fritters", "crispy snack", "vegetarian snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Potato Pakoras",
  image: "potato-pakoras.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "3 potatoes, thinly sliced",
    "1 cup gram flour",
    "1 tsp cumin seeds",
    "1/2 tsp turmeric",
    "1/2 tsp red chili powder",
    "1/2 tsp ajwain (carom seeds)",
    "Water as needed",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Mix gram flour with all spices and water to make thick batter.",
    "Dip potato slices in batter to coat.",
    "Heat oil to 350°F (175°C).",
    "Fry potato slices in batches until golden and crispy.",
    "Drain on paper towels.",
    "Sprinkle with chaat masala.",
    "Serve hot with ketchup."
  ],
  difficulty: "Easy",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Crispy thinly sliced potato fritters - a classic Pakistani snack, best served with ketchup or chutney.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 10,
  baseServings: 4,
  calories: 170,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["potatoes", "gram flour", "cumin seeds", "turmeric", "red chili", "ajwain", "chaat masala"],
  searchKeywords: ["pakoras", "potato pakoras", "aloo pakora", "fritters", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},

 
  {
  title: "Hot & Spicy Wings",
  image: "hot-and-spicy-wings.jpg",
  cuisine: "Continental",
  ingredientsRaw: [
    "12 chicken wings",
    "1/2 cup hot sauce",
    "1/4 cup butter, melted",
    "1 tbsp vinegar",
    "1 tsp garlic powder",
    "1/2 tsp cayenne pepper",
    "Oil for frying"
  ],
  stepsRaw: [
    "Pat chicken wings dry with paper towels.",
    "Heat oil to 375°F (190°C).",
    "Fry wings in batches for 10-12 minutes until golden and cooked.",
    "In a bowl, mix hot sauce, melted butter, vinegar, garlic powder, and cayenne.",
    "Toss fried wings in sauce until well coated.",
    "Serve hot with ranch dressing."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Fiery chicken wings coated in a buttery hot sauce - perfect for people who love spicy food. Serve with ranch.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 45,
  baseServings: 4,
  calories: 280,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken wings", "hot sauce", "butter", "vinegar", "garlic powder", "cayenne"],
  searchKeywords: ["wings", "chicken wings", "hot wings", "spicy wings", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "BBQ Wings",
  image: "hot-and-spicy-wings.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "12 chicken wings",
    "1 cup BBQ sauce",
    "2 tbsp honey",
    "1 tbsp brown sugar",
    "1 tsp smoked paprika",
    "1 tsp garlic powder",
    "Oil for frying"
  ],
  stepsRaw: [
    "Pat wings dry, season with salt and pepper.",
    "Heat oil and fry wings until golden and cooked (10-12 minutes).",
    "In a saucepan, combine BBQ sauce, honey, brown sugar, paprika, and garlic powder.",
    "Heat sauce until bubbling, then reduce heat.",
    "Toss fried wings in BBQ sauce until coated.",
    "Serve hot."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Smoky, sweet, and sticky BBQ chicken wings - a crowd-pleasing appetizer everyone enjoys.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 48,
  baseServings: 4,
  calories: 300,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken wings", "bbq sauce", "honey", "brown sugar", "paprika", "garlic powder"],
  searchKeywords: ["wings", "bbq wings", "chicken wings", "sticky wings", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Garlic Parmesan Wings",
  image: "garlic-permesan-wings.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "12 chicken wings",
    "1/4 cup butter",
    "6 cloves garlic, minced",
    "1/2 cup grated Parmesan cheese",
    "2 tbsp parsley, chopped",
    "Salt and pepper to taste",
    "Oil for frying"
  ],
  stepsRaw: [
    "Fry wings until golden and cooked (10-12 minutes).",
    "In a pan, melt butter and sauté garlic until fragrant (1-2 minutes).",
    "Place fried wings in large bowl, pour garlic butter over.",
    "Sprinkle with Parmesan cheese and parsley, toss well.",
    "Serve hot."
  ],
  difficulty: "Medium",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Savory garlic butter wings topped with Parmesan and parsley - rich and very satisfying.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "standard",
  costPerServing: 50,
  baseServings: 4,
  calories: 320,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken wings", "butter", "garlic", "parmesan", "parsley"],
  searchKeywords: ["wings", "garlic wings", "parmesan wings", "chicken wings", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Honey Sesame Wings",
  image: "honey-sesame-wings.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "12 chicken wings",
    "1/2 cup honey",
    "1/4 cup soy sauce",
    "2 tbsp sesame oil",
    "2 cloves garlic, minced",
    "1 tbsp ginger, grated",
    "Sesame seeds for garnish",
    "Oil for frying"
  ],
  stepsRaw: [
    "Mix honey, soy sauce, sesame oil, garlic, and ginger in a bowl.",
    "Fry wings until golden and cooked (10-12 minutes).",
    "Toss hot wings in honey mixture until well coated.",
    "Sprinkle with sesame seeds.",
    "Serve hot with spring onions."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Sweet and savory Asian-style wings with honey, soy, and sesame - sticky and addictive.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["soy"],
  budget: "standard",
  costPerServing: 52,
  baseServings: 4,
  calories: 310,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken wings", "honey", "soy sauce", "sesame oil", "garlic", "ginger", "sesame seeds"],
  searchKeywords: ["wings", "honey wings", "sesame wings", "chicken wings", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Salt & Pepper Wings",
  image: "salt-and-pepper-wings.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "12 chicken wings",
    "2 tbsp salt",
    "1 tbsp black pepper, crushed",
    "1 tsp white pepper",
    "2 green chilies, chopped",
    "2 cloves garlic, minced",
    "Oil for frying"
  ],
  stepsRaw: [
    "Season wings with salt and let sit for 30 minutes.",
    "Heat oil and fry wings until crispy and golden (12-15 minutes).",
    "In a separate pan, heat 1 tbsp oil, sauté garlic and green chilies.",
    "Add fried wings, sprinkle with black and white pepper.",
    "Toss well to coat.",
    "Serve hot with lemon wedges."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Simple, crispy salt and pepper wings with a spicy kick from green chilies and garlic.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 40,
  baseServings: 4,
  calories: 270,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken wings", "salt", "black pepper", "white pepper", "green chilies", "garlic"],
  searchKeywords: ["wings", "salt pepper wings", "crispy wings", "chicken wings", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Lemon Pepper Wings",
  image: "salt-and-pepper-wings.jpg",
  cuisine: "italian",
  ingredientsRaw: [
    "12 chicken wings",
    "2 tbsp lemon pepper seasoning",
    "1 tsp garlic powder",
    "1 tsp onion powder",
    "Zest of 1 lemon",
    "2 tbsp lemon juice",
    "Oil for frying"
  ],
  stepsRaw: [
    "Season wings with lemon pepper, garlic powder, onion powder.",
    "Fry until golden and cooked.",
    "Toss with fresh lemon zest and juice.",
    "Serve hot."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Zesty lemon pepper wings - bright, tangy, and perfectly crispy. A great flavor combination.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 42,
  baseServings: 4,
  calories: 275,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken wings", "lemon pepper", "garlic powder", "onion powder", "lemon"],
  searchKeywords: ["wings", "lemon wings", "lemon pepper wings", "chicken wings", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Mozzarella Sticks",
  image: "mozzarela-sticks.jpg",
  cuisine: "Italian",
  ingredientsRaw: [
    "12 mozzarella cheese sticks",
    "1 cup all-purpose flour",
    "2 eggs, beaten",
    "1 cup breadcrumbs",
    "1 tsp Italian seasoning",
    "1/2 tsp garlic powder",
    "Salt to taste",
    "Oil for deep frying",
    "Marinara sauce for dipping"
  ],
  stepsRaw: [
    "Freeze cheese sticks for at least 2 hours until solid.",
    "Set up three bowls: flour, beaten eggs, breadcrumbs mixed with seasonings.",
    "Coat each cheese stick in flour, then egg, then breadcrumbs.",
    "Repeat egg and breadcrumb coating for extra crispy coating.",
    "Freeze again for 30 minutes.",
    "Heat oil to 375°F (190°C).",
    "Fry frozen sticks in batches for 1-2 minutes until golden.",
    "Drain and serve immediately with marinara sauce."
  ],
  difficulty: "Medium",
  cookingTime: 180,
  isActive: true,
  isHalal: true,
  description: "Crispy golden breaded mozzarella sticks with a warm, gooey center. A classic Italian appetizer.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten", "dairy"],
  budget: "standard",
  costPerServing: 35,
  baseServings: 4,
  calories: 310,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["mozzarella", "flour", "eggs", "breadcrumbs", "italian seasoning", "garlic powder", "marinara"],
  searchKeywords: ["mozzarella sticks", "cheese sticks", "crispy cheese", "snack", "appetizer"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Jalapeño Poppers",
  image: "jalapeno-poppers.jpg",
  cuisine: "Continental",
  ingredientsRaw: [
    "12 fresh jalapeños",
    "8 oz cream cheese, softened",
    "1 cup cheddar cheese, shredded",
    "1 tsp cumin powder",
    "1/2 tsp garlic powder",
    "1 cup breadcrumbs",
    "2 eggs, beaten",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Cut jalapeños in half lengthwise, remove seeds and membranes.",
    "Mix cream cheese, cheddar, cumin, and garlic powder.",
    "Stuff each jalapeño half with cheese mixture.",
    "Press halves back together or leave open-faced.",
    "Dip in beaten egg, then coat with breadcrumbs.",
    "Freeze for 30 minutes.",
    "Deep fry until golden (3-4 minutes).",
    "Serve hot with ranch dressing."
  ],
  difficulty: "Medium",
  cookingTime: 45,
  isActive: true,
  isHalal: true,
  description: "Spicy jalapeño poppers stuffed with creamy cheese, breaded and fried. A Tex-Mex favorite.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten", "dairy"],
  budget: "standard",
  costPerServing: 38,
  baseServings: 4,
  calories: 290,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["jalapenos", "cream cheese", "cheddar", "cumin", "garlic powder", "breadcrumbs", "eggs"],
  searchKeywords: ["jalapeno poppers", "cheese poppers", "spicy snack", "snack", "appetizer"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Stuffed Mushrooms",
  image: "stuffed-mushrooms.jpg",
  cuisine: "Continental",
  ingredientsRaw: [
    "24 large mushrooms, stems removed",
    "8 oz cream cheese, softened",
    "1/2 cup Parmesan cheese, grated",
    "2 cloves garlic, minced",
    "2 tbsp parsley, chopped",
    "1/2 tsp black pepper",
    "2 tbsp breadcrumbs",
    "2 tbsp olive oil"
  ],
  stepsRaw: [
    "Preheat oven to 375°F (190°C).",
    "Clean mushrooms, remove stems (chop stems finely).",
    "Mix cream cheese, Parmesan, chopped stems, garlic, parsley, pepper.",
    "Fill each mushroom cap with cheese mixture.",
    "Sprinkle breadcrumbs on top, drizzle with olive oil.",
    "Bake for 20 minutes until mushrooms are tender and tops are golden.",
    "Let cool slightly before serving.",
    "Serve warm as an elegant appetizer."
  ],
  difficulty: "Easy",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Elegant stuffed mushrooms with creamy cheese, garlic, and herbs - a perfect party appetizer.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "standard",
  costPerServing: 42,
  baseServings: 4,
  calories: 210,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["mushrooms", "cream cheese", "parmesan", "garlic", "parsley", "breadcrumbs", "olive oil"],
  searchKeywords: ["stuffed mushrooms", "cheese mushrooms", "baked mushrooms", "snack", "appetizer"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Cheese Balls",
  image: "cheese-balls.jpg",
  cuisine: "Continental",
  ingredientsRaw: [
    "200g mozzarella cheese, cubed",
    "100g cream cheese",
    "1 cup all-purpose flour",
    "2 eggs, beaten",
    "1 cup breadcrumbs",
    "1 tsp Italian seasoning",
    "Oil for deep frying",
    "Marinara sauce for dipping"
  ],
  stepsRaw: [
    "Cut mozzarella into small cubes.",
    "Take small piece of cream cheese, wrap around mozzarella cube, form into ball.",
    "Freeze cheese balls for 1 hour until firm.",
    "Set up flour, egg, and breadcrumbs with seasoning.",
    "Coat frozen cheese balls in flour, then egg, then breadcrumbs.",
    "Repeat for double coating.",
    "Deep fry at 350°F (175°C) for 2-3 minutes until golden.",
    "Serve immediately with marinara sauce."
  ],
  difficulty: "Medium",
  cookingTime: 90,
  isActive: true,
  isHalal: true,
  description: "Crispy fried cheese balls with a gooey center - irresistible and very popular.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten", "dairy"],
  budget: "standard",
  costPerServing: 45,
  baseServings: 4,
  calories: 340,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["mozzarella", "cream cheese", "flour", "eggs", "breadcrumbs", "italian seasoning", "marinara"],
  searchKeywords: ["cheese balls", "crispy cheese", "cheese snack", "snack", "appetizer"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Halloumi Fries",
  image: "halloumi-fries.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "200g halloumi cheese",
    "1/4 cup flour",
    "1 tsp paprika",
    "1/2 tsp black pepper",
    "Oil for frying",
    "Lemon wedges for serving"
  ],
  stepsRaw: [
    "Cut halloumi into fry-shaped sticks.",
    "Mix flour with paprika and pepper.",
    "Dredge halloumi sticks in seasoned flour.",
    "Heat oil in pan.",
    "Fry until golden on all sides (2-3 minutes).",
    "Drain on paper towels.",
    "Serve hot with lemon wedges."
  ],
  difficulty: "Easy",
  cookingTime: 15,
  isActive: true,
  isHalal: true,
  description: "Crispy fried halloumi cheese sticks seasoned with paprika - salty, tasty, and addictive.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "standard",
  costPerServing: 35,
  baseServings: 4,
  calories: 280,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["halloumi", "flour", "paprika", "black pepper", "lemon"],
  searchKeywords: ["halloumi fries", "cheese fries", "crispy cheese", "snack", "appetizer"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Shrimp Tempura",
  image: "shrimp-tempura.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "12 large shrimp, peeled with tails on",
    "1 cup all-purpose flour",
    "1/4 cup cornstarch",
    "1 cup ice-cold water",
    "1 egg yolk",
    "1/2 tsp baking soda",
    "Salt to taste",
    "Oil for deep frying",
    "Tempura dipping sauce"
  ],
  stepsRaw: [
    "Make slits on underside of shrimp to prevent curling.",
    "Pat shrimp completely dry.",
    "Mix flour, cornstarch, baking soda, and salt.",
    "Add ice-cold water and egg yolk, mix gently (batter should be lumpy).",
    "Heat oil to 375°F (190°C).",
    "Dip shrimp in batter, let excess drip off.",
    "Deep fry in batches for 2-3 minutes until light golden.",
    "Drain and serve immediately with tempura sauce."
  ],
  difficulty: "Medium",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Light, crispy tempura-battered shrimp - delicate and perfect with dipping sauce.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["shellfish", "gluten", "eggs"],
  budget: "standard",
  costPerServing: 60,
  baseServings: 4,
  calories: 310,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["shrimp", "flour", "cornstarch", "egg yolk", "baking soda", "tempura sauce"],
  searchKeywords: ["shrimp tempura", "crispy shrimp", "tempura", "snack", "appetizer"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Calamari Rings",
  image: "calamari-rings.jpg",
  cuisine: "Italian",
  ingredientsRaw: [
    "500g calamari rings",
    "1 cup all-purpose flour",
    "1/2 cup cornmeal",
    "1 tsp paprika",
    "1 tsp garlic powder",
    "Salt and pepper to taste",
    "2 eggs, beaten",
    "Oil for deep frying",
    "Lemon wedges for serving"
  ],
  stepsRaw: [
    "Pat calamari rings completely dry.",
    "Mix flour, cornmeal, paprika, garlic powder, salt, pepper.",
    "Dip rings in beaten egg, then dredge in flour mixture.",
    "Heat oil to 375°F (190°C).",
    "Fry in batches for 2-3 minutes until golden.",
    "Drain on paper towels.",
    "Serve hot with lemon wedges and marinara sauce."
  ],
  difficulty: "Medium",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Tender calamari rings with a crispy, seasoned coating. A classic Italian appetizer.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["shellfish", "gluten", "eggs"],
  budget: "standard",
  costPerServing: 55,
  baseServings: 4,
  calories: 320,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["calamari", "flour", "cornmeal", "paprika", "garlic powder", "eggs", "lemon"],
  searchKeywords: ["calamari rings", "fried calamari", "crispy squid", "snack", "appetizer"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Fish Bites",
  image: "fish-bites.jpg",
  cuisine: "Continental",
  ingredientsRaw: [
    "400g white fish fillets, cut into 1-inch pieces",
    "1 cup all-purpose flour",
    "1 cup breadcrumbs",
    "2 eggs, beaten",
    "1 tsp garlic powder",
    "1 tsp paprika",
    "Salt and pepper to taste",
    "Oil for deep frying",
    "Tartar sauce for serving"
  ],
  stepsRaw: [
    "Season fish pieces with salt, pepper, garlic powder, paprika.",
    "Set up three bowls: flour, beaten eggs, breadcrumbs.",
    "Coat fish in flour, then egg, then breadcrumbs.",
    "Heat oil to 375°F (190°C).",
    "Fry fish bites in batches for 3-4 minutes until golden.",
    "Drain on paper towels.",
    "Serve hot with tartar sauce."
  ],
  difficulty: "Medium",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Bite-sized crispy fish pieces breaded and fried - perfect with tartar sauce.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["fish", "gluten", "eggs"],
  budget: "standard",
  costPerServing: 50,
  baseServings: 4,
  calories: 290,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["fish", "flour", "breadcrumbs", "eggs", "garlic powder", "paprika", "tartar sauce"],
  searchKeywords: ["fish bites", "crispy fish", "popcorn fish", "snack", "appetizer"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Hummus with Pita Bread",
  image: "hummus-with-pita-bread.jpg",
  cuisine: "Continental",
  ingredientsRaw: [
    "2 cans chickpeas, drained",
    "1/4 cup tahini",
    "3 tbsp lemon juice",
    "2 cloves garlic",
    "1/2 tsp cumin",
    "Salt to taste",
    "3 tbsp olive oil",
    "Paprika for garnish",
    "Pita bread for serving"
  ],
  stepsRaw: [
    "Combine chickpeas, tahini, lemon juice, garlic, cumin, salt in food processor.",
    "Blend until smooth, scraping down sides.",
    "With processor running, slowly add olive oil until creamy.",
    "Transfer to serving bowl.",
    "Make a well in center, drizzle with olive oil.",
    "Sprinkle with paprika.",
    "Warm pita bread in oven.",
    "Serve hummus with warm pita triangles."
  ],
  difficulty: "Easy",
  cookingTime: 15,
  isActive: true,
  isHalal: true,
  description: "Creamy, smooth hummus made from chickpeas and tahini - served with warm pita bread.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["none"],
  budget: "standard",
  costPerServing: 20,
  baseServings: 4,
  calories: 220,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chickpeas", "tahini", "lemon", "garlic", "cumin", "olive oil", "pita"],
  searchKeywords: ["hummus", "chickpea dip", "pita bread", "snack", "dip"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Guacamole with Tortilla Chips",
  image: "guacamole-with-chips.jpg",
  cuisine: "Continental",
  ingredientsRaw: [
    "3 ripe avocados",
    "1 tomato, diced",
    "1/2 red onion, finely chopped",
    "1 jalapeño, seeded and minced",
    "1/4 cup cilantro, chopped",
    "2 tbsp lime juice",
    "1 clove garlic, minced",
    "Salt to taste",
    "Tortilla chips for serving"
  ],
  stepsRaw: [
    "Cut avocados, remove pit, scoop flesh into bowl.",
    "Mash avocados with fork to desired consistency.",
    "Add tomato, onion, jalapeño, cilantro, lime juice, garlic.",
    "Mix well, season with salt.",
    "Press plastic wrap directly on surface to prevent browning.",
    "Let sit 30 minutes for flavors to meld.",
    "Serve with tortilla chips."
  ],
  difficulty: "Easy",
  cookingTime: 40,
  isActive: true,
  isHalal: true,
  description: "Fresh, chunky guacamole with avocado, tomato, onion, jalapeño, and cilantro - perfect with tortilla chips.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 45,
  baseServings: 4,
  calories: 210,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["avocados", "tomato", "onion", "jalapeno", "cilantro", "lime", "garlic", "tortilla chips"],
  searchKeywords: ["guacamole", "avocado dip", "tortilla chips", "snack", "dip"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Stuffed Mushrooms",
  image: "stuffed-mushrooms.jpg",
  cuisine: "Continental",
  ingredientsRaw: [
    "24 large mushrooms",
    "1 cup breadcrumbs",
    "1/2 cup Parmesan, grated",
    "1/4 cup parsley, chopped",
    "2 cloves garlic, minced",
    "1 tsp thyme",
    "1/4 cup olive oil",
    "Salt and pepper to taste"
  ],
  stepsRaw: [
    "Preheat oven to 375°F (190°C).",
    "Remove mushroom stems, chop finely.",
    "Mix chopped stems with breadcrumbs, Parmesan, parsley, garlic, thyme.",
    "Add olive oil gradually until mixture comes together.",
    "Season with salt and pepper.",
    "Fill each mushroom cap with stuffing mixture.",
    "Place on baking sheet, bake for 20 minutes.",
    "Serve warm."
  ],
  difficulty: "Easy",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Mushroom caps stuffed with herbed breadcrumb and Parmesan mixture - baked until tender.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["gluten", "dairy"],
  budget: "standard",
  costPerServing: 30,
  baseServings: 4,
  calories: 190,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["mushrooms", "breadcrumbs", "parmesan", "parsley", "garlic", "thyme", "olive oil"],
  searchKeywords: ["stuffed mushrooms", "baked mushrooms", "herb mushrooms", "snack", "appetizer"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Lollipop",
  image: "spicy-glazed-chicken-lollipop.jpg",
  cuisine: "Continental",
  ingredientsRaw: [
    "12 chicken wing lollipops",
    "2 tbsp soy sauce",
    "1 tbsp chili sauce",
    "1 tbsp ginger-garlic paste",
    "1 tsp red chili powder",
    "1/2 tsp black pepper",
    "1 egg, beaten",
    "1/2 cup cornstarch",
    "Oil for deep frying"
  ],
  stepsRaw: [
    "Make lollipops by cutting around small end of wing, pushing meat down.",
    "Marinate chicken with soy sauce, chili sauce, ginger-garlic paste, spices for 1 hour.",
    "Add beaten egg and cornstarch to marinated chicken, mix well.",
    "Heat oil to 350°F (175°C).",
    "Fry lollipops for 8-10 minutes until golden and cooked.",
    "Drain on paper towels.",
    "Toss in additional chili sauce if desired.",
    "Serve hot with mayonnaise."
  ],
  difficulty: "Hard",
  cookingTime: 80,
  isActive: true,
  isHalal: true,
  description: "Spicy Indo-Chinese chicken lollipops - crispy, tangy, and very addictive.",
  category: "Snacks",
  subCategory: "appetizers",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack", "Appetizer"],
  beverageCategory: null,
  allergens: ["eggs", "soy"],
  budget: "standard",
  costPerServing: 55,
  baseServings: 4,
  calories: 350,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken wings", "soy sauce", "chili sauce", "ginger garlic", "red chili", "black pepper", "egg", "cornstarch"],
  searchKeywords: ["chicken lollipop", "lollipop", "spicy chicken", "crispy chicken", "snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
];

async function migrateRecipes() {
  try {
    console.log('Connecting to MongoDB');
    
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) {
      throw new Error('MongoDB URI not found');
    }
    
    await mongoose.connect(mongoURI, { 
      serverSelectionTimeoutMS: 10000, 
      family: 4 
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();