const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
  {
    title: "Vanilla Sponge Cake",
    image: "vanilla-sponge-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "2 cups sugar",
      "1 cup butter, room temperature",
      "4 eggs",
      "1 cup milk",
      "2 tsp vanilla essence",
      "1 tbsp baking powder",
      "1/2 tsp salt"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C).",
      "Grease and flour two 9-inch round cake pans.",
      "Beat butter and sugar until light and fluffy.",
      "Add eggs one by one and mix well.",
      "Add vanilla essence.",
      "In a separate bowl, mix flour, baking powder and salt.",
      "Add dry ingredients to butter mixture alternately with milk.",
      "Divide batter evenly between both pans.",
      "Bake for 25-30 minutes until toothpick comes out clean.",
      "Cool in pan for 10 minutes, then transfer to wire rack."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A light and fluffy classic vanilla sponge cake perfect for birthdays, celebrations, or tea time.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 8,
    calories: 380,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "butter", "eggs", "milk", "vanilla", "baking powder", "salt"],
    searchKeywords: ["vanilla cake", "sponge cake", "cake", "birthday cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chocolate Mug Cake",
    image: "choc-mug-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 tbsp all-purpose flour",
      "4 tbsp sugar",
      "2 tbsp cocoa powder",
      "1/4 tsp baking powder",
      "3 tbsp milk",
      "2 tbsp cooking oil",
      "1/4 tsp vanilla essence",
      "1 tbsp chocolate chips (optional)"
    ],
    stepsRaw: [
      "In a mug, mix flour, sugar, cocoa powder and baking powder.",
      "Add milk, oil and vanilla essence. Mix until smooth.",
      "Add chocolate chips if using.",
      "Microwave on high for 1 minute 30 seconds to 2 minutes.",
      "Let cool for 1 minute and enjoy.",
      "Serve with ice cream if desired."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A quick single-serving chocolate cake made in a mug, perfect for instant dessert cravings.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "wheat"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 1,
    calories: 350,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "cocoa", "baking powder", "milk", "oil", "vanilla", "chocolate chips"],
    searchKeywords: ["mug cake", "chocolate cake", "quick cake", "single cake", "microwave cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Banana Bread",
    image: "banana-bread.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "3 ripe bananas, mashed",
      "1/3 cup melted butter",
      "1 cup sugar",
      "1 egg, beaten",
      "1 tsp vanilla essence",
      "1 tsp baking soda",
      "Pinch of salt",
      "1 1/2 cups all-purpose flour",
      "1/2 cup chopped walnuts (optional)"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease a 9x5 inch loaf pan.",
      "Mash bananas well with a fork.",
      "Mix melted butter into bananas.",
      "Add sugar, egg and vanilla essence and mix.",
      "Add baking soda and salt and mix well.",
      "Add flour gradually while mixing.",
      "Fold in walnuts if using.",
      "Pour batter into pan.",
      "Bake for 60-65 minutes until toothpick comes out clean.",
      "Cool completely before slicing."
    ],
    difficulty: "Easy",
    cookingTime: 75,
    isActive: true,
    isHalal: true,
    description: "A moist and delicious banana bread made with ripe bananas, perfect for breakfast or as a snack.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 8,
    calories: 320,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["banana", "butter", "sugar", "egg", "vanilla", "baking soda", "salt", "flour", "walnuts"],
    searchKeywords: ["banana bread", "banana cake", "bread", "breakfast", "snack"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Butter Pound Cake",
    image: "butter-pound-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "2 cups sugar",
      "1 cup butter, softened",
      "5 eggs",
      "1/2 cup yogurt",
      "1 tsp vanilla essence",
      "1/2 tsp baking powder",
      "1/4 tsp salt"
    ],
    stepsRaw: [
      "Preheat oven to 325°F (165°C). Grease a tube pan.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one by one and beat well.",
      "Add vanilla essence and yogurt and mix.",
      "In another bowl, whisk flour, baking powder and salt.",
      "Gradually add dry ingredients to butter mixture.",
      "Pour batter into pan.",
      "Bake for 60-75 minutes until golden brown.",
      "Cool in pan for 20 minutes, then remove."
    ],
    difficulty: "Medium",
    cookingTime: 85,
    isActive: true,
    isHalal: true,
    description: "A rich, dense and buttery classic pound cake perfect with tea or coffee.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 55,
    baseServings: 10,
    calories: 450,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "butter", "eggs", "yogurt", "vanilla", "baking powder", "salt"],
    searchKeywords: ["pound cake", "butter cake", "cake", "dessert", "tea cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Coffee Cake",
    image: "coffee-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1 cup sugar",
      "1/2 cup butter, softened",
      "2 eggs",
      "1 cup yogurt",
      "1 tsp vanilla essence",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "For topping: 1/2 cup brown sugar, 1/2 cup chopped walnuts, 2 tsp cinnamon"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease a 9-inch square pan.",
      "Make topping: Mix brown sugar, walnuts and cinnamon.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one by one.",
      "Add vanilla essence and yogurt and mix.",
      "In another bowl, whisk flour, baking powder, baking soda and salt.",
      "Gradually add dry ingredients to butter mixture.",
      "Spread half of batter in pan.",
      "Sprinkle half of topping.",
      "Top with remaining batter and sprinkle remaining topping.",
      "Bake for 35-40 minutes until golden brown."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A delicious cinnamon streusel-topped coffee cake perfect with your morning coffee.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 9,
    calories: 380,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "butter", "eggs", "yogurt", "vanilla", "baking powder", "baking soda", "salt", "brown sugar", "walnuts", "cinnamon"],
    searchKeywords: ["coffee cake", "cinnamon cake", "breakfast cake", "cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Vegan Sugar Cookies",
    image: "vegan-sugar-cookies.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 1/2 cups all-purpose flour",
      "1 cup vegan butter, softened",
      "1 cup sugar",
      "1/4 cup almond milk",
      "2 tsp vanilla essence",
      "1 tbsp cornstarch",
      "1 tsp baking powder",
      "1/2 tsp salt"
    ],
    stepsRaw: [
      "Cream vegan butter and sugar until fluffy.",
      "Add almond milk and vanilla essence and mix well.",
      "In another bowl, whisk flour, cornstarch, baking powder and salt.",
      "Gradually add dry ingredients to wet mixture.",
      "Divide dough in half, shape into disks, wrap and chill for 1 hour.",
      "Preheat oven to 350°F (180°C).",
      "Roll dough to 1/4-inch thickness on floured surface.",
      "Cut with cookie cutters.",
      "Bake for 8-10 minutes until edges are lightly golden.",
      "Cool on baking sheets for 5 minutes."
    ],
    difficulty: "Medium",
    cookingTime: 90,
    isActive: true,
    isHalal: true,
    description: "Plant-based buttery sugar cookies perfect for holidays, parties or anytime you need a sweet treat.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["wheat", "nuts"],
    budget: "standard",
    costPerServing: 35,
    baseServings: 24,
    calories: 120,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "vegan butter", "sugar", "almond milk", "vanilla", "cornstarch", "baking powder", "salt"],
    searchKeywords: ["vegan cookies", "sugar cookies", "cookies", "eggless cookies", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Peanut Butter Cookies",
    image: "peanut-butter-cookies.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup creamy peanut butter",
      "1 cup sugar",
      "1 egg",
      "1 tsp vanilla essence",
      "1 tsp baking soda",
      "Pinch of salt",
      "Sugar for rolling"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C).",
      "Mix peanut butter, sugar, egg, vanilla, baking soda and salt.",
      "Make 1-inch balls and roll in sugar.",
      "Place on baking sheets and press with fork.",
      "Bake for 8-10 minutes until edges are set.",
      "Cool on baking sheets for 5 minutes.",
      "Store in airtight container."
    ],
    difficulty: "Easy",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "Soft, chewy and delicious peanut butter cookies made with just a few ingredients.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["eggs", "peanuts"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 18,
    calories: 140,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["peanut butter", "sugar", "egg", "vanilla", "baking soda", "salt"],
    searchKeywords: ["peanut butter cookies", "cookies", "peanut cookies", "dessert", "snack"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Vegan Chocolate Cake",
    image: "vegan-choc-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 1/2 cups all-purpose flour",
      "1 cup sugar",
      "1/4 cup cocoa powder",
      "1 tsp baking soda",
      "1/2 tsp salt",
      "1 cup water",
      "1/3 cup cooking oil",
      "1 tsp vanilla essence",
      "1 tsp vinegar"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease an 8-inch pan.",
      "Whisk together flour, sugar, cocoa powder, baking soda and salt.",
      "Make a well in center and add water, oil, vanilla and vinegar.",
      "Mix until just combined (batter will be thin).",
      "Pour into prepared pan.",
      "Bake for 30-35 minutes until toothpick comes out clean.",
      "Cool in pan for 10 minutes.",
      "Frost with vegan chocolate frosting if desired."
    ],
    difficulty: "Easy",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A rich, moist and delicious eggless chocolate cake that's completely vegan.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["wheat"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 8,
    calories: 350,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "cocoa", "baking soda", "salt", "water", "oil", "vanilla", "vinegar"],
    searchKeywords: ["vegan cake", "chocolate cake", "eggless cake", "cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Continental Red Velvet",
    image: "continental-red-velvet.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 1/2 cups all-purpose flour",
      "1 1/2 cups sugar",
      "1 cup buttermilk",
      "1/2 cup butter, softened",
      "2 eggs",
      "2 tbsp red food coloring",
      "1 tsp vanilla essence",
      "1 tsp baking soda",
      "1 tsp vinegar",
      "1 tsp cocoa powder",
      "1/2 tsp salt"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease two 9-inch pans.",
      "Whisk flour, cocoa powder and salt.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one by one.",
      "Mix in food coloring and vanilla.",
      "Add flour mixture alternately with buttermilk.",
      "Mix baking soda and vinegar, fold into batter.",
      "Divide batter between pans.",
      "Bake for 25-30 minutes.",
      "Cool completely before frosting with cream cheese frosting."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A classic red velvet cake with a beautiful red color and tangy cream cheese frosting.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 10,
    calories: 480,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "buttermilk", "butter", "eggs", "red color", "vanilla", "baking soda", "vinegar", "cocoa", "salt"],
    searchKeywords: ["red velvet cake", "red cake", "velvet cake", "birthday cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Yogurt Pound Cake",
    image: "yogurt-pound-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 1/2 cups all-purpose flour",
      "1 cup plain yogurt",
      "1 cup sugar",
      "3 eggs",
      "1/2 cup cooking oil",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1 tsp vanilla essence",
      "Pinch of salt"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease a loaf pan.",
      "Whisk flour, baking powder, baking soda and salt.",
      "Beat eggs and sugar until pale and fluffy.",
      "Add yogurt, oil and vanilla essence and mix well.",
      "Gradually fold in dry ingredients.",
      "Pour batter into pan.",
      "Bake for 45-50 minutes until golden brown.",
      "Cool in pan for 10 minutes.",
      "Dust with powdered sugar before serving."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A moist and tender pound cake made with yogurt, resulting in a soft crumb.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 8,
    calories: 360,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "yogurt", "sugar", "eggs", "oil", "baking powder", "baking soda", "vanilla", "salt"],
    searchKeywords: ["yogurt cake", "pound cake", "moist cake", "cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Japanese Cheesecake",
    image: "japanese-cheesecake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "250g cream cheese",
      "50g butter",
      "100ml milk",
      "60g cake flour",
      "20g cornstarch",
      "6 eggs, separated",
      "120g sugar",
      "1 tsp lemon juice",
      "1/4 tsp cream of tartar"
    ],
    stepsRaw: [
      "Preheat oven to 320°F (160°C). Prepare water bath.",
      "Melt cream cheese, butter and milk over double boiler.",
      "Remove from heat, sift in flour and cornstarch and mix well.",
      "Add egg yolks one by one, mixing after each.",
      "Beat egg whites with cream of tartar until foamy.",
      "Gradually add sugar, beating until stiff peaks form.",
      "Fold egg whites into cheese mixture in three batches.",
      "Pour into springform pan lined with parchment paper.",
      "Place in water bath and bake for 70-80 minutes.",
      "Turn off oven and let cake cool inside for 1 hour.",
      "Chill for at least 4 hours before serving."
    ],
    difficulty: "Hard",
    cookingTime: 180,
    isActive: true,
    isHalal: true,
    description: "A light, fluffy and jiggly Japanese-style cheesecake that's less sweet and airy.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "premium",
    costPerServing: 80,
    baseServings: 8,
    calories: 320,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["cream cheese", "butter", "milk", "cake flour", "cornstarch", "eggs", "sugar", "lemon", "cream of tartar"],
    searchKeywords: ["japanese cheesecake", "cheesecake", "fluffy cake", "dessert", "japanese cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Spanish Orange Cake",
    image: "spanish-orange-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1 1/2 cups sugar",
      "3 eggs",
      "1 cup fresh orange juice",
      "1/2 cup cooking oil",
      "Zest of 2 oranges",
      "1 tbsp baking powder",
      "1/2 tsp salt",
      "Powdered sugar for dusting"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease a bundt pan.",
      "Whisk flour, baking powder and salt.",
      "Beat eggs and sugar until pale and fluffy.",
      "Add orange juice, oil and orange zest and mix well.",
      "Gradually add dry ingredients and mix well.",
      "Pour batter into pan.",
      "Bake for 45-50 minutes until golden brown.",
      "Cool in pan for 15 minutes.",
      "Dust with powdered sugar before serving."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A bright, citrusy Spanish orange cake that's moist and full of fresh orange flavor.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["eggs", "wheat"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 10,
    calories: 350,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "eggs", "orange juice", "oil", "orange zest", "baking powder", "salt", "powdered sugar"],
    searchKeywords: ["orange cake", "spanish cake", "citrus cake", "cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cinnamon Rolls",
    image: "cinnamon-rolls.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "For dough: 3 cups all-purpose flour",
      "1/4 cup sugar",
      "1 tsp salt",
      "2 1/4 tsp instant yeast",
      "3/4 cup warm milk",
      "1/4 cup melted butter",
      "1 egg",
      "For filling: 1/2 cup brown sugar",
      "2 tbsp cinnamon powder",
      "1/4 cup softened butter",
      "For icing: 1 cup powdered sugar",
      "2 tbsp milk",
      "1/2 tsp vanilla essence"
    ],
    stepsRaw: [
      "Mix warm milk, sugar and yeast, let sit for 5 minutes.",
      "Combine flour and salt.",
      "Add yeast mixture, melted butter and egg to flour.",
      "Knead until smooth dough forms (8-10 minutes).",
      "Place in greased bowl, cover and let rise for 1 hour.",
      "Roll dough into 12x18 inch rectangle.",
      "Spread softened butter evenly.",
      "Mix brown sugar and cinnamon, sprinkle over butter.",
      "Roll dough tightly from long edge into a log.",
      "Cut into 12 equal pieces.",
      "Place in greased baking pan, cover and let rise 30 minutes.",
      "Preheat oven to 350°F (175°C).",
      "Bake for 20-25 minutes until golden brown.",
      "Mix icing ingredients and drizzle over warm rolls.",
      "Serve warm."
    ],
    difficulty: "Hard",
    cookingTime: 150,
    isActive: true,
    isHalal: true,
    description: "Soft, gooey and irresistible cinnamon rolls perfect for breakfast or brunch.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 12,
    calories: 380,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "salt", "yeast", "milk", "butter", "egg", "brown sugar", "cinnamon", "powdered sugar", "vanilla"],
    searchKeywords: ["cinnamon rolls", "cinnamon buns", "rolls", "breakfast", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Blueberry Muffins",
    image: "blueberry-muffins.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1 cup sugar",
      "1/2 cup melted butter",
      "2 eggs",
      "1 cup buttermilk",
      "2 tsp baking powder",
      "1/2 tsp baking soda",
      "1 tsp vanilla essence",
      "1/2 tsp salt",
      "1 1/2 cups fresh blueberries",
      "2 tbsp flour for coating blueberries"
    ],
    stepsRaw: [
      "Preheat oven to 400°F (200°C). Line muffin tin.",
      "Whisk flour, baking powder, baking soda and salt.",
      "Whisk melted butter and sugar until combined.",
      "Add eggs one by one, beating well after each.",
      "Mix in buttermilk and vanilla essence.",
      "Gradually fold in dry ingredients (do not overmix).",
      "Toss blueberries with 2 tbsp flour to coat.",
      "Gently fold blueberries into batter.",
      "Divide batter among muffin cups, filling each 2/3 full.",
      "Bake for 18-20 minutes until golden brown.",
      "Cool in pan for 5 minutes.",
      "Serve warm or at room temperature."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Soft, fluffy muffins bursting with fresh blueberries, perfect for breakfast or a snack.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 35,
    baseServings: 12,
    calories: 250,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "butter", "eggs", "buttermilk", "baking powder", "baking soda", "vanilla", "salt", "blueberries"],
    searchKeywords: ["blueberry muffins", "muffins", "breakfast", "snack", "blueberry bread"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cherry Almond Coffee Cake",
    image: "cherry-almond-coffee.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "3/4 cup sugar",
      "1/2 cup butter, softened",
      "2 eggs",
      "1 cup yogurt",
      "1 tsp almond essence",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "1 cup fresh or frozen cherries, pitted",
      "For topping: 1/4 cup sliced almonds, 2 tbsp sugar"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease a 9-inch square pan.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one by one.",
      "Mix in yogurt and almond essence.",
      "Whisk flour, baking powder, baking soda and salt.",
      "Gradually add dry ingredients to butter mixture.",
      "Fold in cherries.",
      "Spread batter in pan.",
      "Sprinkle with almonds and sugar.",
      "Bake for 35-40 minutes until golden brown.",
      "Cool in pan for 15 minutes before serving.",
      "Serve with coffee or tea."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A delicious cherry and almond streusel coffee cake perfect with your morning coffee.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 9,
    calories: 370,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "butter", "eggs", "yogurt", "almond extract", "baking powder", "baking soda", "salt", "cherries", "almonds"],
    searchKeywords: ["coffee cake", "cherry cake", "almond cake", "cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Swedish Princess Cake",
    image: "swedish-princess-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "For cake: 3 eggs",
      "3/4 cup sugar",
      "3/4 cup all-purpose flour",
      "1 tsp baking powder",
      "For filling: 2 cups whipped cream",
      "1 cup vanilla custard",
      "1 cup strawberry jam",
      "For covering: Marzipan (almond paste)",
      "Green food coloring"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C).",
      "Beat eggs and sugar until fluffy.",
      "Sift flour and baking powder, fold into egg mixture.",
      "Pour into cake pan.",
      "Bake for 25 minutes.",
      "Cool cake and cut into layers.",
      "Spread jam on cake layer.",
      "Add whipped cream and custard layer.",
      "Place top layer.",
      "Cover whole cake with whipped cream.",
      "Color marzipan green and roll out.",
      "Cover cake with marzipan.",
      "Decorate with marzipan rose."
    ],
    difficulty: "Hard",
    cookingTime: 120,
    isActive: true,
    isHalal: true,
    description: "A classic Swedish princess cake with layers of sponge, jam, custard, whipped cream and green marzipan.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "premium",
    costPerServing: 100,
    baseServings: 10,
    calories: 520,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["eggs", "sugar", "flour", "baking powder", "whipped cream", "custard", "strawberry jam", "marzipan", "green color"],
    searchKeywords: ["princess cake", "swedish cake", "marzipan cake", "layer cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Russian Honey Cake",
    image: "russian-honey-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "3 eggs",
      "1 cup honey",
      "1 cup sugar",
      "2 cups all-purpose flour",
      "1 tsp baking soda",
      "1/2 cup butter",
      "For cream: 2 cups sour cream",
      "1 cup whipped cream",
      "1/2 cup powdered sugar"
    ],
    stepsRaw: [
      "Melt butter, honey and sugar together.",
      "Let cool slightly.",
      "Add eggs and mix well.",
      "Mix flour and baking soda.",
      "Divide dough into 8-10 thin layers.",
      "Bake each layer for 5-7 minutes.",
      "Mix sour cream, whipped cream and powdered sugar for cream.",
      "Spread cream between cake layers.",
      "Cover top and sides with cream.",
      "Decorate with cake crumbs.",
      "Refrigerate for 12 hours before serving."
    ],
    difficulty: "Hard",
    cookingTime: 180,
    isActive: true,
    isHalal: true,
    description: "A traditional Russian honey cake with multiple thin layers and rich sour cream frosting, also known as Medovik.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 10,
    calories: 480,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["eggs", "honey", "sugar", "flour", "baking soda", "butter", "sour cream", "whipped cream", "powdered sugar"],
    searchKeywords: ["honey cake", "russian cake", "medovik", "layer cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Almond Sponge Roll",
    image: "almond-sponge-roll.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 eggs, separated",
      "3/4 cup sugar",
      "3/4 cup ground almonds",
      "1/4 cup all-purpose flour",
      "1 tsp vanilla essence",
      "For filling: 1 1/2 cups whipped cream",
      "1/2 cup powdered sugar",
      "Sliced almonds for decoration"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C).",
      "Line baking sheet with parchment paper.",
      "Beat egg whites until stiff peaks form.",
      "Gradually add sugar while beating.",
      "Add egg yolks and vanilla essence.",
      "Mix ground almonds and flour, fold into egg mixture.",
      "Spread batter on baking sheet.",
      "Bake for 10-12 minutes.",
      "Roll cake in warm towel.",
      "Let cool completely.",
      "Mix whipped cream and powdered sugar.",
      "Unroll cake, spread cream and roll again.",
      "Decorate with sliced almonds."
    ],
    difficulty: "Hard",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A light almond sponge cake rolled with sweet whipped cream, perfect for tea time.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 8,
    calories: 380,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["eggs", "sugar", "ground almonds", "flour", "vanilla", "whipped cream", "powdered sugar", "sliced almonds"],
    searchKeywords: ["sponge roll", "almond roll", "swiss roll", "cream roll", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chocolate Butter Cake",
    image: "chocolate-butter-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 3/4 cups all-purpose flour",
      "2 cups sugar",
      "3/4 cup cocoa powder",
      "1 1/2 tsp baking powder",
      "1 1/2 tsp baking soda",
      "1 tsp salt",
      "2 eggs",
      "1 cup milk",
      "1/2 cup cooking oil",
      "2 tsp vanilla essence",
      "1 cup boiling water"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease cake pans.",
      "Mix flour, sugar, cocoa, baking powder, baking soda and salt.",
      "Beat eggs, milk, oil and vanilla essence together.",
      "Add wet ingredients to dry and mix well.",
      "Add boiling water and mix (batter will be thin).",
      "Divide batter between pans.",
      "Bake for 30-35 minutes.",
      "Cool completely before frosting with chocolate buttercream."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A rich, moist and decadent chocolate butter cake perfect for chocolate lovers.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 55,
    baseServings: 10,
    calories: 420,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "cocoa", "baking powder", "baking soda", "salt", "eggs", "milk", "oil", "vanilla", "water"],
    searchKeywords: ["chocolate cake", "butter cake", "moist cake", "cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Whipped Cream Frosting",
    image: "whipped-cream-frosting.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups heavy cream",
      "1/2 cup powdered sugar",
      "1 tsp vanilla essence"
    ],
    stepsRaw: [
      "Chill bowl and beaters in refrigerator.",
      "Pour heavy cream into cold bowl.",
      "Beat on medium speed until soft peaks form.",
      "Gradually add powdered sugar while beating.",
      "Add vanilla essence.",
      "Beat until stiff peaks form.",
      "Use immediately to frost cakes.",
      "Refrigerate if not using right away."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A light, fluffy homemade whipped cream frosting perfect for cakes, cupcakes and desserts.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 2,
    calories: 280,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["cream", "powdered sugar", "vanilla"],
    searchKeywords: ["whipped cream", "frosting", "cream", "cake topping", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chocolate Fudge Cake",
    image: "chocolate-fudge-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 3/4 cups all-purpose flour",
      "2 cups sugar",
      "3/4 cup cocoa powder",
      "1 1/2 tsp baking powder",
      "1 1/2 tsp baking soda",
      "1 tsp salt",
      "2 eggs",
      "1 cup milk",
      "1/2 cup cooking oil",
      "2 tsp vanilla essence",
      "1 cup boiling water",
      "For fudge frosting: 1 cup chocolate chips, 1/2 cup cream"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Prepare cake pans.",
      "Mix dry ingredients in large bowl.",
      "Beat eggs, milk, oil and vanilla together.",
      "Add wet ingredients to dry and mix well.",
      "Add boiling water and mix until smooth.",
      "Divide batter between pans.",
      "Bake for 30-35 minutes.",
      "For frosting: Heat cream until steaming.",
      "Pour over chocolate chips, let sit 2 minutes.",
      "Whisk until smooth and glossy.",
      "Frost cooled cake with chocolate fudge."
    ],
    difficulty: "Hard",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A decadent chocolate fudge cake with rich, glossy fudge frosting for special occasions.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 10,
    calories: 520,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "cocoa", "baking powder", "baking soda", "salt", "eggs", "milk", "oil", "vanilla", "water", "chocolate chips", "cream"],
    searchKeywords: ["chocolate fudge cake", "fudge cake", "chocolate cake", "cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Lemon Drizzle Cake",
    image: "lemon-drizzle-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 3/4 cups all-purpose flour",
      "1 cup sugar",
      "1/2 cup butter, room temperature",
      "3 eggs",
      "1/2 cup milk",
      "Zest of 2 lemons",
      "Juice of 1 lemon",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "For drizzle: 1/2 cup powdered sugar, 2 tbsp lemon juice"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease loaf pan.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one by one.",
      "Mix in lemon zest and juice.",
      "Whisk flour, baking powder, baking soda and salt.",
      "Add milk and flour mixture alternately to batter.",
      "Pour batter into pan.",
      "Bake for 45-50 minutes.",
      "Mix powdered sugar and lemon juice for drizzle.",
      "Poke holes in warm cake with skewer.",
      "Pour drizzle over warm cake.",
      "Let cool completely before slicing."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A tangy and sweet lemon drizzle cake with a crisp sugary crust and moist citrusy interior.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 8,
    calories: 350,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "butter", "eggs", "milk", "lemon zest", "lemon juice", "baking powder", "baking soda", "salt", "powdered sugar"],
    searchKeywords: ["lemon cake", "lemon drizzle", "citrus cake", "cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Carrot Cake",
    image: "carrot-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups grated carrots",
      "2 cups all-purpose flour",
      "1 1/2 cups sugar",
      "1 cup cooking oil",
      "4 eggs",
      "1 cup chopped walnuts",
      "1 tsp baking powder",
      "1 tsp baking soda",
      "1 tsp cinnamon powder",
      "1/2 tsp nutmeg powder",
      "1/2 tsp salt",
      "For cream cheese frosting: 200g cream cheese, 1/2 cup butter, 2 cups powdered sugar"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease cake pans.",
      "Beat eggs and sugar until fluffy.",
      "Add oil and mix well.",
      "Mix flour, baking powder, baking soda, cinnamon, nutmeg and salt.",
      "Add dry ingredients to egg mixture.",
      "Fold in carrots and walnuts.",
      "Divide batter between pans.",
      "Bake for 30-35 minutes.",
      "For frosting: Beat cream cheese and butter until smooth.",
      "Gradually add powdered sugar.",
      "Frost cooled cake layers.",
      "Decorate with extra walnuts."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A spiced carrot cake with creamy cheese frosting and crunchy walnuts, perfect for any occasion.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 65,
    baseServings: 10,
    calories: 490,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["carrots", "flour", "sugar", "oil", "eggs", "walnuts", "baking powder", "baking soda", "cinnamon", "nutmeg", "salt", "cream cheese", "butter", "powdered sugar"],
    searchKeywords: ["carrot cake", "cream cheese cake", "spiced cake", "cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Marble Cake",
    image: "marble-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1 1/2 cups sugar",
      "1 cup butter, room temperature",
      "4 eggs",
      "1 cup milk",
      "1 tsp vanilla essence",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "1/4 cup cocoa powder",
      "2 tbsp hot water"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease bundt pan.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one by one.",
      "Mix in vanilla essence.",
      "Whisk flour, baking powder, baking soda and salt.",
      "Add milk and flour mixture alternately to batter.",
      "Divide batter in half.",
      "Mix cocoa powder and hot water, add to one half.",
      "Alternate spoonfuls of vanilla and chocolate batter in pan.",
      "Swirl with knife for marble effect.",
      "Bake for 45-50 minutes.",
      "Cool in pan for 15 minutes."
    ],
    difficulty: "Medium",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A beautiful marble cake with swirls of vanilla and chocolate, perfect for tea time.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 10,
    calories: 420,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "butter", "eggs", "milk", "vanilla", "baking powder", "baking soda", "salt", "cocoa", "water"],
    searchKeywords: ["marble cake", "vanilla chocolate cake", "swirl cake", "cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Coconut Cake",
    image: "coconut-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1 1/2 cups sugar",
      "1 cup butter, room temperature",
      "4 eggs",
      "1 cup coconut milk",
      "1 cup grated coconut",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "1 tsp vanilla essence",
      "For frosting: 2 cups whipped cream, 1 cup grated coconut"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease cake pans.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one by one.",
      "Mix in vanilla essence.",
      "Whisk flour, baking powder, baking soda and salt.",
      "Add coconut milk and flour mixture alternately.",
      "Fold in grated coconut.",
      "Divide batter between pans.",
      "Bake for 25-30 minutes.",
      "Cool completely.",
      "Frost with whipped cream.",
      "Coat with grated coconut."
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A moist coconut cake with creamy whipped cream frosting and shredded coconut, perfect for coconut lovers.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 55,
    baseServings: 10,
    calories: 460,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "butter", "eggs", "coconut milk", "coconut", "baking powder", "baking soda", "salt", "vanilla", "whipped cream"],
    searchKeywords: ["coconut cake", "coconut cream cake", "cake", "dessert", "coconut dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Strawberry Shortcake",
    image: "strawberry-shortcake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1/3 cup sugar",
      "1 tbsp baking powder",
      "1/2 tsp salt",
      "1/2 cup cold butter",
      "2/3 cup milk",
      "1 egg",
      "For filling: 2 cups sliced strawberries, 2 tbsp sugar",
      "For cream: 2 cups whipped cream"
    ],
    stepsRaw: [
      "Preheat oven to 425°F (220°C).",
      "Mix flour, sugar, baking powder and salt.",
      "Cut cold butter into flour mixture.",
      "Beat milk and egg together, add to flour mixture.",
      "Knead gently, roll out and cut into circles.",
      "Bake for 15 minutes until golden.",
      "Mix strawberries with sugar.",
      "Split shortcakes in half.",
      "Fill with whipped cream and strawberries.",
      "Top with other half.",
      "Serve immediately."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "A classic strawberry shortcake with tender biscuit layers, fresh strawberries and whipped cream.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 6,
    calories: 420,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "baking powder", "salt", "cold butter", "milk", "egg", "strawberries", "whipped cream"],
    searchKeywords: ["strawberry shortcake", "shortcake", "strawberry dessert", "dessert", "summer dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Pineapple Upside Down Cake",
    image: "pineapple-upside-down-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "For topping: 1/4 cup butter",
      "1/2 cup brown sugar",
      "6-7 pineapple rings",
      "Maraschino cherries",
      "For cake: 1 1/2 cups all-purpose flour",
      "1 cup sugar",
      "1/2 cup butter, room temperature",
      "2 eggs",
      "1/2 cup pineapple juice",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C).",
      "Melt butter in cake pan.",
      "Sprinkle brown sugar over butter.",
      "Arrange pineapple rings and cherries.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one by one.",
      "Whisk flour, baking powder, baking soda and salt.",
      "Add pineapple juice and flour mixture alternately.",
      "Pour batter over pineapple arrangement.",
      "Bake for 35-40 minutes.",
      "Immediately invert onto serving plate.",
      "Serve warm."
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A classic pineapple upside down cake with caramelized pineapple rings and cherries, best served warm.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 8,
    calories: 420,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["butter", "brown sugar", "pineapple", "cherries", "flour", "sugar", "eggs", "pineapple juice", "baking powder", "baking soda", "salt"],
    searchKeywords: ["pineapple cake", "upside down cake", "pineapple dessert", "cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Fluffy Vanilla Cake",
    image: "fluffy-vanilla-cake.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 1/4 cups all-purpose flour",
      "1 1/2 cups sugar",
      "3/4 cup butter, room temperature",
      "3 eggs",
      "1 cup milk",
      "2 1/2 tsp baking powder",
      "1/2 tsp salt",
      "2 tsp vanilla essence"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease cake pans.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one by one.",
      "Mix in vanilla essence.",
      "Whisk flour, baking powder and salt.",
      "Add milk and flour mixture alternately.",
      "Divide batter between pans.",
      "Bake for 25-30 minutes.",
      "Cool completely before frosting."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "An extra fluffy and light vanilla layer cake perfect for birthdays and celebrations.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 8,
    calories: 400,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "butter", "eggs", "milk", "baking powder", "salt", "vanilla"],
    searchKeywords: ["vanilla cake", "fluffy cake", "cake", "birthday cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "French Heart Puff",
    image: "french-heart-puff.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 sheet puff pastry",
      "1 cup chocolate hazelnut spread",
      "1 egg, beaten",
      "1 tbsp milk",
      "Powdered sugar for dusting"
    ],
    stepsRaw: [
      "Preheat oven to 400°F (200°C).",
      "Roll out puff pastry.",
      "Cut heart shapes with cookie cutter.",
      "Spread chocolate on half the hearts.",
      "Top with remaining hearts.",
      "Seal edges with fork.",
      "Mix egg and milk, brush on pastries.",
      "Bake for 15-20 minutes until puffed and golden.",
      "Dust with powdered sugar.",
      "Serve warm."
    ],
    difficulty: "Easy",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Flaky puff pastry hearts filled with chocolate hazelnut spread, perfect for Valentine's Day or any special occasion.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 6,
    calories: 320,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["puff pastry", "chocolate spread", "egg", "milk", "powdered sugar"],
    searchKeywords: ["puff pastry hearts", "chocolate hearts", "french pastry", "dessert", "snack"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cake Rusk",
    image: "cake-rusk.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "Leftover cake or plain cake",
      "1/2 cup sugar",
      "1/2 cup milk",
      "1/2 tsp cardamom powder",
      "Ghee for frying"
    ],
    stepsRaw: [
      "Cut cake into 1-inch thick slices.",
      "Boil sugar and milk to make syrup.",
      "Add cardamom powder to syrup.",
      "Dip cake slices in syrup briefly.",
      "Heat ghee in pan.",
      "Fry cake slices until golden brown.",
      "Drain on paper towels.",
      "Let cool completely.",
      "Store in airtight container.",
      "Serve with tea."
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Crispy twice-baked cake rusks flavored with cardamom, perfect for dipping in tea.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 6,
    calories: 180,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["cake", "sugar", "milk", "cardamom", "ghee"],
    searchKeywords: ["cake rusk", "rusk", "tea rusk", "pakistani snack", "biscuit"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
];

async function migrateRecipes() {
  try {
    console.log('Connecting to MongoDB');
    
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) {
      throw new Error('MongoDB URI not found');
    }
    
    await mongoose.connect(mongoURI, { 
      serverSelectionTimeoutMS: 10000, 
      family: 4 
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();