const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
  {
    title: "Tikka",
    image: "chicken-tikka-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - bone-in pieces (thighs and drumsticks work best)",
      "1 cup plain yogurt (beaten until smooth)",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons lemon juice",
      "2 teaspoons red chili powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1 teaspoon salt",
      "2 tablespoons oil",
      "1 teaspoon chaat masala",
      "Charcoal for smoking (if you want)"
    ],
    stepsRaw: [
      "Wash the chicken pieces and pat them dry with paper towels. Make deep cuts on each piece so the marinade goes inside.",
      "In a large bowl, whisk the yogurt until smooth. Add ginger-garlic paste, lemon juice, red chili powder, turmeric, cumin powder, coriander powder, garam masala, salt, and oil.",
      "Mix everything well to make a smooth marinade.",
      "Add the chicken pieces to the marinade and coat them well. Massage the marinade into the cuts.",
      "Cover and put in the fridge for 4-6 hours (overnight is best for more flavor).",
      "For smoky flavor: Heat a small piece of charcoal until it is red hot. Put it in a small bowl inside the marinade bowl. Pour 1 teaspoon of ghee over the charcoal and cover the bowl right away. Let the smoke go in for 5-7 minutes.",
      "Heat your grill to medium-high heat (about 200°C/400°F). If using an oven, heat it to 220°C (425°F).",
      "Put the marinated chicken pieces onto skewers or place them directly on the grill.",
      "Grill for 15-20 minutes, turning every 5 minutes, until the chicken is charred on the outside and cooked through inside.",
      "Brush with oil while grilling to keep it moist.",
      "Take off the grill and sprinkle chaat masala over the hot tikka.",
      "Serve hot with mint chutney, onion rings, and lemon wedges."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A classic Pakistani BBQ dish — juicy chicken marinated in spiced yogurt and grilled to smoky perfection. Great for gatherings and special occasions.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 180,
    baseServings: 4,
    calories: 280,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "ginger", "garlic", "lemon", "red chili", "turmeric", "cumin", "coriander", "garam masala", "oil", "chaat masala"],
    searchKeywords: ["tikka", "chicken", "bbq", "grilled", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Malai Tikka",
    image: "malai-tikka.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg boneless chicken - cut into 1-inch pieces",
      "1 cup heavy cream",
      "1/2 cup plain yogurt",
      "2 tablespoons ginger paste",
      "2 tablespoons garlic paste",
      "2 tablespoons green chili paste",
      "1 teaspoon white pepper powder",
      "1 teaspoon cardamom powder",
      "1 teaspoon salt",
      "2 tablespoons oil",
      "2 tablespoons lemon juice",
      "Charcoal for smoking (if you want)"
    ],
    stepsRaw: [
      "Cut the boneless chicken into 1-inch pieces. Pat them dry with paper towels.",
      "In a bowl, mix cream, yogurt, ginger paste, garlic paste, green chili paste, white pepper, cardamom powder, salt, oil, and lemon juice.",
      "Whisk until smooth and well combined.",
      "Add the chicken pieces to the marinade and mix gently to coat every piece.",
      "Cover and put in the fridge for 4-6 hours.",
      "For smoky flavor: Heat charcoal until red hot, put in a bowl with ghee inside the marinade bowl, cover for 5 minutes.",
      "Heat the grill to medium heat (180°C/350°F).",
      "Put the chicken pieces onto skewers, leaving a little space between them so they cook evenly.",
      "Grill for 12-15 minutes, turning now and then, until the chicken is golden and cooked through.",
      "Brush with oil or butter while grilling for extra moisture.",
      "The tikka should be white/creamy in color, not charred.",
      "Serve hot with green chutney and naan."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "A rich and creamy white chicken tikka marinated in heavy cream, yogurt, and mild spices. Soft, juicy, and great for those who like less heat.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 200,
    baseServings: 4,
    calories: 310,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "cream", "yogurt", "ginger", "garlic", "green chili", "white pepper", "cardamom", "oil", "lemon"],
    searchKeywords: ["malai tikka", "white tikka", "creamy tikka", "chicken", "bbq"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Hariyali Tikka",
    image: "fish-haryali-tikka.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - boneless, cut into pieces",
      "1 cup fresh coriander leaves",
      "1 cup fresh mint leaves",
      "4 green chilies",
      "2 tablespoons ginger-garlic paste",
      "1/2 cup plain yogurt",
      "1 teaspoon cumin powder",
      "1 teaspoon chaat masala",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "In a blender, put coriander leaves, mint leaves, and green chilies. Blend into a smooth paste using a little water if needed.",
      "In a bowl, mix the green paste with yogurt, ginger-garlic paste, cumin powder, chaat masala, salt, and oil.",
      "Add the chicken pieces and mix well to coat completely. The marinade should be bright green.",
      "Cover and put in the fridge for 4 hours.",
      "Heat the grill to medium-high heat.",
      "Put the chicken onto skewers.",
      "Grill for 12-15 minutes, turning often, until the chicken is charred and cooked through.",
      "The green color will get darker.",
      "Serve hot with onion rings and mint chutney."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "A bright green chicken tikka marinated in fresh coriander, mint, and green chilies. Full of herby freshness and smoky grill flavor.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 180,
    baseServings: 4,
    calories: 260,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "coriander", "mint", "green chili", "ginger", "garlic", "yogurt", "cumin", "chaat masala", "oil"],
    searchKeywords: ["hariyali tikka", "green tikka", "herb tikka", "chicken", "bbq"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Achari Tikka",
    image: "achari-tikka.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - bone-in pieces",
      "1 cup plain yogurt",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons pickle masala (achari masala)",
      "1 teaspoon fennel seeds",
      "1 teaspoon mustard seeds",
      "1 teaspoon fenugreek seeds",
      "1 teaspoon red chili powder",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "In a small pan, dry roast fennel seeds, mustard seeds, and fenugreek seeds for 1-2 minutes until they smell good. Let them cool, then grind to a coarse powder.",
      "In a bowl, mix yogurt, ginger-garlic paste, pickle masala, ground spices, red chili powder, salt, and oil.",
      "Make deep cuts on the chicken pieces. Add to the marinade and coat well.",
      "Cover and put in the fridge for 4-6 hours.",
      "Heat the grill to medium-high heat.",
      "Grill the chicken for 15-20 minutes, turning now and then, until charred and cooked through.",
      "The tikka will have a tangy pickle-like taste.",
      "Serve hot with mint chutney and salad."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A tangy and spicy chicken tikka marinated with achari masala and roasted pickle spices. Bold flavors of fennel, mustard, and fenugreek give it a pickle taste.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 190,
    baseServings: 4,
    calories: 270,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "ginger", "garlic", "pickle masala", "fennel", "mustard", "fenugreek", "red chili", "oil"],
    searchKeywords: ["achari tikka", "pickle tikka", "tangy tikka", "chicken", "bbq"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Afghani Tikka",
    image: "chicken-tikka-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - boneless, cut into pieces",
      "1 cup heavy cream",
      "1/2 cup plain yogurt",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon white pepper powder",
      "1 teaspoon cardamom powder",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "In a bowl, mix cream, yogurt, ginger-garlic paste, white pepper, cardamom powder, salt, and oil.",
      "Add the chicken pieces and mix well to coat.",
      "Cover and put in the fridge for 4 hours.",
      "Heat the grill to medium heat.",
      "Put the chicken onto skewers.",
      "Grill for 12-15 minutes until golden and cooked through. Do not over-char.",
      "The tikka should stay light in color.",
      "Serve hot with naan and garlic yogurt sauce."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "A creamy and mild Afghani-style chicken tikka marinated in heavy cream, yogurt, and aromatic spices. Light in color, rich in taste — great for those who like mild flavors.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 210,
    baseServings: 4,
    calories: 300,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "cream", "yogurt", "ginger", "garlic", "white pepper", "cardamom", "oil"],
    searchKeywords: ["afghani tikka", "creamy tikka", "mild tikka", "chicken", "bbq"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Balochi Tikka",
    image: "chicken-tikka-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton or beef - boneless pieces",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons red chili powder",
      "1 tablespoon coriander powder",
      "1 teaspoon cumin powder",
      "1 teaspoon black pepper powder",
      "2 tablespoons mustard oil",
      "Salt to taste",
      "Charcoal for smoking"
    ],
    stepsRaw: [
      "In a bowl, mix ginger-garlic paste, red chili powder, coriander powder, cumin powder, black pepper, mustard oil, and salt.",
      "Add the meat pieces and coat well. Mustard oil gives a special flavor.",
      "Cover and put in the fridge overnight (8-10 hours) for the best results.",
      "Add charcoal smoke for extra flavor if you want.",
      "Heat the charcoal grill to high heat.",
      "Put the meat onto skewers.",
      "Grill for 15-20 minutes for mutton (10-12 for beef), turning often, until charred and tender.",
      "Serve hot with naan and spicy chutney."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A bold and spicy Balochistan-style tikka made with mutton or beef. Marinated overnight in red chili and mustard oil, then grilled on charcoal for a strong smoky flavor.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 250,
    baseServings: 4,
    calories: 350,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "beef", "ginger", "garlic", "red chili", "coriander", "cumin", "black pepper", "mustard oil", "charcoal"],
    searchKeywords: ["balochi tikka", "mutton", "beef", "bbq", "spicy"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Chicken Boti",
    image: "chicken-boti-kebab.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg boneless chicken - cut into 1-inch pieces",
      "1 cup plain yogurt",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons lemon juice",
      "2 teaspoons red chili powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon cumin powder",
      "1 teaspoon garam masala",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "In a bowl, mix yogurt, ginger-garlic paste, lemon juice, red chili powder, turmeric, cumin, garam masala, salt, and oil.",
      "Add the chicken pieces and mix well to coat evenly.",
      "Cover and put in the fridge for 4 hours.",
      "Heat the grill to medium-high heat.",
      "Put the chicken pieces onto skewers, leaving small gaps between them.",
      "Grill for 12-15 minutes, turning every 3-4 minutes, until charred and cooked through.",
      "Brush with oil while grilling to keep it moist.",
      "Serve hot with mint chutney and onion rings."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Classic Pakistani boneless chicken boti marinated in spiced yogurt and grilled to juicy perfection. A crowd-pleasing BBQ favorite.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 180,
    baseServings: 4,
    calories: 260,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "ginger", "garlic", "lemon", "red chili", "turmeric", "cumin", "garam masala", "oil"],
    searchKeywords: ["chicken boti", "boti", "chicken", "bbq", "grilled"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Malai Boti",
    image: "chicken-malai-boti.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg boneless chicken - cut into pieces",
      "1 cup heavy cream",
      "1/2 cup plain yogurt",
      "2 tablespoons ginger paste",
      "2 tablespoons garlic paste",
      "1 teaspoon white pepper powder",
      "1 teaspoon cardamom powder",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Mix cream, yogurt, ginger paste, garlic paste, white pepper, cardamom, salt, and oil in a bowl.",
      "Add the chicken pieces and coat well.",
      "Marinate for 4 hours in the fridge.",
      "Heat the grill to medium heat.",
      "Put the chicken onto skewers.",
      "Grill for 10-12 minutes until golden and cooked through.",
      "Do not over-char - the boti should stay light in color.",
      "Serve hot with garlic yogurt sauce and naan."
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Melt-in-your-mouth creamy chicken boti marinated in heavy cream and mild aromatic spices. Soft, juicy, and very rich.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 210,
    baseServings: 4,
    calories: 310,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "cream", "yogurt", "ginger", "garlic", "white pepper", "cardamom", "oil"],
    searchKeywords: ["malai boti", "creamy boti", "white boti", "chicken", "bbq"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Achari Boti",
    image: "achari-tikka.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg boneless chicken - pieces",
      "1 cup plain yogurt",
      "2 tablespoons pickle masala",
      "1 teaspoon fennel seeds - crushed",
      "1 teaspoon mustard seeds - crushed",
      "1 teaspoon red chili powder",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Crush fennel and mustard seeds coarsely.",
      "Mix yogurt, pickle masala, crushed seeds, red chili, salt, and oil.",
      "Add the chicken pieces and coat well.",
      "Marinate for 4 hours.",
      "Grill on medium-high heat for 12-15 minutes until charred.",
      "Serve hot with salad."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Tangy and spicy chicken boti with a strong pickle flavor. Crushed fennel and mustard seeds give it a special achari taste that BBQ lovers will enjoy.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 185,
    baseServings: 4,
    calories: 255,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "pickle masala", "fennel", "mustard", "red chili", "oil"],
    searchKeywords: ["achari boti", "pickle boti", "tangy boti", "chicken", "bbq"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Beef Boti",
    image: "beef-boti-kebab.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg beef - sirloin or tenderloin, cut into 1-inch pieces",
      "1 cup plain yogurt",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons raw papaya paste (to tenderize the meat)",
      "2 teaspoons red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon garam masala",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Papaya paste is important for making beef tender. Grate raw papaya and make a paste.",
      "In a bowl, mix yogurt, ginger-garlic paste, papaya paste, red chili, cumin, garam masala, salt, and oil.",
      "Add the beef pieces and coat well. Massage the marinade into the meat.",
      "Cover and put in the fridge for 6-8 hours or overnight.",
      "Heat the grill to medium-high heat.",
      "Put the beef onto skewers.",
      "Grill for 15-18 minutes for medium doneness, turning often.",
      "Do not overcook or the beef will become tough.",
      "Serve hot with naan and mint chutney."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Juicy and tender beef boti marinated overnight with raw papaya and spiced yogurt. Slow-grilled on charcoal for a rich, smoky BBQ flavor.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 280,
    baseServings: 4,
    calories: 370,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["beef", "yogurt", "ginger", "garlic", "papaya", "red chili", "cumin", "garam masala", "oil"],
    searchKeywords: ["beef boti", "boti", "beef", "bbq", "grilled"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Chicken Seekh Kebab",
    image: "chicken-seekh-kebab.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken mince (keema)",
      "1 medium onion - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "2 green chilies - finely chopped",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "1/2 teaspoon garam masala",
      "1/2 teaspoon chaat masala",
      "2 tablespoons fresh coriander - chopped",
      "1 tablespoon fresh mint - chopped",
      "1 large egg (to bind the mixture)",
      "Salt to taste",
      "2 tablespoons oil for basting"
    ],
    stepsRaw: [
      "In a large bowl, put the chicken mince. Make sure the mince has no extra water.",
      "Add finely chopped onions, ginger-garlic paste, green chilies, cumin powder, coriander powder, red chili powder, garam masala, chaat masala, fresh coriander, mint, and salt.",
      "Add the egg and mix everything well with your hands.",
      "Knead the mixture for 8-10 minutes until it becomes sticky and binds together. This step is important for soft kebabs.",
      "Cover and put in the fridge for 1 hour to let the flavors develop.",
      "Wet your hands with water. Take a portion of the mixture and shape it onto a skewer like a sausage, about 6 inches long.",
      "Do the same with the rest of the mixture.",
      "Heat the grill to medium heat or heat a tawa (flat pan).",
      "If grilling: Cook on medium heat for 10-12 minutes, turning often, until evenly browned and cooked through.",
      "If using a tawa: Shallow fry with oil until golden on all sides.",
      "Brush with oil while cooking to keep the kebabs moist.",
      "Serve hot with mint chutney, onion rings, and lemon wedges."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Soft and juicy chicken seekh kebabs made with spiced minced chicken shaped onto skewers. A classic Pakistani BBQ favorite served with mint chutney.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["eggs"],
    budget: "standard",
    costPerServing: 160,
    baseServings: 4,
    calories: 240,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken mince", "onion", "ginger", "garlic", "green chili", "cumin", "coriander", "red chili", "garam masala", "chaat masala", "egg", "mint", "oil"],
    searchKeywords: ["seekh kebab", "chicken", "bbq", "grilled", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Mutton Seekh Kebab",
    image: "mutton-seekh-kebab.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince (keema)",
      "1 medium onion - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "2 green chilies - finely chopped",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "1/2 teaspoon garam masala",
      "2 tablespoons fresh coriander - chopped",
      "1 teaspoon salt",
      "1 egg",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Make sure the mutton mince is fresh and well-drained.",
      "Mix all the ingredients together in a bowl. Knead well for 8-10 minutes.",
      "Put in the fridge for 1 hour.",
      "Shape onto skewers like sausages.",
      "Grill on medium heat for 12-15 minutes, turning often, until charred and cooked.",
      "Brush with oil while grilling.",
      "Serve hot with mint chutney."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Rich and spicy mutton seekh kebabs full of strong flavors. Slow-grilled on charcoal for a deep smoky taste — a true BBQ classic.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["eggs"],
    budget: "standard",
    costPerServing: 220,
    baseServings: 4,
    calories: 290,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "onion", "ginger", "garlic", "green chili", "cumin", "coriander", "red chili", "garam masala", "egg", "oil"],
    searchKeywords: ["seekh kebab", "mutton", "bbq", "grilled", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Beef Seekh Kebab",
    image: "beef-seekh-kebab.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g beef mince (keema)",
      "1 medium onion - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "2 green chilies - finely chopped",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "1/2 teaspoon garam masala",
      "2 tablespoons fresh coriander",
      "1 teaspoon salt",
      "1 egg",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Mix all the ingredients in a bowl. Knead well for 10 minutes.",
      "Put in the fridge for 1 hour.",
      "Shape onto skewers.",
      "Grill on medium heat for 12-15 minutes until cooked through.",
      "Serve with chutney."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Hearty and tasty beef seekh kebabs made with spiced mince and grilled to perfection. A filling BBQ dish loved across Pakistan.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["eggs"],
    budget: "standard",
    costPerServing: 240,
    baseServings: 4,
    calories: 310,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["beef mince", "onion", "ginger", "garlic", "green chili", "cumin", "coriander", "red chili", "garam masala", "egg", "oil"],
    searchKeywords: ["seekh kebab", "beef", "bbq", "grilled", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Hariyali Seekh Kebab",
    image: "haryali-seekh-kebab.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken or mutton mince",
      "1 cup fresh coriander leaves",
      "1/2 cup fresh mint leaves",
      "4 green chilies",
      "1 medium onion - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon chaat masala",
      "1 teaspoon salt",
      "1 egg",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Grind coriander, mint, and green chilies into a smooth paste.",
      "Mix the green paste with mince, onions, ginger-garlic paste, cumin, chaat masala, salt, and egg.",
      "Knead well for 8-10 minutes.",
      "Put in the fridge for 1 hour.",
      "Shape onto skewers.",
      "Grill on medium heat for 10-12 minutes until cooked and slightly charred.",
      "Serve hot with mint chutney."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Bright green seekh kebabs full of fresh coriander, mint, and green chili. Aromatic, herby, and perfectly charred on the grill.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["eggs"],
    budget: "standard",
    costPerServing: 180,
    baseServings: 4,
    calories: 250,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken mince", "mutton mince", "coriander", "mint", "green chili", "onion", "ginger", "garlic", "cumin", "chaat masala", "egg", "oil"],
    searchKeywords: ["hariyali seekh kebab", "green kebab", "herb kebab", "bbq", "grilled"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Cheese Seekh Kebab",
    image: "cheese-seekh-kebab.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken mince",
      "100g cheese - cut into small pieces (mozzarella or cheddar)",
      "1 medium onion - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "2 green chilies - finely chopped",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "1 teaspoon salt",
      "2 tablespoons fresh coriander",
      "1 egg"
    ],
    stepsRaw: [
      "Mix mince with all the ingredients except cheese. Knead well for 8-10 minutes.",
      "Take a portion of the mince mixture and flatten it in your palm.",
      "Put a cheese piece in the center and wrap the mince around it completely.",
      "Gently shape it into a sausage on a skewer.",
      "Do the same with the rest of the mixture and cheese.",
      "Grill on medium heat for 10-12 minutes until cooked and the cheese starts to melt.",
      "Serve hot - the cheese will be gooey and melted inside."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Juicy chicken seekh kebabs stuffed with melted cheese — a family favorite, especially for kids!",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "teens", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken mince", "cheese", "onion", "ginger garlic", "green chili", "cumin", "coriander", "red chili", "egg"],
    searchKeywords: ["cheese kebab", "seekh kebab", "chicken", "bbq", "kids"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
  },
  {
    title: "Chapli",
    image: "chapli-kebab-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g beef mince (keema)",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "2 green chilies - finely chopped",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "1 teaspoon pomegranate seeds (anardana) - crushed",
      "1 teaspoon garam masala",
      "2 tablespoons fresh coriander - chopped",
      "2 tablespoons fresh mint - chopped",
      "4 tablespoons cornflour (to bind the kebab)",
      "1 large egg",
      "Salt to taste",
      "Oil for shallow frying"
    ],
    stepsRaw: [
      "In a large bowl, put the beef mince. Make sure the mince is well-drained.",
      "Add finely chopped onions, tomatoes, ginger-garlic paste, green chilies, cumin powder, coriander powder, red chili powder, crushed anardana, garam masala, fresh coriander, mint, cornflour, egg, and salt.",
      "Mix everything well with your hands. Do not over-knead because chapli kebabs should have a coarse texture.",
      "Cover and put in the fridge for 30 minutes to let the flavors mix.",
      "Take a portion of the mixture (about the size of a tennis ball) and flatten it into a patty about 1/2 inch thick.",
      "Heat oil in a shallow pan over medium heat.",
      "Gently put the patties in the hot oil. Do not overcrowd the pan.",
      "Cook for 4-5 minutes on each side until golden brown and crispy.",
      "The edges should be crisp while the inside stays soft.",
      "Drain on paper towels.",
      "Serve hot with naan, raita, and fresh salad."
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Famous Peshawari chapli kebab – crispy on the outside, soft and juicy inside. Made with beef mince and aromatic spices.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["eggs"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["beef mince", "onion", "tomato", "ginger garlic", "green chili", "cumin", "coriander", "red chili", "anardana", "garam masala", "cornflour", "egg", "mint"],
    searchKeywords: ["chapli kebab", "peshawari kebab", "beef", "crispy", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Chicken Chapli Kebab",
    image: "chicken-chapli-kebab.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken mince",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "2 green chilies - finely chopped",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "1 teaspoon anardana - crushed",
      "2 tablespoons fresh coriander",
      "3 tablespoons cornflour",
      "1 egg",
      "Salt to taste",
      "Oil for frying"
    ],
    stepsRaw: [
      "Mix all the ingredients in a bowl. Do not over-knead.",
      "Let it rest for 30 minutes.",
      "Shape into patties.",
      "Shallow fry until golden brown and crispy on both sides.",
      "Serve hot with chutney."
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Lighter chicken version of the classic chapli kebab – crispy edges, soft center, and full of flavor.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["eggs"],
    budget: "standard",
    costPerServing: 140,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken mince", "onion", "tomato", "ginger garlic", "green chili", "cumin", "coriander", "red chili", "anardana", "cornflour", "egg"],
    searchKeywords: ["chicken chapli kebab", "chapli kebab", "chicken", "crispy", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Peshawari Chapli Kebab",
    image: "chicken-chapli-kebab.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g beef mince (with some fat is better)",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "2 green chilies - finely chopped",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "1 tablespoon anardana (pomegranate seeds) - crushed",
      "2 tablespoons cornflour",
      "1 egg",
      "Salt to taste",
      "Oil for frying"
    ],
    stepsRaw: [
      "Mix all the ingredients well.",
      "Let it rest for 30 minutes.",
      "Shape into round patties.",
      "Shallow fry on low-medium heat until golden and crisp.",
      "Serve with naan."
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Authentic Peshawari style chapli kebab with crushed anardana and traditional spices. Crispy, juicy, and full of flavor.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["eggs"],
    budget: "standard",
    costPerServing: 160,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["beef mince", "onion", "tomato", "ginger garlic", "green chili", "cumin", "coriander", "red chili", "anardana", "cornflour", "egg"],
    searchKeywords: ["peshawari chapli kebab", "chapli kebab", "beef", "crispy", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Bihari",
    image: "behari-boti.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g beef - thinly sliced (flank or sirloin)",
      "1 cup plain yogurt",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons raw papaya paste (tenderizer)",
      "2 teaspoons red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1 teaspoon salt",
      "2 tablespoons oil",
      "1 teaspoon chaat masala"
    ],
    stepsRaw: [
      "Pound the beef slices with a meat mallet to make them even thinner. This makes them tender.",
      "In a bowl, mix yogurt, ginger-garlic paste, papaya paste, red chili powder, cumin, coriander, garam masala, salt, and oil.",
      "Add the beef slices and coat well. Make sure each slice is well-coated.",
      "Cover and put in the fridge for 6-8 hours (overnight is best).",
      "Heat the grill to medium-high heat.",
      "Put the marinated beef slices onto flat skewers (seekh style), weaving them back and forth.",
      "Grill for 8-10 minutes, turning often, until charred and cooked through.",
      "Do not overcook or the beef will become tough.",
      "Sprinkle chaat masala and serve hot with mint chutney and naan."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Famous Bihari kebabs – thinly sliced beef marinated with papaya and spices, grilled to perfection. Melt-in-mouth tender.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 200,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["beef", "yogurt", "ginger garlic", "papaya", "red chili", "cumin", "coriander", "garam masala", "chaat masala"],
    searchKeywords: ["bihari kebab", "beef", "melt in mouth", "bbq", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Chicken Bihari Kebab",
    image: "chicken-behari-kebab.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken breast - thinly sliced",
      "1 cup yogurt",
      "2 tablespoons ginger-garlic paste",
      "1 tablespoon papaya paste",
      "2 teaspoons red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Pound the chicken slices thin.",
      "Mix all the marinade ingredients.",
      "Marinate the chicken for 4 hours.",
      "Put onto skewers.",
      "Grill for 6-8 minutes until cooked.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Lighter chicken version of Bihari kebab – tender, juicy, and full of flavor. Quicker to make.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 170,
    baseServings: 4,
    calories: 340,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken breast", "yogurt", "ginger garlic", "papaya", "red chili", "cumin"],
    searchKeywords: ["chicken bihari kebab", "bihari kebab", "chicken", "bbq", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Bihari Boti",
    image: "behari-boti.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g beef - cut into 1-inch pieces",
      "1 cup yogurt",
      "2 tablespoons ginger-garlic paste",
      "1 tablespoon papaya paste",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Mix all the marinade ingredients.",
      "Add the beef pieces and marinate for 6 hours.",
      "Put onto skewers.",
      "Grill for 12-15 minutes until tender.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Bihari style boti – tender beef pieces marinated in spiced yogurt and grilled to perfection.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 180,
    baseServings: 4,
    calories: 400,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["beef cubes", "yogurt", "ginger garlic", "papaya", "red chili", "garam masala"],
    searchKeywords: ["bihari boti", "beef", "boti", "bbq", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Tandoori Chicken Legs",
    image: "tandoori-chicken-legs.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "6 chicken legs (drumsticks or thighs)",
      "1 cup plain yogurt",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons tandoori masala",
      "2 teaspoons red chili powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon cumin powder",
      "1 teaspoon salt",
      "2 tablespoons oil",
      "Red food color - a little bit (if you want)"
    ],
    stepsRaw: [
      "Make deep cuts on the chicken legs so the marinade can go inside.",
      "In a bowl, mix yogurt, ginger-garlic paste, tandoori masala, red chili powder, turmeric, cumin, salt, oil, and food color if using.",
      "Apply the marinade well to the chicken legs, getting it into the cuts.",
      "Cover and put in the fridge for 4-6 hours.",
      "Heat the grill to medium heat (180°C/350°F).",
      "Put the chicken legs on the grill.",
      "Grill for 20-25 minutes, turning every 5-6 minutes, until charred and cooked through.",
      "Brush with oil while grilling to keep them moist.",
      "The inside temperature should reach 75°C (165°F).",
      "Serve hot with mint chutney and onion rings."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Classic tandoori chicken legs – juicy, smoky, and full of traditional BBQ flavors. Great for family dinners.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 350,
    ageGroup: ["adults", "teens", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken legs", "yogurt", "ginger garlic", "tandoori masala", "red chili", "turmeric", "cumin"],
    searchKeywords: ["tandoori chicken", "chicken legs", "bbq", "grilled", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Chicken Leg Piece",
    image: "tandoori-chicken-legs.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "4 chicken legs",
      "1 cup yogurt",
      "2 tablespoons ginger-garlic paste",
      "2 teaspoons red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Marinate the chicken legs with all the ingredients for 4 hours.",
      "Grill on medium heat for 20 minutes until cooked.",
      "Serve with salad."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Simple and tasty grilled chicken legs with a basic spiced yogurt marinade. Great for a quick BBQ.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 300,
    ageGroup: ["adults", "teens", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken legs", "yogurt", "ginger garlic", "red chili", "cumin", "coriander"],
    searchKeywords: ["chicken leg", "grilled chicken", "bbq", "simple", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Hariyali Chicken Leg",
    image: "haryali-chicken-leg-platter.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "4 chicken legs",
      "1 cup coriander-mint chutney",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon chaat masala",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Mix the chutney with ginger-garlic, cumin, chaat masala, salt, and oil.",
      "Marinate the chicken legs for 4 hours.",
      "Grill until charred and cooked through.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Herby green marinated chicken legs with coriander-mint chutney. Fresh, tasty, and colorful.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 130,
    baseServings: 4,
    calories: 310,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken legs", "coriander chutney", "mint chutney", "ginger garlic", "cumin", "chaat masala"],
    searchKeywords: ["hariyali chicken", "green chicken", "chicken leg", "bbq", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Reshmi",
    image: "reshmi-tikka.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken mince",
      "1/2 cup heavy cream",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons green chili paste",
      "1 teaspoon white pepper powder",
      "1 teaspoon cardamom powder",
      "1 teaspoon salt",
      "2 tablespoons cornflour",
      "Oil for brushing"
    ],
    stepsRaw: [
      "In a bowl, mix chicken mince with cream, ginger-garlic paste, green chili paste, white pepper, cardamom powder, salt, and cornflour.",
      "Knead well for 8-10 minutes until the mixture is very smooth and sticky.",
      "Cover and put in the fridge for 1 hour.",
      "Wet your hands with water. Take a portion and shape into patties or onto skewers.",
      "Heat the grill to low-medium heat.",
      "Grill for 8-10 minutes, turning gently, until cooked and lightly golden.",
      "Do not over-char - reshmi kebabs should stay light in color.",
      "Brush with oil while cooking.",
      "Serve hot with mint chutney."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Royal Mughlai reshmi kebabs – silky smooth, creamy, and melt-in-mouth. Made with chicken mince and cream.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 160,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken mince", "cream", "ginger garlic", "green chili", "white pepper", "cardamom", "cornflour"],
    searchKeywords: ["reshmi kebab", "silky kebab", "creamy kebab", "chicken", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Reshmi Tikka",
    image: "reshmi-tikka.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless chicken - cut into pieces",
      "1/2 cup cream",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons green chili paste",
      "1 teaspoon white pepper",
      "1 teaspoon cardamom powder",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Mix cream, ginger-garlic paste, green chili paste, white pepper, cardamom, salt, and oil.",
      "Add the chicken pieces and marinate for 4 hours.",
      "Put onto skewers.",
      "Grill on low-medium heat for 10-12 minutes until cooked.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Creamy and tender reshmi tikka – boneless chicken pieces marinated in spiced cream, grilled to perfection.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 360,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["boneless chicken", "cream", "ginger garlic", "green chili", "white pepper", "cardamom"],
    searchKeywords: ["reshmi tikka", "creamy tikka", "chicken", "bbq", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Malai Reshmi",
    image: "reshmi-tikka.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless chicken",
      "1 cup heavy cream",
      "2 tablespoons ginger paste",
      "2 tablespoons garlic paste",
      "1 teaspoon white pepper",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Mix all the ingredients. Marinate the chicken for 4 hours.",
      "Grill on low heat until cooked through.",
      "Serve with naan."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Extra creamy and rich malai reshmi kebab – boneless chicken marinated in heavy cream and mild spices.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 170,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["boneless chicken", "cream", "ginger", "garlic", "white pepper"],
    searchKeywords: ["malai reshmi", "creamy kebab", "chicken", "bbq", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Seekh",
    image: "seekh-kebab-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g beef mince (very fine mince)",
      "1 tablespoon raw papaya paste",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1 teaspoon cardamom powder",
      "1 teaspoon nutmeg powder",
      "1 teaspoon mace powder",
      "1 teaspoon salt",
      "2 tablespoons fried onions paste",
      "2 tablespoons ghee for frying"
    ],
    stepsRaw: [
      "In a bowl, mix beef mince with papaya paste, ginger-garlic paste, and all the spice powders.",
      "Let it rest for 2 hours. The papaya helps to tenderize the meat.",
      "Add fried onion paste (blend fried onions with a little water).",
      "Knead the mixture well for 10 minutes until very smooth and soft.",
      "Cover and put in the fridge for 1 hour.",
      "Take small portions and shape into flat patties (about 2 inches across).",
      "Heat ghee in a pan over low heat.",
      "Shallow fry the patties on low heat for 2-3 minutes per side until golden brown.",
      "The kebabs should be very soft and melt in your mouth.",
      "Serve hot with ulte tawe ka paratha and mint chutney."
    ],
    difficulty: "Hard",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Lucknow-style melt-in-mouth kebabs – made with beef mince and aromatic spices, shallow fried in ghee.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 220,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["beef mince", "papaya", "ginger garlic", "cumin", "coriander", "red chili", "garam masala", "cardamom", "nutmeg", "mace", "fried onions", "ghee"],
    searchKeywords: ["seekh kebab", "galouti kebab", "beef", "melt in mouth", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Chicken Galouti",
    image: "chicken-galouti.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken mince",
      "1 tablespoon raw papaya paste",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1 teaspoon salt",
      "2 tablespoons fried onions paste",
      "2 tablespoons ghee"
    ],
    stepsRaw: [
      "Mix all the ingredients and let it rest for 2 hours.",
      "Shape into small patties.",
      "Shallow fry on low heat until golden.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Chicken version of galouti kebab – lighter but equally soft and tasty, shallow fried in ghee.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 180,
    baseServings: 4,
    calories: 370,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken mince", "papaya", "ginger garlic", "cumin", "coriander", "red chili", "garam masala", "fried onions", "ghee"],
    searchKeywords: ["chicken galouti", "galouti kebab", "chicken", "soft kebab", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Fish Tikka",
    image: "fish-tikka.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g firm white fish fillets (salmon, cod, or sea bass) - cut into pieces",
      "1/2 cup plain yogurt",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons lemon juice",
      "2 teaspoons red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Cut the fish into 1-inch pieces. Pat them dry with paper towels.",
      "In a bowl, mix yogurt, ginger-garlic paste, lemon juice, red chili powder, cumin, coriander, salt, and oil.",
      "Add the fish pieces and gently mix to coat. Fish is delicate, so mix gently.",
      "Marinate for only 30-45 minutes (fish doesn't need long marination).",
      "Heat the grill to high heat.",
      "Put the fish pieces onto skewers carefully.",
      "Grill for 3-4 minutes per side only. Fish cooks very quickly.",
      "Do not overcook or the fish will become dry.",
      "Serve hot with lemon wedges and mint chutney."
    ],
    difficulty: "Easy",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "Light and healthy grilled fish tikka – tender fish pieces marinated in spiced yogurt, grilled to perfection.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 250,
    baseServings: 4,
    calories: 280,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["fish", "yogurt", "ginger garlic", "lemon", "red chili", "cumin", "coriander"],
    searchKeywords: ["fish tikka", "grilled fish", "fish", "bbq", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Fish",
    image: "fish-fry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 whole fish (pomfret, sea bass, or trout) - cleaned",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons lemon juice",
      "2 teaspoons red chili powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon cumin powder",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Clean the fish well. Make 3-4 deep cuts on each side of the fish.",
      "In a bowl, mix ginger-garlic paste, lemon juice, red chili powder, turmeric, cumin, salt, and oil.",
      "Apply the marinade well all over the fish, including inside the cavity and into the cuts.",
      "Cover and put in the fridge for 1 hour.",
      "Heat the grill to medium-high heat.",
      "Put the fish on the grill.",
      "Grill for 10-12 minutes per side, depending on how thick the fish is.",
      "Flip carefully using a wide spatula.",
      "The fish is done when the flesh flakes easily with a fork.",
      "Serve hot with lemon wedges and mint chutney."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Whole grilled fish marinated with aromatic spices – an impressive main course for BBQ gatherings.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 300,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["fish", "ginger garlic", "lemon", "red chili", "turmeric", "cumin"],
    searchKeywords: ["whole fish", "grilled fish", "fish", "bbq", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Tandoori Fish",
    image: "fish-fry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g fish fillets - cut into pieces",
      "1/2 cup yogurt",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "1 teaspoon chaat masala",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Marinate the fish for 45 minutes.",
      "Grill on high heat for 3-4 minutes per side.",
      "Sprinkle chaat masala before serving.",
      "Serve hot."
    ],
    difficulty: "Easy",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "Smoky tandoori fish with chaat masala – quick and tasty BBQ dish.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 240,
    baseServings: 4,
    calories: 270,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["fish", "yogurt", "ginger garlic", "cumin", "coriander", "red chili", "chaat masala"],
    searchKeywords: ["tandoori fish", "fish", "smoky fish", "bbq", "quick"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Grilled Veg Platter",
    image: "grilled-veg.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 capsicums (bell peppers) - cut into pieces",
      "2 onions - cut into pieces",
      "2 tomatoes - thick slices",
      "1 zucchini - sliced",
      "1 eggplant - sliced",
      "2 tablespoons olive oil",
      "1 teaspoon red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon dried oregano",
      "1 teaspoon salt"
    ],
    stepsRaw: [
      "Cut all the vegetables into similar-sized pieces so they cook evenly.",
      "In a bowl, mix olive oil, red chili powder, cumin, oregano, and salt.",
      "Add the vegetables and toss to coat evenly.",
      "Put the vegetables onto skewers, alternating colors for a nice look.",
      "Heat the grill to medium-high heat.",
      "Grill the skewers for 8-10 minutes, turning now and then, until the vegetables are charred and tender-crisp.",
      "Do not overcook - the vegetables should still have some crunch.",
      "Serve hot with mint chutney."
    ],
    difficulty: "Easy",
    cookingTime: 15,
    isActive: true,
    isHalal: true,
    description: "Colorful mixed grilled vegetables with Mediterranean spices – a great side dish for any BBQ.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 120,
    ageGroup: ["adults", "teens", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart"],
    pantryKeywords: ["capsicum", "onion", "tomato", "zucchini", "eggplant", "olive oil", "cumin", "oregano"],
    searchKeywords: ["grilled vegetables", "veg platter", "bbq", "healthy", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Tandoori Mushroom",
    image: "stuffed-mushrooms.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g button mushrooms - cleaned",
      "1/2 cup yogurt",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon chaat masala",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Clean the mushrooms with a damp cloth (don't wash them in water).",
      "In a bowl, mix yogurt, ginger-garlic paste, red chili, cumin, chaat masala, salt, and oil.",
      "Add the mushrooms and gently mix to coat.",
      "Marinate for 30 minutes.",
      "Put the mushrooms onto skewers.",
      "Grill on medium-high heat for 5-7 minutes, turning once, until charred.",
      "Serve hot."
    ],
    difficulty: "Easy",
    cookingTime: 15,
    isActive: true,
    isHalal: true,
    description: "Juicy tandoori mushrooms marinated in spiced yogurt – a great vegetarian BBQ option.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 90,
    baseServings: 4,
    calories: 110,
    ageGroup: ["adults", "teens", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["mushrooms", "yogurt", "ginger garlic", "red chili", "cumin", "chaat masala"],
    searchKeywords: ["tandoori mushroom", "grilled mushrooms", "mushroom", "veg bbq", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Tandoori Paneer",
    image: "tandoori-paneer.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g paneer - cut into 1-inch pieces",
      "1 capsicum - cut into pieces",
      "1 onion - cut into pieces",
      "1/2 cup yogurt",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon chaat masala",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Soak the paneer pieces in warm water for 10 minutes to keep them soft.",
      "In a bowl, mix yogurt, ginger-garlic paste, red chili, cumin, chaat masala, salt, and oil.",
      "Add the paneer and vegetable pieces. Gently mix to coat.",
      "Marinate for 30 minutes.",
      "Put onto skewers, alternating paneer and vegetables.",
      "Grill on medium heat for 5-7 minutes, turning gently, until charred.",
      "The paneer should be golden outside and soft inside.",
      "Serve hot with mint chutney."
    ],
    difficulty: "Easy",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "Grilled paneer tikka with vegetables – a vegetarian delight, soft and smoky.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 280,
    ageGroup: ["adults", "teens", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["paneer", "capsicum", "onion", "yogurt", "ginger garlic", "red chili", "cumin", "chaat masala"],
    searchKeywords: ["tandoori paneer", "paneer tikka", "grilled paneer", "vegetarian", "bbq"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Seekh Kebab Masala",
    image: "seekh-kebab-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "12 seekh kebabs (already cooked)",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili powder",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration",
      "1 cup warm water"
    ],
    stepsRaw: [
      "Make the seekh kebabs using the recipe and set them aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add the chopped onions and sauté for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until fragrant.",
      "Add tomato puree, red chili powder, turmeric, and salt. Cook for 5-6 minutes until the oil separates.",
      "Add 1 cup of warm water and bring to a simmer. Cook for 5 minutes.",
      "Add the cooked seekh kebabs to the gravy.",
      "Simmer for 5-7 minutes, gently spooning gravy over the kebabs.",
      "Sprinkle garam masala and decorate with fresh coriander.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Seekh kebabs cooked in a rich, spicy tomato-onion gravy – a great mix of BBQ and curry.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 220,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["seekh kebabs", "onion", "tomato", "ginger garlic", "cumin seeds", "red chili", "turmeric", "garam masala"],
    searchKeywords: ["seekh kebab masala", "kebab curry", "gravy", "pakistani", "bbq"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Chapli Kebab Karahi",
    image: "chapli-kebab-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "6 chapli kebabs (already cooked)",
      "2 medium tomatoes - chopped",
      "2 tablespoons ginger-garlic paste",
      "2 green chilies - slit",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili powder",
      "1/2 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Make the chapli kebabs using the recipe and set them aside.",
      "Heat oil in a karahi or wok over medium heat. Add cumin seeds and let them crackle.",
      "Add ginger-garlic paste and cook for 1-2 minutes.",
      "Add the chopped tomatoes and cook for 5-6 minutes until soft.",
      "Add red chili powder and salt. Mix well.",
      "Add the cooked chapli kebabs and green chilies.",
      "Simmer for 5 minutes, gently stirring.",
      "Decorate with fresh coriander leaves.",
      "Serve hot with naan."
    ],
    difficulty: "Medium",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "Chapli kebabs cooked in a spicy tomato karahi – a tasty mix of BBQ and traditional karahi.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 210,
    baseServings: 4,
    calories: 460,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chapli kebabs", "tomato", "ginger garlic", "green chili", "cumin seeds", "red chili"],
    searchKeywords: ["chapli kebab karahi", "chapli karahi", "kebab karahi", "pakistani", "bbq"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Tandoori Raan",
    image: "tandoori-raan.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 whole lamb leg (about 2 kg)",
      "2 cups plain yogurt",
      "4 tablespoons ginger-garlic paste",
      "2 tablespoons red chili powder",
      "1 tablespoon turmeric powder",
      "1 tablespoon cumin powder",
      "1 tablespoon coriander powder",
      "1 tablespoon garam masala",
      "1 teaspoon nutmeg powder",
      "1 teaspoon mace powder",
      "1 tablespoon salt",
      "1/2 cup oil",
      "Charcoal for smoking"
    ],
    stepsRaw: [
      "Wash the lamb leg and pat it dry. Make deep cuts all over the meat with a sharp knife.",
      "In a large bowl, mix yogurt, ginger-garlic paste, red chili powder, turmeric, cumin, coriander, garam masala, nutmeg, mace, salt, and oil.",
      "Apply the marinade well all over the lamb leg, pushing it into the cuts.",
      "Cover and put in the fridge for 24-48 hours. The longer, the better.",
      "Add charcoal smoke for 10 minutes before cooking.",
      "Heat the oven or grill to 160°C (325°F).",
      "Put the lamb leg on a roasting rack with a tray underneath to catch the drippings.",
      "Roast for 2-3 hours, brushing with the marinade every 30 minutes.",
      "For the last 15 minutes, increase the heat to 200°C (400°F) to char the outside.",
      "Let the meat rest for 15 minutes before cutting.",
      "Serve hot with naan and mint chutney."
    ],
    difficulty: "Hard",
    cookingTime: 180,
    isActive: true,
    isHalal: true,
    description: "A showstopper whole grilled lamb leg marinated in rich spiced yogurt, slow-roasted to perfection. Great for special occasions.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 450,
    baseServings: 6,
    calories: 520,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["lamb", "yogurt", "ginger garlic", "red chili", "turmeric", "cumin", "coriander", "garam masala", "nutmeg", "mace"],
    searchKeywords: ["tandoori raan", "lamb leg", "whole lamb", "bbq", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Mutton Chops",
    image: "mutton-chops-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg mutton chops (about 8-10 chops)",
      "1 cup plain yogurt",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons raw papaya paste",
      "2 teaspoons red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon garam masala",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Wash the mutton chops and pat them dry. Trim extra fat if you want.",
      "In a bowl, mix yogurt, ginger-garlic paste, papaya paste, red chili powder, cumin, garam masala, salt, and oil.",
      "Apply the marinade to the chops and put in the fridge for 6-8 hours.",
      "Heat the grill to medium-high heat.",
      "Put the chops on the grill.",
      "Grill for 5-6 minutes per side for medium doneness.",
      "Brush with oil while grilling.",
      "Serve hot with mint chutney and salad."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Tender and juicy grilled mutton chops marinated with papaya and spices. Great for BBQ lovers.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 280,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton chops", "yogurt", "ginger garlic", "papaya", "red chili", "cumin", "garam masala"],
    searchKeywords: ["mutton chops", "grilled chops", "lamb chops", "bbq", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
  {
    title: "Tandoori Quail",
    image: "tandoori-quails.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "6 quails (bater) - cleaned",
      "1 cup yogurt",
      "2 tablespoons ginger-garlic paste",
      "2 teaspoons red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon garam masala",
      "1 teaspoon salt",
      "2 tablespoons oil"
    ],
    stepsRaw: [
      "Clean the quails and make cuts on them.",
      "Mix all the marinade ingredients.",
      "Marinate the quails for 4 hours.",
      "Heat the grill to medium heat.",
      "Grill the quails for 10-12 minutes, turning now and then, until cooked through.",
      "Serve hot with salad."
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Delicate grilled quail (bater) marinated in spiced yogurt – a traditional delicacy.",
    category: "Dinner",
    subCategory: "bbq",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 200,
    baseServings: 4,
    calories: 310,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["quail", "bater", "yogurt", "ginger garlic", "red chili", "cumin", "garam masala"],
    searchKeywords: ["tandoori quail", "quail", "bater", "bbq", "pakistani"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0,
    createdBy: null
  },
];

async function migrateRecipes() {
  try {
    console.log('Connecting to MongoDB');
    
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) {
      throw new Error('MongoDB URI not found');
    }
    
    await mongoose.connect(mongoURI, { 
      serverSelectionTimeoutMS: 10000, 
      family: 4 
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();