const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });


const recipesToMigrate = [
  {
    title: "Chai",
    image: "http://localhost:5000/uploads/chai.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups water",
      "2 cups milk",
      "4 teaspoons black tea leaves",
      "4 teaspoons sugar (adjust to taste)",
      "4 green cardamom pods, slightly crushed",
      "1 inch ginger, grated",
      "2-3 cloves (optional)"
    ],
    stepsRaw: [
      "Put water in a pot and bring to boil.",
      "Add tea leaves, crushed cardamom, ginger, and cloves.",
      "Boil for 2 minutes until tea leaves release their color.",
      "Add milk and bring to boil again.",
      "Lower the flame and cook for 3-4 minutes.",
      "Add sugar and stir until it dissolves.",
      "Strain the tea into cups using a strainer.",
      "Serve hot with biscuits or snacks."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A traditional Pakistani spiced milk tea that is rich, aromatic, and perfect with biscuits or snacks.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 15,
    baseServings: 4,
    calories: 80,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["tea leaves", "milk", "sugar", "cardamom", "ginger", "cloves", "water"],
    searchKeywords: ["chai", "pakistani tea", "milk tea", "karak chai", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Coffee",
    image: "http://localhost:5000/uploads/coffee.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 tablespoons coffee powder",
      "2 tablespoons sugar",
      "2 cups water",
      "1 cup milk",
      "1 teaspoon cocoa powder (optional)"
    ],
    stepsRaw: [
      "Boil water in a pot.",
      "Add coffee powder and sugar to boiling water.",
      "Cook for 5 minutes until strong smell comes.",
      "Heat milk separately until hot but not boiling.",
      "Mix coffee liquid with hot milk.",
      "Add cocoa powder if you want extra flavor.",
      "Pour into cups and serve right away.",
      "Enjoy with breakfast or as evening drink."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A rich and aromatic brewed coffee that is perfect for breakfast or as an evening pick-me-up.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 2,
    calories: 70,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["coffee powder", "sugar", "water", "milk", "cocoa powder"],
    searchKeywords: ["coffee", "hot coffee", "brewed coffee", "morning coffee", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Hot Chocolate",
    image: "http://localhost:5000/uploads/hot-chocolate.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups milk",
      "4 tablespoons cocoa powder",
      "4 tablespoons sugar",
      "1/4 cup chocolate chips",
      "1 teaspoon vanilla extract",
      "Whipped cream for topping",
      "Chocolate shavings for garnish"
    ],
    stepsRaw: [
      "Heat milk in a pot on medium flame.",
      "Add cocoa powder and sugar, whisk until dissolved.",
      "Add chocolate chips and stir continuously.",
      "Cook until chocolate melts completely.",
      "Add vanilla extract and mix well.",
      "Do not let it boil, keep on low flame.",
      "Pour into mugs and top with whipped cream.",
      "Garnish with chocolate shavings and serve hot."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A creamy and indulgent hot chocolate that is perfect for cold days and chocolate lovers.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 2,
    calories: 250,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["milk", "cocoa powder", "sugar", "chocolate chips", "vanilla", "whipped cream"],
    searchKeywords: ["hot chocolate", "creamy hot chocolate", "winter drink", "chocolate drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Kashmiri Chai",
    image: "http://localhost:5000/uploads/kashmiri-chai.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "4 tablespoons Kashmiri tea leaves",
      "8 cups water",
      "1/2 teaspoon baking soda",
      "2 cups milk",
      "1/2 cup sugar",
      "4-5 green cardamom pods",
      "1/4 cup crushed almonds",
      "Pink food color (optional)"
    ],
    stepsRaw: [
      "Boil tea leaves in 4 cups water for 15 minutes.",
      "Add baking soda and boil until color changes to red.",
      "Strain the tea liquid and set aside.",
      "In another pot, boil remaining water with cardamom.",
      "Add tea liquid and cook for 10 minutes.",
      "Add milk and sugar, mix well.",
      "Add pink color if you want traditional look.",
      "Serve hot with crushed almonds on top."
    ],
    difficulty: "Hard",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A traditional pink-colored Kashmiri tea that is rich, creamy, and perfect for special occasions.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "nuts"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 4,
    calories: 150,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["kashmiri tea leaves", "water", "baking soda", "milk", "sugar", "cardamom", "almonds", "pink food color"],
    searchKeywords: ["kashmiri chai", "pink tea", "noon chai", "kashmiri tea", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Masala Chai",
    image: "http://localhost:5000/uploads/masala-chai.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "4 cups water",
      "4 cups milk",
      "8 teaspoons black tea leaves",
      "8 teaspoons sugar",
      "1 inch ginger, crushed",
      "4 green cardamom pods",
      "4 cloves",
      "1 cinnamon stick",
      "2 black peppercorns",
      "1 star anise (optional)"
    ],
    stepsRaw: [
      "Crush all spices lightly with a mortar and pestle.",
      "Put water in a pot and bring to boil.",
      "Add crushed spices and boil for 5 minutes.",
      "Add tea leaves and boil for 2 more minutes.",
      "Add milk and bring to a rolling boil.",
      "Lower the flame and cook for 5 minutes.",
      "Add sugar and stir until it dissolves.",
      "Strain and serve hot with snacks."
    ],
    difficulty: "Medium",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "An aromatic spiced Indian tea with ginger, cardamom, and cloves, perfect for cold weather.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 4,
    calories: 90,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["tea leaves", "milk", "sugar", "ginger", "cardamom", "cloves", "cinnamon", "peppercorns", "star anise", "water"],
    searchKeywords: ["masala chai", "spiced tea", "indian tea", "chai masala", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Green Tea",
    image: "http://localhost:5000/uploads/green-tea.jpg",
    cuisine: "Chinese",
    ingredientsRaw: [
      "2 cups water",
      "2 green tea bags or 2 teaspoons loose green tea",
      "1 teaspoon honey (optional)",
      "1 slice lemon",
      "Fresh mint leaves (optional)"
    ],
    stepsRaw: [
      "Boil water and let it cool for 2 minutes (80°C).",
      "Put tea bags or leaves in a teapot.",
      "Pour hot water over tea and leave for 3 minutes.",
      "Remove tea bags or strain leaves.",
      "Add honey if you want and stir well.",
      "Serve in cups with lemon slice.",
      "Add mint leaves for freshness if you like.",
      "Drink without milk for best benefits."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A light and refreshing antioxidant-rich green tea that is perfect for health-conscious people.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 2,
    calories: 20,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["green tea bags", "water", "honey", "lemon", "mint leaves"],
    searchKeywords: ["green tea", "healthy tea", "antioxidant tea", "weight loss tea", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Ginger Tea",
    image: "http://localhost:5000/uploads/ginger-tea.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups water",
      "2 cups milk",
      "4 teaspoons black tea leaves",
      "2 inch ginger, grated",
      "4 teaspoons sugar",
      "4-5 mint leaves (optional)",
      "1 teaspoon lemon juice (optional)"
    ],
    stepsRaw: [
      "In a pot, boil water with grated ginger.",
      "Add tea leaves and boil for 3 minutes.",
      "Add milk and bring to boil.",
      "Cook on low flame for 5 minutes.",
      "Add sugar and stir until it dissolves.",
      "Add mint leaves for extra flavor if you like.",
      "Strain into cups and add lemon juice.",
      "Serve hot for cold relief."
    ],
    difficulty: "Easy",
    cookingTime: 15,
    isActive: true,
    isHalal: true,
    description: "A zesty and soothing ginger tea that is great for cold relief and digestion.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 15,
    baseServings: 2,
    calories: 70,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["tea leaves", "milk", "ginger", "sugar", "mint leaves", "lemon juice", "water"],
    searchKeywords: ["ginger tea", "adrak chai", "ginger milk tea", "cold remedy tea", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cardamom Tea",
    image: "http://localhost:5000/uploads/cardamon-tea.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups water",
      "2 cups milk",
      "4 teaspoons black tea leaves",
      "6-8 green cardamom pods, crushed",
      "4 teaspoons sugar",
      "Saffron strands (optional)"
    ],
    stepsRaw: [
      "Crush cardamom pods to release flavor.",
      "Boil water with crushed cardamom for 5 minutes.",
      "Add tea leaves and boil for 2 minutes.",
      "Add milk and bring to a rolling boil.",
      "Lower the flame and cook for 4 minutes.",
      "Add sugar and saffron if you like.",
      "Strain into cups using a fine strainer.",
      "Serve hot with biscuits or cake."
    ],
    difficulty: "Easy",
    cookingTime: 15,
    isActive: true,
    isHalal: true,
    description: "A fragrant cardamom tea that is aromatic, soothing, and perfect with biscuits or cake.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 2,
    calories: 80,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["tea leaves", "milk", "sugar", "cardamom", "saffron", "water"],
    searchKeywords: ["cardamom tea", "elaichi chai", "cardamom milk tea", "fragrant tea", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Lemonade",
    image: "http://localhost:5000/uploads/lemonade.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 lemons, squeezed (about 1 cup juice)",
      "1 cup sugar",
      "6 cups cold water",
      "Ice cubes",
      "Fresh mint leaves",
      "Lemon slices for garnish"
    ],
    stepsRaw: [
      "Make sugar syrup: mix sugar with 1 cup hot water.",
      "Stir until sugar completely dissolves.",
      "Let syrup cool to room temperature.",
      "In a pitcher, mix lemon juice and cold water.",
      "Add cooled sugar syrup and mix well.",
      "Add ice cubes and stir.",
      "Add lemon slices and mint for decoration.",
      "Serve cold in tall glasses."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A classic refreshing lemonade that is perfect for hot summer days and outdoor gatherings.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 15,
    baseServings: 4,
    calories: 120,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["lemons", "sugar", "water", "ice cubes", "mint leaves"],
    searchKeywords: ["lemonade", "fresh lemonade", "homemade lemonade", "summer drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mango Lassi",
    image: "http://localhost:5000/uploads/mango-lassi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 ripe mangoes, peeled and chopped",
      "2 cups plain yogurt",
      "1 cup cold milk",
      "4 tablespoons sugar or honey",
      "1/2 teaspoon cardamom powder",
      "Ice cubes",
      "Chopped pistachios for garnish"
    ],
    stepsRaw: [
      "Peel and chop ripe mangoes into pieces.",
      "In a blender, add mango pieces and yogurt.",
      "Add milk, sugar, and cardamom powder.",
      "Blend until smooth and creamy.",
      "Add ice cubes and blend briefly.",
      "Taste and add more sugar if needed.",
      "Pour into tall glasses.",
      "Garnish with chopped pistachios and serve."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A creamy and refreshing mango lassi that is perfect for summer and goes well with spicy food.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 2,
    calories: 220,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["mangoes", "yogurt", "milk", "sugar", "cardamom", "ice cubes", "pistachios"],
    searchKeywords: ["mango lassi", "lassi", "mango drink", "indian yogurt drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Sweet Lassi",
    image: "http://localhost:5000/uploads/sweet-lassi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "3 cups plain yogurt",
      "1 cup cold water",
      "6 tablespoons sugar",
      "1/2 teaspoon cardamom powder",
      "Ice cubes",
      "Rose water (optional)",
      "Saffron strands for garnish"
    ],
    stepsRaw: [
      "In a blender, mix yogurt and cold water.",
      "Add sugar and cardamom powder.",
      "Blend until smooth and frothy.",
      "Add ice cubes and blend for 30 seconds.",
      "Add rose water if you want fragrance.",
      "Pour into serving glasses.",
      "Soak saffron in a little milk for garnish.",
      "Drizzle saffron milk on top and serve cold."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A traditional sweet lassi that is creamy, refreshing, and perfect with spicy meals.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 2,
    calories: 180,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["yogurt", "water", "sugar", "cardamom", "ice cubes", "rose water", "saffron"],
    searchKeywords: ["sweet lassi", "lassi", "yogurt drink", "indian drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Salted Lassi",
    image: "http://localhost:5000/uploads/salted-lassi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "3 cups plain yogurt",
      "1 cup cold water",
      "1 teaspoon salt",
      "1/2 teaspoon roasted cumin powder",
      "Ice cubes",
      "Fresh mint leaves",
      "Black salt (optional)"
    ],
    stepsRaw: [
      "Mix yogurt and water in a blender.",
      "Add salt and blend until smooth.",
      "Add ice cubes and blend briefly.",
      "Pour into tall glasses.",
      "Sprinkle roasted cumin powder on top.",
      "Add fresh mint leaves for decoration.",
      "Add a little black salt if you like.",
      "Serve cold as a refreshing drink."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A savory salted lassi with roasted cumin, perfect for digestion and hot summer days.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 2,
    calories: 120,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "heart", "bp"],
    pantryKeywords: ["yogurt", "water", "salt", "roasted cumin", "ice cubes", "mint leaves", "black salt"],
    searchKeywords: ["salted lassi", "namkin lassi", "savory lassi", "yogurt drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Iced Tea",
    image: "http://localhost:5000/uploads/iced-tea.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 black tea bags",
      "4 cups boiling water",
      "1/2 cup sugar",
      "4 cups cold water",
      "Ice cubes",
      "Lemon slices",
      "Fresh mint leaves"
    ],
    stepsRaw: [
      "Put tea bags in boiling water for 5 minutes.",
      "Remove tea bags and let tea cool.",
      "Make sugar syrup: dissolve sugar in 1/2 cup hot water.",
      "Mix cooled tea with cold water.",
      "Add sugar syrup and stir well.",
      "Put in refrigerator for 1 hour to chill.",
      "Serve over ice cubes in tall glasses.",
      "Add lemon slices and mint for decoration."
    ],
    difficulty: "Easy",
    cookingTime: 75,
    isActive: true,
    isHalal: true,
    description: "A chilled black iced tea with lemon, perfect for hot summer days and outdoor parties.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 15,
    baseServings: 4,
    calories: 80,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["black tea bags", "water", "sugar", "ice cubes", "lemon slices", "mint leaves"],
    searchKeywords: ["iced tea", "lemon iced tea", "cold tea", "summer drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cold Coffee",
    image: "http://localhost:5000/uploads/cold-coffee.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 tablespoons instant coffee",
      "4 tablespoons sugar",
      "4 cups cold milk",
      "Ice cubes",
      "2 scoops vanilla ice cream",
      "Chocolate syrup",
      "Whipped cream for topping"
    ],
    stepsRaw: [
      "Mix coffee powder with 2 tablespoons hot water.",
      "Add sugar and stir until it dissolves.",
      "In a blender, mix coffee mixture and milk.",
      "Add ice cubes and blend until frothy.",
      "Pour into tall glasses.",
      "Add a scoop of vanilla ice cream.",
      "Drizzle chocolate syrup on top.",
      "Top with whipped cream and serve."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A frothy chilled coffee with ice cream and whipped cream, perfect for coffee lovers.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 2,
    calories: 280,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["instant coffee", "sugar", "milk", "ice cubes", "vanilla ice cream", "chocolate syrup", "whipped cream"],
    searchKeywords: ["cold coffee", "iced coffee", "frothy coffee", "coffee milkshake", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Falooda",
    image: "http://localhost:5000/uploads/falooda.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1/2 cup falooda seeds (sabja)",
      "1/2 cup cooked vermicelli",
      "4 cups milk, chilled",
      "1/2 cup rose syrup",
      "4 scoops vanilla ice cream",
      "1/4 cup chopped mixed nuts",
      "1/4 cup basil seeds soaked",
      "Jelly cubes (optional)"
    ],
    stepsRaw: [
      "Soak falooda seeds in water for 30 minutes.",
      "Cook vermicelli according to package instructions.",
      "In tall glasses, add soaked falooda seeds.",
      "Add a layer of cooked vermicelli.",
      "Pour chilled milk to fill half the glass.",
      "Add 2 tablespoons rose syrup in each glass.",
      "Add a scoop of vanilla ice cream.",
      "Garnish with nuts and serve right away."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A layered dessert drink with falooda seeds, vermicelli, rose syrup, and ice cream.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "nuts"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["falooda seeds", "vermicelli", "milk", "rose syrup", "vanilla ice cream", "mixed nuts", "basil seeds", "jelly cubes"],
    searchKeywords: ["falooda", "pakistani falooda", "dessert drink", "layered drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Sugarcane Juice",
    image: "http://localhost:5000/uploads/vanilla-sponge-cake.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "4-5 sugarcane sticks",
      "1 inch ginger",
      "4-5 mint leaves",
      "1 lemon, squeezed",
      "Black salt to taste",
      "Ice cubes",
      "Lemon slices for garnish"
    ],
    stepsRaw: [
      "Peel sugarcane and cut into small pieces.",
      "Put sugarcane through a juicer.",
      "Add ginger and mint while juicing.",
      "Collect juice in a large pitcher.",
      "Add lemon juice and black salt.",
      "Stir well and put in refrigerator to chill.",
      "Serve over ice cubes in glasses.",
      "Add lemon slices for decoration."
    ],
    difficulty: "Medium",
    cookingTime: 15,
    isActive: true,
    isHalal: true,
    description: "A fresh and sweet sugarcane juice with ginger and mint, perfect for hot summer days.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 4,
    calories: 150,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["sugarcane sticks", "ginger", "mint leaves", "lemon", "black salt", "ice cubes"],
    searchKeywords: ["sugarcane juice", "fresh juice", "summer drink", "ganne ka ras", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Strawberry Banana Smoothie",
    image: "http://localhost:5000/uploads/strawberry-banana-smoothie.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup strawberries, cleaned",
      "1 ripe banana",
      "1 cup yogurt",
      "1/2 cup milk",
      "2 tablespoons honey",
      "1/2 cup ice cubes",
      "Fresh strawberries for garnish"
    ],
    stepsRaw: [
      "Wash and clean fresh strawberries.",
      "Peel and slice ripe banana.",
      "In a blender, mix strawberries and banana.",
      "Add yogurt, milk, and honey.",
      "Add ice cubes and blend until smooth.",
      "Taste and add more honey if needed.",
      "Pour into serving glasses.",
      "Add fresh strawberry slices on top for decoration."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A creamy and delicious strawberry banana smoothie that is perfect for breakfast or as a snack.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 2,
    calories: 190,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["strawberries", "banana", "yogurt", "milk", "honey", "ice cubes"],
    searchKeywords: ["strawberry banana smoothie", "fruit smoothie", "breakfast smoothie", "healthy drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mango Smoothie",
    image: "http://localhost:5000/uploads/mango-smoothie.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 ripe mangoes, peeled and chopped",
      "1 cup plain yogurt",
      "1/2 cup orange juice",
      "2 tablespoons honey",
      "1/2 teaspoon cardamom powder",
      "Ice cubes",
      "Mint leaves for garnish"
    ],
    stepsRaw: [
      "Peel and chop ripe mangoes into chunks.",
      "In a blender, add mango chunks and yogurt.",
      "Add orange juice and honey.",
      "Add cardamom powder and ice cubes.",
      "Blend until smooth and creamy.",
      "Pour into tall glasses.",
      "Add fresh mint leaves for decoration.",
      "Serve right away for best flavor."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A tropical mango smoothie that is creamy, refreshing, and perfect for summer mornings.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 55,
    baseServings: 2,
    calories: 210,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["mangoes", "yogurt", "orange juice", "honey", "cardamom", "ice cubes", "mint leaves"],
    searchKeywords: ["mango smoothie", "tropical smoothie", "fruit smoothie", "healthy drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Berry Blast Smoothie",
    image: "http://localhost:5000/uploads/berry-blast-smoothie.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup mixed berries (strawberries, blueberries, raspberries)",
      "1 banana",
      "1 cup Greek yogurt",
      "1/2 cup almond milk",
      "1 tablespoon chia seeds",
      "2 tablespoons honey",
      "Ice cubes",
      "Fresh berries for garnish"
    ],
    stepsRaw: [
      "Wash and prepare all berries.",
      "Peel and slice banana.",
      "In a blender, mix berries and banana.",
      "Add Greek yogurt and almond milk.",
      "Add chia seeds and honey.",
      "Add ice cubes and blend until smooth.",
      "Pour into glasses and let sit for 5 minutes.",
      "Add fresh berries on top for decoration."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "An antioxidant-rich mixed berry smoothie that is healthy, delicious, and perfect for breakfast.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "nuts"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 2,
    calories: 230,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["mixed berries", "banana", "greek yogurt", "almond milk", "chia seeds", "honey", "ice cubes"],
    searchKeywords: ["berry blast smoothie", "antioxidant smoothie", "mixed berry smoothie", "healthy drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Green Detox Smoothie",
    image: "http://localhost:5000/uploads/green-detox-smoothie.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup spinach leaves",
      "1 green apple, chopped",
      "1/2 cucumber, peeled",
      "1 banana",
      "1 tablespoon lemon juice",
      "1 cup coconut water",
      "1 tablespoon honey",
      "Ice cubes"
    ],
    stepsRaw: [
      "Wash spinach leaves well.",
      "Chop green apple and peel cucumber.",
      "Peel and slice banana.",
      "In a blender, add spinach first.",
      "Add apple, cucumber, and banana.",
      "Add lemon juice and coconut water.",
      "Add honey and ice cubes.",
      "Blend until smooth and serve right away."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A healthy green detox smoothie with spinach, apple, and cucumber for a nutritional boost.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 2,
    calories: 140,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["spinach", "green apple", "cucumber", "banana", "lemon juice", "coconut water", "honey", "ice cubes"],
    searchKeywords: ["green detox smoothie", "healthy smoothie", "detox drink", "green smoothie", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Peanut Butter Smoothie",
    image: "http://localhost:5000/uploads/peanut-butter-smoothie.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 bananas",
      "3 tablespoons peanut butter",
      "2 cups milk",
      "2 tablespoons honey",
      "1/2 teaspoon cinnamon powder",
      "Ice cubes",
      "Chopped peanuts for garnish"
    ],
    stepsRaw: [
      "Peel and slice ripe bananas.",
      "In a blender, mix bananas and peanut butter.",
      "Add milk and honey.",
      "Add cinnamon powder and ice cubes.",
      "Blend until smooth and creamy.",
      "Taste and add more honey if needed.",
      "Pour into serving glasses.",
      "Add chopped peanuts on top for decoration."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A protein-packed peanut butter smoothie that is creamy, satisfying, and perfect after workout.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "peanuts"],
    budget: "standard",
    costPerServing: 55,
    baseServings: 2,
    calories: 320,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["bananas", "peanut butter", "milk", "honey", "cinnamon", "ice cubes", "chopped peanuts"],
    searchKeywords: ["peanut butter smoothie", "protein smoothie", "banana peanut butter smoothie", "healthy drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chocolate Smoothie",
    image: "http://localhost:5000/uploads/chocolate-smoothie.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 bananas",
      "3 tablespoons cocoa powder",
      "2 cups milk",
      "2 tablespoons honey",
      "1/2 teaspoon vanilla extract",
      "Ice cubes",
      "Chocolate shavings for topping",
      "Whipped cream (optional)"
    ],
    stepsRaw: [
      "Peel and slice ripe bananas.",
      "In a blender, mix bananas and cocoa powder.",
      "Add milk, honey, and vanilla extract.",
      "Add ice cubes and blend until smooth.",
      "Pour into tall glasses.",
      "Top with whipped cream if you like.",
      "Sprinkle chocolate shavings on top.",
      "Serve right away for best taste."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A rich chocolate smoothie that is like a milkshake, perfect for chocolate cravings.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 2,
    calories: 280,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["bananas", "cocoa powder", "milk", "honey", "vanilla", "ice cubes", "chocolate shavings", "whipped cream"],
    searchKeywords: ["chocolate smoothie", "chocolate milkshake", "banana chocolate smoothie", "sweet drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Avocado Smoothie",
    image: "http://localhost:5000/uploads/avocado-smoothie.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 ripe avocado",
      "1 banana",
      "1 cup milk",
      "2 tablespoons honey",
      "1 tablespoon lime juice",
      "Ice cubes",
      "Mint leaves for garnish"
    ],
    stepsRaw: [
      "Cut avocado, remove seed and scoop out flesh.",
      "Peel and slice banana.",
      "In a blender, mix avocado and banana.",
      "Add milk, honey, and lime juice.",
      "Add ice cubes and blend until creamy.",
      "Pour into serving glasses.",
      "Add fresh mint leaves for decoration.",
      "Serve right away as a healthy breakfast."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A creamy and nutritious avocado smoothie that is rich in healthy fats and perfect for breakfast.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 2,
    calories: 280,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["avocado", "banana", "milk", "honey", "lime juice", "ice cubes", "mint leaves"],
    searchKeywords: ["avocado smoothie", "healthy smoothie", "creamy smoothie", "breakfast drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Protein Power Smoothie",
    image: "http://localhost:5000/uploads/protein-power-smoothie.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 banana",
      "1 cup Greek yogurt",
      "1 cup milk",
      "2 tablespoons protein powder",
      "1 tablespoon almond butter",
      "1 tablespoon flax seeds",
      "Ice cubes",
      "Sliced almonds for garnish"
    ],
    stepsRaw: [
      "Peel and slice banana.",
      "In a blender, mix banana and Greek yogurt.",
      "Add milk and protein powder.",
      "Add almond butter and flax seeds.",
      "Add ice cubes and blend until smooth.",
      "Pour into tall glasses.",
      "Add sliced almonds on top for decoration.",
      "Enjoy as a post-workout recovery drink."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A protein-packed post-workout smoothie with Greek yogurt, protein powder, and almond butter.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "nuts"],
    budget: "premium",
    costPerServing: 100,
    baseServings: 1,
    calories: 380,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["banana", "greek yogurt", "milk", "protein powder", "almond butter", "flax seeds", "ice cubes", "sliced almonds"],
    searchKeywords: ["protein smoothie", "post workout drink", "protein shake", "healthy smoothie", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Virgin Mojito",
    image: "http://localhost:5000/uploads/virgin-mojito.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "10-12 fresh mint leaves",
      "2 limes, cut into wedges",
      "4 tablespoons sugar",
      "Ice cubes",
      "Soda water",
      "Fresh mint sprigs for garnish",
      "Lime slices for garnish"
    ],
    stepsRaw: [
      "In a tall glass, crush mint leaves with lime wedges.",
      "Add sugar and crush until sugar dissolves.",
      "Fill glass with ice cubes.",
      "Top with chilled soda water.",
      "Stir gently to mix everything.",
      "Add fresh mint sprig for decoration.",
      "Put a lime slice on the rim of the glass.",
      "Serve right away with a straw."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A refreshing non-alcoholic mint and lime mojito that is perfect for parties and summer days.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 1,
    calories: 120,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["mint leaves", "limes", "sugar", "ice cubes", "soda water"],
    searchKeywords: ["virgin mojito", "non alcoholic mojito", "mint lime drink", "summer mocktail", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Virgin Pina Colada",
    image: "http://localhost:5000/uploads/pina-colado.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups pineapple juice",
      "1 cup coconut cream",
      "1 cup crushed ice",
      "2 tablespoons sugar syrup",
      "Pineapple slices for garnish",
      "Maraschino cherries",
      "Umbrella for decoration"
    ],
    stepsRaw: [
      "In a blender, mix pineapple juice and coconut cream.",
      "Add crushed ice and sugar syrup.",
      "Blend until smooth and creamy.",
      "Pour into tall glasses.",
      "Add pineapple slice on the rim for decoration.",
      "Put a maraschino cherry on top.",
      "Add a cocktail umbrella for fun.",
      "Serve right away while frothy."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A tropical non-alcoholic pina colada with pineapple and coconut, perfect for summer parties.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 2,
    calories: 220,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["pineapple juice", "coconut cream", "crushed ice", "sugar syrup", "pineapple slices", "maraschino cherries"],
    searchKeywords: ["non alcoholic pina colada", "virgin pina colada", "pineapple coconut drink", "tropical mocktail", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Shirley Temple",
    image: "http://localhost:5000/uploads/shirley-temple.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup ginger ale",
      "1/2 cup lemon-lime soda",
      "1 tablespoon grenadine syrup",
      "Ice cubes",
      "Maraschino cherries",
      "Orange slice for garnish",
      "Lemon slice for garnish"
    ],
    stepsRaw: [
      "Fill a tall glass with ice cubes.",
      "Pour ginger ale over ice.",
      "Add lemon-lime soda gently.",
      "Slowly pour grenadine syrup.",
      "Do not stir to create layers.",
      "Add maraschino cherries for decoration.",
      "Put orange and lemon slices on the rim.",
      "Serve with a straw and stirrer."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A sweet non-alcoholic mocktail with ginger ale, lemon-lime soda, and grenadine syrup.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 1,
    calories: 150,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["ginger ale", "lemon-lime soda", "grenadine syrup", "ice cubes", "maraschino cherries", "orange slice", "lemon slice"],
    searchKeywords: ["shirley temple", "non alcoholic mocktail", "sweet mocktail", "kids drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Fruit Punch",
    image: "http://localhost:5000/uploads/fruit-punch.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups orange juice",
      "1 cup pineapple juice",
      "1 cup cranberry juice",
      "1 lemon, squeezed",
      "1/4 cup sugar syrup",
      "Ice cubes",
      "Mixed fruit slices",
      "Fresh mint leaves"
    ],
    stepsRaw: [
      "In a large pitcher, mix all juices.",
      "Add lemon juice and sugar syrup.",
      "Stir well until completely mixed.",
      "Put in refrigerator for 1 hour to chill.",
      "Add ice cubes to serving glasses.",
      "Pour fruit punch over ice.",
      "Add mixed fruit slices for decoration.",
      "Add mint leaves and serve cold."
    ],
    difficulty: "Easy",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A colorful mixed fruit punch that is perfect for parties and family gatherings.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 4,
    calories: 130,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["orange juice", "pineapple juice", "cranberry juice", "lemon", "sugar syrup", "ice cubes", "mixed fruit slices", "mint leaves"],
    searchKeywords: ["fruit punch", "mixed fruit drink", "party punch", "summer drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Blue Lagoon",
    image: "http://localhost:5000/uploads/blue-lagoon.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup lemonade",
      "1/2 cup blue curacao syrup",
      "1/2 cup soda water",
      "Ice cubes",
      "Lemon slices",
      "Maraschino cherries",
      "Sugar for rim (optional)"
    ],
    stepsRaw: [
      "If you want, rim the glass with sugar.",
      "Fill glass with ice cubes.",
      "Pour lemonade over ice.",
      "Add blue curacao syrup slowly.",
      "Top with soda water gently.",
      "Add lemon slice for decoration.",
      "Put a maraschino cherry on top.",
      "Serve with a blue straw for effect."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A vibrant blue citrus mocktail that is visually stunning and refreshingly tangy.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 1,
    calories: 160,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["lemonade", "blue curacao syrup", "soda water", "ice cubes", "lemon slices", "maraschino cherries", "sugar"],
    searchKeywords: ["blue lagoon mocktail", "blue mocktail", "citrus mocktail", "party drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mango Tango",
    image: "http://localhost:5000/uploads/mango-tango.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup mango juice",
      "1/2 cup orange juice",
      "1/4 cup pineapple juice",
      "1 tablespoon lime juice",
      "Ice cubes",
      "Mango slices for garnish",
      "Fresh mint sprig"
    ],
    stepsRaw: [
      "In a shaker, mix all fruit juices.",
      "Add lime juice and ice cubes.",
      "Shake well for 30 seconds.",
      "Strain into a chilled cocktail glass.",
      "Add fresh mango slice for decoration.",
      "Put a mint sprig for freshness.",
      "Serve right away while cold.",
      "Perfect for summer parties."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A tropical mango mocktail with orange and pineapple, perfect for summer parties.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 1,
    calories: 140,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["mango juice", "orange juice", "pineapple juice", "lime juice", "ice cubes", "mango slices", "mint sprig"],
    searchKeywords: ["mango tango", "mango mocktail", "tropical mocktail", "summer drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Sunrise Mocktail",
    image: "http://localhost:5000/uploads/sunrise-mocktail.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup orange juice",
      "2 tablespoons grenadine syrup",
      "Ice cubes",
      "Orange slice for garnish",
      "Maraschino cherry",
      "Umbrella for decoration"
    ],
    stepsRaw: [
      "Fill a tall glass with ice cubes.",
      "Pour orange juice over ice.",
      "Slowly pour grenadine down the side.",
      "Let it settle at the bottom for sunrise effect.",
      "Do not stir to keep the layers.",
      "Put an orange slice on the rim for decoration.",
      "Add a cherry and umbrella.",
      "Serve with a long spoon for mixing."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A beautiful layered orange mocktail that looks like a sunrise, perfect for special occasions.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 1,
    calories: 130,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["orange juice", "grenadine syrup", "ice cubes", "orange slice", "maraschino cherry"],
    searchKeywords: ["sunrise mocktail", "layered mocktail", "orange mocktail", "party drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Berry Bliss",
    image: "http://localhost:5000/uploads/berry-bliss.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1/2 cup mixed berry puree",
      "1/2 cup cranberry juice",
      "1/2 cup soda water",
      "1 tablespoon lime juice",
      "Ice cubes",
      "Fresh berries for garnish",
      "Mint leaves"
    ],
    stepsRaw: [
      "Make berry puree by blending fresh berries.",
      "Strain puree to remove seeds.",
      "In a glass, add berry puree first.",
      "Add ice cubes to fill the glass.",
      "Pour cranberry juice over ice.",
      "Top with soda water gently.",
      "Add lime juice and stir lightly.",
      "Add fresh berries and mint for decoration."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A mixed berry refreshing cooler that is bursting with berry flavor and perfect for summer.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 55,
    baseServings: 1,
    calories: 110,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["mixed berry puree", "cranberry juice", "soda water", "lime juice", "ice cubes", "fresh berries", "mint leaves"],
    searchKeywords: ["berry bliss", "berry mocktail", "mixed berry drink", "summer cooler", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Rooh Afza",
    image: "http://localhost:5000/uploads/rooh-afza.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "4 tablespoons Rooh Afza syrup",
      "4 cups chilled milk or water",
      "Ice cubes",
      "2 tablespoons chopped mixed nuts",
      "1 tablespoon basil seeds (optional)",
      "Rose petals for garnish"
    ],
    stepsRaw: [
      "In a glass, add Rooh Afza syrup.",
      "Add chilled milk or water as you like.",
      "Stir well until syrup dissolves completely.",
      "Add ice cubes to make it colder.",
      "Soak basil seeds in water if using.",
      "Add soaked basil seeds to the drink.",
      "Add chopped nuts and rose petals for decoration.",
      "Serve right away for traditional taste."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A traditional rose-flavored drink that is refreshing and perfect for hot summer days.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "nuts"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 4,
    calories: 110,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["rooh afza syrup", "milk", "water", "ice cubes", "mixed nuts", "basil seeds", "rose petals"],
    searchKeywords: ["rooh afza", "rose drink", "traditional drink", "pakistani drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Sharbat-e-Sandal",
    image: "http://localhost:5000/uploads/sandal-sharbat.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 teaspoons sandalwood powder",
      "4 cups water",
      "1 cup sugar",
      "1 tablespoon lemon juice",
      "Ice cubes",
      "Rose water for flavor",
      "Pistachios for garnish"
    ],
    stepsRaw: [
      "Make sugar syrup by dissolving sugar in water.",
      "Add sandalwood powder to the syrup.",
      "Cook on low flame for 10 minutes.",
      "Strain through a cloth.",
      "Add lemon juice and rose water.",
      "Put in refrigerator for 2 hours to chill.",
      "Serve over ice cubes in glasses.",
      "Add crushed pistachios on top for decoration."
    ],
    difficulty: "Medium",
    cookingTime: 130,
    isActive: true,
    isHalal: true,
    description: "A cooling sandalwood sharbat that is traditional and perfect for hot summer days.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["nuts"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 4,
    calories: 120,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["sandalwood powder", "water", "sugar", "lemon juice", "ice cubes", "rose water", "pistachios"],
    searchKeywords: ["sharbat e sandal", "sandalwood drink", "cooling drink", "pakistani sharbat", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Sattu Sharbat",
    image: "http://localhost:5000/uploads/sattu-sharbat.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1/2 cup sattu flour",
      "4 cups cold water",
      "2 tablespoons lemon juice",
      "1 teaspoon roasted cumin powder",
      "Black salt to taste",
      "Ice cubes",
      "Fresh mint leaves"
    ],
    stepsRaw: [
      "In a pitcher, mix sattu flour with a little water.",
      "Make a smooth paste without lumps.",
      "Add the rest of the water and mix well.",
      "Add lemon juice and black salt.",
      "Add roasted cumin powder and stir.",
      "Put in refrigerator for 30 minutes to chill.",
      "Serve over ice cubes in glasses.",
      "Add fresh mint leaves for decoration."
    ],
    difficulty: "Easy",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A nutritious roasted gram flour drink that is cooling and perfect for summer.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 4,
    calories: 90,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["sattu flour", "water", "lemon juice", "roasted cumin", "black salt", "ice cubes", "mint leaves"],
    searchKeywords: ["sattu sharbat", "sattu drink", "roasted gram drink", "summer cooler", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Jal Zeera",
    image: "http://localhost:5000/uploads/jal-zeera.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1/4 cup mint leaves",
      "1/4 cup coriander leaves",
      "1 tablespoon cumin seeds",
      "1 tablespoon black salt",
      "1 tablespoon lemon juice",
      "4 cups water",
      "Ice cubes",
      "Cumin powder for garnish"
    ],
    stepsRaw: [
      "Dry roast cumin seeds until they smell nice.",
      "Grind roasted cumin with mint and coriander.",
      "Mix the paste with water in a pitcher.",
      "Add black salt and lemon juice.",
      "Stir well and put in refrigerator for 1 hour.",
      "Strain before serving if you like.",
      "Serve over ice cubes in glasses.",
      "Sprinkle cumin powder on top."
    ],
    difficulty: "Medium",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A spicy Indian cumin cooler that is tangy, refreshing, and great for digestion.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 15,
    baseServings: 4,
    calories: 40,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["mint leaves", "coriander leaves", "cumin seeds", "black salt", "lemon juice", "water", "ice cubes"],
    searchKeywords: ["jal jeera", "cumin drink", "spicy cooler", "indian drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Aam Panna",
    image: "http://localhost:5000/uploads/aam-panna.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 raw mangoes",
      "1/2 cup sugar",
      "1 teaspoon roasted cumin powder",
      "1/2 teaspoon black salt",
      "4 cups water",
      "Ice cubes",
      "Fresh mint leaves"
    ],
    stepsRaw: [
      "Cook raw mangoes in a pressure cooker until soft.",
      "Peel and take out the pulp from mangoes.",
      "Blend pulp with sugar and water.",
      "Strain to remove any fibers.",
      "Add roasted cumin and black salt.",
      "Put in refrigerator for 2 hours to chill.",
      "Serve over ice cubes in glasses.",
      "Add fresh mint leaves for decoration."
    ],
    difficulty: "Medium",
    cookingTime: 130,
    isActive: true,
    isHalal: true,
    description: "A tangy raw mango summer cooler that is refreshing and helps prevent heat stroke.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 4,
    calories: 100,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["raw mangoes", "sugar", "roasted cumin", "black salt", "water", "ice cubes", "mint leaves"],
    searchKeywords: ["aam panna", "raw mango drink", "kacchi kairi drink", "summer cooler", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Badam Milk",
    image: "http://localhost:5000/uploads/badam-milk.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1/2 cup almonds, soaked overnight",
      "4 cups milk",
      "4-5 saffron strands",
      "4 cardamom pods, crushed",
      "4 tablespoons sugar",
      "Chopped pistachios for garnish"
    ],
    stepsRaw: [
      "Peel soaked almonds after soaking overnight.",
      "Blend almonds with a little milk to make a paste.",
      "Heat the rest of the milk in a pot.",
      "Add almond paste and stir continuously.",
      "Add crushed cardamom and saffron.",
      "Add sugar and cook for 10 minutes.",
      "Serve hot or cold as you like.",
      "Add chopped pistachios on top for decoration."
    ],
    difficulty: "Medium",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "A rich almond-flavored milk that is nutritious and perfect for kids and adults alike.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "nuts"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 4,
    calories: 220,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["almonds", "milk", "saffron", "cardamom", "sugar", "pistachios"],
    searchKeywords: ["badam milk", "almond milk", "nutritious drink", "kids drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Masala Milk",
    image: "http://localhost:5000/uploads/masala-milk.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "4 cups milk",
      "2 tablespoons sugar",
      "1/2 teaspoon cardamom powder",
      "1/4 teaspoon nutmeg powder",
      "1/4 teaspoon dry ginger powder",
      "Saffron strands (optional)",
      "Chopped nuts for garnish"
    ],
    stepsRaw: [
      "Heat milk in a heavy-bottomed pot.",
      "Bring to boil and then lower the flame.",
      "Cook for 10 minutes to reduce a little.",
      "Add sugar and stir until it dissolves.",
      "Add all spice powders and mix well.",
      "Add saffron if you want color.",
      "Serve hot in mugs or glasses.",
      "Add chopped nuts on top for decoration."
    ],
    difficulty: "Easy",
    cookingTime: 15,
    isActive: true,
    isHalal: true,
    description: "A spiced warm milk that is comforting, aromatic, and perfect before bedtime.",
    category: "Breakfast",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "nuts"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 4,
    calories: 150,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["milk", "sugar", "cardamom", "nutmeg", "dry ginger", "saffron", "chopped nuts"],
    searchKeywords: ["masala milk", "spiced milk", "warm milk", "comfort drink", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Thandai",
    image: "http://localhost:5000/uploads/thandai.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1/2 cup almonds",
      "2 tablespoons poppy seeds",
      "2 tablespoons watermelon seeds",
      "1 tablespoon fennel seeds",
      "10-12 black peppercorns",
      "4 cups milk",
      "1/2 cup sugar",
      "Rose water for flavor"
    ],
    stepsRaw: [
      "Soak all nuts and seeds overnight.",
      "Drain water and grind to a fine paste.",
      "Add a little milk while grinding.",
      "Strain the paste through a cloth.",
      "Mix the strained paste with the rest of the milk.",
      "Add sugar and rose water.",
      "Put in refrigerator for 4 hours to chill.",
      "Serve cold with rose petals on top for decoration."
    ],
    difficulty: "Hard",
    cookingTime: 270,
    isActive: true,
    isHalal: true,
    description: "A festive spiced milk drink that is traditionally served during Holi and other celebrations.",
    category: "Snacks",
    subCategory: "beverages",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "nuts"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 4,
    calories: 250,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["almonds", "poppy seeds", "watermelon seeds", "fennel seeds", "black peppercorns", "milk", "sugar", "rose water"],
    searchKeywords: ["thandai", "festive drink", "holi drink", "spiced milk", "beverage"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
];

async function migrateRecipes() {
  try {
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    
    if (!mongoURI) {
      throw new Error('MongoDB URI not found');
    }
    
    console.log('Connecting to MongoDB');
    await mongoose.connect(mongoURI, {
      serverSelectionTimeoutMS: 10000,
      family: 4
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();