const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [

  {
    title: "Chicken Chana Dal",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - curry cut pieces with bones",
      "1 cup chana dal (split Bengal gram) - washed and soaked",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration",
      "2 green chilies - slit lengthwise"
    ],
    stepsRaw: [
      "Wash chana dal well under running water. Soak in fresh water for 30 minutes. Drain before cooking.",
      "Heat oil in a large heavy-bottomed pot over medium heat. Add cumin seeds and let them crackle for 30 seconds until they smell good.",
      "Add finely chopped onions and cook for 5-6 minutes until they turn golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until the raw smell goes away.",
      "Add chicken pieces and fry on high heat for 5-7 minutes until the chicken changes color to white and gets a little brown.",
      "Add chopped tomatoes and cook for 5-6 minutes until they become soft and mushy.",
      "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes until the spices smell good.",
      "Add soaked chana dal and 3 cups of warm water. Stir well to mix everything.",
      "Cover the pot with a lid and cook on medium heat for 30-35 minutes until the chicken and dal are completely tender.",
      "Sprinkle garam masala and decorate with fresh coriander leaves and green chilies.",
      "Serve hot with naan, roti, or steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A filling and healthy chicken curry with chana dal (split Bengal gram) – a complete one-pot meal great with rice or roti.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 90,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "chana dal", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["chicken", "chicken dal", "chana dal chicken", "chicken curry", "pakistani chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Chana Dal Fry",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup chana dal - washed and soaked",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon mustard seeds",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash chana dal and soak for 30 minutes. Drain well.",
      "Heat oil in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white and gets a little brown.",
      "Add tomato puree and cook for 5-6 minutes until the oil separates from the masala.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add soaked chana dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 30-35 minutes until the chicken and dal are tender.",
      "Add garam masala and fresh coriander leaves. Mix well.",
      "Serve hot with naan or steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Restaurant-style chicken with chana dal – mustard and cumin tadka gives a special flavor, great with naan.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 90,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "chana dal", "onion", "tomato", "ginger", "garlic", "mustard seeds", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["chicken", "chana dal chicken fry", "fried chicken dal", "chicken curry", "pakistani chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Chana Dal Palak",
    image: "chicken-chana-daal-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup chana dal - washed and soaked",
      "2 cups fresh spinach (palak) - washed and finely chopped",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash chana dal and soak for 30 minutes. Drain well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped spinach and cook for 3-4 minutes until the spinach wilts completely.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add soaked chana dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 30-35 minutes until the chicken and dal are tender.",
      "Sprinkle garam masala and serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Healthy green curry with chicken, chana dal, and fresh spinach – good for you and tasty, great with roti.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Mixed",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 350,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general", "diabetes", "heart"],
    pantryKeywords: ["chicken", "chana dal", "spinach", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["chicken", "chicken palak dal", "spinach chicken dal", "green chicken curry", "healthy chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Chana Dal Louki",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup chana dal - washed and soaked",
      "2 cups louki (bottle gourd) - peeled and cut into small pieces",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash chana dal and soak for 30 minutes. Drain well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add louki pieces and cook for 5-6 minutes, stirring now and then.",
      "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add soaked chana dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 30-35 minutes until the chicken, dal, and louki are all tender.",
      "Serve hot with steamed rice or roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Light and healthy curry with chicken, chana dal, and bottle gourd (louki) – a wholesome, low-oil dish.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 340,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general", "diabetes", "heart"],
    pantryKeywords: ["chicken", "chana dal", "louki", "bottle gourd", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["chicken", "chicken louki dal", "bottle gourd chicken", "light chicken curry", "healthy dal chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Spicy Chicken Chana Dal",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup chana dal - washed and soaked",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "3 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste",
      "2 green chilies - finely chopped"
    ],
    stepsRaw: [
      "Wash chana dal and soak for 30 minutes. Drain well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and green chilies. Cook for 5-6 minutes until soft.",
      "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add soaked chana dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 30-35 minutes until the chicken and dal are tender.",
      "Sprinkle garam masala and serve hot with naan or steamed rice."
    ],
    difficulty: "Hard",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Extra spicy chicken curry with chana dal – full of red chili and green chilies, great for heat lovers.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 410,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "chana dal", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala", "green chili"],
    searchKeywords: ["chicken", "spicy chicken dal", "hot chicken curry", "fiery chicken", "chana dal chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Moong Dal",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup moong dal (split yellow lentils) - washed",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash moong dal well under running water. Moong dal does not need soaking.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and mushy.",
      "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add washed moong dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 25-30 minutes until the chicken and dal are tender.",
      "Decorate with fresh coriander leaves and serve hot with steamed rice or roti."
    ],
    difficulty: "Easy",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Light and easy-to-digest chicken curry with split yellow moong dal – a healthy, comforting one-pot meal.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 75,
    baseServings: 4,
    calories: 330,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "moong dal", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["chicken", "chicken moong dal", "yellow lentil chicken", "light chicken dal", "healthy chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Moong Dal Fry",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup moong dal - washed",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon mustard seeds",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash moong dal well.",
      "Heat oil in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add tomato puree and cook for 5-6 minutes until the oil separates from the masala.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add washed moong dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 25-30 minutes until the chicken and dal are tender.",
      "Add garam masala and serve hot with naan or roti."
    ],
    difficulty: "Easy",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Chicken and moong dal with mustard and cumin tadka – a fragrant, restaurant-style curry.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 78,
    baseServings: 4,
    calories: 340,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "moong dal", "onion", "tomato", "ginger", "garlic", "mustard seeds", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["chicken", "chicken moong dal fry", "tempered chicken dal", "fry dal chicken", "restaurant style chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Moong Dal Palak",
    image: "Chicken-Chana-Dal-Palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup moong dal - washed",
      "2 cups fresh spinach - washed and finely chopped",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash moong dal well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped spinach and cook for 3-4 minutes until the spinach wilts completely.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add washed moong dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 25-30 minutes until the chicken and dal are tender.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Healthy green curry with chicken, moong dal, and fresh spinach – good for you, iron-rich, and tasty.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Mixed",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 72,
    baseServings: 4,
    calories: 310,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general", "diabetes", "heart"],
    pantryKeywords: ["chicken", "moong dal", "spinach", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili"],
    searchKeywords: ["chicken", "chicken moong dal palak", "spinach chicken dal", "green chicken curry", "healthy dal chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Moong Dal Louki",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup moong dal - washed",
      "2 cups louki (bottle gourd) - peeled and cut into small pieces",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash moong dal well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add louki pieces and cook for 5-6 minutes, stirring now and then.",
      "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add washed moong dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 25-30 minutes until the chicken, dal, and louki are all tender.",
      "Serve hot with steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Light summer curry with chicken, moong dal, and bottle gourd (louki) – good for you, easy to digest, and great with rice.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 70,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general", "diabetes", "heart"],
    pantryKeywords: ["chicken", "moong dal", "louki", "bottle gourd", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["chicken", "chicken moong dal louki", "bottle gourd chicken dal", "light summer curry", "healthy chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Light Chicken Moong Dal",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - skinless, cut into pieces",
      "1 cup moong dal - washed",
      "1 medium onion - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1/4 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash moong dal well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 4-5 minutes until soft and see-through.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add washed moong dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 25-30 minutes until the chicken and dal are tender.",
      "Decorate with fresh coriander leaves and serve hot with steamed rice."
    ],
    difficulty: "Easy",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Light and healthy low-oil chicken curry with moong dal – simple, wholesome, and easy to digest.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 68,
    baseServings: 4,
    calories: 300,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general", "diabetes", "heart"],
    pantryKeywords: ["chicken", "moong dal", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili"],
    searchKeywords: ["chicken", "light chicken moong dal", "low oil chicken dal", "healthy chicken curry", "easy chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Maash Dal",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup maash dal (black lentils / urad dal) - washed and soaked",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash maash dal well. Soak in fresh water for 2 hours. Drain before cooking.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white and gets a little brown.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and mushy.",
      "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add soaked maash dal and 3 cups of warm water. Stir well.",
      "Cover and cook for 35-40 minutes until the chicken and dal are completely tender.",
      "Sprinkle garam masala and decorate with fresh coriander leaves.",
      "Serve hot with naan, roti, or steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Rich and creamy chicken curry with black lentils (maash dal / urad dal) – hearty, tasty, and great with naan.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "maash dal", "black lentils", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["chicken", "chicken maash dal", "black lentil chicken curry", "urad dal chicken", "creamy chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Maash Dal Fry",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup maash dal - washed and soaked",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon mustard seeds",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash maash dal and soak for 2 hours. Drain well.",
      "Heat oil in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add tomato puree and cook for 5-6 minutes until the oil separates from the masala.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add soaked maash dal and 3 cups of warm water. Stir well.",
      "Cover and cook for 35-40 minutes until the chicken and dal are tender.",
      "Add garam masala and serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Chicken and black lentils (maash dal) with mustard and cumin tadka – aromatic, rich, and restaurant-style.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 88,
    baseServings: 4,
    calories: 400,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "maash dal", "black lentils", "onion", "tomato", "ginger", "garlic", "mustard seeds", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["chicken", "chicken maash dal fry", "tempered black lentil chicken", "fry chicken dal", "restaurant style chicken maash"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Maash Dal Palak",
    image: "Chicken-Chana-Dal-Palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup maash dal - washed and soaked",
      "2 cups fresh spinach - washed and finely chopped",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash maash dal and soak for 2 hours. Drain well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped spinach and cook for 3-4 minutes until wilted.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add soaked maash dal and 3 cups of warm water. Stir well.",
      "Cover and cook for 35-40 minutes until the chicken and dal are tender.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Healthy chicken curry with black lentils (maash dal) and fresh spinach – iron-rich, good for you, and tasty.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Mixed",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 370,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "maash dal", "spinach", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili"],
    searchKeywords: ["chicken", "chicken maash dal palak", "black lentil spinach chicken", "healthy chicken dal", "palak chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Creamy Chicken Maash Dal",
    image: "creamy-chicken-maash-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup maash dal - washed and soaked",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1/4 cup heavy cream",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash maash dal and soak for 2 hours. Drain well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add tomato puree and cook for 5-6 minutes until the oil separates from the masala.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add soaked maash dal and 3 cups of warm water. Stir well.",
      "Cover and cook for 35-40 minutes until the chicken and dal are tender.",
      "Add cream and simmer for 5-7 minutes on low heat. Do not boil after adding cream.",
      "Serve hot with butter naan or steamed rice."
    ],
    difficulty: "Hard",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Rich and creamy chicken curry with black lentils (maash dal) finished with heavy cream – a fancy, restaurant-style dish.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 95,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "maash dal", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "cream"],
    searchKeywords: ["chicken", "creamy chicken maash dal", "rich black lentil chicken", "restaurant style chicken dal", "dal makhani style chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Masoor Dal",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup masoor dal (red lentils) - washed",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash masoor dal well. Masoor dal does not need soaking.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and mushy.",
      "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add washed masoor dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 20-25 minutes until the chicken and dal are tender.",
      "Decorate with fresh coriander leaves and serve hot with steamed rice or roti."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Quick and easy chicken curry with red lentils (masoor dal) – cooks fast, tasty, and great for weeknight dinners.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 70,
    baseServings: 4,
    calories: 340,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "masoor dal", "red lentils", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["chicken", "chicken masoor dal", "red lentil chicken", "quick chicken dal", "easy chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Masoor Dal Fry",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup masoor dal - washed",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon mustard seeds",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash masoor dal well.",
      "Heat oil in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add tomato puree and cook for 5-6 minutes until the oil separates from the masala.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add washed masoor dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 20-25 minutes until the chicken and dal are tender.",
      "Add garam masala and serve hot with naan or roti."
    ],
    difficulty: "Easy",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Chicken and red lentils (masoor dal) with mustard and cumin tadka – aromatic and tasty.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 72,
    baseServings: 4,
    calories: 350,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "masoor dal", "red lentils", "onion", "tomato", "ginger", "garlic", "mustard seeds", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["chicken", "chicken masoor dal fry", "tempered red lentil chicken", "fry chicken masoor dal", "restaurant style chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Masoor Dal Palak",
    image: "Chicken-Chana-Dal-Palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup masoor dal - washed",
      "2 cups fresh spinach - washed and finely chopped",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash masoor dal well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped spinach and cook for 3-4 minutes until wilted.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add washed masoor dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 20-25 minutes until the chicken and dal are tender.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Healthy green curry with chicken, red lentils (masoor dal), and fresh spinach – good for you, quick, and tasty.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Mixed",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 68,
    baseServings: 4,
    calories: 330,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "masoor dal", "spinach", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili"],
    searchKeywords: ["chicken", "chicken masoor dal palak", "red lentil spinach chicken", "healthy green chicken curry", "palak chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Quick Chicken Masoor Dal",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - boneless, cut into pieces",
      "1 cup masoor dal - washed",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1/4 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash masoor dal well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 4-5 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add washed masoor dal and 2 cups of warm water. Stir well.",
      "Cover and cook for 20 minutes until the chicken and dal are tender.",
      "Serve hot with steamed rice or roti."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Super quick and easy chicken curry with red lentils (masoor dal) – ready in just 30 minutes, great for busy weeknights.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 72,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "masoor dal", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili"],
    searchKeywords: ["chicken", "quick chicken masoor dal", "30 minute chicken dal", "easy chicken curry", "boneless chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Mix Dal",
    image: "chicken-mix-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1/3 cup chana dal - washed and soaked",
      "1/3 cup moong dal - washed",
      "1/3 cup masoor dal - washed",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash all dals together. Soak chana dal separately for 30 minutes as it takes longer to cook.",
      "Mix all dals together.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and mushy.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add mixed dals and 3 cups of warm water. Stir well.",
      "Cover and cook for 30-35 minutes until the chicken and all dals are tender.",
      "Add garam masala and fresh coriander leaves. Mix well.",
      "Serve hot with steamed rice or roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Hearty chicken curry with a mix of three lentils (chana, moong, masoor) – the best of all dals in one pot.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 78,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "chana dal", "moong dal", "masoor dal", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["chicken", "chicken mix dal", "mixed lentil chicken curry", "three dal chicken", "panchmel dal chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Panchmel Dal",
    image: "panchmel-dal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1/4 cup each: chana dal, moong dal, masoor dal, urad dal, toor dal",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash all dals together. Soak chana dal and urad dal for 1 hour as they take longer to cook.",
      "Mix all dals together.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add tomato puree and cook for 5-6 minutes until the oil separates from the masala.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add mixed dals and 3 cups of warm water. Stir well.",
      "Cover and cook for 35-40 minutes until the chicken and all dals are tender.",
      "Add garam masala and serve hot with naan or steamed rice."
    ],
    difficulty: "Hard",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Rajasthani-style chicken curry with five lentils (panchmel dal) – a tasty, protein-packed one-pot meal.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "chana dal", "moong dal", "masoor dal", "urad dal", "toor dal", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["chicken", "chicken panchmel dal", "five lentil chicken curry", "rajasthani chicken dal", "mixed dal chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Dal Makhani",
    image: "mutton-dal-makhni.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup whole urad dal (sabut urad) - washed and soaked overnight",
      "1/4 cup rajma (kidney beans) - washed and soaked overnight",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1/4 cup heavy cream",
      "3 tablespoons butter",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash urad dal and rajma together. Soak in plenty of water overnight (8-10 hours). Drain before cooking.",
      "In a pressure cooker, add soaked dal and rajma, 3 cups of water, turmeric powder, and salt. Pressure cook for 5-6 whistles until very soft.",
      "Let the pressure release naturally. Mash the dal well with a masher. Set aside.",
      "Heat butter in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add tomato puree and cook for 5-6 minutes until the butter separates from the masala.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Add 1/2 cup of water if needed.",
      "Simmer on low heat for 20-25 minutes until the chicken is tender.",
      "Add cream and simmer for 5-7 minutes on low heat.",
      "Decorate with fresh coriander leaves and a spoonful of butter.",
      "Serve hot with butter naan or steamed rice."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Restaurant-style creamy chicken with black lentils (urad dal) and kidney beans – rich, buttery, and indulgent.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 110,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "urad dal", "rajma", "kidney beans", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "cream", "butter"],
    searchKeywords: ["chicken", "chicken dal makhani", "creamy chicken black lentil", "restaurant style chicken dal", "butter chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Dal Bukhara",
    image: "mutton-dal-makhni.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup whole urad dal (sabut urad) - washed and soaked overnight",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1/4 cup heavy cream",
      "1/4 cup butter",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash urad dal and soak overnight. Drain before cooking.",
      "In a pressure cooker, add soaked dal, 3 cups of water, and salt. Pressure cook for 5-6 whistles until very soft.",
      "Let the pressure release naturally. Mash the dal well. Set aside.",
      "Heat butter in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 7-8 minutes until dark golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add tomato puree and cook for 5-6 minutes until the butter separates from the masala.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer on low heat for 25-30 minutes.",
      "Add cream and garam masala. Simmer for 10 minutes.",
      "Decorate with fresh coriander leaves and serve with butter naan."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Peshawari-style royal dish – creamy black lentil dal with chicken, slow-simmered with butter and cream.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 105,
    baseServings: 4,
    calories: 470,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "urad dal", "black lentils", "onion", "tomato", "ginger", "garlic", "cumin", "red chili", "garam masala", "cream", "butter"],
    searchKeywords: ["chicken", "chicken dal bukhara", "peshawari chicken dal", "royal black dal chicken", "dal bukhara with chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Dal Palak",
    image: "chicken-chana-daal-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup mixed dal (moong dal + masoor dal) - washed",
      "2 cups fresh spinach - washed and finely chopped",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash the mixed dals well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped spinach and cook for 3-4 minutes until wilted.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add the mixed dals and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 25-30 minutes until the chicken and dal are tender.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Healthy chicken curry with a mix of moong and masoor dal, plus fresh spinach – a good-for-you, tasty one-pot meal.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Mixed",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 70,
    baseServings: 4,
    calories: 340,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "moong dal", "masoor dal", "spinach", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili"],
    searchKeywords: ["chicken", "chicken dal palak", "spinach chicken dal", "healthy chicken curry", "green chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Dal Louki",
    image: "chana-dal-lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup moong dal - washed",
      "2 cups louki (bottle gourd) - peeled and cut into small pieces",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash moong dal well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add louki pieces and cook for 5-6 minutes, stirring now and then.",
      "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add washed moong dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 25-30 minutes until the chicken, dal, and louki are all tender.",
      "Serve hot with steamed rice or roti."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Light summer curry with chicken, moong dal, and bottle gourd (louki) – refreshing, easy to digest, and great with rice.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 68,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "moong dal", "louki", "bottle gourd", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["chicken", "chicken dal louki", "bottle gourd chicken dal", "light summer curry", "healthy chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Dal Tori",
    image: "chana-dal-lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup chana dal - washed and soaked",
      "2 cups tori (ridge gourd) - peeled and cut into small pieces",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash chana dal and soak for 30 minutes. Drain well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add tori pieces and cook for 5-6 minutes, stirring now and then.",
      "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add soaked chana dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 30-35 minutes until the chicken, dal, and tori are all tender.",
      "Serve hot with steamed rice or roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Special and tasty chicken curry with chana dal and ridge gourd (tori) – a good-for-you, high-fiber dish.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Mixed",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 72,
    baseServings: 4,
    calories: 350,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "chana dal", "tori", "ridge gourd", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["chicken", "chicken dal tori", "ridge gourd chicken dal", "chana dal chicken", "healthy vegetable chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Dal Methi",
    image: "chana-dal-lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup moong dal - washed",
      "1 large bunch fresh methi (fenugreek leaves) - washed and finely chopped",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1/2 cup cooking oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash moong dal well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped methi leaves and cook for 3-4 minutes until wilted.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add washed moong dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 25-30 minutes until the chicken and dal are tender.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Aromatic chicken curry with moong dal and fresh fenugreek leaves (methi) – a little bitter, very tasty, and healthy.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Mixed",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 70,
    baseServings: 4,
    calories: 335,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "moong dal", "methi", "fenugreek leaves", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili"],
    searchKeywords: ["chicken", "chicken dal methi", "fenugreek chicken dal", "methi chicken curry", "healthy dal chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Dal Tadka",
    image: "chana-dal-lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup toor dal - washed",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons ghee",
      "1 teaspoon mustard seeds",
      "2 dried red chilies",
      "Few curry leaves",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash toor dal well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and mushy.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add toor dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 25-30 minutes until the chicken and dal are tender.",
      "For the tadka: In a small pan, heat ghee. Add mustard seeds, dried red chilies, and curry leaves. Let them crackle for 30 seconds.",
      "Pour the hot tadka over the curry. Add garam masala and fresh coriander leaves.",
      "Serve hot with steamed rice or jeera rice."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Restaurant-style chicken and toor dal with ghee tadka – aromatic, spicy, and very tasty.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "toor dal", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "ghee", "mustard seeds", "curry leaves"],
    searchKeywords: ["chicken", "chicken dal tadka", "tempered chicken dal", "restaurant style chicken dal", "tadka dal with chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Dal Fry",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup mixed dal (toor dal + moong dal) - washed",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "1 small capsicum - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1 teaspoon kasuri methi (dried fenugreek leaves)",
      "1/2 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash the mixed dals well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add finely chopped capsicum and cook for 2-3 minutes.",
      "Add tomato puree and cook for 5-6 minutes until the oil separates from the masala.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add the mixed dals and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 25-30 minutes until the chicken and dal are tender.",
      "Crush kasuri methi between your palms and add to the curry. Add garam masala and fresh coriander leaves.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Restaurant-style dal fry with chicken – a tasty mix of toor and moong dal, capsicum, and kasuri methi.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 78,
    baseServings: 4,
    calories: 360,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "toor dal", "moong dal", "onion", "capsicum", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "kasuri methi"],
    searchKeywords: ["chicken", "chicken dal fry", "restaurant dal fry with chicken", "mixed dal chicken", "capsicum chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Hyderabadi Chicken Dal",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup chana dal - washed and soaked",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration",
      "2 green chilies - slit"
    ],
    stepsRaw: [
      "Wash chana dal and soak for 30 minutes. Drain well.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and green chilies. Cook for 5-6 minutes until soft.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add soaked chana dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 30-35 minutes until the chicken and dal are tender.",
      "Add garam masala and fresh coriander leaves. Mix well.",
      "Serve hot with steamed rice or roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Hyderabadi-style chicken with chana dal – earthy, tasty, and mildly spiced, great with steamed rice.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 75,
    baseServings: 4,
    calories: 360,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "chana dal", "onion", "tomato", "green chili", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["chicken", "hyderabadi chicken dal", "chana dal chicken hyderabadi", "south indian chicken dal", "flavorful chicken dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Punjabi Chicken Dal",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup maash dal - washed and soaked",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons butter",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash maash dal and soak for 2 hours. Drain well.",
      "Heat butter in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add tomato puree and cook for 5-6 minutes until the butter separates from the masala.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add soaked maash dal and 3 cups of warm water. Stir well.",
      "Cover and cook for 35-40 minutes until the chicken and dal are tender.",
      "Add garam masala and fresh coriander leaves. Mix well.",
      "Serve hot with butter naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Rich and buttery Punjabi-style chicken with black lentils (maash dal) – creamy, hearty, and full of flavor.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 90,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "maash dal", "black lentils", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "butter"],
    searchKeywords: ["chicken", "punjabi chicken dal", "buttery chicken dal", "maash dal chicken", "rich chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "South Indian Chicken Dal",
    image: "chicken-chana-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup toor dal - washed",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon mustard seeds",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1/2 teaspoon asafoetida (hing)",
      "Few curry leaves",
      "1 tablespoon lemon juice",
      "1/4 cup cooking oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash toor dal well.",
      "Heat oil in a pan over medium heat. Add mustard seeds, cumin seeds, asafoetida, and curry leaves. Let them crackle for 30 seconds.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken pieces and fry for 5-7 minutes until the chicken turns white.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft.",
      "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
      "Add toor dal and 2.5 cups of warm water. Stir well.",
      "Cover and cook for 25-30 minutes until the chicken and dal are tender.",
      "Add lemon juice and fresh coriander leaves. Mix well.",
      "Serve hot with steamed rice or dosa."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Tangy and spicy South Indian-style chicken with toor dal, with mustard seeds, curry leaves, and a hint of lemon.",
    category: "Dinner",
    subCategory: "dal-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "standard",
    costPerServing: 72,
    baseServings: 4,
    calories: 330,
    ageGroup: ["adults", "teens"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "toor dal", "tomato", "ginger", "garlic", "mustard seeds", "cumin", "asafoetida", "curry leaves", "turmeric", "red chili", "lemon"],
    searchKeywords: ["chicken", "south indian chicken dal", "tangy chicken dal", "lemon chicken dal", "dosa curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
];

async function migrateRecipes() {
  try {
    console.log('Connecting to MongoDB...');
    
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) {
      throw new Error('MongoDB URI not found');
    }
    
    await mongoose.connect(mongoURI, { 
      serverSelectionTimeoutMS: 10000, 
      family: 4 
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();