const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
  {
  title: "Mutton Chana Dal",
  image: "mutton-chana-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - curry cut pieces with bones",
    "1 cup chana dal (split Bengal gram) - washed and soaked",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon coriander powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste",
    "Fresh coriander leaves for garnish",
    "2 green chilies - slit lengthwise"
  ],
  stepsRaw: [
    "Wash chana dal well under running water. Soak in fresh water for 30 minutes. Drain before cooking.",
    "Heat oil in a large heavy-bottomed pot over medium heat. Add cumin seeds and let them crackle for 30 seconds until they smell good.",
    "Add finely chopped onions and cook for 6-7 minutes until they turn golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until the raw smell goes away.",
    "Add mutton pieces and fry on high heat for 8-10 minutes until the mutton is well-browned on all sides.",
    "Add chopped tomatoes and cook for 6-7 minutes until they become soft and mushy.",
    "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2-3 minutes until the spices smell good.",
    "Add soaked chana dal and 4 cups of warm water. Stir well to mix everything.",
    "Cover the pot with a lid and cook on medium heat for 45-50 minutes until the mutton and dal are completely tender.",
    "Sprinkle garam masala and garnish with fresh coriander leaves and green chilies.",
    "Serve hot with naan, roti, or steamed rice."
  ],
  difficulty: "Hard",
  cookingTime: 70,
  isActive: true,
  isHalal: true,
  description: "Rich, hearty mutton curry with chana dal – slow-cooked until tender, great with naan or rice.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 75,
  baseServings: 4,
  calories: 480,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "chana dal", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
  searchKeywords: ["mutton", "chana dal", "mutton dal", "pakistani mutton", "dal curry"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Chana Dal Fry",
  image: "mutton-chana-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup chana dal - washed and soaked",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - blended into smooth puree",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon mustard seeds",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash chana dal and soak for 30 minutes. Drain well.",
    "Heat oil in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add tomato puree and cook for 6-7 minutes until the oil separates from the masala.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add soaked chana dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 45-50 minutes until the mutton and dal are tender.",
    "Add garam masala and fresh coriander leaves. Mix well.",
    "Serve hot with naan or steamed rice."
  ],
  difficulty: "Hard",
  cookingTime: 70,
  isActive: true,
  isHalal: true,
  description: "Restaurant-style mutton and chana dal with mustard and cumin tadka – rich, aromatic, and tasty.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 78,
  baseServings: 4,
  calories: 500,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "chana dal", "mustard seeds", "cumin", "onion", "tomato", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "chana dal", "mutton dal fry", "tempered mutton dal", "restaurant style"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Chana Dal Palak",
  image: "mutton-dal-palak.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup chana dal - washed and soaked",
    "2 cups fresh spinach - washed and finely chopped",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash chana dal and soak for 30 minutes. Drain well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add chopped spinach and cook for 3-4 minutes until the spinach wilts completely.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add soaked chana dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 45-50 minutes until the mutton and dal are tender.",
    "Sprinkle garam masala and serve hot with roti or naan."
  ],
  difficulty: "Hard",
  cookingTime: 70,
  isActive: true,
  isHalal: true,
  description: "Healthy and tasty mutton curry with chana dal and fresh spinach – iron-rich and hearty.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 72,
  baseServings: 4,
  calories: 460,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "chana dal", "spinach", "onion", "tomato", "ginger", "garlic", "cumin", "garam masala"],
  searchKeywords: ["mutton", "chana dal", "mutton dal palak", "spinach mutton", "healthy mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Chana Dal Louki",
  image: "mutton-dal-lauki.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup chana dal - washed and soaked",
    "2 cups louki (bottle gourd) - peeled and cut into small pieces",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon coriander powder",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash chana dal and soak for 30 minutes. Drain well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add louki pieces and cook for 5-6 minutes, stirring now and then.",
    "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
    "Add soaked chana dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 45-50 minutes until the mutton, dal, and louki are all tender.",
    "Serve hot with steamed rice or roti."
  ],
  difficulty: "Hard",
  cookingTime: 70,
  isActive: true,
  isHalal: true,
  description: "Light and healthy mutton curry with chana dal and bottle gourd (louki) – a wholesome, low-oil dish.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 70,
  baseServings: 4,
  calories: 440,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "chana dal", "louki", "bottle gourd", "onion", "tomato", "ginger", "garlic", "cumin", "coriander"],
  searchKeywords: ["mutton", "chana dal", "mutton dal louki", "bottle gourd mutton", "light mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Spicy Mutton Chana Dal",
  image: "mutton-chana-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup chana dal - washed and soaked",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "3 teaspoons red chili powder",
    "1 teaspoon coriander powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste",
    "2 green chilies - finely chopped"
  ],
  stepsRaw: [
    "Wash chana dal and soak for 30 minutes. Drain well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and green chilies. Cook for 6-7 minutes until soft.",
    "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2-3 minutes.",
    "Add soaked chana dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 45-50 minutes until the mutton and dal are tender.",
    "Sprinkle garam masala and serve hot with naan or steamed rice."
  ],
  difficulty: "Hard",
  cookingTime: 70,
  isActive: true,
  isHalal: true,
  description: "Extra spicy mutton and chana dal curry loaded with red chili and green chilies – for heat lovers only.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 74,
  baseServings: 4,
  calories: 490,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "chana dal", "onion", "tomato", "ginger", "garlic", "red chili", "green chili", "garam masala"],
  searchKeywords: ["mutton", "chana dal", "spicy mutton", "hot mutton dal", "fiery mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Moong Dal",
  image: "mutton-moong-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup moong dal (split yellow lentils) - washed",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon coriander powder",
    "1/2 cup cooking oil",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash moong dal well under running water. Moong dal does not need soaking.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 6-7 minutes until soft and mushy.",
    "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2-3 minutes.",
    "Add washed moong dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 40-45 minutes until the mutton and dal are tender.",
    "Garnish with fresh coriander leaves and serve hot with steamed rice or roti."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Light and easy-to-digest mutton curry with split yellow moong dal – a comforting, healthy meal.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 68,
  baseServings: 4,
  calories: 430,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
  searchKeywords: ["mutton", "moong dal", "mutton moong dal", "yellow lentil mutton", "light mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Moong Dal Fry",
  image: "mutton-moong-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup moong dal - washed",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - blended into smooth puree",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon mustard seeds",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash moong dal well.",
    "Heat oil in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add tomato puree and cook for 6-7 minutes until the oil separates from the masala.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add washed moong dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 40-45 minutes until the mutton and dal are tender.",
    "Add garam masala and serve hot with naan or roti."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Mutton and moong dal with mustard and cumin tadka – a fragrant, restaurant-style curry.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 70,
  baseServings: 4,
  calories: 450,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "mustard seeds", "cumin", "onion", "tomato", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "moong dal", "mutton moong dal fry", "tempered mutton dal", "restaurant style"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Moong Dal Palak",
  image: "mutton-dal-palak.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup moong dal - washed",
    "2 cups fresh spinach - washed and finely chopped",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash moong dal well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add chopped spinach and cook for 3-4 minutes until the spinach wilts completely.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add washed moong dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 40-45 minutes until the mutton and dal are tender.",
    "Serve hot with roti or naan."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Healthy green curry with mutton, moong dal, and fresh spinach – nutritious, iron-rich, and tasty.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 66,
  baseServings: 4,
  calories: 420,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "spinach", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric"],
  searchKeywords: ["mutton", "moong dal", "mutton moong dal palak", "spinach mutton", "healthy mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Moong Dal Louki",
  image: "mutton-dal-lauki.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup moong dal - washed",
    "2 cups louki (bottle gourd) - peeled and cut into small pieces",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon coriander powder",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash moong dal well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add louki pieces and cook for 5-6 minutes, stirring now and then.",
    "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
    "Add washed moong dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 40-45 minutes until the mutton, dal, and louki are all tender.",
    "Serve hot with steamed rice."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Light summer curry with mutton, moong dal, and bottle gourd (louki) – refreshing, nutritious, and easy to digest.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 68,
  baseServings: 4,
  calories: 410,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "louki", "bottle gourd", "onion", "tomato", "ginger", "garlic", "cumin", "coriander"],
  searchKeywords: ["mutton", "moong dal", "mutton dal louki", "bottle gourd mutton", "light mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Light Mutton Moong Dal",
  image: "mutton-moong-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - lean pieces",
    "1 cup moong dal - washed",
    "1 medium onion - finely chopped",
    "1 tablespoon ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1/2 teaspoon turmeric powder",
    "1 teaspoon red chili powder",
    "1/4 cup cooking oil",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash moong dal well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 4-5 minutes until soft and see-through.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add washed moong dal and 3 cups of warm water. Stir well.",
    "Cover and cook for 40-45 minutes until the mutton and dal are tender.",
    "Garnish with fresh coriander leaves and serve hot with steamed rice."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Light, low-oil mutton and moong dal curry – a healthy, wholesome, and easy-to-digest meal.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 65,
  baseServings: 4,
  calories: 390,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili"],
  searchKeywords: ["mutton", "moong dal", "light mutton", "low oil mutton", "healthy mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Maash Dal",
  image: "mutton-mash-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup maash dal (black lentils / urad dal) - washed and soaked",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon coriander powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash maash dal well. Soak in fresh water for 2 hours. Drain before cooking.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 6-7 minutes until soft and mushy.",
    "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2-3 minutes.",
    "Add soaked maash dal and 4 cups of warm water. Stir well.",
    "Cover and cook for 50-55 minutes until the mutton and dal are completely tender.",
    "Sprinkle garam masala and garnish with fresh coriander leaves.",
    "Serve hot with naan, roti, or steamed rice."
  ],
  difficulty: "Hard",
  cookingTime: 75,
  isActive: true,
  isHalal: true,
  description: "Rich and creamy black lentil (maash dal) cooked with tender mutton – a hearty, slow-cooked Pakistani dish.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 80,
  baseServings: 4,
  calories: 520,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "maash dal", "black lentils", "onion", "tomato", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "maash dal", "mutton maash dal", "black lentil mutton", "creamy mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Maash Dal Fry",
  image: "mutton-mash-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup maash dal - washed and soaked",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - blended into smooth puree",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon mustard seeds",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash maash dal and soak for 2 hours. Drain well.",
    "Heat oil in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add tomato puree and cook for 6-7 minutes until the oil separates from the masala.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add soaked maash dal and 4 cups of warm water. Stir well.",
    "Cover and cook for 50-55 minutes until the mutton and dal are tender.",
    "Add garam masala and serve hot with naan or roti."
  ],
  difficulty: "Hard",
  cookingTime: 75,
  isActive: true,
  isHalal: true,
  description: "Mutton and black lentils with mustard and cumin tadka – a fragrant, restaurant-style dal fry.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 82,
  baseServings: 4,
  calories: 530,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "maash dal", "mustard seeds", "cumin", "onion", "tomato", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "maash dal", "mutton maash dal fry", "tempered black lentil", "restaurant style"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Maash Dal Palak",
  image: "mutton-dal-palak.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup maash dal - washed and soaked",
    "2 cups fresh spinach - washed and finely chopped",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash maash dal and soak for 2 hours. Drain well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add chopped spinach and cook for 3-4 minutes until wilted.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add soaked maash dal and 4 cups of warm water. Stir well.",
    "Cover and cook for 50-55 minutes until the mutton and dal are tender.",
    "Serve hot with roti or naan."
  ],
  difficulty: "Hard",
  cookingTime: 75,
  isActive: true,
  isHalal: true,
  description: "Nutritious mutton and black lentil curry with fresh spinach – iron-rich, hearty, and tasty.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 76,
  baseServings: 4,
  calories: 490,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "maash dal", "spinach", "onion", "tomato", "ginger", "garlic", "cumin"],
  searchKeywords: ["mutton", "maash dal", "mutton maash dal palak", "spinach black lentil", "healthy mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Creamy Mutton Maash Dal",
  image: "creamy-mutton-mash-dal.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup maash dal - washed and soaked",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - blended into smooth puree",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1/4 cup heavy cream",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash maash dal and soak for 2 hours. Drain well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add tomato puree and cook for 6-7 minutes until the oil separates from the masala.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add soaked maash dal and 4 cups of warm water. Stir well.",
    "Cover and cook for 50-55 minutes until the mutton and dal are tender.",
    "Add cream and simmer for 5-7 minutes on low heat. Do not boil after adding cream.",
    "Serve hot with butter naan or steamed rice."
  ],
  difficulty: "Hard",
  cookingTime: 75,
  isActive: true,
  isHalal: true,
  description: "Rich, creamy mutton and black lentil dal finished with heavy cream – a luxurious, indulgent dish.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "standard",
  costPerServing: 88,
  baseServings: 4,
  calories: 560,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "maash dal", "cream", "onion", "tomato", "ginger", "garlic", "cumin"],
  searchKeywords: ["mutton", "maash dal", "creamy mutton", "rich mutton dal", "indulgent mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Masoor Dal",
  image: "mutton-moong-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup masoor dal (red lentils) - washed",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon coriander powder",
    "1/2 cup cooking oil",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash masoor dal well. Masoor dal does not need soaking.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 6-7 minutes until soft and mushy.",
    "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2-3 minutes.",
    "Add washed masoor dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 35-40 minutes until the mutton and dal are tender.",
    "Garnish with fresh coriander leaves and serve hot with steamed rice or roti."
  ],
  difficulty: "Hard",
  cookingTime: 60,
  isActive: true,
  isHalal: true,
  description: "Quick and easy mutton curry with red lentils (masoor dal) – a fast-cooking, tasty weeknight meal.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 72,
  baseServings: 4,
  calories: 450,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "masoor dal", "red lentils", "onion", "tomato", "ginger", "garlic", "cumin", "coriander"],
  searchKeywords: ["mutton", "masoor dal", "mutton masoor dal", "red lentil mutton", "quick mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Masoor Dal Fry",
  image: "mutton-moong-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup masoor dal - washed",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - blended into smooth puree",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon mustard seeds",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash masoor dal well.",
    "Heat oil in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add tomato puree and cook for 6-7 minutes until the oil separates from the masala.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add washed masoor dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 35-40 minutes until the mutton and dal are tender.",
    "Add garam masala and serve hot with naan or roti."
  ],
  difficulty: "Hard",
  cookingTime: 60,
  isActive: true,
  isHalal: true,
  description: "Mutton and red lentils with a mustard-cumin tadka – a fragrant, quick dal fry.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 74,
  baseServings: 4,
  calories: 460,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "masoor dal", "mustard seeds", "cumin", "onion", "tomato", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "masoor dal", "mutton masoor dal fry", "tempered red lentil", "quick dal fry"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Masoor Dal Palak",
  image: "mutton-dal-palak.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup masoor dal - washed",
    "2 cups fresh spinach - washed and finely chopped",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash masoor dal well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add chopped spinach and cook for 3-4 minutes until wilted.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add washed masoor dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 35-40 minutes until the mutton and dal are tender.",
    "Serve hot with roti or naan."
  ],
  difficulty: "Hard",
  cookingTime: 60,
  isActive: true,
  isHalal: true,
  description: "Healthy mutton curry with red lentils and fresh spinach – a nutritious, iron-rich meal.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 70,
  baseServings: 4,
  calories: 430,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "masoor dal", "spinach", "onion", "tomato", "ginger", "garlic", "cumin"],
  searchKeywords: ["mutton", "masoor dal", "mutton masoor dal palak", "spinach mutton", "healthy mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Quick Mutton Masoor Dal",
  image: "mutton-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - boneless, cut into pieces",
    "1 cup masoor dal - washed",
    "1 medium onion - finely chopped",
    "2 medium tomatoes - finely chopped",
    "1 tablespoon ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1/2 teaspoon turmeric powder",
    "1 teaspoon red chili powder",
    "1/4 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash masoor dal well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add washed masoor dal and 3 cups of warm water. Stir well.",
    "Cover and cook for 35 minutes until the mutton and dal are tender.",
    "Serve hot with steamed rice or roti."
  ],
  difficulty: "Hard",
  cookingTime: 55,
  isActive: true,
  isHalal: true,
  description: "Super quick mutton and red lentil curry ready in under an hour – great for busy weeknights.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 68,
  baseServings: 4,
  calories: 420,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "masoor dal", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili"],
  searchKeywords: ["mutton", "masoor dal", "quick mutton", "fast mutton dal", "easy mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Mix Dal",
  image: "mutton-mix-daal.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1/3 cup chana dal - washed and soaked",
    "1/3 cup moong dal - washed",
    "1/3 cup masoor dal - washed",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash all dals together. Soak chana dal separately for 30 minutes as it takes longer to cook.",
    "Mix all dals together.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 6-7 minutes until soft and mushy.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
    "Add mixed dals and 4 cups of warm water. Stir well.",
    "Cover and cook for 45-50 minutes until the mutton and all dals are tender.",
    "Add garam masala and fresh coriander leaves. Mix well.",
    "Serve hot with steamed rice or roti."
  ],
  difficulty: "Hard",
  cookingTime: 70,
  isActive: true,
  isHalal: true,
  description: "Hearty mutton curry with a trio of lentils (chana, moong, masoor) – a protein-packed, tasty one-pot meal.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 75,
  baseServings: 4,
  calories: 510,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "chana dal", "moong dal", "masoor dal", "onion", "tomato", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "mix dal", "mutton mix dal", "mixed lentil mutton", "protein rich"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Panchmel Dal",
  image: "mutton-panchmel-dal.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1/4 cup each: chana dal, moong dal, masoor dal, urad dal, toor dal",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - blended into smooth puree",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash all dals together. Soak chana dal and urad dal for 1 hour as they take longer to cook.",
    "Mix all dals together.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add tomato puree and cook for 6-7 minutes until the oil separates from the masala.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add mixed dals and 4 cups of warm water. Stir well.",
    "Cover and cook for 50-55 minutes until the mutton and all dals are tender.",
    "Add garam masala and serve hot with naan or steamed rice."
  ],
  difficulty: "Hard",
  cookingTime: 75,
  isActive: true,
  isHalal: true,
  description: "Rajasthani-style mutton curry with five lentils – rich, aromatic, and deeply satisfying.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 80,
  baseServings: 4,
  calories: 540,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "chana dal", "moong dal", "masoor dal", "urad dal", "toor dal", "onion", "tomato", "garam masala"],
  searchKeywords: ["mutton", "panchmel dal", "mutton panchmel", "five lentil mutton", "rajasthani"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Makhani",
  image: "mutton-dal-makhni.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup whole urad dal (sabut urad) - washed and soaked overnight",
    "1/4 cup rajma (kidney beans) - washed and soaked overnight",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - blended into smooth puree",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1/4 cup heavy cream",
    "3 tablespoons butter",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash urad dal and rajma together. Soak in plenty of water overnight (8-10 hours). Drain before cooking.",
    "In a pressure cooker, add soaked dal and rajma, 4 cups of water, turmeric powder, and salt. Pressure cook for 6-7 whistles until very soft.",
    "Let the pressure release naturally. Mash the dal well with a masher. Set aside.",
    "Heat butter in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add tomato puree and cook for 6-7 minutes until the butter separates from the masala.",
    "Add red chili powder and salt. Mix well and cook for 2 minutes.",
    "Add the cooked dal and stir well. Add 1/2 cup of water if needed.",
    "Simmer on low heat for 20-25 minutes until the mutton is tender.",
    "Add cream and simmer for 5-7 minutes on low heat.",
    "Garnish with fresh coriander leaves and a spoonful of butter.",
    "Serve hot with butter naan or steamed rice."
  ],
  difficulty: "Hard",
  cookingTime: 90,
  isActive: true,
  isHalal: true,
  description: "Restaurant-style creamy mutton and black lentil dal with kidney beans – rich, buttery, and indulgent.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "standard",
  costPerServing: 95,
  baseServings: 4,
  calories: 590,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "urad dal", "rajma", "butter", "cream", "onion", "tomato", "ginger", "garlic"],
  searchKeywords: ["mutton", "dal makhani", "mutton dal makhani", "creamy mutton", "restaurant style"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Bukhara",
  image: "mutton-dal-bukhara.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup whole urad dal (sabut urad) - washed and soaked overnight",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - blended into smooth puree",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon red chili powder",
    "1 teaspoon garam masala",
    "1/4 cup heavy cream",
    "1/4 cup butter",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash urad dal and soak overnight. Drain before cooking.",
    "In a pressure cooker, add soaked dal, 4 cups of water, and salt. Pressure cook for 6-7 whistles until very soft.",
    "Let the pressure release naturally. Mash the dal well. Set aside.",
    "Heat butter in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 7-8 minutes until dark golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add tomato puree and cook for 6-7 minutes until the butter separates from the masala.",
    "Add red chili powder and salt. Mix well and cook for 2 minutes.",
    "Add the cooked dal and stir well. Simmer on low heat for 25-30 minutes until the mutton is tender.",
    "Add cream and garam masala. Simmer for 10 minutes on low heat.",
    "Garnish with fresh coriander leaves and serve with butter naan."
  ],
  difficulty: "Hard",
  cookingTime: 90,
  isActive: true,
  isHalal: true,
  description: "Peshawari-style royal mutton and black lentil dal – slow-cooked with butter and cream, rich and aromatic.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "standard",
  costPerServing: 92,
  baseServings: 4,
  calories: 580,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "urad dal", "butter", "cream", "onion", "tomato", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "dal bukhara", "mutton dal bukhara", "peshawari mutton", "royal mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Palak",
  image: "mutton-dal-palak.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup mixed dal (moong dal + masoor dal) - washed",
    "2 cups fresh spinach - washed and finely chopped",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash the mixed dals well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add chopped spinach and cook for 3-4 minutes until wilted.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add the mixed dals and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 40-45 minutes until the mutton and dal are tender.",
    "Serve hot with roti or naan."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Healthy and tasty mutton curry with moong and masoor dal, plus fresh spinach – iron-rich and nourishing.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 72,
  baseServings: 4,
  calories: 470,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "masoor dal", "spinach", "onion", "tomato", "ginger", "garlic", "cumin"],
  searchKeywords: ["mutton", "dal palak", "mutton dal palak", "spinach mutton", "healthy mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Louki",
  image: "mutton-dal-lauki.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup moong dal - washed",
    "2 cups louki (bottle gourd) - peeled and cut into small pieces",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon coriander powder",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash moong dal well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add louki pieces and cook for 5-6 minutes, stirring now and then.",
    "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
    "Add washed moong dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 40-45 minutes until the mutton, dal, and louki are all tender.",
    "Serve hot with steamed rice or roti."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Light summer curry with mutton, moong dal, and bottle gourd (louki) – refreshing, nutritious, and easy to digest.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 68,
  baseServings: 4,
  calories: 430,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "louki", "bottle gourd", "onion", "tomato", "ginger", "garlic", "cumin", "coriander"],
  searchKeywords: ["mutton", "dal louki", "mutton dal louki", "bottle gourd mutton", "light mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Tori",
  image: "mutton-dal-tori.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup chana dal - washed and soaked",
    "2 cups tori (ridge gourd) - peeled and cut into small pieces",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon coriander powder",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash chana dal and soak for 30 minutes. Drain well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add tori pieces and cook for 5-6 minutes, stirring now and then.",
    "Add turmeric powder, red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
    "Add soaked chana dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 45-50 minutes until the mutton, dal, and tori are all tender.",
    "Serve hot with steamed rice or roti."
  ],
  difficulty: "Hard",
  cookingTime: 70,
  isActive: true,
  isHalal: true,
  description: "Unique and tasty mutton curry with chana dal and ridge gourd (tori) – a fiber-rich, tasty combination.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 72,
  baseServings: 4,
  calories: 460,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "chana dal", "tori", "ridge gourd", "onion", "tomato", "ginger", "garlic", "cumin", "coriander"],
  searchKeywords: ["mutton", "dal tori", "mutton dal tori", "ridge gourd mutton", "chana dal mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Methi",
  image: "mutton-dal-methi.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup moong dal - washed",
    "1 large bunch fresh methi (fenugreek leaves) - washed and finely chopped",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash moong dal well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add chopped methi leaves and cook for 3-4 minutes until wilted.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add washed moong dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 40-45 minutes until the mutton and dal are tender.",
    "Serve hot with roti or naan."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Aromatic mutton and moong dal curry with fresh fenugreek leaves (methi) – a little bitter, deeply tasty, and healthy.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 70,
  baseServings: 4,
  calories: 440,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "methi", "fenugreek leaves", "onion", "tomato", "ginger", "garlic", "cumin"],
  searchKeywords: ["mutton", "dal methi", "mutton dal methi", "fenugreek mutton", "aromatic mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Tadka",
  image: "mutton-dal-tadka.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup toor dal - washed",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "2 tablespoons ghee",
    "1 teaspoon mustard seeds",
    "2 dried red chilies",
    "Few curry leaves",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash toor dal well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 6-7 minutes until soft and mushy.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
    "Add toor dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 40-45 minutes until the mutton and dal are tender.",
    "For the tadka: In a small pan, heat ghee. Add mustard seeds, dried red chilies, and curry leaves. Let them crackle for 30 seconds.",
    "Pour the hot tadka over the curry. Add garam masala and fresh coriander leaves.",
    "Serve hot with steamed rice or jeera rice."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Restaurant-style mutton and toor dal with a fragrant ghee tadka of mustard seeds, curry leaves, and dried red chilies.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "standard",
  costPerServing: 78,
  baseServings: 4,
  calories: 520,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "toor dal", "ghee", "mustard seeds", "curry leaves", "onion", "tomato", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "dal tadka", "mutton dal tadka", "tempered mutton", "restaurant style"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Fry",
  image: "mutton-dal-fry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup mixed dal (toor dal + moong dal) - washed",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - blended into smooth puree",
    "1 small capsicum - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "1 teaspoon kasuri methi (dried fenugreek leaves)",
    "1/2 cup cooking oil",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash the mixed dals well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add finely chopped capsicum and cook for 2-3 minutes.",
    "Add tomato puree and cook for 6-7 minutes until the oil separates from the masala.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add the mixed dals and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 40-45 minutes until the mutton and dal are tender.",
    "Crush kasuri methi between your palms and add to the curry. Add garam masala and fresh coriander leaves.",
    "Serve hot with naan or roti."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Restaurant-style dal fry with mutton, mixed toor and moong dal, capsicum, and a hint of kasuri methi.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 75,
  baseServings: 4,
  calories: 500,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "toor dal", "moong dal", "capsicum", "tomato", "kasuri methi", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "dal fry", "mutton dal fry", "restaurant mutton", "mixed dal mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Hyderabadi Mutton Dal",
  image: "hyderabadi-mutton-dal.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup chana dal - washed and soaked",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste",
    "Fresh coriander leaves for garnish",
    "2 green chilies - slit"
  ],
  stepsRaw: [
    "Wash chana dal and soak for 30 minutes. Drain well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and green chilies. Cook for 6-7 minutes until soft.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2-3 minutes.",
    "Add soaked chana dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 45-50 minutes until the mutton and dal are tender.",
    "Add garam masala and fresh coriander leaves. Mix well.",
    "Serve hot with steamed rice or roti."
  ],
  difficulty: "Hard",
  cookingTime: 70,
  isActive: true,
  isHalal: true,
  description: "Hyderabadi-style mutton and chana dal – earthy, tasty, and mildly spiced with green chilies.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 74,
  baseServings: 4,
  calories: 490,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "chana dal", "green chili", "onion", "tomato", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "hyderabadi dal", "hyderabadi mutton", "chana dal mutton", "south indian"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Punjabi Mutton Dal",
  image: "punjabi-mutton-dal.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup maash dal - washed and soaked",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - blended into smooth puree",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "2 tablespoons butter",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash maash dal and soak for 2 hours. Drain well.",
    "Heat butter in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add tomato puree and cook for 6-7 minutes until the butter separates from the masala.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add soaked maash dal and 4 cups of warm water. Stir well.",
    "Cover and cook for 50-55 minutes until the mutton and dal are tender.",
    "Add garam masala and fresh coriander leaves. Mix well.",
    "Serve hot with butter naan or roti."
  ],
  difficulty: "Hard",
  cookingTime: 75,
  isActive: true,
  isHalal: true,
  description: "Rich, buttery Punjabi-style mutton and black lentil dal – creamy, hearty, and full of flavor.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "standard",
  costPerServing: 85,
  baseServings: 4,
  calories: 560,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "maash dal", "butter", "tomato", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "punjabi dal", "punjabi mutton", "buttery mutton", "black lentil mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "South Indian Mutton Dal",
  image: "mutton-dal-south-indian.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup toor dal - washed",
    "2 medium tomatoes - finely chopped",
    "1 tablespoon ginger-garlic paste",
    "1 teaspoon mustard seeds",
    "1 teaspoon cumin seeds",
    "1/2 teaspoon turmeric powder",
    "1 teaspoon red chili powder",
    "1/2 teaspoon asafoetida (hing)",
    "Few curry leaves",
    "1 tablespoon lemon juice",
    "1/4 cup cooking oil",
    "Salt to taste",
    "Fresh coriander leaves for garnish"
  ],
  stepsRaw: [
    "Wash toor dal well.",
    "Heat oil in a pan over medium heat. Add mustard seeds, cumin seeds, asafoetida, and curry leaves. Let them crackle for 30 seconds.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 6-7 minutes until soft.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add toor dal and 3.5 cups of warm water. Stir well.",
    "Cover and cook for 40-45 minutes until the mutton and dal are tender.",
    "Add lemon juice and fresh coriander leaves. Mix well.",
    "Serve hot with steamed rice or dosa."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Tangy, spicy South Indian-style mutton and toor dal with mustard seeds, curry leaves, and a hint of lemon.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 72,
  baseServings: 4,
  calories: 470,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "toor dal", "mustard seeds", "curry leaves", "asafoetida", "lemon", "tomato"],
  searchKeywords: ["mutton", "south indian dal", "south indian mutton", "tangy mutton", "lemon mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Karela",
  image: "karela-mutton-curry.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup toor dal - washed",
    "2 medium karela (bitter gourd) - thinly sliced",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1/2 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon dry mango powder (amchur)",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Rub karela slices with 1 teaspoon salt and set aside for 30 minutes to reduce bitterness. Rinse well with water and squeeze out the bitter juice completely.",
    "Wash toor dal well.",
    "In a pressure cooker, add dal, 3 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles until soft. Set aside.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until the mutton is well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add the prepared karela slices and fry for 5-6 minutes until lightly browned.",
    "Add red chili powder and salt. Mix well and cook for 2 minutes.",
    "Add the cooked dal and stir well. Simmer for 10-12 minutes on low heat.",
    "Sprinkle amchur powder and serve hot with steamed rice."
  ],
  difficulty: "Hard",
  cookingTime: 75,
  isActive: true,
  isHalal: true,
  description: "Healthy bitter-sweet dal with mutton, toor dal, and bitter gourd (karela) – a special taste with great health benefits.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 70,
  baseServings: 4,
  calories: 450,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "toor dal", "karela", "bitter gourd", "amchur", "onion", "tomato", "ginger", "garlic"],
  searchKeywords: ["mutton", "dal karela", "mutton dal karela", "bitter gourd mutton", "healthy mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Shimla Mirch",
  image: "mutton-dal-shimla-mirch.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup moong dal - washed",
    "2 medium capsicum (bell peppers) - cut into pieces",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash moong dal well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add washed moong dal and 3 cups of warm water. Cover and cook for 30-35 minutes.",
    "Add capsicum pieces and cook for 5-7 minutes until capsicum is tender.",
    "Sprinkle garam masala and serve hot with roti or naan."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Colorful and tasty mutton dal with bell peppers – a bright, nutritious curry with a mild crunch.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 68,
  baseServings: 4,
  calories: 460,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "capsicum", "bell peppers", "onion", "tomato", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "dal shimla mirch", "capsicum mutton", "bell pepper mutton", "colorful mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Gobhi",
  image: "mutton-dal-ghobi.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup masoor dal - washed",
    "1 medium cauliflower - cut into small florets",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1/2 cup cooking oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Wash masoor dal well.",
    "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
    "Add finely chopped onions and cook for 6-7 minutes until golden brown.",
    "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
    "Add mutton pieces and fry for 8-10 minutes until well-browned.",
    "Add chopped tomatoes and cook for 5-6 minutes until soft.",
    "Add turmeric powder, red chili powder, and salt. Mix well and cook for 2 minutes.",
    "Add washed masoor dal and 3 cups of warm water. Cover and cook for 25-30 minutes.",
    "Add cauliflower florets and cook for 10-12 minutes until cauliflower is tender.",
    "Serve hot with roti or naan."
  ],
  difficulty: "Hard",
  cookingTime: 65,
  isActive: true,
  isHalal: true,
  description: "Nutritious mutton and red lentil curry with cauliflower – a healthy, fiber-rich meal.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 65,
  baseServings: 4,
  calories: 450,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "masoor dal", "cauliflower", "onion", "tomato", "ginger", "garlic"],
  searchKeywords: ["mutton", "dal gobhi", "mutton dal gobhi", "cauliflower mutton", "healthy mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Multani",
  image: "mutton-dal-multani.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup moong dal - washed",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon coriander powder",
    "1/2 cup oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Pressure cook moong dal until soft. Set aside.",
    "Heat oil, add cumin seeds and onions. Cook until golden.",
    "Add ginger-garlic paste, cook for 2 minutes.",
    "Add mutton and fry for 8-10 minutes until browned.",
    "Add tomatoes, turmeric, red chili, coriander, salt. Cook until soft.",
    "Add cooked dal and 1 cup water. Simmer for 30 minutes.",
    "Serve hot with naan."
  ],
  difficulty: "Hard",
  cookingTime: 70,
  isActive: true,
  isHalal: true,
  description: "Traditional Multani-style mutton and moong dal – simple, home-style, and deeply satisfying.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 68,
  baseServings: 4,
  calories: 470,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "onion", "tomato", "ginger", "garlic", "cumin", "coriander"],
  searchKeywords: ["mutton", "dal multani", "multani mutton", "traditional mutton", "moong dal mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Sultani",
  image: "mutton-dal-sultani.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - boneless pieces",
    "1 cup maash dal - washed and soaked",
    "2 medium onions - thinly sliced",
    "1 cup yogurt - beaten",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon garam masala",
    "1/4 cup cream",
    "1/4 cup butter",
    "2 tablespoons cashew paste",
    "Salt to taste"
  ],
  stepsRaw: [
    "Pressure cook maash dal until very soft. Mash well.",
    "Heat butter, add cumin seeds and onions. Fry until golden brown.",
    "Add ginger-garlic paste, cook for 2 minutes.",
    "Add mutton and fry for 8-10 minutes until browned.",
    "Add yogurt, turmeric, red chili, salt. Cook for 5 minutes.",
    "Add cooked dal, cashew paste, and 1 cup water. Simmer for 30 minutes.",
    "Add cream and garam masala. Simmer for 5 minutes.",
    "Serve hot with butter naan."
  ],
  difficulty: "Hard",
  cookingTime: 85,
  isActive: true,
  isHalal: true,
  description: "Royal sultani mutton and black lentil dal with cashew paste, cream, and butter – a luxurious feast.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy", "nuts"],
  budget: "standard",
  costPerServing: 95,
  baseServings: 4,
  calories: 620,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "maash dal", "butter", "cream", "cashew", "yogurt", "ginger", "garlic", "garam masala"],
  searchKeywords: ["mutton", "dal sultani", "sultani mutton", "royal mutton", "luxurious mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Sarson",
  image: "mutton-dal-sarson.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup moong dal - washed",
    "2 cups mustard greens (sarson) - washed and finely chopped",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1/2 cup oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Pressure cook moong dal until soft. Set aside.",
    "Heat oil, add cumin seeds and onions. Cook until golden.",
    "Add ginger-garlic paste, cook for 2 minutes.",
    "Add mutton and fry for 8-10 minutes until browned.",
    "Add tomatoes, turmeric, red chili, salt. Cook until soft.",
    "Add mustard greens and cook for 5-7 minutes until wilted.",
    "Add cooked dal and 1 cup water. Simmer for 25-30 minutes.",
    "Serve hot with makki ki roti."
  ],
  difficulty: "Hard",
  cookingTime: 75,
  isActive: true,
  isHalal: true,
  description: "Winter special mutton and moong dal with mustard greens – a rustic, nutritious Punjabi classic.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 70,
  baseServings: 4,
  calories: 460,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "mustard greens", "onion", "tomato", "ginger", "garlic"],
  searchKeywords: ["mutton", "dal sarson", "sarson mutton", "winter mutton", "mustard greens mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Kaddu",
  image: "mutton-dal-kaddu.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup chana dal - washed and soaked",
    "2 cups kaddu (pumpkin) - peeled and cut into pieces",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 tablespoon jaggery",
    "1/2 cup oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Pressure cook chana dal until soft. Set aside.",
    "Heat oil, add cumin seeds and onions. Cook until golden.",
    "Add ginger-garlic paste, cook for 2 minutes.",
    "Add mutton and fry for 8-10 minutes until browned.",
    "Add tomatoes, turmeric, red chili, salt. Cook until soft.",
    "Add pumpkin pieces and cook for 5-6 minutes.",
    "Add cooked dal, jaggery, and 1 cup water. Simmer for 25-30 minutes.",
    "Serve hot with roti."
  ],
  difficulty: "Hard",
  cookingTime: 75,
  isActive: true,
  isHalal: true,
  description: "Sweet and savory mutton, chana dal, and pumpkin curry with a hint of jaggery – a unique autumnal dish.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 72,
  baseServings: 4,
  calories: 480,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "chana dal", "pumpkin", "jaggery", "onion", "tomato", "ginger", "garlic"],
  searchKeywords: ["mutton", "dal kaddu", "pumpkin mutton", "sweet savory mutton", "kaddu mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Arvi",
  image: "mutton-dal-arvi.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup masoor dal - washed",
    "2 cups arvi (colocasia) - boiled, peeled, and sliced",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1/2 cup oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Pressure cook masoor dal until soft. Set aside.",
    "Heat oil, add cumin seeds and onions. Cook until golden.",
    "Add ginger-garlic paste, cook for 2 minutes.",
    "Add mutton and fry for 8-10 minutes until browned.",
    "Add tomatoes, turmeric, red chili, salt. Cook until soft.",
    "Add cooked dal and 1 cup water. Simmer for 25 minutes.",
    "Add arvi slices and cook for 8-10 minutes until tender.",
    "Serve hot with roti."
  ],
  difficulty: "Hard",
  cookingTime: 75,
  isActive: true,
  isHalal: true,
  description: "Unique and tasty mutton, red lentil, and colocasia (arvi) curry – a tasty, off-beat combination.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 70,
  baseServings: 4,
  calories: 470,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "masoor dal", "arvi", "colocasia", "onion", "tomato", "ginger", "garlic"],
  searchKeywords: ["mutton", "dal arvi", "arvi mutton", "colocasia mutton", "unique mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Mutton Dal Tinda",
  image: "mutton-dal-with-tinda-gourd.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton - medium pieces",
    "1 cup moong dal - washed",
    "2 cups tinday (apple gourd) - peeled and cut into pieces",
    "2 medium onions - finely chopped",
    "2 medium tomatoes - finely chopped",
    "2 tablespoons ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1/2 cup oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Pressure cook moong dal until soft. Set aside.",
    "Heat oil, add cumin seeds and onions. Cook until golden.",
    "Add ginger-garlic paste, cook for 2 minutes.",
    "Add mutton and fry for 8-10 minutes until browned.",
    "Add tomatoes, turmeric, red chili, salt. Cook until soft.",
    "Add tinday pieces and cook for 5-6 minutes.",
    "Add cooked dal and 1 cup water. Simmer for 25-30 minutes.",
    "Serve hot with roti."
  ],
  difficulty: "Hard",
  cookingTime: 70,
  isActive: true,
  isHalal: true,
  description: "Light and healthy mutton, moong dal, and apple gourd (tinda) curry – a refreshing, low-oil dish.",
  category: "Lunch",
  subCategory: "dal-mutton",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 66,
  baseServings: 4,
  calories: 440,
  ageGroup: ["adults", "teens"],
  patientFriendly: ["general"],
  pantryKeywords: ["mutton", "moong dal", "tinda", "apple gourd", "onion", "tomato", "ginger", "garlic"],
  searchKeywords: ["mutton", "dal tinda", "tinda mutton", "apple gourd mutton", "light mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
}
];

async function migrateRecipes() {
  try {
    console.log('Connecting to MongoDB...');
    
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) {
      throw new Error('MongoDB URI not found');
    }
    
    await mongoose.connect(mongoURI, { 
      serverSelectionTimeoutMS: 10000, 
      family: 4 
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();