const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
  {
    title: "Banana Bread Recipe",
    image: "banana-bread.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "3 ripe bananas (mashed well)",
      "1/3 cup butter (melted)",
      "1 cup sugar",
      "1 egg (beaten)",
      "1 teaspoon vanilla essence",
      "1 teaspoon baking soda",
      "A little bit of salt",
      "1 1/2 cups plain flour (maida)",
      "1/2 cup chopped walnuts (if you like)"
    ],
    stepsRaw: [
      "Turn on the oven at 350°F (175°C). Grease a loaf pan with oil or butter.",
      "In a big bowl, mash the bananas with a fork until completely smooth.",
      "Add the melted butter to the mashed bananas and mix well.",
      "Put in the sugar, egg, and vanilla essence. Mix everything together properly.",
      "Add baking soda and salt. Mix well again.",
      "Slowly add the flour, little by little, and mix until everything is just combined. Do not overmix.",
      "If using walnuts, gently fold them into the batter.",
      "Pour the batter into the greased loaf pan.",
      "Bake for 60-65 minutes. Insert a toothpick in the center - if it comes out clean, it's ready.",
      "Let it cool in the pan for 10 minutes, then take it out and cool completely on a wire rack."
    ],
    difficulty: "Medium",
    cookingTime: 75,
    isActive: true,
    isHalal: true,
    description: "A soft and tasty banana bread that is great for breakfast, tea time, or as a sweet treat.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "eggs", "gluten", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 8,
    calories: 350,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["bananas", "butter", "sugar", "egg", "vanilla", "baking soda", "salt", "flour", "walnuts"],
    searchKeywords: ["banana bread", "bread", "dessert", "baking", "snack"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mango Caramel Delight",
    image: "Mango-Caramel-Delight.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 big ripe mangoes (peeled and cut into small pieces)",
      "1 cup sugar (for making caramel)",
      "1/4 cup water",
      "1 cup heavy cream",
      "1 teaspoon vanilla essence",
      "1/2 cup condensed milk",
      "1/2 cup whipped cream",
      "1/4 cup chopped pistachios (for decoration)"
    ],
    stepsRaw: [
      "To make caramel: Put sugar and water in a pan on medium heat.",
      "Cook without stirring until the sugar melts and turns golden brown in color.",
      "Carefully add heavy cream while stirring continuously. Be careful as it may splatter.",
      "Cook for 2-3 minutes until a smooth caramel forms.",
      "Turn off the heat and add vanilla essence. Mix well.",
      "Let the caramel cool down completely.",
      "In a blender, blend 1 1/2 mangoes with condensed milk until smooth.",
      "In serving glasses, make layers - first mango puree, then caramel sauce, then whipped cream.",
      "Top with the remaining diced mangoes.",
      "Decorate with chopped pistachios and serve chilled."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "A rich mango dessert with layers of caramel sauce and cream - a real treat for mango lovers.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "nuts"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["mangoes", "sugar", "cream", "vanilla", "condensed milk", "whipped cream", "pistachios"],
    searchKeywords: ["mango caramel delight", "mango dessert", "caramel mango", "layered dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chocolate Delight",
    image: "Chocolate-Delight.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 1/2 cups chocolate cookies (crushed)",
      "1/2 cup butter (melted)",
      "1 cup semi-sweet chocolate chips",
      "1 cup heavy cream",
      "1/2 cup sugar",
      "1 teaspoon vanilla essence",
      "2 cups whipped cream",
      "Chocolate shavings for decoration"
    ],
    stepsRaw: [
      "Mix crushed cookies with melted butter until well combined.",
      "Press this mixture into the bottom of serving glasses to make a base.",
      "Put in the fridge for 15 minutes to set.",
      "Heat heavy cream in a pan until steaming hot but not boiling.",
      "Pour hot cream over chocolate chips and let it sit for 2 minutes.",
      "Whisk until smooth and shiny chocolate ganache forms.",
      "Add sugar and vanilla essence, stir until dissolved.",
      "Let the ganache cool to room temperature.",
      "Put a layer of whipped cream over the cookie base in glasses.",
      "Pour chocolate ganache over the whipped cream.",
      "Add another layer of whipped cream on top and decorate with chocolate shavings.",
      "Chill for at least 2 hours before serving."
    ],
    difficulty: "Medium",
    cookingTime: 150,
    isActive: true,
    isHalal: true,
    description: "A chocolate lover's dream - layers of cookie crust, chocolate ganache, and whipped cream.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "gluten", "wheat"],
    budget: "standard",
    costPerServing: 90,
    baseServings: 4,
    calories: 550,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["chocolate cookies", "butter", "chocolate chips", "cream", "sugar", "vanilla", "whipped cream", "chocolate"],
    searchKeywords: ["chocolate delight", "layered chocolate dessert", "chocolate mousse", "no bake dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Suji Cake",
    image: "Suji-cake.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup semolina (suji)",
      "1 cup sugar",
      "1 cup yogurt",
      "1/2 cup vegetable oil",
      "1/2 cup milk",
      "1 teaspoon baking powder",
      "1/2 teaspoon baking soda",
      "1 teaspoon cardamom powder",
      "1/4 cup chopped nuts (almonds, cashews)",
      "1 tablespoon ghee"
    ],
    stepsRaw: [
      "Turn on the oven at 350°F (175°C). Grease a cake pan with oil or butter.",
      "In a big bowl, mix semolina and yogurt together.",
      "Let the mixture sit for 20 minutes so the semolina becomes soft.",
      "Add sugar and mix well until the sugar dissolves completely.",
      "Pour in vegetable oil and milk, mix thoroughly.",
      "Add baking powder, baking soda, and cardamom powder.",
      "Mix until a smooth batter forms.",
      "Heat ghee in a small pan and fry nuts until they become golden brown.",
      "Add these fried nuts to the batter and mix.",
      "Pour the batter into the greased cake pan.",
      "Bake for 35-40 minutes. Insert a toothpick - if it comes out clean, it's ready.",
      "Let it cool completely before cutting into pieces."
    ],
    difficulty: "Easy",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A traditional semolina cake with cardamom and nuts - soft, moist, and great with tea.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "nuts", "gluten"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 6,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["semolina", "sugar", "yogurt", "oil", "milk", "baking powder", "baking soda", "cardamom", "nuts", "ghee"],
    searchKeywords: ["suji cake", "semolina cake", "pakistani cake", "cardamom cake", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Sweet Dumplings",
    image: "Sweet-Dumplings.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup plain flour (maida)",
      "2 tablespoons semolina (suji)",
      "2 tablespoons ghee",
      "1/4 cup milk (or as needed)",
      "A little bit of salt",
      "1 cup sugar",
      "1 cup water",
      "4-5 cardamom pods",
      "Oil for frying",
      "Chopped pistachios for decoration"
    ],
    stepsRaw: [
      "For syrup: Put sugar, water, and cardamom pods in a pan.",
      "Bring to a boil, then simmer for 10 minutes until it thickens a little bit.",
      "Turn off the heat and keep the syrup warm.",
      "For dough: Mix flour, semolina, ghee, and salt in a bowl.",
      "Slowly add milk and make a stiff dough.",
      "Cover the dough and let it rest for 15 minutes.",
      "Divide the dough into small equal pieces.",
      "Roll each piece into smooth round balls.",
      "Heat oil in a deep pan on medium heat.",
      "Fry the dumplings until they become golden brown and puffed up.",
      "Immediately put the hot dumplings into the warm syrup.",
      "Let them soak for 15-20 minutes, turning them now and then.",
      "Decorate with chopped pistachios and serve."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Crispy deep-fried dumplings soaked in sweet syrup - a classic Pakistani sweet.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "gluten", "wheat"],
    budget: "standard",
    costPerServing: 35,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "semolina", "ghee", "milk", "sugar", "water", "cardamom", "oil", "pistachios"],
    searchKeywords: ["sweet dumplings", "gulab jamun", "pakistani dessert", "fried dumplings", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cherry Delight",
    image: "Cherry-delight.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups fresh cherries (seeds removed)",
      "1 cup cherry juice",
      "1/2 cup sugar",
      "1 tablespoon cornflour",
      "2 tablespoons water",
      "1 cup whipped cream",
      "1 cup vanilla custard",
      "1/2 cup digestive biscuits (crushed)",
      "2 tablespoons butter (melted)"
    ],
    stepsRaw: [
      "Mix crushed biscuits with melted butter for the base.",
      "Press this mixture into the bottom of serving glasses.",
      "Put in the fridge for 15 minutes.",
      "In a pan, mix cherries, cherry juice, and sugar.",
      "Bring to a boil, then lower the heat and simmer for 10 minutes.",
      "Mix cornflour with water to make a smooth paste.",
      "Add this paste to the cherry mixture while stirring continuously.",
      "Cook for 2-3 minutes until the mixture thickens.",
      "Turn off the heat and let it cool completely.",
      "Put a layer of vanilla custard over the biscuit base.",
      "Add a layer of cherry compote on top.",
      "Finish with a layer of whipped cream.",
      "Decorate with fresh cherries and serve chilled."
    ],
    difficulty: "Easy",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A beautiful layered cherry dessert with creamy custard and a crunchy biscuit base.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "gluten", "wheat"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["cherries", "cherry juice", "sugar", "cornstarch", "whipped cream", "vanilla custard", "biscuits", "butter"],
    searchKeywords: ["cherry delight", "cherry dessert", "layered dessert", "custard dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Watermelon Pudding",
    image: "Watermelon-pudding.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "3 cups watermelon (seeds removed and chopped)",
      "1/2 cup sugar",
      "2 tablespoons agar-agar powder",
      "1/4 cup cold water",
      "1 cup milk",
      "1/4 cup condensed milk",
      "1 teaspoon vanilla essence",
      "Fresh mint leaves for decoration"
    ],
    stepsRaw: [
      "Blend the watermelon until it becomes smooth puree.",
      "Strain through a sieve to remove any pieces of pulp.",
      "In a small bowl, soak agar-agar in cold water for 10 minutes.",
      "Heat milk in a pan, add the soaked agar-agar.",
      "Cook on low heat, stirring until the agar-agar dissolves completely.",
      "Add sugar and condensed milk, stir until the sugar dissolves.",
      "Turn off the heat and add the watermelon puree.",
      "Add vanilla essence and mix well.",
      "Pour the mixture into serving bowls or a mold.",
      "Put in the fridge for 3-4 hours until it sets.",
      "Decorate with fresh mint leaves before serving.",
      "Serve chilled."
    ],
    difficulty: "Medium",
    cookingTime: 270,
    isActive: true,
    isHalal: true,
    description: "A refreshing watermelon pudding that is light, fruity, and perfect for hot summer days.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 4,
    calories: 180,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["watermelon", "sugar", "agar-agar", "milk", "condensed milk", "vanilla", "mint"],
    searchKeywords: ["watermelon pudding", "watermelon dessert", "agar agar dessert", "refreshing dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Custard Falooda",
    image: "Custard-Falooda.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups milk",
      "3 tablespoons custard powder",
      "1/4 cup sugar",
      "1/2 cup falooda seeds (sabja/tukmaria)",
      "1/2 cup cooked vermicelli (seviyan)",
      "1/2 cup mixed fruits (mango, banana, apple)",
      "2 scoops vanilla ice cream",
      "1/4 cup rose syrup",
      "Chopped nuts for decoration"
    ],
    stepsRaw: [
      "Soak falooda seeds in water for 30 minutes, then drain the water.",
      "Cook vermicelli according to the package instructions, then drain.",
      "Mix custard powder with 1/4 cup cold milk to make a smooth paste.",
      "Heat the remaining milk in a pan.",
      "When the milk is warm, add the custard paste while stirring continuously.",
      "Add sugar and cook on medium heat until the mixture thickens.",
      "Turn off the heat and let it cool completely.",
      "In tall glasses, add soaked falooda seeds as the first layer.",
      "Add a layer of cooked vermicelli.",
      "Pour the cooled custard over the vermicelli.",
      "Add mixed fruits as the next layer.",
      "Drizzle rose syrup over the fruits.",
      "Top with a scoop of vanilla ice cream.",
      "Decorate with chopped nuts and serve immediately."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A popular layered dessert with custard, falooda seeds, vermicelli, fruits, and ice cream.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "gluten", "nuts"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["milk", "custard powder", "sugar", "falooda seeds", "vermicelli", "mixed fruits", "ice cream", "rose syrup", "nuts"],
    searchKeywords: ["custard falooda", "falooda", "layered dessert", "ice cream dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Custard Ice Cream",
    image: "Custard-ice-cream.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups heavy cream",
      "1 cup full-fat milk",
      "3/4 cup sugar",
      "4 egg yolks",
      "1 tablespoon custard powder",
      "1 teaspoon vanilla essence",
      "A little bit of salt",
      "1/4 cup chopped nuts (optional)"
    ],
    stepsRaw: [
      "Mix custard powder with 2 tablespoons of milk to make a smooth paste.",
      "In a pan, heat milk and heavy cream until steaming.",
      "In a separate bowl, whisk egg yolks and sugar until the color becomes pale.",
      "Slowly pour the hot milk mixture into the egg yolks while whisking constantly.",
      "Put the mixture back in the pan, add the custard paste.",
      "Cook on low heat, stirring constantly until the mixture thickens.",
      "Strain through a fine sieve to remove any lumps.",
      "Add vanilla essence and salt, stir well.",
      "Let it cool completely, then put in the fridge for 4 hours.",
      "If you have an ice cream maker, churn according to instructions.",
      "If no ice cream maker, freeze the mixture and stir every 30 minutes.",
      "Add chopped nuts before the final freezing if you want.",
      "Freeze for at least 6 hours before serving."
    ],
    difficulty: "Hard",
    cookingTime: 600,
    isActive: true,
    isHalal: true,
    description: "A rich and creamy homemade custard ice cream that is smooth, velvety, and very tasty.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "eggs", "nuts"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 6,
    calories: 450,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["cream", "milk", "sugar", "egg yolks", "custard powder", "vanilla", "salt", "nuts"],
    searchKeywords: ["custard ice cream", "homemade ice cream", "creamy ice cream", "frozen dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Bread Malai Pudding",
    image: "Bread-Malai-Pudding.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "6 slices white bread (crusts removed)",
      "2 cups milk",
      "1/2 cup sugar",
      "1/2 cup condensed milk",
      "1/4 cup cream",
      "1 teaspoon cardamom powder",
      "1/4 cup chopped nuts (almonds, pistachios)",
      "2 tablespoons ghee",
      "Saffron strands for decoration"
    ],
    stepsRaw: [
      "Cut the bread slices into small pieces or triangles.",
      "Heat ghee in a pan and lightly toast the bread pieces until golden.",
      "In a pan, heat the milk until it comes to a boil.",
      "Lower the heat, add sugar and condensed milk.",
      "Cook for 10 minutes, stirring now and then.",
      "Add the toasted bread pieces to the milk mixture.",
      "Cook on low heat until the bread absorbs the milk and becomes soft.",
      "Add cream and cardamom powder, mix well.",
      "Turn off the heat and let it cool a little bit.",
      "Put it in a serving dish and press gently to level it.",
      "Decorate with chopped nuts and saffron strands.",
      "Put in the fridge for at least 2 hours.",
      "Serve cold."
    ],
    difficulty: "Easy",
    cookingTime: 150,
    isActive: true,
    isHalal: true,
    description: "A creamy bread pudding with cardamom flavor and nuts on top - a comforting dessert.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "gluten", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["bread", "milk", "sugar", "condensed milk", "cream", "cardamom", "nuts", "ghee", "saffron"],
    searchKeywords: ["bread malai pudding", "bread pudding", "malai pudding", "pakistani dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Custard Panna Cotta",
    image: "Custard-Panna-Cotta.jpg",
    cuisine: "Italian",
    ingredientsRaw: [
      "2 cups heavy cream",
      "1/2 cup sugar",
      "2 teaspoons gelatin powder",
      "1/4 cup cold water",
      "1 teaspoon vanilla essence",
      "1 cup mixed berry compote",
      "Fresh mint leaves for decoration"
    ],
    stepsRaw: [
      "Soak gelatin in cold water for 5 minutes to soften it.",
      "Heat heavy cream and sugar in a pan until steaming.",
      "Turn off the heat, add the softened gelatin, and stir until it dissolves.",
      "Add vanilla essence and mix well.",
      "Strain the mixture through a fine sieve.",
      "Pour into serving glasses or molds.",
      "Put in the fridge for at least 4 hours until it sets.",
      "To serve, run a knife around the edges to loosen.",
      "If needed, dip the mold in warm water for a few seconds.",
      "Turn it upside down onto a serving plate.",
      "Top with mixed berry compote.",
      "Decorate with fresh mint leaves.",
      "Serve chilled."
    ],
    difficulty: "Medium",
    cookingTime: 270,
    isActive: true,
    isHalal: true,
    description: "A creamy Italian-style dessert that is silky smooth and goes perfectly with berry compote.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["cream", "sugar", "gelatin", "water", "vanilla", "berry compote", "mint"],
    searchKeywords: ["custard panna cotta", "panna cotta", "italian dessert", "creamy dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Qissa Khawani Kheer",
    image: "Qissa-Khawani-Kheer.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1/2 cup basmati rice",
      "1 liter full-fat milk",
      "1/2 cup sugar",
      "1/4 cup condensed milk",
      "1 teaspoon cardamom powder",
      "1/4 cup mixed nuts (almonds, pistachios, cashews)",
      "1 tablespoon ghee",
      "Saffron strands soaked in 2 tablespoons milk",
      "Rose water for flavor (optional)"
    ],
    stepsRaw: [
      "Wash the rice and soak in water for 30 minutes.",
      "Heat ghee in a heavy-bottomed pan, fry the nuts until golden, and set aside.",
      "Drain the rice and add to the same pan, lightly roast for 2 minutes.",
      "Add milk and bring to a boil, stirring now and then.",
      "Lower the heat and simmer until the rice is completely cooked.",
      "Stir frequently so it doesn't stick to the bottom.",
      "When the rice is soft and the milk has reduced by half, add sugar.",
      "Add condensed milk and cardamom powder.",
      "Cook for another 10 minutes until it reaches the consistency you like.",
      "Add the saffron milk and fried nuts (save some for decoration).",
      "Add rose water if using, and mix well.",
      "Turn off the heat and let it cool to room temperature.",
      "Decorate with the remaining nuts and serve warm or chilled."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A traditional rich rice pudding with cardamom, saffron, and nuts - a royal Pakistani dessert.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "nuts"],
    budget: "standard",
    costPerServing: 55,
    baseServings: 4,
    calories: 350,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["rice", "milk", "sugar", "condensed milk", "cardamom", "nuts", "ghee", "saffron", "rose water"],
    searchKeywords: ["kheer", "rice pudding", "qissa khawani kheer", "pakistani dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Walnut Halwa",
    image: "Walnut-Halwa.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups walnuts (finely ground)",
      "1 cup sugar",
      "1 cup water",
      "1/2 cup ghee",
      "1/2 cup milk",
      "1/4 cup khoya (milk solids, grated)",
      "1 teaspoon cardamom powder",
      "Saffron strands soaked in 2 tablespoons milk",
      "Silver leaf (varq) for decoration"
    ],
    stepsRaw: [
      "Soak the ground walnuts in milk for 30 minutes.",
      "Make sugar syrup: Put sugar and water in a pan.",
      "Cook until a one-string consistency syrup forms.",
      "Heat ghee in a heavy-bottomed pan on medium heat.",
      "Add the soaked walnuts (with milk) to the ghee.",
      "Cook while stirring continuously until the mixture thickens.",
      "Slowly add the sugar syrup while stirring.",
      "Cook until the halwa starts leaving the sides of the pan.",
      "Add grated khoya and cardamom powder.",
      "Keep cooking until the ghee separates from the mixture.",
      "Add saffron milk and mix well.",
      "Turn off the heat and put it in a serving dish.",
      "Decorate with silver leaf and serve warm."
    ],
    difficulty: "Hard",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A rich and nutty walnut halwa that is indulgent, fragrant, and perfect for special occasions.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "nuts"],
    budget: "premium",
    costPerServing: 100,
    baseServings: 4,
    calories: 550,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["walnuts", "sugar", "water", "ghee", "milk", "khoya", "cardamom", "saffron"],
    searchKeywords: ["walnut halwa", "akhrot halwa", "nutty halwa", "pakistani halwa", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cinnamon Rolls",
    image: "Cinnamon-Roll.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "For dough: 3 cups plain flour (maida)",
      "1/4 cup sugar",
      "1 teaspoon salt",
      "2 1/4 teaspoons instant yeast",
      "3/4 cup warm milk",
      "1/4 cup melted butter",
      "1 egg",
      "For filling: 1/2 cup brown sugar",
      "2 tablespoons cinnamon powder",
      "1/4 cup softened butter",
      "For icing: 1 cup powdered sugar",
      "2 tablespoons milk",
      "1/2 teaspoon vanilla essence"
    ],
    stepsRaw: [
      "Mix warm milk, sugar, and yeast. Let it sit for 5 minutes until it becomes foamy.",
      "In a big bowl, mix flour and salt.",
      "Add the yeast mixture, melted butter, and egg to the flour.",
      "Knead until a smooth and elastic dough forms (about 8-10 minutes).",
      "Put the dough in a greased bowl, cover it, and let it rise for 1 hour.",
      "Press the dough down, then roll it into a 12x18 inch rectangle.",
      "Spread softened butter evenly over the dough.",
      "Mix brown sugar and cinnamon, then sprinkle it over the butter.",
      "Roll the dough tightly from the long edge into a log.",
      "Cut into 12 equal pieces using dental floss or a sharp knife.",
      "Place the rolls in a greased baking pan, cover, and let rise for 30 minutes.",
      "Turn on the oven at 350°F (175°C).",
      "Bake for 20-25 minutes until they become golden brown.",
      "Mix the icing ingredients until smooth, then drizzle over the warm rolls.",
      "Serve warm."
    ],
    difficulty: "Hard",
    cookingTime: 150,
    isActive: true,
    isHalal: true,
    description: "Soft, sweet cinnamon rolls with a gooey filling and creamy icing - pure bliss.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "eggs", "gluten", "wheat"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 12,
    calories: 320,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "sugar", "salt", "yeast", "milk", "butter", "egg", "brown sugar", "cinnamon", "powdered sugar", "vanilla"],
    searchKeywords: ["cinnamon rolls", "cinnamon buns", "sweet rolls", "baked dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Bread Gulab Jamun",
    image: "Bread-gulab-jamun.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "6 slices white bread (crusts removed)",
      "1/4 cup milk powder",
      "2 tablespoons plain flour (maida)",
      "1/4 teaspoon baking powder",
      "2 tablespoons yogurt",
      "1/4 cup milk (as needed)",
      "Oil for frying",
      "For syrup: 1 1/2 cups sugar",
      "1 1/2 cups water",
      "4-5 cardamom pods",
      "1 teaspoon rose water",
      "Chopped pistachios for decoration"
    ],
    stepsRaw: [
      "Make syrup: Put sugar, water, and cardamom in a pan.",
      "Boil for 10 minutes until it thickens a little, then add rose water.",
      "Keep the syrup warm.",
      "Tear the bread into small pieces and soak in milk for 5 minutes.",
      "Squeeze out the extra milk from the bread.",
      "Add milk powder, flour, baking powder, and yogurt.",
      "Knead into a soft dough, adding more milk if needed.",
      "Divide the dough into small equal pieces.",
      "Roll each piece into smooth balls without any cracks.",
      "Heat oil on medium heat (not too hot).",
      "Fry the balls until they become golden brown, turning them frequently.",
      "Immediately put the hot gulab jamuns into the warm syrup.",
      "Let them soak for at least 1 hour, turning them now and then.",
      "Decorate with chopped pistachios and serve warm or cold."
    ],
    difficulty: "Medium",
    cookingTime: 90,
    isActive: true,
    isHalal: true,
    description: "A quick bread version of the classic gulab jamun - soft, sweet, and soaked in fragrant syrup.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 6,
    calories: 280,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["bread", "milk powder", "flour", "baking powder", "yogurt", "milk", "oil", "sugar", "water", "cardamom", "rose water", "pistachios"],
    searchKeywords: ["bread gulab jamun", "quick gulab jamun", "instant gulab jamun", "pakistani sweet", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Creamy Mango Delight",
    image: "Creamy-Mango-Delight.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 big ripe mangoes (pureed)",
      "1 cup whipped cream",
      "1/2 cup condensed milk",
      "1/2 cup mango pieces (for layering)",
      "1/2 cup digestive biscuits (crushed)",
      "2 tablespoons butter (melted)",
      "1 teaspoon vanilla essence",
      "1/4 cup chopped nuts for decoration"
    ],
    stepsRaw: [
      "Mix crushed biscuits with melted butter for the base.",
      "Press this mixture into the bottom of serving glasses.",
      "Put in the fridge for 15 minutes.",
      "In a big bowl, mix mango puree and condensed milk.",
      "Add vanilla essence and mix well.",
      "Gently fold in whipped cream until everything is just combined.",
      "Put a layer of mango cream mixture over the biscuit base.",
      "Add a layer of fresh mango pieces.",
      "Repeat the layers until the glass is full.",
      "Top with the remaining whipped cream.",
      "Decorate with chopped nuts and mango pieces.",
      "Put in the fridge for at least 2 hours before serving.",
      "Serve cold."
    ],
    difficulty: "Easy",
    cookingTime: 135,
    isActive: true,
    isHalal: true,
    description: "A no-bake creamy mango dessert with a biscuit crust and fresh mango pieces - pure summer bliss.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "gluten", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["mangoes", "whipped cream", "condensed milk", "biscuits", "butter", "vanilla", "nuts"],
    searchKeywords: ["creamy mango delight", "mango dessert", "no bake dessert", "summer dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Kunafa Dates",
    image: "kunafa-dates.jpg",
    cuisine: "Turkish",
    ingredientsRaw: [
      "250g kunafa dough (kataifi), thawed",
      "1 cup pitted dates (chopped)",
      "1/2 cup walnuts (chopped)",
      "1 teaspoon cinnamon powder",
      "1/2 cup ghee (melted)",
      "For syrup: 1 cup sugar",
      "1/2 cup water",
      "1 tablespoon lemon juice",
      "1 teaspoon orange blossom water",
      "1/4 cup pistachios (crushed for decoration)"
    ],
    stepsRaw: [
      "Make syrup: Put sugar, water, and lemon juice in a pan.",
      "Boil for 10 minutes until it thickens a little.",
      "Turn off the heat and add orange blossom water.",
      "Let the syrup cool completely.",
      "Turn on the oven at 350°F (175°C).",
      "Separate the kunafa threads with your fingers.",
      "Mix dates, walnuts, and cinnamon for the filling.",
      "Brush a baking dish with melted ghee.",
      "Spread half of the kunafa dough in the dish, pressing it down.",
      "Spread the date-walnut filling evenly on top.",
      "Cover with the remaining kunafa dough and press down gently.",
      "Pour the remaining melted ghee evenly over the top.",
      "Bake for 30-35 minutes until it becomes golden brown.",
      "Pour the cold syrup over the hot kunafa.",
      "Decorate with crushed pistachios and let it rest for 10 minutes.",
      "Serve warm."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A Middle Eastern kunafa pastry filled with dates and walnuts, soaked in orange blossom syrup.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "gluten", "wheat", "nuts"],
    budget: "premium",
    costPerServing: 120,
    baseServings: 6,
    calories: 480,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["kunafa dough", "dates", "walnuts", "cinnamon", "ghee", "sugar", "water", "lemon", "orange blossom water", "pistachios"],
    searchKeywords: ["kunafa dates", "kunafa with dates", "middle eastern dessert", "arabic dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Kunafa Chocolate",
    image: "kunafa-chocolate.jpg",
    cuisine: "Arabic",
    ingredientsRaw: [
      "250g kunafa dough (kataifi), thawed",
      "200g dark chocolate (chopped)",
      "1/2 cup heavy cream",
      "1/2 cup ghee (melted)",
      "1/4 cup sugar",
      "1 teaspoon vanilla essence",
      "For chocolate sauce: 1/2 cup chocolate chips",
      "1/4 cup cream",
      "Chopped almonds for decoration"
    ],
    stepsRaw: [
      "Make chocolate ganache: Heat cream until it is steaming.",
      "Pour it over the chopped chocolate and let it sit for 2 minutes.",
      "Whisk until smooth, then add vanilla essence.",
      "Turn on the oven at 350°F (175°C).",
      "Separate the kunafa threads with your fingers.",
      "Brush a baking dish with melted ghee.",
      "Mix kunafa with sugar and the remaining ghee.",
      "Press half of the kunafa mixture into the baking dish.",
      "Spread the chocolate ganache evenly over the kunafa.",
      "Cover with the remaining kunafa mixture and press gently.",
      "Bake for 30-35 minutes until it becomes golden and crisp.",
      "Make chocolate sauce: Heat cream and pour it over chocolate chips.",
      "Stir until a smooth sauce forms.",
      "Drizzle chocolate sauce over the baked kunafa.",
      "Decorate with chopped almonds.",
      "Let it cool a little before serving."
    ],
    difficulty: "Hard",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A crispy kunafa pastry filled with rich chocolate ganache and topped with chocolate sauce.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "gluten", "wheat", "nuts"],
    budget: "premium",
    costPerServing: 130,
    baseServings: 6,
    calories: 520,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["kunafa dough", "dark chocolate", "cream", "ghee", "sugar", "vanilla", "chocolate chips", "almonds"],
    searchKeywords: ["kunafa chocolate", "chocolate kunafa", "middle eastern dessert", "arabic dessert", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chocolate Strawberry Crepes",
    image: "Chocolate-Strawberry-Crepes.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "For crepes: 1 cup plain flour (maida)",
      "2 eggs",
      "1 1/4 cups milk",
      "2 tablespoons melted butter",
      "2 tablespoons sugar",
      "A little bit of salt",
      "For filling: 1 cup sliced strawberries",
      "1/2 cup chocolate hazelnut spread",
      "1 cup whipped cream",
      "For chocolate sauce: 1/2 cup chocolate chips",
      "1/4 cup cream",
      "Powdered sugar for dusting"
    ],
    stepsRaw: [
      "Make crepe batter: Whisk eggs, milk, and melted butter together.",
      "Add flour, sugar, and salt, and whisk until smooth.",
      "Let the batter rest for 30 minutes.",
      "Heat a non-stick pan over medium heat.",
      "Pour 1/4 cup of batter and swirl to coat the pan thinly.",
      "Cook for 1-2 minutes until the edges start to lift.",
      "Flip and cook for 30 seconds more.",
      "Repeat with the remaining batter.",
      "Make chocolate sauce: Heat cream and pour it over chocolate chips.",
      "Stir until a smooth sauce forms.",
      "Spread chocolate hazelnut spread on each crepe.",
      "Add sliced strawberries and whipped cream.",
      "Fold the crepes into triangles or roll them up.",
      "Drizzle with chocolate sauce.",
      "Dust with powdered sugar before serving.",
      "Serve immediately."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Thin, delicate crepes filled with chocolate hazelnut spread, fresh strawberries, and cream.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "eggs", "gluten", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["flour", "eggs", "milk", "butter", "sugar", "salt", "strawberries", "chocolate spread", "whipped cream", "chocolate chips", "cream", "powdered sugar"],
    searchKeywords: ["chocolate strawberry crepes", "crepes", "french dessert", "strawberry crepes", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Sweet Milk Balls",
    image: "sweet-milk-balls.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 liter full-fat milk",
      "1/2 cup sugar",
      "1/4 cup milk powder",
      "1 tablespoon ghee",
      "1/2 teaspoon cardamom powder",
      "1/4 cup chopped nuts (pistachios, almonds)",
      "Oil for frying",
      "For coating: 1/4 cup powdered sugar",
      "1 teaspoon cinnamon powder"
    ],
    stepsRaw: [
      "Boil the milk in a heavy-bottomed pan.",
      "Lower the heat and simmer until the milk reduces to half.",
      "Add sugar and milk powder, stirring continuously.",
      "Cook until the mixture thickens and starts leaving the sides of the pan.",
      "Add ghee and cardamom powder, mix well.",
      "Turn off the heat and let it cool a little.",
      "Add the chopped nuts to the mixture.",
      "When it is cool enough to handle, shape it into small balls.",
      "Heat oil in a deep pan on medium heat.",
      "Fry the balls until they become golden brown, turning them gently.",
      "Drain on paper towels.",
      "Mix powdered sugar and cinnamon for the coating.",
      "Roll the warm balls in the cinnamon-sugar mixture.",
      "Let them cool completely before serving.",
      "Store in an airtight container."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Fried milk balls coated in spiced cinnamon sugar - a unique and tasty Pakistani sweet.",
    category: "Dessert",
    subCategory: "desserts",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["dairy", "nuts"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 6,
    calories: 280,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["milk", "sugar", "milk powder", "ghee", "cardamom", "nuts", "oil", "powdered sugar", "cinnamon"],
    searchKeywords: ["sweet milk balls", "milk dessert", "pakistani sweet", "fried milk balls", "dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
]

async function migrateRecipes() {
  try {
    console.log('Connecting to MongoDB');
    
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) {
      throw new Error('MongoDB URI not found');
    }
    
    await mongoose.connect(mongoURI, { 
      serverSelectionTimeoutMS: 10000, 
      family: 4 
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();