const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');
const BeginnersGuide = require('../models/BeginnersGuide');
const User = require('../models/User');

dotenv.config({ path: path.join(__dirname, '../.env') });

const allGuides = [];
const addGuide = (item, mainCategory, subCategory, filterTags = []) => {
  if (!item || !item.name) return;
  allGuides.push({
    title: item.name,
    category: mainCategory,
    subCategory: subCategory,
    filterTags: filterTags,
    image: item.image || '',
    content: JSON.stringify({
      id: item.id,
      name: item.name,
      tagline: item.tagline || '',
      fullDesc: item.fullDesc || '',
      keyUses: item.keyUses || [],
      bestFor: item.bestFor || '',
      type: item.type || subCategory,
      material: item.material || '',
      size: item.size || '',
      price: item.price || '',
      priceRange: item.priceRange || '',
      durability: item.durability || '',
      pros: item.pros || [],
      cons: item.cons || [],
      care: item.care || '',
      bladeType: item.bladeType || '',
      utensilType: item.utensilType || '',
      cookwareType: item.cookwareType || '',
      crockeryType: item.crockeryType || '',
      cutleryType: item.cutleryType || '',
      servingType: item.servingType || '',
      capacity: item.capacity || '',
      materialType: item.materialType || ''
    })
  });
};
const knivesData = [
  {
    id: 1,
    name: "Chef's Knife",
    image: "Chefs.png",
    size: "8-10 inches",
    bestFor: "All-purpose chopping, slicing, dicing",
    material: "High-carbon stainless steel",
    price: "Rs.700 to Rs.4,500",
    priceRange: "Mid to Premium",
    fullDesc: "The most versatile knife in the kitchen. The curved blade allows a rocking motion for fast chopping. Perfect for chopping vegetables, slicing meats, and mincing herbs. A quality chef's knife is the only knife many cooks need.",
    keyUses: ["Chopping vegetables", "Slicing meats", "Mincing herbs", "Dicing onions", "Crushing garlic"],
    care: "Hand wash only, dry immediately, sharpen regularly",
    durability: "Lifetime with proper care",
    pros: ["Versatile (handles most tasks)", "Precise cutting control", "Comfortable grip", "Good weight balance"],
    cons: ["Requires sharpening", "Heavy for some users", "Can be intimidating", "Expensive for quality"],
    type: "knife",
    bladeType: "chef"
  },
  {
    id: 2,
    name: "Paring Knife",
    image: "Paring.png",
    size: "3-4 inches",
    bestFor: "Peeling, precision work, small tasks",
    material: "Stainless steel",
    price: "Rs.200 to Rs.4,000",
    priceRange: "Budget to Mid",
    fullDesc: "A small knife ideal for peeling fruits, deveining shrimp, removing seeds, and detailed cutting work. The short blade gives you precise control for intricate tasks where a larger knife would be awkward. Often used in hand, not on a cutting board.",
    keyUses: ["Peeling fruits and vegetables", "Deveining shrimp", "Removing seeds", "Detailed cutting", "Trimming small items"],
    care: "Hand wash recommended",
    durability: "5-10 years",
    pros: ["Precise control", "Easy to handle", "Lightweight", "Inexpensive"],
    cons: ["Limited to small tasks", "Small blade limits use", "Can be hard to sharpen", "Not for heavy cutting"],
    type: "knife",
    bladeType: "paring"
  },
  {
    id: 3,
    name: "Bread Knife",
    image: "Bread.png",
    size: "8-10 inches",
    bestFor: "Slicing crusty bread, cakes, tomatoes",
    material: "Stainless steel with serrated edge",
    price: "Rs.350 to Rs.1,5000",
    priceRange: "Budget to Mid",
    fullDesc: "The serrated edge of a bread knife easily cuts through crusty bread without crushing the soft interior. The sawing motion works well for any food with a hard exterior and soft interior, including tomatoes and cakes. Unlike straight-edge knives, serrated knives stay sharp for years.",
    keyUses: ["Slicing crusty bread", "Cutting cakes and pastries", "Slicing tomatoes", "Cutting bagels", "Slicing citrus fruits"],
    care: "Hand wash only, serrated edge is difficult to sharpen",
    durability: "5-10 years (serrated edge stays sharp longer)",
    pros: ["Serrated edge cuts without crushing", "Long blade for large items", "Stays sharp for years", "Great for bread and pastries"],
    cons: ["Difficult to sharpen at home", "Not for precise cuts", "Specific use case", "Can tear soft bread if technique wrong"],
    type: "knife",
    bladeType: "serrated"
  },
  {
    id: 4,
    name: "Santoku Knife",
    image: "Santoku.png",
    size: "5-7 inches",
    bestFor: "Japanese-style slicing, chopping",
    material: "Japanese steel (VG-10, Shun, etc.)",
    price: "Rs.350 to Rs.3,500",
    priceRange: "Mid to Premium",
    fullDesc: "A Japanese style all-purpose knife meaning 'three virtues' used for slicing, dicing, and mincing. The straighter edge and sheepsfoot blade tip allow for precise cutting. Granton edges (dimples) prevent food from sticking to the blade. Typically lighter than Western chef's knives.",
    keyUses: ["Slicing vegetables", "Cutting meat", "Chopping herbs", "Precision cuts", "Push cutting"],
    care: "Hand wash, regular honing on ceramic rod",
    durability: "Lifetime with proper care",
    pros: ["Granton edges prevent sticking", "Lightweight", "Precise cuts", "Sheepsfoot tip safe for cutting boards"],
    cons: ["Expensive", "Requires careful maintenance", "Not for heavy-duty tasks", "Can chip if used on bones"],
    type: "knife",
    bladeType: "santoku"
  },
  {
    id: 5,
    name: "Boning Knife",
    image: "Boning.png",
    size: "5-7 inches",
    bestFor: "Removing bones from meat, filleting fish",
    material: "Flexible stainless steel",
    price: "Rs.400 to Rs.7,000",
    priceRange: "Budget to Mid",
    fullDesc: "A thin, flexible blade perfect for deboning chicken, filleting fish, and trimming meats. The narrow blade can maneuver around bones and joints. Flexibility varies by brand and stiffer for beef, more flexible for fish.",
    keyUses: ["Deboning chicken", "Filleting fish", "Trimming meat", "Removing silver skin", "Butchery tasks"],
    care: "Hand wash, keep sharp, store safely",
    durability: "5-10 years",
    pros: ["Flexible blade  around bones", "Precise deboning control", "Thin profile for tight spaces", "Essential for meat preparation"],
    cons: ["Fragile tip can break", "Specialized use only", "Not for everyday cutting", "Requires sharpening skill"],
    type: "knife",
    bladeType: "boning"
  },
  {
    id: 6,
    name: "Utility Knife",
    image: "Utility.png",
    size: "4-6 inches",
    bestFor: "Mid-sized cutting tasks",
    material: "Stainless steel",
    price: "Rs.350 to Rs.1500",
    priceRange: "Budget",
    bestFor: "Small to medium cutting tasks between chef's and paring knives",
    fullDesc: "A mid sized knife that fills the gap between a chef's knife and a paring knife. Useful for cutting sandwiches, small vegetables, and fruits where a chef's knife feels too large but a paring knife is too small. A good extra knife for tasks that don not require a specialized blade.",
    keyUses: ["Cutting sandwiches", "Slicing small vegetables", "Cutting fruit", "Everyday small tasks", "When chef's knife is too large"],
    care: "Hand wash recommended",
    durability: "5-10 years",
    pros: ["Versatile mid sized", "Easy to handle", "Lightweight", "Inexpensive"],
    cons: ["Not specialized for any task", "Average performance", "Often overlooked", "Not as sharp as premium knives"],
    type: "knife",
    bladeType: "utility"
  },
  {
    id: 7,
    name: "Nakiri Knife",
    image: "Nakiri.png",
    size: "6-7 inches",
    bestFor: "Vegetable chopping",
    material: "Japanese carbon steel",
    price: "Rs.2,000 to Rs.6,000",
    priceRange: "Premium",
    bestFor: "Vegetable preparation, especially chopping and slicing",
    fullDesc: "A traditional Japanese vegetable knife with a straight blade edge and sheepsfoot tip. The straight edge allows you to chop through vegetables with a straight up-and-down motion rather than a rocking motion. Excellent for thin, precise vegetable cuts.",
    keyUses: ["Chopping vegetables", "Slicing vegetables thinly", "Vegetable preparation", "Precision vegetable cuts", "Making coleslaw"],
    care: "Hand wash, dry immediately to prevent rust (carbon steel)",
    durability: "Lifetime with proper care",
    pros: ["Straight edge for precise chopping", "Perfect for vegetables", "Excellent for thin slices", "Sheepsfoot tip safe"],
    cons: ["Not for meat or bones", "Requires careful maintenance (carbon steel)", "Expensive", "Specialized for vegetables only"],
    type: "knife",
    bladeType: "nakiri"
  }
];

const cuttingBoardTypes = [
  {
    id: 1,
    name: "Bamboo Cutting Board",
    image: "BambooBoard.png",
    pros: ["Eco-friendly and sustainable", "Lightweight", "Naturally antibacterial", "Affordable"],
    cons: ["Can dull knives faster than wood", "Absorbs moisture", "May crack over time", "Requires regular oiling"],
    bestFor: "General vegetable chopping, fruits, bread",
    care: "Hand wash, oil monthly with mineral oil",
    price: "$20-$50",
    priceRange: "Budget",
    fullDesc: "Made from fast-growing bamboo, these boards are an eco-friendly alternative to traditional wood. Bamboo is harder than many woods, which makes it durable but can be harder on knife edges. Naturally antibacterial and lightweight.",
    durability: "3-5 years",
    type: "cutting-board",
    material: "Bamboo",
    size: "Various from 8x10 to 12x18 inches"
  },
  {
    id: 2,
    name: "Maple Wood Cutting Board",
    image: "MappleBoard.png",
    pros: ["Durable and long-lasting", "Gentle on knife edges", "Natural antibacterial properties", "Beautiful appearance"],
    cons: ["Heavier than bamboo", "More expensive", "Requires regular oiling", "Can stain"],
    bestFor: "All-purpose cutting, meat preparation, cheese boards",
    care: "Hand wash, oil regularly with food-grade mineral oil",
    price: "$50-$150",
    priceRange: "Mid to Premium",
    fullDesc: "Hard maple is the gold standard for cutting boards. It's hard enough to be durable but soft enough to be gentle on knife edges. The closed grain resists moisture and bacteria. With proper care, a maple board can last for decades.",
    durability: "10+ years (lifetime with care)",
    type: "cutting-board",
    material: "Hardwood Maple",
    size: "Various from 12x12 to 18x24 inches"
  },
  {
    id: 3,
    name: "Plastic Cutting Board",
    image: "PlasticBoard.png",
    pros: ["Dishwasher safe", "Lightweight and affordable", "Variety of colors", "Non-porous"],
    cons: ["Can harbor bacteria in knife grooves", "Not eco-friendly", "Scratches easily", "Shorter lifespan"],
    bestFor: "Raw meat, fish (use color-coded boards)",
    care: "Dishwasher safe, replace when deeply grooved",
    price: "$10-$30",
    priceRange: "Budget",
    fullDesc: "Affordable and dishwasher-safe, plastic boards are convenient for raw meat and fish. Use different colors for different food types to prevent cross-contamination. Replace when the surface becomes deeply grooved from knife cuts.",
    durability: "1-2 years (replace when grooved)",
    type: "cutting-board",
    material: "Polyethylene Plastic",
    size: "Various from 8x10 to 15x20 inches"
  },
  {
    id: 4,
    name: "Rubber Cutting Board",
    image: "RubberBoard.png",
    pros: ["Self-healing surface", "Gentle on knives (softest option)", "Non-slip base", "Sanitary and non-porous"],
    cons: ["Heavy", "Can stain (especially from beets, turmeric)", "Expensive", "Limited availability"],
    bestFor: "Professional kitchens, heavy daily use",
    care: "Hand wash, sanitize regularly",
    price: "$40-$100",
    priceRange: "Premium",
    fullDesc: "Professional-grade cutting boards made from rubber. The surface is self-healing, meaning knife cuts close up rather than creating grooves. Extremely gentle on knife edges. Non-slip base keeps board stable. Used in many professional kitchens.",
    durability: "5-7 years",
    type: "cutting-board",
    material: "Rubber",
    size: "Various from 10x14 to 15x20 inches"
  }
];

const mixingBowlTypes = [
  {
    id: 1,
    name: "Stainless Steel Mixing Bowls",
    image: "SteelBowl.png",
    pros: ["Durable and virtually indestructible", "Non-reactive for all foods", "Dishwasher safe", "Lightweight", "Nested for storage"],
    cons: ["Can be noisy when mixing", "Can dent if dropped", "Not microwave safe", "Can be slippery"],
    bestFor: "Mixing, marinating, storing, baking prep",
    sizes: "1, 1.5, 2.5, 3, 5 quart set",
    care: "Dishwasher safe",
    price: "$30-$80",
    priceRange: "Mid",
    fullDesc: "Virtually indestructible, non-reactive, and won't absorb stains or odors. Stainless steel bowls are the workhorses of any kitchen. They're lightweight, nest for compact storage, and don't break when dropped. Perfect for everything from mixing batter to marinating meat.",
    durability: "Lifetime",
    type: "mixing-bowl",
    material: "Stainless Steel (18/8 or 18/10)",
    capacity: "1 to 5 quarts"
  },
  {
    id: 2,
    name: "Glass Mixing Bowls",
    image: "GlassBowl.png",
    pros: ["Heat-resistant (oven and microwave safe)", "See-through to monitor contents", "Non-porous won't stain", "Easy to clean"],
    cons: ["Can break if dropped", "Heavier than stainless steel", "More expensive than plastic", "Nesting limited"],
    bestFor: "Baking, microwave use, serving, melting butter/chocolate",
    sizes: "0.5, 1.5, 2.5, 4 quart set",
    care: "Dishwasher safe",
    price: "$25-$60",
    priceRange: "Budget to Mid",
    fullDesc: "Perfect for microwave use and serving. Glass bowls let you see what's inside, which is helpful for melting chocolate or checking dough consistency. Non-porous surface won't stain from tomato sauce or curry. Can go from microwave to table.",
    durability: "5-10 years (breakable)",
    type: "mixing-bowl",
    material: "Tempered Glass (Pyrex, Anchor Hocking)",
    capacity: "0.5 to 4 quarts"
  },
  {
    id: 3,
    name: "Ceramic Mixing Bowls",
    image: "CeramicBowl.png",
    pros: ["Oven-safe", "Stylish enough for serving", "Non-reactive", "Good heat retention"],
    cons: ["Can chip or crack", "Heavier than other options", "More expensive", "Can be slippery when wet"],
    bestFor: "Serving, baking, mixing, table presentation",
    sizes: "Various sizes, often sold as nesting sets",
    care: "Hand wash recommended for hand-painted pieces",
    price: "$40-$100",
    priceRange: "Mid to Premium",
    fullDesc: "Beautiful enough for serving and functional for baking. Ceramic bowls retain heat well, keeping food warm longer. Excellent heat distribution for oven use. Many are microwave and dishwasher safe, but hand-painted pieces need gentle care.",
    durability: "10+ years with care",
    type: "mixing-bowl",
    material: "Stoneware or Porcelain Ceramic",
    capacity: "Various from 0.5 to 4 quarts"
  },
  {
    id: 4,
    name: "Plastic Mixing Bowls",
    image: "PlasticBowl.png",
    pros: ["Lightweight", "Unbreakable", "Affordable", "Bright color options"],
    cons: ["Can stain (tomato sauce, turmeric)", "Not heat resistant", "Can absorb odors", "Shorter lifespan"],
    bestFor: "Everyday mixing, kids helping, outdoor cooking",
    sizes: "Set of 3-5 from small to large",
    care: "Dishwasher safe (top rack recommended)",
    price: "$15-$40",
    priceRange: "Budget",
    fullDesc: "Lightweight and unbreakable, plastic bowls are great for everyday use, especially when kids are helping in the kitchen. They're affordable and come in fun colors. However, they can stain and absorb odors over time and aren't suitable for hot contents.",
    durability: "2-3 years",
    type: "mixing-bowl",
    material: "Polypropylene or Melamine",
    capacity: "0.5 to 5 quarts"
  }
];

const cookwareTypes = [
  {
    id: 1,
    name: "Pressure Cooker",
    image: "PressureCooker.png",
    pros: ["Cooks food 70% faster", "Energy efficient", "Retains more nutrients", "Tenderizes tough meats"],
    cons: ["Safety concerns if misused", "Learning curve for timing", "Bulky storage", "Can't check food mid-cooking"],
    bestFor: "Rice, lentils, beans, tough meats, stews, stocks",
    material: "Stainless steel or Aluminum",
    capacity: "3, 5, 6, 8, 10 liters",
    care: "Hand wash, check gasket regularly, clean valve",
    price: "$40-$150",
    priceRange: "Mid to Premium",
    fullDesc: "A pressure cooker cooks food up to 70% faster than conventional methods by trapping steam and raising the internal temperature. Perfect for beans, tough meats, and stocks. Modern pressure cookers have multiple safety features, making them much safer than old models.",
    durability: "10+ years (replace gasket every 1-2 years)",
    type: "cookware",
    cookwareType: "pressure-cooker"
  },
  {
    id: 2,
    name: "Tawa/Griddle",
    image: "Tawa.png",
    pros: ["Even heat distribution", "Large flat surface", "Versatile for flatbreads and pancakes", "No moving parts"],
    cons: ["Takes storage space", "Heavy (especially cast iron)", "Requires seasoning (cast iron)", "Can warp if thin"],
    bestFor: "Roti, paratha, pancakes, dosa, tortillas, grilled sandwiches",
    material: "Cast Iron, Non-stick, or Carbon Steel",
    diameter: "8, 10, 12 inches",
    care: "Cast iron: season regularly, Non-stick: gentle cleaning",
    price: "$15-$50",
    priceRange: "Budget to Mid",
    fullDesc: "Essential for making flatbreads (roti, chapati, paratha) and dosa. A flat, round pan that distributes heat evenly. Cast iron versions develop a natural non-stick seasoning over time. Non-stick versions are easier to maintain but less durable.",
    durability: "Cast iron: lifetime, Non-stick: 3-5 years",
    type: "cookware",
    cookwareType: "tawa"
  },
  {
    id: 3,
    name: "Karahi/Wok",
    image: "Karahi.png",
    pros: ["High heat cooking capability", "Versatile (stir-fry, deep-fry, curry)", "Quick cooking", "Curved shape for tossing"],
    cons: ["Requires seasoning (carbon steel)", "Not for slow cooking", "Handle gets hot", "Needs high heat source"],
    bestFor: "Stir-frying, deep-frying, Indian curries, pakoras, noodles",
    material: "Carbon steel, Cast iron, or Non-stick",
    capacity: "2, 3, 4, 5 liters",
    care: "Carbon steel: season before first use, hand wash, dry immediately",
    price: "$25-$80",
    priceRange: "Budget to Mid",
    fullDesc: "A deep, curved pan perfect for high-heat cooking. The curved shape allows easy tossing of ingredients. Traditional karahi is carbon steel, which develops a natural non-stick patina. Perfect for stir-fries, curries, and deep-frying.",
    durability: "Carbon steel/cast iron: lifetime, Non-stick: 3-5 years",
    type: "cookware",
    cookwareType: "karahi"
  },
  {
    id: 4,
    name: "Skillet/Frying Pan",
    image: "FryingPan.png",
    pros: ["Versatile and most-used pan", "Quick heating", "Low sides for easy flipping", "Available in all materials"],
    cons: ["Limited capacity for liquids", "Food can stick (stainless steel)", "Handle gets hot", "Not for deep frying"],
    bestFor: "Sautéing, frying eggs, searing meat, pancakes, stir-fry",
    material: "Non-stick, Stainless steel, Cast iron, Carbon steel",
    diameter: "8, 10, 12 inches",
    care: "Varies by material (see cookware materials section)",
    price: "$20-$100",
    priceRange: "Budget to Premium",
    fullDesc: "The most-used pan in most kitchens. Low, slightly curved sides make it easy to flip foods and slide them onto plates. Perfect for everything from eggs to seared steaks. Available in every material - choose based on your cooking style.",
    durability: "5-10 years (non-stick less)",
    type: "cookware",
    cookwareType: "skillet"
  },
  {
    id: 5,
    name: "Dutch Oven",
    image: "DutchOven.png",
    pros: ["Excellent heat retention", "Versatile (stovetop to oven)", "Even heat distribution", "Can bake bread"],
    cons: ["Very heavy", "Expensive (enameled cast iron)", "Requires seasoning (raw cast iron)", "Slow to heat"],
    bestFor: "Braising, stewing, baking bread, soups, chili, roasting",
    material: "Enameled cast iron or raw cast iron",
    capacity: "4, 5.5, 7 quarts",
    care: "Enameled: hand wash, avoid metal utensils; Raw: season regularly",
    price: "$50-$300",
    priceRange: "Premium",
    fullDesc: "A large, heavy pot with tight-fitting lid. Legendary for heat retention and even cooking. Goes from stovetop to oven. Perfect for slow-cooked stews, braised meats, no-knead bread, and soups. Enameled versions don't require seasoning but are more expensive.",
    durability: "Lifetime (heirloom piece)",
    type: "cookware",
    cookwareType: "dutch-oven"
  },
  {
    id: 6,
    name: "Stock Pot",
    image: "StockPot.png",
    pros: ["Large capacity for big batches", "Great for stocks and soups", "Tall sides prevent boiling over", "Lid included"],
    cons: ["Heavy when full", "Takes storage space", "Slow to heat", "Not for browning/searing"],
    bestFor: "Making stocks, soups, pasta, seafood boils, large batches",
    material: "Stainless steel (most common)",
    capacity: "8, 12, 16, 20 quarts",
    care: "Dishwasher safe",
    price: "$30-$120",
    priceRange: "Budget to Mid",
    fullDesc: "A large, tall pot designed for cooking large quantities of liquid-based dishes. The tall sides help prevent boil-overs. Perfect for making stocks from bones, cooking pasta for a crowd, or preparing large batches of soup for freezing.",
    durability: "10+ years",
    type: "cookware",
    cookwareType: "stock-pot"
  }
];

const cookwareMaterials = [
  {
    id: 1,
    name: "Stainless Steel Cookware",
    image: "SteelCookware.png",
    pros: ["Durable and long-lasting", "Non-reactive (won't react with acidic foods)", "Dishwasher safe", "Oven safe", "Professional appearance"],
    cons: ["Food can stick (requires oil)", "Heavier than non-stick", "More expensive than non-stick", "Can discolor with high heat"],
    bestFor: "All-purpose cooking, searing meat, deglazing for sauces",
    care: "Dishwasher safe, use Bar Keepers Friend for stains",
    durability: "Lifetime",
    price: "$$-$$$ (Mid to Premium)",
    fullDesc: "The workhorse of professional kitchens. Stainless steel is durable, non-reactive, and can handle high heat. Food does stick, which is actually good for creating fond (the browned bits) that form the base of pan sauces. Quality cookware has an aluminum or copper core for even heating.",
    type: "cookware-material",
    material: "Stainless Steel with aluminum/copper core"
  },
  {
    id: 2,
    name: "Non-Stick Cookware",
    image: "NonStickCookware.png",
    pros: ["Easy cleaning (wipes clean)", "Less oil needed for cooking", "Food doesn't stick", "Good for beginners"],
    cons: ["Coating wears off over time", "Not for high heat (damages coating)", "Scratches easily", "Not oven safe (usually)", "Short lifespan"],
    bestFor: "Eggs, pancakes, fish, delicate foods",
    care: "Hand wash only, use wooden/silicone utensils, no metal, no high heat",
    durability: "2-5 years (coating degrades)",
    price: "$-$$ (Budget to Mid)",
    fullDesc: "Perfect for delicate foods that tend to stick like eggs, fish, and pancakes. The non-stick coating allows cooking with minimal oil. However, the coating is fragile and will eventually wear off. Never use metal utensils or high heat, which damages the coating.",
    type: "cookware-material",
    material: "Aluminum with PTFE (Teflon) or ceramic coating"
  },
  {
    id: 3,
    name: "Cast Iron Cookware",
    image: "IronCookware.png",
    pros: ["Natural non-stick when seasoned", "Adds dietary iron to food", "Incredibly durable (lasts forever)", "Oven safe any temperature", "Excellent heat retention"],
    cons: ["Very heavy", "Requires seasoning and maintenance", "Rusts if not dried properly", "Not dishwasher safe", "Slow to heat"],
    bestFor: "High heat cooking, searing steaks, frying, baking cornbread",
    care: "Season regularly with oil, dry immediately after washing, never soap",
    durability: "Lifetime (heirloom)",
    price: "$$-$$$ (Mid to Premium)",
    fullDesc: "Cast iron lasts forever and gets better with age as seasoning builds. Excellent heat retention means it stays hot even after adding cold food. Naturally non-stick when properly seasoned. Adds a small amount of dietary iron to your food. Can go from stovetop to oven to campfire.",
    type: "cookware-material",
    material: "Cast Iron"
  }
];

const utensilItems = [
  {
    id: 1,
    name: "Wooden Spoon",
    category: "cooking",
    image: "wooden_spoon.png",
    pros: ["Gentle on cookware", "Doesn't conduct heat", "Natural antibacterial"],
    cons: ["Not dishwasher safe", "Requires oiling", "Can crack"],
    bestFor: "Stirring sauces, mixing batters, non-stick pans",
    material: "Beechwood, Olive wood, Bamboo",
    care: "Hand wash, oil monthly with mineral oil",
    price: "$5-$15",
    fullDesc: "A timeless kitchen tool. Wooden spoons won't scratch any cookware, including delicate non-stick.",
    durability: "5+ years",
    type: "utensil",
    utensilType: "wooden-spoon"
  },
  {
    id: 2,
    name: "Spatula (Turner)",
    category: "cooking",
    image: "Spatula.png",
    pros: ["Thin flexible edge", "Heat resistant", "Essential for flipping"],
    cons: ["Metal scratches non-stick", "Can melt if left in pan"],
    bestFor: "Flipping pancakes, eggs, burgers, fish",
    material: "Silicone, Metal, Wood",
    care: "Dishwasher safe (silicone), hand wash wood",
    price: "$8-$20",
    fullDesc: "Essential for flipping foods. Silicone is best for non-stick pans.",
    durability: "3-5 years",
    type: "utensil",
    utensilType: "spatula"
  },
  {
    id: 3,
    name: "Whisk",
    category: "cooking",
    image: "Whisk.png",
    pros: ["Incorporates air efficiently", "Mixes quickly", "Various sizes"],
    cons: ["Difficult to clean", "Can splash", "Bulky storage"],
    bestFor: "Beating eggs, mixing sauces, whipping cream",
    material: "Stainless steel",
    care: "Hand wash recommended",
    price: "$6-$18",
    fullDesc: "Incorporates air into mixtures for fluffy eggs, whipped cream, and smooth sauces.",
    durability: "5+ years",
    type: "utensil",
    utensilType: "whisk"
  },
  {
    id: 4,
    name: "Tongs",
    category: "cooking",
    image: "Tongs.png",
    pros: ["Secure grip", "Locks for storage", "Heat resistant"],
    cons: ["Can scratch pans", "Spring wears out", "Bulky"],
    bestFor: "Turning meat, serving pasta, grilling",
    material: "Stainless steel with silicone tips",
    care: "Dishwasher safe",
    price: "$10-$25",
    fullDesc: "Like an extension of your hand. Great for flipping and gripping hot foods.",
    durability: "5-10 years",
    type: "utensil",
    utensilType: "tongs"
  },
  {
    id: 5,
    name: "Ladle",
    category: "cooking",
    image: "Ladle.png",
    pros: ["Deep bowl", "Long handle", "Easy pouring"],
    cons: ["Large size", "Only for liquids", "Storage space"],
    bestFor: "Serving soups, stews, sauces",
    material: "Stainless steel",
    care: "Dishwasher safe",
    price: "$8-$20",
    fullDesc: "Perfect for serving soups, stews, and sauces. Deep bowl holds plenty.",
    durability: "10+ years",
    type: "utensil",
    utensilType: "ladle"
  },
  {
    id: 6,
    name: "Slotted Spoon",
    category: "cooking",
    image: "SlottedSpoons.png",
    pros: ["Drains liquids", "Versatile", "Easy to clean"],
    cons: ["Food falls through", "Limited capacity", "Not for liquids"],
    bestFor: "Serving vegetables, pasta, fried foods",
    material: "Stainless steel",
    care: "Dishwasher safe",
    price: "$7-$18",
    fullDesc: "Drains liquids while serving. Perfect for pasta, vegetables, and fried foods.",
    durability: "10+ years",
    type: "utensil",
    utensilType: "slotted-spoon"
  },
  {
    id: 7,
    name: "Pasta Server",
    category: "cooking",
    image: "pasta_server.png",
    pros: ["Curved teeth grip pasta", "Drains water", "Serves perfect portions"],
    cons: ["Single purpose", "Bulky", "Only for pasta"],
    bestFor: "Serving spaghetti, fettuccine, linguine",
    material: "Stainless steel, Nylon",
    care: "Dishwasher safe",
    price: "$8-$15",
    fullDesc: "Specialized tool with curved teeth that grip and hold pasta while draining water.",
    durability: "5-10 years",
    type: "utensil",
    utensilType: "pasta-server"
  },
  {
    id: 8,
    name: "Potato Masher",
    category: "cooking",
    image: "potato_masher.png",
    pros: ["Mashes quickly", "Sturdy design", "Easy to clean"],
    cons: ["Single purpose", "Storage space", "Can bend if cheap"],
    bestFor: "Mashing potatoes, yams, bananas, beans",
    material: "Stainless steel",
    care: "Dishwasher safe",
    price: "$10-$20",
    fullDesc: "Makes smooth mashed potatoes quickly. Zigzag pattern mashes efficiently.",
    durability: "10+ years",
    type: "utensil",
    utensilType: "potato-masher"
  },
  {
    id: 9,
    name: "Vegetable Peeler",
    category: "prep",
    image: "peeler.png",
    pros: ["Quick and efficient", "Safe design", "Thin peels"],
    cons: ["Blade dulls over time", "Only for peeling", "Can break"],
    bestFor: "Peeling potatoes, carrots, apples, cucumbers",
    material: "Stainless steel blade",
    care: "Hand wash, dry immediately",
    price: "$5-$15",
    fullDesc: "Makes quick work of peeling. Swivel blade follows contours of produce.",
    durability: "2-3 years",
    type: "utensil",
    utensilType: "peeler"
  },
  {
    id: 10,
    name: "Cheese Grater (Box Grater)",
    category: "prep",
    image: "grater.png",
    pros: ["Multiple grating sizes", "Sturdy", "Versatile"],
    cons: ["Difficult to clean", "Bulky storage", "Can cut fingers"],
    bestFor: "Grinding cheese, vegetables, zesting citrus",
    material: "Stainless steel",
    sizes: "4-sided with different grate sizes",
    care: "Hand wash with brush",
    price: "$10-$25",
    fullDesc: "4-sided grater with different grate sizes for cheese, vegetables, and zesting.",
    durability: "10+ years",
    type: "utensil",
    utensilType: "grater"
  },
  {
    id: 11,
    name: "Zester",
    category: "prep",
    image: "zester.png",
    pros: ["Fine micro-blades", "Perfect for citrus zest", "Also grates garlic/ginger"],
    cons: ["Single purpose", "Sharp blades", "Small"],
    bestFor: "Zesting lemons, oranges, limes; grating garlic, ginger, nutmeg",
    material: "Stainless steel",
    length: "8-10 inches",
    care: "Hand wash carefully",
    price: "$8-$15",
    fullDesc: "Microplane-style grater perfect for citrus zest, hard cheese, garlic, and ginger.",
    durability: "10+ years",
    type: "utensil",
    utensilType: "zester"
  },
  {
    id: 12,
    name: "Garlic Press",
    category: "prep",
    image: "garlic_press.png",
    pros: ["Quick garlic mincing", "No knife needed", "Extracts maximum flavor"],
    cons: ["Difficult to clean", "Single purpose", "Can rust"],
    bestFor: "Mincing garlic cloves quickly",
    material: "Stainless steel, Cast aluminum",
    care: "Hand wash, clean holes after use",
    price: "$10-$20",
    fullDesc: "Presses garlic cloves through small holes, instantly mincing them without a knife.",
    durability: "10+ years",
    type: "utensil",
    utensilType: "garlic-press"
  },
  {
    id: 13,
    name: "Can Opener",
    category: "prep",
    image: "can_opener.png",
    pros: ["Essential tool", "Smooth cutting", "Ergonomic handle"],
    cons: ["Mechanism can fail", "Difficult for some", "Storage"],
    bestFor: "Opening canned goods safely",
    material: "Stainless steel",
    care: "Wipe clean, dry",
    price: "$8-$20",
    fullDesc: "Essential for opening canned goods. Smooth cutting wheel leaves no sharp edges.",
    durability: "5-10 years",
    type: "utensil",
    utensilType: "can-opener"
  },
  {
    id: 14,
    name: "Rolling Pin",
    category: "baking",
    image: "rolling_pin.png",
    pros: ["Rolls dough evenly", "Wood is non-stick", "Various types"],
    cons: ["Large storage", "Heavy (marble)", "Wood needs care"],
    bestFor: "Rolling dough for cookies, pie crusts, pasta",
    material: "Wood, Marble, Silicone",
    length: "12-18 inches",
    care: "Hand wash, dry immediately",
    price: "$10-$40",
    fullDesc: "Essential for baking. Marble stays cold (good for pastry). Wood is traditional.",
    durability: "Lifetime",
    type: "utensil",
    utensilType: "rolling-pin"
  },
  {
    id: 15,
    name: "Pastry Brush",
    category: "baking",
    image: "pastry_brush.png",
    pros: ["Applies egg wash/butter evenly", "Heat resistant", "Versatile"],
    cons: ["Hairs can shed", "Difficult to clean (silicone)", "Small"],
    bestFor: "Applying egg wash, butter, oil to pastries and breads",
    material: "Silicone, Natural bristle",
    care: "Hand wash, air dry",
    price: "$5-$12",
    fullDesc: "Applies egg wash, melted butter, or oil evenly on baked goods.",
    durability: "3-5 years",
    type: "utensil",
    utensilType: "pastry-brush"
  },
  {
    id: 16,
    name: "Dough Scraper",
    category: "baking",
    image: "dough_scrapper.png",
    pros: ["Stainless steel blade", "Divides dough", "Cleans work surface"],
    cons: ["Sharp edge", "Single purpose", "Storage"],
    bestFor: "Dividing dough, scraping work surfaces, lifting dough",
    material: "Stainless steel",
    size: "4x5 inches",
    care: "Dishwasher safe",
    price: "$8-$15",
    fullDesc: "Essential for bread making. Divides dough and scrapes work surfaces clean.",
    durability: "Lifetime",
    type: "utensil",
    utensilType: "dough-scraper"
  },
  {
    id: 17,
    name: "Sifter / Sieve",
    category: "baking",
    image: "sifter.png",
    pros: ["Removes lumps", "Aerates flour", "Double-duty as strainer"],
    cons: ["Time consuming", "Extra step", "Storage space"],
    bestFor: "Sifting flour, cocoa powder, dusting powdered sugar",
    material: "Stainless steel",
    capacity: "2-4 cups",
    care: "Hand wash, dry well",
    price: "$10-$25",
    fullDesc: "Removes lumps from flour and adds air for lighter baked goods.",
    durability: "10+ years",
    type: "utensil",
    utensilType: "sifter"
  },
  {
    id: 18,
    name: "Measuring Cups (Dry)",
    category: "measuring",
    image: "dry_cups.png",
    pros: ["Nesting for storage", "Level top for accuracy", "Multiple sizes"],
    cons: ["Not for liquids", "Can rust if cheap", "Hand wash only (stainless)"],
    bestFor: "Measuring dry ingredients like flour, sugar, rice",
    material: "Stainless steel, Plastic",
    sizes: "1/4, 1/3, 1/2, 1 cup",
    care: "Dishwasher safe (most)",
    price: "$10-$25",
    fullDesc: "Essential set for precise baking. Level off excess for accuracy.",
    durability: "10+ years",
    type: "utensil",
    utensilType: "dry-measuring-cups"
  },
  {
    id: 19,
    name: "Measuring Spoons",
    category: "measuring",
    image: "dry_spoons.png",
    pros: ["Nesting for storage", "Essential for recipes", "Magnetic options"],
    cons: ["Small and easy to lose", "Can bend if cheap", "Hard to level sticky ingredients"],
    bestFor: "Measuring small amounts of spices, extracts, baking powder",
    material: "Stainless steel, Plastic",
    sizes: "1/8 tsp, 1/4 tsp, 1/2 tsp, 1 tsp, 1 tbsp",
    care: "Dishwasher safe",
    price: "$5-$15",
    fullDesc: "Essential for precise seasoning and baking. Get stainless steel for durability.",
    durability: "10+ years",
    type: "utensil",
    utensilType: "measuring-spoons"
  },
  {
    id: 20,
    name: "Liquid Measuring Cup",
    category: "measuring",
    image: "liq_chps.png",
    pros: ["Spout for pouring", "Clear markings", "Heat resistant (glass)"],
    cons: ["Can break (glass)", "Not for dry ingredients", "Storage space"],
    bestFor: "Measuring liquids like water, milk, oil",
    material: "Glass, Plastic",
    capacity: "1 cup, 2 cups, 4 cups",
    care: "Dishwasher safe",
    price: "$5-$15",
    fullDesc: "Designed for accurate liquid measurement. Read at eye level for precision.",
    durability: "5-10 years (glass), 2-3 years (plastic)",
    type: "utensil",
    utensilType: "liquid-measuring-cup"
  },
  {
    id: 21,
    name: "Kitchen Scale",
    category: "measuring",
    image: "kitchen_scale.png",
    pros: ["Most accurate method", "Works for all ingredients", "Fewer dishes to wash"],
    cons: ["Requires batteries", "More expensive", "Learning curve"],
    bestFor: "Baking, portion control, professional cooking",
    material: "Stainless steel, Plastic",
    capacity: "5-11 lbs / 2-5 kg",
    care: "Wipe clean, remove batteries if not used",
    price: "$15-$40",
    fullDesc: "Most accurate way to measure ingredients. Essential for serious bakers.",
    durability: "5-10 years",
    type: "utensil",
    utensilType: "kitchen-scale"
  },
  {
    id: 22,
    name: "Kitchen Shears",
    category: "specialty",
    image: "kitchen_shears.png",
    pros: ["Multi-purpose", "Come apart for cleaning", "Cut herbs without bruising"],
    cons: ["Need sharpening", "Not for heavy-duty", "Can rust"],
    bestFor: "Cutting herbs, opening packages, snipping poultry",
    material: "Stainless steel",
    care: "Hand wash, dry immediately",
    price: "$12-$30",
    fullDesc: "Incredibly versatile. Use for herbs, packaging, poultry, and even pizza.",
    durability: "5-10 years",
    type: "utensil",
    utensilType: "shears"
  },
  {
    id: 23,
    name: "Meat Tenderizer",
    category: "specialty",
    image: "meat_tender.png",
    pros: ["Tenderizes tough meat", "Two sides (flat/pointed)", "Sturdy"],
    cons: ["Heavy", "Single purpose", "Can be loud"],
    bestFor: "Tenderizing steaks, chicken breasts, pounding meat",
    material: "Cast aluminum, Stainless steel",
    care: "Hand wash, dry",
    price: "$10-$25",
    fullDesc: "Dual-sided tool - flat side for pounding, pointed side for tenderizing.",
    durability: "Lifetime",
    type: "utensil",
    utensilType: "meat-tenderizer"
  },
  {
    id: 24,
    name: "Basting Brush",
    category: "specialty",
    image: "basting_brush.png",
    pros: ["Applies marinade evenly", "Heat resistant", "Silicone is easy to clean"],
    cons: ["Natural bristles shed", "Small", "Can melt if cheap"],
    bestFor: "Basting meats, applying marinades, brushing sauce",
    material: "Silicone, Natural bristle",
    care: "Dishwasher safe (silicone), hand wash (bristle)",
    price: "$5-$12",
    fullDesc: "Applies marinades and sauces to meats while cooking. Silicone is easiest to clean.",
    durability: "3-5 years",
    type: "utensil",
    utensilType: "basting-brush"
  }
];
const crockeryItems = [
  {
    id: 1,
    name: "Dinner Plates",
    category: "dining",
    image: "dinner_plate.png",
    pros: ["Essential for every meal", "Easy to clean", "Stackable"],
    cons: ["Can break if dropped", "Take cabinet space"],
    bestFor: "Main course, formal dining, everyday meals",
    material: "Porcelain, Stoneware",
    care: "Dishwasher safe",
    price: "$5-$25 each",
    fullDesc: "The foundation of your table setting. Dinner plates are typically 10-11 inches.",
    durability: "5-10 years",
    type: "crockery",
    crockeryType: "plate",
    size: "10-11 inches"
  },
  {
    id: 2,
    name: "Side Plates",
    category: "dining",
    image: "side_plate.png",
    pros: ["Multi-purpose", "Space saving", "Versatile"],
    cons: ["Small size limits use", "Can chip"],
    bestFor: "Salad, bread, snacks, dessert",
    material: "Porcelain, Stoneware",
    care: "Dishwasher safe",
    price: "$3-$15 each",
    fullDesc: "Also called salad or dessert plates. Perfect for bread, salad, and desserts.",
    durability: "5-10 years",
    type: "crockery",
    crockeryType: "side-plate",
    size: "7-8 inches"
  },
  {
    id: 3,
    name: "Soup Bowls",
    category: "dining",
    image: "soup_bowl.png",
    pros: ["Deep design holds liquids", "Wide rim for easy eating"],
    cons: ["Limited use (mainly soups)", "Take more storage space"],
    bestFor: "Soups, stews, chili, cereal",
    material: "Ceramic, Stoneware",
    capacity: "12-20 oz",
    care: "Dishwasher safe",
    price: "$4-$18 each",
    fullDesc: "Deeper than cereal bowls. Perfect for broth-based meals.",
    durability: "5-10 years",
    type: "crockery",
    crockeryType: "soup-bowl"
  },
  {
    id: 4,
    name: "Cereal Bowls",
    category: "dining",
    image: "dessert_bowl.png",
    pros: ["Versatile for many foods", "Everyday essential", "Stackable"],
    cons: ["Small capacity for soups", "Can chip"],
    bestFor: "Breakfast cereal, oatmeal, rice, desserts",
    material: "Ceramic, Stoneware",
    capacity: "16-24 oz",
    care: "Dishwasher safe",
    price: "$3-$12 each",
    fullDesc: "Everyday essentials. Great for breakfast and small meals.",
    durability: "3-5 years",
    type: "crockery",
    crockeryType: "cereal-bowl"
  },
  {
    id: 5,
    name: "Serving Bowls (Crockery)",
    category: "dining",
    image: "serving_bowl.png",
    pros: ["Large capacity", "Beautiful presentation", "Family style"],
    cons: ["Storage space", "Heavy when full", "Can break"],
    bestFor: "Salads, pasta, rice, family meals",
    material: "Ceramic, Stoneware",
    capacity: "1-3 quarts",
    care: "Dishwasher safe",
    price: "$10-$35",
    fullDesc: "Brings the family together for shared meals.",
    durability: "5-10 years",
    type: "crockery",
    crockeryType: "serving-bowl"
  },
  {
    id: 6,
    name: "Tea Cups & Saucers",
    category: "tea",
    image: "tea_saucer.png",
    pros: ["Elegant", "Formal", "Saucer catches spills"],
    cons: ["Fragile", "Small capacity", "Hand wash only"],
    bestFor: "Formal tea, coffee, guests",
    material: "Fine porcelain, Bone china",
    capacity: "6-8 oz",
    care: "Hand wash recommended",
    price: "$10-$40 per set",
    fullDesc: "Adds elegance to any gathering. Perfect for afternoon tea.",
    durability: "10+ years",
    type: "crockery",
    crockeryType: "tea-cup"
  },
  {
    id: 7,
    name: "Mugs",
    category: "tea",
    image: "mugs.png",
    pros: ["Heat resistant", "Comfortable handle", "Microwave safe"],
    cons: ["Can stain from coffee/tea", "Can break"],
    bestFor: "Tea, coffee, hot chocolate, soup",
    material: "Ceramic, Stoneware",
    capacity: "10-16 oz",
    care: "Dishwasher safe",
    price: "$5-$20 each",
    fullDesc: "Everyday essentials for morning coffee or evening tea.",
    durability: "5-10 years",
    type: "crockery",
    crockeryType: "mug"
  },
  {
    id: 8,
    name: "Tea Pot",
    category: "tea",
    image: "tea_pot.png",
    pros: ["Large capacity", "Keeps tea warm", "Elegant design"],
    cons: ["Fragile", "Hand wash only", "Takes storage space"],
    bestFor: "Brewing and serving tea for guests",
    material: "Ceramic, Porcelain, Cast iron",
    capacity: "4-8 cups",
    care: "Hand wash recommended",
    price: "$15-$50",
    fullDesc: "Essential for tea lovers. Brews and serves tea beautifully.",
    durability: "10+ years",
    type: "crockery",
    crockeryType: "tea-pot"
  },
  {
    id: 9,
    name: "Sugar Bowl",
    category: "tea",
    image: "salt_sugar_pot.png",
    pros: ["Keeps sugar dry", "With lid", "Elegant"],
    cons: ["Small size", "Can break", "Single purpose"],
    bestFor: "Sugar service at tea/coffee time",
    material: "Ceramic, Porcelain",
    capacity: "8-12 oz",
    care: "Dishwasher safe",
    price: "$8-$20",
    fullDesc: "Essential for tea and coffee service. Keeps sugar fresh and dry.",
    durability: "5-10 years",
    type: "crockery",
    crockeryType: "sugar-bowl"
  },
  {
    id: 10,
    name: "Creamer",
    category: "tea",
    image: "creamer.png",
    pros: ["Pouring spout", "Elegant design", "No drips"],
    cons: ["Small capacity", "Can break", "Single purpose"],
    bestFor: "Serving milk, cream for tea/coffee",
    material: "Ceramic, Porcelain",
    capacity: "6-10 oz",
    care: "Dishwasher safe",
    price: "$6-$18",
    fullDesc: "Perfect for serving milk or cream with tea and coffee.",
    durability: "5-10 years",
    type: "crockery",
    crockeryType: "creamer"
  },
  {
    id: 11,
    name: "Coffee Mugs Set",
    category: "tea",
    image: "coffee_mugs.png",
    pros: ["Thicker walls keep coffee hot", "Comfortable grip", "Durable"],
    cons: ["Heavier than tea cups", "Can stain", "Takes space"],
    bestFor: "Coffee, hot chocolate, morning beverages",
    material: "Ceramic, Stoneware",
    capacity: "12-16 oz",
    care: "Dishwasher safe",
    price: "$15-$30 per set",
    fullDesc: "Perfect for coffee lovers. Thicker ceramic keeps beverages hot longer.",
    durability: "5-10 years",
    type: "crockery",
    crockeryType: "coffee-mug"
  },
  {
    id: 12,
    name: "Water Glasses",
    category: "water",
    image: "water.set.png",
    pros: ["Clear view", "Easy to clean", "Inexpensive"],
    cons: ["Can break easily", "Can be plain", "No handle"],
    bestFor: "Water, juices, cold drinks",
    material: "Glass",
    capacity: "10-16 oz",
    care: "Dishwasher safe",
    price: "$2-$10 each",
    fullDesc: "Everyday drinking glasses for water and cold beverages.",
    durability: "3-5 years",
    type: "crockery",
    crockeryType: "water-glass"
  },
  {
    id: 13,
    name: "Juice Glasses",
    category: "water",
    image: "juice_set.png",
    pros: ["Smaller size", "Stackable", "Perfect portion"],
    cons: ["Small capacity", "Only for small drinks", "Can break"],
    bestFor: "Juices, small portions, kids drinks",
    material: "Glass",
    capacity: "6-8 oz",
    care: "Dishwasher safe",
    price: "$1-$6 each",
    fullDesc: "Perfect for morning juice or small beverage servings.",
    durability: "3-5 years",
    type: "crockery",
    crockeryType: "juice-glass"
  },
  {
    id: 14,
    name: "Pitcher",
    category: "water",
    image: "pitcher.png",
    pros: ["Large capacity", "Easy pouring", "Keeps drinks cold"],
    cons: ["Bulky storage", "Heavy when full", "Can break"],
    bestFor: "Serving water, juice, lemonade, iced tea",
    material: "Glass, Plastic",
    capacity: "1-2 liters",
    care: "Dishwasher safe",
    price: "$10-$30",
    fullDesc: "Essential for serving drinks at the table or for parties.",
    durability: "3-5 years",
    type: "crockery",
    crockeryType: "pitcher"
  },
  {
    id: 15,
    name: "Tumblers",
    category: "water",
    image: "tumbler.png",
    pros: ["Sturdy", "Stackable", "Everyday use"],
    cons: ["Plain design", "Can break", "No handle"],
    bestFor: "Water, cold drinks, everyday use",
    material: "Glass, Stainless steel",
    capacity: "12-14 oz",
    care: "Dishwasher safe",
    price: "$3-$8 each",
    fullDesc: "Sturdy everyday glasses for water and cold beverages.",
    durability: "5+ years",
    type: "crockery",
    crockeryType: "tumbler"
  }
];
const cutleryItems = [
  {
    id: 1,
    name: "Dinner Fork",
    category: "dinner",
    image: "dinner_fork.png",
    pros: ["Essential utensil", "Versatile", "Durable"],
    cons: ["Food can get stuck between tines", "Can bend if cheap"],
    bestFor: "Main course, pasta, salads, meat dishes",
    material: "Stainless steel 18/10",
    length: "7-8 inches",
    care: "Dishwasher safe",
    price: "$2-$8 each",
    fullDesc: "Your most-used eating utensil. Quality 18/10 stainless steel resists rust.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "dinner-fork"
  },
  {
    id: 2,
    name: "Dinner Knife",
    category: "dinner",
    image: "dinner_knife.png",
    pros: ["Serrated edge cuts easily", "Essential for meat", "Durable"],
    cons: ["Needs occasional sharpening", "Safety with children"],
    bestFor: "Cutting meat, vegetables, spreading butter",
    material: "Stainless steel 18/10",
    length: "8-9 inches",
    care: "Dishwasher safe",
    price: "$3-$10 each",
    fullDesc: "Designed to cut food on your plate. Quality knives have full tang.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "dinner-knife"
  },
  {
    id: 3,
    name: "Tablespoon",
    category: "dinner",
    image: "tablespoon.png",
    pros: ["Larger size holds more", "Multi-purpose", "Sturdy"],
    cons: ["Too large for some mouths", "Heavy"],
    bestFor: "Eating main courses, serving food, measuring",
    material: "Stainless steel",
    length: "6-7 inches",
    care: "Dishwasher safe",
    price: "$2-$6 each",
    fullDesc: "Larger than teaspoons. Great for serving and eating main courses.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "tablespoon"
  },
  {
    id: 4,
    name: "Teaspoon",
    category: "dinner",
    image: "tea_spoon.png",
    pros: ["Perfect size for stirring", "Versatile", "Standard measurement"],
    cons: ["Too small for main courses", "Can get lost"],
    bestFor: "Stirring coffee/tea, eating desserts, measuring spices",
    material: "Stainless steel",
    length: "5-6 inches",
    care: "Dishwasher safe",
    price: "$1-$5 each",
    fullDesc: "For stirring coffee and eating desserts. Every kitchen needs many.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "teaspoon"
  },
  {
    id: 5,
    name: "Dessert Spoon",
    category: "dinner",
    image: "dessert_spoon.png",
    pros: ["Perfect dessert size", "Elegant", "Comfortable"],
    cons: ["Limited use", "Not for main courses", "Extra item"],
    bestFor: "Desserts, pudding, ice cream, yogurt",
    material: "Stainless steel",
    length: "6-7 inches",
    care: "Dishwasher safe",
    price: "$2-$7 each",
    fullDesc: "Smaller than tablespoon, larger than teaspoon. Perfect for desserts.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "dessert-spoon"
  },
  {
    id: 6,
    name: "Soup Spoon",
    category: "dinner",
    image: "soup_spoon.png",
    pros: ["Round bowl holds liquid", "Comfortable grip", "Essential for soup"],
    cons: ["Single purpose", "Larger than other spoons"],
    bestFor: "Soups, stews, broth, liquid foods",
    material: "Stainless steel",
    length: "6-7 inches",
    care: "Dishwasher safe",
    price: "$2-$7 each",
    fullDesc: "Round bowl to hold more liquid. Essential for soup lovers.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "soup-spoon"
  },
  {
    id: 7,
    name: "Salad Fork",
    category: "dinner",
    image: "salad_fork.png",
    pros: ["Smaller size", "Elegant", "Perfect for appetizers"],
    cons: ["Limited use", "Smaller than dinner fork", "Extra item"],
    bestFor: "Salads, appetizers, seafood, desserts",
    material: "Stainless steel",
    length: "6-7 inches",
    care: "Dishwasher safe",
    price: "$2-$6 each",
    fullDesc: "Smaller than dinner fork. Used for salad courses and appetizers.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "salad-fork"
  },
  {
    id: 8,
    name: "Coffee Spoon",
    category: "tea",
    image: "coffee_spoon.png",
    pros: ["Smaller than teaspoon", "Perfect for espresso", "Elegant"],
    cons: ["Very small", "Limited use", "Can get lost"],
    bestFor: "Stirring espresso, cappuccino, small cups",
    material: "Stainless steel",
    length: "4-5 inches",
    care: "Dishwasher safe",
    price: "$1-$4 each",
    fullDesc: "Small spoon designed for espresso and demitasse cups.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "coffee-spoon"
  },
  {
    id: 9,
    name: "Sugar Spoon",
    category: "tea",
    image: "sugar_spoon.png",
    pros: ["Small scoop shape", "Perfect for sugar", "Elegant"],
    cons: ["Single purpose", "Small size", "Can get lost"],
    bestFor: "Scooping sugar from sugar bowl",
    material: "Stainless steel, Silver",
    length: "4-5 inches",
    care: "Hand wash recommended",
    price: "$3-$10 each",
    fullDesc: "Small spoon with a deep bowl for scooping sugar.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "sugar-spoon"
  },
  {
    id: 10,
    name: "Butter Knife",
    category: "tea",
    image: "butter_knife.png",
    pros: ["Rounded edge for safety", "Essential for breakfast", "Good for spreading"],
    cons: ["Not for cutting", "Limited function", "Small"],
    bestFor: "Spreading butter, jams, soft cheeses, peanut butter",
    material: "Stainless steel",
    length: "6-7 inches",
    care: "Dishwasher safe",
    price: "$2-$6 each",
    fullDesc: "Rounded tips for safe spreading. Essential for breakfast.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "butter-knife"
  },
  {
    id: 11,
    name: "Tea Strainer Spoon",
    category: "tea",
    image: "tea_strainer.png",
    pros: ["Strains loose tea", "Multi-purpose", "Elegant"],
    cons: ["Small holes clog", "Single purpose", "Delicate"],
    bestFor: "Straining loose tea leaves while pouring",
    material: "Stainless steel",
    length: "5-6 inches",
    care: "Hand wash",
    price: "$5-$15",
    fullDesc: "Combines spoon and strainer. Perfect for loose leaf tea.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "tea-strainer"
  },
  {
    id: 12,
    name: "Serving Fork",
    category: "serving",
    image: "serving_fork.png",
    pros: ["Long handle", "Large tines", "Great for carving"],
    cons: ["Large size", "Storage space", "Limited to serving"],
    bestFor: "Carving meat, serving roasts, holding food while cutting",
    material: "Stainless steel",
    length: "9-10 inches",
    care: "Dishwasher safe",
    price: "$5-$15",
    fullDesc: "Large fork for carving and serving meat dishes.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "serving-fork"
  },
  {
    id: 13,
    name: "Serving Spoon",
    category: "serving",
    image: "serving_spoon.png",
    pros: ["Large bowl", "Long handle", "Deep scoop"],
    cons: ["Heavy", "Large size", "Storage space"],
    bestFor: "Serving vegetables, rice, pasta, gravy",
    material: "Stainless steel",
    length: "8-9 inches",
    care: "Dishwasher safe",
    price: "$4-$12",
    fullDesc: "Large spoon for serving main dishes and sides.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "serving-spoon"
  },
  {
    id: 14,
    name: "Slotted Serving Spoon",
    category: "serving",
    image: "slotted_spoon.png",
    pros: ["Drains liquids", "Great for vegetables", "Versatile"],
    cons: ["Slots let small foods fall", "Limited use"],
    bestFor: "Serving vegetables, pasta, dumplings, fried foods",
    material: "Stainless steel",
    length: "8-9 inches",
    care: "Dishwasher safe",
    price: "$5-$15",
    fullDesc: "Perfect for serving foods that need draining.",
    durability: "10+ years",
    type: "cutlery",
    cutleryType: "slotted-serving-spoon"
  }
];
const utensilsServing = {
  id: 1,
  name: "Serving Utensils Set",
  tagline: "Complete serving tools for every dish",
  fullDesc: "A complete set of serving utensils designed for easy and elegant food service. This set includes all the essential tools you need to serve curries, rice, desserts, cakes, fish, and more. Made from high-quality 18/10 stainless steel that resists rust and maintains its shine for years. The ergonomic handles provide a comfortable grip, and the utensils are dishwasher safe for easy cleaning.",
  keyUses: [
    "Serving curries and gravies with the curry ladle",
    "Serving rice and grains with the rice spoon",
    "Scooping ice cream and frozen desserts",
    "Serving cakes, pies, and pastries with cake server",
    "Serving fish and delicate foods with fish slice",
    "Tossing and serving salads and pasta with tongs",
    "Gripping and serving breads, meats, and vegetables"
  ],
  image: "ser_utensils_set.png",
  type: "serving-utensils",
  material: "Stainless Steel 18/10",
  price: "$30-$70",
  priceRange: "Mid Range",
  bestFor: "Everyday serving, parties, family dinners, entertaining guests",
  durability: "10+ years with proper care",
  pros: [
    "Complete set covers all serving needs",
    "Premium 18/10 stainless steel resists rust",
    "Ergonomic handles for comfortable grip",
    "Dishwasher safe for easy cleaning",
    "Heat resistant for hot foods",
    "Professional look for entertaining"
  ],
  cons: [
    "Set takes significant drawer/cabinet space",
    "Some pieces may be rarely used",
    "Metal can scratch non-stick serving bowls",
    "Hand washing recommended to maintain shine"
  ],
  care: "Dishwasher safe on top rack. For best results and longest life, hand wash with mild soap and dry immediately. Avoid using abrasive scrubbers that can scratch the surface.",
  sizes: "Each utensil approximately 9-10 inches in length",
  utensilType: "serving-utensils-complete-set",
  items: [
    "Curry Ladle",
    "Rice Spoon",
    "Ice Cream Scoop",
    "Cake Server",
    "Fish Slice",
    "Serving Tongs",
    "Tongs"
  ]
};
const cutleryEating = {
  id: 2,
  name: "Cutlery Set",
  tagline: "Complete dining essentials for everyday meals",
  fullDesc: "A complete 6-piece cutlery set for daily dining. Made from premium 18/10 stainless steel that provides excellent rust resistance and durability. Each piece is perfectly balanced with a comfortable weight. The satin finish resists fingerprints and water spots. This set includes everything you need for breakfast, lunch, and dinner - from main courses to desserts.",
  keyUses: [
    "Dinner knife - cutting meat, vegetables, and spreading",
    "Dinner fork - eating main courses, pasta, and salads",
    "Salad fork - smaller fork for appetizers and salads",
    "Table spoon - eating main courses and serving",
    "Dessert spoon - eating sweets, puddings, and ice cream",
    "Teaspoon - stirring tea/coffee and eating small portions"
  ],
  image: "ser_cutlery_set.png",
  type: "cutlery",
  material: "Stainless Steel 18/10",
  price: "$20-$60",
  priceRange: "Budget to Mid",
  bestFor: "Daily dining, family meals, formal dinner settings, entertaining guests",
  durability: "10-15 years with proper care",
  pros: [
    "Complete 6-piece set for all dining needs",
    "Premium 18/10 stainless steel won't rust",
    "Comfortable weight and balanced feel",
    "Dishwasher safe for convenience",
    "Satin finish resists water spots",
    "Smooth edges for comfortable use"
  ],
  cons: [
    "Knives may require occasional sharpening",
    "Can develop water spots if not dried promptly",
    "Cheaper versions may bend under pressure",
    "Some designs have hard-to-clean crevices"
  ],
  care: "Dishwasher safe. For best results, dry immediately after washing to prevent water spots. Avoid leaving in contact with acidic foods for extended periods.",
  sizes: "Dinner knife: 8-9 inches, Dinner fork: 7-8 inches, Salad fork: 6-7 inches, Table spoon: 6-7 inches, Dessert spoon: 6 inches, Teaspoon: 5-6 inches",
  cutleryType: "eating-cutlery-complete-set",
  items: [
    "Dinner Knife",
    "Dinner Fork",
    "Salad Fork",
    "Table Spoon",
    "Dessert Spoon",
    "Teaspoon"
  ]
};
const dinnerwareBowls = {
  id: 3,
  name: "Dinnerware - Bowls",
  tagline: "Complete collection of serving bowls for every need",
  fullDesc: "A comprehensive collection of bowls for all your serving needs. From small ramekins to large tureens, this category includes everything you need to serve soups, salads, rice dishes, desserts, and more. Choose from various materials including ceramic, stoneware, and glass depending on your style and durability preferences.",
  keyUses: [
    "Serving soups, stews, and chili",
    "Serving salads and fresh vegetables",
    "Serving rice, pasta, and grain dishes",
    "Serving desserts like ice cream and pudding",
    "Serving cereal and breakfast items",
    "Baking and serving individual portions (ramekins)"
  ],
  image: "ser_bowl_set.png",
  type: "dinnerware",
  subcategory: "bowls",
  material: "Ceramic / Stoneware / Glass / Porcelain",
  price: "$25-$120 (set dependent)",
  priceRange: "Budget to Premium",
  bestFor: "Serving all types of food, family-style meals, entertaining",
  durability: "5-10 years with careful use",
  pros: [
    "Multiple sizes for different foods",
    "Microwave and dishwasher safe (most materials)",
    "Beautiful presentation options",
    "Stackable for compact storage",
    "Non-porous materials won't stain",
    "Heat retention for warm foods"
  ],
  cons: [
    "Can chip or crack if dropped",
    "Ceramic and glass are heavy",
    "Takes significant cabinet space",
    "Some materials not oven safe"
  ],
  care: "Most are dishwasher safe. Avoid sudden temperature changes (don't pour hot liquid into cold glass). Stack carefully to prevent chipping.",
  commonItems: [
    "Serving Bowls (large, medium, small)",
    "Salad Bowls",
    "Soup Bowls / Soup Cups",
    "Cereal Bowls",
    "Ramekins (small baking/serving bowls)",
    "Tureen (large covered bowl)",
    "Sugar Bowl"
  ]
};
const dinnerwarePlatters = {
  id: 4,
  name: "Dinnerware - Platters & Trays",
  tagline: "Elegant platters and trays for impressive food presentation",
  fullDesc: "A complete collection of platters and trays designed to elevate your food presentation. Large platters are perfect for main dishes like biryani, roasted meats, and whole fish. Serving trays are ideal for appetizers, snacks, and drinks. Cake stands add height and drama to desserts. Available in ceramic, slate, wood, and marble materials.",
  keyUses: [
    "Serving main courses like biryani, roast meats, and pasta",
    "Presenting appetizers and finger foods",
    "Displaying cakes, pastries, and desserts on cake stands",
    "Serving breakfast items on serving trays",
    "Presenting cheese boards and charcuterie",
    "Serving fruits and snacks for parties"
  ],
  image: "ser_platters.png",
  type: "dinnerware",
  subcategory: "platters-and-trays",
  material: "Ceramic / Slate / Wood / Marble / Porcelain",
  price: "$20-$80 (per piece)",
  priceRange: "Mid to Premium",
  bestFor: "Entertaining guests, holiday meals, special occasions, buffet-style serving",
  durability: "5-10+ years with careful use",
  pros: [
    "Large surface area for main dishes",
    "Beautiful presentation for special occasions",
    "Slate and wood options for modern look",
    "Marble stays cold for cheese and desserts",
    "Cake stands create beautiful centerpieces",
    "Many are dishwasher safe"
  ],
  cons: [
    "Bulky - takes significant storage space",
    "Can be heavy, especially when full",
    "Fragile - can break if dropped",
    "Large platters may not fit in standard cabinets",
    "Slate can be heavy and expensive"
  ],
  care: "Most ceramic and glass are dishwasher safe. Wood and slate require hand washing. Marble should be hand washed and dried immediately.",
  commonItems: [
    "Round Platters (various sizes)",
    "Oval Platters",
    "Rectangular Platters",
    "Wooden Serving Boards",
    "Marble Serving Boards",
    "Serving Trays (various sizes)",
    "Cake Stand (single tier)",
    "Cake Stand (multi-tier)"
  ]
};
const dinnerwareGravy = {
  id: 5,
  name: "Dinnerware - Gravy & Sauceware",
  tagline: "Specialized vessels for serving gravies and sauces",
  fullDesc: "A specialized collection for serving gravies, sauces, and condiments. The gravy boat features a built-in spout for drip-free pouring. Small sauce bowls and dip bowls are perfect for serving individual portions of chutney, ketchup, or dipping sauces. Cruet sets keep oil and vinegar organized on the table.",
  keyUses: [
    "Serving gravy with roasts and holiday meals",
    "Serving curry sauces and dal",
    "Serving dips like hummus, salsa, and ranch",
    "Serving chutneys and pickles with meals",
    "Serving oil and vinegar for salads (cruet set)",
    "Serving melted butter for seafood"
  ],
  image: "ser_gravy_boats.png",
  type: "dinnerware",
  subcategory: "gravy-and-sauceware",
  material: "Ceramic / Porcelain / Glass",
  price: "$15-$45 (per set)",
  priceRange: "Budget to Mid",
  bestFor: "Holiday dinners, family meals, parties, formal dining",
  durability: "5-10 years with careful use",
  pros: [
    "Drip-free pouring spout on gravy boats",
    "Perfect portion sizes for dips and sauces",
    "Cruet sets keep table organized",
    "Matching sets look elegant",
    "Small sizes don't take much storage",
    "Microwave safe for reheating sauces"
  ],
  cons: [
    "Single-purpose items for most pieces",
    "Can tip over easily if not on stable surface",
    "Small pieces can get lost",
    "Fragile - can chip or break"
  ],
  care: "Most are dishwasher safe. Hand washing recommended for decorative or hand-painted pieces. Dry thoroughly before storing.",
  commonItems: [
    "Gravy Boat with attached tray",
    "Gravy Boat without tray",
    "Chutney Bowls (small)",
    "Pickle Bowls",
    "Dip Bowls",
    "Condiment Set (3-6 small bowls with tray)",
    "Cruet Set (oil and vinegar bottles)",
    "Butter Dish with lid"
  ]
};
const dinnerwareAccessories = {
  id: 6,
  name: "Dinnerware - Accessories",
  tagline: "Essential table accessories for complete dining experience",
  fullDesc: "A collection of essential table accessories that complete your dining setup. Tea and coffee serveware includes teapots, coffee pots, creamers, and sugar bowls. Additional accessories like salt and pepper shakers, napkin rings, and trivets add functionality and style to your table.",
  keyUses: [
    "Brewing and serving tea with teapot",
    "Serving coffee at breakfast or after dinner",
    "Serving cream and milk with beverages",
    "Serving sugar for tea and coffee",
    "Seasoning food with salt and pepper shakers",
    "Protecting tables with trivets and coasters"
  ],
  image: "ser_accessories.png",
  type: "dinnerware",
  subcategory: "accessories",
  material: "Ceramic / Porcelain / Glass / Wood / Metal",
  price: "$10-$60 (set dependent)",
  priceRange: "Budget to Premium",
  bestFor: "Complete table setting, tea time, coffee service, everyday dining",
  durability: "5-10+ years with careful use",
  pros: [
    "Completes your table setting",
    "Teapots and coffee pots keep beverages hot",
    "Creamer and sugar bowl add elegance",
    "Salt and pepper shakers are essential for every table",
    "Trivets protect table surfaces",
    "Many are dishwasher safe"
  ],
  cons: [
    "Many small pieces to store",
    "Can be fragile",
    "Some items (teapots) take significant space",
    "Matching sets can be expensive"
  ],
  care: "Most ceramic and glass are dishwasher safe. Wooden accessories require hand washing. Metal accessories should be dried immediately to prevent water spots.",
  commonItems: [
    "Tea Pot (various capacities)",
    "Coffee Pot / Carafe",
    "Creamer / Milk Pitcher",
    "Sugar Bowl with lid",
    "Salt and Pepper Shakers (set)",
    "Napkin Rings (set of 4-6)",
    "Trivets / Pot Holders (matching)",
    "Coasters (set of 4-6)"
  ]
};
knivesData.forEach(item => {
  addGuide(item, 'kitchen-tools', 'knives', ['knife', 'cutting', 'chef', 'paring', 'bread', 'santoku', 'boning', 'utility', 'nakiri']);
});
cuttingBoardTypes.forEach(item => {
  addGuide(item, 'kitchen-tools', 'cutting-boards', ['cutting-board', 'chopping-board', 'bamboo', 'maple', 'plastic', 'rubber']);
});
mixingBowlTypes.forEach(item => {
  addGuide(item, 'kitchen-tools', 'mixing-bowls', ['mixing-bowl', 'stainless-steel', 'glass', 'ceramic', 'plastic']);
});-
cookwareTypes.forEach(item => {
  addGuide(item, 'kitchen-tools', 'cookware', ['cookware', 'pressure-cooker', 'tawa', 'karahi', 'skillet', 'dutch-oven', 'stock-pot']);
});
cookwareMaterials.forEach(item => {
  addGuide(item, 'kitchen-tools', 'cookware-materials', ['cookware-material', 'stainless-steel', 'non-stick', 'cast-iron']);
});
utensilItems.forEach(item => {
  addGuide(item, 'kitchen-tools', 'utensils', ['utensil', 'cooking', 'prep', 'baking', 'measuring', 'specialty']);
});
crockeryItems.forEach(item => {
  addGuide(item, 'kitchen-tools', 'crockery', ['crockery', 'plate', 'bowl', 'cup', 'mug', 'teapot', 'dinnerware']);
});
cutleryItems.forEach(item => {
  addGuide(item, 'kitchen-tools', 'cutlery', ['cutlery', 'fork', 'knife', 'spoon', 'dinner', 'tea', 'serving']);
});
addGuide(utensilsServing, 'kitchen-tools', 'servingware', ['utensils', 'serving', 'serving-utensils', 'complete-set', 'stainless-steel', 'entertaining']);
addGuide(cutleryEating, 'kitchen-tools', 'servingware', ['cutlery', 'eating', 'dining', 'complete-set', 'stainless-steel', 'fork', 'spoon', 'knife']);
addGuide(dinnerwareBowls, 'kitchen-tools', 'servingware', ['dinnerware', 'bowls', 'serving-bowls', 'ceramic', 'stoneware', 'soup-bowl', 'salad-bowl']);
addGuide(dinnerwarePlatters, 'kitchen-tools', 'servingware', ['dinnerware', 'platters', 'trays', 'cake-stand', 'ceramic', 'serving-tray']);
addGuide(dinnerwareGravy, 'kitchen-tools', 'servingware', ['dinnerware', 'gravy', 'sauce', 'condiments', 'gravy-boat', 'cruet-set', 'butter-dish']);
addGuide(dinnerwareAccessories, 'kitchen-tools', 'servingware', ['dinnerware', 'accessories', 'tea-pot', 'coffee', 'sugar-bowl', 'salt-pepper', 'table-accessories']);

const migrate = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected');

    const admin = await User.findOne({ email: 'chefbot.ai.kitchen@gmail.com' });
    if (!admin) {
      console.error('Admin not found');
      process.exit(1);
    }

    const validGuides = allGuides.filter(g => g.title && g.content);
    if (validGuides.length === 0) {
      console.log('No guides to insert');
      process.exit(0);
    }

    const toInsert = validGuides.map(g => ({ ...g, createdBy: admin._id }));
    const result = await BeginnersGuide.insertMany(toInsert);
    console.log(result.length + ' guides inserted');
    process.exit(0);
  } catch (error) {
    console.error('Migration failed:', error);
    process.exit(1);
  }
};

migrate();