const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
  {
    title: "Chana Dal",
    image: "chana-daal.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup chana dal (split Bengal gram) - washed and soaked",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "2 tablespoons oil or ghee",
      "Salt to taste",
      "Fresh coriander leaves for decoration",
      "2 green chilies - slit lengthwise"
    ],
    stepsRaw: [
      "Wash chana dal well under running water until the water runs clear. Soak in fresh water for 30 minutes. Drain before cooking.",
      "In a pressure cooker, add the soaked dal, 2 cups of water, turmeric powder, and salt. Close the lid and pressure cook on medium heat for 3-4 whistles or until the dal is soft and mushy.",
      "Let the pressure release naturally. Open the lid and mash the dal slightly with the back of a spoon. Set aside.",
      "Heat oil or ghee in a separate pan over medium heat. Add cumin seeds and let them crackle for 30 seconds until they smell good.",
      "Add finely chopped onions and cook for 5-6 minutes until they turn golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until the raw smell goes away.",
      "Add chopped tomatoes and cook for 5-6 minutes until they become soft and mushy.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes until the spices smell good.",
      "Add the cooked dal and stir well. Add 1/2 cup of water if the dal is too thick. Let it simmer for 10-12 minutes on low heat.",
      "Sprinkle garam masala and decorate with fresh coriander leaves and green chilies.",
      "Serve hot with steamed rice, jeera rice, or roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A protein-rich split Bengal gram dal cooked with aromatic spices – a simple, comforting Pakistani favorite.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 15,
    baseServings: 4,
    calories: 220,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chana dal", "onion", "tomato", "ginger-garlic paste", "cumin seeds", "turmeric", "red chili", "coriander", "garam masala", "ghee", "green chilies"],
    searchKeywords: ["chana dal", "split Bengal gram", "pakistani dal", "protein rich lentil", "vegetarian curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chana Dal Fry",
    image: "chana-daal.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup chana dal - washed and soaked",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon mustard seeds",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "2 tablespoons ghee",
      "Salt to taste",
      "Fresh coriander leaves for decoration",
      "1 lemon - juiced"
    ],
    stepsRaw: [
      "Wash chana dal well and soak in water for 30 minutes. Drain well.",
      "In a pressure cooker, add the soaked dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles until the dal is soft but not completely mushy.",
      "Let the pressure release naturally. Open the lid and set the cooked dal aside.",
      "Heat ghee in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and the oil starts separating.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 8-10 minutes on low heat, stirring now and then.",
      "Add garam masala, lemon juice, and fresh coriander leaves. Mix well.",
      "Serve hot with naan, roti, or steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Chana dal (split Bengal gram) with mustard and cumin seeds, finished with lemon juice – a tasty dal fry.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 18,
    baseServings: 4,
    calories: 240,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chana dal", "mustard seeds", "cumin seeds", "onion", "tomato", "ginger-garlic paste", "ghee", "lemon", "coriander"],
    searchKeywords: ["chana dal fry", "tempered chana dal", "dal fry recipe", "pakistani chana dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chana Dal Palak",
    image: "chana-dal-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup chana dal - washed and soaked",
      "2 cups fresh spinach (palak) - washed and finely chopped",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "2 tablespoons oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash chana dal and soak for 30 minutes. Drain well.",
      "In a pressure cooker, add the soaked dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles until soft.",
      "Let the pressure release naturally. Set the cooked dal aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped spinach and cook for 3-4 minutes until the spinach wilts completely.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 8-10 minutes on low heat.",
      "Sprinkle garam masala and decorate with fresh coriander leaves.",
      "Serve hot with roti or steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Healthy chana dal with fresh spinach – a good-for-you, iron-rich lentil curry great with roti or rice.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 20,
    baseServings: 4,
    calories: 230,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chana dal", "spinach", "palak", "onion", "tomato", "ginger-garlic paste", "cumin", "coriander", "garam masala"],
    searchKeywords: ["chana dal palak", "spinach chana dal", "healthy dal", "iron rich lentil"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chana Dal Louki",
    image: "chana-dal-lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup chana dal - washed and soaked",
      "2 cups louki (bottle gourd) - peeled and cut into small pieces",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "2 tablespoons oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash chana dal and soak for 30 minutes. Drain well.",
      "In a pressure cooker, add the soaked dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles until soft.",
      "Let the pressure release naturally. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add louki pieces and cook for 5-6 minutes, stirring now and then.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 10-12 minutes until the louki is completely tender.",
      "Decorate with fresh coriander leaves and serve hot with steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Light and healthy chana dal with bottle gourd (louki) – a comforting, low-oil lentil dish.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 18,
    baseServings: 4,
    calories: 210,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chana dal", "louki", "bottle gourd", "onion", "tomato", "ginger-garlic paste", "cumin", "coriander"],
    searchKeywords: ["chana dal louki", "bottle gourd dal", "light lentil curry", "healthy dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chana Dal with Spinach",
    image: "chana-dal-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup chana dal - washed and soaked",
      "2 cups fresh spinach - blanched and pureed",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons ghee",
      "Salt to taste",
      "2 tablespoons fresh cream (optional)"
    ],
    stepsRaw: [
      "Wash chana dal and soak for 30 minutes. Drain well.",
      "In a pressure cooker, add the soaked dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles until soft.",
      "Let the pressure release naturally. Mash the dal slightly with a spoon. Set aside.",
      "Blanch spinach in hot water for 2 minutes, then blend into a smooth puree. Set aside.",
      "Heat ghee in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add tomato puree and cook for 5-6 minutes until the ghee separates from the masala.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add spinach puree and cook for 3-4 minutes.",
      "Add the cooked dal and stir well. Simmer for 8-10 minutes on low heat.",
      "Sprinkle garam masala and add fresh cream if using. Mix well.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Rich and creamy chana dal with spinach puree, finished with a touch of cream – a restaurant-style healthy dal.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 4,
    calories: 260,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chana dal", "spinach puree", "onion", "tomato puree", "ginger-garlic paste", "ghee", "cumin", "garam masala", "cream"],
    searchKeywords: ["chana dal spinach", "palak chana dal", "creamy spinach dal", "restaurant style dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Moong Dal",
    image: "moong-dal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup moong dal (split yellow lentils) - washed",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "2 tablespoons oil or ghee",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash moong dal well under running water until the water runs clear. Moong dal does not need soaking.",
      "In a pressure cooker, add the washed dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. The dal should be soft and slightly mushy. Set aside.",
      "Heat oil or ghee in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until the raw smell goes away.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and mushy.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes until the spices smell good.",
      "Add the cooked dal and stir well. Simmer for 5-7 minutes on low heat.",
      "Decorate with fresh coriander leaves and serve hot with steamed rice or roti."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Light and easy-to-digest split yellow moong dal – a simple, comforting lentil curry great for everyday meals.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 12,
    baseServings: 4,
    calories: 180,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["moong dal", "onion", "tomato", "ginger-garlic paste", "cumin", "turmeric", "red chili", "coriander", "ghee"],
    searchKeywords: ["moong dal", "yellow lentil dal", "simple dal", "pakistani moong dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Moong Dal Fry",
    image: "moong-dal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup moong dal - washed",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon mustard seeds",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons ghee",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash moong dal well. No need to soak.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. Set aside.",
      "Heat ghee in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and the oil starts separating.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 5-7 minutes on low heat.",
      "Add garam masala and fresh coriander leaves. Mix well.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Easy",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Moong dal with mustard and cumin seeds – a tasty dal fry that goes great with roti or naan.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 15,
    baseServings: 4,
    calories: 200,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["moong dal", "mustard seeds", "cumin seeds", "onion", "tomato", "ginger-garlic paste", "ghee", "garam masala"],
    searchKeywords: ["moong dal fry", "tempered moong dal", "dal fry recipe", "easy lentil curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Moong Dal Palak",
    image: "chana-dal-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup moong dal - washed",
      "2 cups fresh spinach - washed and finely chopped",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash moong dal well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped spinach and cook for 3-4 minutes until wilted completely.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 5-7 minutes on low heat.",
      "Sprinkle garam masala and decorate with fresh coriander leaves.",
      "Serve hot with roti or steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Healthy green moong dal with fresh spinach – a good-for-you, iron-rich lentil curry great with roti or rice.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 18,
    baseServings: 4,
    calories: 210,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["moong dal", "spinach", "palak", "onion", "tomato", "ginger-garlic paste", "cumin", "garam masala"],
    searchKeywords: ["moong dal palak", "spinach moong dal", "healthy green dal", "iron rich lentil"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Moong Dal Louki",
    image: "chana-dal-lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup moong dal - washed",
      "2 cups louki (bottle gourd) - peeled and cut into small pieces",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "2 tablespoons oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash moong dal well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add louki pieces and cook for 5-6 minutes, stirring now and then.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 8-10 minutes until louki is tender.",
      "Decorate with fresh coriander leaves and serve hot with steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Light summer moong dal with bottle gourd (louki) – a refreshing, easy-to-digest lentil curry.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 16,
    baseServings: 4,
    calories: 195,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["moong dal", "louki", "bottle gourd", "onion", "tomato", "ginger-garlic paste", "cumin", "coriander"],
    searchKeywords: ["moong dal louki", "bottle gourd dal", "light summer dal", "healthy lentil"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Moong Dal with Spinach",
    image: "chana-dal-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup moong dal - washed",
      "2 cups fresh spinach - blanched and pureed",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons ghee",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash moong dal well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. Mash the dal slightly. Set aside.",
      "Blanch spinach in hot water for 2 minutes, then blend into a smooth puree.",
      "Heat ghee in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add tomato puree and cook for 5-6 minutes until the ghee separates.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add spinach puree and cook for 3-4 minutes.",
      "Add the cooked dal and stir well. Simmer for 5-7 minutes on low heat.",
      "Sprinkle garam masala and serve hot with roti."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Creamy moong dal with smooth spinach puree and a touch of ghee – a good-for-you, restaurant-style dal.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 22,
    baseServings: 4,
    calories: 235,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["moong dal", "spinach puree", "onion", "tomato puree", "ginger-garlic paste", "ghee", "cumin", "garam masala"],
    searchKeywords: ["creamy moong dal spinach", "palak moong dal puree", "healthy dal", "restaurant style"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Moong Dal Khichdi",
    image: "daal-mong-khichri.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1/2 cup moong dal - washed",
      "1/2 cup basmati rice - washed",
      "1 medium onion - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "2 tablespoons ghee",
      "Salt to taste",
      "Fresh coriander leaves for decoration",
      "3 cups water"
    ],
    stepsRaw: [
      "Wash rice and moong dal together well under running water. Drain well.",
      "Heat ghee in a pressure cooker over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 3-4 minutes until light golden.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add the washed rice and dal. Stir well to coat with ghee for 2 minutes.",
      "Add turmeric powder and salt. Mix well.",
      "Add 3 cups of water and stir everything together.",
      "Close the pressure cooker lid and cook on medium heat for 3-4 whistles.",
      "Let the pressure release naturally. Open the lid and check the consistency. It should be soft and porridge-like.",
      "If too thick, add some hot water and mix well.",
      "Decorate with fresh coriander leaves and serve hot with yogurt, pickle, or papad."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Comforting rice and moong dal porridge (khichdi) – light, easy to digest, great for sick days or a healthy meal.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 20,
    baseServings: 4,
    calories: 250,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["moong dal", "basmati rice", "onion", "ginger-garlic paste", "cumin", "turmeric", "ghee"],
    searchKeywords: ["moong dal khichdi", "rice lentil porridge", "comfort food", "sick day meal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Maash Dal",
    image: "mash-dal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup maash dal (black lentils / urad dal) - washed and soaked",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "2 tablespoons oil or ghee",
      "Salt to taste",
      "Fresh coriander leaves for decoration",
      "2 green chilies - slit lengthwise"
    ],
    stepsRaw: [
      "Wash maash dal well under running water. Soak in fresh water for 2 hours. Drain before cooking.",
      "In a pressure cooker, add the soaked dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 4-5 whistles until the dal is very soft and mushy.",
      "Let the pressure release naturally. Open the lid and mash the dal well with a spoon. Set aside.",
      "Heat oil or ghee in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until the raw smell goes away.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and mushy.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes until the spices smell good.",
      "Add the cooked dal and stir well. Add 1/2 cup of water if the dal is too thick. Let it simmer for 15-20 minutes on low heat.",
      "Sprinkle garam masala and decorate with fresh coriander leaves and green chilies.",
      "Serve hot with steamed rice, naan, or roti."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Rich and creamy black lentils (maash dal / urad dal) slow-cooked with aromatic spices – a classic Pakistani dal.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 22,
    baseServings: 4,
    calories: 260,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["maash dal", "black lentils", "urad dal", "onion", "tomato", "ginger-garlic paste", "cumin", "coriander", "garam masala"],
    searchKeywords: ["maash ki dal", "black lentil dal", "urad dal recipe", "creamy dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Maash Dal Fry",
    image: "maash-daal-fry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup maash dal - washed and soaked",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon mustard seeds",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons ghee",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash maash dal and soak for 2 hours. Drain well.",
      "In a pressure cooker, add the soaked dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 4-5 whistles until very soft.",
      "Let the pressure release naturally. Mash the dal well and set aside.",
      "Heat ghee in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and the ghee separates.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 10-12 minutes on low heat.",
      "Add garam masala and fresh coriander leaves. Mix well.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "Restaurant-style black lentils (maash dal) with mustard and cumin tadka – rich and tasty.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 25,
    baseServings: 4,
    calories: 280,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["maash dal", "mustard seeds", "cumin seeds", "onion", "tomato", "ginger-garlic paste", "ghee", "garam masala"],
    searchKeywords: ["maash dal fry", "tempered black lentil", "restaurant style dal", "urad dal fry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Maash Dal Palak",
    image: "chana-dal-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup maash dal - washed and soaked",
      "2 cups fresh spinach - washed and finely chopped",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash maash dal and soak for 2 hours. Drain well.",
      "In a pressure cooker, add the soaked dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 4-5 whistles until soft.",
      "Let the pressure release naturally. Mash the dal slightly and set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped spinach and cook for 3-4 minutes until wilted.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 10-12 minutes on low heat.",
      "Sprinkle garam masala and serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "Healthy black lentils (maash dal) with fresh spinach – a hearty, iron-rich vegetarian dal.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 24,
    baseServings: 4,
    calories: 250,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["maash dal", "spinach", "palak", "onion", "tomato", "ginger-garlic paste", "cumin", "garam masala"],
    searchKeywords: ["maash dal palak", "black lentil spinach", "healthy dal", "iron rich lentil"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Maash Dal Louki",
    image: "chana-dal-lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup maash dal - washed and soaked",
      "2 cups louki (bottle gourd) - peeled and cut into small pieces",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "2 tablespoons oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash maash dal and soak for 2 hours. Drain well.",
      "In a pressure cooker, add the soaked dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 4-5 whistles until soft.",
      "Let the pressure release naturally. Mash the dal slightly and set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add louki pieces and cook for 5-6 minutes, stirring now and then.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 10-12 minutes until louki is tender.",
      "Serve hot with steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "Creamy black lentils (maash dal) with bottle gourd (louki) – a light, healthy, and good-for-you dal.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 22,
    baseServings: 4,
    calories: 240,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["maash dal", "louki", "bottle gourd", "onion", "tomato", "ginger-garlic paste", "cumin", "coriander"],
    searchKeywords: ["maash dal louki", "black lentil bottle gourd", "light creamy dal", "healthy lentil"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Masoor Dal",
    image: "masoor-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup masoor dal (red lentils) - washed",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "2 tablespoons oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash masoor dal well under running water until the water runs clear. Masoor dal does not need soaking.",
      "In a pressure cooker, add the washed dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. The dal should be soft and mushy. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and mushy.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 5-7 minutes on low heat.",
      "Decorate with fresh coriander leaves and serve hot with steamed rice or roti."
    ],
    difficulty: "Easy",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Quick and easy red lentil dal (masoor dal) – a simple, everyday Pakistani comfort food.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 10,
    baseServings: 4,
    calories: 180,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["masoor dal", "red lentils", "onion", "tomato", "ginger-garlic paste", "cumin", "turmeric", "coriander", "oil"],
    searchKeywords: ["masoor dal", "red lentil curry", "quick dal", "pakistani masoor dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Masoor Dal Fry",
    image: "masoor-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup masoor dal - washed",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon mustard seeds",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons ghee",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash masoor dal well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. Set aside.",
      "Heat ghee in a pan over medium heat. Add mustard seeds and cumin seeds. Let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and the ghee separates.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 5-7 minutes on low heat.",
      "Add garam masala and fresh coriander leaves. Mix well.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Red lentil dal with mustard and cumin seeds – a tasty, restaurant-style dal fry.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 15,
    baseServings: 4,
    calories: 210,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["masoor dal", "mustard seeds", "cumin seeds", "onion", "tomato", "ginger-garlic paste", "ghee", "garam masala"],
    searchKeywords: ["masoor dal fry", "tempered red lentil", "dal fry recipe", "quick dal fry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Masoor Dal Palak",
    image: "chana-dal-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup masoor dal - washed",
      "2 cups fresh spinach - washed and finely chopped",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash masoor dal well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped spinach and cook for 3-4 minutes until wilted.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 5-7 minutes on low heat.",
      "Sprinkle garam masala and serve hot with roti or rice."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Quick healthy red lentil dal with fresh spinach – a good-for-you, iron-packed meal ready in minutes.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 16,
    baseServings: 4,
    calories: 195,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["masoor dal", "spinach", "palak", "onion", "tomato", "ginger-garlic paste", "cumin", "garam masala"],
    searchKeywords: ["masoor dal palak", "red lentil spinach", "healthy dal", "iron rich lentil"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Masoor Dal Louki",
    image: "chana-dal-lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup masoor dal - washed",
      "2 cups louki (bottle gourd) - peeled and cut into small pieces",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "2 tablespoons oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash masoor dal well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add louki pieces and cook for 5-6 minutes, stirring now and then.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 8-10 minutes until louki is tender.",
      "Serve hot with steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Light and healthy red lentil dal with bottle gourd (louki) – a refreshing, easy-to-digest meal.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 14,
    baseServings: 4,
    calories: 185,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["masoor dal", "louki", "bottle gourd", "onion", "tomato", "ginger-garlic paste", "cumin", "coriander"],
    searchKeywords: ["masoor dal louki", "red lentil bottle gourd", "light summer dal", "healthy lentil"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mix Dal",
    image: "mix-daal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1/3 cup chana dal - washed and soaked",
      "1/3 cup moong dal - washed",
      "1/3 cup masoor dal - washed",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "2 tablespoons oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash all dals together. Soak chana dal separately for 30 minutes as it takes longer to cook.",
      "Mix all dals together in a pressure cooker. Add 2.5 cups of water, turmeric powder, and salt.",
      "Pressure cook for 3-4 whistles until all dals are soft and well-cooked.",
      "Let the pressure release naturally. Mash the dals slightly with a spoon. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and mushy.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 8-10 minutes on low heat.",
      "Sprinkle garam masala and decorate with fresh coriander leaves.",
      "Serve hot with steamed rice or roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A tasty mix of three lentils (chana, moong, masoor) – the best of all dals in one comforting pot.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 15,
    baseServings: 4,
    calories: 210,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chana dal", "moong dal", "masoor dal", "onion", "tomato", "ginger-garlic paste", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["mix dal", "mixed lentil curry", "three dal recipe", "pakistani mix dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Panchmel Dal",
    image: "panchmel-dal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1/4 cup chana dal - washed and soaked",
      "1/4 cup moong dal - washed",
      "1/4 cup masoor dal - washed",
      "1/4 cup urad dal - washed and soaked",
      "1/4 cup toor dal - washed",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "2 tablespoons ginger-garlic-green chili paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons ghee",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash all dals together. Soak chana dal and urad dal for 1 hour as they take longer to cook.",
      "Mix all dals in a pressure cooker. Add 3 cups of water, turmeric powder, and salt.",
      "Pressure cook for 4-5 whistles until all dals are very soft and well-cooked.",
      "Let the pressure release naturally. Mash the dals well with a spoon. Set aside.",
      "Heat ghee in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic-green chili paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and the ghee separates.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 10-12 minutes on low heat.",
      "Add garam masala and fresh coriander leaves. Mix well.",
      "Serve hot with steamed rice or roti."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Authentic Rajasthani five-lentil dal – a tasty, protein-packed dish with ghee and aromatic spices.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 4,
    calories: 260,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chana dal", "moong dal", "masoor dal", "urad dal", "toor dal", "ghee", "cumin", "ginger-garlic-green chili paste", "garam masala"],
    searchKeywords: ["panchmel dal", "five lentil dal", "rajasthani dal", "mixed lentil curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Dal Makhani",
    image: "daal-makhni.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup whole urad dal (sabut urad) - washed and soaked overnight",
      "1/4 cup rajma (kidney beans) - washed and soaked overnight",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1/4 cup heavy cream",
      "3 tablespoons butter",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash urad dal and rajma together. Soak in plenty of water overnight (8-10 hours). Drain before cooking.",
      "In a pressure cooker, add the soaked dal and rajma, 3 cups of water, turmeric powder, and salt. Pressure cook for 5-6 whistles until very soft and mushy.",
      "Let the pressure release naturally. Open the lid and mash the dal well with a masher or the back of a spoon. Set aside.",
      "Heat butter in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 6-7 minutes until dark golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add tomato puree and cook for 7-8 minutes until the butter separates from the masala.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Add 1/2 cup of water if needed.",
      "Simmer on very low heat for 30-40 minutes, stirring now and then. The longer it simmers, the better the flavor.",
      "Add cream and garam masala. Mix well and simmer for another 5-7 minutes.",
      "Decorate with fresh coriander leaves and a spoonful of butter.",
      "Serve hot with butter naan or steamed rice."
    ],
    difficulty: "Hard",
    cookingTime: 90,
    isActive: true,
    isHalal: true,
    description: "Rich, creamy black lentil dal with kidney beans, slow-cooked with butter and cream – a classic restaurant favorite.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["urad dal", "rajma", "butter", "heavy cream", "onion", "tomato puree", "ginger-garlic paste", "cumin", "garam masala"],
    searchKeywords: ["dal makhani", "creamy black lentil", "restaurant style dal", "butter dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Dal Palak",
    image: "chana-dal-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup mixed dal (moong dal + masoor dal) - washed",
      "2 cups fresh spinach - washed and finely chopped",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash the mixed dals well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped spinach and cook for 3-4 minutes until wilted.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 5-7 minutes on low heat.",
      "Sprinkle garam masala and serve hot with roti or steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Iron-rich dal with moong and masoor lentils and fresh spinach – a healthy, comforting green dal.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 18,
    baseServings: 4,
    calories: 200,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["moong dal", "masoor dal", "spinach", "onion", "tomato", "ginger-garlic paste", "cumin", "garam masala"],
    searchKeywords: ["dal palak", "spinach lentil curry", "healthy dal", "iron rich dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Dal Louki",
    image: "chana-dal-lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup moong dal - washed",
      "2 cups louki (bottle gourd) - peeled and cut into small pieces",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "2 tablespoons oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash moong dal well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add louki pieces and cook for 5-6 minutes, stirring now and then.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 8-10 minutes until louki is tender.",
      "Serve hot with steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Light and refreshing moong dal with bottle gourd (louki) – great for summer, easy to digest.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 16,
    baseServings: 4,
    calories: 185,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["moong dal", "louki", "bottle gourd", "onion", "tomato", "ginger-garlic paste", "cumin", "coriander"],
    searchKeywords: ["dal louki", "bottle gourd dal", "light summer dal", "healthy lentil"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Dal Tori",
    image: "chana-dal-lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup chana dal - washed and soaked",
      "2 cups tori (ridge gourd) - peeled and cut into small pieces",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon coriander powder",
      "2 tablespoons oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash chana dal and soak for 30 minutes. Drain well.",
      "In a pressure cooker, add the soaked dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles until soft.",
      "Let the pressure release naturally. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add tori pieces and cook for 5-6 minutes, stirring now and then.",
      "Add red chili powder, coriander powder, and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 8-10 minutes until tori is tender.",
      "Serve hot with steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Special and tasty chana dal with ridge gourd (tori) – a good-for-you, high-fiber dish.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 18,
    baseServings: 4,
    calories: 210,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chana dal", "tori", "ridge gourd", "onion", "tomato", "ginger-garlic paste", "cumin", "coriander"],
    searchKeywords: ["dal tori", "ridge gourd dal", "chana dal with tori", "healthy dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Dal Karela",
    image: "daal-karela.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup toor dal - washed",
      "2 medium karela (bitter gourd) - thinly sliced",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon dry mango powder (amchur)",
      "2 tablespoons oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Rub karela slices with 1 teaspoon salt and set aside for 30 minutes to reduce the bitterness. Rinse well with water and squeeze out the bitter juice completely.",
      "Wash toor dal well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles until soft.",
      "Let the pressure release naturally. Mash the dal slightly. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add the prepared karela slices and fry for 5-6 minutes until lightly browned.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 8-10 minutes on low heat.",
      "Sprinkle amchur powder and serve hot with steamed rice."
    ],
    difficulty: "Hard",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "Healthy bitter-sweet dal with toor dal and bitter gourd (karela) – a special taste with great health benefits.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 20,
    baseServings: 4,
    calories: 230,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["toor dal", "karela", "bitter gourd", "onion", "tomato", "ginger-garlic paste", "cumin", "amchur"],
    searchKeywords: ["dal karela", "bitter gourd dal", "healthy bitter dal", "toor dal with karela"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Dal Methi",
    image: "chana-dal-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup moong dal - washed",
      "1 large bunch fresh methi (fenugreek leaves) - washed and finely chopped",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "2 tablespoons oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash moong dal well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 2-3 whistles until soft.",
      "Let the pressure release naturally. Set aside.",
      "Heat oil in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5 minutes until soft.",
      "Add chopped methi leaves and cook for 3-4 minutes until wilted.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 5-7 minutes on low heat.",
      "Decorate with fresh coriander leaves and serve hot with roti or steamed rice."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Aromatic and healthy moong dal with fresh fenugreek leaves (methi) – a little bitter, deeply tasty.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 18,
    baseServings: 4,
    calories: 200,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["moong dal", "methi", "fenugreek leaves", "onion", "tomato", "ginger-garlic paste", "cumin"],
    searchKeywords: ["dal methi", "fenugreek dal", "healthy lentil", "moong dal methi"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Dal Tadka",
    image: "daal-tadka.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup toor dal - washed",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons ghee",
      "1 teaspoon mustard seeds",
      "2 dried red chilies",
      "Few curry leaves",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash toor dal well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles until soft and mushy.",
      "Let the pressure release naturally. Whisk the dal well until smooth. Set aside.",
      "Heat 1 tablespoon of ghee in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and mushy.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 8-10 minutes on low heat.",
      "For the tadka: In a small pan, heat the remaining 1 tablespoon of ghee. Add mustard seeds, dried red chilies, and curry leaves. Let them crackle for 30 seconds.",
      "Pour the hot tadka over the dal. Add garam masala and fresh coriander leaves.",
      "Serve hot with steamed rice or jeera rice."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Classic restaurant-style toor dal with a fragrant ghee tadka of mustard seeds, cumin, and curry leaves.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 22,
    baseServings: 4,
    calories: 240,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["toor dal", "ghee", "mustard seeds", "cumin seeds", "curry leaves", "onion", "tomato", "ginger-garlic paste"],
    searchKeywords: ["dal tadka", "tempered dal", "restaurant dal", "toor dal tadka"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Dal Fry",
    image: "chana-daal.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup mixed dal (toor dal + moong dal) - washed",
      "1 medium onion - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "1 small capsicum - finely chopped",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons butter",
      "1 teaspoon kasuri methi (dried fenugreek leaves)",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash the mixed dals well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles until soft.",
      "Let the pressure release naturally. Whisk the dal well until smooth. Set aside.",
      "Heat butter in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 5-6 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add finely chopped capsicum and cook for 2-3 minutes.",
      "Add tomato puree and cook for 5-6 minutes until the butter separates from the masala.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 8-10 minutes on low heat.",
      "Crush kasuri methi between your palms and add to the dal. Add garam masala and fresh coriander leaves.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Restaurant-style dal fry with a mix of toor and moong dal, capsicum, and a buttery tomato gravy.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 4,
    calories: 260,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["toor dal", "moong dal", "butter", "capsicum", "onion", "tomato puree", "ginger-garlic paste", "kasuri methi"],
    searchKeywords: ["dal fry", "restaurant dal fry", "mixed dal fry", "buttery dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Dal Bukhara",
    image: "daal-bukhara.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup whole urad dal (sabut urad) - washed and soaked overnight",
      "1/4 cup rajma (kidney beans) - washed and soaked overnight",
      "2 medium onions - finely chopped",
      "2 medium tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup heavy cream",
      "1/4 cup butter",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash urad dal and rajma together. Soak in plenty of water overnight (8-10 hours). Drain before cooking.",
      "In a pressure cooker, add the soaked dal and rajma, 3 cups of water, and salt. Pressure cook for 5-6 whistles until very soft and mushy.",
      "Let the pressure release naturally. Open the lid and mash the dal well with a masher. Set aside.",
      "Heat butter in a pan over medium heat. Add cumin seeds and let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 7-8 minutes until dark golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add tomato puree and cook for 7-8 minutes until the butter separates from the masala.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Add 1/2 cup of water if needed.",
      "Simmer on very low heat for 45-60 minutes, stirring now and then. The longer it simmers, the better the flavor.",
      "Add cream and garam masala. Mix well and simmer for another 10-15 minutes.",
      "Decorate with fresh coriander leaves and a spoonful of butter.",
      "Serve hot with butter naan or steamed rice."
    ],
    difficulty: "Hard",
    cookingTime: 90,
    isActive: true,
    isHalal: true,
    description: "Peshawar-style royal creamy black lentil dal with butter and cream – rich, slow-cooked, and indulgent.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 40,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["urad dal", "rajma", "butter", "heavy cream", "onion", "tomato puree", "ginger-garlic paste", "garam masala"],
    searchKeywords: ["dal bukhara", "peshawari dal", "creamy black dal", "royal dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Gujarati Dal",
    image: "daal-bukhara.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup toor dal - washed",
      "1 tablespoon ginger-green chili paste",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon mustard seeds",
      "1 teaspoon cumin seeds",
      "1/2 teaspoon asafoetida (hing)",
      "Few curry leaves",
      "1 tablespoon jaggery (gur) - grated",
      "1 tablespoon lemon juice",
      "2 tablespoons oil",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash toor dal well.",
      "In a pressure cooker, add the dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles until soft.",
      "Let the pressure release naturally. Whisk the dal well until smooth. Set aside.",
      "Heat oil in a pan over medium heat. Add mustard seeds, cumin seeds, asafoetida, and curry leaves. Let them crackle for 30 seconds.",
      "Add ginger-green chili paste and cook for 1 minute until it smells good.",
      "Add red chili powder and salt. Mix well and cook for 1 minute.",
      "Add the cooked dal and bring to a boil.",
      "Add grated jaggery and mix well until dissolved.",
      "Simmer for 5-7 minutes on low heat.",
      "Add lemon juice and mix well.",
      "Decorate with fresh coriander leaves and serve hot with steamed rice or khichdi."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Sweet and sour Gujarati-style toor dal with jaggery and lemon – a lovely balance of flavors.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 18,
    baseServings: 4,
    calories: 190,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["toor dal", "jaggery", "lemon juice", "mustard seeds", "cumin seeds", "asafoetida", "curry leaves", "ginger-green chili paste"],
    searchKeywords: ["gujarati dal", "sweet sour dal", "khatti meethi dal", "toor dal recipe"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Rajasthani Dal",
    image: "daal-bukhara.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup chana dal - washed and soaked",
      "2 tablespoons ghee",
      "1 teaspoon cumin seeds",
      "1 teaspoon mustard seeds",
      "2 dried red chilies",
      "1 medium onion - finely chopped",
      "2 tablespoons ginger-garlic paste",
      "2 medium tomatoes - finely chopped",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "Salt to taste",
      "Fresh coriander leaves for decoration"
    ],
    stepsRaw: [
      "Wash chana dal and soak for 1 hour. Drain well.",
      "In a pressure cooker, add the soaked dal, 2 cups of water, turmeric powder, and salt. Pressure cook for 3-4 whistles until soft.",
      "Let the pressure release naturally. Mash the dal slightly. Set aside.",
      "Heat ghee in a pan over medium heat. Add cumin seeds, mustard seeds, and dried red chilies. Let them crackle for 30 seconds.",
      "Add finely chopped onions and cook for 6-7 minutes until dark golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chopped tomatoes and cook for 5-6 minutes until soft and the ghee separates.",
      "Add red chili powder and salt. Mix well and cook for 2 minutes.",
      "Add the cooked dal and stir well. Simmer for 10-12 minutes on low heat.",
      "Add garam masala and fresh coriander leaves. Mix well.",
      "Serve hot with steamed rice or roti."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Spicy Rajasthani-style chana dal with ghee, mustard seeds, and dried red chilies – bold and tasty.",
    category: "Dinner",
    subCategory: "plain-dal",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 22,
    baseServings: 4,
    calories: 250,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chana dal", "ghee", "mustard seeds", "cumin seeds", "dried red chilies", "onion", "tomato", "ginger-garlic paste", "garam masala"],
    searchKeywords: ["rajasthani dal", "spicy chana dal", "dal tadka rajasthani", "desi dal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
];

async function migrateRecipes() {
  try {
    console.log('Connecting to MongoDB...');
    
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) {
      throw new Error('MongoDB URI not found');
    }
    
    await mongoose.connect(mongoURI, { 
      serverSelectionTimeoutMS: 10000, 
      family: 4 
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();