const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
  {
    title: "Chicken Curry",
    image: "chicken-curry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "2 onions - chopped small",
      "2 tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "Fresh coriander leaves for garnish",
      "2 green chilies - cut long"
    ],
    stepsRaw: [
      "Put oil in a big pot on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until the raw smell goes away.",
      "Add chicken pieces and fry on high heat for 5-7 minutes until the chicken changes color.",
      "Add chopped tomatoes and cook for 6-7 minutes until they become soft.",
      "Add turmeric, red chili powder, coriander powder, and salt. Mix well and cook for 2-3 minutes.",
      "Add 1 cup of water and bring to a boil. Cover and cook on medium heat for 20-25 minutes.",
      "Sprinkle garam masala and put fresh coriander leaves and green chilies on top.",
      "Serve hot with naan or rice."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A classic Pakistani chicken curry that's rich, flavorful, and pairs perfectly with naan or rice.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "cumin", "oil", "salt"],
    searchKeywords: ["chicken curry", "pakistani chicken", "classic chicken", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Karahi",
    image: "chicken-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "4 tomatoes - chopped small",
      "2 tablespoons ginger - cut into thin strips",
      "2 tablespoons garlic - chopped small",
      "4 green chilies - cut long",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili flakes",
      "1 teaspoon black pepper powder",
      "1 teaspoon salt",
      "1/2 cup cooking oil",
      "Fresh coriander leaves for garnish",
      "1 lemon - juice"
    ],
    stepsRaw: [
      "Put oil in a karahi (wok) on high heat. Add chicken and fry for 5 minutes.",
      "Add ginger strips, chopped garlic, and green chilies. Cook for 2 minutes.",
      "Add chopped tomatoes and cook for 8-10 minutes until they become soft and oil starts to separate.",
      "Add cumin seeds, red chili flakes, black pepper powder, and salt. Mix well.",
      "Cook on high heat until the oil comes on top and the chicken is done.",
      "Add lemon juice and put fresh coriander leaves on top.",
      "Serve hot with naan."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A traditional karahi-style chicken that's bold, spicy, and perfect for a hearty meal with naan.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 370,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "tomato", "ginger", "garlic", "green chili", "cumin", "oil", "salt", "lemon"],
    searchKeywords: ["chicken karahi", "pakistani karahi", "karahi chicken", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Handi",
    image: "chicken-handi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "1 cup yogurt - beaten until smooth",
      "2 onions - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1/4 cup cream",
      "Fresh coriander leaves for garnish"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add turmeric powder, red chili powder, and salt. Mix well.",
      "Add beaten yogurt and mix well.",
      "Cover and cook on low heat for 25 minutes.",
      "Add cream and garam masala. Cook for 5 minutes on low heat.",
      "Put fresh coriander leaves on top and serve."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A slow-cooked creamy chicken handi that's rich, flavorful, and perfect for a royal dining experience.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "onion", "cumin", "cream", "oil", "salt"],
    searchKeywords: ["chicken handi", "handi chicken", "creamy chicken", "pakistani chicken", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Qorma",
    image: "chicken-qorma.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "1 cup yogurt - beaten until smooth",
      "2 onions - sliced thin",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "4 whole cloves",
      "2 green cardamom pods",
      "1 small cinnamon stick"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add whole spices (cloves, cardamom, cinnamon) and cook for 30 seconds until they pop.",
      "Add sliced onions and fry for 7-8 minutes until golden brown.",
      "Take out half of the fried onions and keep aside for later.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add turmeric powder, red chili powder, and salt. Mix well.",
      "Add beaten yogurt slowly while stirring all the time so it doesn't curdle.",
      "Add 1/2 cup water and cook for 25 minutes.",
      "Add garam masala and put the saved fried onions on top.",
      "Serve hot with naan or rice."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A rich and creamy chicken qorma that's perfect for special occasions and family gatherings.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 90,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "onion", "cumin", "oil", "salt"],
    searchKeywords: ["chicken qorma", "chicken korma", "pakistani qorma", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Jalfrezi",
    image: "chicken-jalfrezi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - boneless, cut into cubes",
      "2 onions - chopped small",
      "2 tomatoes - chopped small",
      "2 capsicum - sliced into strips",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken cubes and fry until the chicken turns white.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add turmeric, red chili powder, coriander powder, and salt. Mix well.",
      "Cook on high heat until the oil separates.",
      "Add capsicum strips and cook for 2 minutes.",
      "Sprinkle garam masala and serve."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A spicy and flavorful chicken jalfrezi with thick gravy and crunchy capsicum, perfect with naan or rice.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "capsicum", "cumin", "oil", "salt"],
    searchKeywords: ["chicken jalfrezi", "spicy chicken", "pakistani chicken", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Lahori",
    image: "chicken-lahori.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "2 onions - chopped small",
      "2 tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "2 tablespoons vinegar",
      "Fresh coriander leaves for garnish"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add turmeric, red chili powder, coriander powder, and salt. Mix well.",
      "Add vinegar and 1/2 cup water. Cook for 20 minutes.",
      "Add garam masala and put fresh coriander leaves on top.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A spicy Lahori-style chicken curry with a tangy kick from vinegar, perfect for those who love bold flavors.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 385,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "cumin", "vinegar", "oil", "salt"],
    searchKeywords: ["chicken lahori", "lahori chicken", "pakistani chicken", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Mughlai",
    image: "chicken-mughlai.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "1 cup yogurt - beaten until smooth",
      "1/2 cup cream",
      "2 onions - sliced thin",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "4 whole cloves",
      "2 green cardamom pods",
      "1 small cinnamon stick"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add whole spices (cloves, cardamom, cinnamon) and cook for 30 seconds until they pop.",
      "Add sliced onions and fry for 7-8 minutes until brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add turmeric powder, red chili powder, and salt. Mix well.",
      "Add beaten yogurt and cook for 20 minutes.",
      "Add cream and cook for 5 minutes on low heat.",
      "Sprinkle garam masala and serve."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A royal Mughlai chicken curry with a rich, creamy gravy that's perfect for special occasions.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 95,
    baseServings: 4,
    calories: 460,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "cream", "onion", "cumin", "oil", "salt"],
    searchKeywords: ["chicken mughlai", "royal chicken", "pakistani chicken", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Do Pyaza",
    image: "chicken-do-pyaz.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "3 onions - sliced thin (divided)",
      "2 tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add half of the sliced onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add turmeric, red chili powder, and salt. Mix well.",
      "Cook for 15 minutes.",
      "Add the remaining raw sliced onions and garam masala.",
      "Cook for 5 minutes and serve."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A delicious chicken do pyaza with double the onions, offering a perfect balance of sweet and savory flavors.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "cumin", "oil", "salt"],
    searchKeywords: ["chicken do pyaza", "do pyaza chicken", "pakistani chicken", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "White Chicken Karahi",
    image: "white-chicken-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "1 cup yogurt - beaten until smooth",
      "2 tablespoons ginger paste",
      "2 tablespoons garlic paste",
      "4 green chilies - whole",
      "1 teaspoon white pepper powder",
      "1 teaspoon black pepper powder",
      "1 teaspoon salt",
      "1/2 cup cooking oil",
      "Fresh coriander leaves for garnish"
    ],
    stepsRaw: [
      "Put oil in a karahi (wok) on medium heat. Add chicken and fry for 5 minutes.",
      "Add ginger paste, garlic paste, and green chilies. Cook for 2 minutes until they smell good.",
      "Add yogurt and cook on high heat until the oil separates.",
      "Add white pepper powder, black pepper powder, and salt. Mix well.",
      "Cook for 10-15 minutes.",
      "Put fresh coriander leaves on top and serve."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A mild and creamy white chicken karahi that's perfect for those who prefer less spicy curries.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 400,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "ginger", "garlic", "green chili", "oil", "salt"],
    searchKeywords: ["white chicken karahi", "white karahi", "creamy karahi", "pakistani karahi", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Peshawari Chicken Karahi",
    image: "peshawari-chicken-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "4 tomatoes - chopped small",
      "2 tablespoons ginger - cut into thin strips",
      "2 tablespoons garlic - chopped small",
      "4 green chilies - whole",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili flakes",
      "1 teaspoon black pepper powder",
      "1 teaspoon salt",
      "1/2 cup cooking oil"
    ],
    stepsRaw: [
      "Put oil in a karahi (wok) on high heat. Add chicken and fry for 5 minutes.",
      "Add ginger strips, chopped garlic, and whole green chilies.",
      "Add chopped tomatoes and cook for 8-10 minutes until they become soft.",
      "Add cumin seeds, red chili flakes, black pepper powder, and salt. Mix well.",
      "Cook on high heat until the oil separates.",
      "Serve with naan."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A rustic and flavorful Peshawari-style chicken karahi that's cooked without water for intense taste.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 370,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "tomato", "ginger", "garlic", "green chili", "cumin", "oil", "salt"],
    searchKeywords: ["peshawari chicken karahi", "peshawari karahi", "pakistani karahi", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Spicy Chicken Karahi",
    image: "spicy-chicken-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "4 tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "4 green chilies - whole",
      "2 teaspoons red chili powder",
      "1 teaspoon cumin seeds",
      "1 teaspoon black pepper powder",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a karahi (wok) on high heat. Add chicken and fry.",
      "Add ginger-garlic paste and green chilies.",
      "Add chopped tomatoes and cook for 8-10 minutes until they become soft.",
      "Add red chili powder, cumin seeds, black pepper powder, and salt. Mix well.",
      "Cook until the oil separates.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "An extra spicy chicken karahi for heat lovers, packed with bold and intense flavors.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 370,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "tomato", "ginger", "garlic", "green chili", "cumin", "oil", "salt"],
    searchKeywords: ["spicy chicken karahi", "hot chicken karahi", "pakistani karahi", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Karahi with Gravy",
    image: "chicken-karahi-with-gravy.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "4 tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "4 green chilies - whole",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1/2 cup cooking oil",
      "Salt as needed",
      "Fresh coriander leaves for garnish"
    ],
    stepsRaw: [
      "Put oil in a karahi (wok) on high heat. Add chicken and fry.",
      "Add ginger-garlic paste and green chilies.",
      "Add tomato puree and cook.",
      "Add cumin seeds, red chili powder, and salt. Mix well.",
      "Add 1 cup of water and cook for 20 minutes on low heat.",
      "Put fresh coriander leaves on top and serve."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A chicken karahi with extra gravy, perfect for those who love more sauce with their naan.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "tomato", "ginger", "garlic", "green chili", "cumin", "oil", "salt"],
    searchKeywords: ["chicken karahi with gravy", "karahi gravy", "pakistani karahi", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Dry Chicken Karahi",
    image: "dry-chicken-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "2 tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "4 green chilies - whole",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a karahi (wok) on high heat. Add chicken and fry until golden brown.",
      "Add ginger-garlic paste and green chilies.",
      "Add chopped tomatoes and cook for 8-10 minutes until they become dry.",
      "Add cumin seeds, red chili powder, and salt. Mix well.",
      "Cook on high heat until the chicken is done and the dish is completely dry.",
      "Serve hot with yogurt sauce (raita)."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "A dry chicken karahi with no gravy, where the masala coats every piece perfectly - ideal with naan.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 360,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "tomato", "ginger", "garlic", "green chili", "cumin", "oil", "salt"],
    searchKeywords: ["dry chicken karahi", "sukha karahi", "pakistani karahi", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Masala",
    image: "chicken-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "2 onions - chopped small",
      "2 tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "Fresh coriander leaves for garnish"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates.",
      "Add turmeric, red chili powder, coriander powder, and salt. Mix well.",
      "Add 1/2 cup water and cook for 20 minutes.",
      "Add garam masala and put fresh coriander leaves on top.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A spicy and aromatic chicken masala that's perfect for those who love rich, flavorful curries.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "cumin", "oil", "salt"],
    searchKeywords: ["chicken masala", "masala chicken", "spicy chicken", "pakistani chicken", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Tikka Masala",
    image: "chicken-tikka-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken tikka pieces - already cooked",
      "2 onions - chopped small",
      "2 tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon kasuri methi (dried fenugreek leaves)",
      "1/2 cup cream",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates.",
      "Add turmeric, red chili powder, and salt. Mix well.",
      "Add chicken tikka pieces and cook for 10 minutes.",
      "Add cream and kasuri methi. Cook for 5 minutes.",
      "Serve hot with naan."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A creamy and rich restaurant-style chicken tikka masala that's perfect for special occasions.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 100,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "cumin", "cream", "oil", "salt"],
    searchKeywords: ["chicken tikka masala", "tikka masala", "creamy chicken", "pakistani chicken", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Butter Masala",
    image: "chicken-butter-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - boneless, cut into cubes",
      "2 onions - chopped small",
      "2 tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili powder",
      "1/2 cup cream",
      "2 tablespoons butter",
      "1 teaspoon kasuri methi (dried fenugreek leaves)",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put butter in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add tomato puree and cook for 6-7 minutes until the butter separates.",
      "Add red chili powder and salt. Mix well.",
      "Add chicken and cook for 15 minutes.",
      "Add cream and kasuri methi. Cook for 5 minutes.",
      "Serve with naan."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A rich and indulgent creamy butter chicken that's perfect for a royal dining experience.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 100,
    baseServings: 4,
    calories: 470,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "cumin", "cream", "butter", "salt"],
    searchKeywords: ["chicken butter masala", "butter chicken", "creamy chicken", "pakistani chicken", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Lababdar",
    image: "chicken-lababdar.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "2 onions - chopped small",
      "2 tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/4 cup cream",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates.",
      "Add red chili powder and salt. Cook for 15 minutes.",
      "Add cream and garam masala. Cook for 5 minutes.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A rich and creamy chicken lababdar that's perfect for a royal dining experience.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 95,
    baseServings: 4,
    calories: 440,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "cumin", "cream", "oil", "salt"],
    searchKeywords: ["chicken lababdar", "creamy chicken", "pakistani chicken", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Kolhapuri",
    image: "chicken-kolhapuri.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "2 onions - chopped small",
      "2 tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "2 teaspoons red chili powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed",
      "1 tablespoon grated coconut"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add chopped onions and fry for 6-7 minutes until brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add chopped tomatoes and cook for 6-7 minutes until soft.",
      "Add red chili powder, turmeric powder, garam masala, salt, and grated coconut. Mix well.",
      "Add 1/2 cup water and cook for 20 minutes.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A spicy Kolhapuri-style chicken curry with coconut, perfect for those who love bold and intense flavors.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 400,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "coconut", "oil", "salt"],
    searchKeywords: ["chicken kolhapuri", "spicy chicken", "pakistani chicken", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Oven Roasted Chicken",
    image: "oven-roasted-chicken.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 whole chicken",
      "1 cup yogurt - beaten until smooth",
      "2 tablespoons ginger-garlic paste",
      "2 teaspoons red chili powder",
      "1 teaspoon turmeric powder",
      "1 teaspoon garam masala",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "2 tablespoons lemon juice",
      "2 tablespoons cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Make small cuts on the chicken with a knife.",
      "Mix all ingredients together to make a marinade.",
      "Put the chicken in the marinade and coat well. Keep in the fridge for 4 hours.",
      "Heat the oven to 180°C (350°F).",
      "Put the chicken in a baking tray.",
      "Roast for 45-50 minutes, brushing with oil every now and then.",
      "Let it rest for 10 minutes before cutting.",
      "Serve with salad."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A perfectly roasted whole chicken that's juicy, flavorful, and perfect for special occasions.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 100,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "lemon", "oil", "salt"],
    searchKeywords: ["oven roasted chicken", "roast chicken", "whole chicken", "pakistani roast", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Tandoori Chicken",
    image: "tandoori-chicken.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 whole chicken",
      "1 cup yogurt - beaten until smooth",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons tandoori masala powder",
      "2 teaspoons red chili powder",
      "1 teaspoon turmeric powder",
      "2 tablespoons lemon juice",
      "2 tablespoons cooking oil",
      "Salt as needed",
      "Orange food color (optional)"
    ],
    stepsRaw: [
      "Make deep cuts on the chicken with a knife.",
      "Mix all ingredients together to make a marinade.",
      "Put the chicken in the marinade and coat well. Keep in the fridge for 6 hours.",
      "Heat the oven to 200°C (400°F).",
      "Put the chicken on a wire rack with a tray underneath.",
      "Bake for 30-35 minutes, turning once.",
      "Brush with oil and grill for 5 minutes for a charred look.",
      "Serve with mint sauce."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A classic tandoori chicken with a vibrant red color and smoky flavor, perfect for parties.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 100,
    baseServings: 4,
    calories: 440,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "lemon", "oil", "salt"],
    searchKeywords: ["tandoori chicken", "classic tandoori", "pakistani tandoori", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Roast with Gravy",
    image: "chicken-roast-with-gravy.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 whole chicken",
      "2 onions - sliced thin",
      "2 tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili powder",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Roast the chicken in the oven until golden brown.",
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add sliced onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and tomatoes. Cook until soft.",
      "Add red chili powder and salt. Mix well.",
      "Add the roasted chicken and 1 cup of water.",
      "Cook for 15 minutes on low heat.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A delicious roasted chicken served in a flavorful gravy, perfect for a hearty meal.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 100,
    baseServings: 4,
    calories: 460,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "cumin", "oil", "salt"],
    searchKeywords: ["chicken roast with gravy", "roast chicken", "gravy chicken", "pakistani roast", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Boneless Curry",
    image: "chicken-boneless-curry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless chicken - cut into cubes",
      "2 onions - chopped small",
      "2 tomatoes - blended into smooth puree",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken cubes and fry until the chicken turns white.",
      "Add tomato puree and cook for 6-7 minutes until the oil separates.",
      "Add turmeric, red chili powder, and salt. Mix well.",
      "Cook for 15 minutes.",
      "Add garam masala and serve."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A quick and easy boneless chicken curry that's perfect for a busy weekday dinner.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "cumin", "oil", "salt"],
    searchKeywords: ["chicken boneless curry", "boneless chicken", "easy chicken", "pakistani chicken", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Malai Boti",
    image: "chicken-malai-boti.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless chicken - cut into cubes",
      "1/2 cup cream",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons green chili paste",
      "1 teaspoon white pepper powder",
      "1 teaspoon garam masala",
      "1 tablespoon lemon juice",
      "2 tablespoons cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Mix all ingredients except chicken in a bowl.",
      "Add chicken and coat well. Keep in the fridge for 2 hours.",
      "Put oil in a pan on medium heat. Add the chicken.",
      "Cook until the chicken is done.",
      "Serve hot with naan."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Creamy and tender chicken malai boti that's perfect as an appetizer or main course with naan.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 90,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "cream", "green chili", "lemon", "oil", "salt"],
    searchKeywords: ["chicken malai boti", "malai boti", "creamy chicken", "pakistani chicken", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Kali Mirch",
    image: "chicken-kali-mirch.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless chicken - cut into cubes",
      "2 onions - chopped small",
      "2 tablespoons ginger-garlic paste",
      "2 tablespoons black pepper - crushed",
      "1 teaspoon cumin seeds",
      "1/2 cup yogurt - beaten until smooth",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add yogurt and crushed black pepper. Mix well.",
      "Cook for 15 minutes.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A bold and peppery black pepper chicken that's perfect for those who love intense flavors.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "yogurt", "cumin", "oil", "salt"],
    searchKeywords: ["chicken kali mirch", "black pepper chicken", "peppery chicken", "pakistani chicken", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Hariyali",
    image: "chicken-hariyali.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless chicken - cut into cubes",
      "1 cup mint and coriander chutney",
      "2 tablespoons ginger-garlic paste",
      "2 green chilies - whole",
      "1 teaspoon cumin seeds",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Grind mint, coriander, and green chilies together to make a paste.",
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chicken and fry for 5 minutes.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add the green paste and salt. Mix well.",
      "Cook for 15 minutes.",
      "Serve with naan."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A vibrant green masala chicken that's fresh, herby, and packed with flavor.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "mint", "green chili", "cumin", "oil", "salt"],
    searchKeywords: ["chicken hariyali", "green chicken", "herby chicken", "pakistani chicken", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Handi Traditional",
    image: "chicken-handi-traditional.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "1 cup yogurt - beaten until smooth",
      "2 onions - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add turmeric, red chili powder, and salt. Mix well.",
      "Add yogurt and cook on low heat for 25 minutes.",
      "Add garam masala and serve."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A traditional chicken handi with a perfect balance of spices and creamy yogurt gravy.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 400,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "onion", "cumin", "oil", "salt"],
    searchKeywords: ["chicken handi", "traditional handi", "pakistani chicken", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Handi with Cream",
    image: "chicken-handi-with-cream.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "1 cup yogurt - beaten until smooth",
      "1/4 cup cream",
      "2 onions - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add turmeric, red chili powder, and salt. Mix well.",
      "Add yogurt and cook for 20 minutes.",
      "Add cream and cook for 5 minutes on low heat.",
      "Serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A creamy and rich chicken handi with the addition of cream for extra indulgence.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 95,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "cream", "onion", "cumin", "oil", "salt"],
    searchKeywords: ["creamy chicken handi", "handi with cream", "pakistani chicken", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Spicy Chicken Handi",
    image: "spicy-chicken-handi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "1 cup yogurt - beaten until smooth",
      "2 onions - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "3 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until golden brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry for 5 minutes.",
      "Add turmeric, red chili powder, and salt. Mix well.",
      "Add yogurt and cook for 25 minutes.",
      "Add garam masala and serve."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "An extra spicy chicken handi for heat lovers, packed with bold and intense flavors.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 410,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "yogurt", "onion", "cumin", "oil", "salt"],
    searchKeywords: ["spicy chicken handi", "hot chicken handi", "pakistani chicken", "non vegetarian", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Bhuna",
    image: "chicken-bhuna.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "2 onions - chopped small",
      "2 tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry until browned.",
      "Add chopped tomatoes and cook until they become dry.",
      "Add turmeric, red chili powder, coriander powder, and salt. Mix well.",
      "Cook on low heat until the oil separates and the chicken is dry.",
      "Serve hot with naan."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A dry bhuna chicken where the masala clings to every piece, perfect with naan or roti.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "cumin", "oil", "salt"],
    searchKeywords: ["chicken bhuna", "bhuna chicken", "dry chicken", "pakistani chicken", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Bhuna Masala",
    image: "chicken-bhuna-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg chicken - cut into pieces",
      "2 onions - chopped small",
      "2 tomatoes - chopped small",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup cooking oil",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put oil in a pan on medium heat. Add cumin seeds and cook for 30 seconds until they pop.",
      "Add chopped onions and fry for 6-7 minutes until brown.",
      "Add ginger-garlic paste and cook for 2 minutes until it smells good.",
      "Add chicken and fry until browned.",
      "Add chopped tomatoes and cook until they become dry.",
      "Add turmeric, red chili powder, and salt. Mix well.",
      "Cook on low heat for 20 minutes.",
      "Add garam masala and serve."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A spicy and aromatic chicken bhuna masala that's perfect for those who love dry curries.",
    category: "Lunch",
    subCategory: "pure-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "onion", "tomato", "cumin", "oil", "salt"],
    searchKeywords: ["chicken bhuna masala", "bhuna masala", "spicy dry chicken", "pakistani chicken", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
];

async function migrateRecipes() {
  try {
    console.log('Connecting to MongoDB');
    
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) {
      throw new Error('MongoDB URI not found');
    }
    
    await mongoose.connect(mongoURI, { 
      serverSelectionTimeoutMS: 10000, 
      family: 4 
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();