const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
require('dotenv').config({ path: '../.env' });
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');

const recipesToMigrate = [
  {
    title: "Mutton Karahi",
    image: "http://localhost:5000/uploads/mutton-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones, medium pieces)",
      "4 tomatoes (chopped)",
      "2 green chilies (cut from middle)",
      "1 tablespoon ginger (cut into thin strips)",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili flakes",
      "1 teaspoon black pepper",
      "1 teaspoon garam masala",
      "½ cup oil or ghee",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a karahi (wok) on high flame",
      "Add mutton and fry until it turns brown (10-12 minutes)",
      "Add ginger strips and green chilies, fry for 2 minutes",
      "Add tomatoes and cook until they become soft and mushy (8-10 minutes)",
      "Add cumin, red chili flakes, black pepper and salt",
      "Cover and cook on low flame for 45-50 minutes until mutton is soft",
      "Sprinkle garam masala and garnish with coriander",
      "Serve hot with naan"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A famous Pakistani mutton curry made in a karahi with tomatoes and green chilies.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "karahi", "tomato", "ginger", "green chili", "cumin", "red chili flakes", "black pepper", "garam masala"],
    searchKeywords: ["mutton karahi", "karahi mutton", "pakistani mutton karahi"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Handi",
    image: "http://localhost:5000/uploads/mutton-handi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (chopped)",
      "1 cup yogurt (beaten well)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "½ cup oil or ghee",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a heavy bottom pot (handi)",
      "Add cumin seeds and onions, fry until golden brown",
      "Add ginger-garlic paste and cook for 2 minutes",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add tomatoes and cook until soft",
      "Add turmeric, red chili and salt",
      "Turn flame to low and slowly add yogurt while stirring (so it doesn't curdle)",
      "Add 1 cup water, cover and cook on low flame for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve hot with naan or roti"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A rich mutton curry made in a handi (clay pot) with yogurt gravy.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 160,
    baseServings: 4,
    calories: 500,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "handi", "yogurt", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton handi", "handi mutton", "pakistani mutton handi"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Qorma",
    image: "http://localhost:5000/uploads/mutton-korma.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (sliced)",
      "1 cup yogurt (beaten well)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "½ cup oil or ghee",
      "Salt as needed",
      "Fried onions for garnish",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, fry onions until golden brown",
      "Take out half of the fried onions and keep aside for garnish",
      "Add ginger-garlic paste to the remaining onions and cook for 2 minutes",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add spices and salt",
      "Turn flame to low and slowly add yogurt while stirring",
      "Add 1 cup water, cover and cook for 45-50 minutes until mutton is soft",
      "Sprinkle garam masala",
      "Garnish with fried onions and coriander",
      "Serve with naan or rice"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A royal mutton curry from Mughlai cuisine with yogurt and fried onions.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 170,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "qorma", "yogurt", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton qorma", "qorma mutton", "pakistani mutton qorma"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Rogan Josh",
    image: "http://localhost:5000/uploads/mutton-rogan-josh.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (blended into paste)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1 teaspoon fennel powder",
      "½ cup oil or ghee",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions, fry until golden",
      "Add ginger-garlic paste and cook for 2 minutes",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add blended tomatoes and cook until oil separates from the gravy",
      "Add turmeric, red chili, fennel powder and salt",
      "Add 1.5 cups water, cover and cook for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve hot with naan or rice"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A Kashmiri-style mutton curry with aromatic spices and red color.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 155,
    baseServings: 4,
    calories: 490,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "rogan josh", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "fennel", "garam masala"],
    searchKeywords: ["mutton rogan josh", "rogan josh mutton", "kashmiri mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Do Pyaz",
    image: "http://localhost:5000/uploads/mutton-do-pyaz.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "3 onions (sliced - divided into two parts)",
      "2 tomatoes (chopped)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and half of the onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add tomatoes and cook until soft",
      "Add spices and salt, mix well",
      "Add 1.5 cups water, cover and cook for 45-50 minutes",
      "Add remaining onions and cook for 10 more minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or roti"
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A tasty mutton curry with double the amount of onions (do pyaza).",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 145,
    baseServings: 4,
    calories: 470,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "do pyaza", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["mutton do pyaza", "do pyaza mutton", "pakistani mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Bhuna",
    image: "http://localhost:5000/uploads/mutton-bhuna.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (chopped)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden brown",
      "Add ginger-garlic paste and cook for 2 minutes",
      "Add mutton and fry on high flame until well-browned (10-12 minutes)",
      "Add tomatoes and cook until oil separates from the gravy",
      "Add spices and salt, mix well",
      "Cook on low flame for 10-15 minutes to dry roast (bhuna) until masala coats the mutton",
      "Add 1 cup water, cover and cook for 40-45 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or roti"
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A dry-style mutton curry with rich, dark masala (bhuna means dry roasted).",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 155,
    baseServings: 4,
    calories: 490,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "bhuna", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["mutton bhuna", "bhuna mutton", "pakistani mutton bhuna"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "White Mutton Karahi",
    image: "http://localhost:5000/uploads/white-mutton-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "1 cup yogurt (beaten well)",
      "2 green chilies (cut from middle)",
      "1 tablespoon ginger (cut into thin strips)",
      "1 teaspoon cumin seeds",
      "1 teaspoon white pepper",
      "1 teaspoon black pepper",
      "½ cup oil or ghee",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a karahi (wok)",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add ginger and green chilies, fry for 2 minutes",
      "Turn flame to low and slowly add yogurt while stirring",
      "Add white pepper, black pepper, cumin and salt",
      "Cover and cook on low flame for 45-50 minutes until mutton is soft",
      "Garnish with coriander and serve with naan"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A white-colored mutton karahi made with yogurt and white pepper (no tomatoes).",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 155,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "white karahi", "yogurt", "ginger", "green chili", "cumin", "white pepper", "black pepper"],
    searchKeywords: ["white mutton karahi", "white karahi", "pakistani mutton karahi"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Peshawari Mutton Karahi",
    image: "http://localhost:5000/uploads/peshawari-mutton-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "4 tomatoes (chopped)",
      "2 green chilies (cut from middle)",
      "1 tablespoon ginger (cut into thin strips)",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili flakes",
      "1 teaspoon black pepper",
      "½ cup oil or ghee",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a karahi (wok)",
      "Add mutton and fry until well-browned (10-12 minutes)",
      "Add ginger and green chilies, fry for 2 minutes",
      "Add tomatoes and cook until they become soft and mushy (8-10 minutes)",
      "Add cumin, red chili flakes, black pepper and salt",
      "Cover and cook on low flame for 45-50 minutes",
      "Garnish with coriander and serve with naan"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A Peshawari-style mutton karahi with simple, bold flavors (just tomatoes and spices).",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 470,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "peshawari karahi", "tomato", "ginger", "green chili", "cumin", "red chili flakes", "black pepper"],
    searchKeywords: ["peshawari mutton karahi", "peshawari karahi", "pakistani mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Spicy Mutton Karahi",
    image: "http://localhost:5000/uploads/spicy-mutton-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "4 tomatoes (chopped)",
      "4 green chilies (cut from middle)",
      "1 tablespoon ginger (cut into thin strips)",
      "1 teaspoon cumin seeds",
      "2 teaspoons red chili powder",
      "1 teaspoon red chili flakes",
      "1 teaspoon black pepper",
      "½ cup oil or ghee",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a karahi (wok)",
      "Add mutton and fry until well-browned (10-12 minutes)",
      "Add ginger and green chilies, fry for 2 minutes",
      "Add tomatoes and cook until soft and mushy",
      "Add cumin, red chili powder, red chili flakes, black pepper and salt",
      "Cover and cook on low flame for 45-50 minutes",
      "Garnish with coriander and serve with naan"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "An extra spicy mutton karahi for people who love very hot food.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "spicy karahi", "tomato", "ginger", "green chili", "cumin", "red chili powder", "red chili flakes", "black pepper"],
    searchKeywords: ["spicy mutton karahi", "hot mutton karahi", "pakistani mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Masala",
    image: "http://localhost:5000/uploads/mutton-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (chopped)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add tomatoes and cook until soft",
      "Add turmeric, red chili, coriander powder and salt",
      "Add 1.5 cups water, cover and cook for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or roti"
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A simple and tasty mutton curry with everyday spices.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 140,
    baseServings: 4,
    calories: 460,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "masala", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["mutton masala", "masala mutton", "pakistani mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Tikka Masala",
    image: "http://localhost:5000/uploads/mutton-tikka-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless mutton (cut into cubes)",
      "2 onions (finely chopped)",
      "2 tomatoes (blended into paste)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1 teaspoon dried fenugreek leaves (kasuri methi)",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add blended tomatoes and cook until oil separates",
      "Add spices and salt, mix well",
      "Add 1 cup water, cover and cook for 40-45 minutes",
      "Crush dried fenugreek leaves between your palms and add, cook for 5 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or rice"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A restaurant-style mutton tikka masala with rich tomato gravy.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 170,
    baseServings: 4,
    calories: 510,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "tikka masala", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "kasuri methi"],
    searchKeywords: ["mutton tikka masala", "tikka masala mutton", "restaurant mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Butter Masala",
    image: "http://localhost:5000/uploads/mutton-butter-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless mutton (cut into cubes)",
      "2 onions (finely chopped)",
      "2 tomatoes (blended into paste)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons butter",
      "2 tablespoons heavy cream",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil and butter, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add blended tomatoes and cook until oil separates",
      "Add turmeric, red chili and salt",
      "Add 1 cup water, cover and cook for 40-45 minutes",
      "Add cream and garam masala, cook on low flame for 5 minutes",
      "Garnish with coriander and serve with naan"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A rich and creamy mutton curry with butter and cream.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 180,
    baseServings: 4,
    calories: 540,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "butter masala", "butter", "cream", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton butter masala", "butter mutton", "creamy mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Lababdar",
    image: "http://localhost:5000/uploads/mutton-lababdar.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless mutton (cut into cubes)",
      "2 onions (finely chopped)",
      "2 tomatoes (blended into paste)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons butter",
      "2 tablespoons heavy cream",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil and butter, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add blended tomatoes and cook until oil separates",
      "Add turmeric, red chili and salt",
      "Add 1 cup water, cover and cook for 40-45 minutes",
      "Add cream and garam masala, cook on low flame for 5 minutes",
      "Garnish with coriander and serve with naan"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A rich and creamy mutton lababdar with butter and cream.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 180,
    baseServings: 4,
    calories: 540,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "lababdar", "butter", "cream", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton lababdar", "lababdar mutton", "creamy mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Kolhapuri",
    image: "http://localhost:5000/uploads/mutton-kolhapuri.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (chopped)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1 teaspoon Kolhapuri masala (special spice mix)",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add tomatoes and cook until soft",
      "Add turmeric, red chili, coriander powder and salt",
      "Add Kolhapuri masala and 1.5 cups water",
      "Cover and cook for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or rice"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A spicy Kolhapuri-style mutton curry with special masala from Maharashtra.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 155,
    baseServings: 4,
    calories: 490,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "kolhapuri", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala", "kolhapuri masala"],
    searchKeywords: ["mutton kolhapuri", "kolhapuri mutton", "spicy mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Kashmiri Rogan Josh",
    image: "http://localhost:5000/uploads/kashmiri-rogan-josh.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (blended into paste)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons Kashmiri red chili powder (for red color)",
      "1 teaspoon fennel powder",
      "1 teaspoon garam masala",
      "½ cup oil or ghee",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add blended tomatoes and cook until oil separates",
      "Add turmeric, Kashmiri red chili, fennel powder and salt",
      "Add 1.5 cups water, cover and cook for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or rice"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "An authentic Kashmiri-style rogan josh with fennel and Kashmiri red chili.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 160,
    baseServings: 4,
    calories: 500,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "kashmiri rogan josh", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "kashmiri red chili", "fennel", "garam masala"],
    searchKeywords: ["kashmiri rogan josh", "rogan josh", "kashmiri mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Easy Rogan Josh",
    image: "http://localhost:5000/uploads/easy-rogan-josh.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (blended into paste)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon fennel powder",
      "1 teaspoon garam masala",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add blended tomatoes and cook until oil separates",
      "Add turmeric, red chili, fennel powder and salt",
      "Add 1.5 cups water, cover and cook for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or rice"
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "An easy version of the classic rogan josh with simple ingredients.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "easy rogan josh", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "fennel", "garam masala"],
    searchKeywords: ["easy rogan josh", "simple mutton curry", "pakistani mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Pressure Cooker Rogan Josh",
    image: "http://localhost:5000/uploads/pressure-cooker-rogan-josh.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (blended into paste)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon fennel powder",
      "1 teaspoon garam masala",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a pressure cooker, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add blended tomatoes and cook until oil separates",
      "Add turmeric, red chili, fennel powder and salt",
      "Add 1.5 cups water, close the pressure cooker lid",
      "Cook on medium flame for 4-5 whistles",
      "Let the pressure release naturally, then open the lid",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or rice"
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A quick pressure cooker version of the classic rogan josh.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "pressure cooker rogan josh", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "fennel", "garam masala"],
    searchKeywords: ["pressure cooker rogan josh", "quick mutton curry", "instant pot mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Kofta Curry",
    image: "http://localhost:5000/uploads/mutton-kofta-curry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "1 onion (finely chopped)",
      "2 green chilies (finely chopped)",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "2 tablespoons gram flour (besan)",
      "Oil for frying",
      "For Gravy: 2 onions, 2 tomatoes, 2 tablespoons ginger-garlic paste, spices",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "For koftas: Mix mutton mince, onion, green chilies, ginger-garlic paste, spices, gram flour and salt",
      "Shape the mixture into small balls",
      "Deep fry the koftas until golden brown, take them out and keep aside",
      "For gravy: Heat oil in a pan, add onions and fry until golden",
      "Add ginger-garlic paste and cook for 2 minutes",
      "Add tomatoes and cook until soft",
      "Add spices and salt, cook until oil separates from the gravy",
      "Add 2 cups water and bring to a boil",
      "Add the fried koftas and cook on low flame for 8-10 minutes",
      "Garnish with coriander and serve with naan or rice"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Delicious mutton kofta curry with soft, juicy meatballs in a rich gravy.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 170,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "kofta", "meatballs", "onion", "green chili", "ginger", "garlic", "cumin", "coriander", "red chili", "besan"],
    searchKeywords: ["mutton kofta curry", "kofta curry", "mutton meatball curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Kofta in Yogurt Gravy",
    image: "http://localhost:5000/uploads/mutton-kofta-in-yogurt-gravy.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "1 onion (finely chopped)",
      "2 green chilies (finely chopped)",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "2 tablespoons gram flour (besan)",
      "Oil for frying",
      "For Gravy: 1 cup yogurt, 2 onions, 2 tablespoons ginger-garlic paste, spices",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Mix mutton mince, onion, green chilies, ginger-garlic paste, spices, gram flour and salt",
      "Shape into small balls and deep fry until golden brown",
      "For gravy: Heat oil in a pan, fry onions until golden",
      "Add ginger-garlic paste and cook for 2 minutes",
      "Turn flame to low and slowly add yogurt while stirring",
      "Add spices and salt, cook for 5 minutes",
      "Add 1 cup water and bring to a boil",
      "Add the fried koftas and cook on low flame for 8-10 minutes",
      "Garnish with coriander and serve"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Mutton kofta in a rich and tangy yogurt gravy.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 175,
    baseServings: 4,
    calories: 530,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "kofta", "yogurt", "gravy", "onion", "ginger", "garlic", "cumin", "coriander", "red chili", "besan"],
    searchKeywords: ["mutton kofta yogurt gravy", "yogurt kofta curry", "mutton meatball curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Nargisi Kofta",
    image: "http://localhost:5000/uploads/nargisi-kofta.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "4 hard-boiled eggs (peeled)",
      "1 onion (finely chopped)",
      "2 green chilies (finely chopped)",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "2 tablespoons gram flour (besan)",
      "Oil for frying",
      "For Gravy: 2 onions, 2 tomatoes, 2 tablespoons ginger-garlic paste, spices",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Mix mutton mince, onion, green chilies, ginger-garlic paste, spices, gram flour and salt",
      "Take each boiled egg and wrap the mince mixture around it to make a ball",
      "Deep fry the koftas until golden brown, take them out and keep aside",
      "For gravy: Heat oil in a pan, fry onions until golden",
      "Add ginger-garlic paste and cook for 2 minutes",
      "Add tomatoes and cook until soft",
      "Add spices and salt, cook until oil separates",
      "Add 2 cups water and bring to a boil",
      "Add the fried koftas and cook on low flame for 8-10 minutes",
      "Garnish with coriander and serve with naan or rice"
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "Royal nargisi kofta - mutton mince wrapped around boiled eggs (like Scotch eggs).",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 180,
    baseServings: 4,
    calories: 540,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "nargisi kofta", "eggs", "onion", "green chili", "ginger", "garlic", "cumin", "coriander", "red chili", "besan"],
    searchKeywords: ["nargisi kofta", "egg kofta", "mutton egg kofta"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Malai Kofta",
    image: "http://localhost:5000/uploads/malai-kofta.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "1 cup paneer (grated)",
      "1 onion (finely chopped)",
      "2 green chilies (finely chopped)",
      "1 tablespoon ginger-garlic paste",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon red chili powder",
      "2 tablespoons gram flour (besan)",
      "Oil for frying",
      "For Gravy: 2 onions, 2 tomatoes, 2 tablespoons ginger-garlic paste, 1/2 cup cream",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Mix mutton mince, paneer, onion, green chilies, ginger-garlic paste, spices, gram flour and salt",
      "Shape into small balls and deep fry until golden brown",
      "For gravy: Heat oil in a pan, fry onions until golden",
      "Add ginger-garlic paste and cook for 2 minutes",
      "Add tomatoes and cook until soft",
      "Add spices and salt, cook until oil separates",
      "Add 1 cup water and bring to a boil",
      "Add cream and the fried koftas, cook on low flame for 8-10 minutes",
      "Garnish with coriander and serve with naan"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Creamy malai kofta made with mutton mince and paneer in a rich gravy.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 185,
    baseServings: 4,
    calories: 550,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "malai kofta", "paneer", "cream", "onion", "green chili", "ginger", "garlic", "cumin", "coriander", "red chili", "besan"],
    searchKeywords: ["malai kofta", "creamy kofta", "mutton paneer kofta"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Rara",
    image: "http://localhost:5000/uploads/mutton-rara.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "250g mutton mince",
      "2 onions (finely chopped)",
      "2 tomatoes (chopped)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton pieces and fry until brown (8-10 minutes)",
      "Add mutton mince and fry until its color changes (5-6 minutes)",
      "Add tomatoes and cook until soft",
      "Add spices and salt, mix well",
      "Add 1.5 cups water, cover and cook for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or roti"
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A rich mutton rara with both bone-in mutton pieces and mince together.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 175,
    baseServings: 4,
    calories: 530,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "rara", "mince", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["mutton rara", "rara mutton", "pakistani mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Rara Masala",
    image: "http://localhost:5000/uploads/mutton-rara-masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "250g mutton mince",
      "2 onions (finely chopped)",
      "2 tomatoes (blended into paste)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton pieces and fry until brown (8-10 minutes)",
      "Add mutton mince and fry until its color changes",
      "Add blended tomatoes and cook until oil separates",
      "Add spices and salt, mix well",
      "Add 1.5 cups water, cover and cook for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or roti"
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A spicy mutton rara masala with rich tomato gravy and both pieces and mince.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 175,
    baseServings: 4,
    calories: 530,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "rara masala", "mince", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton rara masala", "rara mutton", "spicy mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Hyderabadi Mutton",
    image: "http://localhost:5000/uploads/hyderabadi-mutton.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (chopped)",
      "1 cup yogurt (beaten well)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add tomatoes and cook until soft",
      "Add spices and salt",
      "Turn flame to low and slowly add yogurt while stirring",
      "Add 1 cup water, cover and cook for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or rice"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A Hyderabadi-style mutton curry with yogurt and aromatic spices.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 155,
    baseServings: 4,
    calories: 490,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "hyderabadi", "yogurt", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["hyderabadi mutton", "hyderabadi curry", "pakistani mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Punjabi Mutton",
    image: "http://localhost:5000/uploads/punjabi-mutton.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (chopped)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "2 tablespoons butter",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil and butter, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add tomatoes and cook until soft",
      "Add spices and salt, mix well",
      "Add 1.5 cups water, cover and cook for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or roti"
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A rich Punjabi-style mutton curry with butter.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 160,
    baseServings: 4,
    calories: 510,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "punjabi", "butter", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["punjabi mutton", "punjabi curry", "pakistani mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chettinad Mutton",
    image: "http://localhost:5000/uploads/chettinad-mutton.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (chopped)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1 teaspoon fennel powder",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add tomatoes and cook until soft",
      "Add turmeric, red chili, coriander, fennel powder and salt",
      "Add 1.5 cups water, cover and cook for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with rice or parotta"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A Chettinad-style mutton curry with aromatic spices from Tamil Nadu.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 155,
    baseServings: 4,
    calories: 490,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "chettinad", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "fennel", "garam masala"],
    searchKeywords: ["chettinad mutton", "chettinad curry", "south indian mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Goan Mutton Curry",
    image: "http://localhost:5000/uploads/goan-mutton-curry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (with bones)",
      "2 onions (finely chopped)",
      "2 tomatoes (chopped)",
      "1 cup coconut milk",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "2 tablespoons vinegar",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton and fry until brown (8-10 minutes)",
      "Add tomatoes and cook until soft",
      "Add spices and salt, mix well",
      "Add 1 cup water, cover and cook for 40-45 minutes",
      "Add coconut milk and vinegar, cook on low flame for 10 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with rice"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A Goan-style mutton curry with coconut milk and vinegar from Goa.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 160,
    baseServings: 4,
    calories: 510,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "goan", "coconut milk", "vinegar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["goan mutton curry", "goan curry", "coconut mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Chops Curry",
    image: "http://localhost:5000/uploads/mutton-chops-curry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton chops",
      "2 onions (finely chopped)",
      "2 tomatoes (chopped)",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "½ cup oil",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds and onions",
      "Fry until golden, add ginger-garlic paste",
      "Add mutton chops and fry until brown (8-10 minutes)",
      "Add tomatoes and cook until soft",
      "Add spices and salt, mix well",
      "Add 1.5 cups water, cover and cook for 45-50 minutes",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or rice"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A delicious mutton chops curry with a rich spicy gravy.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 170,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton chops", "chops curry", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["mutton chops curry", "chops curry", "pakistani mutton chops"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Chops Karahi",
    image: "http://localhost:5000/uploads/mutton-chops-karahi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton chops",
      "4 tomatoes (chopped)",
      "2 green chilies (cut from middle)",
      "1 tablespoon ginger (cut into thin strips)",
      "1 teaspoon cumin seeds",
      "1 teaspoon red chili flakes",
      "1 teaspoon black pepper",
      "½ cup oil or ghee",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a karahi (wok)",
      "Add mutton chops and fry until well-browned (10-12 minutes)",
      "Add ginger and green chilies, fry for 2 minutes",
      "Add tomatoes and cook until soft and mushy",
      "Add cumin, red chili flakes, black pepper and salt",
      "Cover and cook on low flame for 45-50 minutes",
      "Garnish with coriander and serve with naan"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Mutton chops cooked in a karahi with tomatoes and green chilies.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 170,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton chops", "karahi", "tomato", "ginger", "green chili", "cumin", "red chili flakes", "black pepper"],
    searchKeywords: ["mutton chops karahi", "chops karahi", "pakistani mutton chops"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Grilled Mutton Chops",
    image: "http://localhost:5000/uploads/grilled-mutton-chops.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton chops",
      "2 tablespoons ginger-garlic paste",
      "1 teaspoon red chili powder",
      "1 teaspoon cumin powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "2 tablespoons yogurt",
      "1 tablespoon lemon juice",
      "Salt as needed",
      "2 tablespoons oil for brushing"
    ],
    stepsRaw: [
      "Mix all ingredients (except oil) in a bowl",
      "Marinate the mutton chops for 2-3 hours (or keep overnight for better taste)",
      "Heat a grill or pan",
      "Brush the chops with oil",
      "Grill each side for 6-8 minutes until nicely charred and cooked",
      "Serve hot with mint chutney and salad"
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Grilled mutton chops with aromatic spices - perfect for barbecues.",
    category: "Lunch",
    subCategory: "pure-mutton",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 180,
    baseServings: 4,
    calories: 500,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton chops", "grilled", "yogurt", "lemon", "ginger", "garlic", "red chili", "cumin", "coriander", "garam masala"],
    searchKeywords: ["grilled mutton chops", "mutton chops", "grilled chops"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
];

async function migrateRecipes() {
  try {
    console.log('Connecting to MongoDB');
    
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) {
      throw new Error('MongoDB URI not found');
    }
    
    await mongoose.connect(mongoURI, { 
      serverSelectionTimeoutMS: 10000, 
      family: 4 
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();