const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
  {
    title: "Chicken Noodles",
    image: "chicken-maggi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 packet Maggi noodles",
      "½ cup boiled chicken, shredded",
      "1½ cups water",
      "Maggi tastemaker (masala)",
      "1 tablespoon oil or butter",
      "¼ cup chopped vegetables (carrot, peas, corn)",
      "½ teaspoon black pepper",
      "1 tablespoon chopped coriander"
    ],
    stepsRaw: [
      "Boil 1½ cups water in a small pan.",
      "Add Maggi noodles and masala to boiling water.",
      "Add chopped vegetables and cook for 2 minutes.",
      "Add shredded chicken and mix well.",
      "Cook for another 2-3 minutes until noodles are soft.",
      "Add oil or butter and black pepper.",
      "Mix everything well and cook for 1 minute.",
      "Garnish with chopped coriander.",
      "Serve hot immediately."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "Quick and tasty Maggi noodles with chicken and vegetables - ready in just 5 minutes. A perfect meal for when you are hungry and want something fast.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 60,
    baseServings: 1,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["maggi noodles", "chicken", "water", "oil", "butter", "vegetables", "carrot", "peas", "corn", "black pepper", "coriander"],
    searchKeywords: ["chicken maggi", "quick noodles", "5 minute meal", "maggi recipe", "quick chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Egg Paratha",
    image: "anda-paratha.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 ready-made parathas",
      "2 eggs",
      "1 small onion, finely chopped",
      "1 green chili, chopped",
      "2 tablespoons chopped coriander",
      "Salt to taste",
      "¼ teaspoon black pepper",
      "2 tablespoons oil or ghee"
    ],
    stepsRaw: [
      "Heat a frying pan on medium heat.",
      "Add 1 tablespoon oil and put one paratha in pan.",
      "Cook for 1 minute until it becomes slightly crispy.",
      "In a bowl, beat one egg with salt and pepper.",
      "Add half of chopped onion, chili, and coriander to egg.",
      "Pour egg mixture over the paratha in pan.",
      "Carefully flip the paratha to cook the egg side.",
      "Cook for 1-2 minutes until egg is fully cooked.",
      "Repeat with second paratha.",
      "Serve hot with ketchup or chutney."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "Quick and delicious egg paratha that is perfect for breakfast or any time you feel hungry. This is a favorite Pakistani breakfast dish.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "eggs", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 2,
    calories: 320,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["parathas", "eggs", "onion", "green chili", "coriander", "oil", "ghee"],
    searchKeywords: ["anda paratha", "egg paratha", "quick breakfast", "egg stuffed paratha", "paratha recipe"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Omelette Sandwich",
    image: "omelette-sandwich.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "4 slices of bread",
      "3 eggs",
      "1 small onion, finely chopped",
      "1 small tomato, chopped",
      "1 green chili, chopped (optional)",
      "2 tablespoons chopped coriander",
      "Salt to taste",
      "¼ teaspoon black pepper",
      "2 tablespoons butter or oil"
    ],
    stepsRaw: [
      "Break eggs into a bowl and beat well.",
      "Add onion, tomato, green chili, and coriander.",
      "Add salt and pepper, mix everything well.",
      "Heat butter or oil in frying pan on medium heat.",
      "Pour egg mixture into pan and spread evenly.",
      "Cook for 1-2 minutes until bottom is set.",
      "Place two bread slices on top of omelette.",
      "Carefully flip the omelette with bread slices attached.",
      "Cook for another 1-2 minutes until bread is toasted.",
      "Repeat with remaining bread and egg mixture.",
      "Cut sandwiches diagonally and serve hot."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "Protein-packed omelette sandwich that is ready in minutes. A perfect quick breakfast or snack for everyone in the family.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "eggs", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 40,
    baseServings: 2,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["bread", "eggs", "onion", "tomato", "green chili", "coriander", "butter", "oil"],
    searchKeywords: ["omlette sandwich", "egg sandwich", "quick sandwich", "breakfast sandwich", "protein sandwich"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cup Noodles ",
    image: "cup-noodles.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup instant noodles (any brand)",
      "Boiling water as needed",
      "Optional add-ons:",
      "2 tablespoons chopped spring onions",
      "½ teaspoon soy sauce",
      "¼ teaspoon chili flakes",
      "1 tablespoon sweet corn"
    ],
    stepsRaw: [
      "Open the cup noodles and take out the masala packet.",
      "Add masala powder to noodles in cup.",
      "Add spring onions and sweet corn if you want.",
      "Pour boiling water into cup up to the marked line.",
      "Add soy sauce and chili flakes if you like.",
      "Close the lid and let it sit for 3 minutes.",
      "After 3 minutes, stir well with fork.",
      "Add extra masala if needed.",
      "Enjoy directly from the cup."
    ],
    difficulty: "Easy",
    cookingTime: 3,
    isActive: true,
    isHalal: true,
    description: "Instant cup noodles that are ready in just 3 minutes. A perfect snack when you are in a hurry or too tired to cook.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["gluten", "wheat", "soy"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 1,
    calories: 280,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["instant noodles", "water", "spring onions", "soy sauce", "chili flakes", "sweet corn"],
    searchKeywords: ["cup noodles", "instant noodles", "quick noodles", "3 minute meal", "ramen"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Butter Toast with Jam",
    image: "toast-with-butter-and-jam.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 slices of bread",
      "2 tablespoons butter",
      "2 tablespoons fruit jam (any flavor)",
      "Pinch of cinnamon powder (optional)"
    ],
    stepsRaw: [
      "Take bread slices and spread butter evenly on one side.",
      "Heat a frying pan on medium heat.",
      "Place bread with butter side down in pan.",
      "Cook for 1-2 minutes until golden brown.",
      "Spread more butter on top side while cooking.",
      "Flip and cook other side for 1-2 minutes.",
      "Take out from pan and spread jam on one slice.",
      "Sprinkle cinnamon powder if you want.",
      "Put slices together or eat separately.",
      "Serve hot with tea or coffee."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "Crispy butter toast with fruit jam - a simple and satisfying breakfast or snack that everyone loves.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 1,
    calories: 220,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["bread", "butter", "fruit jam", "cinnamon"],
    searchKeywords: ["butter toast", "jam toast", "quick breakfast", "toast recipe", "simple toast"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Fruit Yogurt ",
    image: "fruit-raita.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup plain yogurt",
      "½ cup mixed fruits (apple, banana, grapes)",
      "1 tablespoon sugar or honey",
      "¼ teaspoon roasted cumin powder",
      "Pinch of salt",
      "1 tablespoon chopped nuts (optional)"
    ],
    stepsRaw: [
      "Take yogurt in a bowl and whisk until smooth.",
      "Add sugar or honey and mix well.",
      "Add roasted cumin powder and salt.",
      "Wash and chop fruits into small pieces.",
      "Add chopped fruits to yogurt mixture.",
      "Mix gently to coat fruits with yogurt.",
      "If using nuts, add them now.",
      "Chill in refrigerator for 15 minutes.",
      "Serve cold as side dish or dessert."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A refreshing yogurt and fruit dish that is perfect as a side dish or light dessert. Very cooling and healthy.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "nuts"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 2,
    calories: 120,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["yogurt", "apple", "banana", "grapes", "sugar", "honey", "cumin", "nuts"],
    searchKeywords: ["fruit raita", "yogurt fruit", "quick raita", "healthy snack", "indian side dish"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cornflakes with Milk",
    image: "cornflakes-with-milk.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup cornflakes",
      "1 cup milk (cold or warm)",
      "1 tablespoon sugar or honey (optional)",
      "½ banana, sliced (optional)",
      "¼ cup mixed berries (optional)"
    ],
    stepsRaw: [
      "Take a cereal bowl.",
      "Add 1 cup of cornflakes to bowl.",
      "If using fruits, add sliced banana and berries.",
      "Pour milk over cornflakes until just covered.",
      "Add sugar or honey if you want.",
      "Mix lightly and serve immediately.",
      "For warm version: warm the milk first.",
      "Eat immediately to keep cornflakes crunchy."
    ],
    difficulty: "Easy",
    cookingTime: 2,
    isActive: true,
    isHalal: true,
    description: "Classic cornflakes with milk - the quickest and easiest breakfast option. Great for busy mornings.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 1,
    calories: 180,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["cornflakes", "milk", "sugar", "honey", "banana", "berries"],
    searchKeywords: ["cornflakes with milk", "cereal breakfast", "quick breakfast", "easy breakfast", "morning cereal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Peanut Butter Banana Sandwich",
    image: "peanut-butter-sandwich.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 slices of bread",
      "2 tablespoons peanut butter",
      "1 teaspoon honey",
      "½ banana, sliced",
      "Pinch of cinnamon powder"
    ],
    stepsRaw: [
      "Toast bread slices until golden brown.",
      "Spread peanut butter evenly on warm toast.",
      "Drizzle honey over peanut butter.",
      "Arrange banana slices on top of peanut butter.",
      "Sprinkle cinnamon powder on top.",
      "Put two slices together or eat separately.",
      "Cut diagonally for better look.",
      "Serve immediately.",
      "Great for breakfast or quick snack."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A nutritious peanut butter and banana sandwich that is quick to make and full of energy. Great for kids and adults.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["peanuts", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 1,
    calories: 350,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["bread", "peanut butter", "honey", "banana", "cinnamon"],
    searchKeywords: ["peanut butter sandwich", "banana sandwich", "quick breakfast", "healthy sandwich", "protein toast"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Boiled Eggs",
    image: "boiled-eggs.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 eggs",
      "Water for boiling",
      "Salt to taste",
      "¼ teaspoon black pepper",
      "Optional: chaat masala, soy sauce"
    ],
    stepsRaw: [
      "Take eggs and wash them under running water.",
      "Place eggs in a small pot.",
      "Add enough water to cover eggs completely.",
      "Bring water to boil on high heat.",
      "Once boiling, reduce heat to medium.",
      "Boil for 8-10 minutes for hard-boiled eggs.",
      "For soft-boiled: boil for 5-6 minutes.",
      "Take out eggs and put them in cold water for 2 minutes.",
      "Peel eggs carefully.",
      "Sprinkle salt, pepper, or your favorite masala.",
      "Serve with bread or as a protein snack."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "Perfect boiled eggs that are protein-packed and great for a quick healthy snack or breakfast. Very easy to make.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["eggs"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 1,
    calories: 140,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["eggs", "water", "salt", "pepper", "chaat masala", "soy sauce"],
    searchKeywords: ["boiled eggs", "hard boiled eggs", "protein snack", "quick protein", "healthy breakfast"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Sweet Yogurt",
    image: "yogurt-with-sugar.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup plain yogurt",
      "2 tablespoons sugar",
      "¼ teaspoon cardamom powder",
      "1 tablespoon chopped nuts (almonds, pistachios)",
      "Few saffron strands (optional)"
    ],
    stepsRaw: [
      "Take yogurt in a bowl and whisk until smooth.",
      "Add sugar and mix well until dissolved.",
      "Add cardamom powder and mix.",
      "If using saffron, soak it in 1 tablespoon warm milk.",
      "Add saffron milk to yogurt if using.",
      "Mix everything gently.",
      "Garnish with chopped nuts.",
      "Serve cold or at room temperature.",
      "A simple and refreshing sweet dish."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A simple sweet yogurt dessert that is quick to make and perfect after a meal. Very popular in Pakistani households.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "nuts"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 1,
    calories: 180,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["yogurt", "sugar", "cardamom", "nuts", "almonds", "pistachios", "saffron"],
    searchKeywords: ["sweet yogurt", "meetha dahi", "quick dessert", "yogurt dessert", "simple sweet"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "French Toast",
    image: "french-toast.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 slices of bread",
      "1 egg",
      "2 tablespoons milk",
      "1 teaspoon sugar",
      "¼ teaspoon vanilla extract (optional)",
      "Pinch of cinnamon powder",
      "1 tablespoon butter or oil",
      "Honey or maple syrup for serving"
    ],
    stepsRaw: [
      "In a shallow bowl, beat egg well.",
      "Add milk, sugar, vanilla, and cinnamon.",
      "Mix everything well.",
      "Heat butter or oil in frying pan on medium heat.",
      "Dip bread slice in egg mixture, coating both sides.",
      "Let extra egg drip off.",
      "Place in hot pan and cook for 2-3 minutes per side.",
      "Cook until golden brown on both sides.",
      "Repeat with second slice.",
      "Serve hot with honey or maple syrup."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "Classic French toast that is golden, crispy on the outside, and soft on the inside. A favorite breakfast in many homes.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "eggs", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 1,
    calories: 350,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["bread", "egg", "milk", "sugar", "vanilla", "cinnamon", "butter", "oil", "honey", "maple syrup"],
    searchKeywords: ["french toast", "egg toast", "sweet breakfast", "quick french toast", "breakfast toast"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Scrambled Eggs",
    image: "scrambled-eggs.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 eggs",
      "1 tablespoon milk or water",
      "Salt to taste",
      "¼ teaspoon black pepper",
      "1 teaspoon butter or oil",
      "1 tablespoon chopped onion (optional)",
      "1 tablespoon chopped tomato (optional)"
    ],
    stepsRaw: [
      "Break eggs into a bowl.",
      "Add milk, salt, and pepper.",
      "Beat well with fork until fluffy.",
      "If using vegetables, add them now.",
      "Heat butter or oil in pan on medium heat.",
      "Pour egg mixture into pan.",
      "Let it set for 30 seconds.",
      "Gently stir with spatula, pushing cooked parts to the center.",
      "Cook until eggs are set but still soft.",
      "Take off from heat immediately.",
      "Serve hot with toast or bread."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "Fluffy and creamy scrambled eggs that are ready in minutes. Perfect for a quick and healthy breakfast.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "eggs"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 1,
    calories: 180,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["eggs", "milk", "water", "salt", "pepper", "butter", "oil", "onion", "tomato"],
    searchKeywords: ["scrambled eggs", "fluffy eggs", "quick breakfast", "egg recipe", "protein breakfast"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Paratha with Scrambled Eggs",
    image: "anda-paratha.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 ready-made parathas",
      "2 eggs",
      "1 small onion, chopped",
      "1 green chili, chopped",
      "Salt to taste",
      "¼ teaspoon black pepper",
      "2 tablespoons oil or ghee",
      "2 tablespoons chopped coriander"
    ],
    stepsRaw: [
      "Heat oil in pan, add chopped onion.",
      "Cook until onion becomes soft and light brown.",
      "Add green chili and cook for 30 seconds.",
      "Break eggs directly into the pan.",
      "Add salt and pepper.",
      "Scramble eggs with vegetables.",
      "Cook until eggs are done but still soft.",
      "Heat parathas separately in another pan.",
      "Put scrambled eggs on one paratha.",
      "Cover with second paratha or fold it.",
      "Garnish with chopped coriander.",
      "Serve hot with ketchup or yogurt."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "Ready-made paratha served with quick scrambled eggs - a filling and satisfying meal that is very popular.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "eggs", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 45,
    baseServings: 2,
    calories: 420,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["parathas", "eggs", "onion", "green chili", "salt", "pepper", "oil", "ghee", "coriander"],
    searchKeywords: ["anda paratha", "egg paratha", "paratha with eggs", "quick paratha", "breakfast paratha"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chickpea Chaat",
    image: "channa-chaat.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup boiled chickpeas (canned or fresh)",
      "1 small onion, finely chopped",
      "1 small tomato, chopped",
      "½ cucumber, chopped",
      "1 green chili, chopped (optional)",
      "1 tablespoon chopped coriander",
      "1 teaspoon chaat masala",
      "½ teaspoon roasted cumin powder",
      "1 tablespoon lemon juice",
      "Salt to taste"
    ],
    stepsRaw: [
      "If using canned chickpeas, drain and wash them well.",
      "In a large bowl, mix chickpeas, onion, tomato, cucumber.",
      "Add green chili if you want.",
      "Add chaat masala, cumin powder, and salt.",
      "Mix everything well.",
      "Add lemon juice and mix again.",
      "Garnish with fresh coriander.",
      "Taste and adjust seasoning if needed.",
      "Serve immediately as snack or light meal."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A tangy and spicy chickpea salad that is refreshing and perfect as a snack or light meal. Very healthy and tasty.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 2,
    calories: 180,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["chickpeas", "onion", "tomato", "cucumber", "green chili", "coriander", "chaat masala", "cumin", "lemon"],
    searchKeywords: ["chana chaat", "chickpea salad", "spicy chaat", "quick snack", "indian chaat"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Vegetable Sandwich",
    image: "veg-sandwich.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "4 slices of bread",
      "1 boiled potato, sliced",
      "1 cucumber, thinly sliced",
      "1 tomato, thinly sliced",
      "1 small onion, thinly sliced",
      "4 lettuce leaves",
      "Butter for spreading",
      "Green chutney or mayonnaise",
      "Salt and pepper to taste"
    ],
    stepsRaw: [
      "Spread butter on one side of each bread slice.",
      "Spread green chutney or mayonnaise on buttered side.",
      "Put lettuce leaf on one slice.",
      "Arrange potato slices, cucumber, tomato, and onion.",
      "Sprinkle salt and pepper.",
      "Cover with another bread slice, buttered side down.",
      "Repeat for second sandwich.",
      "Cut diagonally into triangles.",
      "Serve immediately."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A fresh and healthy vegetable sandwich packed with crunchy veggies and tasty chutney. Great for lunch or snack.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 2,
    calories: 250,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["bread", "potato", "cucumber", "tomato", "onion", "lettuce", "butter", "green chutney", "mayonnaise"],
    searchKeywords: ["vegetable sandwich", "veggie sandwich", "fresh sandwich", "healthy sandwich", "quick lunch"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Quick Pasta with Ready Sauce",
    image: "pasta-with-ready-sauce.jpg",
    cuisine: "Italian",
    ingredientsRaw: [
      "1 cup pasta (penne, macaroni, or spaghetti)",
      "2 cups water",
      "Salt for boiling water",
      "½ cup ready tomato pasta sauce",
      "1 teaspoon olive oil or butter",
      "¼ teaspoon dried oregano",
      "¼ teaspoon chili flakes",
      "2 tablespoons grated cheese"
    ],
    stepsRaw: [
      "Boil water in a pot with salt.",
      "Add pasta and cook for 8-10 minutes or as per instructions on packet.",
      "Drain pasta, saving some pasta water.",
      "Heat pasta sauce in the same pot.",
      "Add cooked pasta to the sauce.",
      "Add oregano, chili flakes, and olive oil.",
      "Mix well, adding pasta water if it looks too dry.",
      "Cook for 1-2 minutes more.",
      "Add grated cheese and mix.",
      "Serve hot immediately."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "Quick and easy pasta made with ready-made sauce - perfect for a fast and satisfying meal that everyone enjoys.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 50,
    baseServings: 1,
    calories: 420,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["pasta", "water", "salt", "tomato sauce", "olive oil", "butter", "oregano", "chili flakes", "cheese"],
    searchKeywords: ["quick pasta", "pasta with sauce", "easy pasta", "tomato pasta", "10 minute pasta"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Leftover Rice Fry",
    image: "leftover-rice-fry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups leftover cooked rice",
      "1 egg (optional)",
      "½ cup mixed vegetables (peas, carrots, corn)",
      "1 small onion, chopped",
      "2 tablespoons soy sauce",
      "1 tablespoon oil",
      "Salt and pepper to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok or large pan.",
      "Add chopped onion and cook until soft.",
      "Add mixed vegetables and cook for 2 minutes.",
      "Push vegetables to the side, add egg and scramble if using.",
      "Add leftover rice and break up any lumps.",
      "Add soy sauce, salt, and pepper.",
      "Mix everything well and cook for 3-4 minutes.",
      "Garnish with chopped spring onions.",
      "Serve hot as a complete meal."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "Quick fried rice made with leftover rice - a great way to use leftovers and make a tasty meal. Very economical.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["eggs", "soy"],
    budget: "economy",
    costPerServing: 40,
    baseServings: 2,
    calories: 320,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["leftover rice", "egg", "mixed vegetables", "onion", "soy sauce", "oil", "spring onions"],
    searchKeywords: ["leftover rice fry", "quick fried rice", "egg fried rice", "rice recipe", "budget meal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Lentils with Rice ",
    image: "daal-chawal.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "½ cup masoor dal (red lentils)",
      "1 cup rice",
      "3 cups water",
      "1 teaspoon turmeric powder",
      "1 teaspoon salt",
      "1 tablespoon ghee or oil",
      "½ teaspoon cumin seeds",
      "1 dried red chili (optional)",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Wash dal and rice separately.",
      "In a pressure cooker, add dal, rice, water, turmeric, and salt.",
      "Close the lid and cook for 2 whistles on medium heat.",
      "Let pressure release naturally.",
      "For tempering: heat ghee in a small pan.",
      "Add cumin seeds and red chili.",
      "Pour this tempering over cooked daal chawal.",
      "Mix gently and garnish with coriander.",
      "Serve hot with pickle or yogurt."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "Comforting lentils with rice that is quick to make and perfect for a simple meal. A classic Pakistani comfort food.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 2,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["masoor dal", "rice", "water", "turmeric", "salt", "ghee", "oil", "cumin", "red chili", "coriander"],
    searchKeywords: ["daal chawal", "lentils with rice", "quick daal", "pakistani comfort food", "simple meal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Mayonnaise Sandwich",
    image: "chicken-mayo-sandwich.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "4 slices of bread",
      "1 cup shredded cooked chicken",
      "¼ cup mayonnaise",
      "2 tablespoons chopped celery or onion",
      "4 lettuce leaves",
      "Salt and pepper to taste",
      "Butter for toasting"
    ],
    stepsRaw: [
      "Mix shredded chicken with mayonnaise.",
      "Add chopped celery or onion.",
      "Season with salt and pepper.",
      "Butter bread slices on one side.",
      "Place lettuce leaf on unbuttered side of one slice.",
      "Spread chicken mixture over lettuce.",
      "Cover with second bread slice, buttered side out.",
      "Toast in pan until golden brown on both sides.",
      "Repeat for second sandwich.",
      "Cut diagonally and serve hot."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A creamy and delicious chicken mayonnaise sandwich that is perfect for a quick lunch or snack. Very filling.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "eggs", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 70,
    baseServings: 2,
    calories: 450,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["bread", "chicken", "mayonnaise", "celery", "onion", "lettuce", "butter"],
    searchKeywords: ["chicken mayo sandwich", "chicken sandwich", "creamy chicken sandwich", "quick lunch", "sandwich recipe"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Minced Meat Paratha ",
    image: "qeema-paratha.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 ready-made parathas",
      "1 cup cooked minced meat (qeema)",
      "1 small onion, finely chopped",
      "1 green chili, chopped",
      "1 tablespoon oil",
      "¼ teaspoon garam masala",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a pan, add chopped onion.",
      "Cook until onion is golden brown.",
      "Add cooked qeema and green chili.",
      "Add garam masala and salt, mix well.",
      "Cook for 2-3 minutes, then take off from heat.",
      "Add fresh coriander and mix.",
      "Take a paratha and put qeema mixture in the center.",
      "Fold paratha over filling or make a roll.",
      "Heat in pan until crispy on both sides.",
      "Serve hot with yogurt or raita."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A flavorful minced meat stuffed paratha that is quick to make and very satisfying. A hearty meal for anyone.",
    category: "Anytime",
    subCategory: "quick",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Anytime"],
    allergens: ["dairy", "gluten", "wheat"],
    budget: "economy",
    costPerServing: 80,
    baseServings: 2,
    calories: 520,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["parathas", "minced meat", "qeema", "onion", "green chili", "oil", "garam masala", "coriander"],
    searchKeywords: ["qeema paratha", "minced meat paratha", "keema paratha", "quick paratha", "stuffed paratha"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
]

async function migrateRecipes() {
  try {
    console.log('Connecting to MongoDB');
    
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) {
      throw new Error('MongoDB URI not found');
    }
    
    await mongoose.connect(mongoURI, { 
      serverSelectionTimeoutMS: 10000, 
      family: 4 
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();