const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
  {
    title: "Cream of Mushroom Soup",
    image: "Cream-of-mushroom-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g fresh mushrooms - cut into thin pieces",
      "1 onion - cut small",
      "2 garlic cloves - crushed",
      "2 cups vegetable stock",
      "1 cup cream",
      "2 tbsp butter",
      "2 tbsp flour",
      "1 tsp thyme",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Heat butter in a big pot on medium flame",
      "Add onion and garlic, fry until soft (3-4 minutes)",
      "Add mushrooms and cook until they become soft and change color (8-10 minutes)",
      "Add flour and stir for 2 minutes",
      "Slowly add vegetable stock while stirring so no lumps form",
      "Add thyme, salt and pepper",
      "Let it cook for 15 minutes on low flame",
      "Add cream and mix well",
      "Cook for 5 more minutes and serve hot"
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Rich and creamy mushroom soup with smooth texture - perfect for cold evenings",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy", "gluten"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 4,
    calories: 280,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["mushrooms", "onion", "garlic", "stock", "cream", "butter", "flour", "thyme"],
    searchKeywords: ["mushroom soup", "cream soup", "soup", "vegetarian", "creamy"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Corn Soup",
    image: "Chicken-Corn-Soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "200g chicken - boil and shred into small pieces",
      "1 can cream style corn",
      "4 cups chicken stock",
      "2 tbsp cornflour",
      "1 egg white",
      "1 tsp ginger - grated",
      "2 spring onions - chopped",
      "Salt as needed",
      "White pepper as needed"
    ],
    stepsRaw: [
      "Put chicken stock in a pot and bring to boil",
      "Add shredded chicken and ginger, cook for 10 minutes",
      "Add cream style corn and mix well",
      "Mix cornflour with half cup water to make a paste",
      "Slowly add cornflour paste while stirring until soup becomes thick",
      "Slowly pour egg white while stirring in one direction",
      "Add salt and white pepper",
      "Put spring onions on top and serve hot"
    ],
    difficulty: "Easy",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Sweet and creamy chicken corn soup that everyone loves - a restaurant favorite",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["eggs"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 4,
    calories: 180,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chicken", "corn", "stock", "cornflour", "egg white", "ginger", "spring onions"],
    searchKeywords: ["chicken corn soup", "sweet corn soup", "chicken soup", "soup", "corn"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Tomato Soup",
    image: "tomato-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg ripe tomatoes - chopped",
      "1 onion - chopped",
      "2 garlic cloves",
      "4 cups vegetable stock",
      "2 tbsp tomato paste",
      "1 tsp sugar",
      "Few fresh basil leaves",
      "2 tbsp cream",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Put tomatoes in hot water for 2 minutes, remove the skin and chop",
      "Heat oil in a pot and fry onion and garlic until soft",
      "Add tomatoes and tomato paste, cook for 10 minutes",
      "Add vegetable stock and cook for 15 minutes",
      "Blend the soup until smooth",
      "Add sugar, salt and pepper",
      "Add fresh basil leaves",
      "Serve hot with cream on top"
    ],
    difficulty: "Easy",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Classic tomato soup that tastes like homemade - tangy, smooth and comforting",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 4,
    calories: 120,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["tomatoes", "onion", "garlic", "stock", "tomato paste", "sugar", "basil", "cream"],
    searchKeywords: ["tomato soup", "creamy tomato soup", "soup", "vegetarian", "classic"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Vegetable Soup",
    image: "mixed-veg-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups mixed vegetables (carrots, peas, beans, corn)",
      "1 onion - chopped",
      "2 garlic cloves",
      "4 cups vegetable stock",
      "2 tomatoes - chopped",
      "1 tsp mixed herbs",
      "2 tbsp oil",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Heat oil in a pot and fry onion and garlic until soft (5 minutes)",
      "Add all vegetables and cook for 5 minutes",
      "Add tomatoes and cook until they become soft",
      "Add vegetable stock and mixed herbs",
      "Bring to boil, then cook on low flame for 20 minutes",
      "Add salt and pepper",
      "You can blend half the soup if you want it thick",
      "Serve hot with bread"
    ],
    difficulty: "Easy",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Healthy vegetable soup full of good veggies - light and perfect for diet",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 15,
    baseServings: 4,
    calories: 90,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["mixed vegetables", "carrots", "peas", "beans", "corn", "onion", "garlic", "stock", "tomatoes"],
    searchKeywords: ["vegetable soup", "mixed vegetable soup", "soup", "healthy", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Noodle Soup",
    image: "Chicken-Corn-Soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "200g chicken - cut into small pieces",
      "1 cup noodles",
      "4 cups chicken stock",
      "1 carrot - cut small",
      "1 onion - chopped",
      "2 garlic cloves",
      "1 tsp black pepper",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Cook noodles in water until soft, drain and keep aside",
      "Heat oil in a pot and fry onion and garlic until soft",
      "Add chicken and cook until it turns white (8-10 minutes)",
      "Add carrot and cook for 5 minutes",
      "Add chicken stock and bring to boil",
      "Add salt and black pepper",
      "Cook for 15 minutes on low flame",
      "Add cooked noodles, mix well and serve hot with coriander"
    ],
    difficulty: "Easy",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Hearty chicken noodle soup with soft noodles and tender chicken - just like home",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["gluten"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 4,
    calories: 250,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chicken", "noodles", "stock", "carrot", "onion", "garlic", "pepper"],
    searchKeywords: ["chicken noodle soup", "noodle soup", "chicken soup", "soup", "hearty"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Hot and Sour Soup",
    image: "Restaurant-Style-Hot-and-Sour-Soup.jpg",
    cuisine: "Chinese",
    ingredientsRaw: [
      "4 cups chicken stock",
      "100g chicken - shredded",
      "50g mushrooms - sliced",
      "2 tbsp soy sauce",
      "2 tbsp vinegar",
      "1 tbsp chilli sauce",
      "2 tbsp cornflour",
      "1 egg - beaten",
      "Salt as needed"
    ],
    stepsRaw: [
      "Bring chicken stock to boil in a pot",
      "Add shredded chicken and mushrooms, cook for 8 minutes",
      "Add soy sauce, vinegar and chilli sauce",
      "Mix cornflour with half cup water to make paste",
      "Slowly add cornflour paste while stirring until soup becomes thick",
      "Slowly pour beaten egg while stirring in one direction",
      "Cook for 2 more minutes",
      "Serve hot with extra chilli sauce on the side"
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Chinese style hot and sour soup with chicken and mushrooms - spicy, tangy and full of flavor",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["eggs", "soy"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 4,
    calories: 150,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["stock", "chicken", "mushrooms", "soy sauce", "vinegar", "chilli sauce", "cornflour", "egg"],
    searchKeywords: ["hot and sour soup", "chinese soup", "soup", "spicy", "tangy"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Lentil Soup",
    image: "LENTIL-SOUP.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup brown lentils (masoor)",
      "1 onion - chopped",
      "2 carrots - cut small",
      "4 cups vegetable stock",
      "2 garlic cloves",
      "1 tsp cumin powder",
      "2 tbsp lemon juice",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Wash lentils and soak in water for 30 minutes, then drain",
      "Heat oil in a pot and fry onion until soft",
      "Add carrots and garlic, cook for 5 minutes",
      "Add lentils and cumin powder",
      "Add vegetable stock and bring to boil",
      "Cook on low flame for 35-40 minutes until lentils are soft",
      "Add lemon juice, salt and pepper",
      "You can blend half the soup for creamy texture"
    ],
    difficulty: "Easy",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Healthy lentil soup full of protein - simple, tasty and good for you",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 20,
    baseServings: 4,
    calories: 180,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["lentils", "masoor", "onion", "carrots", "stock", "garlic", "cumin", "lemon"],
    searchKeywords: ["lentil soup", "masoor dal soup", "protein soup", "soup", "healthy"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Vegetable Soup",
    image: "Chicken-veg-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "300g chicken - cut into small pieces",
      "1 onion - chopped",
      "2 carrots - chopped",
      "2 potatoes - chopped",
      "1 cup green beans - chopped",
      "4 cups chicken stock",
      "2 tomatoes - chopped",
      "1 tsp mixed herbs",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Heat oil in a pot and fry onion until golden",
      "Add chicken and cook until it turns brown (8-10 minutes)",
      "Add carrots, potatoes and beans, cook for 5 minutes",
      "Add chicken stock and bring to boil",
      "Add tomatoes and mixed herbs",
      "Cook on low flame for 30 minutes until vegetables are soft",
      "Add salt and pepper",
      "Serve hot with bread"
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Hearty soup with chicken and garden vegetables - a complete meal in a bowl",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 35,
    baseServings: 4,
    calories: 280,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chicken", "onion", "carrots", "potatoes", "beans", "stock", "tomatoes", "herbs"],
    searchKeywords: ["chicken vegetable soup", "chicken soup", "soup", "hearty", "vegetable"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Pumpkin Soup",
    image: "Pumpkin-Soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 kg pumpkin - remove skin and cut into cubes",
      "1 onion - chopped",
      "2 garlic cloves",
      "4 cups vegetable stock",
      "1 cup coconut milk",
      "1 tsp cinnamon powder",
      "1/2 tsp nutmeg powder",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Put pumpkin cubes in oven at 200°C for 25 minutes to roast",
      "Heat oil in a pot and fry onion and garlic until soft",
      "Add roasted pumpkin and vegetable stock",
      "Cook for 15 minutes on low flame",
      "Blend the soup until very smooth",
      "Put back in pot and add coconut milk, cinnamon and nutmeg",
      "Heat through but do not boil",
      "Serve hot with roasted pumpkin seeds on top if you have them"
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Smooth and creamy pumpkin soup with a hint of cinnamon - tastes like winter in a bowl",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 25,
    baseServings: 4,
    calories: 160,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["pumpkin", "onion", "garlic", "stock", "coconut milk", "cinnamon", "nutmeg"],
    searchKeywords: ["pumpkin soup", "creamy pumpkin soup", "soup", "vegetarian", "winter"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Egg Drop Soup",
    image: "Egg-drop-soup.jpg",
    cuisine: "Chinese",
    ingredientsRaw: [
      "4 cups chicken stock",
      "2 eggs - beat lightly",
      "2 tbsp cornflour",
      "1 tsp soy sauce",
      "1/2 tsp ginger - grated",
      "2 spring onions - chopped",
      "1/4 tsp white pepper",
      "Salt as needed"
    ],
    stepsRaw: [
      "Bring chicken stock to boil in a pot",
      "Mix cornflour with half cup water to make paste",
      "Add soy sauce, ginger and white pepper to the stock",
      "Slowly add cornflour paste while stirring",
      "Turn flame to low",
      "Slowly pour beaten eggs while stirring gently in one direction",
      "Cook for 1 minute until eggs make thin ribbons",
      "Put spring onions on top and serve immediately"
    ],
    difficulty: "Easy",
    cookingTime: 15,
    isActive: true,
    isHalal: true,
    description: "Chinese egg drop soup with soft egg ribbons - very light and takes only 10 minutes",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["eggs", "soy"],
    budget: "economy",
    costPerServing: 15,
    baseServings: 4,
    calories: 80,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["stock", "eggs", "cornflour", "soy sauce", "ginger", "spring onions", "white pepper"],
    searchKeywords: ["egg drop soup", "chinese soup", "soup", "quick", "light"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cream of Chicken Soup",
    image: "Cream-of-Chicken-Soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "300g chicken breast",
      "4 cups chicken stock",
      "1 cup cream",
      "1 onion - chopped",
      "2 tbsp butter",
      "2 tbsp flour",
      "1 tsp thyme",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Boil chicken in stock for 15-20 minutes until cooked",
      "Take out chicken, shred into small pieces",
      "Melt butter in a pot and fry onion until soft",
      "Add flour and cook for 2 minutes while stirring",
      "Slowly add chicken stock while whisking so no lumps form",
      "Cook for 10 minutes until soup becomes a little thick",
      "Add shredded chicken and thyme",
      "Add cream, heat through but do not boil",
      "Add salt and pepper, serve hot"
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Smooth and creamy chicken soup that everyone loves - rich, comforting and delicious",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy", "gluten"],
    budget: "economy",
    costPerServing: 40,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chicken", "stock", "cream", "onion", "butter", "flour", "thyme"],
    searchKeywords: ["cream of chicken soup", "chicken soup", "creamy soup", "soup", "comfort"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Spinach Soup",
    image: "Spinach-Soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g fresh spinach (palak)",
      "1 onion - chopped",
      "2 garlic cloves",
      "3 cups vegetable stock",
      "1 cup milk",
      "2 tbsp butter",
      "A little bit of nutmeg",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Wash spinach very well in water",
      "Melt butter in a pot and fry onion and garlic until soft",
      "Add spinach and cook for 3-4 minutes until it becomes soft",
      "Add vegetable stock and bring to boil",
      "Cook for 10 minutes on low flame",
      "Blend until very smooth",
      "Put back in pot, add milk and nutmeg",
      "Heat through and serve"
    ],
    difficulty: "Easy",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Healthy green spinach soup with a touch of nutmeg - light, nourishing and tasty",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 4,
    calories: 120,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["spinach", "palak", "onion", "garlic", "stock", "milk", "butter", "nutmeg"],
    searchKeywords: ["spinach soup", "palak soup", "green soup", "soup", "healthy"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Soup",
    image: "mutton-broth.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton with bones",
      "8 cups water",
      "1 onion - chopped",
      "4 garlic cloves",
      "1 inch ginger - sliced",
      "1 tsp black pepper whole",
      "4 cloves",
      "2 green cardamom",
      "1 cinnamon stick",
      "1 bay leaf",
      "Salt as needed",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Wash mutton very well",
      "Put mutton in a big pot with water",
      "Add onion, garlic, ginger and all whole spices",
      "Bring to boil, then turn flame to low",
      "Cook for 2-3 hours until mutton becomes very soft",
      "Remove foam that comes on top while cooking",
      "Add salt at the end",
      "You can strain the soup or serve with meat pieces",
      "Put fresh coriander on top and serve hot"
    ],
    difficulty: "Hard",
    cookingTime: 180,
    isActive: true,
    isHalal: true,
    description: "Traditional mutton soup that warms you up - full of flavor and very nourishing",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 55,
    baseServings: 4,
    calories: 280,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "onion", "garlic", "ginger", "pepper", "cloves", "cardamom", "cinnamon", "bay leaf"],
    searchKeywords: ["mutton soup", "mutton broth", "yakhni", "soup", "traditional"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Manchow Soup",
    image: "manchow-soup.jpg",
    cuisine: "Chinese",
    ingredientsRaw: [
      "4 cups vegetable stock",
      "1 cup mixed vegetables (carrots, cabbage, capsicum)",
      "100g tofu or shredded chicken",
      "2 tbsp soy sauce",
      "1 tbsp vinegar",
      "1 tbsp chilli sauce",
      "2 tbsp cornflour",
      "Crispy noodles for topping",
      "Salt as needed"
    ],
    stepsRaw: [
      "Fry vegetables and tofu in a pot for 3-4 minutes",
      "Add vegetable stock and bring to boil",
      "Add soy sauce, vinegar and chilli sauce",
      "Mix cornflour with half cup water to make paste",
      "Slowly add cornflour paste while stirring until soup becomes thick",
      "Cook for 10 minutes on low flame",
      "Deep fry noodles until golden brown and crispy",
      "Serve soup with lots of crispy noodles on top"
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Indo-Chinese manchow soup with crispy noodles on top - spicy, tangy and crunchy",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["soy", "gluten"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 4,
    calories: 210,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["stock", "mixed vegetables", "tofu", "soy sauce", "vinegar", "chilli sauce", "cornflour", "noodles"],
    searchKeywords: ["manchow soup", "indo chinese soup", "soup", "crispy noodles", "spicy"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Potato Soup",
    image: "Chicken-Potato-Soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "300g chicken - cut into small pieces",
      "3 potatoes - chopped",
      "1 onion - chopped",
      "2 carrots - chopped",
      "4 cups chicken stock",
      "1 cup milk",
      "2 tbsp flour",
      "2 tbsp butter",
      "Fresh dill for garnish",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Melt butter in a pot and fry onion until soft",
      "Add chicken and cook until it turns white (8-10 minutes)",
      "Add potatoes and carrots, cook for 5 minutes",
      "Add flour and stir for 2 minutes",
      "Slowly add chicken stock while stirring",
      "Cook for 20 minutes until vegetables are soft",
      "Add milk and heat through but do not boil",
      "Add salt and pepper",
      "Put fresh dill on top and serve"
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Creamy chicken and potato soup with carrots - very filling and comforting",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy", "gluten"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 4,
    calories: 300,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chicken", "potatoes", "onion", "carrots", "stock", "milk", "flour", "butter", "dill"],
    searchKeywords: ["chicken potato soup", "potato soup", "chicken soup", "soup", "creamy"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Garlic Soup",
    image: "garlic-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 whole garlic bulbs",
      "1 onion - chopped",
      "4 cups vegetable stock",
      "1 cup cream",
      "2 tbsp olive oil",
      "Fresh thyme",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Cut the tops off garlic bulbs",
      "Put oil on them and wrap in foil",
      "Put in oven at 190°C for 45-60 minutes until soft",
      "Let cool, then squeeze out the soft garlic",
      "Heat oil in a pot and fry onion until soft",
      "Add roasted garlic and vegetable stock",
      "Cook for 20 minutes on low flame",
      "Blend until very smooth",
      "Add cream and fresh thyme",
      "Heat through and serve"
    ],
    difficulty: "Medium",
    cookingTime: 80,
    isActive: true,
    isHalal: true,
    description: "Roasted garlic soup that is rich and creamy - full of flavor and very good for you",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 4,
    calories: 180,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["garlic", "onion", "stock", "cream", "olive oil", "thyme"],
    searchKeywords: ["garlic soup", "roasted garlic soup", "soup", "creamy", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Barley Soup",
    image: "Barley-Soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup barley (jau)",
      "2 carrots - chopped",
      "2 potatoes - chopped",
      "1 onion - chopped",
      "4 cups vegetable stock",
      "2 tbsp tomato paste",
      "1 tsp thyme",
      "2 tbsp olive oil",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Wash barley and soak in water for 30 minutes",
      "Heat oil in a pot and fry onion until soft",
      "Add carrots and potatoes, cook for 5 minutes",
      "Add barley and vegetable stock",
      "Add tomato paste and thyme",
      "Bring to boil, then turn flame to low",
      "Cook for 50-60 minutes until barley is soft",
      "Add salt and pepper",
      "Serve hot with bread"
    ],
    difficulty: "Medium",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "Hearty barley soup with vegetables - full of fiber and very healthy",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 25,
    baseServings: 4,
    calories: 190,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["barley", "jau", "carrots", "potatoes", "onion", "stock", "tomato paste", "thyme"],
    searchKeywords: ["barley soup", "jau soup", "soup", "healthy", "grain"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Thai Soup",
    image: "thai-soup.jpg",
    cuisine: "Chinese",
    ingredientsRaw: [
      "4 cups chicken stock",
      "2 stalks lemongrass",
      "4 kaffir lime leaves",
      "2 inch galangal or ginger - sliced",
      "200g shrimp or chicken",
      "4 mushrooms - sliced",
      "2 tbsp fish sauce",
      "2 tbsp lime juice",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Crush lemongrass stalks and put in pot with stock",
      "Add galangal slices and kaffir lime leaves",
      "Bring to boil and cook for 10 minutes",
      "Add shrimp and mushrooms",
      "Cook until shrimp turns pink (about 5 minutes)",
      "Take out lemongrass and galangal before serving",
      "Add fish sauce and lime juice",
      "Put fresh coriander on top and serve"
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Thai soup with lemongrass and shrimp - light, fragrant and very refreshing",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["shellfish"],
    budget: "economy",
    costPerServing: 45,
    baseServings: 4,
    calories: 160,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["lemongrass", "kaffir lime", "galangal", "ginger", "shrimp", "mushrooms", "fish sauce", "lime"],
    searchKeywords: ["thai soup", "tom yum", "lemongrass soup", "soup", "shrimp"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Oats Soup",
    image: "Oats-Soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup rolled oats",
      "4 cups vegetable stock",
      "1 carrot - grated",
      "1 onion - chopped",
      "2 garlic cloves",
      "1 tsp cumin powder",
      "2 tbsp lemon juice",
      "Fresh coriander for garnish",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Dry roast oats in a pan for 2-3 minutes until you smell them",
      "Heat oil in a pot and fry onion and garlic until soft",
      "Add grated carrot and cook for 2 minutes",
      "Add roasted oats and vegetable stock",
      "Bring to boil, then turn flame to low",
      "Cook for 15 minutes until oats are soft",
      "Add cumin powder, lemon juice, salt and pepper",
      "Put fresh coriander on top and serve hot"
    ],
    difficulty: "Easy",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Healthy oats soup with carrots - good for diet and very easy to make",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 15,
    baseServings: 4,
    calories: 120,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["oats", "stock", "carrot", "onion", "garlic", "cumin", "lemon", "coriander"],
    searchKeywords: ["oats soup", "oatmeal soup", "healthy soup", "soup", "diet"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mulligatawny Soup",
    image: "Mulligatawny-Soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup red lentils (masoor)",
      "1 onion - chopped",
      "2 carrots - chopped",
      "2 apples - remove skin and chop",
      "4 cups vegetable stock",
      "2 tbsp curry powder",
      "1 tsp turmeric",
      "1 tsp cumin",
      "2 tbsp coconut milk",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Wash lentils and soak in water for 30 minutes, then drain",
      "Heat oil in a pot and fry onion until soft",
      "Add carrots and apples, cook for 5 minutes",
      "Add curry powder, turmeric and cumin, cook for 2 minutes",
      "Add lentils and vegetable stock",
      "Bring to boil, then cook on low for 30 minutes until lentils are soft",
      "You can blend half the soup for creamy texture",
      "Add coconut milk, salt and pepper",
      "Serve hot"
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Curried lentil soup with apples and coconut milk - warm, spicy and different",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 30,
    baseServings: 4,
    calories: 210,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["lentils", "masoor", "onion", "carrots", "apples", "stock", "curry powder", "turmeric", "cumin", "coconut milk"],
    searchKeywords: ["mulligatawny soup", "curried lentil soup", "soup", "spiced", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Clear Soup",
    image: "Clear-chicken-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "300g chicken pieces with bones",
      "6 cups water",
      "1 carrot - sliced",
      "2 celery stalks",
      "1 onion - cut into 4 pieces",
      "4 garlic cloves",
      "1 inch ginger - sliced",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put chicken in a pot with cold water",
      "Bring to boil, then remove the foam that comes on top",
      "Add all vegetables and aromatics",
      "Turn flame to low and cook for 40 minutes",
      "Take out chicken and shred the meat",
      "Strain the soup through a cloth for clear liquid",
      "Put the shredded chicken back in the clear soup",
      "Add a little salt and serve"
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Light and clear chicken soup - very good for when you are sick or on diet",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 25,
    baseServings: 4,
    calories: 110,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chicken", "carrot", "celery", "onion", "garlic", "ginger"],
    searchKeywords: ["chicken clear soup", "clear soup", "light soup", "soup", "healthy"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mixed Grain Soup",
    image: "Mixed-Grain-Soup.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1/2 cup barley",
      "1/2 cup quinoa",
      "1/4 cup lentils",
      "4 cups vegetable stock",
      "2 carrots - chopped",
      "2 celery stalks - chopped",
      "1 onion - chopped",
      "2 tbsp olive oil",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Wash all grains well under water",
      "Heat oil in a pot and fry onion until soft (8 minutes)",
      "Add carrots and celery, cook for 5 minutes",
      "Add all grains and cook for 2 minutes while stirring",
      "Add vegetable stock and bring to boil",
      "Turn flame to low and cover",
      "Cook for 45 minutes until all grains are soft",
      "Add salt and pepper",
      "Serve hot with bread"
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "Soup made with three different grains - very healthy and full of fiber",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 25,
    baseServings: 4,
    calories: 210,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["barley", "quinoa", "lentils", "stock", "carrots", "celery", "onion"],
    searchKeywords: ["mixed grain soup", "multi grain soup", "soup", "healthy", "grain"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Noodle Soup",
    image: "noodle-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "200g noodles",
      "4 cups chicken stock",
      "1 cup mixed vegetables",
      "100g shredded chicken or tofu",
      "2 tbsp soy sauce",
      "1 tsp sesame oil",
      "Spring onions for garnish",
      "Chilli flakes if you want spicy"
    ],
    stepsRaw: [
      "Cook noodles in water until soft, drain and keep aside",
      "Bring chicken stock to boil in a pot",
      "Add vegetables and chicken, cook for 10 minutes",
      "Add soy sauce and sesame oil",
      "Put cooked noodles in serving bowls",
      "Pour hot soup with vegetables over the noodles",
      "Put spring onions on top",
      "Add chilli flakes if you like and serve"
    ],
    difficulty: "Easy",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Simple noodle soup with vegetables and chicken - quick to make and very tasty",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["soy", "gluten"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 4,
    calories: 230,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["noodles", "stock", "mixed vegetables", "chicken", "soy sauce", "sesame oil", "spring onions"],
    searchKeywords: ["noodle soup", "simple noodle soup", "soup", "quick", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Fish Vegetable Soup",
    image: "fish-veg-and-noodle-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "300g white fish (like tilapia or cod)",
      "1 cup noodles",
      "4 cups fish or vegetable stock",
      "1 cup mixed vegetables",
      "2 tbsp fish sauce",
      "1 tbsp lime juice",
      "1 tsp ginger - grated",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Cook noodles in water until soft, drain and keep aside",
      "Heat stock in a pot on low flame",
      "Add ginger and vegetables",
      "Cook for 8 minutes until vegetables are soft",
      "Add fish pieces carefully to the pot",
      "Cook for 5 minutes until fish is done (it will become white and flaky)",
      "Add noodles, fish sauce and lime juice",
      "Put fresh coriander on top and serve"
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Light fish soup with noodles and vegetables - very healthy and tastes fresh",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["fish", "gluten"],
    budget: "economy",
    costPerServing: 40,
    baseServings: 4,
    calories: 190,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["fish", "tilapia", "cod", "noodles", "stock", "mixed vegetables", "fish sauce", "lime", "ginger"],
    searchKeywords: ["fish vegetable soup", "fish noodle soup", "fish soup", "soup", "light"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Paye Soup",
    image: "paye-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "4 lamb or goat trotters (paye)",
      "2 onions - chopped",
      "2 inch ginger - grated",
      "6 garlic cloves",
      "2 tbsp coriander powder",
      "1 tbsp red chili powder",
      "1 tsp turmeric",
      "Fresh ginger for garnish",
      "Salt as needed"
    ],
    stepsRaw: [
      "Clean trotters very well, wash many times",
      "Put trotters in pressure cooker with water",
      "Cook for 2 hours until very soft",
      "In a separate pan, fry onions until golden brown",
      "Add ginger, garlic and all spices, cook for 3 minutes",
      "Add cooked trotters and the broth",
      "Cook for 3-4 hours until soup becomes thick and sticky",
      "Remove extra fat if you want",
      "Serve with fresh ginger, lemon and coriander"
    ],
    difficulty: "Hard",
    cookingTime: 360,
    isActive: true,
    isHalal: true,
    description: "Traditional paye soup made with trotters - very rich and full of goodness",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 55,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["trotters", "paye", "onions", "ginger", "garlic", "coriander powder", "red chili", "turmeric"],
    searchKeywords: ["paye soup", "trotter soup", "paya", "soup", "traditional"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Broth",
    image: "Chicken-broth.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 kg chicken bones",
      "12 cups water",
      "2 onions - cut into 4 pieces",
      "3 carrots - cut big",
      "4 celery stalks",
      "4 garlic cloves - smashed",
      "2 bay leaves",
      "1 tsp black pepper whole",
      "Salt as needed"
    ],
    stepsRaw: [
      "Put chicken bones in a big pot with water",
      "Bring to boil, remove the foam that comes on top",
      "Add all vegetables and spices",
      "Turn flame to low and cover partly",
      "Cook for 3 hours",
      "Strain through a fine sieve or cloth",
      "Let it cool, then put in fridge",
      "Remove the fat layer from top when cold",
      "Use as base for soups or keep in freezer for 6 months"
    ],
    difficulty: "Hard",
    cookingTime: 180,
    isActive: true,
    isHalal: true,
    description: "Homemade chicken stock - much better than the box ones. Use in any soup",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 15,
    baseServings: 8,
    calories: 50,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chicken bones", "onions", "carrots", "celery", "garlic", "bay leaves", "pepper"],
    searchKeywords: ["chicken broth", "chicken stock", "homemade stock", "soup", "base"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Tikka Corn Soup",
    image: "Chicken-Tikka-Corn-Soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "200g chicken tikka pieces",
      "1 can cream style corn",
      "1 capsicum - chopped",
      "4 cups chicken stock",
      "1 cup cream",
      "2 tbsp tikka masala",
      "1 onion - chopped",
      "2 tbsp butter",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat butter in a pot and fry onion until golden",
      "Add chicken tikka pieces and cook for 5 minutes",
      "Add capsicum and corn, cook for 3 minutes",
      "Add tikka masala and cook for 2 minutes",
      "Add chicken stock and bring to boil",
      "Cook for 15 minutes on low flame",
      "Add cream and heat through but do not boil",
      "Put fresh coriander on top and serve"
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Fusion soup with spicy chicken tikka and sweet corn - desi style soup",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 40,
    baseServings: 4,
    calories: 310,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken tikka", "corn", "capsicum", "stock", "cream", "tikka masala", "onion", "butter"],
    searchKeywords: ["chicken tikka corn soup", "tikka soup", "soup", "desi", "corn"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Creamy Noodle Soup",
    image: "Creamy-noodles-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "200g noodles",
      "4 cups chicken stock",
      "1 cup mixed vegetables (carrots, peas, corn)",
      "1 cup milk",
      "2 tbsp butter",
      "2 tbsp flour",
      "1 tsp black pepper",
      "Salt as needed"
    ],
    stepsRaw: [
      "Cook noodles in water until soft, drain and keep aside",
      "Melt butter in a pot and add flour, cook for 2 minutes",
      "Slowly add chicken stock while whisking so no lumps form",
      "Add mixed vegetables and cook for 10 minutes until soft",
      "Add milk and cooked noodles",
      "Add salt and pepper",
      "Cook for 5 more minutes",
      "Serve hot with fresh herbs on top"
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Creamy noodle soup that kids will love - smooth, comforting and easy to make",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy", "gluten"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 4,
    calories: 250,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["noodles", "stock", "mixed vegetables", "milk", "butter", "flour", "pepper"],
    searchKeywords: ["creamy noodle soup", "creamy pasta soup", "soup", "kids", "comfort"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Macaroni Soup",
    image: "Chicken-macroni-corn-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "200g chicken - cut into small pieces",
      "1 cup macaroni",
      "1 cup sweet corn",
      "1 carrot - cut small",
      "4 cups chicken stock",
      "1 onion - chopped",
      "2 garlic cloves",
      "2 tbsp soy sauce",
      "1 tsp black pepper",
      "Salt as needed"
    ],
    stepsRaw: [
      "Heat oil in a pot and fry onion and garlic until soft",
      "Add chicken and cook until it turns white",
      "Add carrot and corn, cook for 5 minutes",
      "Add chicken stock and bring to boil",
      "Add macaroni and cook until soft (about 10-12 minutes)",
      "Add soy sauce and black pepper",
      "Cook for 10 more minutes",
      "Serve hot with bread"
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Hearty soup with chicken, macaroni and sweet corn - a complete meal",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["soy", "gluten"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
    pantryKeywords: ["chicken", "macaroni", "corn", "carrot", "stock", "onion", "garlic", "soy sauce"],
    searchKeywords: ["chicken macaroni soup", "macaroni soup", "chicken pasta soup", "soup", "hearty"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Hot and Sour Macaroni Soup",
    image: "hot-and-sour-chicken-soup.jpg",
    cuisine: "Chinese",
    ingredientsRaw: [
      "200g chicken - shredded",
      "1 cup macaroni",
      "4 cups chicken stock",
      "2 tbsp soy sauce",
      "1 tbsp vinegar",
      "1 tbsp chilli garlic sauce",
      "2 tbsp cornflour",
      "1 cup mixed vegetables",
      "Salt as needed"
    ],
    stepsRaw: [
      "Cook macaroni in water until soft, drain and keep aside",
      "Bring chicken stock to boil in a pot",
      "Add chicken and vegetables, cook for 10 minutes",
      "Add soy sauce, vinegar and chilli garlic sauce",
      "Mix cornflour with half cup water to make paste",
      "Slowly add cornflour paste while stirring until soup becomes thick",
      "Add cooked macaroni and heat through",
      "Serve hot with extra chilli sauce on the side"
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Spicy and tangy hot and sour soup with macaroni - a fusion desi Chinese soup",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["soy", "gluten"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 4,
    calories: 280,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "macaroni", "stock", "soy sauce", "vinegar", "chilli garlic", "cornflour", "mixed vegetables"],
    searchKeywords: ["hot and sour macaroni soup", "spicy pasta soup", "chinese soup", "soup", "macaroni"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Pot Pie Soup",
    image: "Chicken-Pot-Pie-Soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "300g chicken - cut into small pieces",
      "2 carrots - chopped",
      "1 cup peas",
      "2 potatoes - chopped",
      "4 cups chicken stock",
      "1 cup milk",
      "2 tbsp flour",
      "Puff pastry sheets for topping",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Fry chicken in a pot until cooked, take out and keep aside",
      "In the same pot, fry vegetables until soft (about 8 minutes)",
      "Add flour and cook for 2 minutes",
      "Slowly add chicken stock and milk while whisking",
      "Put chicken back in the pot",
      "Cook for 20 minutes until soup becomes thick",
      "While soup cooks, cut puff pastry into small shapes and bake until golden",
      "Serve soup with crispy pastry pieces on top"
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "All the goodness of chicken pot pie in soup form - creamy and very satisfying",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy", "gluten"],
    budget: "economy",
    costPerServing: 45,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "carrots", "peas", "potatoes", "stock", "milk", "flour", "pastry"],
    searchKeywords: ["chicken pot pie soup", "pot pie soup", "chicken soup", "soup", "creamy"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Creamy Chicken Macaroni Soup",
    image: "creamy-chicken-macroni-soup.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "200g chicken - cut into small pieces",
      "1 cup macaroni",
      "4 cups chicken stock",
      "1 cup cream",
      "1 onion - chopped",
      "2 tbsp butter",
      "2 tbsp flour",
      "1 tsp mixed herbs",
      "Salt as needed",
      "Pepper as needed"
    ],
    stepsRaw: [
      "Cook macaroni in water until soft, drain and keep aside",
      "Fry chicken in a pot until cooked, take out and keep aside",
      "Melt butter in the same pot and fry onion until soft",
      "Add flour and cook for 2 minutes",
      "Slowly add chicken stock while whisking",
      "Add chicken and mixed herbs",
      "Cook for 15 minutes on low flame",
      "Add cream and cooked macaroni",
      "Heat through and serve"
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "Very creamy macaroni soup with chicken - rich, smooth and filling",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: ["dairy", "gluten"],
    budget: "economy",
    costPerServing: 40,
    baseServings: 4,
    calories: 360,
    ageGroup: ["adults", "seniors", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "macaroni", "stock", "cream", "onion", "butter", "flour", "herbs"],
    searchKeywords: ["creamy chicken macaroni soup", "creamy pasta soup", "macaroni soup", "soup", "chicken"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Herbal Soup",
    image: "herbal-soup.jpg",
    cuisine: "Chinese",
    ingredientsRaw: [
      "300g chicken",
      "10 red dates (khajoor)",
      "20g goji berries",
      "15g dried longan",
      "10g dried Chinese yam",
      "2 liters water",
      "Very little salt if you want"
    ],
    stepsRaw: [
      "Put chicken in boiling water for 5 minutes, then wash",
      "Put all ingredients in a big pot with water",
      "Bring to boil, then turn flame to low",
      "Cook for 1.5 to 2 hours until chicken is very soft",
      "Remove any foam that comes on top",
      "Add very little salt if you want",
      "Strain and serve hot",
      "Throw away the herbs before serving"
    ],
    difficulty: "Hard",
    cookingTime: 120,
    isActive: true,
    isHalal: true,
    description: "Chinese herbal soup that is very good for health - people drink it when feeling weak",
    category: "Dinner",
    subCategory: "soups",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    beverageCategory: null,
    allergens: [],
    budget: "economy",
    costPerServing: 40,
    baseServings: 4,
    calories: 180,
    ageGroup: ["adults", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "red dates", "goji berries", "longan", "yam"],
    searchKeywords: ["herbal soup", "chinese medicinal soup", "tonic soup", "soup", "healthy"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
];

async function migrate() {
  try {
    console.log('Connecting to MongoDB');
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) throw new Error('MongoDB URI not found');
    await mongoose.connect(mongoURI, { serverSelectionTimeoutMS: 10000, family: 4 });   
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log(`\nMigration Complete!`);
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    process.exit(0);
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrate();