const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
require('dotenv').config({ path: '../.env' });
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');

const recipesToMigrate = [
  {
    title: "Mutton Aloo",
    image: "http://localhost:5000/uploads/Mutton_Aloo.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (bone-in pieces)",
      "3 medium potatoes (cubed)",
      "2 onions (chopped)",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish",
      "Green chilies to garnish"
    ],
    stepsRaw: [
      "Heat oil, add cumin seeds, then fry onions until golden",
      "Add ginger-garlic paste, cook 2 mins",
      "Add mutton, fry until brown (8-10 mins)",
      "Add tomatoes, cook until soft and oil separates",
      "Add all spices and salt, mix well",
      "Add potatoes + 2 cups water, cover and cook 45-50 mins on low heat",
      "Sprinkle garam masala, garnish with coriander",
      "Serve with naan or rice"
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A rich and flavorful mutton and potato curry that's perfect for special occasions.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "potato", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["mutton aloo", "aloo mutton", "mutton potato curry", "pakistani mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Aloo Matar",
    image: "http://localhost:5000/uploads/Aloo-matar-mutton.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 potatoes (cubed)",
      "1 cup green peas",
      "2 onions",
      "2 tomatoes (blended)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions in oil until golden, add ginger-garlic paste",
      "Add mutton, brown it well",
      "Add blended tomatoes, cook until oil separates",
      "Add spices and salt",
      "Add potatoes + 2 cups water, cook 40-45 mins covered",
      "Add peas, cook 10-12 more mins",
      "Finish with garam masala and coriander"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A delicious mutton curry with potatoes and sweet peas.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 125,
    baseServings: 4,
    calories: 460,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "potato", "peas", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["mutton aloo matar", "aloo matar mutton", "mutton potato peas curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Aloo Baingan",
    image: "http://localhost:5000/uploads/aloo-baingan-mutton.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 potatoes (cubed)",
      "2 eggplants (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions in oil until golden, add ginger-garlic paste",
      "Brown the mutton well",
      "Add tomatoes, cook until soft",
      "Add spices and salt, then potatoes + 1.5 cups water",
      "Cook covered 40-45 mins until mutton is almost done",
      "Add eggplant, cook 12-15 mins gently (don't break pieces)",
      "Garnish and serve with roti"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A unique mutton curry with potatoes and eggplant in a rich masala gravy.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 440,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "potato", "eggplant", "baingan", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton aloo baingan", "aloo baingan mutton", "mutton eggplant potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Aloo Shimla Mirch",
    image: "http://localhost:5000/uploads/mutton-aloo-shimla-mirch.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 potatoes (cubed)",
      "2 capsicums (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Fry onions in oil, add ginger-garlic paste",
      "Brown the mutton, then add tomatoes and cook until soft",
      "Add spices and potatoes + 1.5 cups water",
      "Cook covered 40-45 mins on low heat",
      "Add capsicum, cook 5-7 mins (keep slightly crunchy)",
      "Sprinkle garam masala and serve"
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A colorful mutton curry with potatoes and bell peppers.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 430,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "potato", "capsicum", "shimla mirch", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["mutton aloo shimla mirch", "mutton capsicum", "mutton bell pepper curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Aloo Gobhi",
    image: "http://localhost:5000/uploads/mutton-aloo-ghobi.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 potatoes (cubed)",
      "1 cauliflower (small florets)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, then brown mutton",
      "Add tomatoes, cook until soft and oily",
      "Add spices + potatoes + 2 cups water",
      "Cook covered 40-45 mins",
      "Add cauliflower, cook 10-12 mins (don't overcook)",
      "Garnish with coriander and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A hearty mutton curry with potatoes and cauliflower.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 435,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "potato", "cauliflower", "gobhi", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton aloo gobhi", "aloo gobhi mutton", "mutton cauliflower curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Aloo Palak",
    image: "http://localhost:5000/uploads/mutton-aloo-palak.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 potatoes (cubed)",
      "500g spinach (blended smooth)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown the mutton",
      "Add tomatoes, cook until oil separates",
      "Add spices + potatoes + 1.5 cups water",
      "Cook covered 40-45 mins",
      "Add blended spinach, simmer 12-15 mins on low heat",
      "Sprinkle garam masala and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A healthy mutton curry with potatoes and spinach.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["mutton", "potato", "spinach", "palak", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton aloo palak", "aloo palak mutton", "mutton spinach curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Aloo Tamatar",
    image: "http://localhost:5000/uploads/mutton-aloo-tamatar.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 potatoes (cubed)",
      "4 ripe tomatoes (chopped)",
      "2 onions (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions in oil, add ginger-garlic paste",
      "Brown mutton well, then add lots of tomatoes",
      "Cook tomatoes 8-10 mins until very mushy and oil comes out",
      "Add spices + potatoes + 2 cups water",
      "Cook covered 45-50 mins until everything is soft",
      "Garnish and serve with roti"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A tangy mutton curry with potatoes and tomatoes.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 110,
    baseServings: 4,
    calories: 425,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "potato", "tomato", "tamatar", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton aloo tamatar", "aloo tamatar mutton", "mutton tomato potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Aloo Beans",
    image: "http://localhost:5000/uploads/mutton-aloo-beans.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 potatoes (sliced)",
      "200g green beans (1-inch pieces)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown the mutton",
      "Add tomatoes, cook until soft",
      "Add spices + potato slices + 1.5 cups water",
      "Cook covered 40-45 mins",
      "Add green beans, cook 12-15 mins until tender",
      "Serve with roti or paratha"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A wholesome mutton curry with potatoes and green beans.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 430,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "potato", "green beans", "beans", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton aloo beans", "aloo beans mutton", "mutton green beans curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Matar",
    image: "http://localhost:5000/uploads/mutton-matar.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (bone-in)",
      "1 cup green peas",
      "2 onions",
      "2 tomatoes (blended)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions until golden, add ginger-garlic paste",
      "Brown mutton on all sides",
      "Add blended tomatoes, cook until oil separates",
      "Add spices + 2 cups water, cook covered 45-50 mins",
      "Add peas, cook 10-12 mins more",
      "Finish with garam masala and coriander"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A classic mutton and peas curry with sweet and savory flavors.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 440,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["mutton matar", "matar mutton", "mutton peas curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Matar Malai",
    image: "http://localhost:5000/uploads/mutton-matar-malai.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless mutton (cubed)",
      "1 cup green peas",
      "1 cup heavy cream",
      "2 onions (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp white pepper",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add white pepper + salt + 1.5 cups water",
      "Cook covered 45-50 mins until mutton is very soft",
      "Add peas, cook 5-7 mins",
      "Turn heat to LOW, add cream, simmer gently 5-7 mins (do NOT boil)",
      "Sprinkle garam masala and serve"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A rich and creamy mutton curry with sweet peas.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 150,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "peas", "matar", "cream", "malai", "onion", "ginger", "garlic", "cumin", "white pepper", "garam masala"],
    searchKeywords: ["mutton matar malai", "creamy mutton peas", "malai mutton matar"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Matar Pulao",
    image: "http://localhost:5000/uploads/matar-mutton-pulao.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "1 cup green peas",
      "2 cups basmati rice (soaked 30 mins)",
      "2 onions (sliced)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "4 cloves",
      "2 cardamom",
      "1 cinnamon stick",
      "1 bay leaf",
      "1 tsp garam masala",
      "½ cup oil or ghee",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry whole spices in oil, then fry onions golden",
      "Add ginger-garlic paste, then brown mutton",
      "Add salt + 3 cups water, cook 30-35 mins until mutton is half done",
      "Add drained rice + peas, stir gently",
      "Cover tightly, cook on LOW 15-20 mins until rice is done",
      "Don't stir — rest 5 mins before serving"
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A one-pot mutton and peas rice pilaf.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 130,
    baseServings: 4,
    calories: 550,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "rice", "basmati", "peas", "matar", "onion", "ginger", "garlic", "cumin", "cloves", "cardamom", "cinnamon", "bay leaf", "garam masala"],
    searchKeywords: ["mutton matar pulao", "matar mutton pulao", "mutton peas rice"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Matar Korma",
    image: "http://localhost:5000/uploads/mutton-matar-qourma.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "1 cup green peas",
      "1 cup yogurt (beaten smooth)",
      "2 onions (sliced)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil or ghee",
      "Salt to taste",
      "Fried onions & coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions until golden brown, remove half for garnish",
      "Add ginger-garlic paste, then brown mutton",
      "Add spices + salt, then on LOW heat slowly stir in yogurt (don't rush or it curdles)",
      "Add 1 cup water, cook covered 45-50 mins",
      "Add peas, cook 10-12 mins",
      "Sprinkle garam masala, top with fried onions"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A royal Mughlai mutton and peas korma with yogurt-based gravy.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 140,
    baseServings: 4,
    calories: 500,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "peas", "matar", "yogurt", "dahi", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton matar korma", "matar mutton korma", "mutton peas korma"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Matar Keema",
    image: "http://localhost:5000/uploads/mutton-matar-keema.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "1 cup green peas",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste",
      "Add mince, fry 10-12 mins breaking all lumps until brown",
      "Add tomatoes, cook until soft",
      "Add spices + ½ cup water, cook covered 20-25 mins",
      "Add peas, cook 10-12 mins",
      "Finish with garam masala and coriander"
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A quick mutton mince curry with sweet peas.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 110,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "keema", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton matar keema", "keema matar", "mutton mince peas curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Palak",
    image: "http://localhost:5000/uploads/mutton-palak.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "500g fresh spinach (blended smooth)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes, cook until oily",
      "Add spices + 1.5 cups water, cook covered 45-50 mins",
      "Add spinach puree, simmer 12-15 mins on low heat",
      "Sprinkle garam masala and serve"
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A healthy mutton curry in spinach gravy.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 125,
    baseServings: 4,
    calories: 410,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["mutton", "spinach", "palak", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton palak", "palak mutton", "mutton spinach curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Palak Malai",
    image: "http://localhost:5000/uploads/mutton-palak-malai.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless mutton (cubed)",
      "500g spinach (blended)",
      "1 cup heavy cream",
      "2 onions",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add spices + 1.5 cups water, cook covered 45-50 mins",
      "Add spinach puree, cook 10-12 mins stirring",
      "On LOW heat add cream, simmer 5-7 mins (do NOT boil)",
      "Sprinkle garam masala and serve"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A rich creamy mutton spinach curry.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 145,
    baseServings: 4,
    calories: 510,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "spinach", "palak", "cream", "malai", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton palak malai", "creamy mutton spinach", "malai palak mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Palak Aloo",
    image: "http://localhost:5000/uploads/mutton-palak-aloo.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 potatoes (cubed)",
      "500g spinach (blended)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes, cook until soft",
      "Add spices + potatoes + 1.5 cups water, cook covered 45-50 mins",
      "Add spinach puree, simmer 12-15 mins",
      "Sprinkle garam masala and serve"
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A complete meal mutton curry with spinach and potatoes.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 125,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["mutton", "spinach", "palak", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton palak aloo", "aloo palak mutton", "mutton spinach potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Palak Matar",
    image: "http://localhost:5000/uploads/mutton-palak-matar.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "1 cup green peas",
      "500g spinach (blended)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes, cook until oily",
      "Add spices + 1.5 cups water, cook covered 45-50 mins",
      "Add peas + spinach puree together, cook 12-15 mins",
      "Sprinkle garam masala and serve"
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A nutritious mutton curry with spinach and peas.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 125,
    baseServings: 4,
    calories: 430,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["mutton", "spinach", "palak", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton palak matar", "palak matar mutton", "mutton spinach peas curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Shimla Mirch",
    image: "http://localhost:5000/uploads/mutton-shimla-mirch.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless mutton (cubed)",
      "3 capsicums (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes, cook until soft",
      "Add spices + 1.5 cups water, cook covered 45-50 mins",
      "Add capsicum, cook 5-7 mins (keep a little crunchy)",
      "Sprinkle garam masala and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A colorful mutton curry with capsicum.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 430,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["mutton", "capsicum", "shimla mirch", "bell pepper", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala"],
    searchKeywords: ["mutton shimla mirch", "mutton capsicum", "mutton bell pepper curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Shimla Mirch Aloo",
    image: "http://localhost:5000/uploads/mutton-shimla-mirch.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 potatoes (cubed)",
      "2 capsicums (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes, cook until soft",
      "Add spices + potatoes + 1.5 cups water, cook covered 45-50 mins",
      "Add capsicum, cook 5-7 mins",
      "Serve with roti or naan"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A hearty mutton curry with capsicum and potatoes.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["mutton", "capsicum", "shimla mirch", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton shimla mirch aloo", "aloo shimla mirch mutton", "mutton capsicum potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Shimla Mirch Matar",
    image: "http://localhost:5000/uploads/mutton-shimla-mirch-matar.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 capsicums (cubed)",
      "1 cup green peas",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add peas, cook 5-7 mins, then add capsicum, cook 5-7 more mins",
      "Serve with roti"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A colorful mutton curry with capsicum and peas.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 435,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["mutton", "capsicum", "shimla mirch", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton shimla mirch matar", "matar shimla mirch mutton", "mutton capsicum peas curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Shimla Mirch Pyaz",
    image: "http://localhost:5000/uploads/mutton-shimla-mirch-pyaz.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless mutton (strips)",
      "2 capsicums (strips)",
      "2 onions (sliced, divided)",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Fry half the onions in oil, add ginger-garlic paste",
      "Brown mutton strips well",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Turn heat HIGH, add capsicum strips + remaining raw onions",
      "Stir fry 5-7 mins until veggies are tender-crisp and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A simple mutton curry with capsicum and onions.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 425,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["mutton", "capsicum", "shimla mirch", "onion", "pyaz", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton shimla mirch pyaz", "pyaz shimla mirch mutton", "mutton capsicum onion curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Gobhi",
    image: "http://localhost:5000/uploads/mutton-ghobi.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "1 cauliflower (small florets)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add cauliflower, cook 10-12 mins (don't make it mushy)",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A healthy mutton curry with cauliflower.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 410,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "cauliflower", "gobhi", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton gobhi", "gobhi mutton", "mutton cauliflower curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Gobhi Aloo",
    image: "http://localhost:5000/uploads/mutton-ghobi-aloo.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "1 cauliflower (florets)",
      "2 potatoes (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + potatoes + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add cauliflower, cook 10-12 mins",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A hearty mutton curry with cauliflower and potatoes.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 440,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "cauliflower", "gobhi", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton gobhi aloo", "aloo gobhi mutton", "mutton cauliflower potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Gobhi Matar",
    image: "http://localhost:5000/uploads/mutton-matar-ghobi.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "1 cauliflower (florets)",
      "1 cup green peas",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Add cauliflower + peas together, cook 10-12 mins",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A nutritious mutton curry with cauliflower and peas.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 425,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "cauliflower", "gobhi", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton gobhi matar", "matar gobhi mutton", "mutton cauliflower peas curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Baingan",
    image: "http://localhost:5000/uploads/mutton-baingan.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 eggplants (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Add eggplant gently, cook 10-12 mins (handle carefully)",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A unique mutton curry with eggplant.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 430,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "eggplant", "baingan", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton baingan", "baingan mutton", "mutton eggplant curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Baingan Aloo",
    image: "http://localhost:5000/uploads/mutton-aloo-baingan.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 eggplants (cubed)",
      "2 potatoes (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + potatoes + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add eggplant, cook 10-12 mins",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A hearty mutton curry with eggplant and potatoes.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "eggplant", "baingan", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton baingan aloo", "aloo baingan mutton", "mutton eggplant potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Baingan Bharta",
    image: "http://localhost:5000/uploads/mutton-baingan-bharta.png",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "2 large eggplants (roasted & mashed)",
      "2 green chilies",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Roast eggplants on gas flame until skin is black and flesh is soft (10-15 mins, turn often)",
      "Cool, peel off charred skin, mash the flesh and keep aside",
      "Fry onions, add ginger-garlic paste, brown the mince (break all lumps)",
      "Add tomatoes + green chilies, cook until oily",
      "Add spices, then add mashed eggplant, mix well, cook 8-10 mins",
      "Sprinkle garam masala and serve"
    ],
    difficulty: "Hard",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A smoky mutton mince curry with mashed eggplant.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 125,
    baseServings: 4,
    calories: 460,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "keema", "eggplant", "baingan", "bharta", "onion", "tomato", "green chili", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton baingan bharta", "baingan bharta mutton", "smoky mutton eggplant"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Tori",
    image: "http://localhost:5000/uploads/mutton-tori.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "500g tori/ridge gourd (peeled & cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Add tori, cook 10-12 mins (tori releases water, gravy becomes thinner — that's normal)",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A light mutton curry with ridge gourd.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "tori", "ridge gourd", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton tori", "tori mutton", "mutton ridge gourd curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Louki",
    image: "http://localhost:5000/uploads/Mutton-Lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "500g louki/bottle gourd (peeled & cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Add louki, cook 12-15 mins until soft and translucent",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A light and nutritious mutton curry with bottle gourd.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 395,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "louki", "bottle gourd", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton louki", "louki mutton", "mutton bottle gourd curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Tori Aloo",
    image: "http://localhost:5000/uploads/Mutton-Tori-Aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "400g tori (cubed)",
      "2 potatoes (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + potatoes + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add tori, cook 10-12 mins",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A wholesome mutton curry with ridge gourd and potatoes.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "tori", "ridge gourd", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton tori aloo", "aloo tori mutton", "mutton ridge gourd potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Karela",
    image: "http://localhost:5000/uploads/Mutton-Karela.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "3 karela/bitter gourds (thinly sliced)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp dry mango powder (amchur)",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Rub karela with salt, wait 30 mins, rinse well and squeeze out bitter juice",
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Add karela, cook 10-12 mins",
      "Sprinkle amchur powder, garnish and serve"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A unique mutton curry with bitter gourd.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes"],
    pantryKeywords: ["mutton", "karela", "bitter gourd", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "amchur"],
    searchKeywords: ["mutton karela", "karela mutton", "mutton bitter gourd curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Karela Aloo",
    image: "http://localhost:5000/uploads/Mutton-Karela-Aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 karela (sliced)",
      "2 potatoes (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp amchur",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Salt karela, rest 30 mins, rinse and squeeze dry",
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + potatoes + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add karela, cook 10-12 mins",
      "Sprinkle amchur, garnish and serve"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A balanced mutton curry with bitter gourd and potatoes.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 440,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes"],
    pantryKeywords: ["mutton", "karela", "bitter gourd", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "amchur"],
    searchKeywords: ["mutton karela aloo", "aloo karela mutton", "mutton bitter gourd potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Karela Masala",
    image: "http://localhost:5000/uploads/Mutton-Karela-Masala.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "3 karela (sliced)",
      "2 onions",
      "2 tomatoes (blended)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Salt karela, rest 30 mins, rinse and squeeze dry",
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add blended tomatoes, cook until oil separates",
      "Add spices + 1.5 cups water, cook covered 45-50 mins",
      "Add karela, cook 10-12 mins",
      "Sprinkle garam masala, garnish and serve"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A spicy mutton curry with bitter gourd.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 430,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "karela", "bitter gourd", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton karela masala", "spicy mutton karela", "masala karela mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Methi",
    image: "http://localhost:5000/uploads/Mutton-Methi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "1 big bunch fresh methi leaves (finely chopped)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Add methi leaves, cook 5-7 mins until they wilt",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "An aromatic mutton curry with fresh fenugreek leaves.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 430,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes"],
    pantryKeywords: ["mutton", "methi", "fenugreek leaves", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton methi", "methi mutton", "mutton fenugreek curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Methi Malai",
    image: "http://localhost:5000/uploads/Mutton-Methi-Malai.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless mutton (cubed)",
      "1 big bunch methi (chopped)",
      "1 cup heavy cream",
      "2 onions",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp white pepper",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add white pepper + salt + 1.5 cups water, cook covered 45-50 mins",
      "Add methi, cook 5-7 mins",
      "On LOW heat add cream, simmer gently 5-7 mins (do NOT boil)",
      "Sprinkle garam masala and serve"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A rich creamy mutton curry with fenugreek leaves.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 145,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "methi", "fenugreek leaves", "cream", "malai", "onion", "ginger", "garlic", "cumin", "white pepper", "garam masala"],
    searchKeywords: ["mutton methi malai", "creamy mutton methi", "malai methi mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Methi Aloo",
    image: "http://localhost:5000/uploads/Mutton-Methi-Aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "1 big bunch methi (chopped)",
      "2 potatoes (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + potatoes + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add methi, cook 5-7 mins until wilted",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A hearty winter mutton curry with fenugreek and potatoes.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes"],
    pantryKeywords: ["mutton", "methi", "fenugreek leaves", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili"],
    searchKeywords: ["mutton methi aloo", "aloo methi mutton", "mutton fenugreek potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Beans",
    image: "http://localhost:5000/uploads/Mutton-Beans.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless mutton (cubed)",
      "200g green beans (1-inch pieces)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Add green beans, cook 12-15 mins",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A simple mutton curry with green beans.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "green beans", "beans", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton beans", "beans mutton", "mutton green beans curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Beans Aloo",
    image: "http://localhost:5000/uploads/Mutton-Beans-Aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "200g green beans (chopped)",
      "2 potatoes (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + potatoes + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add beans, cook 12-15 mins",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A wholesome mutton curry with beans and potatoes.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 440,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "green beans", "beans", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton beans aloo", "aloo beans mutton", "mutton beans potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Beans Matar",
    image: "http://localhost:5000/uploads/Mutton-Beans-Matar.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "200g green beans (chopped)",
      "1 cup green peas",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Add beans + peas together, cook 12-15 mins",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A colorful mutton curry with beans and peas.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 430,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "green beans", "beans", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton beans matar", "matar beans mutton", "mutton beans peas curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Tinday",
    image: "http://localhost:5000/uploads/Mutton-Beans-Matar.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "500g tinday/apple gourd (peeled & cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Add tinday, cook 12-15 mins until tender",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A light mutton curry with apple gourd.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 395,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "tinday", "apple gourd", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton tinday", "tinday mutton", "mutton apple gourd curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Kaddu",
    image: "http://localhost:5000/uploads/mutton-kaddu.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "500g kaddu/pumpkin (peeled & cubed)",
      "1 tbsp jaggery or brown sugar",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Add pumpkin + jaggery, cook 12-15 mins until soft",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A sweet and savory mutton curry with pumpkin.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 430,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes"],
    pantryKeywords: ["mutton", "kaddu", "pumpkin", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "jaggery"],
    searchKeywords: ["mutton kaddu", "kaddu mutton", "mutton pumpkin curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Kaddu Aloo",
    image: "http://localhost:5000/uploads/Mutton-Kadu-Aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "300g pumpkin (cubed)",
      "2 potatoes (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + potatoes + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add pumpkin, cook 12-15 mins",
      "Garnish and serve"
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A hearty winter mutton curry with pumpkin and potatoes.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 115,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "kaddu", "pumpkin", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton kaddu aloo", "aloo kaddu mutton", "mutton pumpkin potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Kaddu Ka Bharta",
    image: "http://localhost:5000/uploads/Mutton-Kadu-Ka-Bharta.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "500g pumpkin (roasted & mashed)",
      "2 green chilies",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Roast pumpkin in oven until soft, peel and mash — keep aside",
      "Fry onions, add ginger-garlic paste, brown mince (break all lumps)",
      "Add tomatoes + green chilies + spices, cook until oily",
      "Add mashed pumpkin, mix well, cook 8-10 mins",
      "Sprinkle garam masala, garnish and serve"
    ],
    difficulty: "Hard",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A unique mutton mince curry with mashed pumpkin.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 125,
    baseServings: 4,
    calories: 460,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "keema", "kaddu", "pumpkin", "bharta", "onion", "tomato", "green chili", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton kaddu ka bharta", "kaddu bharta mutton", "mashed pumpkin mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Arvi",
    image: "http://localhost:5000/uploads/mutton-arvi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "500g arvi/colocasia (boiled & peeled)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Boil arvi 20 mins until tender, cool, peel and slice — keep aside",
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + 1.5 cups water, cook covered 45-50 mins",
      "Add arvi slices gently, cook 8-10 mins (don't break them)",
      "Garnish and serve"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A unique mutton curry with colocasia (arvi).",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 430,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "arvi", "colocasia", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton arvi", "arvi mutton", "mutton colocasia curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Arvi Aloo",
    image: "http://localhost:5000/uploads/mutton-arvi-aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "300g arvi (boiled & peeled)",
      "2 potatoes (cubed)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Boil arvi, peel and slice — keep aside",
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + potatoes + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add arvi gently, cook 8-10 mins",
      "Garnish and serve"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A hearty mutton curry with colocasia and potatoes.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 460,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "arvi", "colocasia", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton arvi aloo", "aloo arvi mutton", "mutton colocasia potato curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Mix Vegetable",
    image: "http://localhost:5000/uploads/mutton-mix-veg.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "1 cup cauliflower florets",
      "1 cup green peas",
      "1 cup carrots (cubed)",
      "1 cup green beans",
      "2 potatoes (cubed)",
      "2 onions",
      "2 tomatoes (blended)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add blended tomatoes + spices + potatoes + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add all remaining vegetables, cook 12-15 mins",
      "Sprinkle garam masala, garnish and serve"
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A complete nutritious mutton curry with mixed vegetables.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 130,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "mixed vegetables", "cauliflower", "peas", "carrots", "beans", "potato", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton mix vegetable", "mixed vegetable mutton curry", "mutton veg curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Jalfrezi",
    image: "http://localhost:5000/uploads/mutton-jalfrezi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g boneless mutton (strips)",
      "1 capsicum (strips)",
      "1 carrot (sliced)",
      "1 onion (sliced)",
      "1 tomato (wedges)",
      "2 tbsp ginger-garlic paste",
      "1 tbsp soy sauce",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions on HIGH heat, add ginger-garlic paste",
      "Brown mutton strips, add spices + 1 cup water",
      "Cook covered 45-50 mins until tender",
      "Add all vegetables on HIGH heat, stir fry 5-7 mins (keep crunchy)",
      "Add soy sauce, mix well, sprinkle garam masala and serve"
    ],
    difficulty: "Hard",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A restaurant-style mutton curry with mixed vegetables.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["soy"],
    budget: "standard",
    costPerServing: 130,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "capsicum", "carrot", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala", "soy sauce"],
    searchKeywords: ["mutton jalfrezi", "jalfrezi mutton", "mutton veg jalfrezi"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Karahi with Veggies",
    image: "http://localhost:5000/uploads/mutton-karahi-veggies.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton (bone-in)",
      "2 tomatoes (chopped)",
      "1 capsicum (sliced)",
      "1 onion (sliced)",
      "2 green chilies",
      "1 tbsp ginger (julienned)",
      "1 tsp cumin seeds",
      "1 tsp red chili flakes",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok (karahi) on HIGH heat, fry mutton until well-browned",
      "Add ginger juliennes + green chilies, fry 2-3 mins",
      "Add tomatoes, cook until mushy",
      "Add spices + 1 cup water, cook covered 45-50 mins",
      "Add capsicum + onion slices, cook on HIGH 3-4 mins (keep slightly crunchy)",
      "Sprinkle garam masala, garnish and serve with naan"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A traditional Pakistani karahi with mutton and vegetables.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 125,
    baseServings: 4,
    calories: 470,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "karahi", "capsicum", "onion", "tomato", "ginger", "green chili", "cumin", "red chili flakes", "garam masala"],
    searchKeywords: ["mutton karahi with veggies", "mutton vegetable karahi", "karahi mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Handi with Veg",
    image: "http://localhost:5000/uploads/mutton-handi-veg.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "1 cup mixed vegetables (carrots, peas, beans)",
      "1 cup yogurt (beaten smooth)",
      "2 onions",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions in a handi/heavy pot, add ginger-garlic paste, brown mutton",
      "Add spices, then on LOW heat slowly stir in yogurt (don't rush or it curdles)",
      "Add 1 cup water, cook covered 45-50 mins",
      "Add vegetables, cook 12-15 mins",
      "Sprinkle garam masala, garnish and serve"
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A rich slow-cooked mutton curry with vegetables.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 140,
    baseServings: 4,
    calories: 500,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "handi", "mixed vegetables", "yogurt", "dahi", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton handi with veg", "mutton vegetable handi", "handi mutton"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Vegetable Curry",
    image: "http://localhost:5000/uploads/mutton-veg-curry.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 cups mixed vegetables (carrots, peas, beans, cauliflower)",
      "2 onions",
      "2 tomatoes (blended)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp coriander powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add blended tomatoes + spices + 1.5 cups water",
      "Cook covered 45-50 mins",
      "Add all vegetables, cook 12-15 mins",
      "Garnish and serve with rice or roti"
    ],
    difficulty: "Medium",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A simple comforting mutton curry with mixed vegetables.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 125,
    baseServings: 4,
    calories: 460,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "mixed vegetables", "carrots", "peas", "beans", "cauliflower", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander"],
    searchKeywords: ["mutton vegetable curry", "veg mutton curry", "simple mutton curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Saag",
    image: "http://localhost:5000/uploads/mutton-saag.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "500g mustard greens/sarson (chopped & blended)",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Boil mustard greens 10-15 mins, drain and blend to coarse paste — keep aside",
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices + saag paste + 1 cup water",
      "Cook covered 45-50 mins until mutton is fully tender",
      "Sprinkle garam masala, serve with makai roti or naan"
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A Punjabi winter mutton curry with mustard greens.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 125,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "saag", "mustard greens", "sarson", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton saag", "saag mutton", "mutton mustard greens curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Sarson Ka Saag",
    image: "http://localhost:5000/uploads/mutton-sarson-ka-saag.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "500g sarson/mustard greens",
      "100g bathua (optional)",
      "1 tbsp cornmeal",
      "2 onions",
      "2 tomatoes (chopped)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "½ cup oil",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Boil mustard greens (+ bathua if using) 10-15 mins, blend to coarse paste",
      "Fry onions, add ginger-garlic paste, brown mutton",
      "Add tomatoes + spices, cook until oily",
      "Add saag paste + cornmeal mixed with a little water",
      "Simmer covered 45-50 mins stirring occasionally until mutton is done",
      "Serve with makai ki roti"
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "An authentic Punjabi mutton curry with mustard greens.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 125,
    baseServings: 4,
    calories: 455,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "sarson ka saag", "mustard greens", "bathua", "cornmeal", "makki ka atta", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili"],
    searchKeywords: ["mutton sarson ka saag", "sarson ka saag mutton", "punjabi mutton saag"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Lauki Kofta",
    image: "http://localhost:5000/uploads/mutton-lauki-kofta.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "500g lauki (grated, water squeezed out)",
      "1 cup gram flour (besan)",
      "2 onions",
      "2 tomatoes (blended)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "Oil for deep frying + 2 tbsp oil for gravy",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Mix mince + grated lauki + besan + salt, shape into small balls",
      "Deep fry the kofta balls until golden brown, drain and keep aside",
      "In a separate pan fry onions, add ginger-garlic paste",
      "Add blended tomatoes + spices + 2 cups water, bring to boil",
      "Add fried kofta, simmer on LOW 8-10 mins",
      "Sprinkle garam masala, garnish and serve"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A unique mutton curry with bottle gourd dumplings.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 150,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "keema", "lauki", "bottle gourd", "besan", "gram flour", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton lauki kofta", "lauki kofta mutton", "mutton bottle gourd kofta"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Vegetable Pulao",
    image: "http://localhost:5000/uploads/mutton-veg-pulao.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton",
      "2 cups basmati rice (soaked 30 mins)",
      "1 cup mixed vegetables (carrots, peas, beans)",
      "2 onions (sliced)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "4 cloves",
      "2 cardamom",
      "1 cinnamon stick",
      "1 bay leaf",
      "1 tsp garam masala",
      "½ cup oil or ghee",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Fry whole spices in oil, then fry onions golden",
      "Add ginger-garlic paste, then brown mutton",
      "Add vegetables + salt + 3 cups water, cook 30-35 mins (mutton half done)",
      "Add drained rice, stir gently",
      "Cover tightly, cook on LOW 15-20 mins until rice is done",
      "Don't stir — rest 5 mins, sprinkle garam masala and serve"
    ],
    difficulty: "Hard",
    cookingTime: 70,
    isActive: true,
    isHalal: true,
    description: "A fragrant one-pot rice dish with mutton and vegetables.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 135,
    baseServings: 4,
    calories: 560,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "rice", "basmati", "mixed vegetables", "carrots", "peas", "beans", "onion", "ginger", "garlic", "cumin", "cloves", "cardamom", "cinnamon", "bay leaf", "garam masala"],
    searchKeywords: ["mutton vegetable pulao", "veg mutton pulao", "mutton veg rice"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Pumpkin Kofta",
    image: "http://localhost:5000/uploads/mutton-pumpkin-kofta.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton mince",
      "500g pumpkin (grated, water squeezed out)",
      "1 cup besan (gram flour)",
      "2 onions",
      "2 tomatoes (blended)",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "1 tsp turmeric powder",
      "2 tsp red chili powder",
      "1 tsp garam masala",
      "Oil for deep frying + 2 tbsp oil for gravy",
      "Salt to taste",
      "Fresh coriander to garnish"
    ],
    stepsRaw: [
      "Mix mince + grated pumpkin + besan + salt, shape into small balls",
      "Deep fry kofta until golden brown, drain and keep aside",
      "In a separate pan fry onions, add ginger-garlic paste",
      "Add blended tomatoes + spices + 2 cups water, bring to boil",
      "Add fried kofta, simmer on LOW 8-10 mins",
      "Sprinkle garam masala, garnish and serve"
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A unique mutton and pumpkin dumplings curry.",
    category: "Lunch",
    subCategory: "plain-vegetables",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 145,
    baseServings: 4,
    calories: 510,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton mince", "keema", "kaddu", "pumpkin", "besan", "gram flour", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala"],
    searchKeywords: ["mutton pumpkin kofta", "pumpkin kofta mutton", "mutton kaddu kofta"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
];

async function migrateRecipes() {
  try {
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    
    if (!mongoURI) {
      throw new Error('MongoDB URI not found in environment variables');
    }
    
    console.log('Connecting to MongoDB...');
    
    await mongoose.connect(mongoURI, {
      serverSelectionTimeoutMS: 10000,
      family: 4
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();