const dns = require('dns');
dns.setServers(['8.8.8.8', '1.1.1.1']);
require('dotenv').config({ path: '../.env' });
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');

const recipesToMigrate = [
  {
    title: "Chicken Aloo",
    image: "http://localhost:5000/uploads/chicken-aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "3 potatoes - peeled and cut into cubes",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste",
      "Fresh coriander leaves",
      "2 green chilies"
    ],
    stepsRaw: [
      "Put oil in a pot and heat it.",
      "Add cumin seeds and let them crackle.",
      "Add onions and fry until golden brown.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix well.",
      "Add potatoes and 1 cup warm water. Mix.",
      "Cover and cook for 25-30 minutes until chicken and potatoes are tender.",
      "Add garam masala. Put coriander leaves and green chilies on top.",
      "Serve hot with naan, roti or rice."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Easy and tasty chicken curry with potatoes. Good for everyday meals.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "potato", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken aloo", "aloo chicken", "chicken potato curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Aloo Matar",
    image: "http://localhost:5000/uploads/chicken-aloo-matar.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - curry cut pieces",
      "2 potatoes - peeled and cut into cubes",
      "1 cup green peas",
      "2 onions - finely chopped",
      "2 tomatoes - blended",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste",
      "Fresh coriander leaves"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry until it turns white.",
      "Add tomato puree and cook until oil separates.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add potatoes and 1 cup warm water. Cover and cook for 15 minutes.",
      "Add peas and cook for 10 more minutes.",
      "Add garam masala and put coriander leaves on top.",
      "Serve hot with naan, roti or paratha."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Tasty chicken curry with potatoes and sweet peas. Good for family dinner.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "potato", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken aloo matar", "aloo matar chicken", "chicken potato peas curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Aloo Baingan",
    image: "http://localhost:5000/uploads/chicken-aloo-baingan.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "2 potatoes - peeled and cut into cubes",
      "2 eggplants - cut into cubes",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste",
      "Fresh coriander leaves"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add potatoes and half cup warm water. Cover and cook for 10 minutes.",
      "Add eggplants and mix gently. Cover and cook for 15 minutes.",
      "Put coriander leaves on top.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Different and tasty chicken curry with potatoes and eggplant.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 385,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "potato", "eggplant", "baingan", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken aloo baingan", "aloo baingan chicken", "chicken eggplant potato curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Aloo Shimla Mirch",
    image: "http://localhost:5000/uploads/chicken-aloo-shimla-mirch.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - boneless, cut into cubes",
      "2 potatoes - peeled and cut into cubes",
      "2 capsicums - cut into cubes",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add potatoes and half cup warm water. Cover and cook for 15 minutes.",
      "Add capsicums and cook for 5-7 minutes.",
      "Add garam masala and serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Colorful chicken curry with potatoes and capsicum. Good for hearty meal.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 370,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "potato", "capsicum", "shimla mirch", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken aloo shimla mirch", "chicken capsicum", "chicken bell pepper curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Aloo Gobhi",
    image: "http://localhost:5000/uploads/chicken-aloo-ghobi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "2 potatoes - peeled and cut into cubes",
      "1 cauliflower - cut into small pieces",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste",
      "Fresh coriander leaves"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add potatoes and 1 cup warm water. Cover and cook for 15 minutes.",
      "Add cauliflower and cook for 10-12 minutes.",
      "Put coriander leaves on top.",
      "Serve hot with roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Filling chicken curry with potatoes and cauliflower. Full of flavor.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 375,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "potato", "cauliflower", "gobhi", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken aloo gobhi", "aloo gobhi chicken", "chicken cauliflower curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Aloo Palak",
    image: "http://localhost:5000/uploads/chicken-aloo-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "2 potatoes - peeled and cut into cubes",
      "500g fresh spinach - blended",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili and salt. Mix and cook for 2 minutes.",
      "Add potatoes and half cup warm water. Cover and cook for 15 minutes.",
      "Add spinach and mix well. Cook on low flame for 10 minutes.",
      "Add garam masala and serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Healthy chicken curry with spinach and potatoes. Good for nutrition.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 360,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["chicken", "potato", "spinach", "palak", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken aloo palak", "aloo palak chicken", "chicken spinach potato curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Aloo Tamatar",
    image: "http://localhost:5000/uploads/chicken-aloo-tamatar.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "2 potatoes - peeled and cut into cubes",
      "4 tomatoes - finely chopped",
      "2 onions - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook for 8-10 minutes until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add potatoes and 1 cup warm water. Cover and cook for 20-25 minutes.",
      "Serve hot with roti, naan or paratha."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Tangy chicken curry with potatoes and tomatoes. Good for tomato gravy lovers.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 75,
    baseServings: 4,
    calories: 365,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "potato", "tomato", "tamatar", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken aloo tamatar", "aloo tamatar chicken", "chicken tomato potato curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Aloo Beans",
    image: "http://localhost:5000/uploads/chicken-aloo-beans.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - boneless, cut into cubes",
      "2 potatoes - peeled and sliced",
      "200g fresh green beans - cut into 1 inch pieces",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add potatoes and half cup warm water. Cover and cook for 10 minutes.",
      "Add green beans and cook for 10 more minutes.",
      "Serve hot with roti or paratha."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Healthy chicken curry with potatoes and green beans. Complete family meal.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 370,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "potato", "green beans", "beans", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken aloo beans", "aloo beans chicken", "chicken green beans curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Matar",
    image: "http://localhost:5000/uploads/chicken-matar.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup green peas",
      "2 onions - finely chopped",
      "2 tomatoes - blended",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste",
      "Fresh coriander leaves"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry until it turns white.",
      "Add tomato puree and cook until oil separates.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add 1 cup warm water. Cover and cook for 20 minutes.",
      "Add peas and cook for 10 more minutes.",
      "Add garam masala and put coriander leaves on top.",
      "Serve hot with naan, roti or rice."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Simple chicken and peas curry. Sweet and savory flavors.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 370,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken matar", "matar chicken", "chicken peas curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Matar Malai",
    image: "http://localhost:5000/uploads/chicken-matar-malai.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - boneless, cut into cubes",
      "1 cup green peas",
      "1 cup heavy cream",
      "2 onions - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon white pepper powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste",
      "Fresh coriander leaves"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry until it turns white.",
      "Add white pepper and salt. Mix and cook for 2 minutes.",
      "Add half cup warm water and cook for 15 minutes.",
      "Add peas and cook for 5 minutes.",
      "Add cream and cook on low flame for 5 minutes. Do not boil.",
      "Add garam masala and put coriander leaves on top.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Rich and creamy chicken curry with peas. Good for special occasions.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 110,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "peas", "matar", "cream", "malai", "onion", "ginger", "garlic", "cumin", "white pepper", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken matar malai", "creamy chicken peas", "malai chicken matar", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Matar Pulao",
    image: "http://localhost:5000/uploads/chicken-matar-pulao.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup green peas",
      "2 cups basmati rice - washed and soaked",
      "2 onions - thinly sliced",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "4 cloves",
      "2 green cardamoms",
      "1 small cinnamon stick",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Wash rice and soak in water for 30 minutes. Then drain.",
      "Heat oil in a big pot.",
      "Add cloves, cardamom, cinnamon and cumin seeds. Let them crackle.",
      "Add onions and fry until golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add salt and 3 cups warm water. Boil for 10 minutes.",
      "Add rice and peas. Mix gently.",
      "Cover and cook on low flame for 15-20 minutes until rice is done.",
      "Add garam masala and serve hot with yogurt."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "One pot chicken and peas rice. Complete and satisfying meal.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 90,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "rice", "basmati", "peas", "matar", "onion", "ginger", "garlic", "cumin", "cloves", "cardamom", "cinnamon", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken matar pulao", "matar chicken pulao", "chicken peas rice", "pakistani pulao"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Matar Korma",
    image: "http://localhost:5000/uploads/chicken-matar-korma.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup green peas",
      "1 cup plain yogurt - beaten",
      "2 onions - thinly sliced",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste",
      "Fresh coriander leaves"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add onions and fry until golden brown.",
      "Take out half of the onions and keep aside.",
      "Add ginger garlic paste to the remaining onions and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add turmeric, red chili and salt. Mix well.",
      "Turn flame to low. Add yogurt slowly while stirring.",
      "Add half cup warm water and cook for 20 minutes.",
      "Add peas and cook for 10 minutes.",
      "Add garam masala and put fried onions and coriander leaves on top.",
      "Serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Rich and flavorful chicken and peas korma. Good for special occasions.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 100,
    baseServings: 4,
    calories: 460,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "peas", "matar", "yogurt", "dahi", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken matar korma", "matar chicken korma", "chicken peas korma", "pakistani korma"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Matar Keema",
    image: "http://localhost:5000/uploads/chicken-matar-keema.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken mince",
      "1 cup green peas",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste",
      "Fresh coriander leaves"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken mince and fry for 5-7 minutes until color changes.",
      "Add tomatoes and cook for 5-6 minutes until soft.",
      "Add turmeric, red chili and salt. Mix and cook for 5 minutes.",
      "Add half cup warm water and cook for 15 minutes.",
      "Add peas and cook for 10 minutes.",
      "Add garam masala and put coriander leaves on top.",
      "Serve hot with naan, paratha or roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Quick and tasty chicken mince curry with peas. Good for busy weekdays.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 75,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken mince", "keema", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken matar keema", "keema matar chicken", "chicken mince peas curry", "pakistani keema"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Palak",
    image: "http://localhost:5000/uploads/chicken-palak.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "500g fresh spinach - blended",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili and salt. Mix and cook for 2 minutes.",
      "Add half cup warm water and cook for 15 minutes.",
      "Add spinach and mix well. Cook on low flame for 10 minutes.",
      "Add garam masala and serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Healthy chicken curry in spinach gravy. Good for iron and protein.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 350,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["chicken", "spinach", "palak", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken palak", "palak chicken", "chicken spinach curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Palak Malai",
    image: "http://localhost:5000/uploads/chicken-palak-malai.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - boneless, cut into cubes",
      "500g fresh spinach - blended",
      "1 cup heavy cream",
      "2 onions - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add turmeric, red chili and salt. Mix and cook for 2 minutes.",
      "Add spinach and cook for 10 minutes.",
      "Add cream and cook on low flame for 5 minutes. Do not boil.",
      "Add garam masala and serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Rich and creamy chicken spinach curry. Smooth and luxurious gravy.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "premium",
    costPerServing: 105,
    baseServings: 4,
    calories: 470,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "spinach", "palak", "cream", "malai", "onion", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken palak malai", "creamy chicken spinach", "malai chicken palak", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Palak Aloo",
    image: "http://localhost:5000/uploads/chicken-palak-aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "2 potatoes - peeled and cut into cubes",
      "500g fresh spinach - blended",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili and salt. Mix and cook for 2 minutes.",
      "Add potatoes and 1 cup warm water. Cover and cook for 15 minutes.",
      "Add spinach and mix well. Cook for 10 minutes.",
      "Add garam masala and serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Complete meal chicken curry with spinach and potatoes. Full of nutrition.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["chicken", "spinach", "palak", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken palak aloo", "aloo palak chicken", "chicken spinach potato curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Palak Matar",
    image: "http://localhost:5000/uploads/chicken-palak-matar.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cup green peas",
      "500g fresh spinach - blended",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili and salt. Mix and cook for 2 minutes.",
      "Add half cup warm water and cook for 15 minutes.",
      "Add peas and spinach. Mix well and cook for 10 minutes.",
      "Add garam masala and serve hot with roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Nutritious chicken curry with spinach and peas. Packed with vegetables.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 370,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["chicken", "spinach", "palak", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken palak matar", "palak matar chicken", "chicken spinach peas curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Shimla Mirch",
    image: "http://localhost:5000/uploads/chicken-shimla-mirch.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - boneless, cut into cubes",
      "3 capsicums - cut into cubes",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add half cup warm water and cook for 15 minutes.",
      "Add capsicums and cook for 5-7 minutes.",
      "Add garam masala and serve hot with naan or roti."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Colorful chicken curry with capsicum. Good for a vibrant family meal.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 360,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["chicken", "capsicum", "shimla mirch", "bell pepper", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken shimla mirch", "chicken capsicum", "chicken bell pepper curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Shimla Mirch Aloo",
    image: "http://localhost:5000/uploads/chicken-shimla-mirch-aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "2 potatoes - peeled and cut into cubes",
      "2 capsicums - cut into cubes",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add potatoes and half cup warm water. Cover and cook for 15 minutes.",
      "Add capsicums and cook for 5 minutes.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Hearty chicken curry with capsicum and potatoes. Good for family dinner.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["chicken", "capsicum", "shimla mirch", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken shimla mirch aloo", "aloo shimla mirch chicken", "chicken capsicum potato curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Shimla Mirch Matar",
    image: "http://localhost:5000/uploads/chicken-shimla-mirch.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "2 capsicums - cut into cubes",
      "1 cup green peas",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add half cup warm water and cook for 15 minutes.",
      "Add peas and cook for 5 minutes.",
      "Add capsicums and cook for 5 more minutes.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Colorful chicken curry with capsicum and peas. Good for a vibrant meal.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 375,
    ageGroup: ["adults"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["chicken", "capsicum", "shimla mirch", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken shimla mirch matar", "matar shimla mirch chicken", "chicken capsicum peas curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Shimla Mirch Pyaz",
    image: "http://localhost:5000/uploads/chicken-shimla-mirch-pyaz.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - boneless, cut into strips",
      "2 capsicums - sliced into strips",
      "2 onions - sliced",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 tablespoon soy sauce",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan or wok.",
      "Add cumin seeds and half of the sliced onions. Fry until golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken strips and fry until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili and salt. Mix and cook for 2 minutes.",
      "Cook for 15 minutes until chicken is tender.",
      "Add capsicum strips and remaining onions. Cook on high flame for 5 minutes.",
      "Add soy sauce, mix well.",
      "Serve hot with fried rice or noodles."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "Indo-Chinese style chicken curry with capsicum and onions. Good with fried rice.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["soy"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "capsicum", "shimla mirch", "onion", "pyaz", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "soy sauce", "oil", "salt"],
    searchKeywords: ["chicken shimla mirch pyaz", "pyaz shimla mirch chicken", "chicken capsicum onion curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Gobhi",
    image: "http://localhost:5000/uploads/chicken-ghobi.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cauliflower - cut into small pieces",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add half cup warm water and cook for 15 minutes.",
      "Add cauliflower and cook for 10-12 minutes.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Healthy chicken curry with cauliflower. Good for a nutritious family meal.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 360,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "cauliflower", "gobhi", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken gobhi", "gobhi chicken", "chicken cauliflower curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Gobhi Aloo",
    image: "http://localhost:5000/uploads/chicken-ghobi-aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cauliflower - cut into pieces",
      "2 potatoes - peeled and cut into cubes",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add potatoes and 1 cup warm water. Cover and cook for 15 minutes.",
      "Add cauliflower and cook for 10 minutes.",
      "Serve hot with roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Complete meal chicken curry with cauliflower and potatoes. Good for hearty dinner.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "cauliflower", "gobhi", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken gobhi aloo", "aloo gobhi chicken", "chicken cauliflower potato curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Gobhi Matar",
    image: "http://localhost:5000/uploads/chicken-ghobi-matar.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "1 cauliflower - cut into pieces",
      "1 cup green peas",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add 1 cup warm water and cook for 15 minutes.",
      "Add cauliflower and peas. Cook for 10 minutes.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Nutritious chicken curry with cauliflower and peas. Packed with vegetables.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 375,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "cauliflower", "gobhi", "peas", "matar", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken gobhi matar", "matar gobhi chicken", "chicken cauliflower peas curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Baingan",
    image: "http://localhost:5000/uploads/chicken-baingan.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "2 eggplants - cut into cubes",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add half cup warm water and cook for 15 minutes.",
      "Add eggplants and mix gently. Cook for 10 minutes.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Different and tasty chicken curry with eggplant. Good for trying new flavors.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 370,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "eggplant", "baingan", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken baingan", "baingan chicken", "chicken eggplant curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Baingan Aloo",
    image: "http://localhost:5000/uploads/chicken-baingan-aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "2 eggplants - cut into cubes",
      "2 potatoes - peeled and cut into cubes",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add potatoes and half cup warm water. Cover and cook for 15 minutes.",
      "Add eggplants and cook for 10 minutes.",
      "Serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Hearty chicken curry with eggplant and potatoes. Good for family meal.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 390,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "eggplant", "baingan", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken baingan aloo", "aloo baingan chicken", "chicken eggplant potato curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Baingan Bharta",
    image: "http://localhost:5000/uploads/chicken-baingan-bharta.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken mince",
      "2 large eggplants - roasted and mashed",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 green chilies - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon garam masala",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Roast eggplants on flame until skin is burnt and flesh is soft. Let cool, then peel and mash.",
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken mince and fry until color changes.",
      "Add tomatoes and green chilies. Cook for 5 minutes.",
      "Add turmeric, red chili and salt. Mix and cook for 2 minutes.",
      "Add mashed eggplant and mix well. Cook for 10 minutes.",
      "Add garam masala and serve hot with roti or naan."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Tasty chicken mince curry with smoky mashed eggplant. Unique and flavorful.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 85,
    baseServings: 4,
    calories: 400,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken mince", "keema", "eggplant", "baingan", "bharta", "onion", "tomato", "green chili", "ginger", "garlic", "cumin", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["chicken baingan bharta", "baingan bharta chicken", "chicken eggplant bharta", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Tori",
    image: "http://localhost:5000/uploads/chicken-tori.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "500g tori (ridge gourd) - peeled and cut into cubes",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add half cup warm water and cook for 15 minutes.",
      "Add tori and cook for 10-12 minutes.",
      "Serve hot with roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Light and healthy chicken curry with ridge gourd. Less oily meal.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 75,
    baseServings: 4,
    calories: 340,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "tori", "ridge gourd", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken tori", "tori chicken", "chicken ridge gourd curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Louki",
    image: "http://localhost:5000/uploads/chicken-lauki.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "500g louki (bottle gourd) - peeled and cut into cubes",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add half cup warm water and cook for 15 minutes.",
      "Add louki and cook for 15 minutes.",
      "Serve hot with roti."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "Light and healthy chicken curry with bottle gourd. Good for health.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 75,
    baseServings: 4,
    calories: 345,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "louki", "bottle gourd", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken louki", "louki chicken", "chicken bottle gourd curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Tori Aloo",
    image: "http://localhost:5000/uploads/chicken-tori-aloo.jpg",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken - medium pieces",
      "400g tori - peeled and cut into cubes",
      "2 potatoes - peeled and cut into cubes",
      "2 onions - finely chopped",
      "2 tomatoes - finely chopped",
      "2 tablespoons ginger garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "2 teaspoons red chili powder",
      "1 teaspoon coriander powder",
      "1/2 cup oil",
      "Salt to taste"
    ],
    stepsRaw: [
      "Heat oil in a pan.",
      "Add cumin seeds and onions. Fry until onions are golden.",
      "Add ginger garlic paste and cook for 2 minutes.",
      "Add chicken and fry for 5 minutes until it turns white.",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili, coriander powder and salt. Mix and cook for 2 minutes.",
      "Add potatoes and half cup warm water. Cover and cook for 10 minutes.",
      "Add tori and cook for 10-12 minutes.",
      "Serve hot with roti."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "Wholesome chicken curry with ridge gourd and potatoes. Complete family meal.",
    category: "Lunch",
    subCategory: "veg-chicken",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: [],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "tori", "ridge gourd", "potato", "aloo", "onion", "tomato", "ginger", "garlic", "cumin", "turmeric", "red chili", "coriander", "oil", "salt"],
    searchKeywords: ["chicken tori aloo", "aloo tori chicken", "chicken ridge gourd potato curry", "pakistani chicken curry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
];

async function migrateRecipes() {
  try {
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    
    if (!mongoURI) {
      throw new Error('MongoDB URI not found in environment variables');
    }
    
    console.log('Connecting to MongoDB');
    
    await mongoose.connect(mongoURI, {
      serverSelectionTimeoutMS: 10000,
      family: 4
    });
    
    console.log('Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\nMigration Complete!');
    console.log(`Added: ${added}, Skipped: ${skipped}`);
    console.log(`Total recipes processed: ${added + skipped}`);
    
    process.exit(0);
    
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

migrateRecipes();