// 17-rice.js - COMPLETE (40 recipes)
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });
const recipesToMigrate = [
  // ==================== BIRYANI (6) ====================
  {
    title: "Chicken Biryani",
    tagline: "Fragrant basmati rice with spiced chicken",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500",
    category: "Rice",
    subCategory: "Biryani",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken, cut into pieces",
      "2 cups basmati rice, soaked 30 minutes",
      "2 onions, thinly sliced",
      "2 tomatoes, chopped",
      "1 cup yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp garam masala",
      "4 green chilies, slit",
      "1/2 cup fresh mint leaves",
      "1/2 cup fresh coriander",
      "2 tbsp lemon juice",
      "Saffron soaked in 1/4 cup warm milk",
      "1 cup ghee or oil",
      "Salt to taste",
      "Whole spices: 2 bay leaves, 4 cloves, 4 cardamom, 1 cinnamon stick"
    ],
    stepsRaw: [
      "Heat ghee in large pot, add whole spices until fragrant.",
      "Add sliced onions, fry until golden brown (8-10 minutes).",
      "Add ginger-garlic paste, cook for 2 minutes.",
      "Add chicken pieces, fry until color changes (5-7 minutes).",
      "Add tomatoes, cook until soft (3-4 minutes).",
      "Add yogurt and all powdered spices, mix well.",
      "Add 1/2 cup water, cover and cook until chicken is 70% done (10-12 minutes).",
      "Meanwhile, boil rice with salt until 70% cooked (about 5-7 minutes). Drain.",
      "Layer half the rice over the chicken masala.",
      "Sprinkle half the mint, coriander, green chilies, and lemon juice.",
      "Add remaining rice on top.",
      "Pour saffron milk over the rice.",
      "Sprinkle remaining herbs and garam masala.",
      "Cover tightly with lid, cook on low heat (dum) for 20-25 minutes.",
      "Let rest for 10 minutes before serving.",
      "Serve with raita and salad."
    ],
    isVegetarian: false,
    difficulty: "Hard",
    cookingTime: 60,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Mutton Biryani",
    tagline: "Basmati rice with tender mutton pieces",
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=500",
    category: "Rice",
    subCategory: "Biryani",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton, with bones",
      "2 cups basmati rice, soaked 30 minutes",
      "3 onions, thinly sliced",
      "2 tomatoes, chopped",
      "1 cup yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp nutmeg powder",
      "1/2 tsp mace powder",
      "4 green chilies, slit",
      "1/2 cup fresh mint leaves",
      "1/2 cup fresh coriander",
      "Saffron soaked in 1/4 cup warm milk",
      "1 cup ghee",
      "Salt to taste",
      "Whole spices: 2 bay leaves, 4 cloves, 4 cardamom, 1 cinnamon stick, 1 star anise"
    ],
    stepsRaw: [
      "Marinate mutton with yogurt, ginger-garlic paste, half the spices for 2 hours.",
      "Heat ghee in large pot, add whole spices until fragrant.",
      "Add sliced onions, fry until golden brown (8-10 minutes). Reserve half for garnish.",
      "Add marinated mutton, fry for 10 minutes until browned.",
      "Add tomatoes, cook until soft (5 minutes).",
      "Add 2 cups hot water, cover and cook until mutton is tender (45-50 minutes).",
      "Meanwhile, boil rice with salt and whole spices until 70% cooked. Drain.",
      "In a separate pot, layer half the rice, then mutton masala, then remaining rice.",
      "Sprinkle herbs, fried onions, green chilies, and saffron milk.",
      "Cover tightly and cook on low heat (dum) for 25-30 minutes.",
      "Rest for 10 minutes before serving.",
      "Serve with raita and salad."
    ],
    isVegetarian: false,
    difficulty: "Hard",
    cookingTime: 90,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Beef Biryani",
    tagline: "Spicy beef biryani with potatoes",
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=500",
    category: "Rice",
    subCategory: "Biryani",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g beef, cubed",
      "2 cups basmati rice, soaked",
      "2 onions, sliced",
      "2 potatoes, quartered",
      "2 tomatoes, chopped",
      "1 cup yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp garam masala",
      "1/2 tsp allspice powder",
      "4 green chilies",
      "Fresh mint and coriander",
      "Saffron milk",
      "Ghee/oil",
      "Whole spices: bay leaves, cloves, cardamom, cinnamon",
      "Salt to taste"
    ],
    stepsRaw: [
      "Pressure cook beef with salt and whole spices until tender (20 minutes). Reserve stock.",
      "Heat ghee, fry whole spices, then onions until golden.",
      "Add ginger-garlic paste, cook for 2 minutes.",
      "Add tomatoes, cook until soft.",
      "Add all powdered spices, cook for 2 minutes.",
      "Add beef and potatoes, fry for 5 minutes.",
      "Add yogurt, cook until oil separates.",
      "Add 1 cup beef stock, simmer for 10 minutes.",
      "Boil rice in remaining beef stock with salt until 70% done.",
      "Layer meat and rice in pot, add herbs and saffron.",
      "Cover and cook on low heat (dum) for 20 minutes.",
      "Rest 10 minutes, serve with raita."
    ],
    isVegetarian: false,
    difficulty: "Hard",
    cookingTime: 60,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Chicken Pulao",
    tagline: "Fragrant rice with chicken and whole spices",
    image: "https://images.unsplash.com/photo-1599043513900-ed6c01d9f80c?w=500",
    category: "Rice",
    subCategory: "Pulao",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken, cut into pieces",
      "2 cups basmati rice, soaked 30 minutes",
      "2 onions, thinly sliced",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "4 cloves",
      "4 cardamom pods",
      "1 cinnamon stick",
      "2 bay leaves",
      "1 tsp black pepper corns",
      "1 tsp salt or to taste",
      "1/2 cup oil or ghee",
      "4 cups chicken stock or water",
      "Fresh coriander for garnish",
      "Fried onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in large pot, add whole spices until fragrant.",
      "Add sliced onions, fry until golden brown (8-10 minutes). Reserve half for garnish.",
      "Add ginger-garlic paste, cook for 2 minutes.",
      "Add chicken pieces, fry until color changes (5-7 minutes).",
      "Add 4 cups water or stock, salt, and black pepper. Bring to boil.",
      "Add soaked rice, stir gently.",
      "Cook on high heat until water is absorbed (8-10 minutes).",
      "Reduce heat to low, cover tightly and cook for 10 minutes (dum).",
      "Let rest for 5 minutes, then fluff with fork.",
      "Garnish with fried onions and fresh coriander.",
      "Serve with raita and salad."
    ],
    isVegetarian: false,
    difficulty: "Medium",
    cookingTime: 35,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Mutton Pulao",
    tagline: "Rice cooked in mutton stock with caramelized onions",
    image: "https://images.unsplash.com/photo-1599043513900-ed6c01d9f80c?w=500",
    category: "Rice",
    subCategory: "Pulao",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton, with bones",
      "2 cups basmati rice, soaked 30 minutes",
      "3 onions, thinly sliced",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "4 cloves",
      "4 cardamom pods",
      "1 cinnamon stick",
      "2 bay leaves",
      "1 tsp black pepper corns",
      "Salt to taste",
      "1/2 cup oil or ghee",
      "4 cups mutton stock",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Pressure cook mutton with salt, half the whole spices until tender (20 minutes).",
      "Separate mutton and stock. Measure stock (should be 4 cups).",
      "Heat oil in pot, add remaining whole spices until fragrant.",
      "Add half the onions, fry until deep golden. Remove for garnish.",
      "Add remaining onions, sauté until soft.",
      "Add ginger-garlic paste, cook for 2 minutes.",
      "Add boiled mutton, fry for 5-7 minutes.",
      "Add mutton stock and salt, bring to boil.",
      "Add soaked rice, cook on high until water absorbs.",
      "Cover and cook on low heat (dum) for 15 minutes.",
      "Let rest for 5 minutes, fluff gently.",
      "Garnish with fried onions and coriander.",
      "Serve with raita."
    ],
    isVegetarian: false,
    difficulty: "Medium",
    cookingTime: 50,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Vegetable Pulao",
    tagline: "Fragrant rice with mixed vegetables",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Pulao",
    cuisine: "Indian",
    ingredientsRaw: [
      "2 cups basmati rice, soaked 30 minutes",
      "1 cup mixed vegetables (carrots, peas, beans, cauliflower)",
      "1 large onion, thinly sliced",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "4 cloves",
      "2 green cardamom pods",
      "1 cinnamon stick",
      "2 bay leaves",
      "1/2 cup oil or ghee",
      "4 cups water",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a large pot over medium heat. Add whole spices and cumin seeds. Sauté until fragrant (30 seconds).",
      "Add sliced onions and sauté until golden brown (6-7 minutes).",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add mixed vegetables and sauté for 3-4 minutes.",
      "Add water and salt. Bring to a boil.",
      "Add soaked and drained rice. Stir gently.",
      "Cook on high heat until water is absorbed (8-10 minutes).",
      "Reduce heat to low, cover tightly and cook for 10-12 minutes (dum).",
      "Let rest for 5 minutes, then fluff with fork.",
      "Garnish with fresh coriander and serve with raita."
    ],
    isVegetarian: true,
    difficulty: "Medium",
    cookingTime: 30,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
// 17-rice.js - CONTINUED (Recipes 7-40)

  // ==================== FriedRice (5) ====================
  {
    title: "Chicken FriedRice",
    tagline: "Stir-FriedRice with chicken and vegetables",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500",
    category: "Rice",
    subCategory: "FriedRice",
    cuisine: "Chinese",
    ingredientsRaw: [
      "3 cups cooked rice (preferably day-old)",
      "200g chicken breast, diced",
      "1 cup mixed vegetables (carrots, peas, corn)",
      "2 eggs, beaten",
      "3 tbsp soy sauce",
      "1 tbsp oil",
      "2 cloves garlic, minced",
      "1 onion, chopped",
      "Salt and pepper to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok or large pan over high heat.",
      "Add garlic and onion, stir-fry for 1 minute.",
      "Add chicken and cook until white and cooked through (5-6 minutes).",
      "Push chicken to side, add beaten eggs and scramble.",
      "Add mixed vegetables and stir-fry for 2-3 minutes.",
      "Add cooked rice and break up any clumps.",
      "Add soy sauce, salt, and pepper. Toss well.",
      "Stir-fry for 3-4 minutes until everything is well combined and heated through.",
      "Garnish with spring onions and serve hot."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 20,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Egg FriedRice",
    tagline: "Simple FriedRice with eggs",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "FriedRice",
    cuisine: "Chinese",
    ingredientsRaw: [
      "3 cups cooked rice (day-old preferred)",
      "3 eggs, beaten",
      "1 cup mixed vegetables",
      "3 tbsp soy sauce",
      "2 tbsp oil",
      "2 cloves garlic, minced",
      "1 onion, chopped",
      "Salt and pepper to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok over high heat.",
      "Add garlic and onion, stir-fry for 1 minute.",
      "Push to side, add beaten eggs and scramble.",
      "Add mixed vegetables and stir-fry for 2-3 minutes.",
      "Add rice and break up clumps.",
      "Add soy sauce, salt, and pepper. Toss well.",
      "Stir-fry for 3-4 minutes until hot.",
      "Garnish with spring onions and serve."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Vegetable FriedRice",
    tagline: "Healthy FriedRice with mixed vegetables",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "FriedRice",
    cuisine: "Chinese",
    ingredientsRaw: [
      "3 cups cooked rice",
      "1 cup mixed vegetables (carrots, peas, corn, beans)",
      "3 tbsp soy sauce",
      "2 tbsp oil",
      "2 cloves garlic, minced",
      "1 onion, chopped",
      "Salt and pepper to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok over high heat.",
      "Add garlic and onion, stir-fry for 1 minute.",
      "Add mixed vegetables and stir-fry for 3-4 minutes.",
      "Add rice and break up clumps.",
      "Add soy sauce, salt, and pepper. Toss well.",
      "Stir-fry for 3-4 minutes until hot.",
      "Garnish with spring onions and serve."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Shrimp FriedRice",
    tagline: "Delicious FriedRice with shrimp",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "FriedRice",
    cuisine: "Chinese",
    ingredientsRaw: [
      "3 cups cooked rice",
      "200g shrimp, peeled and deveined",
      "1 cup mixed vegetables",
      "3 tbsp soy sauce",
      "2 tbsp oil",
      "2 cloves garlic, minced",
      "1 onion, chopped",
      "Salt and pepper to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok over high heat.",
      "Add garlic and onion, stir-fry for 1 minute.",
      "Add shrimp and cook until pink (2-3 minutes). Remove and set aside.",
      "In same wok, add vegetables and stir-fry for 2-3 minutes.",
      "Add rice and break up clumps.",
      "Add soy sauce, salt, and pepper. Toss well.",
      "Add cooked shrimp back to wok.",
      "Stir-fry for 2-3 minutes until hot.",
      "Garnish with spring onions and serve."
    ],
    isVegetarian: false,
    difficulty: "Medium",
    cookingTime: 20,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Singapore FriedRice",
    tagline: "Spicy curry-flavored FriedRice",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "FriedRice",
    cuisine: "Chinese",
    ingredientsRaw: [
      "3 cups cooked rice",
      "200g chicken, diced",
      "100g shrimp",
      "1 cup mixed vegetables",
      "2 eggs, beaten",
      "2 tbsp curry powder",
      "3 tbsp soy sauce",
      "2 tbsp oil",
      "2 cloves garlic, minced",
      "1 onion, chopped",
      "Salt to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok over high heat.",
      "Add garlic and onion, stir-fry for 1 minute.",
      "Add chicken and shrimp, cook until done (5-6 minutes). Remove and set aside.",
      "Add beaten eggs, scramble, then add vegetables.",
      "Add rice and break up clumps.",
      "Add curry powder, soy sauce, and salt. Toss well.",
      "Add cooked chicken and shrimp back to wok.",
      "Stir-fry for 3-4 minutes until hot and fragrant.",
      "Garnish with spring onions and serve."
    ],
    isVegetarian: false,
    difficulty: "Medium",
    cookingTime: 25,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },

  // ==================== KHICHDI (4) ====================
  {
    title: "Simple Khichdi",
    tagline: "Comforting rice and lentil porridge",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Khichdi",
    cuisine: "Indian",
    ingredientsRaw: [
      "1 cup basmati rice",
      "1/2 cup moong dal (yellow lentils)",
      "4 cups water",
      "1 tsp turmeric powder",
      "1 tsp salt",
      "2 tbsp ghee",
      "1 tsp cumin seeds",
      "1 onion, sliced (for tempering)",
      "2 green chilies, slit"
    ],
    stepsRaw: [
      "Wash rice and dal together until water runs clear.",
      "In a pressure cooker, add rice, dal, water, turmeric, and salt.",
      "Close lid and cook for 3 whistles on medium heat.",
      "Let pressure release naturally.",
      "For tempering: heat ghee in a small pan, add cumin seeds.",
      "Add sliced onions and green chilies, fry until golden.",
      "Pour tempering over khichdi and mix gently.",
      "Khichdi should be soft and porridge-like.",
      "Serve hot with yogurt, pickle, or papad."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 25,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Vegetable Khichdi",
    tagline: "Nutritious khichdi with mixed vegetables",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Khichdi",
    cuisine: "Indian",
    ingredientsRaw: [
      "1 cup basmati rice",
      "1/2 cup moong dal",
      "1 cup mixed vegetables (carrots, peas, beans)",
      "4 cups water",
      "1 tsp turmeric",
      "1 tsp salt",
      "2 tbsp ghee",
      "1 tsp cumin seeds",
      "1 onion, chopped",
      "1 tomato, chopped",
      "1 tsp ginger-garlic paste"
    ],
    stepsRaw: [
      "Wash rice and dal together.",
      "In a pressure cooker, add rice, dal, vegetables, water, turmeric, and salt.",
      "Cook for 3 whistles, let pressure release naturally.",
      "For tempering: heat ghee, add cumin seeds.",
      "Add onion, fry until golden, then add ginger-garlic paste and tomato.",
      "Cook until tomato softens.",
      "Pour tempering over khichdi and mix well.",
      "Serve hot with yogurt and pickle."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 30,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Masala Khichdi",
    tagline: "Spiced khichdi with aromatic spices",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Khichdi",
    cuisine: "Indian",
    ingredientsRaw: [
      "1 cup basmati rice",
      "1/2 cup moong dal",
      "4 cups water",
      "1 tsp turmeric",
      "1 tsp salt",
      "2 tbsp ghee",
      "1 tsp cumin seeds",
      "1 onion, chopped",
      "1 tomato, chopped",
      "1 tsp ginger-garlic paste",
      "1 tsp garam masala",
      "1/2 tsp red chili powder"
    ],
    stepsRaw: [
      "Wash rice and dal together.",
      "In pressure cooker, add rice, dal, water, turmeric, and salt. Cook for 3 whistles.",
      "Heat ghee in a pan, add cumin seeds.",
      "Add onion, fry until golden. Add ginger-garlic paste and tomato.",
      "Cook until tomato softens. Add red chili powder and garam masala.",
      "Pour this masala into the cooked khichdi and mix well.",
      "Simmer for 5 minutes to blend flavors.",
      "Serve hot with yogurt or raita."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 30,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Sabudana Khichdi",
    tagline: "Tapioca pearl khichdi - fasting special",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Khichdi",
    cuisine: "Indian",
    ingredientsRaw: [
      "1 cup sabudana (tapioca pearls)",
      "2 medium potatoes, boiled and cubed",
      "1/2 cup peanuts, roasted and crushed",
      "2 green chilies, chopped",
      "1 tsp cumin seeds",
      "2 tbsp ghee",
      "1 tbsp lemon juice",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Wash sabudana thoroughly and soak in water for 4-5 hours or overnight.",
      "Drain excess water. Sabudana should be soft but separate.",
      "Heat ghee in a pan, add cumin seeds and green chilies.",
      "Add cubed potatoes and fry for 2-3 minutes.",
      "Add soaked sabudana and crushed peanuts.",
      "Cook on low heat for 5-7 minutes, stirring gently until sabudana becomes translucent.",
      "Add salt and lemon juice. Mix well.",
      "Garnish with fresh coriander and serve hot."
    ],
    isVegetarian: true,
    difficulty: "Medium",
    cookingTime: 20,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },

  // ==================== Other (6) ====================
  {
    title: "Zarda (Sweet Rice)",
    tagline: "Fragrant sweet rice with nuts",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Other",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, soaked 30 minutes",
      "1 cup sugar",
      "1/2 cup ghee",
      "4 cardamom pods",
      "2 cloves",
      "1 cinnamon stick",
      "Yellow food color",
      "2 tbsp raisins",
      "2 tbsp almonds, sliced",
      "2 tbsp pistachios, sliced",
      "2 tbsp coconut, grated",
      "1 tbsp candied orange peel (optional)"
    ],
    stepsRaw: [
      "Wash and soak rice for 30 minutes.",
      "Boil rice with whole spices until 70% cooked. Drain.",
      "Heat ghee in pan, add raisins and nuts, fry lightly.",
      "Add boiled rice, sugar mixed with food color.",
      "Add 1/4 cup water, mix gently.",
      "Cover and cook on low heat for 15 minutes.",
      "Fluff gently with fork.",
      "Garnish with coconut and orange peel.",
      "Serve warm as dessert."
    ],
    isVegetarian: true,
    difficulty: "Medium",
    cookingTime: 45,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Kheer (Rice Pudding)",
    tagline: "Creamy rice pudding with nuts",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Other",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 liter full cream milk",
      "1/4 cup basmati rice, washed and soaked",
      "1/2 cup sugar",
      "10 almonds, sliced",
      "10 pistachios, sliced",
      "2 tbsp raisins",
      "4 cardamom pods, crushed",
      "1 tbsp rose water",
      "1/4 tsp nutmeg powder"
    ],
    stepsRaw: [
      "Drain soaked rice, grind coarsely.",
      "Boil milk in heavy bottom pan.",
      "Add ground rice, cook on low heat stirring frequently.",
      "Cook until rice is soft and milk thickens (40-45 minutes).",
      "Add sugar, cook for 10 more minutes.",
      "Add cardamom, nutmeg, and half the nuts.",
      "Cook for 5 minutes until desired consistency.",
      "Add rose water, mix.",
      "Remove from heat, let cool.",
      "Garnish with remaining nuts and serve chilled or warm."
    ],
    isVegetarian: true,
    difficulty: "Medium",
    cookingTime: 60,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Tomato Rice",
    tagline: "Tangy and flavorful tomato rice",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Other",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, cooked",
      "4 ripe tomatoes, pureed",
      "1 onion, finely chopped",
      "2 tbsp oil",
      "1 tsp mustard seeds",
      "1 tsp cumin seeds",
      "1 tsp turmeric",
      "1 tsp red chili powder",
      "Few curry leaves",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a pan, add mustard seeds and cumin seeds. Let them crackle.",
      "Add curry leaves and onion, fry until golden.",
      "Add tomato puree, turmeric, red chili powder, and salt.",
      "Cook until oil separates and mixture thickens (8-10 minutes).",
      "Add cooked rice and mix gently.",
      "Cover and cook on low heat for 5 minutes.",
      "Garnish with fresh coriander and serve hot."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 20,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Lemon Rice",
    tagline: "Tangy and refreshing lemon rice",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Other",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, cooked",
      "2 tbsp lemon juice",
      "1 tbsp oil",
      "1 tsp mustard seeds",
      "1 tsp urad dal",
      "1 tsp chana dal",
      "Few curry leaves",
      "2 green chilies, slit",
      "1/4 cup peanuts",
      "1/2 tsp turmeric",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a pan, add mustard seeds. Let them crackle.",
      "Add urad dal, chana dal, peanuts, and curry leaves. Fry until golden.",
      "Add green chilies and turmeric. Sauté for 30 seconds.",
      "Add cooked rice, lemon juice, and salt.",
      "Mix gently and cook for 2-3 minutes.",
      "Garnish with fresh coriander and serve hot."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Coconut Rice",
    tagline: "Fragrant rice with coconut",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Other",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, cooked",
      "1/2 cup fresh coconut, grated",
      "1 tbsp oil",
      "1 tsp mustard seeds",
      "1 tsp urad dal",
      "1 tsp chana dal",
      "Few curry leaves",
      "2 green chilies, slit",
      "2 tbsp cashews",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a pan, add mustard seeds. Let them crackle.",
      "Add urad dal, chana dal, cashews, and curry leaves. Fry until golden.",
      "Add green chilies and grated coconut. Sauté for 2-3 minutes.",
      "Add cooked rice and salt.",
      "Mix gently and cook for 2-3 minutes until well combined.",
      "Garnish with fresh coriander and serve hot."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Curd Rice",
    tagline: "Cooling yogurt rice - comfort food",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Other",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups cooked rice (cooled)",
      "1 cup plain yogurt",
      "1/2 cup milk",
      "1 tbsp oil",
      "1 tsp mustard seeds",
      "1 tsp urad dal",
      "Few curry leaves",
      "1 green chili, chopped",
      "1 tbsp ginger, grated",
      "Salt to taste",
      "Fresh coriander and pomegranate for garnish"
    ],
    stepsRaw: [
      "In a bowl, mix cooked rice, yogurt, milk, and salt. Mash slightly.",
      "Heat oil in a small pan, add mustard seeds. Let them crackle.",
      "Add urad dal, curry leaves, green chili, and ginger. Fry for 1 minute.",
      "Pour this tempering over the rice mixture.",
      "Mix well and let it sit for 15 minutes to absorb flavors.",
      "Garnish with fresh coriander and pomegranate seeds.",
      "Serve at room temperature or chilled."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 10,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },

  // ==================== Pulao (6) ====================
  {
    title: "Kabuli Pulao",
    tagline: "Afghan rice with lamb, carrots, and raisins",
    image: "https://images.unsplash.com/photo-1599043513900-ed6c01d9f80c?w=500",
    category: "Rice",
    subCategory: "Pulao",
    cuisine: "Afghan",
    ingredientsRaw: [
      "500g lamb, cubed",
      "2 cups basmati rice, soaked",
      "2 carrots, julienned",
      "1/2 cup raisins",
      "1/2 cup almonds, sliced",
      "2 onions, sliced",
      "2 tbsp oil",
      "1 tsp cumin seeds",
      "4 cloves",
      "4 cardamom pods",
      "1 cinnamon stick",
      "Salt to taste",
      "4 cups water"
    ],
    stepsRaw: [
      "Heat oil in a large pot, add whole spices and onions. Fry until golden.",
      "Add lamb and cook until browned (8-10 minutes).",
      "Add water and salt. Cook until lamb is tender (30-40 minutes).",
      "Separate lamb and stock. Measure 4 cups of stock.",
      "In a separate pan, fry julienned carrots in oil until soft.",
      "Add raisins and almonds, fry for 1 minute. Set aside.",
      "In the pot, add rice and lamb stock. Cook until water absorbs.",
      "Layer cooked lamb, carrots, raisins, and almonds on top of rice.",
      "Cover and cook on low heat (dum) for 15 minutes.",
      "Mix gently before serving."
    ],
    isVegetarian: false,
    difficulty: "Hard",
    cookingTime: 75,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Pakistani Pulao",
    tagline: "Royal Pulao and aromatic spices",
    image: "https://images.unsplash.com/photo-1599043513900-ed6c01d9f80c?w=500",
    category: "Rice",
    subCategory: "Pulao",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken, cubed",
      "2 cups basmati rice, soaked",
      "1 cup yogurt",
      "2 onions, thinly sliced",
      "2 tbsp ginger-garlic paste",
      "1 tsp saffron strands",
      "1 tsp cardamom powder",
      "1/2 cup cream",
      "1/2 cup ghee",
      "Whole spices: cloves, cardamom, cinnamon",
      "Salt to taste",
      "Fried onions and nuts for garnish"
    ],
    stepsRaw: [
      "Marinate chicken with yogurt, ginger-garlic paste, and salt for 1 hour.",
      "Heat ghee, add whole spices, then onions. Fry until golden.",
      "Add marinated chicken, cook until done (15-20 minutes).",
      "In a separate pot, cook rice until 70% done. Drain.",
      "Layer half the rice, then chicken, then remaining rice.",
      "Sprinkle saffron milk, cardamom powder, and cream.",
      "Cover and cook on low heat (dum) for 20 minutes.",
      "Garnish with fried onions and nuts.",
      "Serve hot with raita."
    ],
    isVegetarian: false,
    difficulty: "Hard",
    cookingTime: 60,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Fish Biryani",
    tagline: "Delicate fish biryani",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500",
    category: "Rice",
    subCategory: "Pulao",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g firm white fish fillets, cut into cubes",
      "2 cups basmati rice, soaked",
      "2 onions, sliced",
      "2 tomatoes, chopped",
      "1 cup yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric",
      "1 tsp red chili powder",
      "1 tsp garam masala",
      "1/2 cup fresh mint and coriander",
      "1/2 cup oil",
      "Salt to taste",
      "Lemon juice"
    ],
    stepsRaw: [
      "Marinate fish with ginger-garlic paste, turmeric, salt, and lemon juice for 30 minutes.",
      "Heat oil, fry onions until golden. Add tomatoes and cook until soft.",
      "Add yogurt, red chili powder, and salt. Cook until oil separates.",
      "Add fish pieces and cook gently for 5-6 minutes (do not stir too much).",
      "In a separate pot, cook rice until 70% done. Drain.",
      "Layer half rice, then fish mixture, then remaining rice.",
      "Sprinkle mint, coriander, and garam masala.",
      "Cover and cook on low heat (dum) for 15 minutes.",
      "Serve hot with raita."
    ],
    isVegetarian: false,
    difficulty: "Medium",
    cookingTime: 50,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Keema Rice",
    tagline: "Rice with minced meat - one pot meal",
    image: "https://images.unsplash.com/photo-1599043513900-ed6c01d9f80c?w=500",
    category: "Rice",
    subCategory: "Pulao",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "300g mince (beef or chicken)",
      "2 cups basmati rice, soaked",
      "2 onions, sliced",
      "2 tomatoes, chopped",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric",
      "1 tsp red chili powder",
      "1 tsp garam masala",
      "1/2 cup oil",
      "3 cups water",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a large pot, add onions and fry until golden.",
      "Add ginger-garlic paste, cook for 2 minutes.",
      "Add mince and fry until browned (8-10 minutes).",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili powder, and salt. Cook for 2 minutes.",
      "Add water and bring to boil.",
      "Add soaked rice and cook until water is absorbed (8-10 minutes).",
      "Cover and cook on low heat (dum) for 10 minutes.",
      "Sprinkle garam masala and garnish with coriander.",
      "Serve hot with raita."
    ],
    isVegetarian: false,
    difficulty: "Medium",
    cookingTime: 40,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Saffron Rice",
    tagline: "Aromatic rice with saffron and nuts",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Other",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, soaked",
      "1/4 tsp saffron strands",
      "2 tbsp warm milk",
      "2 tbsp ghee",
      "4 cloves",
      "4 cardamom pods",
      "1 cinnamon stick",
      "2 tbsp almonds, sliced",
      "2 tbsp pistachios, sliced",
      "Salt to taste",
      "3 cups water"
    ],
    stepsRaw: [
      "Soak saffron in warm milk for 15 minutes.",
      "Heat ghee in a pot, add whole spices. Sauté until fragrant.",
      "Add soaked rice and fry for 2 minutes.",
      "Add water and salt. Bring to boil.",
      "Cook until water is absorbed (8-10 minutes).",
      "Add saffron milk and nuts.",
      "Cover and cook on low heat (dum) for 10 minutes.",
      "Fluff gently with fork and serve hot with curry."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 30,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  },
  {
    title: "Jeera Rice",
    tagline: "Simple cumin rice - perfect with dal",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    category: "Rice",
    subCategory: "Other",
    cuisine: "Indian",
    ingredientsRaw: [
      "2 cups basmati rice, soaked",
      "2 tbsp ghee",
      "1 tsp cumin seeds",
      "2 cloves",
      "2 cardamom pods",
      "1 cinnamon stick",
      "Salt to taste",
      "3 cups water"
    ],
    stepsRaw: [
      "Heat ghee in a pot, add cumin seeds and whole spices.",
      "Sauté until fragrant (30 seconds).",
      "Add soaked rice and fry for 2 minutes.",
      "Add water and salt. Bring to boil.",
      "Cook until water is absorbed (8-10 minutes).",
      "Cover and cook on low heat (dum) for 5-10 minutes.",
      "Fluff with fork and serve hot with dal."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 25,
    servings: 4,
    isActive: true,
    isHalal: true,
    budget: "standard",
    mealTime: ["Lunch", "Dinner"],
    ageGroup: ["adults"],
    patientFriendly: ["general"]
  }
];

async function migrate() {
  try {
    // Check which environment variable is available
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    
    console.log('🔍 MONGODB_URI:', process.env.MONGODB_URI);
    console.log('🔍 MONGOURI:', process.env.MONGOURI);
    console.log('🔍 MONGO_URI:', process.env.MONGO_URI);
    console.log('🔍 Using URI:', mongoURI ? 'Found' : 'NOT FOUND');
    console.log('🔍 Current directory:', __dirname);
    
    if (!mongoURI) {
      throw new Error('MongoDB URI not found in environment variables. Please check your .env file');
    }
    
    console.log('🔌 Connecting to MongoDB...');
    
    await mongoose.connect(mongoURI, {
      serverSelectionTimeoutMS: 10000,
      family: 4
    });
    
    console.log('✅ Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`✅ Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`⚠️ Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\n🎉 Migration Complete!');
    console.log(`📊 Added: ${added}, Skipped: ${skipped}`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

migrate();