// 17-rice.js - COMPLETE (40 recipes)
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });
const recipesToMigrate = [
  {
    title: "Chicken Biryani",
    tagline: "Fragrant basmati rice with spiced chicken",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken, cut into pieces",
      "2 cups basmati rice, soaked 30 minutes",
      "2 onions, thinly sliced",
      "2 tomatoes, chopped",
      "1 cup yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp garam masala",
      "4 green chilies, slit",
      "1/2 cup fresh mint leaves",
      "1/2 cup fresh coriander",
      "2 tbsp lemon juice",
      "Saffron soaked in 1/4 cup warm milk",
      "1 cup ghee or oil",
      "Salt to taste",
      "Whole spices: 2 bay leaves, 4 cloves, 4 cardamom, 1 cinnamon stick"
    ],
    stepsRaw: [
      "Heat ghee in large pot, add whole spices until fragrant.",
      "Add sliced onions, fry until golden brown (8-10 minutes).",
      "Add ginger-garlic paste, cook for 2 minutes.",
      "Add chicken pieces, fry until color changes (5-7 minutes).",
      "Add tomatoes, cook until soft (3-4 minutes).",
      "Add yogurt and all powdered spices, mix well.",
      "Add 1/2 cup water, cover and cook until chicken is 70% done (10-12 minutes).",
      "Meanwhile, boil rice with salt until 70% cooked (about 5-7 minutes). Drain.",
      "Layer half the rice over the chicken masala.",
      "Sprinkle half the mint, coriander, green chilies, and lemon juice.",
      "Add remaining rice on top.",
      "Pour saffron milk over the rice.",
      "Sprinkle remaining herbs and garam masala.",
      "Cover tightly with lid, cook on low heat (dum) for 20-25 minutes.",
      "Let rest for 10 minutes before serving.",
      "Serve with raita and salad."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A fragrant and flavorful chicken biryani with aromatic basmati rice and perfectly spiced chicken, perfect for special occasions.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 580,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "basmati rice", "onion", "tomato", "yogurt", "ginger", "garlic", "mint", "coriander", "saffron", "ghee", "whole spices"],
    searchKeywords: ["chicken biryani", "pakistani biryani", "chicken biryani recipe", "biryani", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Biryani",
    tagline: "Basmati rice with tender mutton pieces",
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton, with bones",
      "2 cups basmati rice, soaked 30 minutes",
      "3 onions, thinly sliced",
      "2 tomatoes, chopped",
      "1 cup yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp nutmeg powder",
      "1/2 tsp mace powder",
      "4 green chilies, slit",
      "1/2 cup fresh mint leaves",
      "1/2 cup fresh coriander",
      "Saffron soaked in 1/4 cup warm milk",
      "1 cup ghee",
      "Salt to taste",
      "Whole spices: 2 bay leaves, 4 cloves, 4 cardamom, 1 cinnamon stick, 1 star anise"
    ],
    stepsRaw: [
      "Marinate mutton with yogurt, ginger-garlic paste, half the spices for 2 hours.",
      "Heat ghee in large pot, add whole spices until fragrant.",
      "Add sliced onions, fry until golden brown (8-10 minutes). Reserve half for garnish.",
      "Add marinated mutton, fry for 10 minutes until browned.",
      "Add tomatoes, cook until soft (5 minutes).",
      "Add 2 cups hot water, cover and cook until mutton is tender (45-50 minutes).",
      "Meanwhile, boil rice with salt and whole spices until 70% cooked. Drain.",
      "In a separate pot, layer half the rice, then mutton masala, then remaining rice.",
      "Sprinkle herbs, fried onions, green chilies, and saffron milk.",
      "Cover tightly and cook on low heat (dum) for 25-30 minutes.",
      "Rest for 10 minutes before serving.",
      "Serve with raita and salad."
    ],
    difficulty: "Hard",
    cookingTime: 90,
    isActive: true,
    isHalal: true,
    description: "A royal mutton biryani with tender meat and aromatic basmati rice, perfect for festive occasions.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "premium",
    costPerServing: 180,
    baseServings: 4,
    calories: 650,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "basmati rice", "onion", "tomato", "yogurt", "ginger", "garlic", "mint", "coriander", "saffron", "ghee", "whole spices"],
    searchKeywords: ["mutton biryani", "pakistani mutton biryani", "mutton biryani recipe", "biryani", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Beef Biryani",
    tagline: "Spicy beef biryani with potatoes",
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g beef, cubed",
      "2 cups basmati rice, soaked",
      "2 onions, sliced",
      "2 potatoes, quartered",
      "2 tomatoes, chopped",
      "1 cup yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp garam masala",
      "1/2 tsp allspice powder",
      "4 green chilies",
      "Fresh mint and coriander",
      "Saffron milk",
      "Ghee/oil",
      "Whole spices: bay leaves, cloves, cardamom, cinnamon",
      "Salt to taste"
    ],
    stepsRaw: [
      "Pressure cook beef with salt and whole spices until tender (20 minutes). Reserve stock.",
      "Heat ghee, fry whole spices, then onions until golden.",
      "Add ginger-garlic paste, cook for 2 minutes.",
      "Add tomatoes, cook until soft.",
      "Add all powdered spices, cook for 2 minutes.",
      "Add beef and potatoes, fry for 5 minutes.",
      "Add yogurt, cook until oil separates.",
      "Add 1 cup beef stock, simmer for 10 minutes.",
      "Boil rice in remaining beef stock with salt until 70% done.",
      "Layer meat and rice in pot, add herbs and saffron.",
      "Cover and cook on low heat (dum) for 20 minutes.",
      "Rest 10 minutes, serve with raita."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A spicy and hearty beef biryani with potatoes, perfect for meat lovers.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 150,
    baseServings: 4,
    calories: 620,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["beef", "basmati rice", "potato", "onion", "tomato", "yogurt", "ginger", "garlic", "mint", "coriander", "saffron", "ghee", "whole spices"],
    searchKeywords: ["beef biryani", "pakistani beef biryani", "beef biryani recipe", "biryani", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Pulao",
    tagline: "Fragrant rice with chicken and whole spices",
    image: "https://images.unsplash.com/photo-1599043513900-ed6c01d9f80c?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken, cut into pieces",
      "2 cups basmati rice, soaked 30 minutes",
      "2 onions, thinly sliced",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "4 cloves",
      "4 cardamom pods",
      "1 cinnamon stick",
      "2 bay leaves",
      "1 tsp black pepper corns",
      "1 tsp salt or to taste",
      "1/2 cup oil or ghee",
      "4 cups chicken stock or water",
      "Fresh coriander for garnish",
      "Fried onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in large pot, add whole spices until fragrant.",
      "Add sliced onions, fry until golden brown (8-10 minutes). Reserve half for garnish.",
      "Add ginger-garlic paste, cook for 2 minutes.",
      "Add chicken pieces, fry until color changes (5-7 minutes).",
      "Add 4 cups water or stock, salt, and black pepper. Bring to boil.",
      "Add soaked rice, stir gently.",
      "Cook on high heat until water is absorbed (8-10 minutes).",
      "Reduce heat to low, cover tightly and cook for 10 minutes (dum).",
      "Let rest for 5 minutes, then fluff with fork.",
      "Garnish with fried onions and fresh coriander.",
      "Serve with raita and salad."
    ],
    difficulty: "Medium",
    cookingTime: 35,
    isActive: true,
    isHalal: true,
    description: "A simple yet flavorful chicken pulao with aromatic whole spices, perfect for a quick and satisfying meal.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 100,
    baseServings: 4,
    calories: 520,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "basmati rice", "onion", "ginger", "garlic", "cumin", "whole spices", "ghee", "salt"],
    searchKeywords: ["chicken pulao", "pakistani chicken pulao", "chicken pulao recipe", "pulao", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Mutton Pulao",
    tagline: "Rice cooked in mutton stock with caramelized onions",
    image: "https://images.unsplash.com/photo-1599043513900-ed6c01d9f80c?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g mutton, with bones",
      "2 cups basmati rice, soaked 30 minutes",
      "3 onions, thinly sliced",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "4 cloves",
      "4 cardamom pods",
      "1 cinnamon stick",
      "2 bay leaves",
      "1 tsp black pepper corns",
      "Salt to taste",
      "1/2 cup oil or ghee",
      "4 cups mutton stock",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Pressure cook mutton with salt, half the whole spices until tender (20 minutes).",
      "Separate mutton and stock. Measure stock (should be 4 cups).",
      "Heat oil in pot, add remaining whole spices until fragrant.",
      "Add half the onions, fry until deep golden. Remove for garnish.",
      "Add remaining onions, sauté until soft.",
      "Add ginger-garlic paste, cook for 2 minutes.",
      "Add boiled mutton, fry for 5-7 minutes.",
      "Add mutton stock and salt, bring to boil.",
      "Add soaked rice, cook on high until water absorbs.",
      "Cover and cook on low heat (dum) for 15 minutes.",
      "Let rest for 5 minutes, fluff gently.",
      "Garnish with fried onions and coriander.",
      "Serve with raita."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A rich and aromatic mutton pulao cooked in flavorful meat stock with caramelized onions.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 160,
    baseServings: 4,
    calories: 600,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["mutton", "basmati rice", "onion", "ginger", "garlic", "cumin", "whole spices", "ghee", "salt"],
    searchKeywords: ["mutton pulao", "pakistani mutton pulao", "mutton pulao recipe", "pulao", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Vegetable Pulao",
    tagline: "Fragrant rice with mixed vegetables",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, soaked 30 minutes",
      "1 cup mixed vegetables (carrots, peas, beans, cauliflower)",
      "1 large onion, thinly sliced",
      "2 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "4 cloves",
      "2 green cardamom pods",
      "1 cinnamon stick",
      "2 bay leaves",
      "1/2 cup oil or ghee",
      "4 cups water",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a large pot over medium heat. Add whole spices and cumin seeds. Sauté until fragrant (30 seconds).",
      "Add sliced onions and sauté until golden brown (6-7 minutes).",
      "Add ginger-garlic paste and cook for 2 minutes.",
      "Add mixed vegetables and sauté for 3-4 minutes.",
      "Add water and salt. Bring to a boil.",
      "Add soaked and drained rice. Stir gently.",
      "Cook on high heat until water is absorbed (8-10 minutes).",
      "Reduce heat to low, cover tightly and cook for 10-12 minutes (dum).",
      "Let rest for 5 minutes, then fluff with fork.",
      "Garnish with fresh coriander and serve with raita."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "A healthy and fragrant vegetable pulao with mixed vegetables and aromatic whole spices.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["basmati rice", "mixed vegetables", "carrots", "peas", "beans", "cauliflower", "onion", "ginger", "garlic", "cumin", "whole spices", "ghee", "salt"],
    searchKeywords: ["vegetable pulao", "veg pulao", "mixed vegetable pulao", "pulao", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chicken Fried Rice",
    tagline: "Stir-fried rice with chicken and vegetables",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500",
    cuisine: "Chinese",
    ingredientsRaw: [
      "3 cups cooked rice (preferably day-old)",
      "200g chicken breast, diced",
      "1 cup mixed vegetables (carrots, peas, corn)",
      "2 eggs, beaten",
      "3 tbsp soy sauce",
      "1 tbsp oil",
      "2 cloves garlic, minced",
      "1 onion, chopped",
      "Salt and pepper to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok or large pan over high heat.",
      "Add garlic and onion, stir-fry for 1 minute.",
      "Add chicken and cook until white and cooked through (5-6 minutes).",
      "Push chicken to side, add beaten eggs and scramble.",
      "Add mixed vegetables and stir-fry for 2-3 minutes.",
      "Add cooked rice and break up any clumps.",
      "Add soy sauce, salt, and pepper. Toss well.",
      "Stir-fry for 3-4 minutes until everything is well combined and heated through.",
      "Garnish with spring onions and serve hot."
    ],
    difficulty: "Easy",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "A quick and delicious chicken fried rice with vegetables and eggs, perfect for a weeknight dinner.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["soy"],
    budget: "standard",
    costPerServing: 90,
    baseServings: 4,
    calories: 450,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["rice", "chicken", "eggs", "mixed vegetables", "carrots", "peas", "corn", "soy sauce", "garlic", "onion", "oil", "salt", "pepper"],
    searchKeywords: ["chicken fried rice", "fried rice", "chinese fried rice", "non vegetarian", "quick meal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Egg Fried Rice",
    tagline: "Simple fried rice with eggs",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Chinese",
    ingredientsRaw: [
      "3 cups cooked rice (day-old preferred)",
      "3 eggs, beaten",
      "1 cup mixed vegetables",
      "3 tbsp soy sauce",
      "2 tbsp oil",
      "2 cloves garlic, minced",
      "1 onion, chopped",
      "Salt and pepper to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok over high heat.",
      "Add garlic and onion, stir-fry for 1 minute.",
      "Push to side, add beaten eggs and scramble.",
      "Add mixed vegetables and stir-fry for 2-3 minutes.",
      "Add rice and break up clumps.",
      "Add soy sauce, salt, and pepper. Toss well.",
      "Stir-fry for 3-4 minutes until hot.",
      "Garnish with spring onions and serve."
    ],
    difficulty: "Easy",
    cookingTime: 15,
    isActive: true,
    isHalal: true,
    description: "A simple and delicious egg fried rice that's quick to make and perfect for any meal.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["soy"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["rice", "eggs", "mixed vegetables", "soy sauce", "garlic", "onion", "oil", "salt", "pepper"],
    searchKeywords: ["egg fried rice", "fried rice", "chinese fried rice", "vegetarian", "quick meal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Vegetable Fried Rice",
    tagline: "Healthy fried rice with mixed vegetables",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Chinese",
    ingredientsRaw: [
      "3 cups cooked rice",
      "1 cup mixed vegetables (carrots, peas, corn, beans)",
      "3 tbsp soy sauce",
      "2 tbsp oil",
      "2 cloves garlic, minced",
      "1 onion, chopped",
      "Salt and pepper to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok over high heat.",
      "Add garlic and onion, stir-fry for 1 minute.",
      "Add mixed vegetables and stir-fry for 3-4 minutes.",
      "Add rice and break up clumps.",
      "Add soy sauce, salt, and pepper. Toss well.",
      "Stir-fry for 3-4 minutes until hot.",
      "Garnish with spring onions and serve."
    ],
    difficulty: "Easy",
    cookingTime: 15,
    isActive: true,
    isHalal: true,
    description: "A healthy and colorful vegetable fried rice that's perfect as a main or side dish.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["soy"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 4,
    calories: 340,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["rice", "mixed vegetables", "carrots", "peas", "corn", "beans", "soy sauce", "garlic", "onion", "oil", "salt", "pepper"],
    searchKeywords: ["vegetable fried rice", "veg fried rice", "chinese fried rice", "vegetarian", "healthy"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Shrimp Fried Rice",
    tagline: "Delicious fried rice with shrimp",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Chinese",
    ingredientsRaw: [
      "3 cups cooked rice",
      "200g shrimp, peeled and deveined",
      "1 cup mixed vegetables",
      "3 tbsp soy sauce",
      "2 tbsp oil",
      "2 cloves garlic, minced",
      "1 onion, chopped",
      "Salt and pepper to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok over high heat.",
      "Add garlic and onion, stir-fry for 1 minute.",
      "Add shrimp and cook until pink (2-3 minutes). Remove and set aside.",
      "In same wok, add vegetables and stir-fry for 2-3 minutes.",
      "Add rice and break up clumps.",
      "Add soy sauce, salt, and pepper. Toss well.",
      "Add cooked shrimp back to wok.",
      "Stir-fry for 2-3 minutes until hot.",
      "Garnish with spring onions and serve."
    ],
    difficulty: "Medium",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "A delicious shrimp fried rice with tender shrimp and crisp vegetables, perfect for seafood lovers.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["soy", "shellfish"],
    budget: "standard",
    costPerServing: 120,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["rice", "shrimp", "mixed vegetables", "soy sauce", "garlic", "onion", "oil", "salt", "pepper"],
    searchKeywords: ["shrimp fried rice", "prawn fried rice", "fried rice", "chinese fried rice", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Singapore Fried Rice",
    tagline: "Spicy curry-flavored fried rice",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Chinese",
    ingredientsRaw: [
      "3 cups cooked rice",
      "200g chicken, diced",
      "100g shrimp",
      "1 cup mixed vegetables",
      "2 eggs, beaten",
      "2 tbsp curry powder",
      "3 tbsp soy sauce",
      "2 tbsp oil",
      "2 cloves garlic, minced",
      "1 onion, chopped",
      "Salt to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in a wok over high heat.",
      "Add garlic and onion, stir-fry for 1 minute.",
      "Add chicken and shrimp, cook until done (5-6 minutes). Remove and set aside.",
      "Add beaten eggs, scramble, then add vegetables.",
      "Add rice and break up clumps.",
      "Add curry powder, soy sauce, and salt. Toss well.",
      "Add cooked chicken and shrimp back to wok.",
      "Stir-fry for 3-4 minutes until hot and fragrant.",
      "Garnish with spring onions and serve."
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "A spicy and aromatic Singapore-style fried rice with curry flavor, chicken, and shrimp.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["soy", "shellfish"],
    budget: "standard",
    costPerServing: 130,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["rice", "chicken", "shrimp", "eggs", "mixed vegetables", "curry powder", "soy sauce", "garlic", "onion", "oil", "salt"],
    searchKeywords: ["singapore fried rice", "singaporean fried rice", "curry fried rice", "chinese fried rice", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Simple Khichdi",
    tagline: "Comforting rice and lentil porridge",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup basmati rice",
      "1/2 cup moong dal (yellow lentils)",
      "4 cups water",
      "1 tsp turmeric powder",
      "1 tsp salt",
      "2 tbsp ghee",
      "1 tsp cumin seeds",
      "1 onion, sliced (for tempering)",
      "2 green chilies, slit"
    ],
    stepsRaw: [
      "Wash rice and dal together until water runs clear.",
      "In a pressure cooker, add rice, dal, water, turmeric, and salt.",
      "Close lid and cook for 3 whistles on medium heat.",
      "Let pressure release naturally.",
      "For tempering: heat ghee in a small pan, add cumin seeds.",
      "Add sliced onions and green chilies, fry until golden.",
      "Pour tempering over khichdi and mix gently.",
      "Khichdi should be soft and porridge-like.",
      "Serve hot with yogurt, pickle, or papad."
    ],
    difficulty: "Easy",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "A comforting rice and lentil porridge that's easy to digest and perfect for sick days or light meals.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["basmati rice", "moong dal", "yellow lentils", "turmeric", "ghee", "cumin", "onion", "green chili", "salt"],
    searchKeywords: ["khichdi", "simple khichdi", "rice lentil porridge", "comfort food", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Vegetable Khichdi",
    tagline: "Nutritious khichdi with mixed vegetables",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup basmati rice",
      "1/2 cup moong dal",
      "1 cup mixed vegetables (carrots, peas, beans)",
      "4 cups water",
      "1 tsp turmeric",
      "1 tsp salt",
      "2 tbsp ghee",
      "1 tsp cumin seeds",
      "1 onion, chopped",
      "1 tomato, chopped",
      "1 tsp ginger-garlic paste"
    ],
    stepsRaw: [
      "Wash rice and dal together.",
      "In a pressure cooker, add rice, dal, vegetables, water, turmeric, and salt.",
      "Cook for 3 whistles, let pressure release naturally.",
      "For tempering: heat ghee, add cumin seeds.",
      "Add onion, fry until golden, then add ginger-garlic paste and tomato.",
      "Cook until tomato softens.",
      "Pour tempering over khichdi and mix well.",
      "Serve hot with yogurt and pickle."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "A nutritious one-pot khichdi with mixed vegetables, perfect for a healthy and balanced meal.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 40,
    baseServings: 4,
    calories: 350,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["basmati rice", "moong dal", "mixed vegetables", "carrots", "peas", "beans", "turmeric", "ghee", "cumin", "onion", "tomato", "ginger", "garlic", "salt"],
    searchKeywords: ["vegetable khichdi", "veg khichdi", "mixed vegetable khichdi", "healthy khichdi", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Masala Khichdi",
    tagline: "Spiced khichdi with aromatic spices",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup basmati rice",
      "1/2 cup moong dal",
      "4 cups water",
      "1 tsp turmeric",
      "1 tsp salt",
      "2 tbsp ghee",
      "1 tsp cumin seeds",
      "1 onion, chopped",
      "1 tomato, chopped",
      "1 tsp ginger-garlic paste",
      "1 tsp garam masala",
      "1/2 tsp red chili powder"
    ],
    stepsRaw: [
      "Wash rice and dal together.",
      "In pressure cooker, add rice, dal, water, turmeric, and salt. Cook for 3 whistles.",
      "Heat ghee in a pan, add cumin seeds.",
      "Add onion, fry until golden. Add ginger-garlic paste and tomato.",
      "Cook until tomato softens. Add red chili powder and garam masala.",
      "Pour this masala into the cooked khichdi and mix well.",
      "Simmer for 5 minutes to blend flavors.",
      "Serve hot with yogurt or raita."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "A flavorful spiced khichdi with aromatic masalas, perfect for those who enjoy bold flavors.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 40,
    baseServings: 4,
    calories: 360,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["basmati rice", "moong dal", "turmeric", "ghee", "cumin", "onion", "tomato", "ginger", "garlic", "garam masala", "red chili", "salt"],
    searchKeywords: ["masala khichdi", "spiced khichdi", "flavorful khichdi", "vegetarian", "comfort food"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Sabudana Khichdi",
    tagline: "Tapioca pearl khichdi - fasting special",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup sabudana (tapioca pearls)",
      "2 medium potatoes, boiled and cubed",
      "1/2 cup peanuts, roasted and crushed",
      "2 green chilies, chopped",
      "1 tsp cumin seeds",
      "2 tbsp ghee",
      "1 tbsp lemon juice",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Wash sabudana thoroughly and soak in water for 4-5 hours or overnight.",
      "Drain excess water. Sabudana should be soft but separate.",
      "Heat ghee in a pan, add cumin seeds and green chilies.",
      "Add cubed potatoes and fry for 2-3 minutes.",
      "Add soaked sabudana and crushed peanuts.",
      "Cook on low heat for 5-7 minutes, stirring gently until sabudana becomes translucent.",
      "Add salt and lemon juice. Mix well.",
      "Garnish with fresh coriander and serve hot."
    ],
    difficulty: "Medium",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "A popular fasting special sabudana khichdi that's light, fluffy, and full of flavor.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner", "Snack"],
    allergens: ["nuts"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes"],
    pantryKeywords: ["sabudana", "tapioca pearls", "potato", "peanuts", "green chili", "cumin", "ghee", "lemon", "salt"],
    searchKeywords: ["sabudana khichdi", "tapioca khichdi", "fasting khichdi", "vrat ka khana", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Zarda (Sweet Rice)",
    tagline: "Fragrant sweet rice with nuts",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, soaked 30 minutes",
      "1 cup sugar",
      "1/2 cup ghee",
      "4 cardamom pods",
      "2 cloves",
      "1 cinnamon stick",
      "Yellow food color",
      "2 tbsp raisins",
      "2 tbsp almonds, sliced",
      "2 tbsp pistachios, sliced",
      "2 tbsp coconut, grated",
      "1 tbsp candied orange peel (optional)"
    ],
    stepsRaw: [
      "Wash and soak rice for 30 minutes.",
      "Boil rice with whole spices until 70% cooked. Drain.",
      "Heat ghee in pan, add raisins and nuts, fry lightly.",
      "Add boiled rice, sugar mixed with food color.",
      "Add 1/4 cup water, mix gently.",
      "Cover and cook on low heat for 15 minutes.",
      "Fluff gently with fork.",
      "Garnish with coconut and orange peel.",
      "Serve warm as dessert."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A fragrant and festive sweet rice dish with nuts and aromatic spices, perfect for celebrations.",
    category: "Lunch",
    subCategory: "rice",    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["nuts"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 4,
    calories: 480,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["basmati rice", "sugar", "ghee", "cardamom", "cloves", "cinnamon", "raisins", "almonds", "pistachios", "coconut", "food color"],
    searchKeywords: ["zarda", "sweet rice", "meetha chawal", "pakistani dessert", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Kheer (Rice Pudding)",
    tagline: "Creamy rice pudding with nuts",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 liter full cream milk",
      "1/4 cup basmati rice, washed and soaked",
      "1/2 cup sugar",
      "10 almonds, sliced",
      "10 pistachios, sliced",
      "2 tbsp raisins",
      "4 cardamom pods, crushed",
      "1 tbsp rose water",
      "1/4 tsp nutmeg powder"
    ],
    stepsRaw: [
      "Drain soaked rice, grind coarsely.",
      "Boil milk in heavy bottom pan.",
      "Add ground rice, cook on low heat stirring frequently.",
      "Cook until rice is soft and milk thickens (40-45 minutes).",
      "Add sugar, cook for 10 more minutes.",
      "Add cardamom, nutmeg, and half the nuts.",
      "Cook for 5 minutes until desired consistency.",
      "Add rose water, mix.",
      "Remove from heat, let cool.",
      "Garnish with remaining nuts and serve chilled or warm."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A creamy and rich rice pudding infused with cardamom and topped with nuts, a classic dessert.",
    category: "Lunch",
    subCategory: "rice",    dietType: "Vegetarian",
    suitableForMeals: ["Dessert"],
    allergens: ["nuts"],
    budget: "standard",
    costPerServing: 80,
    baseServings: 4,
    calories: 420,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["milk", "basmati rice", "sugar", "almonds", "pistachios", "raisins", "cardamom", "rose water", "nutmeg"],
    searchKeywords: ["kheer", "rice pudding", "meetha", "pakistani dessert", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Tomato Rice",
    tagline: "Tangy and flavorful tomato rice",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, cooked",
      "4 ripe tomatoes, pureed",
      "1 onion, finely chopped",
      "2 tbsp oil",
      "1 tsp mustard seeds",
      "1 tsp cumin seeds",
      "1 tsp turmeric",
      "1 tsp red chili powder",
      "Few curry leaves",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a pan, add mustard seeds and cumin seeds. Let them crackle.",
      "Add curry leaves and onion, fry until golden.",
      "Add tomato puree, turmeric, red chili powder, and salt.",
      "Cook until oil separates and mixture thickens (8-10 minutes).",
      "Add cooked rice and mix gently.",
      "Cover and cook on low heat for 5 minutes.",
      "Garnish with fresh coriander and serve hot."
    ],
    difficulty: "Easy",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "A tangy and flavorful tomato rice that's quick to make and perfect for lunchboxes.",
    category: "Lunch",
    subCategory: "rice",    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 40,
    baseServings: 4,
    calories: 320,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["basmati rice", "tomato", "onion", "mustard seeds", "cumin", "turmeric", "red chili", "curry leaves", "oil", "salt"],
    searchKeywords: ["tomato rice", "tamatar rice", "south indian tomato rice", "vegetarian", "quick meal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Lemon Rice",
    tagline: "Tangy and refreshing lemon rice",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, cooked",
      "2 tbsp lemon juice",
      "1 tbsp oil",
      "1 tsp mustard seeds",
      "1 tsp urad dal",
      "1 tsp chana dal",
      "Few curry leaves",
      "2 green chilies, slit",
      "1/4 cup peanuts",
      "1/2 tsp turmeric",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a pan, add mustard seeds. Let them crackle.",
      "Add urad dal, chana dal, peanuts, and curry leaves. Fry until golden.",
      "Add green chilies and turmeric. Sauté for 30 seconds.",
      "Add cooked rice, lemon juice, and salt.",
      "Mix gently and cook for 2-3 minutes.",
      "Garnish with fresh coriander and serve hot."
    ],
    difficulty: "Easy",
    cookingTime: 15,
    isActive: true,
    isHalal: true,
    description: "A tangy and refreshing lemon rice that's perfect for a quick lunch or tiffin box.",
    category: "Lunch",
    subCategory: "rice",    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["nuts"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 4,
    calories: 310,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["basmati rice", "lemon", "mustard seeds", "urad dal", "chana dal", "peanuts", "curry leaves", "green chili", "turmeric", "oil", "salt"],
    searchKeywords: ["lemon rice", "nimbu chawal", "south indian lemon rice", "vegetarian", "quick meal"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Coconut Rice",
    tagline: "Fragrant rice with coconut",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, cooked",
      "1/2 cup fresh coconut, grated",
      "1 tbsp oil",
      "1 tsp mustard seeds",
      "1 tsp urad dal",
      "1 tsp chana dal",
      "Few curry leaves",
      "2 green chilies, slit",
      "2 tbsp cashews",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a pan, add mustard seeds. Let them crackle.",
      "Add urad dal, chana dal, cashews, and curry leaves. Fry until golden.",
      "Add green chilies and grated coconut. Sauté for 2-3 minutes.",
      "Add cooked rice and salt.",
      "Mix gently and cook for 2-3 minutes until well combined.",
      "Garnish with fresh coriander and serve hot."
    ],
    difficulty: "Easy",
    cookingTime: 15,
    isActive: true,
    isHalal: true,
    description: "A fragrant coconut rice with roasted nuts and spices, perfect as a side dish or light meal.",
    category: "Lunch",
    subCategory: "rice",    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["nuts"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 4,
    calories: 360,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["basmati rice", "coconut", "mustard seeds", "urad dal", "chana dal", "cashews", "curry leaves", "green chili", "oil", "salt"],
    searchKeywords: ["coconut rice", "nariyal chawal", "south indian coconut rice", "vegetarian", "side dish"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Curd Rice",
    tagline: "Cooling yogurt rice - comfort food",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups cooked rice (cooled)",
      "1 cup plain yogurt",
      "1/2 cup milk",
      "1 tbsp oil",
      "1 tsp mustard seeds",
      "1 tsp urad dal",
      "Few curry leaves",
      "1 green chili, chopped",
      "1 tbsp ginger, grated",
      "Salt to taste",
      "Fresh coriander and pomegranate for garnish"
    ],
    stepsRaw: [
      "In a bowl, mix cooked rice, yogurt, milk, and salt. Mash slightly.",
      "Heat oil in a small pan, add mustard seeds. Let them crackle.",
      "Add urad dal, curry leaves, green chili, and ginger. Fry for 1 minute.",
      "Pour this tempering over the rice mixture.",
      "Mix well and let it sit for 15 minutes to absorb flavors.",
      "Garnish with fresh coriander and pomegranate seeds.",
      "Serve at room temperature or chilled."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A cooling and comforting yogurt rice that's perfect for hot summer days or as a light meal.",
    category: "Lunch",
    subCategory: "rice",    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 40,
    baseServings: 4,
    calories: 280,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["rice", "yogurt", "milk", "mustard seeds", "urad dal", "curry leaves", "green chili", "ginger", "oil", "salt"],
    searchKeywords: ["curd rice", "dahi chawal", "yogurt rice", "south indian curd rice", "vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Kabuli Pulao",
    tagline: "Afghan rice with lamb, carrots, and raisins",
    image: "https://images.unsplash.com/photo-1599043513900-ed6c01d9f80c?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g lamb, cubed",
      "2 cups basmati rice, soaked",
      "2 carrots, julienned",
      "1/2 cup raisins",
      "1/2 cup almonds, sliced",
      "2 onions, sliced",
      "2 tbsp oil",
      "1 tsp cumin seeds",
      "4 cloves",
      "4 cardamom pods",
      "1 cinnamon stick",
      "Salt to taste",
      "4 cups water"
    ],
    stepsRaw: [
      "Heat oil in a large pot, add whole spices and onions. Fry until golden.",
      "Add lamb and cook until browned (8-10 minutes).",
      "Add water and salt. Cook until lamb is tender (30-40 minutes).",
      "Separate lamb and stock. Measure 4 cups of stock.",
      "In a separate pan, fry julienned carrots in oil until soft.",
      "Add raisins and almonds, fry for 1 minute. Set aside.",
      "In the pot, add rice and lamb stock. Cook until water absorbs.",
      "Layer cooked lamb, carrots, raisins, and almonds on top of rice.",
      "Cover and cook on low heat (dum) for 15 minutes.",
      "Mix gently before serving."
    ],
    difficulty: "Hard",
    cookingTime: 75,
    isActive: true,
    isHalal: true,
    description: "An authentic Afghan rice dish with tender lamb, sweet carrots, and raisins, perfect for special occasions.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["nuts"],
    budget: "premium",
    costPerServing: 180,
    baseServings: 4,
    calories: 650,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["lamb", "basmati rice", "carrots", "raisins", "almonds", "onion", "cumin", "whole spices", "oil", "salt"],
    searchKeywords: ["kabuli pulao", "afghan pulao", "kabuli palaw", "rice with lamb", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Pakistani Pulao",
    tagline: "Royal pulao and aromatic spices",
    image: "https://images.unsplash.com/photo-1599043513900-ed6c01d9f80c?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g chicken, cubed",
      "2 cups basmati rice, soaked",
      "1 cup yogurt",
      "2 onions, thinly sliced",
      "2 tbsp ginger-garlic paste",
      "1 tsp saffron strands",
      "1 tsp cardamom powder",
      "1/2 cup cream",
      "1/2 cup ghee",
      "Whole spices: cloves, cardamom, cinnamon",
      "Salt to taste",
      "Fried onions and nuts for garnish"
    ],
    stepsRaw: [
      "Marinate chicken with yogurt, ginger-garlic paste, and salt for 1 hour.",
      "Heat ghee, add whole spices, then onions. Fry until golden.",
      "Add marinated chicken, cook until done (15-20 minutes).",
      "In a separate pot, cook rice until 70% done. Drain.",
      "Layer half the rice, then chicken, then remaining rice.",
      "Sprinkle saffron milk, cardamom powder, and cream.",
      "Cover and cook on low heat (dum) for 20 minutes.",
      "Garnish with fried onions and nuts.",
      "Serve hot with raita."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A royal Pakistani pulao with aromatic spices, saffron, and cream, perfect for celebrations.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["nuts"],
    budget: "premium",
    costPerServing: 150,
    baseServings: 4,
    calories: 620,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["chicken", "basmati rice", "yogurt", "onion", "ginger", "garlic", "saffron", "cardamom", "cream", "ghee", "whole spices", "salt"],
    searchKeywords: ["pakistani pulao", "royal pulao", "chicken pulao", "pakistani rice dish", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Fish Biryani",
    tagline: "Delicate fish biryani",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "500g firm white fish fillets, cut into cubes",
      "2 cups basmati rice, soaked",
      "2 onions, sliced",
      "2 tomatoes, chopped",
      "1 cup yogurt",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric",
      "1 tsp red chili powder",
      "1 tsp garam masala",
      "1/2 cup fresh mint and coriander",
      "1/2 cup oil",
      "Salt to taste",
      "Lemon juice"
    ],
    stepsRaw: [
      "Marinate fish with ginger-garlic paste, turmeric, salt, and lemon juice for 30 minutes.",
      "Heat oil, fry onions until golden. Add tomatoes and cook until soft.",
      "Add yogurt, red chili powder, and salt. Cook until oil separates.",
      "Add fish pieces and cook gently for 5-6 minutes (do not stir too much).",
      "In a separate pot, cook rice until 70% done. Drain.",
      "Layer half rice, then fish mixture, then remaining rice.",
      "Sprinkle mint, coriander, and garam masala.",
      "Cover and cook on low heat (dum) for 15 minutes.",
      "Serve hot with raita."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A delicate and flavorful fish biryani that's perfect for seafood lovers.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 140,
    baseServings: 4,
    calories: 550,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["fish", "basmati rice", "onion", "tomato", "yogurt", "ginger", "garlic", "mint", "coriander", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["fish biryani", "fish biryani recipe", "seafood biryani", "biryani", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Keema Rice",
    tagline: "Rice with minced meat - one pot meal",
    image: "https://images.unsplash.com/photo-1599043513900-ed6c01d9f80c?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "300g mince (beef or chicken)",
      "2 cups basmati rice, soaked",
      "2 onions, sliced",
      "2 tomatoes, chopped",
      "2 tbsp ginger-garlic paste",
      "1 tsp turmeric",
      "1 tsp red chili powder",
      "1 tsp garam masala",
      "1/2 cup oil",
      "3 cups water",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in a large pot, add onions and fry until golden.",
      "Add ginger-garlic paste, cook for 2 minutes.",
      "Add mince and fry until browned (8-10 minutes).",
      "Add tomatoes and cook until soft.",
      "Add turmeric, red chili powder, and salt. Cook for 2 minutes.",
      "Add water and bring to boil.",
      "Add soaked rice and cook until water is absorbed (8-10 minutes).",
      "Cover and cook on low heat (dum) for 10 minutes.",
      "Sprinkle garam masala and garnish with coriander.",
      "Serve hot with raita."
    ],
    difficulty: "Medium",
    cookingTime: 40,
    isActive: true,
    isHalal: true,
    description: "A hearty one-pot keema rice with minced meat and aromatic spices, perfect for a quick meal.",
    category: "Lunch",
   subCategory: "rice",
    dietType: "Non-Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "standard",
    costPerServing: 110,
    baseServings: 4,
    calories: 540,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["mince", "keema", "basmati rice", "onion", "tomato", "ginger", "garlic", "turmeric", "red chili", "garam masala", "oil", "salt"],
    searchKeywords: ["keema rice", "keema pulao", "mince rice", "one pot meal", "non vegetarian"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Saffron Rice",
    tagline: "Aromatic rice with saffron and nuts",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, soaked",
      "1/4 tsp saffron strands",
      "2 tbsp warm milk",
      "2 tbsp ghee",
      "4 cloves",
      "4 cardamom pods",
      "1 cinnamon stick",
      "2 tbsp almonds, sliced",
      "2 tbsp pistachios, sliced",
      "Salt to taste",
      "3 cups water"
    ],
    stepsRaw: [
      "Soak saffron in warm milk for 15 minutes.",
      "Heat ghee in a pot, add whole spices. Sauté until fragrant.",
      "Add soaked rice and fry for 2 minutes.",
      "Add water and salt. Bring to boil.",
      "Cook until water is absorbed (8-10 minutes).",
      "Add saffron milk and nuts.",
      "Cover and cook on low heat (dum) for 10 minutes.",
      "Fluff gently with fork and serve hot with curry."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "An aromatic saffron rice with nuts and whole spices, perfect as a side dish for special meals.",
    category: "Lunch",
    subCategory: "rice",    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["nuts"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 4,
    calories: 380,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["basmati rice", "saffron", "milk", "ghee", "cloves", "cardamom", "cinnamon", "almonds", "pistachios", "salt"],
    searchKeywords: ["saffron rice", "kesar rice", "aromatic rice", "vegetarian", "side dish"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Jeera Rice",
    tagline: "Simple cumin rice - perfect with dal",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups basmati rice, soaked",
      "2 tbsp ghee",
      "1 tsp cumin seeds",
      "2 cloves",
      "2 cardamom pods",
      "1 cinnamon stick",
      "Salt to taste",
      "3 cups water"
    ],
    stepsRaw: [
      "Heat ghee in a pot, add cumin seeds and whole spices.",
      "Sauté until fragrant (30 seconds).",
      "Add soaked rice and fry for 2 minutes.",
      "Add water and salt. Bring to boil.",
      "Cook until water is absorbed (8-10 minutes).",
      "Cover and cook on low heat (dum) for 5-10 minutes.",
      "Fluff with fork and serve hot with dal."
    ],
    difficulty: "Easy",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "A simple and aromatic cumin rice that's the perfect companion to any dal or curry.",
    category: "Lunch",
    subCategory: "rice",    dietType: "Vegetarian",
    suitableForMeals: ["Lunch", "Dinner"],
    allergens: ["none"],
    budget: "economy",
    costPerServing: 35,
    baseServings: 4,
    calories: 300,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general", "diabetes", "heart", "bp"],
    pantryKeywords: ["basmati rice", "ghee", "cumin seeds", "cloves", "cardamom", "cinnamon", "salt"],
    searchKeywords: ["jeera rice", "cumin rice", "simple rice", "vegetarian", "side dish"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
]

async function migrate() {
  try {
    // Check which environment variable is available
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    
    console.log('🔍 MONGODB_URI:', process.env.MONGODB_URI);
    console.log('🔍 MONGOURI:', process.env.MONGOURI);
    console.log('🔍 MONGO_URI:', process.env.MONGO_URI);
    console.log('🔍 Using URI:', mongoURI ? 'Found' : 'NOT FOUND');
    console.log('🔍 Current directory:', __dirname);
    
    if (!mongoURI) {
      throw new Error('MongoDB URI not found in environment variables. Please check your .env file');
    }
    
    console.log('🔌 Connecting to MongoDB...');
    
    await mongoose.connect(mongoURI, {
      serverSelectionTimeoutMS: 10000,
      family: 4
    });
    
    console.log('✅ Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`✅ Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`⚠️ Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\n🎉 Migration Complete!');
    console.log(`📊 Added: ${added}, Skipped: ${skipped}`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

migrate();