// 07-baking.js
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });
const recipesToMigrate = [
  {
    title: "Vanilla Sponge Cake",
    tagline: "Light and fluffy classic vanilla cake",
    image: "https://taylorandcolledge.ie/wp-content/uploads/2022/12/Vanilla-Sponge-Cake-Website-Image-scaled.jpeg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups maida (all-purpose flour)",
      "2 cups sugar",
      "1 cup butter, room temperature",
      "4 eggs",
      "1 cup milk",
      "2 tsp vanilla essence",
      "1 tbsp baking powder",
      "1/2 tsp salt"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C).",
      "Grease and flour two 9-inch round cake pans.",
      "Cream butter and sugar until light and fluffy.",
      "Add eggs one at a time, beating well after each.",
      "Mix in vanilla essence.",
      "In separate bowl, whisk flour, baking powder, and salt.",
      "Add dry ingredients to butter mixture alternately with milk.",
      "Divide batter evenly between pans.",
      "Bake for 25-30 minutes or until toothpick comes out clean.",
      "Cool in pans for 10 minutes before transferring to wire racks."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A light and fluffy classic vanilla sponge cake that's perfect for birthdays, celebrations, or afternoon tea.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 8,
    calories: 380,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["maida", "all-purpose flour", "sugar", "butter", "eggs", "milk", "vanilla", "baking powder", "salt"],
    searchKeywords: ["vanilla sponge cake", "classic vanilla cake", "sponge cake", "birthday cake", "baking"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chocolate Mug Cake",
    tagline: "Quick single-serving chocolate cake in minutes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPAVsSBNsyUzNya7rQU6Cb3s88EhcNT97hhw&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 tbsp all-purpose flour",
      "4 tbsp sugar",
      "2 tbsp cocoa powder",
      "1/4 tsp baking powder",
      "3 tbsp milk",
      "2 tbsp vegetable oil",
      "1/4 tsp vanilla essence",
      "1 tbsp chocolate chips (optional)"
    ],
    stepsRaw: [
      "In microwave-safe mug, mix flour, sugar, cocoa powder, and baking powder.",
      "Add milk, oil, and vanilla essence. Mix until smooth.",
      "Stir in chocolate chips if using.",
      "Microwave on high for 1 minute 30 seconds to 2 minutes.",
      "Let cool for 1 minute before enjoying.",
      "Top with ice cream if desired."
    ],
    difficulty: "Easy",
    cookingTime: 5,
    isActive: true,
    isHalal: true,
    description: "A quick and easy single-serving chocolate cake made in a mug, perfect for instant dessert cravings.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "wheat"],
    budget: "economy",
    costPerServing: 30,
    baseServings: 1,
    calories: 350,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "cocoa powder", "baking powder", "milk", "vegetable oil", "vanilla", "chocolate chips"],
    searchKeywords: ["chocolate mug cake", "mug cake", "quick cake", "single serving cake", "microwave cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Banana Bread",
    tagline: "Moist and delicious quick bread with ripe bananas",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBa3I-TLJmKEAfIxyvpjKoCvXBmulsE9C6Ew&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "3 ripe bananas, mashed",
      "1/3 cup melted butter",
      "1 cup sugar",
      "1 egg, beaten",
      "1 tsp vanilla essence",
      "1 tsp baking soda",
      "Pinch of salt",
      "1 1/2 cups all-purpose flour",
      "1/2 cup chopped walnuts (optional)"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease a 9x5 inch loaf pan.",
      "Mash bananas with fork until smooth.",
      "Stir melted butter into bananas.",
      "Mix in sugar, egg, and vanilla essence.",
      "Add baking soda and salt, mix thoroughly.",
      "Gradually add flour, mixing until just incorporated.",
      "Fold in chopped walnuts if using.",
      "Pour batter into prepared pan.",
      "Bake for 60-65 minutes or until toothpick comes out clean.",
      "Cool completely before slicing."
    ],
    difficulty: "Easy",
    cookingTime: 75,
    isActive: true,
    isHalal: true,
    description: "A moist and delicious banana bread made with ripe bananas, perfect for breakfast or as a snack.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 8,
    calories: 320,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["banana", "butter", "sugar", "egg", "vanilla", "baking soda", "salt", "all-purpose flour", "walnuts"],
    searchKeywords: ["banana bread", "banana cake", "moist banana bread", "quick bread", "breakfast bread"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Butter Pound Cake",
    tagline: "Rich, dense buttery classic pound cake",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQedyHGj1yIBACcB9f12oQOuOFZfn8FxfdfJw&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "2 cups sugar",
      "1 cup butter, softened",
      "5 eggs",
      "1/2 cup yogurt",
      "1 tsp vanilla essence",
      "1/2 tsp baking powder",
      "1/4 tsp salt"
    ],
    stepsRaw: [
      "Preheat oven to 325°F (165°C). Grease a tube pan.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one at a time, beating well after each.",
      "Mix in vanilla essence and yogurt.",
      "In separate bowl, whisk flour, baking powder, and salt.",
      "Gradually add dry ingredients to butter mixture.",
      "Pour batter into prepared pan.",
      "Bake for 60-75 minutes or until golden brown.",
      "Cool in pan for 20 minutes before removing."
    ],
    difficulty: "Medium",
    cookingTime: 85,
    isActive: true,
    isHalal: true,
    description: "A rich, dense, and buttery classic pound cake that's perfect with tea or coffee.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 55,
    baseServings: 10,
    calories: 450,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "butter", "eggs", "yogurt", "vanilla", "baking powder", "salt"],
    searchKeywords: ["butter pound cake", "pound cake", "classic pound cake", "butter cake", "dense cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Coffee Cake",
    tagline: "Cinnamon streusel topped coffee cake",
    image: "https://images.immediate.co.uk/production/volatile/sites/30/2023/02/Irish-coffee-cake-e23e0f0.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1 cup sugar",
      "1/2 cup butter, softened",
      "2 eggs",
      "1 cup yogurt",
      "1 tsp vanilla essence",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "For topping: 1/2 cup brown sugar, 1/2 cup chopped walnuts, 2 tsp cinnamon"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease a 9-inch square pan.",
      "Make topping: Mix brown sugar, walnuts, and cinnamon.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one at a time.",
      "Mix in vanilla essence and yogurt.",
      "In separate bowl, whisk flour, baking powder, baking soda, and salt.",
      "Gradually add dry ingredients to butter mixture.",
      "Spread half of batter in pan.",
      "Sprinkle with half of topping.",
      "Top with remaining batter and sprinkle with remaining topping.",
      "Bake for 35-40 minutes until golden brown."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A delicious cinnamon streusel-topped coffee cake that's perfect with your morning coffee.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 9,
    calories: 380,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "butter", "eggs", "yogurt", "vanilla", "baking powder", "baking soda", "salt", "brown sugar", "walnuts", "cinnamon"],
    searchKeywords: ["coffee cake", "cinnamon coffee cake", "streusel cake", "breakfast cake", "tea cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Vegan Sugar Cookies",
    tagline: "Plant-based buttery sugar cookies",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 1/2 cups all-purpose flour",
      "1 cup vegan butter, softened",
      "1 cup sugar",
      "1/4 cup almond milk",
      "2 tsp vanilla essence",
      "1 tbsp cornstarch",
      "1 tsp baking powder",
      "1/2 tsp salt"
    ],
    stepsRaw: [
      "Cream vegan butter and sugar until fluffy.",
      "Add almond milk and vanilla essence, mix well.",
      "In separate bowl, whisk flour, cornstarch, baking powder, and salt.",
      "Gradually add dry ingredients to wet mixture.",
      "Divide dough in half, shape into disks, wrap, chill for 1 hour.",
      "Preheat oven to 350°F (180°C).",
      "Roll dough to 1/4-inch thickness on floured surface.",
      "Cut with cookie cutters.",
      "Bake for 8-10 minutes until edges are lightly golden.",
      "Cool on baking sheets for 5 minutes."
    ],
    difficulty: "Medium",
    cookingTime: 90,
    isActive: true,
    isHalal: true,
    description: "Plant-based buttery sugar cookies that are perfect for holidays, parties, or anytime you need a sweet treat.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["wheat", "nuts"],
    budget: "standard",
    costPerServing: 35,
    baseServings: 24,
    calories: 120,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "vegan butter", "sugar", "almond milk", "vanilla", "cornstarch", "baking powder", "salt"],
    searchKeywords: ["vegan sugar cookies", "plant based cookies", "eggless cookies", "dairy free cookies", "sugar cookies"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Peanut Butter Cookies",
    tagline: "Soft and chewy peanut butter cookies",
    image: "https://www.twopeasandtheirpod.com/wp-content/uploads/2022/10/Soft-Peanut-Butter-Cookies-16-500x500.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup creamy peanut butter",
      "1 cup sugar",
      "1 egg",
      "1 tsp vanilla essence",
      "1 tsp baking soda",
      "Pinch of salt",
      "Sugar for rolling"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C).",
      "Mix peanut butter, sugar, egg, vanilla, baking soda, and salt.",
      "Form dough into 1-inch balls and roll in sugar.",
      "Place on baking sheets and flatten with fork.",
      "Bake for 8-10 minutes until edges are set.",
      "Let cool on baking sheets for 5 minutes.",
      "Store in airtight container."
    ],
    difficulty: "Easy",
    cookingTime: 20,
    isActive: true,
    isHalal: true,
    description: "Soft, chewy, and delicious peanut butter cookies that are incredibly easy to make with just a few ingredients.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["eggs", "peanuts"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 18,
    calories: 140,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["peanut butter", "sugar", "egg", "vanilla", "baking soda", "salt"],
    searchKeywords: ["peanut butter cookies", "soft peanut butter cookies", "chewy cookies", "easy cookies", "3 ingredient cookies"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Vegan Chocolate Cake",
    tagline: "Rich and moist eggless chocolate cake",
    image: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/vegan_peanut_choc_cake_64828_16x9.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 1/2 cups all-purpose flour",
      "1 cup sugar",
      "1/4 cup cocoa powder",
      "1 tsp baking soda",
      "1/2 tsp salt",
      "1 cup water",
      "1/3 cup vegetable oil",
      "1 tsp vanilla essence",
      "1 tsp vinegar"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease an 8-inch pan.",
      "Whisk together flour, sugar, cocoa powder, baking soda, and salt.",
      "Make a well and add water, oil, vanilla, and vinegar.",
      "Mix until just combined (batter will be thin).",
      "Pour into prepared pan.",
      "Bake for 30-35 minutes or until toothpick comes out clean.",
      "Cool in pan for 10 minutes.",
      "Frost with vegan chocolate frosting if desired."
    ],
    difficulty: "Easy",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A rich, moist, and delicious eggless chocolate cake that's completely vegan and perfect for any celebration.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["wheat"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 8,
    calories: 350,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "cocoa powder", "baking soda", "salt", "water", "vegetable oil", "vanilla", "vinegar"],
    searchKeywords: ["vegan chocolate cake", "eggless chocolate cake", "dairy free cake", "moist chocolate cake", "plant based cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Continental Red Velvet",
    tagline: "Classic red velvet cake with cream cheese frosting",
    image: "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 1/2 cups all-purpose flour",
      "1 1/2 cups sugar",
      "1 cup buttermilk",
      "1/2 cup butter, softened",
      "2 eggs",
      "2 tbsp red food coloring",
      "1 tsp vanilla essence",
      "1 tsp baking soda",
      "1 tsp vinegar",
      "1 tsp cocoa powder",
      "1/2 tsp salt"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease two 9-inch pans.",
      "Whisk flour, cocoa powder, and salt.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one at a time.",
      "Mix in food coloring and vanilla.",
      "Add flour mixture alternately with buttermilk.",
      "Mix baking soda and vinegar, fold into batter.",
      "Divide batter between pans.",
      "Bake for 25-30 minutes.",
      "Cool completely before frosting with cream cheese frosting."
    ],
    difficulty: "Hard",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A classic red velvet cake with a beautiful red color and tangy cream cheese frosting, perfect for special occasions.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 10,
    calories: 480,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "buttermilk", "butter", "eggs", "red food coloring", "vanilla", "baking soda", "vinegar", "cocoa powder", "salt"],
    searchKeywords: ["red velvet cake", "classic red velvet", "cream cheese frosting", "birthday cake", "layer cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Yogurt Pound Cake",
    tagline: "Moist pound cake made with yogurt",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTanuHBasCHpLk0_eoWortqRkdOV3_TbWUYlQ&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 1/2 cups all-purpose flour",
      "1 cup plain yogurt",
      "1 cup sugar",
      "3 eggs",
      "1/2 cup vegetable oil",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1 tsp vanilla essence",
      "Pinch of salt"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease a loaf pan.",
      "Whisk flour, baking powder, baking soda, and salt.",
      "Beat eggs and sugar until pale and fluffy.",
      "Add yogurt, oil, and vanilla essence, mix well.",
      "Gradually fold in dry ingredients.",
      "Pour batter into pan.",
      "Bake for 45-50 minutes until golden brown.",
      "Cool in pan for 10 minutes.",
      "Dust with powdered sugar before serving."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A moist and tender pound cake made with yogurt, resulting in a soft crumb and delicious flavor.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 8,
    calories: 360,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "yogurt", "sugar", "eggs", "vegetable oil", "baking powder", "baking soda", "vanilla", "salt"],
    searchKeywords: ["yogurt pound cake", "moist pound cake", "easy pound cake", "loaf cake", "tea cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Japanese Cheesecake",
    tagline: "Light and fluffy Japanese-style cheesecake",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGeCOIMxR-Q-vqsPGWBcMwHzgph6C36UumEg&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "250g cream cheese",
      "50g butter",
      "100ml milk",
      "60g cake flour",
      "20g cornstarch",
      "6 eggs, separated",
      "120g sugar",
      "1 tsp lemon juice",
      "1/4 tsp cream of tartar"
    ],
    stepsRaw: [
      "Preheat oven to 320°F (160°C). Prepare water bath.",
      "Melt cream cheese, butter, and milk over double boiler.",
      "Remove from heat, sift in flour and cornstarch, mix well.",
      "Add egg yolks one at a time, mixing after each.",
      "Beat egg whites with cream of tartar until foamy.",
      "Gradually add sugar, beating until stiff peaks form.",
      "Fold egg whites into cheese mixture in three batches.",
      "Pour into springform pan lined with parchment.",
      "Place in water bath and bake for 70-80 minutes.",
      "Turn off oven and let cake cool inside for 1 hour.",
      "Chill for at least 4 hours before serving."
    ],
    difficulty: "Hard",
    cookingTime: 180,
    isActive: true,
    isHalal: true,
    description: "A light, fluffy, and jiggly Japanese-style cheesecake that's less sweet and incredibly airy.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "premium",
    costPerServing: 80,
    baseServings: 8,
    calories: 320,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["cream cheese", "butter", "milk", "cake flour", "cornstarch", "eggs", "sugar", "lemon juice", "cream of tartar"],
    searchKeywords: ["japanese cheesecake", "cotton cheesecake", "jiggly cheesecake", "light cheesecake", "fluffy cheesecake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Spanish Orange Cake",
    tagline: "Bright and citrusy orange-flavored cake",
    image: "https://static01.nyt.com/images/2014/04/07/dining/orangeflan-still/orangeflan-still-superJumbo.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1 1/2 cups sugar",
      "3 eggs",
      "1 cup fresh orange juice",
      "1/2 cup vegetable oil",
      "Zest of 2 oranges",
      "1 tbsp baking powder",
      "1/2 tsp salt",
      "Powdered sugar for dusting"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease a bundt pan.",
      "Whisk flour, baking powder, and salt.",
      "Beat eggs and sugar until pale and fluffy.",
      "Add orange juice, oil, and orange zest, mix well.",
      "Gradually add dry ingredients, mixing until combined.",
      "Pour batter into pan.",
      "Bake for 45-50 minutes until golden brown.",
      "Cool in pan for 15 minutes.",
      "Dust with powdered sugar before serving."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A bright, citrusy Spanish orange cake that's incredibly moist and bursting with fresh orange flavor.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["eggs", "wheat"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 10,
    calories: 350,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "eggs", "orange juice", "vegetable oil", "orange zest", "baking powder", "salt", "powdered sugar"],
    searchKeywords: ["spanish orange cake", "orange cake", "citrus cake", "orange bundt cake", "moist orange cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cinnamon Rolls",
    tagline: "Soft and gooey cinnamon rolls with cream cheese icing",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9Qu0vAF4GgA-nFxLQca7gHmrnGNklAhewBA&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "For dough: 3 cups all-purpose flour",
      "1/4 cup sugar",
      "1 tsp salt",
      "2 1/4 tsp instant yeast",
      "3/4 cup warm milk",
      "1/4 cup melted butter",
      "1 egg",
      "For filling: 1/2 cup brown sugar",
      "2 tbsp cinnamon powder",
      "1/4 cup softened butter",
      "For icing: 1 cup powdered sugar",
      "2 tbsp milk",
      "1/2 tsp vanilla essence"
    ],
    stepsRaw: [
      "Mix warm milk, sugar, and yeast, let sit for 5 minutes.",
      "Combine flour and salt.",
      "Add yeast mixture, melted butter, and egg to flour.",
      "Knead until smooth dough forms (8-10 minutes).",
      "Place in greased bowl, cover, let rise for 1 hour.",
      "Roll dough into 12x18 inch rectangle.",
      "Spread softened butter evenly.",
      "Mix brown sugar and cinnamon, sprinkle over butter.",
      "Roll dough tightly from long edge into log.",
      "Cut into 12 equal pieces.",
      "Place in greased baking pan, cover, let rise 30 minutes.",
      "Preheat oven to 350°F (175°C).",
      "Bake for 20-25 minutes until golden brown.",
      "Mix icing ingredients, drizzle over warm rolls.",
      "Serve warm."
    ],
    difficulty: "Hard",
    cookingTime: 150,
    isActive: true,
    isHalal: true,
    description: "Soft, gooey, and irresistible cinnamon rolls with cream cheese icing, perfect for breakfast or brunch.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 12,
    calories: 380,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "salt", "instant yeast", "warm milk", "butter", "egg", "brown sugar", "cinnamon", "powdered sugar", "vanilla"],
    searchKeywords: ["cinnamon rolls", "homemade cinnamon rolls", "cinnamon buns", "cream cheese icing", "breakfast rolls"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Blueberry Muffins",
    tagline: "Soft and fluffy muffins bursting with blueberries",
    image: "https://bakerbynature.com/wp-content/uploads/2011/05/Blueberry-Muffins-1-of-1.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1 cup sugar",
      "1/2 cup melted butter",
      "2 eggs",
      "1 cup buttermilk",
      "2 tsp baking powder",
      "1/2 tsp baking soda",
      "1 tsp vanilla essence",
      "1/2 tsp salt",
      "1 1/2 cups fresh blueberries",
      "2 tbsp flour for coating blueberries"
    ],
    stepsRaw: [
      "Preheat oven to 400°F (200°C). Line muffin tin.",
      "Whisk flour, baking powder, baking soda, and salt.",
      "Whisk melted butter and sugar until combined.",
      "Add eggs one at a time, beating well after each.",
      "Mix in buttermilk and vanilla essence.",
      "Gradually fold in dry ingredients (do not overmix).",
      "Toss blueberries with 2 tbsp flour to coat.",
      "Gently fold blueberries into batter.",
      "Divide batter among muffin cups, filling each 2/3 full.",
      "Bake for 18-20 minutes until golden brown.",
      "Cool in pan for 5 minutes.",
      "Serve warm or at room temperature."
    ],
    difficulty: "Easy",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "Soft, fluffy muffins bursting with fresh blueberries, perfect for breakfast or as a snack.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 35,
    baseServings: 12,
    calories: 250,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "butter", "eggs", "buttermilk", "baking powder", "baking soda", "vanilla", "salt", "blueberries"],
    searchKeywords: ["blueberry muffins", "homemade muffins", "breakfast muffins", "blueberry breakfast", "soft muffins"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cherry Almond Coffee Cake",
    tagline: "Cherry and almond streusel coffee cake",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7KGXGkHz01bB8pH8fHHNGXpxK4_ZF1BqiJg&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "3/4 cup sugar",
      "1/2 cup butter, softened",
      "2 eggs",
      "1 cup yogurt",
      "1 tsp almond essence",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "1 cup fresh or frozen cherries, pitted",
      "For topping: 1/4 cup sliced almonds, 2 tbsp sugar"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease a 9-inch square pan.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one at a time.",
      "Mix in yogurt and almond essence.",
      "Whisk flour, baking powder, baking soda, and salt.",
      "Gradually add dry ingredients to butter mixture.",
      "Fold in cherries.",
      "Spread batter in pan.",
      "Sprinkle with almonds and sugar.",
      "Bake for 35-40 minutes until golden brown.",
      "Cool in pan for 15 minutes before serving.",
      "Serve with coffee or tea."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A delicious cherry and almond streusel coffee cake that's perfect with your morning coffee.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 9,
    calories: 370,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "butter", "eggs", "yogurt", "almond essence", "baking powder", "baking soda", "salt", "cherries", "almonds"],
    searchKeywords: ["cherry almond coffee cake", "coffee cake", "cherry cake", "almond cake", "streusel cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Swedish Princess Cake",
    tagline: "Classic Swedish layer cake with marzipan dome",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNKGu9ONn5KlCyny1dV8HDGrtsMKybPtkMig&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "For cake: 3 eggs",
      "3/4 cup sugar",
      "3/4 cup all-purpose flour",
      "1 tsp baking powder",
      "For filling: 2 cups whipped cream",
      "1 cup vanilla custard",
      "1 cup strawberry jam",
      "For covering: Marzipan (almond paste)",
      "Green food coloring"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C).",
      "Beat eggs and sugar until fluffy.",
      "Sift flour and baking powder, fold into egg mixture.",
      "Pour into cake pan.",
      "Bake for 25 minutes.",
      "Cool cake and cut into layers.",
      "Spread jam on cake layer.",
      "Add whipped cream and custard layer.",
      "Place top layer.",
      "Cover whole cake with whipped cream.",
      "Color marzipan green and roll out.",
      "Cover cake with marzipan.",
      "Decorate with marzipan rose."
    ],
    difficulty: "Hard",
    cookingTime: 120,
    isActive: true,
    isHalal: true,
    description: "A classic Swedish princess cake with layers of sponge, jam, custard, whipped cream, and a green marzipan dome.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "premium",
    costPerServing: 100,
    baseServings: 10,
    calories: 520,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["eggs", "sugar", "all-purpose flour", "baking powder", "whipped cream", "vanilla custard", "strawberry jam", "marzipan", "green food coloring"],
    searchKeywords: ["swedish princess cake", "princess cake", "marzipan cake", "layer cake", "scandinavian cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Russian Honey Cake",
    tagline: "Layered honey cake with sour cream frosting",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcSK0q_8hsHxqGKyhHkENFFlo5Gywjk9Pz8Q&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "3 eggs",
      "1 cup honey",
      "1 cup sugar",
      "2 cups all-purpose flour",
      "1 tsp baking soda",
      "1/2 cup butter",
      "For cream: 2 cups sour cream",
      "1 cup whipped cream",
      "1/2 cup powdered sugar"
    ],
    stepsRaw: [
      "Melt butter, honey, sugar together.",
      "Let cool slightly.",
      "Add eggs, mix well.",
      "Mix flour and baking soda.",
      "Divide dough into 8-10 thin layers.",
      "Bake each layer for 5-7 minutes.",
      "Mix sour cream, whipped cream, powdered sugar for cream.",
      "Spread cream between cake layers.",
      "Cover top and sides with cream.",
      "Decorate with cake crumbs.",
      "Refrigerate for 12 hours before serving."
    ],
    difficulty: "Hard",
    cookingTime: 180,
    isActive: true,
    isHalal: true,
    description: "A traditional Russian honey cake with multiple thin layers and a rich sour cream frosting, also known as Medovik.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 10,
    calories: 480,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["eggs", "honey", "sugar", "all-purpose flour", "baking soda", "butter", "sour cream", "whipped cream", "powdered sugar"],
    searchKeywords: ["russian honey cake", "medovik", "honey cake", "layered cake", "russian dessert"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Almond Sponge Roll",
    tagline: "Light almond sponge cake rolled with cream",
    image: "https://www.kingarthurbaking.com/sites/default/files/styles/featured_image/public/2019-10/almond-roll.jpg?itok=7IzXxgDh",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 eggs, separated",
      "3/4 cup sugar",
      "3/4 cup ground almonds",
      "1/4 cup all-purpose flour",
      "1 tsp vanilla essence",
      "For filling: 1 1/2 cups whipped cream",
      "1/2 cup powdered sugar",
      "Sliced almonds for decoration"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C).",
      "Line baking sheet with parchment paper.",
      "Beat egg whites until stiff peaks form.",
      "Gradually add sugar while beating.",
      "Add egg yolks and vanilla essence.",
      "Mix ground almonds and flour, fold into egg mixture.",
      "Spread batter on baking sheet.",
      "Bake for 10-12 minutes.",
      "Roll cake in warm towel.",
      "Let cool completely.",
      "Mix whipped cream and powdered sugar.",
      "Unroll cake, spread cream, roll again.",
      "Decorate with sliced almonds."
    ],
    difficulty: "Hard",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "A light almond sponge cake rolled with sweet whipped cream, perfect for tea time or dessert.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 8,
    calories: 380,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["eggs", "sugar", "ground almonds", "all-purpose flour", "vanilla", "whipped cream", "powdered sugar", "sliced almonds"],
    searchKeywords: ["almond sponge roll", "almond roll cake", "sponge roll", "swiss roll", "cream roll"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chocolate Butter Cake",
    tagline: "Rich and moist chocolate butter cake",
    image: "https://theunlikelybaker.com/wp-content/uploads/2024/08/Chocolate-Butter-Mochi-Feature.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 3/4 cups all-purpose flour",
      "2 cups sugar",
      "3/4 cup cocoa powder",
      "1 1/2 tsp baking powder",
      "1 1/2 tsp baking soda",
      "1 tsp salt",
      "2 eggs",
      "1 cup milk",
      "1/2 cup vegetable oil",
      "2 tsp vanilla essence",
      "1 cup boiling water"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease cake pans.",
      "Mix flour, sugar, cocoa, baking powder, baking soda, salt.",
      "Beat eggs, milk, oil, vanilla essence together.",
      "Add wet ingredients to dry, mix well.",
      "Add boiling water, mix (batter will be thin).",
      "Divide batter between pans.",
      "Bake for 30-35 minutes.",
      "Cool completely before frosting with chocolate buttercream."
    ],
    difficulty: "Medium",
    cookingTime: 50,
    isActive: true,
    isHalal: true,
    description: "A rich, moist, and decadent chocolate butter cake that's perfect for chocolate lovers.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 55,
    baseServings: 10,
    calories: 420,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "cocoa powder", "baking powder", "baking soda", "salt", "eggs", "milk", "vegetable oil", "vanilla", "boiling water"],
    searchKeywords: ["chocolate butter cake", "moist chocolate cake", "chocolate cake", "butter cake", "birthday cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Whipped Cream Frosting",
    tagline: "Light and fluffy homemade whipped cream",
    image: "https://img.sndimg.com/food/image/upload/q_92,fl_progressive,w_1200,c_scale/v1/img/recipes/39/01/3/aeAtoOWHSeWQh9UD7W3K_0S9A6192.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups heavy cream",
      "1/2 cup powdered sugar",
      "1 tsp vanilla essence"
    ],
    stepsRaw: [
      "Chill bowl and beaters in refrigerator.",
      "Pour heavy cream into cold bowl.",
      "Beat on medium speed until soft peaks form.",
      "Gradually add powdered sugar while beating.",
      "Add vanilla essence.",
      "Beat until stiff peaks form.",
      "Use immediately to frost cakes.",
      "Refrigerate if not using right away."
    ],
    difficulty: "Easy",
    cookingTime: 10,
    isActive: true,
    isHalal: true,
    description: "A light, fluffy, and homemade whipped cream frosting that's perfect for cakes, cupcakes, and desserts.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy"],
    budget: "economy",
    costPerServing: 25,
    baseServings: 2,
    calories: 280,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["heavy cream", "powdered sugar", "vanilla essence"],
    searchKeywords: ["whipped cream frosting", "homemade whipped cream", "whipped cream", "cake frosting", "cream topping"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Chocolate Fudge Cake",
    tagline: "Decadent chocolate cake with fudge frosting",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 3/4 cups all-purpose flour",
      "2 cups sugar",
      "3/4 cup cocoa powder",
      "1 1/2 tsp baking powder",
      "1 1/2 tsp baking soda",
      "1 tsp salt",
      "2 eggs",
      "1 cup milk",
      "1/2 cup vegetable oil",
      "2 tsp vanilla essence",
      "1 cup boiling water",
      "For fudge frosting: 1 cup chocolate chips, 1/2 cup cream"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Prepare cake pans.",
      "Mix dry ingredients in large bowl.",
      "Beat eggs, milk, oil, vanilla together.",
      "Add wet ingredients to dry, mix well.",
      "Add boiling water, mix until smooth.",
      "Divide batter between pans.",
      "Bake for 30-35 minutes.",
      "For frosting: Heat cream until steaming.",
      "Pour over chocolate chips, let sit 2 minutes.",
      "Whisk until smooth and glossy.",
      "Frost cooled cake with chocolate fudge."
    ],
    difficulty: "Hard",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A decadent chocolate fudge cake with rich, glossy fudge frosting, perfect for special occasions.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 70,
    baseServings: 10,
    calories: 520,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "cocoa powder", "baking powder", "baking soda", "salt", "eggs", "milk", "vegetable oil", "vanilla", "boiling water", "chocolate chips", "cream"],
    searchKeywords: ["chocolate fudge cake", "fudge cake", "decadent chocolate cake", "chocolate cake", "birthday cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Lemon Drizzle Cake",
    tagline: "Tangy lemon cake with sweet drizzle",
    image: "https://www.amummytoo.co.uk/wp-content/uploads/2024/03/lemon-drizzle-cake-recipe-serving.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 3/4 cups all-purpose flour",
      "1 cup sugar",
      "1/2 cup butter, room temperature",
      "3 eggs",
      "1/2 cup milk",
      "Zest of 2 lemons",
      "Juice of 1 lemon",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "For drizzle: 1/2 cup powdered sugar, 2 tbsp lemon juice"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease loaf pan.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one at a time.",
      "Mix in lemon zest and juice.",
      "Whisk flour, baking powder, baking soda, salt.",
      "Add milk and flour mixture alternately to batter.",
      "Pour batter into pan.",
      "Bake for 45-50 minutes.",
      "Mix powdered sugar and lemon juice for drizzle.",
      "Poke holes in warm cake with skewer.",
      "Pour drizzle over warm cake.",
      "Let cool completely before slicing."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A tangy and sweet lemon drizzle cake with a crisp sugary crust and moist, citrusy interior.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 8,
    calories: 350,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "butter", "eggs", "milk", "lemon zest", "lemon juice", "baking powder", "baking soda", "salt", "powdered sugar"],
    searchKeywords: ["lemon drizzle cake", "lemon cake", "citrus cake", "tangy lemon cake", "loaf cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Carrot Cake",
    tagline: "Spiced carrot cake with cream cheese frosting",
    image: "https://vikalinka.com/wp-content/uploads/2022/03/Carrot-Cake-14-Edit.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups grated carrots",
      "2 cups all-purpose flour",
      "1 1/2 cups sugar",
      "1 cup vegetable oil",
      "4 eggs",
      "1 cup chopped walnuts",
      "1 tsp baking powder",
      "1 tsp baking soda",
      "1 tsp cinnamon powder",
      "1/2 tsp nutmeg powder",
      "1/2 tsp salt",
      "For cream cheese frosting: 200g cream cheese, 1/2 cup butter, 2 cups powdered sugar"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease cake pans.",
      "Beat eggs and sugar until fluffy.",
      "Add oil, mix well.",
      "Mix flour, baking powder, baking soda, cinnamon, nutmeg, salt.",
      "Add dry ingredients to egg mixture.",
      "Fold in carrots and walnuts.",
      "Divide batter between pans.",
      "Bake for 30-35 minutes.",
      "For frosting: Beat cream cheese and butter until smooth.",
      "Gradually add powdered sugar.",
      "Frost cooled cake layers.",
      "Decorate with extra walnuts."
    ],
    difficulty: "Medium",
    cookingTime: 60,
    isActive: true,
    isHalal: true,
    description: "A spiced carrot cake with creamy cheese frosting and crunchy walnuts, perfect for any occasion.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 65,
    baseServings: 10,
    calories: 490,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["carrots", "all-purpose flour", "sugar", "vegetable oil", "eggs", "walnuts", "baking powder", "baking soda", "cinnamon", "nutmeg", "salt", "cream cheese", "butter", "powdered sugar"],
    searchKeywords: ["carrot cake", "cream cheese frosting", "spiced carrot cake", "walnut cake", "layer cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Marble Cake",
    tagline: "Beautiful swirls of vanilla and chocolate",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQJqwjQTeFo1FQEB9xLqYMFcWHpt0gXOJ5UQ&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1 1/2 cups sugar",
      "1 cup butter, room temperature",
      "4 eggs",
      "1 cup milk",
      "1 tsp vanilla essence",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "1/4 cup cocoa powder",
      "2 tbsp hot water"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease bundt pan.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one at a time.",
      "Mix in vanilla essence.",
      "Whisk flour, baking powder, baking soda, salt.",
      "Add milk and flour mixture alternately to batter.",
      "Divide batter in half.",
      "Mix cocoa powder and hot water, add to one half.",
      "Alternate spoonfuls of vanilla and chocolate batter in pan.",
      "Swirl with knife for marble effect.",
      "Bake for 45-50 minutes.",
      "Cool in pan for 15 minutes."
    ],
    difficulty: "Medium",
    cookingTime: 65,
    isActive: true,
    isHalal: true,
    description: "A beautiful marble cake with swirls of vanilla and chocolate, perfect for tea time.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 10,
    calories: 420,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "butter", "eggs", "milk", "vanilla", "baking powder", "baking soda", "salt", "cocoa powder", "hot water"],
    searchKeywords: ["marble cake", "vanilla chocolate cake", "swirl cake", "bundt cake", "tea cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Coconut Cake",
    tagline: "Moist coconut cake with coconut frosting",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnRIq-0EjSkxVDSfqmfljHVNKk0_UV87Ob9A&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1 1/2 cups sugar",
      "1 cup butter, room temperature",
      "4 eggs",
      "1 cup coconut milk",
      "1 cup grated coconut",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "1 tsp vanilla essence",
      "For frosting: 2 cups whipped cream, 1 cup grated coconut"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease cake pans.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one at a time.",
      "Mix in vanilla essence.",
      "Whisk flour, baking powder, baking soda, salt.",
      "Add coconut milk and flour mixture alternately.",
      "Fold in grated coconut.",
      "Divide batter between pans.",
      "Bake for 25-30 minutes.",
      "Cool completely.",
      "Frost with whipped cream.",
      "Coat with grated coconut."
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A moist coconut cake with creamy whipped cream frosting and shredded coconut, perfect for coconut lovers.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 55,
    baseServings: 10,
    calories: 460,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "butter", "eggs", "coconut milk", "grated coconut", "baking powder", "baking soda", "salt", "vanilla", "whipped cream"],
    searchKeywords: ["coconut cake", "coconut cream cake", "moist coconut cake", "coconut frosting", "layer cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Strawberry Shortcake",
    tagline: "Biscuit-style cake with fresh strawberries",
    image: "https://britneybreaksbread.com/wp-content/uploads/2025/05/strawberry-shortcake-with-pound-cake-2.jpg",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups all-purpose flour",
      "1/3 cup sugar",
      "1 tbsp baking powder",
      "1/2 tsp salt",
      "1/2 cup cold butter",
      "2/3 cup milk",
      "1 egg",
      "For filling: 2 cups sliced strawberries, 2 tbsp sugar",
      "For cream: 2 cups whipped cream"
    ],
    stepsRaw: [
      "Preheat oven to 425°F (220°C).",
      "Mix flour, sugar, baking powder, salt.",
      "Cut cold butter into flour mixture.",
      "Beat milk and egg together, add to flour mixture.",
      "Knead gently, roll out, cut into circles.",
      "Bake for 15 minutes until golden.",
      "Mix strawberries with sugar.",
      "Split shortcakes in half.",
      "Fill with whipped cream and strawberries.",
      "Top with other half.",
      "Serve immediately."
    ],
    difficulty: "Medium",
    cookingTime: 30,
    isActive: true,
    isHalal: true,
    description: "A classic strawberry shortcake with tender biscuit layers, fresh strawberries, and whipped cream.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 60,
    baseServings: 6,
    calories: 420,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "baking powder", "salt", "cold butter", "milk", "egg", "strawberries", "whipped cream"],
    searchKeywords: ["strawberry shortcake", "shortcake", "strawberry dessert", "summer dessert", "berry cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Pineapple Upside Down Cake",
    tagline: "Caramelized pineapple ring cake",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV64SvGoK8tvOktVcC__8q99fEXRmHztmiaA&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "For topping: 1/4 cup butter",
      "1/2 cup brown sugar",
      "6-7 pineapple rings",
      "Maraschino cherries",
      "For cake: 1 1/2 cups all-purpose flour",
      "1 cup sugar",
      "1/2 cup butter, room temperature",
      "2 eggs",
      "1/2 cup pineapple juice",
      "1 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C).",
      "Melt butter in cake pan.",
      "Sprinkle brown sugar over butter.",
      "Arrange pineapple rings and cherries.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one at a time.",
      "Whisk flour, baking powder, baking soda, salt.",
      "Add pineapple juice and flour mixture alternately.",
      "Pour batter over pineapple arrangement.",
      "Bake for 35-40 minutes.",
      "Immediately invert onto serving plate.",
      "Serve warm."
    ],
    difficulty: "Medium",
    cookingTime: 55,
    isActive: true,
    isHalal: true,
    description: "A classic pineapple upside down cake with caramelized pineapple rings and cherries, best served warm.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 50,
    baseServings: 8,
    calories: 420,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["butter", "brown sugar", "pineapple rings", "maraschino cherries", "all-purpose flour", "sugar", "eggs", "pineapple juice", "baking powder", "baking soda", "salt"],
    searchKeywords: ["pineapple upside down cake", "upside down cake", "pineapple cake", "retro cake", "caramelized pineapple"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Fluffy Vanilla Cake",
    tagline: "Extra fluffy and light vanilla layer cake",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr4PHChVfFJRLTOkLFLASOeVFVECM1VLi09A&s",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 1/4 cups all-purpose flour",
      "1 1/2 cups sugar",
      "3/4 cup butter, room temperature",
      "3 eggs",
      "1 cup milk",
      "2 1/2 tsp baking powder",
      "1/2 tsp salt",
      "2 tsp vanilla essence"
    ],
    stepsRaw: [
      "Preheat oven to 350°F (180°C). Grease cake pans.",
      "Cream butter and sugar until fluffy.",
      "Add eggs one at a time.",
      "Mix in vanilla essence.",
      "Whisk flour, baking powder, salt.",
      "Add milk and flour mixture alternately.",
      "Divide batter between pans.",
      "Bake for 25-30 minutes.",
      "Cool completely before frosting."
    ],
    difficulty: "Medium",
    cookingTime: 45,
    isActive: true,
    isHalal: true,
    description: "An extra fluffy and light vanilla layer cake that's perfect for birthdays and celebrations.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "standard",
    costPerServing: 45,
    baseServings: 8,
    calories: 400,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["all-purpose flour", "sugar", "butter", "eggs", "milk", "baking powder", "salt", "vanilla"],
    searchKeywords: ["fluffy vanilla cake", "vanilla cake", "light vanilla cake", "birthday cake", "layer cake"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "French Heart Puff",
    tagline: "Flaky puff pastry hearts with chocolate",
    image: "https://i.ytimg.com/vi/D7ZTYrTLv8A/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLABv0l7wmdZvMsfrPlLjazrS9U2fQ",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 sheet puff pastry",
      "1 cup chocolate hazelnut spread",
      "1 egg, beaten",
      "1 tbsp milk",
      "Powdered sugar for dusting"
    ],
    stepsRaw: [
      "Preheat oven to 400°F (200°C).",
      "Roll out puff pastry.",
      "Cut heart shapes with cookie cutter.",
      "Spread chocolate on half the hearts.",
      "Top with remaining hearts.",
      "Seal edges with fork.",
      "Mix egg and milk, brush on pastries.",
      "Bake for 15-20 minutes until puffed and golden.",
      "Dust with powdered sugar.",
      "Serve warm."
    ],
    difficulty: "Easy",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Flaky puff pastry hearts filled with chocolate hazelnut spread, perfect for Valentine's Day or any special occasion.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Dessert", "Snack"],
    allergens: ["dairy", "eggs", "wheat", "nuts"],
    budget: "standard",
    costPerServing: 40,
    baseServings: 6,
    calories: 320,
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
    pantryKeywords: ["puff pastry", "chocolate hazelnut spread", "egg", "milk", "powdered sugar"],
    searchKeywords: ["french heart puff", "puff pastry hearts", "chocolate hearts", "valentine dessert", "easy pastry"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  },
  {
    title: "Cake Rusk",
    tagline: "Crispy twice-baked cake perfect with tea",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_Z1IBAdxCGUZ-0tQv7ZVmvXTC8aAPLPDMfA&s",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "Leftover cake or plain cake",
      "1/2 cup sugar",
      "1/2 cup milk",
      "1/2 tsp cardamom powder",
      "Ghee for frying"
    ],
    stepsRaw: [
      "Cut cake into 1-inch thick slices.",
      "Boil sugar and milk to make syrup.",
      "Add cardamom powder to syrup.",
      "Dip cake slices in syrup briefly.",
      "Heat ghee in pan.",
      "Fry cake slices until golden brown.",
      "Drain on paper towels.",
      "Let cool completely.",
      "Store in airtight container.",
      "Serve with tea."
    ],
    difficulty: "Medium",
    cookingTime: 25,
    isActive: true,
    isHalal: true,
    description: "Crispy twice-baked cake rusks flavored with cardamom, perfect for dipping in tea.",
    category: "Snacks",
    subCategory: "baking",
    dietType: "Vegetarian",
    suitableForMeals: ["Snack", "Breakfast"],
    allergens: ["dairy", "eggs", "wheat"],
    budget: "economy",
    costPerServing: 20,
    baseServings: 6,
    calories: 180,
    ageGroup: ["adults", "kids", "seniors"],
    patientFriendly: ["general"],
    pantryKeywords: ["cake", "sugar", "milk", "cardamom", "ghee"],
    searchKeywords: ["cake rusk", "rusk", "tea rusk", "pakistani rusk", "biscuit with tea"],
    isFeatured: false,
    averageRating: 0,
    totalRatings: 0,
    timesSuggested: 0,
    timesUsedInPlans: 0
  }
]

async function migrate() {
  try {
    // Check which environment variable is available
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    
    console.log('🔍 MONGODB_URI:', process.env.MONGODB_URI);
    console.log('🔍 MONGOURI:', process.env.MONGOURI);
    console.log('🔍 MONGO_URI:', process.env.MONGO_URI);
    console.log('🔍 Using URI:', mongoURI ? 'Found' : 'NOT FOUND');
    console.log('🔍 Current directory:', __dirname);
    
    if (!mongoURI) {
      throw new Error('MongoDB URI not found in environment variables. Please check your .env file');
    }
    
    console.log('🔌 Connecting to MongoDB...');
    
    await mongoose.connect(mongoURI, {
      serverSelectionTimeoutMS: 10000,
      family: 4
    });
    
    console.log('✅ Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`✅ Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`⚠️ Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\n🎉 Migration Complete!');
    console.log(`📊 Added: ${added}, Skipped: ${skipped}`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

migrate();