// 11-quick.js
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
  // ==================== 5-MINUTE RECIPES (1-10) ====================
  {
    title: "Chicken Maggi",
    tagline: "Quick noodles with shredded chicken",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "Asian",
    ingredientsRaw: [
      "1 packet Maggi noodles",
      "½ cup boiled chicken, shredded",
      "1½ cups water",
      "Maggi tastemaker",
      "1 tablespoon oil or butter",
      "¼ cup chopped vegetables (carrot, peas, corn)",
      "½ teaspoon black pepper",
      "1 tablespoon chopped coriander"
    ],
    stepsRaw: [
      "Boil 1½ cups water in a small pan.",
      "Add Maggi noodles and tastemaker to boiling water.",
      "Add chopped vegetables and cook for 2 minutes.",
      "Add shredded chicken and mix well.",
      "Cook for another 2-3 minutes until noodles are soft.",
      "Add oil or butter and black pepper.",
      "Mix everything well and cook for 1 minute.",
      "Garnish with chopped coriander.",
      "Serve hot immediately."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 5,
    servings: 1,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Anda Paratha",
    tagline: "Egg-stuffed paratha for quick breakfast",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 ready-made parathas",
      "2 eggs",
      "1 small onion, finely chopped",
      "1 green chili, chopped",
      "2 tablespoons chopped coriander",
      "Salt to taste",
      "¼ teaspoon black pepper",
      "2 tablespoons oil or ghee"
    ],
    stepsRaw: [
      "Heat a frying pan on medium heat.",
      "Add 1 tablespoon oil and place one paratha.",
      "Cook for 1 minute until slightly crispy.",
      "In a bowl, beat one egg with salt and pepper.",
      "Add half of chopped onion, chili, and coriander to egg.",
      "Pour egg mixture over the paratha in pan.",
      "Carefully flip the paratha to cook egg side.",
      "Cook for 1-2 minutes until egg is set.",
      "Repeat with second paratha.",
      "Serve hot with ketchup or chutney."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 5,
    servings: 2,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Omlette Sandwich",
    tagline: "Protein-packed omlette between bread",
    image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "International",
    ingredientsRaw: [
      "4 slices of bread",
      "3 eggs",
      "1 small onion, finely chopped",
      "1 small tomato, chopped",
      "1 green chili, chopped (optional)",
      "2 tablespoons chopped coriander",
      "Salt to taste",
      "¼ teaspoon black pepper",
      "2 tablespoons butter or oil"
    ],
    stepsRaw: [
      "Break eggs into a bowl and beat well.",
      "Add onion, tomato, green chili, and coriander.",
      "Add salt and pepper, mix everything well.",
      "Heat butter or oil in frying pan on medium heat.",
      "Pour egg mixture into pan and spread evenly.",
      "Cook for 1-2 minutes until bottom is set.",
      "Place two bread slices on top of omlette.",
      "Carefully flip the omlette with bread slices attached.",
      "Cook for another 1-2 minutes until bread is toasted.",
      "Repeat with remaining bread and egg mixture.",
      "Cut sandwiches diagonally and serve hot."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 5,
    servings: 2,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Cup Noodles",
    tagline: "Instant noodles in a cup",
    image: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "Asian",
    ingredientsRaw: [
      "1 cup instant noodles (any brand)",
      "Boiling water as needed",
      "Optional add-ons:",
      "2 tablespoons chopped spring onions",
      "½ teaspoon soy sauce",
      "¼ teaspoon chili flakes",
      "1 tablespoon sweet corn"
    ],
    stepsRaw: [
      "Open the cup noodles and remove seasoning packet.",
      "Add seasoning powder to noodles in cup.",
      "Add spring onions and sweet corn if using.",
      "Pour boiling water into cup up to marked line.",
      "Add soy sauce and chili flakes if desired.",
      "Close the lid and let it sit for 3 minutes.",
      "After 3 minutes, stir well with fork.",
      "Add extra seasoning if needed.",
      "Enjoy directly from the cup."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 3,
    servings: 1,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Butter Toast with Jam",
    tagline: "Crispy toast with jam",
    image: "https://images.unsplash.com/photo-1577303935007-0d306ee638cf?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "International",
    ingredientsRaw: [
      "2 slices of bread",
      "2 tablespoons butter",
      "2 tablespoons fruit jam (any flavor)",
      "Pinch of cinnamon powder (optional)"
    ],
    stepsRaw: [
      "Take bread slices and spread butter evenly on one side.",
      "Heat a frying pan on medium heat.",
      "Place bread butter-side down in pan.",
      "Cook for 1-2 minutes until golden brown.",
      "Spread more butter on top side while cooking.",
      "Flip and cook other side for 1-2 minutes.",
      "Remove from pan and spread jam on one slice.",
      "Sprinkle cinnamon powder if using.",
      "Put slices together or enjoy separately.",
      "Serve hot with tea or coffee."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 5,
    servings: 1,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Fruit Raita",
    tagline: "Yogurt with mixed fruits",
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "Indian",
    ingredientsRaw: [
      "1 cup plain yogurt",
      "½ cup mixed fruits (apple, banana, grapes)",
      "1 tablespoon sugar or honey",
      "¼ teaspoon roasted cumin powder",
      "Pinch of salt",
      "1 tablespoon chopped nuts (optional)"
    ],
    stepsRaw: [
      "Take yogurt in bowl and whisk until smooth.",
      "Add sugar or honey and mix well.",
      "Add roasted cumin powder and salt.",
      "Wash and chop fruits into small pieces.",
      "Add chopped fruits to yogurt mixture.",
      "Mix gently to coat fruits with yogurt.",
      "If using nuts, add them now.",
      "Chill in refrigerator for 15 minutes.",
      "Serve cold as side dish or dessert."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 5,
    servings: 2,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Cornflakes with Milk",
    tagline: "Classic breakfast cereal",
    image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "International",
    ingredientsRaw: [
      "1 cup cornflakes",
      "1 cup milk (cold or warm)",
      "1 tablespoon sugar or honey (optional)",
      "½ banana, sliced (optional)",
      "¼ cup mixed berries (optional)"
    ],
    stepsRaw: [
      "Take a cereal bowl.",
      "Add 1 cup of cornflakes to bowl.",
      "If using fruits, add sliced banana and berries.",
      "Pour milk over cornflakes until just covered.",
      "Add sugar or honey if desired.",
      "Mix lightly and serve immediately.",
      "For warm version: warm milk first.",
      "Eat immediately to keep cornflakes crunchy."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 2,
    servings: 1,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Peanut Butter Sandwich",
    tagline: "Nutritious peanut butter toast",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "International",
    ingredientsRaw: [
      "2 slices of bread",
      "2 tablespoons peanut butter",
      "1 teaspoon honey",
      "½ banana, sliced",
      "Pinch of cinnamon powder"
    ],
    stepsRaw: [
      "Toast bread slices until golden brown.",
      "Spread peanut butter evenly on warm toast.",
      "Drizzle honey over peanut butter.",
      "Arrange banana slices on peanut butter.",
      "Sprinkle cinnamon powder on top.",
      "Put two slices together or enjoy separately.",
      "Cut diagonally for better presentation.",
      "Serve immediately.",
      "Great for breakfast or quick snack."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 5,
    servings: 1,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Boiled Eggs",
    tagline: "Perfect protein-packed eggs",
    image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "International",
    ingredientsRaw: [
      "2 eggs",
      "Water for boiling",
      "Salt to taste",
      "¼ teaspoon black pepper",
      "Optional: chaat masala, soy sauce"
    ],
    stepsRaw: [
      "Take eggs and wash under running water.",
      "Place eggs in small pot.",
      "Add enough water to cover eggs completely.",
      "Bring water to boil on high heat.",
      "Once boiling, reduce heat to medium.",
      "Boil for 8-10 minutes for hard-boiled eggs.",
      "For soft-boiled: boil for 5-6 minutes.",
      "Remove eggs and place in cold water for 2 minutes.",
      "Peel eggs carefully.",
      "Sprinkle salt, pepper, or favorite seasoning.",
      "Serve with bread or as protein snack."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 10,
    servings: 1,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Yogurt with Sugar",
    tagline: "Simple sweet yogurt",
    image: "https://images.unsplash.com/photo-1606913853347-bb6e96f5d7b6?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "Indian",
    ingredientsRaw: [
      "1 cup plain yogurt",
      "2 tablespoons sugar",
      "¼ teaspoon cardamom powder",
      "1 tablespoon chopped nuts (almonds, pistachios)",
      "Few saffron strands (optional)"
    ],
    stepsRaw: [
      "Take yogurt in bowl and whisk until smooth.",
      "Add sugar and mix well until dissolved.",
      "Add cardamom powder and mix.",
      "If using saffron, soak in 1 tablespoon warm milk.",
      "Add saffron milk to yogurt if using.",
      "Mix everything gently.",
      "Garnish with chopped nuts.",
      "Serve chilled or at room temperature.",
      "Simple and refreshing dessert."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 5,
    servings: 1,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },

  // ==================== 10-MINUTE RECIPES (11-20) ====================
  {
    title: "French Toast",
    tagline: "Egg-dipped golden toast",
    image: "https://images.unsplash.com/photo-1483137140003-ae073b395549?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "French",
    ingredientsRaw: [
      "2 slices of bread",
      "1 egg",
      "2 tablespoons milk",
      "1 teaspoon sugar",
      "¼ teaspoon vanilla extract (optional)",
      "Pinch of cinnamon powder",
      "1 tablespoon butter or oil",
      "Honey or maple syrup for serving"
    ],
    stepsRaw: [
      "In shallow bowl, beat egg well.",
      "Add milk, sugar, vanilla, and cinnamon.",
      "Mix everything well.",
      "Heat butter or oil in frying pan on medium heat.",
      "Dip bread slice in egg mixture, coating both sides.",
      "Let excess drip off.",
      "Place in hot pan and cook for 2-3 minutes per side.",
      "Cook until golden brown on both sides.",
      "Repeat with second slice.",
      "Serve hot with honey or maple syrup."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 10,
    servings: 1,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Scrambled Eggs",
    tagline: "Fluffy scrambled eggs",
    image: "https://images.unsplash.com/photo-1593614911681-ee6c8c7b6163?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "International",
    ingredientsRaw: [
      "2 eggs",
      "1 tablespoon milk or water",
      "Salt to taste",
      "¼ teaspoon black pepper",
      "1 teaspoon butter or oil",
      "1 tablespoon chopped onion (optional)",
      "1 tablespoon chopped tomato (optional)"
    ],
    stepsRaw: [
      "Break eggs into bowl.",
      "Add milk, salt, and pepper.",
      "Beat well with fork until fluffy.",
      "If using vegetables, add them now.",
      "Heat butter or oil in pan on medium heat.",
      "Pour egg mixture into pan.",
      "Let it set for 30 seconds.",
      "Gently stir with spatula, pushing cooked parts to center.",
      "Cook until eggs are set but still moist.",
      "Remove from heat immediately.",
      "Serve hot with toast or bread."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 5,
    servings: 1,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Ready-made Paratha with Anda",
    tagline: "Paratha with scrambled eggs",
    image: "https://images.unsplash.com/photo-1559919436-8d6f6ee0117a?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 ready-made parathas",
      "2 eggs",
      "1 small onion, chopped",
      "1 green chili, chopped",
      "Salt to taste",
      "¼ teaspoon black pepper",
      "2 tablespoons oil or ghee",
      "2 tablespoons chopped coriander"
    ],
    stepsRaw: [
      "Heat oil in pan, add chopped onion.",
      "Cook until onion is translucent.",
      "Add green chili and cook for 30 seconds.",
      "Break eggs directly into pan.",
      "Add salt and pepper.",
      "Scramble eggs with vegetables.",
      "Cook until eggs are done but still soft.",
      "Heat parathas separately in another pan.",
      "Place scrambled eggs on one paratha.",
      "Cover with second paratha or fold.",
      "Garnish with chopped coriander.",
      "Serve hot with ketchup or raita."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 10,
    servings: 2,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Chana Chaat",
    tagline: "Spicy chickpea salad",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "Indian",
    ingredientsRaw: [
      "1 cup boiled chickpeas (canned or fresh)",
      "1 small onion, finely chopped",
      "1 small tomato, chopped",
      "½ cucumber, chopped",
      "1 green chili, chopped (optional)",
      "1 tablespoon chopped coriander",
      "1 teaspoon chaat masala",
      "½ teaspoon roasted cumin powder",
      "1 tablespoon lemon juice",
      "Salt to taste"
    ],
    stepsRaw: [
      "If using canned chickpeas, drain and rinse well.",
      "In large bowl, combine chickpeas, onion, tomato, cucumber.",
      "Add green chili if using.",
      "Add chaat masala, cumin powder, and salt.",
      "Mix everything well.",
      "Add lemon juice and mix again.",
      "Garnish with fresh coriander.",
      "Taste and adjust seasoning.",
      "Serve immediately as snack or light meal."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 10,
    servings: 2,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Vegetable Sandwich",
    tagline: "Fresh veggie sandwich",
    image: "https://images.unsplash.com/photo-1572799011048-50b9c6d2937f?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "International",
    ingredientsRaw: [
      "4 slices of bread",
      "1 boiled potato, sliced",
      "1 cucumber, thinly sliced",
      "1 tomato, thinly sliced",
      "1 small onion, thinly sliced",
      "4 lettuce leaves",
      "Butter for spreading",
      "Green chutney or mayonnaise",
      "Salt and pepper to taste"
    ],
    stepsRaw: [
      "Spread butter on one side of each bread slice.",
      "Spread green chutney or mayonnaise on buttered side.",
      "Layer lettuce leaf on one slice.",
      "Arrange potato slices, cucumber, tomato, and onion.",
      "Sprinkle salt and pepper.",
      "Cover with another bread slice, buttered side down.",
      "Repeat for second sandwich.",
      "Cut diagonally into triangles.",
      "Serve immediately."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 10,
    servings: 2,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Pasta with Ready Sauce",
    tagline: "Quick pasta with jar sauce",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "Italian",
    ingredientsRaw: [
      "1 cup pasta (penne, macaroni, or spaghetti)",
      "2 cups water",
      "Salt for boiling water",
      "½ cup ready tomato pasta sauce",
      "1 teaspoon olive oil or butter",
      "¼ teaspoon dried oregano",
      "¼ teaspoon chili flakes",
      "2 tablespoons grated cheese"
    ],
    stepsRaw: [
      "Boil water in pot with salt.",
      "Add pasta and cook for 8-10 minutes or as per instructions.",
      "Drain pasta, saving some pasta water.",
      "Heat pasta sauce in same pot.",
      "Add cooked pasta to sauce.",
      "Add oregano, chili flakes, and olive oil.",
      "Mix well, adding pasta water if too dry.",
      "Cook for 1-2 minutes more.",
      "Add grated cheese and mix.",
      "Serve hot immediately."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 10,
    servings: 1,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Leftover Rice Fry",
    tagline: "Quick fried rice",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "Asian",
    ingredientsRaw: [
      "2 cups leftover cooked rice",
      "1 egg (optional)",
      "½ cup mixed vegetables (peas, carrots, corn)",
      "1 small onion, chopped",
      "2 tablespoons soy sauce",
      "1 tablespoon oil",
      "Salt and pepper to taste",
      "Spring onions for garnish"
    ],
    stepsRaw: [
      "Heat oil in wok or large pan.",
      "Add chopped onion and cook until soft.",
      "Add mixed vegetables and cook for 2 minutes.",
      "Push vegetables to side, add egg and scramble if using.",
      "Add leftover rice and break up any lumps.",
      "Add soy sauce, salt, and pepper.",
      "Mix everything well and cook for 3-4 minutes.",
      "Garnish with chopped spring onions.",
      "Serve hot as complete meal."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 10,
    servings: 2,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Daal Chawal",
    tagline: "Comforting lentils with rice",
    image: "https://images.unsplash.com/photo-1585937421612-70ca003675ed?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "½ cup masoor dal (red lentils)",
      "1 cup rice",
      "3 cups water",
      "1 teaspoon turmeric powder",
      "1 teaspoon salt",
      "1 tablespoon ghee or oil",
      "½ teaspoon cumin seeds",
      "1 dried red chili (optional)",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Wash dal and rice separately.",
      "In pressure cooker, add dal, rice, water, turmeric, and salt.",
      "Close lid and cook for 2 whistles on medium heat.",
      "Let pressure release naturally.",
      "For tempering: heat ghee in small pan.",
      "Add cumin seeds and red chili.",
      "Pour tempering over cooked daal chawal.",
      "Mix gently and garnish with coriander.",
      "Serve hot with pickle or yogurt."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 10,
    servings: 2,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Chicken Mayo Sandwich",
    tagline: "Creamy chicken sandwich",
    image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "International",
    ingredientsRaw: [
      "4 slices of bread",
      "1 cup shredded cooked chicken",
      "¼ cup mayonnaise",
      "2 tablespoons chopped celery or onion",
      "4 lettuce leaves",
      "Salt and pepper to taste",
      "Butter for toasting"
    ],
    stepsRaw: [
      "Mix shredded chicken with mayonnaise.",
      "Add chopped celery or onion.",
      "Season with salt and pepper.",
      "Butter bread slices on one side.",
      "Place lettuce leaf on unbuttered side of one slice.",
      "Spread chicken mixture over lettuce.",
      "Cover with second bread slice, buttered side out.",
      "Toast in pan until golden brown on both sides.",
      "Repeat for second sandwich.",
      "Cut diagonally and serve hot."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 10,
    servings: 2,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  },
  {
    title: "Qeema Paratha",
    tagline: "Minced meat stuffed paratha",
    image: "https://images.unsplash.com/photo-1516714435131-44d6b64dc6f4?w=500&h=300&fit=crop",
    category: "Quick",
    subCategory:"Quick & Easy",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 ready-made parathas",
      "1 cup cooked minced meat (qeema)",
      "1 small onion, finely chopped",
      "1 green chili, chopped",
      "1 tablespoon oil",
      "¼ teaspoon garam masala",
      "Salt to taste",
      "Fresh coriander for garnish"
    ],
    stepsRaw: [
      "Heat oil in pan, add chopped onion.",
      "Cook until onion is golden brown.",
      "Add cooked qeema and green chili.",
      "Add garam masala and salt, mix well.",
      "Cook for 2-3 minutes, then remove from heat.",
      "Add fresh coriander, mix.",
      "Take paratha, place qeema mixture in center.",
      "Fold paratha over filling or make roll.",
      "Heat in pan until crispy on both sides.",
      "Serve hot with yogurt or raita."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 10,
    servings: 2,
    isActive: true,
    isHalal: true,
    budget: "economy",
    mealTime: ["anytime"],
    ageGroup: ["adults", "kids"],
    patientFriendly: ["general"],
  }
];

async function migrate() {
  try {
    console.log('🔌 Connecting to MongoDB...');
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
if (!mongoURI) throw new Error('MongoDB URI not found');
await mongoose.connect(mongoURI, { serverSelectionTimeoutMS: 10000, family: 4 });
    console.log('✅ Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`✅ Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`⚠️ Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\n🎉 Migration Complete!');
    console.log(`📊 Added: ${added}, Skipped: ${skipped}`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

migrate();