// 10-salads.js - COMPLETE (40 recipes)
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });
const recipesToMigrate = [
  {
    title: "Kachumber Salad",
    tagline: "Fresh chopped cucumber and tomato salad with Indian spices",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cucumbers, finely chopped",
      "2 tomatoes, finely chopped",
      "1 onion, finely chopped",
      "1 green chilli, finely chopped",
      "1/4 cup fresh coriander leaves, chopped",
      "1/2 teaspoon roasted cumin powder",
      "1/2 teaspoon chaat masala",
      "1/4 teaspoon black salt",
      "Salt to taste",
      "1 tablespoon lemon juice",
      "1 tablespoon olive oil"
    ],
    stepsRaw: [
      "Wash and finely chop all vegetables.",
      "In a large mixing bowl, combine cucumbers, tomatoes, and onions.",
      "Add finely chopped green chili for extra spice.",
      "Add chopped coriander leaves for freshness.",
      "Sprinkle roasted cumin powder, chaat masala, and black salt.",
      "Add regular salt according to your taste.",
      "Drizzle lemon juice and olive oil over the salad.",
      "Gently mix all ingredients until well combined.",
      "Let the salad rest for 10 minutes to allow flavors to blend.",
      "Serve fresh as a side dish with your meals."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Onion Raita",
    tagline: "Cool yogurt dip with crunchy onions and spices",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups plain yogurt",
      "1 large onion, finely chopped",
      "1 green chilli, finely chopped",
      "1/4 cup fresh coriander leaves, chopped",
      "1/2 teaspoon roasted cumin powder",
      "1/4 teaspoon black salt",
      "Salt to taste",
      "1/2 teaspoon sugar",
      "1 tablespoon fresh mint leaves, chopped",
      "1/4 teaspoon black pepper powder"
    ],
    stepsRaw: [
      "Take yogurt in a mixing bowl and whisk until smooth.",
      "Add finely chopped onions to the yogurt.",
      "Add chopped green chili and coriander leaves.",
      "Mix in roasted cumin powder, black salt, and regular salt.",
      "Add sugar to balance the acidity of yogurt.",
      "Add mint leaves for extra freshness.",
      "Sprinkle black pepper powder.",
      "Mix all ingredients thoroughly.",
      "Cover and refrigerate for at least 30 minutes.",
      "Garnish with more coriander leaves before serving.",
      "Serve chilled with biryani or rice dishes."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 40,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Boondi Raita",
    tagline: "Yogurt with crispy chickpea flour pearls",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups plain yogurt",
      "1/2 cup boondi",
      "1/4 teaspoon roasted cumin powder",
      "1/4 teaspoon red chili powder",
      "1/4 teaspoon chaat masala",
      "Salt to taste",
      "1/2 teaspoon sugar",
      "2 tablespoons fresh coriander leaves, chopped",
      "1/4 teaspoon black salt",
      "1 tablespoon water if yogurt is thick"
    ],
    stepsRaw: [
      "Whisk yogurt in a bowl until smooth and creamy.",
      "If yogurt is too thick, add 1 tablespoon water.",
      "Add salt, sugar, and black salt to yogurt.",
      "Mix in roasted cumin powder and red chili powder.",
      "Combine all spices well into the yogurt.",
      "Add boondi to the yogurt mixture.",
      "Let it soak for 10 minutes until boondi softens slightly.",
      "Add chaat masala and mix gently.",
      "Garnish with chopped coriander leaves.",
      "Refrigerate for 15-20 minutes before serving.",
      "Serve chilled as a refreshing side dish."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 35,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Cucumber Raita",
    tagline: "Cool yogurt with fresh grated cucumber",
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups plain yogurt",
      "1 large cucumber, grated or finely chopped",
      "1/2 teaspoon roasted cumin powder",
      "1/4 teaspoon black pepper powder",
      "Salt to taste",
      "1 green chili, finely chopped",
      "2 tablespoons fresh mint leaves, chopped",
      "1 tablespoon fresh coriander leaves, chopped",
      "1/4 teaspoon sugar",
      "1 tablespoon roasted peanuts, crushed"
    ],
    stepsRaw: [
      "Peel and grate or finely chop cucumber.",
      "Squeeze out excess water from cucumber to prevent watery raita.",
      "Whisk yogurt in a bowl until smooth and creamy.",
      "Add squeezed cucumber to yogurt.",
      "Mix in roasted cumin powder and black pepper.",
      "Add salt and sugar for balanced flavor.",
      "Add chopped green chili for mild spice.",
      "Add chopped mint and coriander leaves.",
      "Mix all ingredients thoroughly.",
      "Garnish with crushed peanuts for crunch.",
      "Refrigerate for at least 30 minutes.",
      "Serve chilled as a cooling side dish."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 40,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Mint Raita",
    tagline: "Refreshing yogurt dip with fresh mint",
    image: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups plain yogurt",
      "1 cup fresh mint leaves",
      "1/4 cup fresh coriander leaves",
      "1 green chili",
      "1/2 teaspoon cumin seeds",
      "1 tablespoon lemon juice",
      "Salt to taste",
      "1/4 teaspoon black salt",
      "1/2 teaspoon sugar",
      "1 tablespoon water"
    ],
    stepsRaw: [
      "Wash mint and coriander leaves thoroughly.",
      "In a blender, combine mint, coriander, green chili, and water.",
      "Blend to make a smooth green paste.",
      "Whisk yogurt in a bowl until smooth.",
      "Add the mint-coriander paste to yogurt.",
      "Mix in lemon juice, salt, and black salt.",
      "Add sugar to balance the flavors.",
      "Dry roast cumin seeds until fragrant, then crush them.",
      "Add crushed cumin to the raita.",
      "Mix all ingredients well.",
      "Refrigerate for at least 1 hour for flavors to develop.",
      "Garnish with mint leaves before serving.",
      "Serve chilled with spicy dishes."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 70,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Potato Salad",
    tagline: "Creamy potato salad with herbs and mustard",
    image: "https://images.unsplash.com/photo-1585238342024-78d387f4a707",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 medium potatoes, boiled and cubed",
      "1/2 cup mayonnaise",
      "1/4 cup sour cream or thick yogurt",
      "1 tablespoon Dijon mustard",
      "1/2 cup celery, finely chopped",
      "1/4 cup red onion, finely chopped",
      "2 tablespoons fresh dill, chopped",
      "Salt to taste",
      "1/4 teaspoon black pepper",
      "2 tablespoons pickle juice or lemon juice",
      "2 hard-boiled eggs, chopped",
      "2 tablespoons fresh chives, chopped"
    ],
    stepsRaw: [
      "Boil potatoes until tender but firm, then cube them.",
      "In a large bowl, mix mayonnaise, sour cream, and Dijon mustard.",
      "Add pickle juice or lemon juice to the dressing.",
      "Season with salt and black pepper.",
      "Add chopped celery and red onion.",
      "Mix in chopped dill and chives.",
      "Gently fold in the potato cubes.",
      "Add chopped hard-boiled eggs.",
      "Mix carefully to coat all potatoes with dressing.",
      "Cover and refrigerate for at least 2 hours.",
      "Before serving, check seasoning and adjust if needed.",
      "Garnish with more fresh herbs.",
      "Serve chilled."
    ],
    isVegetarian: true,
    difficulty: "Medium",
    cookingTime: 150,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Mixed Vegetable Salad",
    tagline: "Colorful medley of fresh garden vegetables",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup cucumber, diced",
      "1 cup tomatoes, diced",
      "1 cup bell peppers, mixed colors, diced",
      "1/2 cup carrots, grated or julienned",
      "1/2 cup cabbage, shredded",
      "1/4 cup red onion, thinly sliced",
      "1/4 cup sweet corn, boiled",
      "2 tablespoons olive oil",
      "1 tablespoon lemon juice",
      "1 teaspoon honey or sugar",
      "Salt to taste",
      "1/4 teaspoon black pepper",
      "1/4 teaspoon dried oregano",
      "2 tablespoons fresh parsley, chopped"
    ],
    stepsRaw: [
      "Wash and prepare all vegetables as directed.",
      "In a large bowl, combine all vegetables.",
      "In a small bowl, prepare dressing: whisk olive oil, lemon juice, and honey.",
      "Add salt, black pepper, and oregano to dressing.",
      "Pour dressing over vegetables.",
      "Toss gently to coat all vegetables evenly.",
      "Add chopped parsley and mix.",
      "Let salad sit for 10-15 minutes for flavors to develop.",
      "Taste and adjust seasoning if needed.",
      "Serve fresh as a healthy side dish.",
      "Can be stored in refrigerator for up to 2 hours."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 20,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Fruit Chaat",
    tagline: "Spiced mixed fruit salad with chaat masala",
    image: "https://images.unsplash.com/photo-1519996529931-28324d5a630e",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 apple, diced",
      "1 banana, sliced",
      "1 orange, peeled and segmented",
      "1 cup pineapple chunks",
      "1 cup pomegranate seeds",
      "1 cup grapes, halved",
      "1/2 cup papaya, diced",
      "1/2 cup mango, diced (if in season)",
      "1 teaspoon chaat masala",
      "1/2 teaspoon black salt",
      "1/2 teaspoon roasted cumin powder",
      "1 tablespoon lemon juice",
      "2 tablespoons fresh mint leaves, chopped",
      "2 tablespoons fresh coriander leaves, chopped"
    ],
    stepsRaw: [
      "Wash and prepare all fruits as directed.",
      "In a large bowl, combine all fruits gently.",
      "Sprinkle chaat masala over fruits.",
      "Add black salt and roasted cumin powder.",
      "Drizzle lemon juice over the fruits.",
      "Gently toss to coat all fruits with spices.",
      "Add chopped mint and coriander leaves.",
      "Mix gently to avoid crushing delicate fruits.",
      "Let it sit for 5 minutes for flavors to blend.",
      "Serve immediately or chill for 15 minutes.",
      "Garnish with more mint leaves before serving.",
      "Best consumed fresh."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Chana Chaat",
    tagline: "Spicy chickpea salad with tangy chutneys",
    image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups boiled chickpeas",
      "1 medium potato, boiled and diced",
      "1 medium onion, finely chopped",
      "1 medium tomato, finely chopped",
      "1 green chili, finely chopped",
      "1/4 cup fresh coriander leaves, chopped",
      "2 tablespoons tamarind chutney",
      "2 tablespoons mint-coriander chutney",
      "1 teaspoon chaat masala",
      "1/2 teaspoon roasted cumin powder",
      "1/2 teaspoon red chili powder",
      "Salt to taste",
      "1 tablespoon lemon juice",
      "Sev for garnish",
      "Pomegranate seeds for garnish"
    ],
    stepsRaw: [
      "Boil chickpeas until tender, drain and cool.",
      "Boil potato, peel and dice it.",
      "In a large bowl, mix chickpeas and potatoes.",
      "Add chopped onion, tomato, and green chili.",
      "Add both tamarind and mint-coriander chutneys.",
      "Sprinkle chaat masala, cumin powder, and red chili powder.",
      "Add salt and lemon juice.",
      "Mix all ingredients gently but thoroughly.",
      "Garnish with fresh coriander leaves.",
      "Top with sev just before serving.",
      "Add pomegranate seeds for sweetness.",
      "Serve immediately for best taste."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 25,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Aloo Chaat",
    tagline: "Crispy spiced potatoes with chutneys",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "3 medium potatoes, boiled and cubed",
      "1 medium onion, finely chopped",
      "1 green chili, finely chopped",
      "2 tablespoons tamarind chutney",
      "2 tablespoons mint-coriander chutney",
      "1/4 cup fresh coriander leaves, chopped",
      "1 teaspoon chaat masala",
      "1/2 teaspoon roasted cumin powder",
      "1/2 teaspoon red chili powder",
      "Salt to taste",
      "1 tablespoon lemon juice",
      "Sev for garnish",
      "1 tablespoon pomegranate seeds",
      "1 tablespoon nylon sev"
    ],
    stepsRaw: [
      "Boil potatoes until tender but firm, cube them.",
      "Heat 1 tablespoon oil in a pan, shallow fry potatoes until golden.",
      "In a bowl, combine fried potatoes with onions and green chili.",
      "Add tamarind chutney and mint-coriander chutney.",
      "Sprinkle chaat masala, cumin powder, and red chili powder.",
      "Add salt and lemon juice.",
      "Mix gently to coat potatoes with spices.",
      "Garnish with fresh coriander leaves.",
      "Top with sev and pomegranate seeds.",
      "Serve immediately while potatoes are still warm.",
      "Can be served as snack or appetizer."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 25,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Papdi Chaat",
    tagline: "Crispy crackers topped with spiced chickpeas and yogurt",
    image: "https://images.unsplash.com/photo-1632922266946-6ba7c5d2bfd7",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "20-25 papdis",
      "1 cup boiled chickpeas",
      "1 cup boiled potatoes, diced",
      "1/2 cup plain yogurt, whisked",
      "2 tablespoons tamarind chutney",
      "2 tablespoons mint-coriander chutney",
      "1 teaspoon chaat masala",
      "1/2 teaspoon roasted cumin powder",
      "1/2 teaspoon red chili powder",
      "Salt to taste",
      "1/4 cup nylon sev",
      "2 tablespoons pomegranate seeds",
      "2 tablespoons fresh coriander leaves, chopped",
      "1 tablespoon roasted cumin seeds, crushed"
    ],
    stepsRaw: [
      "Arrange papdis on a serving plate.",
      "Spread boiled chickpeas over papdis.",
      "Add boiled potato cubes over chickpeas.",
      "Drizzle whisked yogurt over everything.",
      "Add tamarind chutney and mint-coriander chutney.",
      "Sprinkle chaat masala, cumin powder, and red chili powder.",
      "Add salt to taste.",
      "Garnish generously with nylon sev.",
      "Sprinkle pomegranate seeds over sev.",
      "Add chopped coriander leaves.",
      "Sprinkle crushed cumin seeds.",
      "Serve immediately before papdis get soggy.",
      "Best enjoyed fresh."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Dahi Bhalla",
    tagline: "Soft lentil dumplings soaked in creamy yogurt",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup urad dal, soaked 4-6 hours",
      "2 cups plain yogurt, whisked",
      "1/4 cup tamarind chutney",
      "2 tablespoons mint-coriander chutney",
      "1 teaspoon chaat masala",
      "1/2 teaspoon roasted cumin powder",
      "1/2 teaspoon red chili powder",
      "Salt to taste",
      "1/4 teaspoon baking soda",
      "Oil for frying",
      "Water for soaking",
      "2 tablespoons pomegranate seeds",
      "2 tablespoons nylon sev",
      "2 tablespoons fresh coriander leaves, chopped"
    ],
    stepsRaw: [
      "Grind soaked urad dal to smooth batter, add salt and baking soda.",
      "Heat oil, drop spoonfuls of batter, fry until golden brown (bhallas).",
      "Soak fried bhallas in warm water for 30 minutes.",
      "Gently squeeze out water from soaked bhallas.",
      "Arrange bhallas on serving plate.",
      "Pour whisked yogurt over bhallas.",
      "Drizzle tamarind and mint-coriander chutneys.",
      "Sprinkle chaat masala, cumin powder, and red chili powder.",
      "Garnish with pomegranate seeds and nylon sev.",
      "Add chopped coriander leaves.",
      "Refrigerate for 30 minutes before serving.",
      "Serve chilled as appetizer or snack."
    ],
    isVegetarian: true,
    difficulty: "Hard",
    cookingTime: 90,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Bhel Puri",
    tagline: "Crunchy puffed rice snack with tangy chutneys",
    image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "2 cups puffed rice",
      "1/2 cup sev",
      "1/2 cup boiled potatoes, diced",
      "1/2 cup boiled chickpeas",
      "1/4 cup raw onions, finely chopped",
      "1/4 cup tomatoes, finely chopped",
      "2 tablespoons tamarind chutney",
      "2 tablespoons mint-coriander chutney",
      "1 tablespoon lemon juice",
      "1 teaspoon chaat masala",
      "1/2 teaspoon roasted cumin powder",
      "1/4 teaspoon black salt",
      "Salt to taste",
      "2 tablespoons fresh coriander leaves, chopped",
      "1 green chili, finely chopped"
    ],
    stepsRaw: [
      "Dry roast puffed rice in a pan for 2-3 minutes, let cool.",
      "In a large bowl, combine puffed rice and sev.",
      "Add boiled potatoes and chickpeas.",
      "Add chopped onions and tomatoes.",
      "Add green chili for extra spice.",
      "Add tamarind and mint-coriander chutneys.",
      "Mix in lemon juice, chaat masala, cumin powder, and black salt.",
      "Add regular salt to taste.",
      "Mix all ingredients gently but quickly.",
      "Add chopped coriander leaves.",
      "Serve immediately in bowls.",
      "Can be garnished with extra sev on top.",
      "Best enjoyed fresh and crispy."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Sev Puri",
    tagline: "Crispy puris topped with potatoes and crunchy sev",
    image: "https://images.unsplash.com/photo-1626082895612-9e6d8e7db8d5",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "20-25 puris",
      "2 medium potatoes, boiled and mashed",
      "1/2 cup boiled chickpeas, mashed slightly",
      "1/4 cup onions, finely chopped",
      "1/4 cup tomatoes, finely chopped",
      "2 tablespoons tamarind chutney",
      "2 tablespoons mint-coriander chutney",
      "1/4 cup nylon sev",
      "1 teaspoon chaat masala",
      "1/2 teaspoon roasted cumin powder",
      "1/2 teaspoon red chili powder",
      "Salt to taste",
      "2 tablespoons fresh coriander leaves, chopped",
      "1 tablespoon pomegranate seeds"
    ],
    stepsRaw: [
      "Arrange puris on a serving plate.",
      "Spread mashed potatoes on each puri.",
      "Add mashed chickpeas over potatoes.",
      "Sprinkle chopped onions and tomatoes.",
      "Drizzle tamarind and mint-coriander chutneys.",
      "Sprinkle chaat masala, cumin powder, and red chili powder.",
      "Add salt to taste.",
      "Generously top with nylon sev.",
      "Garnish with chopped coriander leaves.",
      "Add pomegranate seeds for sweetness.",
      "Serve immediately before puris get soggy.",
      "Best enjoyed as fresh snack."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Pakora Salad",
    tagline: "Crispy vegetable fritters in spiced yogurt",
    image: "https://images.unsplash.com/photo-1631747558697-4d3c5e1b5c1b",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Pakistani",
    ingredientsRaw: [
      "1 cup besan (gram flour)",
      "1 cup mixed vegetables (onion, spinach, potato)",
      "1 green chili, chopped",
      "1/2 teaspoon carom seeds",
      "1/2 teaspoon red chili powder",
      "Salt to taste",
      "Water as needed",
      "Oil for frying",
      "1 cup yogurt, whisked",
      "1/2 teaspoon roasted cumin powder",
      "1/4 teaspoon red chili powder",
      "2 tablespoons fresh coriander leaves, chopped",
      "1 tablespoon mint leaves, chopped",
      "1 tablespoon tamarind chutney"
    ],
    stepsRaw: [
      "Mix besan with spices and water to make thick batter.",
      "Add chopped vegetables to batter, mix well.",
      "Heat oil, drop spoonfuls of batter, fry until golden brown.",
      "Drain pakoras on paper towel, let cool slightly.",
      "Whisk yogurt with spices and herbs.",
      "Spread yogurt mixture on serving plate.",
      "Arrange pakoras over yogurt.",
      "Drizzle tamarind chutney over pakoras.",
      "Sprinkle more cumin powder and red chili powder.",
      "Garnish with fresh coriander leaves.",
      "Serve immediately while pakoras are still crisp."
    ],
    isVegetarian: true,
    difficulty: "Medium",
    cookingTime: 30,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Greek Salad",
    tagline: "Classic Mediterranean salad with feta and olives",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 large tomatoes, cut into wedges",
      "1 cucumber, sliced",
      "1 green bell pepper, sliced",
      "1 red onion, thinly sliced",
      "1 cup Kalamata olives",
      "200g feta cheese, cubed",
      "3 tablespoons extra virgin olive oil",
      "1 tablespoon red wine vinegar",
      "1 teaspoon dried oregano",
      "Salt to taste",
      "Freshly ground black pepper",
      "Fresh oregano leaves for garnish"
    ],
    stepsRaw: [
      "Wash and prepare all vegetables.",
      "In a large bowl, combine tomatoes, cucumber, bell pepper, and onion.",
      "Add Kalamata olives to the vegetables.",
      "Add cubed feta cheese.",
      "In a small bowl, whisk together olive oil and red wine vinegar.",
      "Add dried oregano, salt, and black pepper to dressing.",
      "Pour dressing over salad ingredients.",
      "Gently toss to combine all ingredients.",
      "Let salad sit for 15 minutes for flavors to blend.",
      "Garnish with fresh oregano leaves before serving.",
      "Serve at room temperature for best flavor.",
      "Can be refrigerated for up to 2 hours."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 20,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Caesar Salad",
    tagline: "Classic romaine salad with creamy Caesar dressing",
    image: "https://images.unsplash.com/photo-1564927279-ef7a135d2d52",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Italian",
    ingredientsRaw: [
      "1 large head romaine lettuce, washed and torn",
      "1/2 cup Parmesan cheese, shaved",
      "1 cup croutons",
      "1/2 cup mayonnaise",
      "2 tablespoons lemon juice",
      "2 cloves garlic, minced",
      "1 teaspoon Dijon mustard",
      "1 teaspoon Worcestershire sauce",
      "1/4 cup grated Parmesan cheese",
      "Salt to taste",
      "Freshly ground black pepper",
      "2 tablespoons olive oil"
    ],
    stepsRaw: [
      "In a bowl, whisk mayonnaise, lemon juice, and garlic.",
      "Add Dijon mustard and Worcestershire sauce.",
      "Mix in grated Parmesan, salt, and pepper.",
      "Slowly whisk in olive oil until emulsified.",
      "In a large bowl, combine romaine lettuce.",
      "Add croutons and Parmesan shavings.",
      "Pour dressing over salad just before serving.",
      "Toss gently to coat lettuce with dressing.",
      "Serve immediately on chilled plates.",
      "Garnish with extra Parmesan cheese.",
      "Best consumed fresh."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Waldorf Salad",
    tagline: "Classic apple, celery and walnut salad",
    image: "https://images.unsplash.com/photo-1574926054530-540288c8e678",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "American",
    ingredientsRaw: [
      "2 large apples, diced",
      "1 cup celery, thinly sliced",
      "1/2 cup walnuts, toasted and chopped",
      "1/2 cup seedless grapes, halved",
      "1/2 cup mayonnaise",
      "1/4 cup Greek yogurt or sour cream",
      "1 tablespoon lemon juice",
      "1 teaspoon honey or sugar",
      "Salt to taste",
      "Freshly ground black pepper",
      "Lettuce leaves for serving",
      "Optional: 1/2 cup raisins or dried cranberries"
    ],
    stepsRaw: [
      "Core and dice apples, toss with lemon juice to prevent browning.",
      "Thinly slice celery stalks.",
      "Toast walnuts in dry pan until fragrant, then chop.",
      "Halve seedless grapes.",
      "In a large bowl, combine apples, celery, walnuts, and grapes.",
      "Add raisins or cranberries if using.",
      "In a small bowl, whisk mayonnaise and Greek yogurt.",
      "Add honey, salt, and pepper to dressing.",
      "Pour dressing over apple mixture.",
      "Gently fold to combine all ingredients.",
      "Chill in refrigerator for at least 30 minutes.",
      "Serve on bed of lettuce leaves.",
      "Garnish with extra walnuts before serving."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 45,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Caprese Salad",
    tagline: "Simple Italian salad with tomato, mozzarella and basil",
    image: "https://images.unsplash.com/photo-1563379091339-03246963d9d6",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Italian",
    ingredientsRaw: [
      "3-4 large ripe tomatoes, sliced",
      "250g fresh mozzarella cheese, sliced",
      "1 bunch fresh basil leaves",
      "3 tablespoons extra virgin olive oil",
      "1 tablespoon balsamic vinegar",
      "Salt to taste",
      "Freshly ground black pepper",
      "Optional: balsamic glaze for drizzling"
    ],
    stepsRaw: [
      "Slice tomatoes and mozzarella to similar thickness.",
      "Arrange tomato and mozzarella slices alternately on plate.",
      "Tuck fresh basil leaves between slices.",
      "In a small bowl, whisk olive oil and balsamic vinegar.",
      "Add salt and pepper to dressing.",
      "Drizzle dressing over arranged salad.",
      "Season with more salt and pepper to taste.",
      "Let salad sit for 10 minutes for flavors to develop.",
      "Drizzle with balsamic glaze if using.",
      "Garnish with whole basil leaves.",
      "Serve at room temperature for best flavor.",
      "Can be served as appetizer or side dish."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Cobb Salad",
    tagline: "Hearty chopped salad with eggs, chicken and avocado",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "American",
    ingredientsRaw: [
      "1 head romaine lettuce, chopped",
      "2 hard-boiled eggs, chopped",
      "2 cooked chicken breasts, diced",
      "6 strips bacon, cooked and crumbled",
      "1 avocado, diced",
      "2 tomatoes, diced",
      "1/2 cup blue cheese, crumbled",
      "1/4 cup red onion, thinly sliced",
      "1/2 cup olive oil",
      "1/4 cup red wine vinegar",
      "1 tablespoon Dijon mustard",
      "1 clove garlic, minced",
      "1 teaspoon honey",
      "Salt and pepper to taste"
    ],
    stepsRaw: [
      "Prepare all ingredients as directed.",
      "Arrange chopped lettuce on large platter.",
      "Arrange other ingredients in rows over lettuce.",
      "For dressing: whisk olive oil, vinegar, and Dijon mustard.",
      "Add garlic, honey, salt, and pepper to dressing.",
      "Drizzle dressing over salad just before serving.",
      "Alternatively, serve dressing on side.",
      "Toss salad at table or serve as arranged.",
      "Serve immediately for best texture."
    ],
    isVegetarian: false,
    difficulty: "Medium",
    cookingTime: 25,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Nicoise Salad",
    tagline: "French composed salad with tuna and vegetables",
    image: "https://images.unsplash.com/photo-1579586337278-3f4e7d9f5a1c",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "French",
    ingredientsRaw: [
      "200g fresh tuna steak or 2 cans tuna in olive oil",
      "4 small potatoes, boiled and quartered",
      "200g green beans, trimmed",
      "4 hard-boiled eggs, quartered",
      "2 tomatoes, cut into wedges",
      "1/2 cup black olives",
      "1/4 cup red onion, thinly sliced",
      "1/4 cup olive oil",
      "2 tablespoons lemon juice",
      "1 tablespoon Dijon mustard",
      "1 clove garlic, minced",
      "1 teaspoon dried oregano",
      "Salt and pepper to taste"
    ],
    stepsRaw: [
      "Grill or sear tuna steak until cooked to preference, slice.",
      "Boil potatoes until tender, quarter when cooled.",
      "Blanch green beans in boiling water for 3 minutes, then ice bath.",
      "Arrange all ingredients attractively on platter.",
      "In a small bowl, whisk olive oil, lemon juice, and mustard.",
      "Add garlic, oregano, salt, and pepper to dressing.",
      "Drizzle dressing over salad just before serving.",
      "Serve at room temperature."
    ],
    isVegetarian: false,
    difficulty: "Medium",
    cookingTime: 30,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Coleslaw",
    tagline: "Creamy cabbage and carrot slaw",
    image: "https://images.unsplash.com/photo-1574926054530-540288c8e678",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "American",
    ingredientsRaw: [
      "4 cups cabbage, finely shredded",
      "2 carrots, grated",
      "1/2 cup mayonnaise",
      "2 tablespoons sour cream or yogurt",
      "1 tablespoon apple cider vinegar",
      "1 tablespoon sugar",
      "1 teaspoon Dijon mustard",
      "1/2 teaspoon celery seeds",
      "Salt to taste",
      "Freshly ground black pepper",
      "2 tablespoons fresh parsley, chopped",
      "1/4 cup red onion, finely chopped"
    ],
    stepsRaw: [
      "Finely shred cabbage using a sharp knife or mandoline.",
      "Grate carrots using large holes of grater.",
      "In a large bowl, combine cabbage and carrots.",
      "In a separate bowl, whisk mayonnaise and sour cream.",
      "Add apple cider vinegar, sugar, and Dijon mustard.",
      "Mix in celery seeds if using, salt, and pepper.",
      "Pour dressing over cabbage mixture.",
      "Add chopped parsley and red onion if using.",
      "Toss thoroughly to coat all vegetables.",
      "Cover and refrigerate for at least 2 hours.",
      "Stir before serving to redistribute dressing.",
      "Serve chilled."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 135,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Garden Salad",
    tagline: "Fresh mixed greens with simple vinaigrette",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 cups mixed lettuce greens",
      "1 cucumber, sliced",
      "2 tomatoes, cut into wedges",
      "1 bell pepper, any color, sliced",
      "1/2 cup radishes, sliced",
      "1/4 cup red onion, thinly sliced",
      "1 carrot, shredded",
      "3 tablespoons olive oil",
      "1 tablespoon red wine vinegar",
      "1 teaspoon Dijon mustard",
      "1/2 teaspoon honey",
      "1 clove garlic, minced",
      "Salt and pepper to taste",
      "1 teaspoon dried oregano"
    ],
    stepsRaw: [
      "Wash and dry lettuce greens thoroughly.",
      "Prepare all vegetables as directed.",
      "In a large salad bowl, combine all vegetables.",
      "In a small jar, combine all dressing ingredients.",
      "Shake dressing vigorously until well combined.",
      "Pour dressing over salad just before serving.",
      "Toss gently to coat all ingredients.",
      "Serve immediately for best texture.",
      "Can customize with other vegetables."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Russian Salad",
    tagline: "Creamy vegetable salad with mayonnaise",
    image: "https://images.unsplash.com/photo-1574926054530-540288c8e678",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 potatoes, boiled and diced",
      "2 carrots, boiled and diced",
      "1 cup green peas, boiled",
      "1 cup French beans, boiled and chopped",
      "1/2 cup sweet corn, boiled",
      "1 apple, peeled and diced",
      "1/2 cup mayonnaise",
      "1/4 cup sour cream or yogurt",
      "1 tablespoon Dijon mustard",
      "1 tablespoon lemon juice",
      "Salt to taste",
      "Freshly ground black pepper",
      "1/4 cup fresh dill, chopped"
    ],
    stepsRaw: [
      "Boil all vegetables separately until tender but firm.",
      "Allow all vegetables to cool completely.",
      "Dice potatoes, carrots, and other vegetables uniformly.",
      "In a large bowl, combine all vegetables and apple.",
      "In a separate bowl, whisk mayonnaise and sour cream.",
      "Add Dijon mustard, lemon juice, salt, and pepper.",
      "Pour dressing over vegetable mixture.",
      "Gently fold to combine all ingredients.",
      "Add chopped dill and mix.",
      "Cover and refrigerate for at least 4 hours.",
      "Stir before serving.",
      "Garnish with more dill before serving."
    ],
    isVegetarian: true,
    difficulty: "Medium",
    cookingTime: 270,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Pasta Salad",
    tagline: "Cold pasta with vegetables and Italian dressing",
    image: "https://images.unsplash.com/photo-1563379091339-03246963d9d6",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Italian",
    ingredientsRaw: [
      "2 cups pasta, cooked",
      "1 cup cherry tomatoes, halved",
      "1 cucumber, diced",
      "1 bell pepper, diced",
      "1/2 cup black olives, sliced",
      "1/4 cup red onion, finely chopped",
      "1/2 cup feta cheese, crumbled",
      "1/3 cup olive oil",
      "2 tablespoons red wine vinegar",
      "1 tablespoon lemon juice",
      "1 clove garlic, minced",
      "1 teaspoon dried oregano",
      "1 teaspoon dried basil",
      "Salt and pepper to taste",
      "Fresh basil leaves for garnish"
    ],
    stepsRaw: [
      "Cook pasta according to package directions, drain, rinse with cold water.",
      "Allow pasta to cool completely.",
      "Prepare all vegetables as directed.",
      "In a large bowl, combine cooled pasta and vegetables.",
      "Add sliced olives and crumbled feta cheese.",
      "In a small bowl, whisk all dressing ingredients together.",
      "Pour dressing over pasta mixture.",
      "Toss gently to combine all ingredients.",
      "Cover and refrigerate for at least 2 hours.",
      "Stir before serving to redistribute dressing.",
      "Garnish with fresh basil leaves.",
      "Serve chilled or at room temperature."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 135,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Continental Potato Salad",
    tagline: "Classic American-style potato salad",
    image: "https://images.unsplash.com/photo-1585238342024-78d387f4a707",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "American",
    ingredientsRaw: [
      "6 medium potatoes, boiled and cubed",
      "4 hard-boiled eggs, chopped",
      "1/2 cup celery, finely chopped",
      "1/4 cup red onion, finely chopped",
      "1/4 cup sweet pickle relish",
      "1 cup mayonnaise",
      "2 tablespoons yellow mustard",
      "1 tablespoon apple cider vinegar",
      "1 teaspoon sugar",
      "Salt to taste",
      "Freshly ground black pepper",
      "1/4 cup fresh parsley, chopped",
      "Paprika for garnish"
    ],
    stepsRaw: [
      "Boil potatoes until tender but firm, cube when cooled.",
      "Hard boil eggs, cool, peel and chop.",
      "In a large bowl, combine potatoes, eggs, celery, and onion.",
      "In a separate bowl, whisk mayonnaise and mustard.",
      "Add pickle relish, vinegar, sugar, salt, and pepper.",
      "Pour dressing over potato mixture.",
      "Gently fold to combine all ingredients.",
      "Add chopped parsley and mix.",
      "Cover and refrigerate for at least 4 hours.",
      "Before serving, taste and adjust seasoning.",
      "Sprinkle with paprika for garnish.",
      "Serve chilled."
    ],
    isVegetarian: true,
    difficulty: "Medium",
    cookingTime: 270,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Macaroni Salad",
    tagline: "Creamy macaroni salad with vegetables",
    image: "https://images.unsplash.com/photo-1574926054530-540288c8e678",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "American",
    ingredientsRaw: [
      "2 cups elbow macaroni, cooked",
      "1/2 cup mayonnaise",
      "1/4 cup sour cream or yogurt",
      "1 tablespoon Dijon mustard",
      "1 tablespoon apple cider vinegar",
      "1 teaspoon sugar",
      "1/2 cup celery, finely chopped",
      "1/4 cup red onion, finely chopped",
      "1/2 cup sweet corn, boiled",
      "1/4 cup black olives, sliced",
      "1/4 cup fresh parsley, chopped",
      "Salt to taste",
      "Freshly ground black pepper",
      "Paprika for garnish"
    ],
    stepsRaw: [
      "Cook macaroni according to package directions, drain, rinse with cold water.",
      "Allow macaroni to cool completely.",
      "In a large bowl, whisk mayonnaise and sour cream.",
      "Add Dijon mustard, vinegar, sugar, salt, and pepper.",
      "Add cooled macaroni to dressing mixture.",
      "Mix in celery, onion, sweet corn, and olives.",
      "Add chopped parsley and mix well.",
      "Cover and refrigerate for at least 2 hours.",
      "Stir before serving to redistribute dressing.",
      "Taste and adjust seasoning if needed.",
      "Sprinkle with paprika before serving.",
      "Serve chilled."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 135,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Fattoush Salad",
    tagline: "Lebanese bread salad with sumac dressing",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 cups romaine lettuce, chopped",
      "2 tomatoes, diced",
      "1 cucumber, diced",
      "1 bell pepper, diced",
      "4 radishes, thinly sliced",
      "4 green onions, chopped",
      "1/2 cup fresh mint leaves, chopped",
      "1/2 cup fresh parsley, chopped",
      "2 pita breads, toasted and broken into pieces",
      "1/4 cup olive oil",
      "2 tablespoons lemon juice",
      "1 tablespoon pomegranate molasses",
      "1 clove garlic, minced",
      "1 teaspoon sumac",
      "Salt to taste",
      "Freshly ground black pepper"
    ],
    stepsRaw: [
      "Toast pita bread until crisp, break into bite-sized pieces.",
      "Wash and prepare all vegetables.",
      "In a large bowl, combine lettuce, tomatoes, cucumber, and bell pepper.",
      "Add radishes, green onions, mint, and parsley.",
      "In a small bowl, whisk all dressing ingredients together.",
      "Pour dressing over salad just before serving.",
      "Add toasted pita pieces and toss gently.",
      "Serve immediately to prevent pita from getting soggy.",
      "Can prepare vegetables ahead, add dressing last.",
      "Sumac adds characteristic tangy flavor."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 20,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Tabbouleh",
    tagline: "Fresh parsley and bulgur salad with lemon",
    image: "https://images.unsplash.com/photo-1579586337278-3f9d8f5a1c1c",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup fine bulgur wheat",
      "2 cups boiling water",
      "4 cups fresh parsley, finely chopped",
      "1/2 cup fresh mint leaves, finely chopped",
      "4 tomatoes, finely diced",
      "1 cucumber, finely diced",
      "4 green onions, finely chopped",
      "1/4 cup lemon juice",
      "1/4 cup olive oil",
      "Salt to taste",
      "Freshly ground black pepper",
      "1 teaspoon ground cumin",
      "Lettuce leaves for serving"
    ],
    stepsRaw: [
      "Place bulgur in a bowl, pour boiling water over it.",
      "Cover and let soak for 30 minutes until tender.",
      "Drain any excess water, fluff with fork.",
      "Finely chop parsley and mint leaves.",
      "Dice tomatoes and cucumber very finely.",
      "Chop green onions finely.",
      "In a large bowl, combine soaked bulgur and chopped herbs.",
      "Add tomatoes, cucumber, and green onions.",
      "In a small bowl, whisk lemon juice and olive oil.",
      "Add salt, pepper, and cumin to dressing.",
      "Pour dressing over salad mixture.",
      "Toss gently to combine all ingredients.",
      "Serve on lettuce leaves or with pita bread."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 40,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Quinoa Salad",
    tagline: "Protein-packed quinoa with fresh vegetables",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "1 cup quinoa, rinsed",
      "2 cups water or vegetable broth",
      "1 cucumber, diced",
      "1 bell pepper, diced",
      "1 cup cherry tomatoes, halved",
      "1/2 cup red onion, finely chopped",
      "1/2 cup black olives, sliced",
      "1/2 cup feta cheese, crumbled",
      "1/4 cup fresh parsley, chopped",
      "1/4 cup olive oil",
      "2 tablespoons lemon juice",
      "1 tablespoon red wine vinegar",
      "1 clove garlic, minced",
      "1 teaspoon dried oregano",
      "Salt and pepper to taste"
    ],
    stepsRaw: [
      "Rinse quinoa thoroughly under cold water.",
      "Cook quinoa in water or broth according to package directions.",
      "Fluff cooked quinoa with fork, allow to cool.",
      "Prepare all vegetables as directed.",
      "In a large bowl, combine cooled quinoa and vegetables.",
      "Add olives, feta cheese, and parsley.",
      "In a small bowl, whisk all dressing ingredients together.",
      "Pour dressing over quinoa mixture.",
      "Toss gently to combine all ingredients.",
      "Cover and refrigerate for at least 1 hour.",
      "Stir before serving.",
      "Can be served cold or at room temperature."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 90,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Chicken Salad",
    tagline: "Creamy chicken salad with grapes and walnuts",
    image: "https://images.unsplash.com/photo-1563379091339-03246963d9d6",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "American",
    ingredientsRaw: [
      "3 cups cooked chicken, shredded or diced",
      "1 cup celery, finely chopped",
      "1/2 cup red onion, finely chopped",
      "1 cup red grapes, halved",
      "1/2 cup walnuts, toasted and chopped",
      "1 cup mayonnaise",
      "1/4 cup sour cream or yogurt",
      "1 tablespoon Dijon mustard",
      "1 tablespoon lemon juice",
      "1 teaspoon honey",
      "Salt to taste",
      "Freshly ground black pepper",
      "1/4 cup fresh dill, chopped",
      "Lettuce leaves for serving"
    ],
    stepsRaw: [
      "Cook chicken until done, cool, then shred or dice.",
      "Toast walnuts in dry pan until fragrant, then chop.",
      "Halve seedless grapes.",
      "In a large bowl, combine chicken, celery, onion, grapes, and walnuts.",
      "In a separate bowl, whisk mayonnaise and sour cream.",
      "Add Dijon mustard, lemon juice, honey, salt, and pepper.",
      "Pour dressing over chicken mixture.",
      "Add chopped dill and mix well.",
      "Cover and refrigerate for at least 2 hours.",
      "Serve on bed of lettuce leaves.",
      "Can be served in sandwiches or with crackers."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 135,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Tuna Salad",
    tagline: "Classic tuna salad with eggs and pickles",
    image: "https://images.unsplash.com/photo-1574926054530-540288c8e678",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "American",
    ingredientsRaw: [
      "2 cans tuna in water, drained",
      "1/2 cup celery, finely chopped",
      "1/4 cup red onion, finely chopped",
      "1/4 cup sweet pickle relish",
      "2 hard-boiled eggs, chopped",
      "1/2 cup mayonnaise",
      "1 tablespoon Dijon mustard",
      "1 tablespoon lemon juice",
      "Salt to taste",
      "Freshly ground black pepper",
      "1/4 cup fresh parsley, chopped",
      "Lettuce leaves or bread for serving"
    ],
    stepsRaw: [
      "Drain tuna thoroughly, flake with fork.",
      "Hard boil eggs, cool, peel and chop.",
      "In a large bowl, combine tuna, celery, onion, and relish.",
      "Add chopped hard-boiled eggs.",
      "In a small bowl, whisk mayonnaise and Dijon mustard.",
      "Add lemon juice, salt, and pepper to dressing.",
      "Pour dressing over tuna mixture.",
      "Add chopped parsley and mix well.",
      "Cover and refrigerate for at least 1 hour.",
      "Serve on lettuce leaves or in sandwiches.",
      "Can be used as dip with crackers."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 75,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Shrimp Salad",
    tagline: "Light and creamy shrimp salad with dill",
    image: "https://images.unsplash.com/photo-1563379091339-03246963d9d6",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "American",
    ingredientsRaw: [
      "1 pound cooked shrimp, peeled and deveined",
      "1 cup celery, finely chopped",
      "1/2 cup red onion, finely chopped",
      "1/2 cup red bell pepper, diced",
      "1/4 cup fresh dill, chopped",
      "1/2 cup mayonnaise",
      "1/4 cup sour cream or yogurt",
      "2 tablespoons lemon juice",
      "1 tablespoon Dijon mustard",
      "1 teaspoon Old Bay seasoning",
      "Salt to taste",
      "Freshly ground black pepper",
      "Lettuce leaves for serving"
    ],
    stepsRaw: [
      "If using raw shrimp, cook until pink and opaque, then cool.",
      "Chop shrimp into bite-sized pieces if large.",
      "In a large bowl, combine shrimp, celery, onion, and bell pepper.",
      "In a separate bowl, whisk mayonnaise and sour cream.",
      "Add lemon juice, Dijon mustard, and Old Bay seasoning.",
      "Season with salt and pepper to taste.",
      "Pour dressing over shrimp mixture.",
      "Add chopped dill and mix gently.",
      "Cover and refrigerate for at least 1 hour.",
      "Serve on bed of lettuce leaves.",
      "Can be served in avocado halves."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 75,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Egg Salad",
    tagline: "Classic creamy egg salad with fresh herbs",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "American",
    ingredientsRaw: [
      "8 hard-boiled eggs",
      "1/2 cup mayonnaise",
      "1 tablespoon Dijon mustard",
      "1 tablespoon lemon juice",
      "1/4 cup celery, finely chopped",
      "2 tablespoons red onion, finely chopped",
      "2 tablespoons sweet pickle relish",
      "1 tablespoon fresh dill, chopped",
      "1 tablespoon fresh chives, chopped",
      "Salt to taste",
      "Freshly ground black pepper",
      "Paprika for garnish",
      "Bread or lettuce leaves for serving"
    ],
    stepsRaw: [
      "Hard boil eggs, cool completely in ice water.",
      "Peel eggs and chop coarsely.",
      "In a large bowl, combine chopped eggs.",
      "Add celery, onion, and pickle relish.",
      "In a small bowl, whisk mayonnaise and Dijon mustard.",
      "Add lemon juice, salt, and pepper to dressing.",
      "Pour dressing over egg mixture.",
      "Add chopped dill and chives.",
      "Mix gently to combine all ingredients.",
      "Cover and refrigerate for at least 30 minutes.",
      "Serve on bread for sandwiches or with crackers.",
      "Sprinkle with paprika before serving."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 45,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Beetroot Salad",
    tagline: "Roasted beetroot with orange and goat cheese",
    image: "https://images.unsplash.com/photo-1574926054530-540288c8e678",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 medium beetroots, boiled or roasted",
      "2 oranges, peeled and segmented",
      "1/2 cup walnuts, toasted and chopped",
      "4 cups mixed salad greens",
      "1/4 cup red onion, thinly sliced",
      "1/2 cup goat cheese or feta cheese, crumbled",
      "1/4 cup olive oil",
      "2 tablespoons orange juice",
      "1 tablespoon balsamic vinegar",
      "1 teaspoon Dijon mustard",
      "1 teaspoon honey",
      "Salt to taste",
      "Freshly ground black pepper",
      "Fresh mint leaves for garnish"
    ],
    stepsRaw: [
      "Boil or roast beetroots until tender, peel and slice.",
      "Toast walnuts in dry pan until fragrant, then chop.",
      "Peel oranges and segment, removing membranes.",
      "Arrange salad greens on serving platter.",
      "Arrange beetroot slices and orange segments over greens.",
      "Sprinkle with toasted walnuts and sliced red onion.",
      "Crumble cheese over salad.",
      "In a small bowl, whisk all dressing ingredients together.",
      "Drizzle dressing over salad just before serving.",
      "Garnish with fresh mint leaves.",
      "Serve immediately."
    ],
    isVegetarian: true,
    difficulty: "Medium",
    cookingTime: 60,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Avocado Salad",
    tagline: "Fresh avocado with tomato and lime dressing",
    image: "https://images.unsplash.com/photo-1563379091339-03246963d9d6",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Mexican",
    ingredientsRaw: [
      "2 ripe avocados, diced",
      "2 tomatoes, diced",
      "1 cucumber, diced",
      "1/2 red onion, thinly sliced",
      "1 jalapeño pepper, seeded and finely chopped",
      "1/4 cup fresh coriander leaves, chopped",
      "2 tablespoons lime juice",
      "2 tablespoons olive oil",
      "Salt to taste",
      "Freshly ground black pepper",
      "1 teaspoon cumin powder",
      "Optional: 1 cup corn kernels, cooked",
      "Tortilla chips for serving"
    ],
    stepsRaw: [
      "Cut avocados in half, remove pit, dice flesh.",
      "Immediately toss avocado with lime juice to prevent browning.",
      "Dice tomatoes and cucumber.",
      "Thinly slice red onion.",
      "Seed and finely chop jalapeño pepper.",
      "In a large bowl, combine all prepared vegetables.",
      "Add chopped coriander leaves.",
      "In a small bowl, whisk olive oil, remaining lime juice, cumin, salt, and pepper.",
      "Pour dressing over salad mixture.",
      "Gently toss to combine all ingredients.",
      "Add corn kernels if using.",
      "Serve immediately with tortilla chips.",
      "Best consumed fresh as avocados brown quickly."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Spinach Salad",
    tagline: "Fresh spinach with strawberries and walnuts",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "6 cups fresh spinach leaves, washed and dried",
      "1 cup strawberries, sliced",
      "1/2 cup walnuts, toasted and chopped",
      "1/4 cup red onion, thinly sliced",
      "1/2 cup feta cheese or goat cheese, crumbled",
      "1/4 cup olive oil",
      "2 tablespoons balsamic vinegar",
      "1 tablespoon honey",
      "1 teaspoon Dijon mustard",
      "1 small shallot, minced",
      "Salt to taste",
      "Freshly ground black pepper"
    ],
    stepsRaw: [
      "Wash spinach thoroughly, dry completely.",
      "Remove stems if desired, tear into bite-sized pieces.",
      "Slice strawberries.",
      "Toast walnuts in dry pan until fragrant, then chop.",
      "Thinly slice red onion.",
      "In a large bowl, combine spinach, strawberries, walnuts, and onion.",
      "Crumble cheese over salad.",
      "In a small bowl, whisk all dressing ingredients together.",
      "Pour dressing over salad just before serving.",
      "Toss gently to coat all ingredients.",
      "Serve immediately.",
      "Dressing can be made ahead and stored."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Broccoli Salad",
    tagline: "Crunchy broccoli with bacon and cranberries",
    image: "https://images.unsplash.com/photo-1579586337278-3f9d8f5a1c1c",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "American",
    ingredientsRaw: [
      "4 cups broccoli florets, chopped into bite-sized pieces",
      "1/2 cup red onion, finely chopped",
      "1/2 cup dried cranberries or raisins",
      "1/2 cup sunflower seeds or pumpkin seeds",
      "1/2 cup bacon, cooked and crumbled",
      "1/2 cup cheddar cheese, shredded",
      "1 cup mayonnaise",
      "2 tablespoons apple cider vinegar",
      "2 tablespoons sugar",
      "Salt to taste",
      "Freshly ground black pepper"
    ],
    stepsRaw: [
      "Chop broccoli florets into small, bite-sized pieces.",
      "Finely chop red onion.",
      "Cook bacon until crisp, drain and crumble.",
      "In a large bowl, combine broccoli, onion, cranberries, and seeds.",
      "Add crumbled bacon and shredded cheese.",
      "In a separate bowl, whisk mayonnaise and vinegar.",
      "Add sugar, salt, and pepper to dressing.",
      "Pour dressing over broccoli mixture.",
      "Mix thoroughly to coat all ingredients.",
      "Cover and refrigerate for at least 2 hours.",
      "Stir before serving.",
      "Flavors improve with longer refrigeration."
    ],
    isVegetarian: false,
    difficulty: "Easy",
    cookingTime: 135,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Feta Cheese Salad",
    tagline: "Greek-style salad with feta and olives",
    image: "https://images.unsplash.com/photo-1564927279-ef7a135d2d52",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "4 cups mixed salad greens",
      "1 cup cherry tomatoes, halved",
      "1 cucumber, sliced",
      "1/2 red onion, thinly sliced",
      "1 bell pepper, sliced",
      "1 cup Kalamata olives",
      "200g feta cheese, cubed",
      "1/4 cup olive oil",
      "2 tablespoons red wine vinegar",
      "1 teaspoon dried oregano",
      "1 clove garlic, minced",
      "1 teaspoon Dijon mustard",
      "Salt to taste",
      "Freshly ground black pepper",
      "Fresh oregano leaves for garnish"
    ],
    stepsRaw: [
      "Wash and dry salad greens thoroughly.",
      "Prepare all vegetables as directed.",
      "Cube feta cheese.",
      "In a large salad bowl, combine greens and all vegetables.",
      "Add Kalamata olives and feta cheese cubes.",
      "In a small bowl, whisk olive oil and red wine vinegar.",
      "Add oregano, garlic, Dijon mustard, salt, and pepper.",
      "Whisk dressing until well combined.",
      "Pour dressing over salad just before serving.",
      "Toss gently to coat all ingredients.",
      "Garnish with fresh oregano leaves.",
      "Serve immediately."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 15,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  },
  {
    title: "Mediterranean Salad",
    tagline: "Healthy grain salad with Mediterranean flavors",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe",
    category: "Salads",
    subCategory: "Salad",
    cuisine: "Continental",
    ingredientsRaw: [
      "2 cups cooked quinoa or couscous",
      "1 cup cherry tomatoes, halved",
      "1 cucumber, diced",
      "1 bell pepper, diced",
      "1/2 cup Kalamata olives, sliced",
      "1/2 cup feta cheese, crumbled",
      "1/4 cup red onion, finely chopped",
      "1/4 cup fresh parsley, chopped",
      "1/4 cup fresh mint leaves, chopped",
      "1/4 cup olive oil",
      "2 tablespoons lemon juice",
      "1 clove garlic, minced",
      "1 teaspoon dried oregano",
      "Salt to taste",
      "Freshly ground black pepper"
    ],
    stepsRaw: [
      "Cook quinoa or couscous according to package directions, cool.",
      "Prepare all vegetables as directed.",
      "Chop fresh herbs finely.",
      "In a large bowl, combine cooled grain and vegetables.",
      "Add olives, feta cheese, and herbs.",
      "In a small bowl, whisk all dressing ingredients together.",
      "Pour dressing over salad mixture.",
      "Toss gently to combine all ingredients.",
      "Cover and refrigerate for at least 1 hour.",
      "Stir before serving.",
      "Can be served cold or at room temperature.",
      "Flavors improve with time."
    ],
    isVegetarian: true,
    difficulty: "Easy",
    cookingTime: 90,
    servings: 4,
    isActive: true,
    isHalal: true,
 budget: "economy",  // Salads are usually economy/standard
  mealTime: ["Lunch", "Dinner", "Anytime"],
  ageGroup: ["adults", "kids", "seniors"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"]
  }
];
async function migrate() {
  try {
    console.log('🔌 Connecting to MongoDB...');
    const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
    if (!mongoURI) throw new Error('MongoDB URI not found');
    await mongoose.connect(mongoURI, { serverSelectionTimeoutMS: 10000, family: 4 });
    console.log('✅ Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`✅ Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`⚠️ Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\n🎉 Migration Complete!');
    console.log(`📊 Added: ${added}, Skipped: ${skipped}`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

migrate();