// 19-soups.js - COMPLETE (38 recipes)
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
 {
  title: "Cream of Mushroom Soup",
  tagline: "Rich, creamy, and earthy mushroom soup",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKqiqU3xgsUs4bYX9IvYvXIEKw_-XIoyvFbQ&s",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g fresh mushrooms, sliced",
    "1 onion, chopped",
    "2 cloves garlic, minced",
    "2 cups vegetable broth",
    "1 cup heavy cream",
    "2 tbsp butter",
    "2 tbsp all-purpose flour",
    "1 tsp thyme",
    "Salt and pepper to taste"
  ],
  stepsRaw: [
    "Melt butter in a large pot over medium heat.",
    "Add onions and garlic, sauté until translucent.",
    "Add mushrooms and cook until they release their moisture and brown slightly.",
    "Sprinkle flour and stir for 2 minutes to cook out raw flour taste.",
    "Gradually add vegetable broth while stirring to prevent lumps.",
    "Bring to a simmer and cook for 15 minutes until slightly thickened.",
    "Stir in cream and thyme, season with salt and pepper.",
    "Simmer for 5 more minutes, adjust seasoning, and serve hot."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Rich, creamy mushroom soup with earthy flavors and a velvety texture – perfect for a cozy dinner.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "economy",
  costPerServing: 35,
  baseServings: 4,
  calories: 280,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["mushrooms", "onion", "garlic", "vegetable broth", "heavy cream", "butter", "flour", "thyme"],
  searchKeywords: ["cream of mushroom soup", "creamy mushroom soup", "rich soup", "vegetarian soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Creamy Noodles Soup",
  tagline: "Comforting noodle soup with creamy broth",
  image: "https://www.twopeasandtheirpod.com/wp-content/uploads/2019/10/Creamy-Chicken-Noodle-Soup-3.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "200g noodles",
    "4 cups chicken broth",
    "1 cup mixed vegetables (carrots, peas, corn)",
    "1 cup milk",
    "2 tbsp butter",
    "2 tbsp flour",
    "1 tsp black pepper",
    "Salt to taste"
  ],
  stepsRaw: [
    "Cook noodles according to package instructions, drain and set aside.",
    "In a pot, melt butter and stir in flour to make a roux, cook for 2 minutes.",
    "Slowly add chicken broth while whisking to prevent lumps.",
    "Add mixed vegetables and cook for 10 minutes until tender.",
    "Stir in milk and cooked noodles.",
    "Season with salt and pepper, simmer for 5 minutes.",
    "Serve hot garnished with fresh herbs."
  ],
  difficulty: "Easy",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Comforting creamy noodle soup with chicken broth, mixed vegetables, and a velvety milk-based broth.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "economy",
  costPerServing: 30,
  baseServings: 4,
  calories: 250,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["noodles", "chicken broth", "mixed vegetables", "milk", "butter", "flour", "black pepper"],
  searchKeywords: ["creamy noodle soup", "noodle soup", "comfort soup", "creamy chicken noodle"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Egg Drop Soup",
  tagline: "Silky Chinese-style egg soup",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT91WUf88VTnCSrt3kQ9ChnM7D053vayxpBEg&s",
  cuisine: "Chinese",
  ingredientsRaw: [
    "4 cups chicken broth",
    "2 eggs, lightly beaten",
    "2 tbsp cornstarch",
    "2 tbsp water",
    "1 tsp soy sauce",
    "1/2 tsp ginger, grated",
    "2 green onions, chopped",
    "1/4 tsp white pepper"
  ],
  stepsRaw: [
    "Bring chicken broth to a boil in a pot.",
    "Mix cornstarch with water to make a slurry.",
    "Add soy sauce, ginger, and white pepper to the broth.",
    "Slowly pour in cornstarch slurry while stirring continuously.",
    "Reduce heat to a simmer.",
    "Slowly drizzle beaten eggs into the soup while stirring gently in one direction.",
    "Cook for 1 minute until eggs set into ribbons.",
    "Garnish with green onions and serve immediately."
  ],
  difficulty: "Easy",
  cookingTime: 10,
  isActive: true,
  isHalal: true,
  description: "Silky, light Chinese-style egg drop soup with delicate egg ribbons and subtle ginger flavor – ready in minutes.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["eggs", "soy"],
  budget: "economy",
  costPerServing: 12,
  baseServings: 4,
  calories: 70,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken broth", "eggs", "cornstarch", "soy sauce", "ginger", "green onions", "white pepper"],
  searchKeywords: ["egg drop soup", "chinese egg soup", "silky soup", "quick soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Macroni Corn Soup",
  tagline: "Hearty soup with chicken, macaroni and corn",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpQ9CCB50MahAFRH-KMbVuObrgRPLUbwzHlw&s",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "200g chicken breast, diced",
    "1 cup macaroni",
    "1 cup sweet corn kernels",
    "1 carrot, diced",
    "4 cups chicken broth",
    "1 onion, chopped",
    "2 cloves garlic, minced",
    "2 tbsp soy sauce",
    "1 tsp black pepper",
    "2 tbsp oil"
  ],
  stepsRaw: [
    "Heat oil in a pot and sauté onions and garlic until fragrant.",
    "Add chicken and cook until no longer pink and lightly browned.",
    "Add carrots and corn, cook for 5 minutes stirring occasionally.",
    "Pour in chicken broth and bring to a boil.",
    "Add macaroni and cook until al dente (about 10-12 minutes).",
    "Season with soy sauce and black pepper.",
    "Simmer for 10 minutes until flavors combine.",
    "Serve hot with crusty bread."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Hearty, filling soup with tender chicken, sweet corn, macaroni, and a savory soy-seasoned broth.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["soy", "gluten"],
  budget: "economy",
  costPerServing: 35,
  baseServings: 4,
  calories: 320,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken breast", "macaroni", "sweet corn", "carrot", "chicken broth", "onion", "garlic", "soy sauce"],
  searchKeywords: ["chicken macaroni corn soup", "hearty chicken soup", "macaroni soup", "corn chicken soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Soup",
  tagline: "Classic comforting chicken soup",
  image: "https://afoodcentriclife.com/wp-content/uploads/2014/01/chicken-vegetable-soup-pot-square-crop-0526.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "1 whole chicken (or 500g chicken pieces)",
    "8 cups water",
    "2 carrots, sliced",
    "2 celery stalks, chopped",
    "1 onion, chopped",
    "3 cloves garlic",
    "1 bay leaf",
    "1 tsp thyme",
    "Salt and pepper to taste",
    "Fresh parsley for garnish"
  ],
  stepsRaw: [
    "Place chicken in a large pot with water.",
    "Bring to a boil, then reduce heat to simmer.",
    "Skim off any foam that rises to the surface.",
    "Add vegetables and herbs (carrots, celery, onion, garlic, bay leaf, thyme).",
    "Simmer for 45-60 minutes until chicken is tender.",
    "Remove chicken, shred the meat, and return to pot.",
    "Season with salt and pepper to taste.",
    "Simmer for another 10 minutes, garnish with parsley and serve hot."
  ],
  difficulty: "Medium",
  cookingTime: 75,
  isActive: true,
  isHalal: true,
  description: "Classic comforting chicken soup with tender shredded chicken, carrots, celery, and aromatic herbs – a timeless remedy.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 30,
  baseServings: 6,
  calories: 200,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["whole chicken", "carrots", "celery", "onion", "garlic", "bay leaf", "thyme", "parsley"],
  searchKeywords: ["chicken soup", "classic chicken soup", "comfort soup", "homemade chicken soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Vegetable Hot and Sour Soup",
  tagline: "Tangy and spicy Indo-Chinese soup",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqAVyVHIovVcsPXzZ8_kDA1VFX6ovci-VF5w&s",
  cuisine: "Chinese",
  ingredientsRaw: [
    "4 cups vegetable broth",
    "1 cup mixed vegetables (carrots, cabbage, bell peppers)",
    "100g tofu, cubed",
    "2 tbsp soy sauce",
    "1 tbsp vinegar",
    "1 tbsp chili sauce",
    "2 tbsp cornstarch",
    "1/4 cup water",
    "1 tsp ginger, grated",
    "1 tsp garlic, minced"
  ],
  stepsRaw: [
    "Bring vegetable broth to a boil in a pot.",
    "Add mixed vegetables and cook for 8-10 minutes until tender-crisp.",
    "Add tofu, ginger, and garlic.",
    "In a bowl, mix cornstarch with water to make slurry.",
    "Add soy sauce, vinegar, and chili sauce to the soup.",
    "Slowly add cornstarch slurry while stirring continuously.",
    "Simmer for 5 minutes until soup thickens.",
    "Adjust seasoning and serve hot."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Tangy, spicy Indo-Chinese vegetable hot and sour soup with tofu and crunchy veggies – a vegetarian delight.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["soy"],
  budget: "economy",
  costPerServing: 20,
  baseServings: 4,
  calories: 110,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["vegetable broth", "mixed vegetables", "tofu", "soy sauce", "vinegar", "chili sauce", "cornstarch", "ginger", "garlic"],
  searchKeywords: ["vegetable hot and sour soup", "indo chinese soup", "vegan hot sour soup", "spicy veg soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Broth",
  tagline: "Rich and nourishing chicken stock",
  image: "https://abraskitchen.com/wp-content/uploads/2021/11/Homemade-Nourishing-Chicken-Soup-from-Scratch.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "2kg chicken bones/carcass",
    "12 cups water",
    "2 onions, quartered",
    "3 carrots, chopped",
    "4 celery stalks",
    "4 cloves garlic, smashed",
    "2 bay leaves",
    "1 tsp peppercorns",
    "Salt to taste"
  ],
  stepsRaw: [
    "Place chicken bones in a large pot with water.",
    "Bring to a boil, skim off impurities that rise to surface.",
    "Add all vegetables and aromatics.",
    "Reduce heat to low, partially cover, and simmer for 3 hours.",
    "Strain through fine mesh sieve or cheesecloth.",
    "Let cool, then refrigerate to remove fat layer from top.",
    "Use as base for soups or store frozen for up to 6 months."
  ],
  difficulty: "Hard",
  cookingTime: 180,
  isActive: true,
  isHalal: true,
  description: "Rich, nourishing homemade chicken broth – the perfect foundation for soups, stews, and sauces.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 15,
  baseServings: 8,
  calories: 50,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken bones", "onions", "carrots", "celery", "garlic", "bay leaves", "peppercorns"],
  searchKeywords: ["chicken broth", "homemade chicken stock", "nourishing broth", "soup base"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Vegetable Soup",
  tagline: "Hearty soup with chicken and garden vegetables",
  image: "https://diethood.com/wp-content/uploads/2023/12/chicken-vegetable-soup-recipe-3.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "300g chicken breast, cubed",
    "1 onion, chopped",
    "2 carrots, diced",
    "2 potatoes, diced",
    "1 cup green beans, chopped",
    "4 cups chicken broth",
    "2 tomatoes, chopped",
    "1 tsp mixed herbs",
    "2 tbsp oil",
    "Salt and pepper to taste"
  ],
  stepsRaw: [
    "Heat oil in a pot and sauté onions until golden.",
    "Add chicken and cook until browned on all sides.",
    "Add carrots, potatoes, and green beans, cook for 5 minutes.",
    "Pour in chicken broth and bring to a boil.",
    "Add tomatoes and mixed herbs.",
    "Simmer for 30 minutes until vegetables are tender.",
    "Season with salt and pepper to taste.",
    "Serve hot with bread rolls or crackers."
  ],
  difficulty: "Medium",
  cookingTime: 50,
  isActive: true,
  isHalal: true,
  description: "Hearty, wholesome chicken vegetable soup with tender chicken, potatoes, carrots, and green beans – a complete meal in a bowl.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 35,
  baseServings: 4,
  calories: 280,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken breast", "onion", "carrots", "potatoes", "green beans", "chicken broth", "tomatoes", "mixed herbs"],
  searchKeywords: ["chicken vegetable soup", "hearty chicken soup", "garden vegetable soup", "wholesome soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Mulligatawny Soup",
  tagline: "Anglo-Indian curried lentil soup",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVLLBgBh_x71ksVntrxbfzJhqM1M9cn1DOrQ&s",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "1 cup red lentils",
    "1 onion, chopped",
    "2 carrots, diced",
    "2 apples, peeled and diced",
    "4 cups vegetable broth",
    "2 tbsp curry powder",
    "1 tsp turmeric",
    "1 tsp cumin",
    "2 tbsp coconut milk",
    "2 tbsp oil"
  ],
  stepsRaw: [
    "Rinse lentils and soak for 30 minutes, then drain.",
    "Heat oil and sauté onions until soft.",
    "Add carrots and apples, cook for 5 minutes.",
    "Add spices (curry powder, turmeric, cumin) and cook until fragrant.",
    "Add lentils and vegetable broth, bring to boil.",
    "Simmer for 30 minutes until lentils are soft.",
    "Blend half the soup for creaminess (optional).",
    "Stir in coconut milk and serve hot."
  ],
  difficulty: "Medium",
  cookingTime: 45,
  isActive: true,
  isHalal: true,
  description: "Anglo-Indian curried lentil soup with red lentils, apples, carrots, and coconut milk – warm, fragrant, and satisfying.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 28,
  baseServings: 4,
  calories: 210,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["red lentils", "onion", "carrots", "apples", "vegetable broth", "curry powder", "turmeric", "cumin", "coconut milk"],
  searchKeywords: ["mulligatawny soup", "curried lentil soup", "anglo indian soup", "spiced lentil soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Tikka Corn Soup",
  tagline: "Spicy fusion soup with tikka flavors",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyWXNwiW5kMyPwJ0ipRVRDZdGAVw3FRr61BQ&s",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "200g chicken tikka pieces",
    "1 cup sweet corn",
    "1 bell pepper, chopped",
    "4 cups chicken broth",
    "1 cup cream",
    "2 tbsp tikka masala",
    "1 onion, chopped",
    "2 tbsp butter",
    "Fresh coriander for garnish"
  ],
  stepsRaw: [
    "Sauté onions in butter until golden brown.",
    "Add chicken tikka pieces and cook for 5 minutes until heated through.",
    "Add bell pepper and sweet corn, cook for 3 minutes.",
    "Add tikka masala and cook for 2 minutes until fragrant.",
    "Pour in chicken broth and bring to simmer.",
    "Cook for 15 minutes until flavors blend.",
    "Stir in cream and heat through (don't boil).",
    "Garnish with fresh coriander and serve."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Spicy fusion soup with tender chicken tikka pieces, sweet corn, and creamy tikka-spiced broth – bold and comforting.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "economy",
  costPerServing: 40,
  baseServings: 4,
  calories: 310,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken tikka", "sweet corn", "bell pepper", "chicken broth", "cream", "tikka masala", "onion", "butter"],
  searchKeywords: ["chicken tikka corn soup", "tikka soup", "fusion chicken soup", "spicy corn soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Lentil Soup",
  tagline: "Protein-packed Mediterranean lentil soup",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdbZe-gy4koKqvF4b9ng5gLdTBLtT9cxPqXg&s",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "1 cup brown lentils",
    "1 onion, chopped",
    "2 carrots, diced",
    "2 celery stalks, chopped",
    "4 cups vegetable broth",
    "2 cloves garlic, minced",
    "1 tsp cumin",
    "1 bay leaf",
    "2 tbsp lemon juice"
  ],
  stepsRaw: [
    "Rinse lentils and drain.",
    "Sauté onions, carrots, and celery in oil until soft (about 8 minutes).",
    "Add garlic and cumin, cook for 1 minute.",
    "Add lentils, vegetable broth, and bay leaf.",
    "Bring to boil, then reduce heat to simmer.",
    "Cook for 35-40 minutes until lentils are tender.",
    "Remove bay leaf and blend partially if desired.",
    "Stir in lemon juice and serve."
  ],
  difficulty: "Easy",
  cookingTime: 50,
  isActive: true,
  isHalal: true,
  description: "Protein-packed Mediterranean brown lentil soup with carrots, celery, and a hint of lemon – hearty and healthy.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 18,
  baseServings: 4,
  calories: 180,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["brown lentils", "onion", "carrots", "celery", "vegetable broth", "garlic", "cumin", "bay leaf", "lemon"],
  searchKeywords: ["mediterranean lentil soup", "protein soup", "healthy lentil soup", "brown lentil soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Tomato Chicken Macaroni Soup",
  tagline: "Italian-inspired tomato soup with pasta",
  image: "https://eatthegains.com/wp-content/uploads/2022/11/Chicken-Tomato-Soup-10-1120x1120.jpg",
  cuisine: "Italian",
  ingredientsRaw: [
    "200g chicken breast, shredded",
    "1 cup macaroni",
    "4 cups tomato puree",
    "2 cups chicken broth",
    "1 onion, chopped",
    "2 cloves garlic",
    "1 tsp oregano",
    "1 tsp basil",
    "2 tbsp olive oil"
  ],
  stepsRaw: [
    "Cook macaroni according to package directions, drain and set aside.",
    "Heat olive oil and sauté onion and garlic until soft.",
    "Add shredded chicken and cook for 5 minutes.",
    "Add tomato puree and chicken broth.",
    "Season with oregano and basil.",
    "Simmer for 15 minutes until flavors meld.",
    "Add cooked macaroni and heat through.",
    "Serve hot with grated Parmesan cheese."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Italian-inspired tomato soup with shredded chicken and macaroni – a hearty, comforting bowl of goodness.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "economy",
  costPerServing: 35,
  baseServings: 4,
  calories: 290,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken breast", "macaroni", "tomato puree", "chicken broth", "onion", "garlic", "oregano", "basil"],
  searchKeywords: ["tomato chicken macaroni soup", "italian chicken soup", "pasta soup", "tomato macaroni soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Barley Soup",
  tagline: "Hearty grain and vegetable soup",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBjCye450K5PpaObGWKQmMunXo0_cTTBoLPg&s",
  cuisine: "Italian",
  ingredientsRaw: [
    "1 cup pearl barley",
    "2 carrots, diced",
    "2 potatoes, diced",
    "1 onion, chopped",
    "4 cups vegetable broth",
    "2 tbsp tomato paste",
    "1 tsp thyme",
    "2 tbsp olive oil"
  ],
  stepsRaw: [
    "Rinse barley and soak for 30 minutes (optional).",
    "Heat oil and sauté onions until translucent.",
    "Add carrots and potatoes, cook for 5 minutes.",
    "Add barley and vegetable broth.",
    "Stir in tomato paste and thyme.",
    "Bring to boil, then reduce to simmer.",
    "Cook for 50-60 minutes until barley is tender.",
    "Season with salt and pepper and serve."
  ],
  difficulty: "Medium",
  cookingTime: 70,
  isActive: true,
  isHalal: true,
  description: "Hearty barley soup with carrots, potatoes, and thyme – a nutritious, fiber-rich grain soup.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 22,
  baseServings: 4,
  calories: 190,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["pearl barley", "carrots", "potatoes", "onion", "vegetable broth", "tomato paste", "thyme"],
  searchKeywords: ["barley soup", "grain soup", "hearty vegetable soup", "fiber rich soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Potato Soup",
  tagline: "Creamy soup with chicken and potatoes",
  image: "https://valentinascorner.com/wp-content/uploads/2024/03/Creamy-Chicken-Potato-Soup-Recipe-1.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "300g chicken, cubed",
    "3 potatoes, diced",
    "1 onion, chopped",
    "2 carrots, diced",
    "4 cups chicken broth",
    "1 cup milk",
    "2 tbsp flour",
    "2 tbsp butter",
    "Fresh dill for garnish"
  ],
  stepsRaw: [
    "Melt butter and sauté onions until soft.",
    "Add chicken and cook until no longer pink.",
    "Add potatoes and carrots, cook for 5 minutes.",
    "Sprinkle flour and stir for 2 minutes to coat.",
    "Gradually add chicken broth while stirring.",
    "Simmer for 20 minutes until vegetables are tender.",
    "Stir in milk and heat through (don't boil).",
    "Garnish with fresh dill and serve."
  ],
  difficulty: "Medium",
  cookingTime: 40,
  isActive: true,
  isHalal: true,
  description: "Creamy, comforting chicken and potato soup with carrots and dill – a classic family favorite.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "economy",
  costPerServing: 32,
  baseServings: 4,
  calories: 300,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken", "potatoes", "onion", "carrots", "chicken broth", "milk", "flour", "butter", "dill"],
  searchKeywords: ["chicken potato soup", "creamy chicken soup", "potato soup", "comfort soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Hareesa Soup",
  tagline: "Traditional meat and wheat porridge",
  image: "https://onestophalal.com/cdn/shop/articles/hareesa-1697927464282_727ae026-7107-443f-87ca-f2ad241d870a_1200x.jpg?v=1697927657",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g boneless chicken or mutton",
    "1 cup wheat, soaked overnight",
    "2 onions, finely chopped",
    "4 cloves garlic, minced",
    "2-inch ginger, grated",
    "1 tbsp red chili powder",
    "1 tsp garam masala",
    "1/2 cup ghee",
    "Salt to taste"
  ],
  stepsRaw: [
    "Pressure cook meat with wheat until very tender (about 45 minutes).",
    "Shred the meat finely using forks or hands.",
    "Heat ghee and sauté onions until golden brown.",
    "Add garlic and ginger, cook for 2 minutes.",
    "Add chili powder and garam masala, cook for 1 minute.",
    "Add shredded meat and wheat mixture with some cooking liquid.",
    "Cook on low heat for 2-3 hours, stirring occasionally.",
    "Serve hot with lemon wedges and fried onions."
  ],
  difficulty: "Hard",
  cookingTime: 180,
  isActive: true,
  isHalal: true,
  description: "Traditional Middle Eastern meat and wheat porridge – rich, nourishing, and slow-cooked to perfection.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 50,
  baseServings: 6,
  calories: 420,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken", "wheat", "onions", "garlic", "ginger", "red chili powder", "garam masala", "ghee"],
  searchKeywords: ["hareesa soup", "middle eastern porridge", "meat wheat soup", "traditional hareesa"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Cream of Chicken Soup",
  tagline: "Velvety smooth chicken cream soup",
  image: "https://www.recipetineats.com/tachyon/2023/07/Creamy-Tuscan-Chicken-Soup_3.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "300g chicken breast",
    "4 cups chicken broth",
    "1 cup heavy cream",
    "1 onion, chopped",
    "2 tbsp butter",
    "2 tbsp flour",
    "1 tsp thyme",
    "Salt and pepper to taste"
  ],
  stepsRaw: [
    "Poach chicken in broth until cooked through (about 15-20 minutes).",
    "Remove chicken, shred or dice finely.",
    "Melt butter and sauté onions until soft.",
    "Add flour and cook for 2 minutes.",
    "Gradually add chicken broth while whisking.",
    "Simmer for 10 minutes until slightly thickened.",
    "Add shredded chicken and thyme.",
    "Stir in cream, heat through (don't boil), season and serve."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Velvety smooth cream of chicken soup with tender shredded chicken and aromatic thyme – pure comfort in a bowl.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "economy",
  costPerServing: 38,
  baseServings: 4,
  calories: 320,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken breast", "chicken broth", "heavy cream", "onion", "butter", "flour", "thyme"],
  searchKeywords: ["cream of chicken soup", "velvety chicken soup", "comfort soup", "creamy chicken"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Spinach Soup",
  tagline: "Healthy and vibrant green spinach soup",
  image: "https://static01.nyt.com/images/2013/06/03/health/03recipehealth/03recipehealth-superJumbo.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g fresh spinach",
    "1 onion, chopped",
    "2 cloves garlic",
    "3 cups vegetable broth",
    "1 cup milk",
    "2 tbsp butter",
    "Pinch of nutmeg",
    "Salt and pepper to taste"
  ],
  stepsRaw: [
    "Wash spinach thoroughly.",
    "Melt butter and sauté onion and garlic until soft.",
    "Add spinach and cook until wilted (about 3-4 minutes).",
    "Add vegetable broth and bring to boil.",
    "Simmer for 10 minutes.",
    "Blend until smooth using immersion blender.",
    "Return to pot, add milk and nutmeg.",
    "Heat through and serve."
  ],
  difficulty: "Easy",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Healthy, vibrant green spinach soup with a touch of nutmeg and milk – light, nutritious, and delicious.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "economy",
  costPerServing: 18,
  baseServings: 4,
  calories: 110,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["spinach", "onion", "garlic", "vegetable broth", "milk", "butter", "nutmeg"],
  searchKeywords: ["spinach soup", "green soup", "healthy soup", "vegetarian soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Restaurant Style Hot and Sour Soup",
  tagline: "Authentic Chinese hot and sour soup",
  image: "https://redhousespice.com/wp-content/uploads/2021/08/Chinese-hot-and-sour-soup-1-scaled.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "4 cups chicken broth",
    "100g chicken, shredded",
    "50g mushrooms, sliced",
    "50g bamboo shoots",
    "2 tbsp soy sauce",
    "2 tbsp vinegar",
    "1 tbsp chili sauce",
    "2 tbsp cornstarch",
    "1 egg, beaten"
  ],
  stepsRaw: [
    "Bring broth to boil in a pot.",
    "Add chicken, mushrooms, and bamboo shoots.",
    "Cook for 8 minutes until chicken is cooked.",
    "Mix cornstarch with water to make slurry.",
    "Add soy sauce, vinegar, and chili sauce.",
    "Add cornstarch slurry while stirring until thickened.",
    "Slowly drizzle beaten egg while stirring in one direction.",
    "Serve immediately with chili oil on side."
  ],
  difficulty: "Medium",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Authentic Chinese hot and sour soup with chicken, mushrooms, bamboo shoots, and silky egg ribbons – tangy and spicy.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["eggs", "soy"],
  budget: "economy",
  costPerServing: 25,
  baseServings: 4,
  calories: 140,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken broth", "chicken", "mushrooms", "bamboo shoots", "soy sauce", "vinegar", "chili sauce", "cornstarch", "egg"],
  searchKeywords: ["hot and sour soup", "chinese soup", "authentic hot sour", "restaurant soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Corn Soup",
  tagline: "Sweet corn and chicken classic",
  image: "https://www.tasteofhome.com/wp-content/uploads/2018/01/Amish-Chicken-Corn-Soup_EXPS_FT24_31049_EC_060524_1.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "200g chicken breast, shredded",
    "1 can cream style corn",
    "4 cups chicken broth",
    "2 tbsp cornstarch",
    "1 egg white",
    "1 tsp ginger, grated",
    "2 spring onions, chopped",
    "Salt and white pepper"
  ],
  stepsRaw: [
    "Bring broth to boil in a pot.",
    "Add chicken and ginger, cook for 10 minutes.",
    "Add cream style corn and stir well.",
    "Mix cornstarch with water to make slurry.",
    "Add slurry while stirring until soup thickens slightly.",
    "Slowly pour in beaten egg white while stirring.",
    "Season with salt and white pepper.",
    "Garnish with spring onions and serve."
  ],
  difficulty: "Easy",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Classic sweet corn and chicken soup with creamy corn, shredded chicken, and delicate egg white ribbons.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["eggs"],
  budget: "economy",
  costPerServing: 28,
  baseServings: 4,
  calories: 180,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken breast", "cream style corn", "chicken broth", "cornstarch", "egg white", "ginger", "spring onions"],
  searchKeywords: ["chicken corn soup", "sweet corn soup", "classic corn soup", "easy chicken soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Mixed Grain Soup",
  tagline: "Nutritious multi-grain vegetable soup",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZGsoN2CzjBtlKPnz2ATrFnz2i1eR20avHuA&s",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "1/2 cup barley",
    "1/2 cup quinoa",
    "1/4 cup lentils",
    "4 cups vegetable broth",
    "2 carrots, diced",
    "2 celery stalks, chopped",
    "1 onion, chopped",
    "2 tbsp olive oil"
  ],
  stepsRaw: [
    "Rinse all grains under cold water.",
    "Heat oil and sauté vegetables until soft (about 8 minutes).",
    "Add grains and cook for 2 minutes, stirring.",
    "Add vegetable broth and bring to boil.",
    "Reduce heat to simmer and cover.",
    "Cook for 45 minutes until grains are tender.",
    "Season with herbs and spices to taste.",
    "Serve hot with crusty bread."
  ],
  difficulty: "Medium",
  cookingTime: 55,
  isActive: true,
  isHalal: true,
  description: "Nutritious multi-grain soup with barley, quinoa, lentils, and fresh vegetables – a fiber-rich, wholesome meal.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 25,
  baseServings: 4,
  calories: 210,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["barley", "quinoa", "lentils", "vegetable broth", "carrots", "celery", "onion"],
  searchKeywords: ["mixed grain soup", "multi grain soup", "healthy grain soup", "vegetable grain soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Hot and Sour Chicken Macaroni Soup",
  tagline: "Spicy tangy soup with pasta",
  image: "https://www.yummytummyaarthi.com/wp-content/uploads/2022/07/hot-and-sour-chicken-soup-1-500x500.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "200g chicken, shredded",
    "1 cup macaroni",
    "4 cups chicken broth",
    "2 tbsp soy sauce",
    "1 tbsp vinegar",
    "1 tbsp chili garlic sauce",
    "2 tbsp cornstarch",
    "1 cup mixed vegetables"
  ],
  stepsRaw: [
    "Cook macaroni according to package, drain and set aside.",
    "Bring broth to boil in a pot.",
    "Add chicken and vegetables, cook for 10 minutes.",
    "Add soy sauce, vinegar, and chili garlic sauce.",
    "Mix cornstarch with water to make slurry.",
    "Add slurry while stirring until soup thickens.",
    "Add cooked macaroni and heat through.",
    "Serve hot with extra chili sauce on side."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Spicy, tangy hot and sour soup with shredded chicken, macaroni, and mixed vegetables – a satisfying fusion meal.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["soy", "gluten"],
  budget: "economy",
  costPerServing: 32,
  baseServings: 4,
  calories: 280,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken", "macaroni", "chicken broth", "soy sauce", "vinegar", "chili garlic sauce", "cornstarch", "mixed vegetables"],
  searchKeywords: ["hot and sour chicken macaroni soup", "spicy pasta soup", "chinese macaroni soup", "fusion soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Herbal Soup",
  tagline: "Traditional Chinese medicinal soup",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWhSr-Av1kFPXW6tpS1_vI0qGUYhbZMCl42w&s",
  cuisine: "Chinese",
  ingredientsRaw: [
    "300g chicken or pork ribs",
    "10 red dates",
    "20g goji berries",
    "15g dried longan",
    "10g dried polygonatum",
    "10g dried Chinese yam",
    "2 liters water",
    "Salt to taste"
  ],
  stepsRaw: [
    "Blanch meat in boiling water for 5 minutes, then rinse.",
    "Combine all ingredients in large pot with water.",
    "Bring to boil, then reduce heat to low simmer.",
    "Simmer for 1.5-2 hours until meat is very tender.",
    "Skim off any impurities that rise to surface.",
    "Season with salt if needed (traditionally unsalted).",
    "Strain and serve hot as nourishing broth.",
    "Discard herbs before serving."
  ],
  difficulty: "Hard",
  cookingTime: 120,
  isActive: true,
  isHalal: true,
  description: "Traditional Chinese medicinal soup with red dates, goji berries, and herbs – a nourishing, restorative broth.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 40,
  baseServings: 4,
  calories: 180,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken", "red dates", "goji berries", "dried longan", "polygonatum", "chinese yam"],
  searchKeywords: ["herbal soup", "chinese medicinal soup", "tonic soup", "nourishing broth"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Mutton Broth",
  tagline: "Rich and nourishing mutton soup",
  image: "https://www.foodireland.com/recipes/wp-content/uploads/2013/07/mutton-broth.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g mutton with bones",
    "8 cups water",
    "1 onion, chopped",
    "4 cloves garlic",
    "1-inch ginger, sliced",
    "1 tsp whole black pepper",
    "4 cloves",
    "2 green cardamom",
    "1 cinnamon stick",
    "1 bay leaf",
    "Salt to taste",
    "Fresh coriander for garnish"
  ],
  stepsRaw: [
    "Wash mutton thoroughly and place in cooking pot.",
    "Add water, onion, garlic, ginger, and all whole spices.",
    "Bring to a boil, then reduce heat to low simmer.",
    "Simmer for 2-3 hours until mutton becomes very tender.",
    "Remove any foam that forms on surface during cooking.",
    "Add salt toward the end of cooking.",
    "Strain broth for clear soup, or serve with meat pieces.",
    "Garnish with fresh coriander and serve hot."
  ],
  difficulty: "Hard",
  cookingTime: 180,
  isActive: true,
  isHalal: true,
  description: "Rich, nourishing mutton broth slow-simmered with whole spices – a hearty, warming traditional soup.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 50,
  baseServings: 4,
  calories: 280,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["mutton", "onion", "garlic", "ginger", "black pepper", "cloves", "cardamom", "cinnamon", "bay leaf"],
  searchKeywords: ["mutton broth", "mutton soup", "nourishing soup", "traditional mutton"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Pumpkin Soup",
  tagline: "Creamy roasted pumpkin soup",
  image: "https://images.immediate.co.uk/production/volatile/sites/30/2021/07/Spicy-pumpkin-soup-fcf2fe5.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "1 kg pumpkin, peeled and cubed",
    "1 onion, chopped",
    "2 cloves garlic",
    "4 cups vegetable broth",
    "1 cup coconut milk",
    "1 tsp cinnamon",
    "1/2 tsp nutmeg",
    "2 tbsp olive oil"
  ],
  stepsRaw: [
    "Toss pumpkin cubes with oil and roast at 200°C for 25 minutes.",
    "Sauté onion and garlic in pot until soft.",
    "Add roasted pumpkin and vegetable broth.",
    "Simmer for 15 minutes.",
    "Blend until very smooth using immersion blender.",
    "Return to pot, add coconut milk and spices.",
    "Heat through without boiling.",
    "Serve with roasted pumpkin seeds and cream swirl."
  ],
  difficulty: "Medium",
  cookingTime: 45,
  isActive: true,
  isHalal: true,
  description: "Creamy, velvety roasted pumpkin soup with coconut milk, cinnamon, and nutmeg – a cozy autumn favorite.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 25,
  baseServings: 4,
  calories: 160,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["pumpkin", "onion", "garlic", "vegetable broth", "coconut milk", "cinnamon", "nutmeg"],
  searchKeywords: ["pumpkin soup", "creamy pumpkin soup", "roasted pumpkin soup", "fall soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Pot Pie Soup with Tender Pops",
  tagline: "All the flavors of pot pie in soup form",
  image: "https://i.ytimg.com/vi/JypPJvP2Kp4/maxresdefault.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "300g chicken, cubed",
    "2 carrots, diced",
    "1 cup peas",
    "2 potatoes, diced",
    "4 cups chicken broth",
    "1 cup milk",
    "2 tbsp flour",
    "Puff pastry for topping"
  ],
  stepsRaw: [
    "Sauté chicken until cooked through, remove from pot.",
    "Sauté vegetables in same pot until tender (about 8 minutes).",
    "Add flour and cook for 2 minutes.",
    "Gradually add broth and milk while whisking.",
    "Add chicken back to pot.",
    "Simmer for 20 minutes until thickened.",
    "While soup simmers, bake puff pastry cut into small shapes.",
    "Serve soup with crispy pastry pops on top."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "All the comforting flavors of chicken pot pie transformed into a creamy soup, topped with crispy puff pastry pops.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "economy",
  costPerServing: 45,
  baseServings: 4,
  calories: 380,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken", "carrots", "peas", "potatoes", "chicken broth", "milk", "flour", "puff pastry"],
  searchKeywords: ["pot pie soup", "chicken pot pie soup", "creamy soup", "puff pastry soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Garlic Soup",
  tagline: "Intensely flavorful roasted garlic soup",
  image: "https://www.lifesambrosia.com/wp-content/uploads/Roasted-Garlic-Soup-Recipe-Photo-8.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "2 whole garlic bulbs",
    "1 onion, chopped",
    "4 cups vegetable broth",
    "1 cup cream",
    "2 tbsp olive oil",
    "Fresh thyme",
    "Salt and pepper"
  ],
  stepsRaw: [
    "Cut tops off garlic bulbs, drizzle with oil, wrap in foil.",
    "Roast at 190°C for 45-60 minutes until soft.",
    "Let cool, then squeeze out roasted garlic cloves.",
    "Sauté onion in pot until translucent.",
    "Add roasted garlic and broth.",
    "Simmer for 20 minutes.",
    "Blend until very smooth.",
    "Stir in cream and thyme, heat through and serve."
  ],
  difficulty: "Medium",
  cookingTime: 80,
  isActive: true,
  isHalal: true,
  description: "Intensely flavorful roasted garlic soup with cream and thyme – a rich, velvety, and aromatic bowl of comfort.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "economy",
  costPerServing: 22,
  baseServings: 4,
  calories: 180,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["garlic", "onion", "vegetable broth", "cream", "olive oil", "thyme"],
  searchKeywords: ["garlic soup", "roasted garlic soup", "creamy garlic soup", "aromatic soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Manchow Soup With Crispy Noodles",
  tagline: "Indo-Chinese soup with crunchy topping",
  image: "https://www.secondrecipe.com/wp-content/uploads/2020/06/veg-manchow-soup.jpg",
  cuisine: "Chinese",
  ingredientsRaw: [
    "4 cups vegetable broth",
    "1 cup mixed vegetables (carrots, cabbage, bell peppers)",
    "100g chicken or tofu",
    "2 tbsp soy sauce",
    "1 tbsp vinegar",
    "1 tbsp chili sauce",
    "2 tbsp cornstarch",
    "Crispy noodles for topping"
  ],
  stepsRaw: [
    "Sauté vegetables and protein until cooked.",
    "Add broth and bring to boil.",
    "Add soy sauce, vinegar, and chili sauce.",
    "Mix cornstarch with water to make slurry.",
    "Add slurry while stirring until soup thickens.",
    "Simmer for 10 minutes.",
    "Deep fry noodles until golden and crispy.",
    "Serve soup with generous amount of crispy noodles on top."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Indo-Chinese manchow soup with mixed vegetables, protein, and a crunchy topping of crispy noodles – spicy and satisfying.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["soy", "gluten"],
  budget: "economy",
  costPerServing: 28,
  baseServings: 4,
  calories: 210,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["vegetable broth", "mixed vegetables", "tofu", "soy sauce", "vinegar", "chili sauce", "cornstarch", "noodles"],
  searchKeywords: ["manchow soup", "indo chinese soup", "crispy noodle soup", "veg manchow"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Oats Soup",
  tagline: "Healthy and hearty oat vegetable soup",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWZ_ZD63lz1QYsdz_Dw_tSKJwEss3DFqaFCg&s",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "1 cup rolled oats",
    "4 cups vegetable broth",
    "1 carrot, grated",
    "1 onion, chopped",
    "2 cloves garlic",
    "1 tsp cumin",
    "2 tbsp lemon juice",
    "Fresh coriander"
  ],
  stepsRaw: [
    "Dry roast oats in pan for 2-3 minutes until fragrant.",
    "Sauté vegetables in pot until soft.",
    "Add oats and broth.",
    "Bring to boil, then reduce to simmer.",
    "Cook for 15 minutes until oats are soft.",
    "Add cumin and lemon juice.",
    "Garnish with fresh coriander.",
    "Serve hot with crusty bread."
  ],
  difficulty: "Easy",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Healthy, hearty oat vegetable soup with carrots, cumin, and lemon – a fiber-rich, nourishing meal.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 15,
  baseServings: 4,
  calories: 120,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["rolled oats", "vegetable broth", "carrot", "onion", "garlic", "cumin", "lemon", "coriander"],
  searchKeywords: ["oats soup", "healthy oat soup", "vegetable oat soup", "hearty soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Creamy Chicken Macaroni Soup",
  tagline: "Rich and creamy pasta soup",
  image: "https://theunlikelybaker.com/wp-content/uploads/2025/11/4-Macaroni-Sopas.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "200g chicken, cubed",
    "1 cup macaroni",
    "4 cups chicken broth",
    "1 cup cream",
    "1 onion, chopped",
    "2 tbsp butter",
    "2 tbsp flour",
    "1 tsp mixed herbs"
  ],
  stepsRaw: [
    "Cook macaroni according to package, drain and set aside.",
    "Sauté chicken until cooked through, remove from pot.",
    "Melt butter and sauté onions until soft.",
    "Add flour and cook for 2 minutes.",
    "Gradually add broth while whisking.",
    "Add chicken and herbs.",
    "Simmer for 15 minutes.",
    "Stir in cream and macaroni, heat through and serve."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Rich and creamy chicken macaroni soup with tender chicken pieces and pasta in a velvety cream broth.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "economy",
  costPerServing: 38,
  baseServings: 4,
  calories: 360,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken", "macaroni", "chicken broth", "cream", "onion", "butter", "flour", "mixed herbs"],
  searchKeywords: ["creamy chicken macaroni soup", "macaroni soup", "pasta soup", "creamy chicken pasta"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Paye Soup",
  tagline: "Rich gelatinous trotter soup",
  image: "https://flavoredbyfatima.com/wp-content/uploads/2020/10/mutton-paya-mutton-trotters.jpeg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "4 lamb or goat trotters",
    "2 onions, chopped",
    "2-inch ginger, grated",
    "6 cloves garlic",
    "2 tbsp coriander powder",
    "1 tbsp red chili powder",
    "1 tsp turmeric",
    "Fresh ginger for garnish"
  ],
  stepsRaw: [
    "Clean trotters thoroughly, wash multiple times.",
    "Pressure cook trotters with water for 2 hours until very tender.",
    "Sauté onions in separate pan until golden brown.",
    "Add ginger, garlic, and spices, cook for 3 minutes.",
    "Add cooked trotters and broth.",
    "Simmer for 3-4 hours until soup becomes thick and gelatinous.",
    "Skim off excess fat if desired.",
    "Serve with fresh ginger, lemon, and chopped coriander."
  ],
  difficulty: "Hard",
  cookingTime: 360,
  isActive: true,
  isHalal: true,
  description: "Rich, gelatinous trotter soup (paye) slow-cooked with aromatic spices – a traditional Pakistani delicacy.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 55,
  baseServings: 4,
  calories: 420,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["lamb trotters", "onions", "ginger", "garlic", "coriander powder", "red chili powder", "turmeric"],
  searchKeywords: ["paye soup", "trotter soup", "paya", "traditional pakistani soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Tomato Soup",
  tagline: "Classic creamy tomato soup",
  image: "https://cdn.loveandlemons.com/wp-content/uploads/2023/01/tomato-soup-recipe.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "1 kg ripe tomatoes",
    "1 onion, chopped",
    "2 cloves garlic",
    "4 cups vegetable broth",
    "2 tbsp tomato paste",
    "1 tsp sugar",
    "Fresh basil",
    "2 tbsp cream"
  ],
  stepsRaw: [
    "Blanch tomatoes in boiling water, peel and chop.",
    "Sauté onion and garlic in pot until soft.",
    "Add tomatoes and tomato paste.",
    "Cook for 10 minutes until tomatoes break down.",
    "Add broth and simmer for 15 minutes.",
    "Blend until very smooth.",
    "Add sugar and fresh basil.",
    "Serve with cream drizzle and croutons."
  ],
  difficulty: "Easy",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Classic creamy tomato soup with fresh basil – smooth, tangy, and comforting, perfect with a drizzle of cream.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "economy",
  costPerServing: 20,
  baseServings: 4,
  calories: 120,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["tomatoes", "onion", "garlic", "vegetable broth", "tomato paste", "sugar", "basil", "cream"],
  searchKeywords: ["tomato soup", "creamy tomato soup", "classic tomato soup", "comfort soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Thai Soup",
  tagline: "Aromatic Thai coconut soup",
  image: "https://kaynutrition.com/wp-content/uploads/2023/10/thai-chicken-noodle-soup-1.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "4 cups chicken or vegetable broth",
    "2 stalks lemongrass",
    "4 kaffir lime leaves",
    "2-inch galangal, sliced",
    "200g shrimp or chicken",
    "4 mushrooms, sliced",
    "2 tbsp fish sauce",
    "2 tbsp lime juice"
  ],
  stepsRaw: [
    "Bruise lemongrass stalks and add to broth.",
    "Add galangal slices and kaffir lime leaves.",
    "Bring to boil and simmer for 10 minutes.",
    "Add protein and mushrooms.",
    "Cook until protein is done (shrimp turn pink).",
    "Remove lemongrass and galangal before serving.",
    "Add fish sauce and lime juice.",
    "Serve with fresh cilantro leaves."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Aromatic Thai coconut-free soup with lemongrass, galangal, lime leaves, and shrimp – fragrant and refreshing.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["shellfish"],
  budget: "economy",
  costPerServing: 45,
  baseServings: 4,
  calories: 160,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["lemongrass", "kaffir lime leaves", "galangal", "shrimp", "mushrooms", "fish sauce", "lime juice"],
  searchKeywords: ["thai soup", "tom yum", "aromatic soup", "thai shrimp soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Corn Soup",
  tagline: "Sweet corn and chicken classic",
  image: "https://www.maggi.lk/sites/default/files/srh_recipes/21f2b7c2ebc7628c987903ea4a638ee9.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "200g chicken breast, shredded",
    "1 can corn kernels",
    "4 cups chicken broth",
    "2 tbsp cornstarch",
    "1 egg white",
    "1 tsp ginger, grated",
    "Spring onions",
    "White pepper"
  ],
  stepsRaw: [
    "Bring broth to boil in a pot.",
    "Add chicken and ginger.",
    "Cook for 10 minutes until chicken is done.",
    "Add corn kernels.",
    "Mix cornstarch with water for slurry.",
    "Add slurry while stirring until soup thickens.",
    "Drizzle egg white while stirring.",
    "Garnish with spring onions and white pepper."
  ],
  difficulty: "Easy",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Classic sweet corn and chicken soup with delicate egg white ribbons – a comforting, family favorite.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["eggs"],
  budget: "economy",
  costPerServing: 28,
  baseServings: 4,
  calories: 170,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken breast", "corn kernels", "chicken broth", "cornstarch", "egg white", "ginger", "spring onions"],
  searchKeywords: ["chicken corn soup", "sweet corn soup", "classic soup", "easy chicken soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Mixed Vegetable Soup",
  tagline: "Healthy garden vegetable soup",
  image: "https://www.forkinthekitchen.com/wp-content/uploads/2022/04/220323.vegetable.barley.soup-3802.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "2 cups mixed vegetables (carrots, peas, beans, corn)",
    "1 onion, chopped",
    "2 cloves garlic",
    "4 cups vegetable broth",
    "2 tomatoes, chopped",
    "1 tsp mixed herbs",
    "2 tbsp olive oil",
    "Salt and pepper"
  ],
  stepsRaw: [
    "Sauté onion and garlic in olive oil until soft.",
    "Add mixed vegetables, cook for 5 minutes.",
    "Add tomatoes and cook until soft.",
    "Add vegetable broth and herbs.",
    "Bring to boil, then simmer for 20 minutes.",
    "Season with salt and pepper.",
    "Blend partially if desired for texture.",
    "Serve hot with whole grain bread."
  ],
  difficulty: "Easy",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Healthy garden vegetable soup with carrots, peas, beans, corn, and tomatoes – light, nourishing, and flavorful.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 15,
  baseServings: 4,
  calories: 90,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["mixed vegetables", "onion", "garlic", "vegetable broth", "tomatoes", "mixed herbs", "olive oil"],
  searchKeywords: ["mixed vegetable soup", "garden vegetable soup", "healthy soup", "veggie soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Clear Soup",
  tagline: "Light and delicate clear chicken soup",
  image: "https://sugarfreelondoner.com/wp-content/uploads/2023/11/clear-chicken-soup-1200.jpg",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "300g chicken pieces",
    "6 cups water",
    "1 carrot, sliced",
    "2 celery stalks",
    "1 onion, quartered",
    "4 cloves garlic",
    "1-inch ginger",
    "Salt to taste"
  ],
  stepsRaw: [
    "Place chicken in pot with cold water.",
    "Bring to boil, immediately skim impurities.",
    "Add vegetables and aromatics.",
    "Reduce heat and simmer for 40 minutes.",
    "Remove chicken and shred meat.",
    "Strain broth through cheesecloth for clarity.",
    "Return shredded chicken to clear broth.",
    "Season lightly with salt and serve."
  ],
  difficulty: "Medium",
  cookingTime: 50,
  isActive: true,
  isHalal: true,
  description: "Light, delicate clear chicken soup with shredded chicken and subtle vegetable flavors – a soothing, healthy broth.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: [],
  budget: "economy",
  costPerServing: 22,
  baseServings: 4,
  calories: 110,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken", "carrot", "celery", "onion", "garlic", "ginger"],
  searchKeywords: ["chicken clear soup", "clear soup", "light chicken broth", "delicate soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Noodles Soup",
  tagline: "Asian-style noodle soup",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYT2yh9YBNNuh7RzN5J4gv5deNnVpsWUw4jA&s",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "200g noodles",
    "4 cups broth (chicken or vegetable)",
    "1 cup mixed vegetables",
    "100g chicken or tofu",
    "2 tbsp soy sauce",
    "1 tsp sesame oil",
    "Spring onions",
    "Chili flakes (optional)"
  ],
  stepsRaw: [
    "Cook noodles according to package, drain and set aside.",
    "Bring broth to boil in a pot.",
    "Add vegetables and protein, cook for 10 minutes.",
    "Season with soy sauce and sesame oil.",
    "Place cooked noodles in serving bowls.",
    "Ladle hot broth with vegetables over noodles.",
    "Garnish with spring onions.",
    "Add chili flakes if desired and serve."
  ],
  difficulty: "Easy",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Asian-style noodle soup with mixed vegetables and your choice of chicken or tofu – quick, customizable, and satisfying.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["soy", "gluten"],
  budget: "economy",
  costPerServing: 25,
  baseServings: 4,
  calories: 230,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["noodles", "broth", "mixed vegetables", "tofu", "soy sauce", "sesame oil", "spring onions"],
  searchKeywords: ["noodle soup", "asian noodle soup", "quick noodle soup", "vegetable noodle soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "19B Soup",
  tagline: "Special signature soup",
  image: "https://i.ytimg.com/vi/yqPFPNhqG1w/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDYXmye0zIrwk7FMmzR8AruWEYTJA",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "4 cups chicken broth",
    "200g chicken, shredded",
    "1 cup mixed vegetables",
    "2 tbsp soy sauce",
    "1 tbsp oyster sauce",
    "1 tsp white pepper",
    "2 tbsp cornstarch",
    "1 egg, beaten"
  ],
  stepsRaw: [
    "Bring broth to boil in a pot.",
    "Add chicken and vegetables.",
    "Cook for 15 minutes until vegetables are tender.",
    "Add soy sauce, oyster sauce, and white pepper.",
    "Mix cornstarch with water to make slurry.",
    "Add slurry while stirring until soup thickens.",
    "Slowly drizzle beaten egg while stirring.",
    "Garnish and serve hot."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Special signature soup with shredded chicken, mixed vegetables, and silky egg ribbons – rich, savory, and unique.",
  category: "Dinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["eggs", "soy"],
  budget: "economy",
  costPerServing: 30,
  baseServings: 4,
  calories: 200,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["chicken broth", "chicken", "mixed vegetables", "soy sauce", "oyster sauce", "cornstarch", "egg"],
  searchKeywords: ["19b soup", "signature soup", "special soup", "creamy chicken soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Fish Vegetable and Noodle Soup",
  tagline: "Light fish soup with noodles",
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRi9QYX7gZb0ZvPyexK40_Nspt-9MnPOwaagQ&s",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "300g white fish fillets (cod, tilapia, or snapper)",
    "1 cup noodles",
    "4 cups fish or vegetable broth",
    "1 cup mixed vegetables",
    "2 tbsp fish sauce",
    "1 tbsp lime juice",
    "1 tsp ginger, grated",
    "Fresh cilantro"
  ],
  stepsRaw: [
    "Cook noodles according to package, drain and set aside.",
    "Bring broth to gentle simmer in pot.",
    "Add ginger and vegetables.",
    "Cook for 8 minutes until vegetables are tender.",
    "Add fish pieces gently to pot.",
    "Cook for 5 minutes until fish flakes easily.",
    "Add noodles, fish sauce, and lime juice.",
    "Garnish with fresh cilantro and serve."
  ],
  difficulty: "Medium",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Light, delicate fish soup with noodles, vegetables, and a hint of lime – a refreshing, healthy Asian-inspired bowl.",
  category: "LightDinner",
  subCategory: "soups",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Lunch", "Dinner"],
  beverageCategory: null,
  allergens: ["fish", "gluten"],
  budget: "economy",
  costPerServing: 40,
  baseServings: 4,
  calories: 190,
  ageGroup: ["adults", "seniors", "kids"],
  patientFriendly: ["general", "diabetes", "heart", "bp", "lowsalt", "lowfat"],
  pantryKeywords: ["white fish", "noodles", "fish broth", "mixed vegetables", "fish sauce", "lime juice", "ginger", "cilantro"],
  searchKeywords: ["fish noodle soup", "light fish soup", "asian fish soup", "seafood noodle soup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
}
];

async function migrate() {
  try {
    console.log('🔌 Connecting to MongoDB...');
const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
if (!mongoURI) throw new Error('MongoDB URI not found');
await mongoose.connect(mongoURI, { serverSelectionTimeoutMS: 10000, family: 4 });   
 console.log('✅ Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`✅ Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`⚠️ Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\n🎉 Migration Complete!');
    console.log(`📊 Added: ${added}, Skipped: ${skipped}`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

migrate();