// 20-snacks.js - COMPLETE (36 recipes)
const mongoose = require('mongoose');
const Recipe = require('../models/Recipe');
require('dotenv').config({ path: '../.env' });

const recipesToMigrate = [
  {
  title: "Pinwheel Spring Rolls",
  tagline: "Crispy rolled spring rolls with vegetable filling",
  image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "10 spring roll wrappers",
    "2 cups shredded cabbage",
    "1 cup grated carrots",
    "1 cup bean sprouts",
    "1/2 cup chopped bell peppers",
    "1/2 cup chopped spring onions",
    "2 tablespoons soy sauce",
    "1 tablespoon vinegar",
    "1 teaspoon ginger-garlic paste",
    "1 teaspoon black pepper",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "Heat 1 tablespoon oil in a pan, add ginger-garlic paste and sauté for 30 seconds.",
    "Add all vegetables and stir-fry for 3-4 minutes until slightly cooked but still crunchy.",
    "Add soy sauce, vinegar, black pepper, and salt. Mix well and cook for 2 minutes.",
    "Remove from heat and let the filling cool completely.",
    "Place a spring roll wrapper on a flat surface, add 2 tablespoons of filling in the center.",
    "Fold the sides inward, then roll tightly from one end to form a cylinder.",
    "Seal the edge with a paste made of flour and water.",
    "Heat oil in a deep pan on medium heat.",
    "Fry spring rolls until golden brown and crispy, about 3-4 minutes.",
    "Drain on paper towels and serve hot with sweet chili sauce."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Crispy, golden vegetable spring rolls with a crunchy cabbage-carrot filling – perfect as a tea-time snack or appetizer.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["gluten", "soy"],
  budget: "standard",
  costPerServing: 18,
  baseServings: 4,
  calories: 160,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["spring roll wrappers", "cabbage", "carrots", "bean sprouts", "bell peppers", "spring onions", "soy sauce", "ginger-garlic paste"],
  searchKeywords: ["pinwheel spring rolls", "vegetable spring rolls", "crispy spring rolls", "asian snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Stuffed Capsicum with Aloo Chaat",
  tagline: "Bell peppers stuffed with spiced potato filling",
  image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "4 large bell peppers",
    "2 large potatoes, boiled and mashed",
    "1 onion, finely chopped",
    "1 tomato, finely chopped",
    "1 green chili, finely chopped",
    "1 teaspoon chaat masala",
    "1/2 teaspoon red chili powder",
    "1/2 teaspoon turmeric powder",
    "1/2 teaspoon garam masala",
    "2 tablespoons chopped coriander",
    "1 tablespoon lemon juice",
    "Salt to taste",
    "2 tablespoons oil"
  ],
  stepsRaw: [
    "Cut the tops off bell peppers and remove seeds.",
    "Boil bell peppers in salted water for 3 minutes, then drain.",
    "In a bowl, mix mashed potatoes, onion, tomato, green chili, and spices.",
    "Add lemon juice and coriander, mix well.",
    "Stuff this mixture into the bell peppers.",
    "Heat oil in a pan, place stuffed bell peppers carefully.",
    "Cover and cook on low heat for 8-10 minutes, turning occasionally.",
    "In a separate bowl, mix some boiled potato cubes with chaat masala, onion, and coriander for chaat.",
    "Serve stuffed capsicum hot with potato chaat on the side.",
    "Garnish with sev and additional coriander leaves."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Colorful bell peppers stuffed with spiced mashed potatoes, served with tangy aloo chaat – a delightful Indian snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 22,
  baseServings: 4,
  calories: 180,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["bell peppers", "potatoes", "onion", "tomato", "green chili", "chaat masala", "garam masala", "coriander", "lemon"],
  searchKeywords: ["stuffed capsicum", "aloo chaat", "stuffed bell peppers", "indian snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Pakora",
  tagline: "Crispy fried chicken fritters with gram flour batter",
  image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g boneless chicken, cut into small pieces",
    "1 cup gram flour (besan)",
    "1/4 cup rice flour",
    "1 teaspoon ginger-garlic paste",
    "1 teaspoon red chili powder",
    "1/2 teaspoon turmeric powder",
    "1 teaspoon garam masala",
    "1 teaspoon coriander powder",
    "1 onion, finely chopped",
    "2 green chilies, chopped",
    "2 tablespoons chopped coriander",
    "1 tablespoon lemon juice",
    "Water as needed",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "In a bowl, mix chicken pieces with ginger-garlic paste, red chili powder, turmeric, and salt.",
    "Let it marinate for 30 minutes.",
    "In another bowl, mix gram flour, rice flour, and all spices.",
    "Add chopped onion, green chilies, and coriander to the flour mixture.",
    "Gradually add water to make a thick batter.",
    "Add lemon juice and mix well.",
    "Heat oil in a deep pan on medium heat.",
    "Dip marinated chicken pieces in the batter, coating well.",
    "Carefully drop battered chicken into hot oil.",
    "Fry until golden brown and crispy, about 5-7 minutes.",
    "Remove with slotted spoon and drain on paper towels.",
    "Serve hot with mint chutney or ketchup."
  ],
  difficulty: "Medium",
  cookingTime: 40,
  isActive: true,
  isHalal: true,
  description: "Crispy, golden chicken fritters coated in spiced gram flour batter – a classic Pakistani tea-time snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 45,
  baseServings: 4,
  calories: 290,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken", "gram flour", "besan", "rice flour", "ginger-garlic paste", "red chili", "garam masala", "onion", "green chilies"],
  searchKeywords: ["chicken pakora", "chicken fritters", "crispy chicken snack", "pakistani pakora"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Cheesy Baked Rolls",
  tagline: "Baked bread rolls stuffed with cheese and corn",
  image: "https://images.unsplash.com/photo-1563379091339-03246963d9d6",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "8 bread slices",
    "1 cup grated mozzarella cheese",
    "1/2 cup grated cheddar cheese",
    "1/2 cup sweet corn kernels",
    "1/4 cup finely chopped bell peppers",
    "1/4 cup finely chopped onions",
    "2 tablespoons pizza sauce",
    "1 teaspoon oregano",
    "1 teaspoon chili flakes",
    "2 tablespoons butter, melted",
    "Salt to taste",
    "Black pepper to taste"
  ],
  stepsRaw: [
    "Preheat oven to 180°C (350°F).",
    "Trim edges from bread slices and flatten with rolling pin.",
    "In a bowl, mix both cheeses, sweet corn, bell peppers, and onions.",
    "Add pizza sauce, oregano, chili flakes, salt, and pepper. Mix well.",
    "Spread this mixture evenly on bread slices.",
    "Roll each slice tightly and seal edges with water.",
    "Brush rolls with melted butter.",
    "Place on baking tray lined with parchment paper.",
    "Bake for 15-20 minutes until golden and crispy.",
    "Serve hot with tomato ketchup or garlic mayo."
  ],
  difficulty: "Easy",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Golden baked bread rolls stuffed with gooey cheese, sweet corn, and bell peppers – a perfect kid-friendly snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "standard",
  costPerServing: 30,
  baseServings: 4,
  calories: 220,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["bread slices", "mozzarella cheese", "cheddar cheese", "sweet corn", "bell peppers", "onion", "pizza sauce", "oregano"],
  searchKeywords: ["cheesy baked rolls", "baked cheese rolls", "cheese corn rolls", "oven baked snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Cheesy Gol Gappa Pakora",
  tagline: "Crispy gol gappa filled with spicy cheese mixture",
  image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "20 gol gappa puris (readymade)",
    "1 cup grated mozzarella cheese",
    "1/2 cup grated processed cheese",
    "1/4 cup finely chopped onions",
    "1/4 cup finely chopped tomatoes",
    "1 green chili, finely chopped",
    "2 tablespoons chopped coriander",
    "1 teaspoon chaat masala",
    "1/2 teaspoon red chili powder",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "Make a small hole in each gol gappa puri.",
    "In a bowl, mix both cheeses, onions, tomatoes, green chili, and coriander.",
    "Add chaat masala, red chili powder, and salt. Mix well.",
    "Carefully stuff this mixture into each gol gappa puri.",
    "Heat oil in a deep pan on medium heat.",
    "Fry stuffed gol gappas until golden brown and crispy.",
    "Drain on paper towels.",
    "Serve immediately with tamarind chutney and mint chutney.",
    "Garnish with sev and chopped coriander."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Fusion snack – crispy gol gappa puris stuffed with spicy cheese mixture, deep-fried to golden perfection.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "standard",
  costPerServing: 35,
  baseServings: 4,
  calories: 210,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["gol gappa puris", "mozzarella cheese", "processed cheese", "onion", "tomato", "green chili", "chaat masala"],
  searchKeywords: ["cheesy gol gappa pakora", "gol gappa snack", "fusion pakora", "cheese stuffed puri"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
{
  title: "Pizza Tots",
  tagline: "Crispy potato tots with pizza flavors",
  image: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "4 large potatoes, boiled and mashed",
    "1/2 cup grated mozzarella cheese",
    "1/4 cup pizza sauce",
    "1/4 cup finely chopped bell peppers",
    "1/4 cup finely chopped onions",
    "2 tablespoons sweet corn kernels",
    "1 teaspoon oregano",
    "1 teaspoon chili flakes",
    "1/2 cup breadcrumbs",
    "1/4 cup all-purpose flour",
    "1 egg, beaten",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "In a bowl, mix mashed potatoes with salt.",
    "Add pizza sauce, cheese, bell peppers, onions, and sweet corn.",
    "Mix in oregano and chili flakes.",
    "Take small portions and shape into round tater tots.",
    "Set up three bowls: flour, beaten egg, and breadcrumbs.",
    "Roll each tot in flour, then dip in egg, then coat with breadcrumbs.",
    "Heat oil in a deep pan on medium heat.",
    "Fry tots until golden brown and crispy.",
    "Drain on paper towels.",
    "Serve hot with pizza sauce or garlic mayo."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Crispy potato tots loaded with pizza flavors – cheese, pizza sauce, and veggies. A fun fusion snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy", "eggs", "gluten"],
  budget: "standard",
  costPerServing: 25,
  baseServings: 4,
  calories: 210,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["potatoes", "mozzarella cheese", "pizza sauce", "bell peppers", "onion", "sweet corn", "oregano", "breadcrumbs"],
  searchKeywords: ["pizza tots", "potato tots", "tater tots pizza", "crispy snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Tandoori Chai",
  tagline: "Smoked spiced tea with tandoori flavor",
  image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "4 cups water",
    "4 teaspoons black tea leaves",
    "4 cups milk",
    "8-10 cardamom pods, crushed",
    "2-3 cinnamon sticks",
    "4-5 cloves",
    "1/2 teaspoon ginger powder",
    "Sugar to taste",
    "Charcoal piece for smoking",
    "1 teaspoon ghee"
  ],
  stepsRaw: [
    "Boil water in a saucepan.",
    "Add tea leaves and all spices (cardamom, cinnamon, cloves, ginger).",
    "Simmer for 5 minutes until strong infusion.",
    "Add milk and sugar, bring to boil.",
    "Reduce heat and simmer for 5 more minutes.",
    "Strain into a metal or heat-proof container.",
    "Heat a charcoal piece until red hot.",
    "Place charcoal in a small metal bowl.",
    "Add 1 teaspoon ghee on the hot charcoal.",
    "Immediately place this bowl in the tea container.",
    "Cover immediately to trap the smoke.",
    "Let it smoke for 2-3 minutes.",
    "Remove charcoal bowl and serve hot."
  ],
  difficulty: "Medium",
  cookingTime: 20,
  isActive: true,
  isHalal: true,
  description: "Smoked spiced tea with a unique tandoori charcoal flavor – a rich, aromatic beverage.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "standard",
  costPerServing: 15,
  baseServings: 4,
  calories: 90,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["black tea", "milk", "cardamom", "cinnamon", "cloves", "ginger powder", "charcoal", "ghee"],
  searchKeywords: ["tandoori chai", "smoked tea", "spiced tea", "indian chai"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Special Falooda",
  tagline: "Layered dessert drink with ice cream and noodles",
  image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "1/2 cup falooda seeds (sabja/tukmaria)",
    "1/2 cup cooked vermicelli",
    "4 cups cold milk",
    "1/2 cup rose syrup",
    "1/2 cup mixed fruits (banana, mango, apple)",
    "4 scoops vanilla ice cream",
    "1/4 cup chopped nuts (pistachios, almonds)",
    "1/4 cup sweet basil seeds",
    "2 tablespoons sugar",
    "1 teaspoon cardamom powder"
  ],
  stepsRaw: [
    "Soak falooda seeds in water for 30 minutes, drain.",
    "Soak sweet basil seeds in water for 10 minutes, drain.",
    "Cook vermicelli according to package instructions, drain and cool.",
    "In a bowl, mix cold milk with sugar and cardamom powder.",
    "Chill this milk mixture in refrigerator.",
    "In tall glasses, add soaked falooda seeds as first layer.",
    "Add soaked basil seeds as second layer.",
    "Add cooked vermicelli as third layer.",
    "Add chopped mixed fruits as fourth layer.",
    "Pour rose syrup over the fruits.",
    "Fill glasses with chilled milk mixture.",
    "Top with a scoop of vanilla ice cream.",
    "Garnish with chopped nuts and serve immediately."
  ],
  difficulty: "Medium",
  cookingTime: 45,
  isActive: true,
  isHalal: true,
  description: "Layered dessert drink with falooda seeds, vermicelli, rose syrup, fruits, and ice cream – a royal treat.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy", "nuts"],
  budget: "standard",
  costPerServing: 45,
  baseServings: 4,
  calories: 250,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["falooda seeds", "vermicelli", "milk", "rose syrup", "mixed fruits", "vanilla ice cream", "nuts", "cardamom"],
  searchKeywords: ["special falooda", "falooda recipe", "layered dessert", "pakistani drink"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Pizza Pie",
  tagline: "Savory pie with pizza toppings and chicken",
  image: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
  cuisine: "Italian",
  ingredientsRaw: [
    "For crust: 2 cups all-purpose flour",
    "1 teaspoon instant yeast",
    "1 teaspoon sugar",
    "1/2 teaspoon salt",
    "1 tablespoon oil",
    "3/4 cup warm water",
    "For topping: 1 cup cooked chicken, shredded",
    "1 cup pizza sauce",
    "2 cups grated mozzarella cheese",
    "1/2 cup chopped bell peppers",
    "1/2 cup chopped onions",
    "1/4 cup sliced olives",
    "1 teaspoon oregano",
    "1 teaspoon chili flakes",
    "2 tablespoons butter, melted"
  ],
  stepsRaw: [
    "Mix yeast, sugar, and warm water, let sit for 5 minutes until foamy.",
    "In a bowl, mix flour and salt.",
    "Add yeast mixture and oil, knead into smooth dough.",
    "Cover and let rise for 1 hour until doubled.",
    "Preheat oven to 200°C (400°F).",
    "Punch down dough and roll to fit a pie dish.",
    "Place in greased pie dish, pressing up the sides.",
    "Spread pizza sauce evenly on the crust.",
    "Add shredded chicken as next layer.",
    "Sprinkle half the cheese.",
    "Add bell peppers, onions, and olives.",
    "Top with remaining cheese.",
    "Sprinkle oregano and chili flakes.",
    "Brush edges with melted butter.",
    "Bake for 20-25 minutes until golden brown.",
    "Let cool for 5 minutes before slicing."
  ],
  difficulty: "Hard",
  cookingTime: 90,
  isActive: true,
  isHalal: true,
  description: "Savory pie with a crispy pizza crust, loaded with chicken, cheese, and classic pizza toppings.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "standard",
  costPerServing: 55,
  baseServings: 4,
  calories: 420,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["all-purpose flour", "yeast", "chicken", "pizza sauce", "mozzarella cheese", "bell peppers", "onion", "olives", "oregano"],
  searchKeywords: ["chicken pizza pie", "pizza pie", "savory pie", "chicken pizza casserole"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Loaded Fries",
  tagline: "Crispy fries topped with cheese and toppings",
  image: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "4 large potatoes, cut into fries",
    "1 cup grated mozzarella cheese",
    "1/2 cup grated cheddar cheese",
    "1 cup cooked minced meat or beans",
    "1/2 cup chopped onions",
    "1/2 cup chopped tomatoes",
    "1/4 cup sliced jalapeños",
    "1/4 cup sour cream",
    "1/4 cup chopped spring onions",
    "2 tablespoons olive oil",
    "1 teaspoon paprika",
    "1 teaspoon garlic powder",
    "Salt to taste",
    "Black pepper to taste"
  ],
  stepsRaw: [
    "Preheat oven to 220°C (425°F).",
    "Toss potato fries with olive oil, paprika, garlic powder, salt, and pepper.",
    "Spread on baking tray in single layer.",
    "Bake for 25-30 minutes until crispy, turning halfway.",
    "Transfer fries to oven-proof serving dish.",
    "Spread cooked minced meat or beans over fries.",
    "Sprinkle both cheeses evenly.",
    "Add onions, tomatoes, and jalapeños.",
    "Return to oven for 5-7 minutes until cheese melts.",
    "Drizzle with sour cream.",
    "Garnish with spring onions.",
    "Serve immediately."
  ],
  difficulty: "Medium",
  cookingTime: 40,
  isActive: true,
  isHalal: true,
  description: "Crispy oven-baked fries loaded with cheese, beans, veggies, and sour cream – a shareable snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "standard",
  costPerServing: 28,
  baseServings: 4,
  calories: 290,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["potatoes", "mozzarella cheese", "cheddar cheese", "beans", "onions", "tomatoes", "jalapeños", "sour cream", "paprika"],
  searchKeywords: ["loaded fries", "cheese fries", "loaded potato fries", "snack fries"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},
  // 20-snacks.js - CONTINUED (Recipes 11-36)
  {
  title: "Potato Finger",
  tagline: "Crispy potato sticks with cheese filling",
  image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "4 large potatoes, boiled and mashed",
    "1/2 cup grated cheese",
    "2 green chilies, finely chopped",
    "2 tablespoons chopped coriander",
    "1 teaspoon chaat masala",
    "1/2 teaspoon red chili powder",
    "1/2 cup breadcrumbs",
    "1/4 cup all-purpose flour",
    "1 egg, beaten",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "In a bowl, mix mashed potatoes with salt.",
    "Add grated cheese, green chilies, and coriander.",
    "Mix in chaat masala and red chili powder.",
    "Take portions and shape into finger-like sticks.",
    "Set up three bowls: flour, beaten egg, and breadcrumbs.",
    "Roll each finger in flour, dip in egg, coat with breadcrumbs.",
    "Heat oil in a deep pan on medium heat.",
    "Fry potato fingers until golden brown and crispy.",
    "Drain on paper towels.",
    "Serve hot with ketchup or mint chutney."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Crispy potato sticks with a cheesy, spiced filling – a delicious finger-licking snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy", "eggs", "gluten"],
  budget: "standard",
  costPerServing: 18,
  baseServings: 4,
  calories: 210,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["potatoes", "grated cheese", "green chilies", "coriander", "chaat masala", "breadcrumbs", "flour", "egg"],
  searchKeywords: ["potato finger", "cheese potato sticks", "crispy potato snack", "finger food"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Thai Chicken Toast",
  tagline: "Crispy toast topped with Thai spiced chicken",
  image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "8 bread slices",
    "250g boneless chicken, minced",
    "1 egg",
    "2 tablespoons chopped spring onions",
    "1 tablespoon chopped coriander",
    "1 teaspoon ginger-garlic paste",
    "1 teaspoon soy sauce",
    "1 teaspoon chili sauce",
    "1/2 teaspoon black pepper",
    "1/2 cup breadcrumbs",
    "Oil for shallow frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "In a bowl, mix minced chicken, egg, spring onions, and coriander.",
    "Add ginger-garlic paste, soy sauce, chili sauce, black pepper, and salt.",
    "Mix well to form a smooth paste.",
    "Trim bread slices and spread chicken mixture evenly on each slice.",
    "Sprinkle breadcrumbs on top of chicken layer.",
    "Heat oil in a pan on medium heat.",
    "Place bread chicken-side down in oil.",
    "Fry for 3-4 minutes until golden brown.",
    "Flip and fry bread side for 1-2 minutes.",
    "Cut into triangles or squares.",
    "Serve hot with sweet chili sauce."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Crispy toast topped with Thai-spiced minced chicken – a flavorful, crunchy snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["eggs", "gluten", "soy"],
  budget: "standard",
  costPerServing: 35,
  baseServings: 4,
  calories: 250,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["bread", "minced chicken", "egg", "spring onions", "soy sauce", "chili sauce", "ginger-garlic paste", "breadcrumbs"],
  searchKeywords: ["thai chicken toast", "chicken toast", "crispy toast snack", "thai appetizer"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Fries",
  tagline: "Crispy chicken strips perfect for dipping",
  image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g chicken breast, cut into thin strips",
    "1 cup all-purpose flour",
    "1/2 cup corn flour",
    "1 teaspoon garlic powder",
    "1 teaspoon paprika",
    "1 teaspoon onion powder",
    "1/2 teaspoon black pepper",
    "1 egg",
    "1/2 cup milk",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "In a bowl, mix flour, corn flour, garlic powder, paprika, onion powder, and salt.",
    "In another bowl, whisk egg and milk together.",
    "Dip chicken strips in flour mixture, then egg mixture, then flour mixture again.",
    "Place on tray and let rest for 10 minutes.",
    "Heat oil in deep pan to 180°C (350°F).",
    "Fry chicken strips in batches until golden brown, about 4-5 minutes.",
    "Drain on paper towels.",
    "Season with additional salt and pepper if needed.",
    "Serve hot with dipping sauces."
  ],
  difficulty: "Easy",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Crispy, golden chicken strips with a crunchy coating – perfect for dipping in your favorite sauce.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["eggs", "gluten", "dairy"],
  budget: "standard",
  costPerServing: 40,
  baseServings: 4,
  calories: 280,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken breast", "all-purpose flour", "corn flour", "garlic powder", "paprika", "onion powder", "egg", "milk"],
  searchKeywords: ["chicken fries", "crispy chicken strips", "chicken fingers", "dipping snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Potato Cheese Bar",
  tagline: "Crispy potato bars with molten cheese center",
  image: "https://images.unsplash.com/photo-1563379091339-03246963d9d6",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "4 large potatoes, boiled and mashed",
    "1 cup grated mozzarella cheese",
    "1/2 cup grated cheddar cheese",
    "1/4 cup finely chopped onions",
    "1/4 cup finely chopped bell peppers",
    "2 green chilies, chopped",
    "2 tablespoons chopped coriander",
    "1 teaspoon chaat masala",
    "1/2 cup breadcrumbs",
    "1/4 cup all-purpose flour",
    "1 egg, beaten",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "In a bowl, mix mashed potatoes with salt.",
    "Add both cheeses, onions, bell peppers, green chilies, and coriander.",
    "Mix in chaat masala.",
    "Shape mixture into rectangular bars.",
    "Set up three bowls: flour, beaten egg, and breadcrumbs.",
    "Roll each bar in flour, dip in egg, coat with breadcrumbs.",
    "Heat oil in a deep pan on medium heat.",
    "Fry bars until golden brown and crispy.",
    "Drain on paper towels.",
    "Serve hot with ketchup or green chutney."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Crispy potato bars with a molten cheese center – an irresistible cheesy snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy", "eggs", "gluten"],
  budget: "standard",
  costPerServing: 25,
  baseServings: 4,
  calories: 260,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["potatoes", "mozzarella cheese", "cheddar cheese", "onions", "bell peppers", "green chilies", "chaat masala", "breadcrumbs"],
  searchKeywords: ["potato cheese bar", "cheese potato bars", "crispy cheese snack", "potato cheese sticks"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Popcorn Chicken",
  tagline: "Bite-sized crispy chicken nuggets",
  image: "https://images.unsplash.com/photo-1626074353765-517a681e40be",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g boneless chicken, cut into small bite-sized pieces",
    "1 cup all-purpose flour",
    "1/2 cup corn flour",
    "1 teaspoon garlic powder",
    "1 teaspoon onion powder",
    "1 teaspoon paprika",
    "1/2 teaspoon black pepper",
    "1/2 teaspoon baking powder",
    "1 egg",
    "1/2 cup buttermilk",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "In a bowl, mix flour, corn flour, garlic powder, onion powder, paprika, baking powder, and salt.",
    "In another bowl, whisk egg and buttermilk.",
    "Dip chicken pieces in flour mixture, then egg mixture, then flour mixture again.",
    "Place on tray and let rest for 15 minutes.",
    "Heat oil in deep pan to 180°C (350°F).",
    "Fry chicken pieces in batches until golden brown and crispy, about 3-4 minutes.",
    "Drain on paper towels.",
    "Toss with additional seasoning if desired.",
    "Serve hot with dipping sauces."
  ],
  difficulty: "Easy",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Bite-sized, crispy popcorn chicken – perfect for snacking, parties, or movie nights.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["eggs", "gluten", "dairy"],
  budget: "standard",
  costPerServing: 42,
  baseServings: 4,
  calories: 290,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken", "all-purpose flour", "corn flour", "garlic powder", "onion powder", "paprika", "egg", "buttermilk"],
  searchKeywords: ["popcorn chicken", "bite sized chicken", "crispy chicken bites", "snack chicken"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Fried Wonton",
  tagline: "Crispy wontons filled with spiced meat",
  image: "https://images.unsplash.com/photo-1563245372-f21724e3856d",
  cuisine: "Chinese",
  ingredientsRaw: [
    "20 wonton wrappers",
    "250g minced chicken or pork",
    "1/2 cup finely chopped cabbage",
    "1/4 cup finely chopped spring onions",
    "1 tablespoon soy sauce",
    "1 teaspoon ginger-garlic paste",
    "1 teaspoon sesame oil",
    "1/2 teaspoon white pepper",
    "Oil for frying",
    "Salt to taste",
    "Water for sealing"
  ],
  stepsRaw: [
    "In a bowl, mix minced meat, cabbage, and spring onions.",
    "Add soy sauce, ginger-garlic paste, sesame oil, white pepper, and salt.",
    "Mix well to combine.",
    "Place a wonton wrapper on palm, add 1 teaspoon filling in center.",
    "Wet edges with water, fold into triangle, press to seal.",
    "Bring two corners together, wet with water, and press to seal.",
    "Heat oil in deep pan to 180°C (350°F).",
    "Fry wontons in batches until golden brown, about 2-3 minutes.",
    "Drain on paper towels.",
    "Serve hot with sweet chili sauce or soy dipping sauce."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Crispy, golden wontons filled with spiced minced chicken – a classic Asian snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["gluten", "soy"],
  budget: "standard",
  costPerServing: 38,
  baseServings: 4,
  calories: 220,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["wonton wrappers", "minced chicken", "cabbage", "spring onions", "soy sauce", "ginger-garlic paste", "sesame oil", "white pepper"],
  searchKeywords: ["fried wonton", "crispy wonton", "chicken wonton", "chinese snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Bread Pizza",
  tagline: "Quick mini pizzas on bread base",
  image: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
  cuisine: "Italian",
  ingredientsRaw: [
    "8 bread slices",
    "1 cup pizza sauce",
    "2 cups grated mozzarella cheese",
    "1/2 cup chopped bell peppers",
    "1/2 cup chopped onions",
    "1/4 cup sweet corn kernels",
    "1/4 cup sliced olives",
    "1 teaspoon oregano",
    "1 teaspoon chili flakes",
    "2 tablespoons butter",
    "Salt to taste",
    "Black pepper to taste"
  ],
  stepsRaw: [
    "Preheat oven to 200°C (400°F).",
    "Butter one side of each bread slice.",
    "Place buttered side down on baking tray.",
    "Spread pizza sauce on each slice.",
    "Sprinkle cheese evenly.",
    "Add bell peppers, onions, sweet corn, and olives.",
    "Season with salt, pepper, oregano, and chili flakes.",
    "Bake for 8-10 minutes until cheese melts and edges are crispy.",
    "Serve immediately."
  ],
  difficulty: "Easy",
  cookingTime: 15,
  isActive: true,
  isHalal: true,
  description: "Quick mini pizzas on a crispy bread base – perfect for a fast, tasty snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "standard",
  costPerServing: 20,
  baseServings: 4,
  calories: 190,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["bread", "pizza sauce", "mozzarella cheese", "bell peppers", "onions", "sweet corn", "olives", "oregano"],
  searchKeywords: ["bread pizza", "mini pizza", "quick pizza snack", "oven pizza bread"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Cheese Sandwich",
  tagline: "Grilled sandwich with chicken and melted cheese",
  image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "8 bread slices",
    "2 cups cooked chicken, shredded",
    "1 cup grated mozzarella cheese",
    "1/2 cup mayonnaise",
    "1/4 cup finely chopped onions",
    "1/4 cup finely chopped bell peppers",
    "2 tablespoons butter",
    "1 teaspoon black pepper",
    "1/2 teaspoon garlic powder",
    "Salt to taste"
  ],
  stepsRaw: [
    "In a bowl, mix shredded chicken with mayonnaise.",
    "Add onions, bell peppers, black pepper, garlic powder, and salt.",
    "Mix well to combine.",
    "Butter one side of each bread slice.",
    "Place 4 slices buttered side down.",
    "Spread chicken mixture evenly.",
    "Sprinkle cheese on top.",
    "Cover with remaining bread slices, buttered side up.",
    "Heat a griddle or pan, place sandwiches.",
    "Grill until golden brown on both sides, pressing gently.",
    "Cut diagonally and serve hot."
  ],
  difficulty: "Easy",
  cookingTime: 15,
  isActive: true,
  isHalal: true,
  description: "Grilled sandwich loaded with creamy shredded chicken and melted mozzarella – a hearty, satisfying snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy", "eggs", "gluten"],
  budget: "standard",
  costPerServing: 35,
  baseServings: 4,
  calories: 340,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["bread", "cooked chicken", "mozzarella cheese", "mayonnaise", "onions", "bell peppers", "butter", "garlic powder"],
  searchKeywords: ["chicken cheese sandwich", "grilled chicken sandwich", "cheesy chicken sandwich", "quick snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Dynamite Chicken",
  tagline: "Spicy glazed chicken with creamy sauce",
  image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g boneless chicken, cut into strips",
    "1/2 cup mayonnaise",
    "1/4 cup sweet chili sauce",
    "2 tablespoons Sriracha sauce",
    "1 tablespoon honey",
    "1 teaspoon garlic powder",
    "1 cup all-purpose flour",
    "1/2 cup corn flour",
    "1 teaspoon paprika",
    "Oil for frying",
    "Salt to taste",
    "Spring onions for garnish"
  ],
  stepsRaw: [
    "In a bowl, mix mayonnaise, sweet chili sauce, Sriracha, honey, and garlic powder for sauce.",
    "In another bowl, mix flour, corn flour, paprika, and salt.",
    "Coat chicken strips in flour mixture.",
    "Heat oil in deep pan to 180°C (350°F).",
    "Fry chicken strips until golden brown and cooked through, about 5-6 minutes.",
    "Drain on paper towels.",
    "Toss fried chicken in prepared sauce until well coated.",
    "Garnish with chopped spring onions.",
    "Serve immediately."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Spicy, sticky glazed chicken strips with a creamy, fiery sauce – a bold and addictive snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["eggs", "gluten"],
  budget: "standard",
  costPerServing: 48,
  baseServings: 4,
  calories: 380,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken", "mayonnaise", "sweet chili sauce", "sriracha", "honey", "garlic powder", "flour", "corn flour", "paprika"],
  searchKeywords: ["dynamite chicken", "spicy chicken", "glazed chicken", "fusion snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Namak Paray",
  tagline: "Crispy savory fried crackers",
  image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "2 cups all-purpose flour",
    "1/2 cup semolina (suji)",
    "1/2 cup ghee or oil",
    "1 teaspoon carom seeds (ajwain)",
    "1 teaspoon black pepper powder",
    "1/2 teaspoon baking powder",
    "Water as needed",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "In a bowl, mix flour, semolina, carom seeds, black pepper, baking powder, and salt.",
    "Add ghee or oil and rub into flour until crumbly.",
    "Gradually add water to form stiff dough.",
    "Cover and rest for 30 minutes.",
    "Divide dough into small balls.",
    "Roll each ball into thin round paratha.",
    "Prick all over with fork to prevent puffing.",
    "Heat oil in deep pan on medium heat.",
    "Fry paray until golden brown and crispy, about 2 minutes per side.",
    "Drain on paper towels.",
    "Cool completely before storing in airtight container."
  ],
  difficulty: "Medium",
  cookingTime: 50,
  isActive: true,
  isHalal: true,
  description: "Crispy, savory fried crackers flavored with carom seeds and black pepper – a classic Pakistani tea-time snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "standard",
  costPerServing: 10,
  baseServings: 6,
  calories: 120,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["all-purpose flour", "semolina", "ghee", "carom seeds", "black pepper", "baking powder"],
  searchKeywords: ["namak paray", "namak pare", "crispy crackers", "pakistani snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Fritters",
  tagline: "Flattened chicken patties with spices",
  image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "500g boneless chicken, minced",
    "1 onion, finely chopped",
    "2 green chilies, finely chopped",
    "2 tablespoons chopped coriander",
    "1 teaspoon ginger-garlic paste",
    "1 teaspoon garam masala",
    "1/2 teaspoon red chili powder",
    "1/2 teaspoon turmeric powder",
    "1 egg",
    "2 tablespoons gram flour (besan)",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "In a bowl, mix minced chicken with onion, green chilies, and coriander.",
    "Add ginger-garlic paste and all spices.",
    "Add egg and gram flour, mix well to combine.",
    "Take small portions and shape into flat patties.",
    "Heat oil in a pan on medium heat.",
    "Shallow fry fritters until golden brown on both sides, about 4-5 minutes per side.",
    "Drain on paper towels.",
    "Serve hot with mint chutney or ketchup."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Flattened, spiced minced chicken patties shallow-fried to golden perfection – a flavorful Pakistani snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["eggs", "gluten"],
  budget: "standard",
  costPerServing: 38,
  baseServings: 4,
  calories: 270,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken mince", "onion", "green chilies", "coriander", "ginger-garlic paste", "garam masala", "egg", "gram flour"],
  searchKeywords: ["chicken fritters", "chicken patties", "pakistani chicken snack", "minced chicken fritters"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Butterfly Chicken",
  tagline: "Butterflied breaded chicken breast",
  image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58",
  cuisine: "Italian",
  ingredientsRaw: [
    "4 chicken breasts",
    "1 cup all-purpose flour",
    "2 eggs, beaten",
    "1 cup breadcrumbs",
    "1 teaspoon garlic powder",
    "1 teaspoon paprika",
    "1/2 teaspoon black pepper",
    "Oil for frying",
    "Salt to taste",
    "Lemon wedges for serving"
  ],
  stepsRaw: [
    "Butterfly chicken breasts: slice horizontally through center, but not all the way through.",
    "Open like a book and pound to even thickness.",
    "Season both sides with salt, pepper, garlic powder, and paprika.",
    "Set up three bowls: flour, beaten eggs, breadcrumbs.",
    "Dredge chicken in flour, dip in egg, coat with breadcrumbs.",
    "Press breadcrumbs firmly to adhere.",
    "Heat oil in deep pan to 180°C (350°F).",
    "Fry chicken until golden brown and cooked through, about 5-6 minutes per side.",
    "Drain on paper towels.",
    "Serve hot with lemon wedges and dipping sauces."
  ],
  difficulty: "Medium",
  cookingTime: 30,
  isActive: true,
  isHalal: true,
  description: "Butterflied, breaded chicken breast fried to crispy perfection – a satisfying, juicy snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["eggs", "gluten"],
  budget: "standard",
  costPerServing: 50,
  baseServings: 4,
  calories: 390,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken breasts", "flour", "eggs", "breadcrumbs", "garlic powder", "paprika", "black pepper"],
  searchKeywords: ["butterfly chicken", "breaded chicken breast", "crispy chicken", "fried chicken snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Veggie Pancakes",
  tagline: "Savory vegetable pancakes with gram flour",
  image: "https://images.unsplash.com/photo-1563245372-f21724e3856d",
  cuisine: "Italian",
  ingredientsRaw: [
    "1 cup gram flour (besan)",
    "1/2 cup rice flour",
    "1 onion, finely chopped",
    "1 tomato, finely chopped",
    "1/2 cup grated carrots",
    "1/2 cup chopped spinach",
    "2 green chilies, chopped",
    "2 tablespoons chopped coriander",
    "1 teaspoon ginger paste",
    "1/2 teaspoon turmeric powder",
    "1/2 teaspoon baking soda",
    "Water as needed",
    "Oil for cooking",
    "Salt to taste"
  ],
  stepsRaw: [
    "In a bowl, mix gram flour and rice flour.",
    "Add all vegetables, green chilies, and coriander.",
    "Add ginger paste, turmeric, baking soda, and salt.",
    "Gradually add water to make medium-thick batter.",
    "Let batter rest for 10 minutes.",
    "Heat a non-stick pan, add few drops of oil.",
    "Pour ladleful of batter, spread into round pancake.",
    "Cook on medium heat until golden brown, about 2-3 minutes.",
    "Flip and cook other side until golden.",
    "Repeat with remaining batter.",
    "Serve hot with chutney or ketchup."
  ],
  difficulty: "Easy",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Savory gram flour pancakes packed with vegetables – a healthy, protein-rich snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 15,
  baseServings: 4,
  calories: 130,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["gram flour", "rice flour", "onion", "tomato", "carrots", "spinach", "green chilies", "ginger paste", "turmeric"],
  searchKeywords: ["veggie pancakes", "savory pancakes", "gram flour pancakes", "besan cheela"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Apple Banana Muffins",
  tagline: "Moist muffins with apple and banana",
  image: "https://images.unsplash.com/photo-1603532648955-039310d9ed75",
  cuisine: "Italian",
  ingredientsRaw: [
    "1 1/2 cups all-purpose flour",
    "1 teaspoon baking powder",
    "1/2 teaspoon baking soda",
    "1/2 teaspoon cinnamon powder",
    "1/4 teaspoon nutmeg powder",
    "2 ripe bananas, mashed",
    "1 apple, peeled and grated",
    "1/2 cup sugar",
    "1/3 cup vegetable oil",
    "1 egg",
    "1 teaspoon vanilla extract",
    "1/4 cup chopped walnuts (optional)"
  ],
  stepsRaw: [
    "Preheat oven to 180°C (350°F). Line muffin tin with paper liners.",
    "In a bowl, whisk flour, baking powder, baking soda, cinnamon, and nutmeg.",
    "In another bowl, mix mashed bananas and grated apple.",
    "Add sugar, oil, egg, and vanilla extract. Mix well.",
    "Add dry ingredients to wet ingredients, mix until just combined.",
    "Fold in chopped walnuts if using.",
    "Divide batter among muffin cups, filling 2/3 full.",
    "Bake for 20-25 minutes until toothpick comes out clean.",
    "Cool in pan for 5 minutes, then transfer to wire rack.",
    "Serve warm or at room temperature."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Moist, fluffy muffins packed with mashed banana and grated apple – a naturally sweet baked snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["eggs", "gluten", "nuts"],
  budget: "standard",
  costPerServing: 22,
  baseServings: 6,
  calories: 210,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["flour", "bananas", "apple", "sugar", "oil", "egg", "vanilla", "cinnamon", "walnuts"],
  searchKeywords: ["apple banana muffins", "fruit muffins", "healthy snack", "baked snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Corn Chaat",
  tagline: "Spicy and tangy corn salad",
  image: "https://images.unsplash.com/photo-1563245372-f21724e3856d",
  cuisine: "Italian",
  ingredientsRaw: [
    "2 cups corn kernels (fresh or frozen)",
    "1 onion, finely chopped",
    "1 tomato, finely chopped",
    "1 green chili, finely chopped",
    "2 tablespoons chopped coriander",
    "1 teaspoon chaat masala",
    "1/2 teaspoon red chili powder",
    "1/2 teaspoon roasted cumin powder",
    "1 tablespoon lemon juice",
    "1 tablespoon sev for garnish",
    "Salt to taste"
  ],
  stepsRaw: [
    "Boil corn kernels in salted water until tender, about 5-7 minutes. Drain.",
    "In a bowl, mix boiled corn with onion, tomato, and green chili.",
    "Add chaat masala, red chili powder, cumin powder, and salt.",
    "Add lemon juice and mix well.",
    "Garnish with chopped coriander and sev.",
    "Serve immediately as a snack.",
    "Optionally, add boiled potatoes or pomegranate seeds for variation."
  ],
  difficulty: "Easy",
  cookingTime: 10,
  isActive: true,
  isHalal: true,
  description: "Spicy, tangy corn salad with chaat masala, lemon, and crunchy sev – a refreshing, quick snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: [],
  budget: "standard",
  costPerServing: 12,
  baseServings: 4,
  calories: 90,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["corn kernels", "onion", "tomato", "green chili", "chaat masala", "cumin powder", "lemon", "sev"],
  searchKeywords: ["corn chaat", "spicy corn", "tangy corn salad", "indian snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Granola Bars",
  tagline: "Homemade healthy snack bars",
  image: "https://images.unsplash.com/photo-1540713434306-58505cf1b6fc",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "2 cups rolled oats",
    "1 cup mixed nuts (almonds, walnuts, cashews), chopped",
    "1/2 cup dried fruits (raisins, cranberries, apricots)",
    "1/4 cup honey",
    "1/4 cup peanut butter",
    "2 tablespoons coconut oil",
    "1 teaspoon vanilla extract",
    "1/2 teaspoon cinnamon powder",
    "Pinch of salt"
  ],
  stepsRaw: [
    "Preheat oven to 160°C (325°F). Line baking pan with parchment paper.",
    "Spread oats and nuts on baking tray, toast for 10 minutes until fragrant.",
    "In saucepan, heat honey, peanut butter, and coconut oil until melted and smooth.",
    "Remove from heat, add vanilla extract, cinnamon, and salt.",
    "In large bowl, mix toasted oats, nuts, and dried fruits.",
    "Pour honey mixture over dry ingredients, mix until well coated.",
    "Press mixture firmly into prepared pan.",
    "Bake for 20-25 minutes until golden brown.",
    "Cool completely in pan before cutting into bars.",
    "Store in airtight container."
  ],
  difficulty: "Medium",
  cookingTime: 40,
  isActive: true,
  isHalal: true,
  description: "Homemade healthy granola bars with oats, nuts, dried fruits, and honey – a perfect on-the-go snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["nuts"],
  budget: "standard",
  costPerServing: 18,
  baseServings: 8,
  calories: 180,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["rolled oats", "mixed nuts", "dried fruits", "honey", "peanut butter", "coconut oil", "cinnamon"],
  searchKeywords: ["granola bars", "homemade granola", "healthy snack bars", "oat bars"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Chicken Samosa",
  tagline: "Crispy triangular pastry with chicken filling",
  image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "For dough: 2 cups all-purpose flour",
    "1/4 cup oil",
    "1/2 teaspoon salt",
    "Water as needed",
    "For filling: 250g minced chicken",
    "1 onion, finely chopped",
    "1 teaspoon ginger-garlic paste",
    "1 green chili, chopped",
    "1/2 teaspoon garam masala",
    "1/2 teaspoon coriander powder",
    "1/4 teaspoon turmeric powder",
    "2 tablespoons chopped coriander",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "Make dough: Mix flour, salt, and oil until crumbly.",
    "Add water gradually to form stiff dough. Rest for 30 minutes.",
    "For filling: Heat oil, sauté onions until golden.",
    "Add ginger-garlic paste and green chili, sauté for 1 minute.",
    "Add minced chicken, cook until browned.",
    "Add all spices and salt, cook for 5-7 minutes.",
    "Add coriander, mix well. Let filling cool.",
    "Divide dough into small balls, roll into thin circles.",
    "Cut each circle in half to form semicircles.",
    "Form cone shape with semicircle, fill with chicken mixture.",
    "Seal edges with water, press firmly.",
    "Heat oil in deep pan, fry samosas until golden brown.",
    "Drain on paper towels, serve hot with chutney."
  ],
  difficulty: "Hard",
  cookingTime: 60,
  isActive: true,
  isHalal: true,
  description: "Crispy, flaky triangular samosas filled with spiced minced chicken – a popular Pakistani snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "standard",
  costPerServing: 30,
  baseServings: 4,
  calories: 310,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["all-purpose flour", "minced chicken", "onion", "ginger-garlic paste", "garam masala", "coriander powder", "turmeric"],
  searchKeywords: ["chicken samosa", "keema samosa", "crispy samosa", "pakistani snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Mat Samosa",
  tagline: "Classic samosa with spiced pea filling",
  image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
  cuisine: "Italian",
  ingredientsRaw: [
    "For dough: 2 cups all-purpose flour",
    "1/4 cup oil",
    "1/2 teaspoon salt",
    "Water as needed",
    "For filling: 1 cup dried yellow peas (matar), soaked overnight",
    "1 onion, finely chopped",
    "1 teaspoon ginger paste",
    "1 green chili, chopped",
    "1/2 teaspoon garam masala",
    "1/2 teaspoon amchur powder",
    "1/4 teaspoon turmeric powder",
    "2 tablespoons chopped coriander",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "Boil soaked peas until tender, drain and coarsely mash.",
    "Make dough: Mix flour, salt, and oil, add water to form stiff dough. Rest 30 minutes.",
    "Heat oil, sauté onions until golden.",
    "Add ginger paste and green chili, sauté for 1 minute.",
    "Add mashed peas, cook for 5 minutes.",
    "Add all spices and salt, mix well.",
    "Add coriander, remove from heat. Let filling cool.",
    "Divide dough into small balls, roll into thin circles.",
    "Cut each circle in half to form semicircles.",
    "Form cone shape, fill with pea mixture.",
    "Seal edges with water, press firmly.",
    "Heat oil in deep pan, fry samosas until golden brown.",
    "Drain on paper towels, serve hot with chutney."
  ],
  difficulty: "Hard",
  cookingTime: 60,
  isActive: true,
  isHalal: true,
  description: "Classic Indian samosa with a hearty, spiced yellow pea filling – a vegetarian favorite.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "standard",
  costPerServing: 20,
  baseServings: 4,
  calories: 260,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["all-purpose flour", "dried yellow peas", "onion", "ginger paste", "garam masala", "amchur powder", "turmeric"],
  searchKeywords: ["mat samosa", "pea samosa", "vegetarian samosa", "indian snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Easy Pinwheel Sandwich",
  tagline: "Colorful rolled sandwiches perfect for parties",
  image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184",
  cuisine: "Italian",
  ingredientsRaw: [
    "8 bread slices",
    "1 cup cream cheese",
    "1/2 cup grated carrots",
    "1/2 cup finely chopped bell peppers",
    "1/4 cup finely chopped spring onions",
    "2 tablespoons chopped coriander",
    "1 teaspoon black pepper",
    "1/2 teaspoon chaat masala",
    "Salt to taste"
  ],
  stepsRaw: [
    "Trim crusts from bread slices.",
    "Flatten each slice with rolling pin.",
    "In a bowl, mix cream cheese with all vegetables.",
    "Add black pepper, chaat masala, and salt.",
    "Spread mixture evenly on bread slices.",
    "Roll each slice tightly from one end.",
    "Wrap in plastic wrap and refrigerate for 30 minutes.",
    "Slice into 1-inch thick pinwheels.",
    "Serve chilled or at room temperature.",
    "Optionally, add ham or chicken slices for non-vegetarian version."
  ],
  difficulty: "Easy",
  cookingTime: 45,
  isActive: true,
  isHalal: true,
  description: "Colorful, creamy rolled sandwiches filled with fresh veggies – perfect for parties and gatherings.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "standard",
  costPerServing: 18,
  baseServings: 4,
  calories: 190,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["bread", "cream cheese", "carrots", "bell peppers", "spring onions", "coriander", "chaat masala"],
  searchKeywords: ["pinwheel sandwich", "rolled sandwich", "party snack", "easy appetizer"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Potato Fritters with Schezwan Sauce",
  tagline: "Crispy potato patties with spicy Schezwan dip",
  image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
  cuisine: "Chinese",
  ingredientsRaw: [
    "4 large potatoes, boiled and mashed",
    "1 onion, finely chopped",
    "2 green chilies, chopped",
    "2 tablespoons chopped coriander",
    "1 teaspoon ginger paste",
    "1/2 teaspoon red chili powder",
    "1/2 teaspoon garam masala",
    "1/2 cup breadcrumbs",
    "Oil for frying",
    "Salt to taste",
    "For Schezwan sauce: 4-5 dry red chilies",
    "4-5 garlic cloves",
    "1 tablespoon soy sauce",
    "1 tablespoon vinegar",
    "1 teaspoon sugar"
  ],
  stepsRaw: [
    "Make fritters: Mix mashed potatoes with onion, green chilies, coriander, ginger, and spices.",
    "Shape into small patties, coat with breadcrumbs.",
    "Heat oil, fry until golden brown. Drain on paper towels.",
    "Make Schezwan sauce: Soak red chilies in hot water for 30 minutes.",
    "Blend chilies and garlic into smooth paste.",
    "Heat 2 tablespoons oil, add paste, cook for 2 minutes.",
    "Add soy sauce, vinegar, sugar, and salt. Cook for 2 more minutes.",
    "Serve potato fritters hot with Schezwan sauce for dipping."
  ],
  difficulty: "Medium",
  cookingTime: 40,
  isActive: true,
  isHalal: true,
  description: "Crispy potato patties served with a fiery homemade Schezwan sauce – an Indo-Chinese fusion snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["soy", "gluten"],
  budget: "standard",
  costPerServing: 22,
  baseServings: 4,
  calories: 210,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["potatoes", "breadcrumbs", "red chilies", "garlic", "soy sauce", "vinegar"],
  searchKeywords: ["potato fritters", "schezwan sauce", "crispy potato patties", "indo chinese snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Corn Croquettes",
  tagline: "Crispy corn and potato rolls",
  image: "https://images.unsplash.com/photo-1563245372-f21724e3856d",
  cuisine: "Italian",
  ingredientsRaw: [
    "2 cups corn kernels (fresh or frozen)",
    "2 potatoes, boiled and mashed",
    "1 onion, finely chopped",
    "2 green chilies, chopped",
    "2 tablespoons chopped coriander",
    "1/2 teaspoon garam masala",
    "1/2 teaspoon red chili powder",
    "1/2 cup breadcrumbs",
    "1/4 cup all-purpose flour",
    "1 egg, beaten",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "Boil corn kernels until tender, drain and coarsely crush.",
    "Mix crushed corn with mashed potatoes.",
    "Add onion, green chilies, coriander, and spices. Mix well.",
    "Take portions and shape into cylindrical croquettes.",
    "Set up three bowls: flour, beaten egg, breadcrumbs.",
    "Roll croquettes in flour, dip in egg, coat with breadcrumbs.",
    "Heat oil in deep pan, fry until golden brown.",
    "Drain on paper towels.",
    "Serve hot with ketchup or green chutney."
  ],
  difficulty: "Medium",
  cookingTime: 35,
  isActive: true,
  isHalal: true,
  description: "Crispy corn and potato croquettes with a crunchy breadcrumb coating – a delightful vegetarian snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["eggs", "gluten"],
  budget: "standard",
  costPerServing: 20,
  baseServings: 4,
  calories: 190,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["corn kernels", "potatoes", "breadcrumbs", "flour", "egg", "garam masala"],
  searchKeywords: ["corn croquettes", "crispy corn rolls", "potato corn snack", "vegetarian croquettes"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Tangri Kebab",
  tagline: "Spicy grilled chicken drumsticks",
  image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "8 chicken drumsticks",
    "1 cup yogurt",
    "2 tablespoons ginger-garlic paste",
    "1 tablespoon lemon juice",
    "1 tablespoon kasuri methi",
    "1 teaspoon red chili powder",
    "1 teaspoon garam masala",
    "1/2 teaspoon turmeric powder",
    "1/2 teaspoon black pepper",
    "2 tablespoons oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Make deep slits in chicken drumsticks.",
    "In a bowl, mix yogurt with all spices, lemon juice, and oil.",
    "Add chicken to marinade, coat well.",
    "Cover and refrigerate for at least 4 hours or overnight.",
    "Preheat oven to 200°C (400°F).",
    "Place drumsticks on baking tray lined with foil.",
    "Bake for 25-30 minutes, turning halfway.",
    "Brush with oil or butter during baking.",
    "Broil for 2-3 minutes for charred effect.",
    "Serve hot with mint chutney and onion rings."
  ],
  difficulty: "Medium",
  cookingTime: 45,
  isActive: true,
  isHalal: true,
  description: "Spicy, yogurt-marinated grilled chicken drumsticks – a classic Pakistani kebab with smoky flavor.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy"],
  budget: "standard",
  costPerServing: 55,
  baseServings: 4,
  calories: 350,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken drumsticks", "yogurt", "ginger-garlic paste", "kasuri methi", "garam masala", "lemon"],
  searchKeywords: ["tangri kebab", "chicken drumstick kebab", "grilled chicken", "pakistani kebab"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Pizza Cone",
  tagline: "Fun pizza in a cone shape",
  image: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
  cuisine: "Italian",
  ingredientsRaw: [
    "1 cup all-purpose flour",
    "1/2 teaspoon instant yeast",
    "1/2 teaspoon sugar",
    "1/4 teaspoon salt",
    "1 tablespoon oil",
    "1/3 cup warm water",
    "1 cup pizza sauce",
    "1 1/2 cups grated mozzarella cheese",
    "1/2 cup chopped bell peppers",
    "1/2 cup chopped onions",
    "1/4 cup sliced olives",
    "1 teaspoon oregano",
    "1 teaspoon chili flakes"
  ],
  stepsRaw: [
    "Mix yeast, sugar, and warm water, let sit for 5 minutes.",
    "Mix flour and salt, add yeast mixture and oil, knead into soft dough.",
    "Cover and let rise for 1 hour.",
    "Preheat oven to 200°C (400°F). Grease cone molds.",
    "Divide dough into small balls, roll into circles.",
    "Place dough circles in cone molds, pressing to shape.",
    "Spread pizza sauce inside cones.",
    "Add cheese and toppings.",
    "Sprinkle oregano and chili flakes.",
    "Bake for 12-15 minutes until golden.",
    "Remove from molds, serve hot."
  ],
  difficulty: "Hard",
  cookingTime: 90,
  isActive: true,
  isHalal: true,
  description: "Fun, portable pizza in a cone shape – crispy crust filled with sauce, cheese, and toppings.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["dairy", "gluten"],
  budget: "standard",
  costPerServing: 35,
  baseServings: 4,
  calories: 310,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["all-purpose flour", "yeast", "pizza sauce", "mozzarella cheese", "bell peppers", "onions", "olives"],
  searchKeywords: ["pizza cone", "cone pizza", "fun snack", "handheld pizza"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Easy Chicken Drumsticks",
  tagline: "Simple oven-baked chicken drumsticks",
  image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58",
  cuisine: "Italian",
  ingredientsRaw: [
    "8 chicken drumsticks",
    "1/4 cup soy sauce",
    "2 tablespoons honey",
    "2 tablespoons ketchup",
    "1 tablespoon ginger-garlic paste",
    "1 teaspoon paprika",
    "1/2 teaspoon black pepper",
    "2 tablespoons oil",
    "Salt to taste"
  ],
  stepsRaw: [
    "Make slits in chicken drumsticks for even cooking.",
    "In a bowl, mix soy sauce, honey, ketchup, ginger-garlic paste, paprika, pepper, and salt.",
    "Marinate chicken in this mixture for at least 1 hour.",
    "Preheat oven to 200°C (400°F).",
    "Place drumsticks on baking tray lined with foil.",
    "Brush with oil.",
    "Bake for 25-30 minutes, turning halfway.",
    "Brush with remaining marinade during baking.",
    "Broil for 2-3 minutes for glaze.",
    "Serve hot with dipping sauce."
  ],
  difficulty: "Easy",
  cookingTime: 40,
  isActive: true,
  isHalal: true,
  description: "Simple, oven-baked chicken drumsticks with a sticky honey-soy glaze – a quick, crowd-pleasing snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Non-Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["soy"],
  budget: "standard",
  costPerServing: 48,
  baseServings: 4,
  calories: 320,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["chicken drumsticks", "soy sauce", "honey", "ketchup", "ginger-garlic paste", "paprika"],
  searchKeywords: ["easy chicken drumsticks", "oven baked chicken", "honey soy chicken", "simple snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Khaja",
  tagline: "Sweet crispy fried pastry in sugar syrup",
  image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b",
  cuisine: "Italian",
  ingredientsRaw: [
    "2 cups all-purpose flour",
    "1/4 cup ghee",
    "Water as needed",
    "1 cup sugar",
    "1/2 cup water for syrup",
    "4-5 cardamom pods, crushed",
    "Oil for frying",
    "Pinch of salt"
  ],
  stepsRaw: [
    "Make dough: Mix flour, salt, and ghee until crumbly.",
    "Add water gradually to form stiff dough. Rest for 30 minutes.",
    "Make syrup: Boil sugar, water, and cardamom until one-string consistency.",
    "Divide dough into small balls, roll into thin circles.",
    "Fold each circle into half, then half again to form triangle.",
    "Roll triangle slightly to seal edges.",
    "Heat oil in deep pan on medium heat.",
    "Fry khaja until light golden brown.",
    "Drain and immediately dip in warm syrup for 1 minute.",
    "Remove from syrup, place on wire rack to dry.",
    "Store in airtight container when completely cooled."
  ],
  difficulty: "Hard",
  cookingTime: 60,
  isActive: true,
  isHalal: true,
  description: "Sweet, crispy layered pastry soaked in cardamom-infused sugar syrup – a traditional Indian sweet snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "standard",
  costPerServing: 15,
  baseServings: 6,
  calories: 160,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["all-purpose flour", "ghee", "sugar", "cardamom"],
  searchKeywords: ["khaja", "sweet pastry", "indian sweet snack", "crispy sugar syrup"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
},{
  title: "Noodles Pakora",
  tagline: "Crispy fritters made with instant noodles",
  image: "https://images.unsplash.com/photo-1563245372-f21724e3856d",
  cuisine: "Pakistani",
  ingredientsRaw: [
    "2 packets instant noodles",
    "1 cup gram flour (besan)",
    "1/4 cup rice flour",
    "1 onion, finely chopped",
    "2 green chilies, chopped",
    "2 tablespoons chopped coriander",
    "1 teaspoon ginger paste",
    "1/2 teaspoon red chili powder",
    "1/2 teaspoon garam masala",
    "Water as needed",
    "Oil for frying",
    "Salt to taste"
  ],
  stepsRaw: [
    "Cook noodles according to package instructions, drain and cool.",
    "Chop cooked noodles into smaller pieces.",
    "In a bowl, mix gram flour and rice flour.",
    "Add chopped noodles, onion, green chilies, coriander, and ginger paste.",
    "Add all spices and salt.",
    "Gradually add water to make thick batter.",
    "Heat oil in deep pan on medium heat.",
    "Drop spoonfuls of batter into hot oil.",
    "Fry until golden brown and crispy, about 3-4 minutes.",
    "Drain on paper towels.",
    "Serve hot with ketchup or chutney."
  ],
  difficulty: "Medium",
  cookingTime: 25,
  isActive: true,
  isHalal: true,
  description: "Crispy, fusion fritters made with instant noodles and gram flour – a unique, crunchy snack.",
  category: "Snacks",
  subCategory: "snacks",
  dietType: "Vegetarian",
  suitableForMeals: ["Snack"],
  beverageCategory: null,
  allergens: ["gluten"],
  budget: "standard",
  costPerServing: 16,
  baseServings: 4,
  calories: 180,
  ageGroup: ["adults", "teens", "kids"],
  patientFriendly: ["general"],
  pantryKeywords: ["instant noodles", "gram flour", "rice flour", "onion", "green chilies", "garam masala"],
  searchKeywords: ["noodles pakora", "noodle fritters", "fusion pakora", "crispy noodle snack"],
  isFeatured: false,
  averageRating: 0,
  totalRatings: 0,
  timesSuggested: 0,
  timesUsedInPlans: 0
}
];



async function migrate() {
  try {
    console.log('🔌 Connecting to MongoDB...');
const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.MONGOURI;
if (!mongoURI) throw new Error('MongoDB URI not found');
await mongoose.connect(mongoURI, { serverSelectionTimeoutMS: 10000, family: 4 });   
 console.log('✅ Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (let recipe of recipesToMigrate) {
      const existing = await Recipe.findOne({ title: recipe.title });
      if (!existing) {
        await Recipe.create(recipe);
        console.log(`✅ Added: ${recipe.title}`);
        added++;
      } else {
        console.log(`⚠️ Skipped: ${recipe.title} (already exists)`);
        skipped++;
      }
    }

    console.log('\n🎉 Migration Complete!');
    console.log(`📊 Added: ${added}, Skipped: ${skipped}`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

migrate();